### ISSUE TITLE
Separate front matter from templates.

### ISSUE THREAD

**Issue by YashJipkate** [11ty/eleventy#1009]
I have a situation wherein it is required that I should not include the front matter in the template. In other words, the content files should be completely free of any SSG related data. I found that layouts can combine their front matter in a hierarchy but I still need to specify the `layout` key in the front matter of the template. I want that there be a way to 'automatically' specify the layout through some config changes or placing the template/layout in corresponding directories. For example, in HUGO the templates stored in a specific directory determine the layout to be used for that template which would be stored in a corresponding directory.

Is there a way to achieve this in 11ty? I have [this](https://github.com/11ty/eleventy/issues/55#issuecomment-362881129) answer by @zachleat which could solve my problem but again I could not find its mention in the docs wondering if it was just an idea.

**Comment by pdehaan** [comment]
You could create a directory specific data file and specify the layout and any other shared config there: https://www.11ty.dev/docs/data-template-dir/

**Comment by YashJipkate** [comment]
Thanks @pdehaan! Closing this!
