### ISSUE TITLE
Validate Javascript Templates

### ISSUE THREAD

**Issue by ithinkihaveacat** [11ty/eleventy#1012]
If a Javascript Template file exists (e.g. `foo.11ty.js`), and it is specified (via `layout: foo`) but does not actually return anything useful (for example, if it's an empty file), eleventy returns a cryptic `fn is not a function` error.

It would be helpful if instead eleventy checked to see if the template file returned a valid value, such as a raw value, function, or class.

**Comment by zachleat** [comment]
Closed by #1013
