### ISSUE TITLE
Can't have tags in both data and frontmatter

### ISSUE THREAD

**Issue by StarfallProjects** [11ty/eleventy#1022]
**Describe the bug**
It seems that you can't set tags in both a data file and frontmatter. They don't merge. The tags in the data file get ignored. Is this a bug or a feature? It feels like a bug - it would be nice to be able to set some tags for all content in a section (in order to get it into a collection), while still setting individual tags where applicable.

It also means if you _only_ add tags via the data file, individual content tags are empty (e.g. posts.data.tags)

**To Reproduce**

https://github.com/StarfallProjects/cloudsthick

Create a `posts` directory, containing a `posts.json` and a `post1.md` file.

In the `posts.json`, add:
```
{
    "tags" : ["posts"]
}
```

In the `post1.md` frontmatter, add:
```
---
title: a test post
date: 2020-03-16
tags: 
 - a-tag
---
```

Then on the homepage, add:

```
{% for post in collections.posts %}
  <li>{{ post.data.title }}</li>
{% endfor %}
```

**Expected behavior**
The homepage should show a list, containing one item - the title of `post1.md`

**Actual behavior**
Nothing shown

**Environment:**

- Windows 10, Node 12.16.1
- Eleventy Version 0.10.0

**Comment by pdehaan** [comment]
Your **StarfallProjects/cloudsthick** repo 404ed for me, but I believe you need to set `setDataDeepMerge()` in your .eleventy.js config file if you want to merge meta data:

https://www.11ty.dev/docs/data-deep-merge/#data-deep-merge

```js
module.exports = function(eleventyConfig) {
  eleventyConfig.setDataDeepMerge(true);
};
```

**Comment by StarfallProjects** [comment]
My apologies, I had the repo still set to private.

And that works, thank you.
