### ISSUE TITLE
By default look for eleventy.config.cjs and eleventy.config.js config files

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#1029]
Also think about a potentially breaking change for 1.0 as we want to move away from dot files and look for `eleventy.config.cjs` and `eleventy.config.js` too (file separately).

I think this will be an additional lookup instead of a replacement for `.eleventy.js`.

**Comment by zachleat** [comment]
Related #1028

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by rynz** [comment]
For consistency between other `.*rc.js` configurations, eg: `.eslintrc.js`, `.prettierrc.js` can we please add an additional default `.eleventyrc.js`?

**Comment by valtlai** [comment]
@rynz, this may not change anything, but ESLint [is moving](https://github.com/eslint/eslint/issues/13481) to `eslint.config.js`.

**Comment by rynz** [comment]
@valtlai, that changes everything! Thank you for the heads up :)

**Comment by brycewray** [comment]
FWIW: in 0.12.1, manually setting the config to `eleventy.config.js` causes oddities with the BrowserSync config in dev mode (e.g., it doesn’t refresh the browser when CSS files are updated). Is this because of hard-coding that, one would assume, will be altered in 1.0.x to allow for `eleventy.config.js` rather than `.eleventy.js`?

**Comment by dafiulh** [comment]
@brycewray Is it related to #1448?

**Comment by dafiulh** [comment]
@brycewray I think it might be related to #1448 and #1568

**Comment by zachleat** [comment]
Punting this one out of 1.0—sorry y’all!

**Comment by zachleat** [comment]
Shipping with `2.0.0-canary.15` thanks to an excellent PR from @Snapstromegon at #2464!
