### ISSUE TITLE
Allow to return arbitary data from the computed data property

### ISSUE THREAD

**Issue by dweidner** [11ty/eleventy#1031]
**Is your feature request related to a problem? Please describe.**
I was a bit surprised to find out, that it is only possible to return string values from the computed data property. I expected the new feature to apply the *magic string substitution* only to string values and to leave other data types alone. Here a short example what I tried to do:

```js
// ./src/pages/pages.11tydata.js
module.exports = {
  layout: 'page',
  eleventyComputed: {
    isHomePage ({ slug }) {
      return slug === 'home';
    },
    slug ({ page, slug = null }) {
      return slug || page.fileSlug;
    },
    permalink ({ slug, isHomePage = false }) {
      return isHomePage ? '/' : `/${slug}/`;
    }
  }
};

```

**Describe the solution you'd like**
It would be great, if I could return any data type from the computed data functions not only string value. I could think of other use cases, where this might be helpful:

```js
module.exports = {
  layout: 'page',
  eleventyComputed: {
    seo ({ page }) {
      return {
        title: '…',
        description: '…',
        author: '…'
      };
    }
  }
};
```

**Describe alternatives you've considered**
In my example it would be easy to move the condition into the permalink function directly, but then the boolean would not be available within the template files.

**Comment by zachleat** [comment]
This will ship with 0.11.0 beta 4
