### ISSUE TITLE
passing data up the layout chain

### ISSUE THREAD

**Issue by tcurdt** [11ty/eleventy#1033]
I need to set `<script type="application/ld+json">` inside the head of a parent layout and I don't see a way to pass this up the layout chain.

**Comment by pdehaan** [comment]
You could probably do it using Nunjucks blocks (I'll see if I can dig up an example somewhere). But another workaround might just be to set the JSON-LD data in the template frontmatter:

```md
---
title: Home
permalink: /
author: Peter
ldjson:
  "@context":
    "@vocab": "http://schema.org/"
    first_name: "givenName"
    last_name: "familyName"
    alias: "alternateName"
    email: "email"
  first_name: "Billy"
  last_name: "Bob"
  alias: "BillyBob"
  email: "billybob@example.com"
---

<h1>{{ title }}</h1>
<p>Welcome to my fancy homepage!</p>
```

```md
---
title: About
permalink: about/
author: pdehaan
ldjson:
  "@context": "https://json-ld.org/contexts/person.jsonld"
  "@id": "http://dbpedia.org/resource/John_Lennon"
  name: "John Lennon"
  born: "1940-10-09"
  spouse: "http://dbpedia.org/resource/Cynthia_Lennon"
---

<h1>{{ title }}</h1>
<p>I'm very uninteresting.</p>
<p>{{ author }}</p>
```

Then, in your layout file, just check for that variable and add the `<script>` wrapper:

```html
<!-- src/_includes/layouts/base.njk -->
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="author" value="{{ author }}" />
<title>{{ title }}</title>
{%- if ldjson %}
<script type="application/ld+json">
{{ ldjson | dump(2) | safe }}
</script>
{%- endif %}
</head>
// ...
```

And my output would be:

```html
<head>
  <meta charset="utf-8" />
  <meta name="author" value="pdehaan" />
  <title>About</title>
  <script type="application/ld+json">
    {
      "@context": "https://json-ld.org/contexts/person.jsonld",
      "@id": "http://dbpedia.org/resource/John_Lennon",
      "name": "John Lennon",
      "born": "1940-10-09",
      "spouse": "http://dbpedia.org/resource/Cynthia_Lennon"
    }
  </script>
</head>
```

Another option might be to just include the `<script>` tags in your `_includes/` directory, and then just set a "ldjson: about-jsonld.html" key in your frontmatter and then use a dynamic include in your layout template, but that might be getting too meta and having too many files kicking around. Might depend on how reusable the JSON-LD files are for your site.

**Comment by pdehaan** [comment]
Or, if you don't like the YAML->JSON frontmatter conversion, you can always use JSON frontmatter:

```md
---json
{
  "title": "About this site",
  "permalink": "about/site/",
  "author": "pdehaan",
  "ldjson": {
    "@context": "https://json-ld.org/contexts/person.jsonld",
    "@id": "http://dbpedia.org/resource/John_Lennon",
    "name": "John Lennon",
    "born": "1940-10-09",
    "spouse": "http://dbpedia.org/resource/Cynthia_Lennon"
  }
}
---
```

**Comment by tcurdt** [comment]
Thanks for the quick feedback.

The data is dynamic but could easily defined at the layout level. So it's structurally different for a blog post and e.g. the index page, but the data changes per blog post.

If I could put the data into the frontmatter and the frontmatter still expands dynamic values like `{{ title }}` that would be a workable solution.

But overriding/setting blocks in parent templates would be the best. I just though I read that 11ty does not support them. Because of the internal layout abstraction.

**Comment by tcurdt** [comment]
@paulrobertlloyd unfortunately the `{{ title }}` does not get resolved in the frontmatter

**Comment by tcurdt** [comment]
Ha! I found `eleventyComputed`. It doesn't feel very elegant - but it does the job!

**Comment by tcurdt** [comment]
From https://www.11ty.dev/docs/data-computed/

```
---
layout: blog
eleventyComputed:
  ldjson:
    "@context":
      "@vocab": "http://schema.org/"
      title: "{{ title }}"
    email: "billybob@example.com"
---
```

**Comment by tcurdt** [comment]
It still would be better to use blocks. But I cannot get them to work. In the base layout I have

```
{% block meta %}{% endblock %}
```
and further down the chain in the post template I have

```
{% block meta %}
Some meta
{% endblock %}
```

but it seem like the latter just gets rendered in place :-(

**Comment by tcurdt** [comment]
I guess that's this is about https://github.com/11ty/eleventy/issues/853
