### ISSUE TITLE
Package eleventy into a single binary or executable

### ISSUE THREAD

**Issue by chrisdmacrae** [11ty/eleventy#104]
One of the common complaints against almost all other static site generators is installation.

This is especially a problem for Jekyll on Windows.

Zeit/pkg creates application executables of node applications for Darwin, Win32, and Unix systems, and will still allow users to add plugins from the NPM ecosystem.

This should be a late roadmap goal, but I believe it will separate Eleventy from the pack by making it accessible to non-technical users.

This could be deployed to OS-level package managers (e.g, homebrew, package-manager, and apt) in order to make installation and update management a breeze, while still leaving the product as a CLI.

**Comment by chrisdmacrae** [comment]
Note, they are performance considerations here. Packaged node apps may run 1.5x slower than unpackaged apps.

This may not be a problem for eleventy as the major bottleneck is file I/O.

**Comment by zachleat** [comment]
cc @mattdsteele this might alleviate the problem you were going through with requiring Node 6 support

**Comment by zachleat** [comment]
I know Hugo provides binaries and they have been successful there https://github.com/gohugoio/hugo/releases

I like this idea!

**Comment by zachleat** [comment]
https://github.com/nexe/nexe

**Comment by aral** [comment]
Just wanted to add that having a single binary would also make it much easier to include 11ty support in other tools like, *wink, wink* [Site.js](https://sitejs.org) alongside other single-binary static site generators like Hugo and Zola.
