### ISSUE TITLE
Can’t find properties of global data via eleventyComputed 

### ISSUE THREAD

**Issue by paulrobertlloyd** [11ty/eleventy#1043]
I’m looking at the new computed data feature, and seems like it can help me greatly simplify my templates (and perhaps help improve build time as a result). However, I’ve come across an issue.

* * *

Given the following `*.11tydata.js` file in a directory:

```js
module.exports = {
  layout: 'article',
  permalink: '{{ page.date | date: "%Y/%m" }}/{{ page.fileSlug }}.html',
  eleventyComputed: {
    image: data => {
      console.log(data.app); // data.app is populated by the global data file, app.js
    }
  }
};
```

Logging `data.app`, I get the following output (simplified) in the console for each page in the directory:

```
{
  title: 'Paul Robert Lloyd',
  short_title: 'PRL',
  description: 'The personal website of Paul Robert Lloyd'
}
```

However, if I update my `*.11tydata.js` file to log `data.app.title`, I get the following error:

```bash
Problem writing Eleventy templates: (more in DEBUG output)
> Cannot read property 'title' of undefined
```

This is weird, as that was previously shown as a property of `app`. Have I missed something?

**Comment by zachleat** [comment]
Related to/fixed with #1061.
