### ISSUE TITLE
How do I display the latest 10 blog posts?

### ISSUE THREAD

**Issue by TedGoas** [11ty/eleventy#1046]
I’m using [11ty](https://www.11ty.dev/) to build my website. I’m using [Skeleventy](https://skeleventy.netlify.com//), if that matters. The blog collection currently has ~40 blog posts and I’d like to display the latest 10 on the homepage. 

My blog posts are markdown files in `/site/blog/`.

In my homepage file’s front-matter (`index.njk`), I’m currently using `pagination` to limit the number of blog posts.

```
---
layout: …
…
pagination:
  data: collections.blog
  size: 10
  alias: articles
---
```

This “works” in limiting the number of posts to 10, but since I have ~40 blog posts it creates copies of the homepage with the subsequent blog posts. I don’t want these subsequent pages, I just want to display the last 10 blog posts and stop there.

<img width="242" alt="Screenshot 2020-03-26 08 18 41" src="https://user-images.githubusercontent.com/1172461/77646964-f7d66d00-6f3b-11ea-9c5f-08efa0745444.png">

Yes, pagination is doing exactly what it’s supposed to do :) so that’s probably not the best option here.

—

I’ve tried a new options listed [in this issue](https://github.com/11ty/eleventy/issues/503), such as 

```
{% assign latest_posts = collections.blog | reverse %}
{%- for post in latest_posts limit:10 -%}
  <!-- post content -->
{%- endfor -%}
```

But they return nothing.

I’m working in [this GitHub branch](https://github.com/TedGoas/Dante/tree/re-write), if it’s helpful to see everything.

**Comment by bturquet** [comment]
Hello @TedGoas ,
Please try the following snippet :
`{% set latest_posts = collections.blog | reverse %}
{% for post in latest_posts.slice(0,10) %}
    
{%- endfor -%}`

**Comment by TedGoas** [comment]
@bturquet Hey thanks so much, that (mostly) worked 🎉

Strangely enough, including `reverse` returned posts in chronological order (oldest first). Removing that produced the intended results 🤷‍♀️. Any idea why that might be?

The following returns the latest 10 posts:

```
{% set latest_posts = collections.blog %}
{% for post in latest_posts.slice(0,10) %}
...
{% endfor %}
```

**Comment by fynnit** [comment]
since this method caused errors at my end
```
ParseError was thrown
> tag set not found
```
I’ve set up a new collection in `.eleventy.js` like so: 

```
eleventyConfig.addCollection("newsrev", function(collectionApi) {
      return collectionApi.getFilteredByTag("news").slice(0,2).sort(function(a, b) {
        return b.date - a.date;
      });
    });
```


hope it helps someone out 🙌🏻

**Comment by mikebutts** [comment]
I know this is closed, but I ran into this using liquid.

solution; 
{% assign latest_projects = projects | slice:0, 2 %}
{% for project in  latest_projects %}

**Comment by hrothmar** [comment]
> hope it helps someone out 🙌🏻
> ```
> eleventyConfig.addCollection("newsrev", function(collectionApi) {
>       return collectionApi.getFilteredByTag("news").slice(0,2).sort(function(a, b) {
>         return b.date - a.date;
>       });
>     });
> ```

I also ran into this issue, and the comment above helped me get most of the way there. One thing to note is that the order of these filters can impact the data returned. With how it's currently set up, we're first taking the whole news collection and looking at only the first two news stories from the collection, then sorting only two returned. This can create some undesired results.

If you want to return the two newest items in a collection, we'll want to sort them first, then slice them afterward, which can be done with this:
```
eleventyConfig.addCollection("latest_news", function (collectionApi) {
	return collectionApi.getFilteredByTag("news").sort(function(a, b) {
		return b.date - a.date;
	}).slice(0,3);
});
```
