### ISSUE TITLE
Add ability to configure built in filters

### ISSUE THREAD

**Issue by paulrobertlloyd** [11ty/eleventy#1048]
**Is your feature request related to a problem? Please describe.**

The `slug` filter uses `-` for its replacement value, but I slug using `_`. [This filter](https://github.com/11ty/eleventy/blob/master/src/Filters/Slug.js) wraps around `slugify`, so it’d be nice to have access to those options.

It might also be nice to be able to change the name of this filter.

**Describe the solution you'd like**

Maybe something like this (mimicking how it’s possible to configure template languages)?

```
module.exports = function(eleventyConfig) {
  eleventyConfig.setFilterOptions("slug", {
    replacement: "_",
    lower: true
  });
};
```

**Describe alternatives you've considered**

I currently use a separate filter, which I’ve called `slugify` so that it doesn’t collide. Hmm, maybe I can call it the same name. Still.

**Comment by paulrobertlloyd** [comment]
Alternative, maybe the slug replacement value is a global config option?

**Comment by zachleat** [comment]
Just as a preliminary comment, I’m pretty sure you can override with your own `slug` universal filter.

**Comment by edjw** [comment]
> Just as a preliminary comment, I’m pretty sure you can override with your own `slug` universal filter.

I do this. You can definitely give your custom slug filter the name `slug`

**Comment by zachleat** [comment]
It is canonical behavior to override built-in filters with your own.

Related: new `slugify` filter in 1.0.
https://github.com/11ty/eleventy/issues/278

In 1.0 both `slug` and `slugify` allow you to pass in your own options as a second argument.

Note also that `eleventyConfig.getFilter` exists too if you want to reuse one of those filters (say in a markdown in-page links plugin)

I believe this can be closed?

**Comment by paulrobertlloyd** [comment]
So is this the recommended way of overriding the slug filter to change its options (and by extension the preferred separator)?

```js
const slugify = require('@sindresorhus/slugify');

module.exports = function (eleventyConfig) {
  eleventyConfig.addFilter('slugify', function(string, {
    separator: '_'
  }));
}
```

**Comment by pdehaan** [comment]
Here's what I had (but I misread your original post as the "slug" filter, not the new slugify; but the solution should be the same):

```js
// .eleventy.js
const eleventyPkg = require("@11ty/eleventy/package.json");

module.exports = function (eleventyConfig) {
  // Get reference to built-in `slug` filter.
  const slugFn = eleventyConfig.getFilter("slug");

  eleventyConfig.addShortcode("version", function () {
    return `${eleventyPkg.name} v${eleventyPkg.version}`;
  });

  eleventyConfig.addFilter("slug", function (value, opts) {
    opts = Object.assign({
      remove: /[*+?=~.()'"!:@]/g,
      replacement: '_',
      lower: true
    }, opts);
    return slugFn(value, opts);
  });

  eleventyConfig.addFilter("slug_original", slugFn);

  return {
    dir: {
      input: "src",
      output: "www"
    }
  };
};
```

```njk
---
# src/index.njk
title: Test
string: The:Quick=Brown+Fox<Jumps&Over-The_Lazy-K9 or does it?'"'
---

<pre data-string-raw>
{{ string | safe }}
</pre>

<pre data-string-slug-original>
{{ string | slug_original | safe }}
</pre>

<pre data-string-slug-override>
{{ string | slug | safe }}
</pre>

<footer>{% version %}</footer>
```

### OUTPUT

```html
<pre data-string-raw>
The:Quick=Brown+Fox<Jumps&Over-The_Lazy-K9 or does it?'"'
</pre>

<pre data-string-slug-original>
the:quickbrown+foxlessjumpsandover-the_lazy-k9-or-does-it'"'
</pre>

<pre data-string-slug-override>
thequickbrownfoxlessjumpsandover-the_lazy-k9_or_does_it
</pre>

<footer>@11ty/eleventy v1.0.0-canary.39</footer>
```

**Comment by pdehaan** [comment]
Oh, and I should point out you can override configs on a per-slug basis as well (although I don't think this worked in liquidjs templates since I don't think you can pass objects as params as easily as in Nunjucks):

```njk
<pre data-string-slug-upper>
{{ string | slug({lower: false}) | safe }}
</pre>
```

### OUTPUT

```html
<pre data-string-slug-upper>
TheQuickBrownFoxlessJumpsandOver-The_Lazy-K9_or_does_it
</pre>
```
