### ISSUE TITLE
getPreviousCollectionItem missing from 0.11.0-beta.3

### ISSUE THREAD

**Issue by ithinkihaveacat** [11ty/eleventy#1056]
In 0.11.0-beta.2, filter functions like `getPreviousCollectionItem()` are available to JavaScript templates. In 0.11.0-beta.3, they are not.

That is, the following JavaScript template prints `DEFINED` in beta.2, and `NOT DEFINED` in beta.3:

```js
module.exports = function (context) {
  console.log(this.getPreviousCollectionItem ? "DEFINED" : "NOT DEFINED");
};
```

I believe this is caused by https://github.com/11ty/eleventy/commit/9de36e8fcf9bbedf6199a8f82f12a7e9ca37a62e.

**Comment by Ryuno-Ki** [comment]
Oh, wait, there are new beta versions out already? :O

**Comment by zachleat** [comment]
Dang, sorry about this—I’ll get it patched up. I probably should start an `alpha` or `daily` channel to fit better with the increased project velocity

**Comment by pdehaan** [comment]
I like the npm `@alpha` tag idea, but I believe you can also install the latest from GitHub using <kbd>npm i github:11ty/eleventy -D</kbd> if one should ever need the latest cutting edge commit.

**Comment by zachleat** [comment]
Unfortunately it does not look like Netlify works with GitHub installs like that, at least the last time I tested it

**Comment by TigersWay** [comment]
With package.json like this one, it sure does deploy on netlify
```
...
  },
  "dependencies": {
    "@11ty/eleventy": "github:11ty/eleventy#master",
    "@fullhuman/postcss-purgecss": "^2.1.0",
...
```

**Comment by zachleat** [comment]
Beautiful, thank you @TigersWay

**Comment by zachleat** [comment]
This will ship with beta 4. Hopefully the last beta but we may do 5

**Comment by Ryuno-Ki** [comment]
Just [learned](https://stackoverflow.com/a/59270088) about how to learn about new beta versions:

`npm view @11ty/eleventy`

Thanks @KyleMit!

**Comment by pdehaan** [comment]
You can also use <kbd>npm info @11ty/eleventy dist-tags --json</kbd>

```json
{
  "latest": "0.10.0",
  "beta": "0.11.0-beta.3"
}
```
