### ISSUE TITLE
Allow underscore prefix for indexes and directory data files

### ISSUE THREAD

**Issue by TigersWay** [11ty/eleventy#1057]
**Is your feature request related to a problem? Please describe.**
For those of us who have a posts/pages/etc organization which is not possible yet with a CMS, or for those who prefer without, it's not always easy to find deep inside a crowed folder the **index file** or the **directory data file**.

**Describe the solution you'd like**
**Allow to prefix these files with an underscore (_)**, which seems under all platforms to be sorted first. Eleventy would use only the first one (priority to decide) found.

**Describe alternatives you've considered**
Playing with a global permalink function makes it possible for indexes, but not for directory data ones.

**Additional context**
I could try a PR.

**Related**
#774

**Comment by zachleat** [comment]
Can we organize on this over at #774? If there is something not listed on #774, please add it over there!
