### ISSUE TITLE
Add documentation about creating menus with data files // collections

### ISSUE THREAD

**Issue by chrisdmacrae** [11ty/eleventy#106]
Menus are a super common problem in static site generators, for obvious reasons.

## Static menus
Eleventy can facilitate static menus very easily with data files. Just write em and call it a day.

## Dynamic menus
Eleventy can easily facilitate dynamic menus using custom collections. It actually allows for pretty robust menus with very little effort.

E.g:

```
module.exports = (eleventyConfig) => {
  eleventyConfig.addCollection("headerMenu", function(collection) {
    var menuCollection = collection.getAll().map(menuItem => {
        return {
          title: menuItem.title,
          url: menuItem.url,
          // any other fields you want...
        }
    })
  });
}

  return { ... }
}
```

**Comment by guayom** [comment]
I would like to collaborate with this issue

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for documentation requests. This means documentation issues will now be closed instead of leaving them open.

View [the documentation queue backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Areactions-%2B1-desc+is%3Aclosed+label%3Adocumentation+label%3Aneeds-votes). Don’t forget to upvote the top comment with 👍!

**Comment by chrisdmacrae** [comment]
@zachlet this would be better as a plugin than documentation.

Create a plugin that generates menus based on the front matter key of each file, and allow it be supplemented with data files?

I think some features this would need to facilitate:

- Creating arbritrary menu items
- Dynamically adding menu items from pages data
- Weighting menu items for sorting
- Nesting

The general data structure for a menu item would have to be:

- `id`: a generated id based on the file path, or a custom provided id
- `title`: the actual content of the menu item
- `permalink`: the permalink of the document, or a custom provided permalink
- `weight`: the set weight, or 0
- `parent`: the menu id, or the id of a menu item, or the actual parent item object
- `menu`: the menu id
- `page`: reference to the page this menu item was generated from, if applicable
- `children`: null, or an array of child menu item ids, or array of actual child menu items?
- `...`: any custom properties added to the menu item

I'm picturing that everything but global data is treated the same way, where you can:

- define a `menus` key
  - which can take a string of a menu id
  - which can take an array of menu ids
  - which can take an object of menu ids as keys, with detailed configuration and custom properties as properties under it.

```
---
menus: main
menus: [main, secondary]
menus:
  main:
   weight: 0
   prefix: Menu
   suffix: Item
   parent: "id_of_parent"
---
```

And in `_data/menus.yml`:

```
main:
   - id: customMenuItem
     title: My Custom Menu Item
     weight: 0
     permalink: example.com
```

Or via the plugin config, in `.eleventy.js`
```
const eleventyMenus = require('eleventy-plugin-menus');

module.exports = (eleventyConfig) => {
  eleventyConfig.addPlugin(eleventyMenus, {
    menus: {
        main: [],
        secondary: []
     }
   })
}
```

**Comment by zachleat** [comment]
Circling back here I believe this is solved nicely with the Navigation plugin! https://www.11ty.dev/docs/plugins/navigation/
