### ISSUE TITLE
Bug with Filters in Computed Data

### ISSUE THREAD

**Issue by nhoizey** [11ty/eleventy#1061]
**Describe the bug**

I tried to replace all `renderData` in my templates with `eleventyComputed`, but the build now doesn't work.

**To Reproduce**

I used to have this YFM in this template:
https://github.com/nhoizey/nicolas-hoizey.com/blob/master/src/articles/index-months.njk

```markdown
---
layout: page
pagination:
  data: collections.articlesByMonth
  size: 1
  alias: month
permalink: "articles/{{ month }}/"
renderData:
  title: Articles published in {{ month | monthString }}
---

…
```

I tried to replace `renderData` with `eleventyComputed`, but it gives me this error:

```
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering njk template ./src/articles/index-months.njk

`TemplateContentRenderError` was thrown
> (./src/articles/index-months.njk)
  TypeError: Cannot read property 'replace' of undefined

`Template render error` was thrown:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nicolas-hoizey.com@2.1.0 eleventy:build: `cross-env NODE_ENV=production eleventy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nicolas-hoizey.com@2.1.0 eleventy:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nhoizey/.npm/_logs/2020-03-30T09_26_27_412Z-debug.log
```

I guess it comes from the `alias` because the error `Cannot read property 'replace' of undefined` comes from the `monthString` filter:
https://github.com/nhoizey/nicolas-hoizey.com/blob/master/src/_11ty/filters/dates.js#L7-L11

```javascript
monthString: (month) => {
  // transforms "2020/02" into "February 2020"
  let fullDate = `${month.replace('/', '-')}-01T10:00:00.000Z`;
  return moment(fullDate).format('MMMM YYYY');
},
```

**Expected behavior**

I thought `eleventyComputed` was supposed to replace `renderData` completely.

**Environment:**

- OS and Version: macOS 10.15.3
- Eleventy Version 0.11.0-beta-3

**Comment by zachleat** [comment]
What does the new failing one look like?

**Comment by nhoizey** [comment]
@zachleat do you mean the YFM that doesn't work?

Same as the other with just `renderData` replaced by `eleventyComputed`:

```markdown
---
layout: page
pagination:
  data: collections.articlesByMonth
  size: 1
  alias: month
permalink: "articles/{{ month }}/"
eleventyComputed:
  title: Articles published in {{ month | monthString }}
---

…
```

**Comment by jasonday** [comment]
I read somewhere that the title should be in `""` when using `eleventyComputed`, but I can't get `eleventyComputed` working either.
