### ISSUE TITLE
Possible to add multiple Shortcodes in a loop?

### ISSUE THREAD

**Issue by mittelgrau** [11ty/eleventy#1062]
Hey,
i'm trying to load different components and add shortcodes for every component in a directory. My normal approach would be to add a `config.addShortcode('Button, require(path/to/button)')`

Is there a viable way to do something like the following:

Given i have a object (components) that contains a 'name' - 'anonymous Function' Pair.
 
// eleventy.js
` 
Object.keys(components).forEach(component => 
 config.addShortcode(`${component}, ${components[component]}`);
)`

**Comment by nhoizey** [comment]
Maybe you'll find some inspiration in what I did just yesterday for my own site:
https://github.com/nhoizey/nicolas-hoizey.com/commit/a3cda1d2ec0d47f69541d2ad6f6a6d2b953db3b0

I followed the lead of @TigersWay:
https://github.com/TigersWay/11ty-netlify-playground/blob/master/.eleventy.js

**Comment by mittelgrau** [comment]
Tried it unsuccessfully with https://www.npmjs.com/package/require-dir but will follow your approach. Thank you!
