### ISSUE TITLE
Disable live reload for developing AMP pages

### ISSUE THREAD

**Issue by walling** [11ty/eleventy#1063]
Hi there, great project! I have a question: Is it possible to disable live reload, when using `--serve`? Unfortunately AMP pages can't have custom JavaScript tags, and the injected live reload script is triggering an error in my AMP validation browser extension.

Is this possible? If not, is it something that is easy to implement?

**Comment by walling** [comment]
Ok, [I found out via this answer](https://stackoverflow.com/a/27579008/317118) that you can do the following in `.eleventy.js`, but seems a bit hackish:

```js
module.exports = () => ({
  browserSyncConfig: {
    snippetOptions: {
      rule: { match: /qqqqqqqqq/ }, // disable browser-sync on all pages
    },
  },
});
```

**Comment by zachleat** [comment]
Another option is that --watch is made for this but you will have to supply your own web server! I've used the `http-server` npm package before with success, but my usual go to is Mac OS Apache and I just leave it on all the time 😅

**Comment by Ryuno-Ki** [comment]
Myself is using `python3 -m http.server` on the output directory. Python normally ships with *nix systems like GNU/Linux or macOS. In case you have Python 2 (EOL!), then the command would be `python -m SimpleHTTPServer`.

**Comment by walling** [comment]
Thanks, that are some good ideas. I now got a nice development process up an running using the following package.json scripts (start with `yarn dev`):

```json
{
  "scripts": {
    "dev": "concurrently yarn:watch yarn:serve",
    "watch": "eleventy --watch",
    "serve": "http-server _site"
  }
}
```
