### ISSUE TITLE
Adding inline JavaScript

### ISSUE THREAD

**Issue by ctuxboy** [11ty/eleventy#1075]
Hello,
I work on a project with 11ty.
At this moment adding inline JS snippets directly in the HTML-pages.
Is this a good way to do, or is it better adding the scripts in Eleventy.js?
What are the benefits? Pro's and Cons?

**Comment by reubenlillie** [comment]
@ctuxboy,

Are you talking about client-side JS? I want to make sure I understand your question.

**Comment by Ryuno-Ki** [comment]
Perhaps related to #1017 .

**Comment by ctuxboy** [comment]
> @ctuxboy,
> 
> Are you talking about client-side JS? I want to make sure I understand your question.

Hi @reubenlillie ,

Thanks for your help!
I have basic JS knowledge and try understand how build my templates 'the right way' . What i mean are the templates itself, not the generated html-files in _site .
I used html-extantion instead of liquid. I hope this is also no problem for a good workflow, or is it also better using the liquid-extention (instead of html)?
Sorry for my poor english, i hope you ubnderstand what i mean.

**Comment by ctuxboy** [comment]
H

> Perhaps related to #1017 .

@Ryuno-Ki thanks for the useful link. :-)

**Comment by Ryuno-Ki** [comment]
Hi @ctuxboy,
I think, here's some confusion about what is meant with „inlining”.
Normally, we interpret that as „take a function and wrap it's content inside a `<script>` tag” (for JS in this case, for CSS it would be `<style>`).

The next question here is: Shall the code be modified (e.g. minified) before it gets inserted into the tag.
If not, you could also write something like this (I do that with Nunjucks, but Liquid should work similiar):

```liquid
<script>
{% include "js/show-tooltip.js" %}
</script>
```
for a JavaScript file `_includes/js/show-tooltip.js` (in my case a symlink to a JS file in an asset folder).

Could be, that it requires a capture, i.e.

```liquid
<script>
{% capture js %}{% include "js/show-tooltip.js" %}{% endcapture %}
{{ js }}
</script>
```

**Comment by ctuxboy** [comment]
> Hi @ctuxboy,
> I think, here's some confusion about what is meant with „inlining”.
> Normally, we interpret that as „take a function and wrap it's content inside a `<script>` tag” (for JS in this case, for CSS it would be `<style>`).
> 
> The next question here is: Shall the code be modified (e.g. minified) before it gets inserted into the tag.
> If not, you could also write something like this (I do that with Nunjucks, but Liquid should work similiar):
> 
> ```
> <script>
> {% include "js/show-tooltip.js" %}
> </script>
> ```
> 
> for a JavaScript file `_includes/js/show-tooltip.js` (in my case a symlink to a JS file in an asset folder).
> 
> Could be, that it requires a capture, i.e.
> 
> ```
> <script>
> {% capture js %}{% include "js/show-tooltip.js" %}{% endcapture %}
> {{ js }}
> </script>
> ```

@Ryuno-Ki oh okay, now i understand why it's better using the 11ty-way.
It's more for manipulating the files if it necessary and so on.
Thanks for your help!!!

**Comment by Ryuno-Ki** [comment]
You're welcome.
If your question was answered, consider closing this issue, please :-)

**Comment by ctuxboy** [comment]
Okay i closed the issue.
