### ISSUE TITLE
11ty crashes silently: doesn't output any files while not reporting any error.

### ISSUE THREAD

**Issue by GerHobbelt** [11ty/eleventy#1081]
**Describe the bug**

Some user configuration and developer mistakes, which cause the Template parts of the code to throw an error and make 11ty fail, are silently eaten and ignored. 

Not even having the DEBUG output as per https://www.11ty.dev/docs/debugging/ was any help: the failure goes unmentioned there as well. When you start to trace through the code you'll discover that there's some inexplicable *lack* of subsequent `debug(...)` output for several input files.

The result then is 11ty reporting success and you staring at a completely empty output directory and going *WTF*?

**To Reproduce**

See #1080 for a deliberately introduced failure (an exception which is rethrown) which showcases the issue: without #1079, 11ty will crash silently thanks to a Promise without `catch` way up the call chain. (See also the #1079 and #1080 patch diffs.)

**Expected behavior**

The exception (**any fatal failure** in that code tree anyway) should have been caught an reported, so that the user has something to read and wonder about while the output is not generated due to user and/or dev error.

**Environment:**

- Win 10 / node 12 
- Eleventy Version: both latest stable `npm i` version (0.10.0) as per today *and* also observed in the `master` branch commit which I forked the showcase and fix pullreqs off: #1079 and #1080 

**Additional context**

Ran into this while going through the code as I attempted to dig up what was going wrong with the local rig.

This kept me from discovering that at least one of my problems was some obscure stuff badly failing around permalinks as defined in a `_data/layouts/template.11ty.js` JavaScript layout template (following the spirit of https://www.11ty.dev/docs/languages/javascript/#permalink-function)

**Comment by zachleat** [comment]
Looks like this was fixed, he says two years too late https://github.com/11ty/eleventy/pull/1080#issuecomment-801578853
