### ISSUE TITLE
escaping Nunjucks syntax in Markdown files

### ISSUE THREAD

**Issue by mvolkmann** [11ty/eleventy#1086]
What is the best way to escape Nunjucks syntax inside a Markdown file that is only there to document the use of Nunjucks? For example:

```
Arguments can be specified positionally or by name.
For example:

{% for dog in collections.dogsByName %}
  {{ dogP(gender=dog.data.gender, breed=dog.data.breed, name=dog.data.name) }}
{% endfor %}
```

I don't want Nunjucks to process anything here in this case.

**Comment by mvolkmann** [comment]
This is related: https://www.larryhudson.io/blog/2020/02/escaping-nunjucks-in-eleventy/

**Comment by brycewray** [comment]
Does the `{% raw %}` and `{% endraw %}` combo not work anymore?

**Comment by mvolkmann** [comment]
I wasn't aware of that. Thanks! It seems to work in some cases, but not all. For example:

```njk
{% raw %}
{% for dog in collections.dogsByName %}
  {% dog dog.data.breed, dog.data.name %}
{% endfor %}
{% enddraw %}
```

This gives me "unknown block tag: dog".
In actual usage this assumes that I have defined a shortcode named "dog".
But I just want to provide an example here and not have Nunjucks attempt to process it.

**Comment by brycewray** [comment]
Wonder if it's not "seeing" your code block within there for some reason? I had three examples in this file and had no problem: https://raw.githubusercontent.com/brycewray/eleventy_bundler/master/src/posts/2019/12/previous-next-eleventy.md
...with the actual output at https://brycewray.com/posts/2019/12/previous-next-eleventy/

**Comment by mvolkmann** [comment]
I looked at your example, but still can't get it to work. Here is what I'm trying.

{% raw %}

```njk
{% for dog in collections.dogsByName %}
  {{ dog.data.breed }}
  {{ dog.data.name }}
{% endfor %}
```

{% enddraw %}

I get "TemplateContentRenderError` was thrown" and "unknown block tag: enddraw."

**Comment by brycewray** [comment]
Sorry, I missed that "d" in your earlier reply. Should be `{% endraw %}`. In other words, you're **end**ing a "**raw**" section, so to speak. So it's `{% raw %}` and then `{% endraw %}`.

**Comment by mvolkmann** [comment]
Well, that does make all the difference. Spelling matters. Thanks!
