### ISSUE TITLE
Introduce breaking (template language) changes in v0.11.0

### ISSUE THREAD

**Issue by paulrobertlloyd** [11ty/eleventy#1091]
A number of template projects 11ty includes have released major updates since this project began:

Language | 11ty version | Latest version
-|-|-
Mustache (#371) | 2.3.2 | 3.1.0
LiquidJS (#469) | 6.4.3 | 9.11.10
markdown-it (#669) | 8.4.2 | 10.0.0

I know that recent versions of LiquidJS have introduced *significant* performance improvements. However, none of these upgraded dependancies are slated to be merged into the project until it reaches v1.0. While breaking changes should of course be avoided, this project is still in v0.x, and such changes are permitted by Semver:

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.
— [Semver specification, #4](https://semver.org/#spec-item-4)

Given the significance of the number 11 to this project, maybe the v0.11 release can introduce the above upgrades, whether these be in addition to other breaking changes or not.

**Comment by zachleat** [comment]
1.0 will be the next release after 0.11 and we’ll bundle these changes there. We’ll stick to strict semver for this project—I hate the exceptions to semver that exist for 0.x. We’ll get rid of the ambiguity there and make that explicit with a 1.0 jump.

**Comment by zachleat** [comment]
Closing this as 1.0 development has commenced and we have individual issues for each of these.
