### ISSUE TITLE
Support .jsonc in global data

### ISSUE THREAD

**Issue by KyleMit** [11ty/eleventy#1094]
**Is your feature request related to a problem?**

[JSON with Comments](https://code.visualstudio.com/docs/languages/json#_json-with-comments) or `.jsonc` is a file format that allows for json syntax with the addition of comments.  Eleventy is powered by json data sets within the repository, and it can be very helpful to markup or annotate information within that dataset for maintainability.  Currently `.jsonc` files are ignored by the global data parser

**Describe the solution you'd like**

An adapter to be added that parses `.jsonc` files and adds to the global data cascade

**Describe alternatives you've considered**

You can manually add the adapter yourself by processing using a `.js` file.  Since the `.jsonc` file is never read, there won't be a naming conflict, so you can have two files per `_data` source

ex. 

* `_data/faqs.jsonc`
* `_data/faqs.js`

Where the `.js`  file can read & process the data like this:

```js
const fs = require("fs");
const jsoncParser = require("jsonc-parser")

let fullPath = `${__dirname}/faqs.jsonc`;
let contents = fs.readFileSync(fullPath, "utf8")
let object = jsoncParser.parse(contents)

module.exports = object
```

**Comment by stevenpetryk** [comment]
Seems like a good first PR (just changing the parser and glob patterns). Would you want to take a stab at it?

**Comment by gael-ian** [comment]
`.jsonc` seems to be a VS Code specific thing. [JSON5](https://json5.org/) takes a wider approach and parsers in many languages (including [JavaScript](https://github.com/json5/json5), of course).

**Comment by zachleat** [comment]
Howdy y’all, we do provide an API to add your own data extensions: https://www.11ty.dev/docs/data-custom/

Please use that!

Even better: make a plugin for it that others can consume!
