### ISSUE TITLE
Using a variable value as the name of a data file

### ISSUE THREAD

**Issue by fbnlsr** [11ty/eleventy#1095]
Quick question. Is it possible to pass a variable to a layout so its value is used as the file name of a data file? Say for instance I have two dictionaries `en.json` and `fr.json`. Can I use the same layout, pass it a variable from my template so that it uses the correct file based on the value of that variable?

Or what would be the best way to achieve this?

**Comment by ThePeach** [comment]
The way I've understood it, it does not seem to be a problem, as long as the reading happens in the right place (could be a simple `lang: en` in frontmatter).
You might need to load all the translations at the very beginning and access them by key.
I'd expect to access them in the template with something like `{% i18n[lang].subtitle %}`.

Dunno if that would make sense

**Comment by fbnlsr** [comment]
Awesome, thanks a lot. I'm closing this issue for now, no need to leave it open.
