### ISSUE TITLE
What is the function of the 'main' section of package.json?

### ISSUE THREAD

**Issue by dixonge** [11ty/eleventy#1096]
Three of my sites have ```main: index.js``` - one has ```main: _site/index.html```
I'm fairly certain I did not edit these lines. Where do they come from? Which is correct?

**Comment by stevenpetryk** [comment]
It’s a standard `package.json` field ([docs](https://docs.npmjs.com/files/package.json#main)). It is likely meaningless for your site, since it’s not a public node package.

**Comment by dixonge** [comment]
So evidently I *did* edit them! I've been futzing with node since my first install of Ghost many years ago, but obviously never read the documentation...
