### ISSUE TITLE
Computed data: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by paulrobertlloyd** [11ty/eleventy#1098]
**Describe the bug**
This is in relation to the change in #973, which now has my computed data throwing an error. This _might_ by okay – maybe what I’m trying to achieve isn’t possible – but thought it was worth flagging all the same.

I have the following computed data in a directory data file, that I use to find article posts related to a given project (which I do using a `category` frontmatter key; if an article has a `category` value that is the same as a projects `title`, it’s deemed to be related):

```js
module.exports = {
  layout: 'project',
  permalink: 'projects/{{ page.fileSlug }}/',
  eleventyComputed: {
    related: data => {
      const articles = data.collections.article;
      return articles.filter(article => {
        const {category} = article.data;
        if (!category) {
          return false;
        }

        return category.includes(data.title);
      });
    }
  }
};
```

However, I now get the following error:

```
Problem writing Eleventy templates: (more in DEBUG output)
> Cannot read property 'filter' of undefined
```

Is 11ty no longer aware of the global `data` object at this point in the cascade? I was getting this error intermittently before, so I guess having it be persistent is an improvement, of sorts 😉 

**Additional context**

- Eleventy version: [master@9109e7](https://github.com/11ty/eleventy/commit/9109e76f1fccc98d1809613c61b2a441152a7f13)

**Comment by zachleat** [comment]
Can you retest with the new version on GitHub? I think I boggled how computed data treats arrays last weekend, hoping it’s patched now. If not I’ll dive in deeper here before 0.11 ships

**Comment by paulrobertlloyd** [comment]
Yep, this appears fixed. Thanks @zachleat!
