### ISSUE TITLE
Where should the eleventyComputed.js global data file be placed?

### ISSUE THREAD

**Issue by anaurelian** [11ty/eleventy#1101]
Where should the [eleventyComputed.js](https://www.11ty.dev/docs/data-computed/#advanced-details) global data file be placed? I have tried many ways, and it does not work:

* /src/eleventyComputed.js
* /src/eleventyComputed.11tydata.js
* /src/_data/eleventyComputed.js
* /src/_data/eleventyComputed.11tydata.js

```
module.exports = {
  eleventyComputed: {
    eleventyNavigation: {
      key: data => data.page.url,
      title: data => data.title,
    }
  }
};
```

I'm using v0.11.0-beta.3. Thank you.

**Comment by ThePeach** [comment]
are you overriding any configuration? if so, can you please share.

**Comment by anaurelian** [comment]
> are you overriding any configuration? if so, can you please share.

```
  ...

  eleventyConfig.addPlugin(eleventyNavigationPlugin);

  eleventyConfig.setDataDeepMerge(true);

  return {
    dir: {
      input: 'src',
      includes: '_includes',
      data: '_data',
      output: '_site',
    },
    passthroughFileCopy: true,
    htmlTemplateEngine: "njk",
    markdownTemplateEngine: "njk"
  }

```

I also like to mention that a `kb.11tydata.js` file with the same content placed in `/src/kb/` works.

**Comment by anaurelian** [comment]
Sorry, this was kind of a silly mistake from my part, the contents of the `_data/eleventyComputed.js` file should be:

```
module.exports = {
  eleventyNavigation: {
    key: data => data.page.url,
    title: data => data.title,
  }
};
```

This correctly writes to the `eleventyComputed.eleventyNavigation` object, no need to add `eleventyComputed:` after `module.exports`, because the file name is already `eleventyComputed`.

I was doing it wrong:

```
module.exports = {
  eleventyComputed: {
    eleventyNavigation: {
      key: data => data.page.url,
      title: data => data.title,
    }
  }
};
```

This was writing to an `eleventyComputed.eleventyComputed.eleventyNavigation` object, not to to the `eleventyComputed.eleventyNavigation` object.
