### ISSUE TITLE
dev server serves files with the wrong mime type

### ISSUE THREAD

**Issue by tcurdt** [11ty/eleventy#1102]
**Describe the bug**

In dev mode, assets are not served with the correct mime type.

**To Reproduce**

This is my config:

    config.addPassthroughCopy('src/assets')

    return {
      dir: {
        input: 'src',
        output: 'site',
        data: '_data'
      },
      templateFormats: [
        'njk',
        'md',
        'css',
        'html',
        'svg',
        'jpg',
        'png'
      ],
      htmlTemplateEngine: 'njk',
      markdownTemplateEngine : "njk",
      passthroughFileCopy: true
    }

My assets get copied over to `_site just` fine. Unfortunately the browser fails to load the js.

    The resource from “http://localhost:2015/assets/js/site.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
    Loading failed for the <script> with source “http://localhost:2015/assets/js/site.js”.

Why is eleventy serving the assets as "text/html"? It should not.
Or does this need to be configured?

**Expected behavior**

The js files should be served with the correct mime type.

**Environment:**

- macOS 10.15.3 
- eleventy 0.10.0

**Comment by matuzo** [comment]
Are you 100% sure that the file exists? Can you access it when you open `http://localhost:2015/assets/js/site.js` in the browser? The reason for the `text/html` mime type could be that you're receiving a 404 page instead of the js file.

**Comment by tcurdt** [comment]
Ahhhh - that was probably it! I re-structured the site now so I can no longer verify it. But in hindsight it sounds like the most likely reason. Thanks, @matuzo
