### ISSUE TITLE
An example of an eleventyComputed.js global data file 

### ISSUE THREAD

**Issue by anaurelian** [11ty/eleventy#1104]
On the [Computed Data | Eleventy, a simpler static site generator.](https://www.11ty.dev/docs/data-computed/) page, in the [Advanced Details](https://www.11ty.dev/docs/data-computed/#advanced-details) section, related to

> You can put eleventyComputed anywhere in the Data Cascade: Front Matter, any Data Files (you could even make an eleventyComputed.js global data file if you wanted to set this for your entire site).

I think it would be helpful to add an example of such a file, similar to the `posts/posts.11tydata.js` example:

```
module.exports = {
  eleventyNavigation: {
    key: data => data.title,
    parent: data => data.parent
  }
};
```

(no need to add `eleventyComputed:` after `module.exports`, because the file name is already `eleventyComputed`.)

This may prevent silly mistaked like [this one](https://github.com/11ty/eleventy/issues/1101).

**Comment by zachleat** [comment]
I like this idea—do you have the bandwidth to PR it? There are “Edit this page” links on the bottom of each docs page.

**Comment by Snugug** [comment]
I've opened a PR to add an example:

https://github.com/11ty/11ty-website/pull/558

**Comment by zachleat** [comment]
Fixed by https://github.com/11ty/11ty-website/pull/558

Thanks @Snugug!
