### ISSUE TITLE
Passthrough Copy should always be incremental

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#1109]
While incremental for passthrough copy is shipping via #977 in 0.11.0, I think a very strong case can be made to always use incremental behavior for passthrough copy files, specifically:

1. When a passthrough copy file changes during watch, just copy the one file (no other templates are processed)
2. When a template changes that is _not_ a passthrough copy file during watch, the passthrough copy file is not copied.

**Comment by marcfilleul** [comment]
+1

**Comment by tarasis** [comment]
Does incremental with passthrough copy only work with WATCH or SERVE? Atm it seems the --incremental doesn't work on its own. Which means each new update (for now) copies 190 files needlessly. Sure its done in ½ a second but its wear and tear that isn't needed.

My ideal it push changes to server, it checks out the new head, builds incrementally (aka only builds what's changed) and then that's served.

```[11ty] Copied 190 files / Wrote 2 files in 0.41 seconds (v1.0.0)```

**Comment by zachleat** [comment]
A better resolution to this issue will be shipping with 2.0.0-canary.12: https://github.com/11ty/eleventy/issues/2456

Works in both `--incremental` and standard modes.

**Comment by zachleat** [comment]
@tarasis sorry to circle back here late but that feature requires Cold Start incremental, which is on the roadmap! Subscribe to https://github.com/11ty/eleventy/issues/984

**Comment by zachleat** [comment]
Note that this feature was swapped to opt-in in 2.0.0-canary.31: https://fosstodon.org/@eleventy/109705218587201477
