### ISSUE TITLE
Allow computed data to configure special Eleventy Data properties (like pagination)

### ISSUE THREAD

**Issue by rhumaric** [11ty/eleventy#1110]
**Describe the bug**
I'm trying to paginate some data that's returned by an `eleventyComputed` property. Eleventy breaks announcing it cannot find the property used for the pagination:

>  Could not resolve pagination key in template data: supportedLocales

**To Reproduce**

The `computed-properties-pagination` branch of [this repository](https://github.com/rhumaric/eleventy-computed-property-order-issue/tree/computed-properties-pagination) contains a reduced test case. The `test.liquid` template tries to paginate over the `supportedLocales` key defined in `data/eleventyComputed`. Run `npx @11ty/eleventy` to get the exception.

If there's a non-computed property with the same name, it will get used for the pagination. You can witness the behaviour using [the previous commit on the branch](https://github.com/rhumaric/eleventy-computed-property-order-issue/tree/99d2ebe230669918baf2dbb23840fd1e9be57ad9). It contains a property with the same key defined in `data/supportedLocales`. The `test.liquid` template does paginate, but does it over the "static" properties not the computed ones.

**Expected behavior**

I'd have expected the computed property to be used for pagination in both cases, overriding the static ones when they are defined.

**Environment:**

- OS and Version: Ubuntu 18.04
- Eleventy Version: Using the `11ty/eleventy#9109e76` in package.json.

**Additional context**

**Comment by rhumaric** [comment]
Realised it wasn't the latest commit on master, but even with `11ty/eleventy#1fd4f02` the issue is still there, unfortunately.

**Comment by martinkz** [comment]
I'm not 100% sure, but I suspect "computed properties", as in functions that return an object being treated as being the object itself, are not a thing in eleventy. I've seen the concept in Vue where you can indeed treat them as a data object. If you look at the examples in the documentation for [computed data](https://www.11ty.dev/docs/data-computed/), they all use plain JS objects (or arrays).

The reason this fails is probably because supportedLocales is a type of function, not something iterable. Is there any particular reason you can't return an object or array instead of a function?

**Comment by rhumaric** [comment]
^_^ Computed properties are actually coming to Eleventy: https://www.11ty.dev/docs/data-computed/. The feature is on master so I was trying it out early.

**Comment by zachleat** [comment]
This docs page is extremely relevant to this discussion: https://www.11ty.dev/docs/advanced-order/

Hmm, let me ponder this one.

**Comment by zachleat** [comment]
We _could_ move this up in the order of operations but that would have a lot more undesirable implications, specifically I think it would create a circular dependency on computed permalinks (and you wouldn’t be able to access `collections` in computed functions). This might just be a out of the box limitation of the feature.

Hmm.

At the very least we should throw an error when computed data overrides something used as a pagination key.

**Comment by zachleat** [comment]
I’m pondering making this even more complicated to work as is out of the box. Updating pending. This feature is way more complicated than I expected 😅

**Comment by zachleat** [comment]
In the mean time use the `before` callback to transform pagination data.

https://www.11ty.dev/docs/pagination/#the-before-callback

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by rhumaric** [comment]
Hadn't thought of the `before` as the latest way for computing data before pagination, thanks for pointing it up. That said, the approach has two drawbacks:

- it needs an actual property for pagination to exist. You can always set a `_forComputedPagination` dummy in the data so that's not really a blocker.
- the data available inside the `before` is pretty limited, you only have access to array that's paginated. I'm assuming it's not really intended to fetch data from somewhere else.

All in all, I think I'm not going the right way about those supported locales, so I'll have a rethink about how I use things. Thanks again for the pointers though.

Regarding computing Eleventy special data props, I agree that could be super handy to give more flexibility.

**Comment by DenizAksimsek** [comment]
I would _really_ appreciate this feature &mdash; it would mean I could set `date` from git logs, as I attempted [here](https://github.com/DenizAksimsek/www/blob/70ce2b1816e40236a96c6755ceb80053d83bbb00/_data/eleventyComputed.js).

**Comment by danielmahal** [comment]
Did you find and alternative way of doing this @rhumaric ?
