### ISSUE TITLE
Eleventy computed data consuming collections

### ISSUE THREAD

**Issue by Snugug** [11ty/eleventy#1114]
**Describe the bug**
Computed data doesn't seem to work for outputting an object or `true` (but oddly enough, `false` works fine). Instead, an error `output.split is not a function` is thrown

**To Reproduce**

1. Create an `eleventyComputed.js` file in the global data directory.
2. Export an object with properties.
3. Have one property use the following: `data => true`. Note the error `output.split is not a function`
4. Change that property to use the following: `data => ({})`. Note the error `output.split is not a function`

**Expected behavior**
Expect to be able to set a computed property to either `true` or an object.

**Environment:**

- Mac OS 10.15.4
- Node v12.16.1
- Eleventy 0.11.0-beta.3

**Additional context**
I expect this to work from the [Advanced Details](https://www.11ty.dev/docs/data-computed/#advanced-details) section.

**Comment by zachleat** [comment]
Sorry about this! Some huge changes to computed data have happened recently but a beta hasn’t shipped with those yet. Can you retest with `github` master before I dive in deeper here?

**Comment by Snugug** [comment]
My code is in a slightly broken state r/n, but a quick check off of `master` no longer throws the error I was seeing. I'll be able to check Monday if it's rendering as expected.

Thanks for the quick reply! Love computed data, an excellent addition to 11ty!

**Comment by Snugug** [comment]
Ok! I've gone ahead and tested this and it is in fact _not_ rendering as expected, although this may be a different issue (and if it is I'm happy to open up a separate issue).

It _feels_ like computed data isn't hooked up to collections yet. Now that objects and `true` are valid output, I tried to actually build my output; part 1 was grabbing some content from a collection, only to find that the `collections` object is empty. Step 2 was to see if my computed data was available from a page in a collection, and found that my property wasn't added, and therefore not available, from an element in a collection.

This was all tested in `master`

**Comment by zachleat** [comment]
Thanks for your patience here—can you retest with the latest master?

**Comment by Snugug** [comment]
Huzzah! Thank you so much for the work on this! It does appear as if it's working as expected now! 😁

**Comment by zachleat** [comment]
Yay! Really appreciate you testing—thanks! I’ll ship a new beta shortly.
