### ISSUE TITLE
Eleventy builds on localhost are slow

### ISSUE THREAD

**Issue by davidrhoden** [11ty/eleventy#1115]
**Describe the bug**
My eleventy builds on localhost are taking longer and longer. The same builds on Netlify still take the normal amount of time.

**To Reproduce**
Commit a changed file to the repo to start the build.

**Expected behavior**
The site is not large, and the large files in it (images, they're not all that large) use the Large File Service. So a normal build that doesn't have a lot of images being uploaded for the first time should take about 30 seconds.

Instead, this happens (command line output)
```
[Browsersync] Reloading Browsers...
Writing _site/admin/index.html from ./admin/index.html.
(It hangs here for quite a while.)

... (writes an additional fifteen files) ...

Writing _site/404.html from ./404.md.
File changed: pages/colorchart.md
File changed: pages/difference/pros.md
File changed: _includes/assets/css/inline.css
Benchmark (Configuration): "jsmin" Nunjucks Filter took 391396ms (92.9%, called 15×)
Copied 4 items / Wrote 16 files in 421.35 seconds (26334.4ms each, v0.11.0-beta.3)
```

**Environment:**

- OS and Version: Mac High Sierra
- Eleventy Version v0.11.0-beta.3

**Additional context**
When I started using Eleventy, I didn't have this problem. It's a new thing. I started the site from a clone of the eleventy-netlify-boilerplate repository maintained by Dan Urbanowicz.
My public repo is https://github.com/davidrhoden/midsouthcoatings/.
I have the same issue with another Eleventy/Netlify public repo, https://github.com/davidrhoden/davidrhoden-basic-netlify

**Comment by hly990** [comment]
I have the same problem.

**Comment by mpalpha** [comment]
same issue here as well.

**Comment by binyamin** [comment]
@zachleat You know the version history better than anyone. Do you have any idea what might be causing this?

@davidrhoden Can you please give us two different eleventy versions (one slow and one quick), so we can figure out what's going on?

**Comment by davidrhoden** [comment]
> @davidrhoden Can you please give us two different eleventy versions (one slow and one quick), so we can figure out what's going on?
Well, the issue was not the version. I used the (excellent) eleventy-netlify-boilerplate repo created by Dan Urbanowicz to seed my sites. That repo includes a JS minifier and a CSS minifier. Those minifiers slow down the build a lot. As my site (https://davidrhoden.com) doesn't use much JS or CSS, I disabled the minifiers and it led to a striking speed increase.

I guess I could turn them back on for "production" builds if I wanted but the Lighthouse score is still quite good even without the minification.

**Comment by binyamin** [comment]
> Those minifiers slow down the build a lot

That sounds like it's related to the boilerplate you used. Is there a reason you opened the issue _here_ (in 11ty/eleventy)?

**Comment by davidrhoden** [comment]
It is related to the minifiers in the boilerplate, but I didn't know that
at the time. I thought I had been encouraged to open issues in the eleventy
community issues.

David Rhoden
315 Tricou Street
New Orleans, Louisiana 70117

504-812-8475 <5048128475>
david@davidrhoden.com
https://davidrhoden.com

**Comment by binyamin** [comment]
>  I thought I had been encouraged to open issues in the eleventy
community issues.

Ah, ok. Do you mind if I close this issue, though?

**Comment by davidrhoden** [comment]
I don't mind.

David Rhoden
315 Tricou Street
New Orleans, Louisiana 70117

504-812-8475 <5048128475>
david@davidrhoden.com
https://davidrhoden.com
