### ISSUE TITLE
Adding Web Component definitions to output pages

### ISSUE THREAD

**Issue by jdvivar** [11ty/eleventy#1117]
Hi

I'm using Eleventy to create a web page that is composed of Web Components. Let's say my page output is:
```html
<html>
  <body>
    <my-custom-tag></my-custom-tag>
  </body>
</html>
```

And the desired output is:
```html
<html>
  <body>
    <my-custom-tag></my-custom-tag>
    <script type="module" src="/js/components/my-custom-tag/my-custom-tag.js"></script>
  </body>
</html>
```

In Eleventy I can easily do that with a transform in its config file. In this case I'm looking for closing tags, making a set of them (to only load once each) and add them down in the body tag with `jsdom`:
```js
const jsdom = require('jsdom')
const { JSDOM } = jsdom

module.exports = function(eleventyConfig) {
  eleventyConfig.addTransform('adding-wc-definitions', function(content, outputPath) {
    if (outputPath.endsWith('.html')) {
      const dom = new JSDOM(content)
      const body = dom.window.document.body.innerHTML
      const regex = /<\/(\w+(-\w+)+)>/g
      const matches = body.matchAll(regex)
      const tagsSet = new Set()
      for (match of matches) {
        tagsSet.add(match[1])
      }
      for (tag of tagsSet) {
        console.log('Adding Web Component: ', tag)
        dom.window.document.body.insertAdjacentHTML('beforeend', `<script type="module" src="/js/components/${tag}/${tag}.js"></script>`)
      }
      return dom.serialize()
    }
    return content
  })
}

return {
    dir: {
      input: 'src',
      output: 'public'
    }
  }
}
```

Is there a better way to do this? Maybe a transform is not what I should be using as I'm new to Eleventy.
In any case, this could be a great example for others to work on or an idea for a plugin.

I ❤️ Eleventy

**Comment by jdvivar** [comment]
@jdevega This is the solution I was talking to you about yesterday

**Comment by btopro** [comment]
https://github.com/elmsln/hax11ty

we're experimenting with https://github.com/elmsln/unbundled-webcomponents methodology which is a lazi-hydration script that leverages an unbundled build routine to figure out what elements need hydrated with a mutation observer at run time.

I'm still trying to figure out how to do local development of web components in a hax11ty routine for local development / testing but it's what we're playing with to achieve this.

**Comment by jdvivar** [comment]
I've finally decided to publish a plugin regarding this:
https://github.com/jdvivar/eleventy-plugin-add-web-component-definitions
