### ISSUE TITLE
Retrieving from APIs - struggling with async and Airtable API

### ISSUE THREAD

**Issue by danfascia** [11ty/eleventy#1122]
I'm trying to retrieve data from the airtable API using the node client, I've got that aspect of it working perfectly fine but I stumble at the final hurdle which is to correctly implement an async data source out of this in 11ty.

Note that if I debug by writing the output to file (see commented out line) it works totally fine so I know that the data retrieval and structuring is fine.

Can anyone tell me what I am doing wrong to pass this data through 11ty as a data source? Thanks

```
require('dotenv').config()
const fs = require('fs');

var Airtable = require('airtable');
var base = new Airtable({apiKey: process.env.AIRTABLE}).base('appaWmn4hIP1yBIHf');

// console.log("Airtable API Key: "process.env.AIRTABLE)

const allCases = []

module.exports = async () => {
    return await base('Cases').select(
        {view: 'All cases'}
    ).eachPage( function page(records, fetchNextPage){
        records.forEach( (record) => {
            allCases.push(
                {
                    "id" : record._rawJson.id,
                    ...record._rawJson.fields
                }
            )
        } )
        fetchNextPage();
    }, function done(err) {
        if (err) { console.log(err); return }
        else 
        {
            console.log(allCases)
            //fs.writeFileSync('./_data/cases.json',JSON.stringify(allCases))
            return allCases
        }
       } )
}
```

**Comment by zachleat** [comment]
Without a reproducible test case and without experience with Airtable, I can’t be of much help here—sorry! Feel free to reply with a demo test case and I can reopen.

**Comment by danfascia** [comment]
It's OK I don't expect specific advice - I was pushing my luck asking on airtable.

I guess my request is for a generic example of how to implement a correct promise based API request to serve 11ty's data engine in the best way.

It's easy enough for something totally straightforward (stargazers) but once you bring in things like paging an API and building out the results - all in an async loop to keep 11ty happy... I find things tend to fail harder

**Comment by dmgawel** [comment]
@danfascia try with a Promise:

```js
require("dotenv").config();

var Airtable = require("airtable");
var base = new Airtable({ apiKey: process.env.AIRTABLE }).base(
  "appaWmn4hIP1yBIHf"
);

module.exports = function() {
  return new Promise((resolve, reject) => {
    const allCases = [];

    base("Cases")
      .select({ view: "All cases" })
      .eachPage(
        function page(records, fetchNextPage) {
          records.forEach(record => {
            allCases.push({
              id: record._rawJson.id,
              ...record._rawJson.fields
            });
          });
          fetchNextPage();
        },
        function done(err) {
          if (err) {
            reject(err);
          } else {
            resolve(allCases);
          }
        }
      );
  });
};
```

**Comment by justin-wallace** [comment]
> @danfascia try with a Promise:
> 
> ```js
> require("dotenv").config();
> 
> var Airtable = require("airtable");
> var base = new Airtable({ apiKey: process.env.AIRTABLE }).base(
>   "appaWmn4hIP1yBIHf"
> );
> 
> module.exports = function() {
>   return new Promise((resolve, reject) => {
>     const allCases = [];
> 
>     base("Cases")
>       .select({ view: "All cases" })
>       .eachPage(
>         function page(records, fetchNextPage) {
>           records.forEach(record => {
>             allCases.push({
>               id: record._rawJson.id,
>               ...record._rawJson.fields
>             });
>           });
>           fetchNextPage();
>         },
>         function done(err) {
>           if (err) {
>             reject(err);
>           } else {
>             resolve(allCases);
>           }
>         }
>       );
>   });
> };
> ```

Years later, this helped me out a ton. Thank you!
