### ISSUE TITLE
tags in front matter: comma-separated like in Ghost?

### ISSUE THREAD

**Issue by autonome** [11ty/eleventy#1124]
**Describe the bug**

I'm migrating from Ghost, where all my tags in front matter are CSV, eg:

```
tags: a, b, c
```

Eleventy doesn't seem to support this. Is there a way I can do this? Either a js function or built-in way?

Thanks!

**Comment by hirusi** [comment]
eleventy does support [multiple tags](https://www.11ty.dev/docs/collections/#tag-syntax). I am assuming your front matter is in YAML. You can use RegEx find and replace to make this an array.

**Comment by danfascia** [comment]
The IP example is not official YAML, that's why it doesn't work.

YAML accepts either of the following notations
```
tags: [a, b, c]

tags:
  - a
  - b
  - c
```

**Comment by autonome** [comment]
Closing as not-a-bug! Thanks @danfascia.

**Comment by zachleat** [comment]
Home base for this one is #2820 moving forward
