### ISSUE TITLE
This is just a question. Is there a roadmap for 11ty?

### ISSUE THREAD

**Issue by amandeeepsingh** [11ty/eleventy#1128]
I would like to know what the future plans for 11ty are. 
Thanks!

**Comment by reubenlillie** [comment]
@amandeeepsingh, are you looking for something other than what's on the Projects boards? https://github.com/orgs/11ty/projects/5

**Comment by amandeeepsingh** [comment]
I am thinking of using 11ty for my project. I am trying to find out what plans does 11ty have for future. Like list of upcoming features.

PS: I am also evaluating if 11ty will be supported by community in future.

Thanks!

**Comment by zachleat** [comment]
https://github.com/orgs/11ty/projects is the link for the project boards

**Comment by amandeeepsingh** [comment]
Thanks! @zachleat

**Comment by robinmetral** [comment]
Looks like boards aren't used anymore — any roadmap anywhere? Now that @zachleat is going to be [working on 11ty full time](https://www.zachleat.com/web/independent-sustainable-11ty/) (congrats!), it would be nice to have a rough idea of where the project is going :slightly_smiling_face: 

The blog post linked above says:

> Practically speaking this means that for the very first time in 11ty’s history, I will be working independently on 11ty full time. This means increased iteration speed, more responsive official support, more features and bug fixes, and faster releases.

It would be great to have a place to get an idea of what these new features will be, broadly speaking. (And perhaps give early feedback?)
