### ISSUE TITLE
Layout chaining should check for recursion

### ISSUE THREAD

**Issue by fhemberger** [11ty/eleventy#1131]
**Describe the bug**
I ran into a loop during build because I was carelessly using search & replace in my code. 😉 

**To Reproduce**
1. Create a layout `page.njk` with the frontend matter

   ```yaml
   ---
   layout: page.njk
   ---
   ```
2. Create a page using this layout
3. Run `npx eleventy` 

Eleventy seemed to be happy to oblige and I just noticed my mistake because the build seemed to run forever. (I didn't wait for a memory issue to occur.)

**Expected behavior**
Either:
- Eleventy should detect accidental layout recursion and stop the build immediately with an error message.

Or:
- Eleventy should issue a performance warning after the _n-th_ nested layout (n=10?) in general
- Eleventy should stop the build with an error message after the _n-th_ nested layout (n=?)

**Environment:**

- OS and Version: macOS 10.15.4
- Eleventy Version: 0.10.0

**Comment by Ryuno-Ki** [comment]
I find the `OR` variant easier to realise technical (less bookkeeping). There are examples in the wild for it, e.g. preventing fork bombs.

**Comment by fhemberger** [comment]
Hmm, I'd rather say the first variant is easier to implement:

Have an array `layouts`, and whenever you process frontend matter with `layout: ...`, check if the layout is already in the `layouts` array stop immediately, otherwise store the layout name in the array.

And if you produce a loop within the template using the template language's include mechanisms, this should be handled by the template language parser itself.

**Comment by zachleat** [comment]
This was fixed with https://github.com/11ty/eleventy/pull/2076 and is available on 2.0
