### ISSUE TITLE
Computed data: directory data calling global data needs to be defensively written in v0.11.0-beta.4

### ISSUE THREAD

**Issue by paulrobertlloyd** [11ty/eleventy#1137]
**Describe the bug**
For every page on my site, I want to provide a list of webmentions that relate to it. 

A global data file, `webmentions.js`, requests JSON from an API – which now, thanks to 11ty-cache-assets, is much simplified and improved. Thank-you 🙏🏻

A function, `getWebmentions()`, takes an array of `webmentions` and a URL, and returns an array containing those webmentions that target that URL. Previously I achieved some of this in my templates, but with computed data, I can now have this code sit in one place, and be accessible to all pages, by using a data file for my `_content` directory:

```js
// src/content/content.11tydata.js

const getWebmentions = require('../../lib/utils/get-webmentions');

module.exports = {
  eleventyComputed: {
    webmentions: data => {
      const url = data.app.url + data.page.url;
      return getWebmentions(data.webmentions, url);
    }
  }
};
```

This worked until at least commit [046740](https://github.com/11ty/eleventy/tree/0467409a3b69560971a09e2742723b86c4406f9f), but recent changes mean I now have to do the following:

```js
// src/content/content.11tydata.js

const getWebmentions = require('../../lib/utils/get-webmentions');

module.exports = {
  eleventyComputed: {
    webmentions: data => {
      const url = data.app.url + data.page.url;
      if (data.webmentions !== undefined) {
        return getWebmentions(data.webmentions, url);
      }
    }
  }
};
```

Is this the expected behaviour? 

Inspecting this a little, it looks like 11ty now loops over the data several times after different calculations before definitive site data object is returned. 

I know there’s a few things going on here – not least directory data calling global data – which probably throws up some cascade issues. Let me know if you need more details!

**Comment by zachleat** [comment]
Per #1138 I’m assuming you were not on the latest beta?

**Comment by zachleat** [comment]
Now I’m re-reading the title here, hmm

**Comment by paulrobertlloyd** [comment]
When I `log` the data, data gets passed several times, and only on the last pass does is it structured as expected.

**Comment by zachleat** [comment]
Maybe marginally related but for my sake I’m cross referencing https://github.com/11ty/eleventy/issues/919

**Comment by zachleat** [comment]
Is this checked in to your repo somewhere? I _think_ this may be unrelated to computed data

**Comment by paulrobertlloyd** [comment]
Yup you can see the current version here: [content.11tydata.js](https://github.com/paulrobertlloyd/paulrobertlloyd-v4/blob/master/src/content/content.11tydata.js)

**Comment by zachleat** [comment]
@paulrobertlloyd Can you try again here with the latest on `master`? I made some more improvements/added some more tests.

Also your repo is immaculate—wow I am very impressed 😇

**Comment by paulrobertlloyd** [comment]
Calling **global data**, I previously had to write this:

```js
webmentions: data => {
  const url = data.app.url + data.page.url;
  if (data.webmentions.children) {
    return getWebmentions(data.webmentions.children, url);
  }
}
```

With the latest commit to `master`, I can return to what I had before:

```js
webmentions: data => {
  const url = data.app.url + data.page.url;
  return getWebmentions(data.webmentions.children, url);
}
```

👍

* * *

Calling **collection data**, I’d like to write:

```js
related_articles: data => {
  const articles = data.collections.article;
  const related = data.related ? data.related : [];
  return articles.filter(article => related.includes(article.url));
}
```

but on `master` I still need to check that a collection exists before I can query it:

```js
related_articles: data => {
  const articles = data.collections.article;
  const related = data.related ? data.related : [];
  if (articles) {
    return articles.filter(article => related.includes(article.url));
  }
}
```

Is it unreasonable to expect a collection to available for querying without having to check it exists first?

**Comment by paulrobertlloyd** [comment]
Calling **frontmatter data** (`data.trip_id`), I’d like to write:

```js
related_trips: data => {
  const trips = data.collections.trip;
  const tripId = data.trip_id ? data.trip_id : [];
  return trips.filter(trip => tripId.includes(trip.data.trip.id));
}
```

but on `master` I need to check both for collection data _and_ frontmatter data:

```js
related_trips: data => {
  const trips = data.collections.trip;
  if (trips && data.trip_id) {
    return trips.filter(trip => data.trip_id.includes(trip.data.trip.id));
  }
}
```

**Comment by zachleat** [comment]
Per front matter, the reason `if (trips && data.trip_id) {` is required there is because your `travel.liquid` file is running `eleventyComputed` data from `travel.11tydata.js`, but has no trip_id’s associated with it.

The collections thing is a legitimate bug.

**Comment by zachleat** [comment]
Just tested your repo with some new changes on master. Please confirm that it’s working (sans the data.trip_id exemption per the previous note).

**Comment by paulrobertlloyd** [comment]
Fantastic! This seems to have fixed things, with it all working as expected. Thanks @zachleat! 👍
