### ISSUE TITLE
How would you handle this in Liquid?

### ISSUE THREAD

**Issue by bosslee** [11ty/eleventy#1141]
Hi there

I am trying to make a site with WP.com as the headless CMS and 11ty as the front end
The request from WP.com comes as the following:
`{
    "found": 12,
    "posts": [
        {
            "ID": 69,
            "date": "2020-04-26T13:06:12+08:00",
            "title": "This is it",
            "content": "\n<p>And here we go again </p>\n"
        }
    ],
    "meta": {
        "links": {
            "counts": "https://public-api.wordpress.com/rest/v1.1/sites/160694989/post-counts/post"
        },
        "next_page": "value=2020-04-26T13%3A06%3A12%2B08%3A00&id=69",
        "wpcom": true
    }
}`

Like to ask how would you handle this in Liquid?
If I do `{{ content }}` those '/m' characters are still around
![image](https://user-images.githubusercontent.com/993948/80789224-ed079b80-8bbd-11ea-8c15-db6dcf5d198f.png)

Thank you very much

**Comment by pdehaan** [comment]
Not sure if this would work (or if it's supported in the current version of Liquidjs bundled with 11ty), but does the Liquid [`strip_newlines`](https://liquidjs.com/filters/strip_newlines.html) filter work?
Ie: `{{ content | strip_newlines }}`

Not sure if they're still newlines by that point that you're seeing them, or just a string that is awkwardly `\n` which you'd have to try and strip via a filter or computedData or something maybe.

**Comment by bosslee** [comment]
Thank you very much!
> Ie: {{ content | strip_newlines }}
Will take a look at it 

> which you'd have to try and strip via a filter or computedData or something 
thanks for the tip
will take a look too
