### ISSUE TITLE
Parse markdown inside global data files

### ISSUE THREAD

**Issue by mikehaart** [11ty/eleventy#1142]
Is there a way to parse markdown inside a JSON global data file using liquid?

**Comment by Bagera** [comment]
What I have done in this case is to make a filter that can take the string from JSON and return HTML (remember to mark the return value as safe or html will be stepped out). You can use the same markdown library as 11ty (markdownit if I remember correctly). If you made universal filters before, it is quite easy. If not, I would recommend reading through someone else's plugin to get inspired.

**Comment by Ryuno-Ki** [comment]
The package is called `markdown-it`.

**Comment by mikehaart** [comment]
Thanks both, using filters with that library looks perfect 👌

**Comment by mikehaart** [comment]
Wanted to share the filter I ended up using, kudos from #684

```js
// .eleventy.js
module.exports = function(eleventyConfig) { 
 ...
  const MarkdownIt = require("markdown-it");
  const mdRender = new MarkdownIt();
  eleventyConfig.addFilter("renderUsingMarkdown", function(rawString) {
    return mdRender.render(rawString);
  });
  ...
}
```

And in the liquid file
`{ index.contentOutput | renderUsingMarkdown }`

**Comment by patrikalienus** [comment]
> Wanted to share the filter I ended up using, kudos from #684
> 
> ```js
> // .eleventy.js
> module.exports = function(eleventyConfig) { 
>  ...
>   const MarkdownIt = require("markdown-it");
>   const mdRender = new MarkdownIt();
>   eleventyConfig.addFilter("renderUsingMarkdown", function(rawString) {
>     return mdRender.render(rawString);
>   });
>   ...
> }
> ```
> 
> And in the liquid file
> `{{ index.rawMarkdown | renderUsingMarkdown }}`

@mikehaart Any idea on how to make this add the proper classes to the <pre> tags as well? Otherwise eleventy syntax highlighting won't work properly.
