### ISSUE TITLE
simple shortcodes question

### ISSUE THREAD

**Issue by mvolkmann** [11ty/eleventy#1148]
I have this in my `.eleventy.js` file:

```js
  eleventyConfig.addShortcode(
    'aTargetBlank',
    (url, text) => `<a href="${url}" target="_blank">${text}</a>`
  );
```

I'm trying to use it in a Markdown file using Nunjucks like this:

```markdown
See {{ aTargetBlank 'https://www.staticgen.com', 'staticgen.com' }}
```

When I build my site I get the error "expected variable end" on this line.
What silly thing am I doing wrong?

**Comment by pdehaan** [comment]
I’m not at my laptop, but is it `{{` or `{%`?
https://www.11ty.dev/docs/shortcodes/

**Comment by mvolkmann** [comment]
Thanks, that was it! It was a silly mistake on my part as I suspected.
