### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by piyushpaliwal** [11ty/eleventy#1151]
### Describe the bug
I get an error upon trying to perform `npx eleventy` stating `Cannot read property 'length' of undefined`. Although, the error sounds pretty basic but unfortunately, being new to the platform, I am unable to find out the root cause.

#### Source Repo: [https://github.com/piyushpaliwal/ecrm_contentcms.git](https://github.com/piyushpaliwal/ecrm_contentcms.git)
I have though narrowed it down to `index.njk` file. Even keeping a blank index.njk file throws this error. The moment you remove this file or change it to `index.md` and put a Front Matter on this page (like below), it starts to throw the error.
```
---
layout: "layouts/default.njk"
---
```
### Expected behavior
I was hoping that index.html will be output

### Screenshots
![image](https://user-images.githubusercontent.com/635693/80991196-4806f000-8e55-11ea-8b4d-ac2241c484fb.png)

### Environment:
- OS and Version: Ubuntu 18.04 (WSL)
- Eleventy Version: 0.10.0

**Comment by piyushpaliwal** [comment]
Ok, found the issue. I knew it was silly. I added a collection by calling an API and missed returning it in the `addCollection` method of `.eleventy.js` file.

**Comment by zachleat** [comment]
Related to https://github.com/11ty/eleventy/issues/3467
