### ISSUE TITLE
programmatically run npx eleventy from different directory

### ISSUE THREAD

**Issue by gabrielsze** [11ty/eleventy#1155]
**Describe the bug**
Currently the `npx eleventy` command works great in building the pages necessary! Also, I wrote a script to run this command programmatically, and it works within the directory. It looks something like this

**trigger.js**
```
const { exec } = require("child_process");

exec("npx eleventy", (error, stdout, stderr) => {
    if (error) {
        console.log(`error: ${error.message}`);
        return;
    }
    if (stderr) {
        console.log(`stderr: ${stderr}`);
        return;
    }
    console.log(`stdout: ${stdout}`);
});
```
When I run `node trigger.js` (in the same directory), it works great and builds my pages.

However, the problem happens when I move my eleventy components into another folder (named hosting). When i place all my files into the hosting folder, and manually run `npx eleventy`, it works!

But once I use my script (inside the hosting folder), it fails with the following error.
(I run `node hosting/trigger.js`)

```
error: Command failed: npx eleventy
Problem writing Eleventy templates: (more in DEBUG output)
> TemplateLayoutPathResolver directory does not exist for dive_list_view.njk: _includes

`Error` was thrown:
```

**My directory structure**
<img width="241" alt="Screenshot 2020-05-06 at 10 31 32 PM" src="https://user-images.githubusercontent.com/46477732/81189606-59810100-8fe9-11ea-9c51-b862a12b74ae.png">

**Comment by zachleat** [comment]
Maybe you want to add a `cwd` to your exec call? https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

**Comment by zachleat** [comment]
I don’t think this is a problem specific to Eleventy though—I don’t have bandwidth to troubleshoot this right now—sorry!

**Comment by zachleat** [comment]
cross posting https://github.com/11ty/eleventy/issues/620

**Comment by zachleat** [comment]
First draft of the docs for this feature are available: https://www.11ty.dev/docs/programmatic/
