### ISSUE TITLE
Wrong date locale displayed after deployment

### ISSUE THREAD

**Issue by ironnysh** [11ty/eleventy#1157]
**Describe the bug**
I'm working on a new 11ty-based website in Hebrew, where the date format is dd.mm.yyyy (eg, 24.12.2020). To avoid using a 3rd party library, I've written a filter to properly display dates. The dates are rendered correctly on my local build, but revert to the American format (12/24/2020) once I deploy. I've tried various workarounds, but can't get 11ty to properly present the date. Thank you very much!

**To Reproduce**
1. in .eleventy.js:
```
eleventyConfig.addFilter("hebrewDate", dateObj => {
const options = { year: 'numeric', month: 'long', day: '2-digit' };
return date = new Date().toLocaleDateString('he-IL', options);
});
```
2. In a page I want to show the date:
`{{ post.date | hebrewDate }}  
`
**Screenshots:**
Wrong (deployed): 
![Screen Shot 2020-05-07 at 18 54 46](https://user-images.githubusercontent.com/63248335/81325608-e8992200-9098-11ea-9d6b-fa98846263a3.png)
Correct (local): 
![Screen Shot 2020-05-07 at 19 25 15](https://user-images.githubusercontent.com/63248335/81325644-f3ec4d80-9098-11ea-9c49-a3bfbb7ce664.png)

**Comment by pdehaan** [comment]
Interesting. Not sure why it'd work locally but not on deployed version...

But there might be a small bug in your original filter where you don't seem to be using `dateObj` argument at all and are returning a confusing assignment to `date = new Date()`. 

```js
// .eleventy.js
module.exports = (eleventyConfig) => {
  eleventyConfig.addFilter("hebrewDate_old", (dateObj) => {
    const options = { year: "numeric", month: "long", day: "2-digit" };
    return date = new Date().toLocaleDateString("he-IL", options);
  });

  eleventyConfig.addFilter("hebrewDate", (dateObj) => {
    const options = { year: "numeric", month: "long", day: "2-digit" };
    return new Date(dateObj).toLocaleDateString("he-IL", options);
  });

  return {
    dir: {
      output: "www",
    },
  };
};
```

```liquid
---
title: Hello
---

A: {{ "2020-04-19" | hebrewDate_old }}<br/>
B: {{ "2020-04-20" | hebrewDate }}<br/>

{#
A: 07 במאי 2020<br/>
B: 19 באפריל 2020<br/>
#}
```

**Comment by ironnysh** [comment]
Hi @pdehaan,
Thank you very much for fixing my code! I’m afraid I’m a JavaScript novice.
However, it still doesn’t seem to solve the mystery... If it makes any difference, I reference the post’s date from front matter, not writing it directly like in your example.

**Comment by pdehaan** [comment]
@ironnysh Do you have a public repo somewhere that I can look at?

**Comment by pdehaan** [comment]
I'm seeing the same results if I use frontmatter or hardcoded dates (using Eleventy@0.10.0 and Nunjucks):

```nunjucks
---
title: Hello
date: 2020-04-22
---

A: {{ "2020-04-19" | hebrewDate_old }}<br/>
{# A: 07 במאי 2020 #}

B: {{ "2020-04-20" | hebrewDate }}<br/>
{# B: 19 באפריל 2020 #}

C: {{ date | hebrewDate }}<br/>
{# C: 21 באפריל 2020 #}
```

**Comment by ironnysh** [comment]
Hi @pdehaan,
Thanks for taking the time to help.
I cloned my local 11ty build in a [public repo](https://github.com/ironnysh/11ty-test).
For now, I'm calling **_hebrewDate_** only on the homepage; marked it to make it clear.

**Comment by ironnysh** [comment]
Yeah, on local it looks fine for me also. It’s an error from me messing around with the code in the morning :-) removed it and now the deploy to Netlify was completed. You can see that the date is presented in the American format: https://happy-turing-ecd2f7.netlify.app/

**Comment by zachleat** [comment]
I think some relevant discussion about this here: https://stackoverflow.com/questions/14792949/date-tolocaledatestring-in-node

I’d recommend moving away from `toLocaleDateString` to use a library for this. I’ve had good luck with Luxon—maybe https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-toLocaleString would work for you.

**Comment by ironnysh** [comment]
Hi @zachleat ,
Thanks a lot for pointing me to the right direction :-) hadn’t crossed my mind that it’s actually a Node thing.
The locale issue has been resolved in v13, but since Netlify uses an earlier version my site was still affected. Upgraded to current Node during the build and all is well now!
