### ISSUE TITLE
Is it possible to grab the landing page permalink for a paginated collection

### ISSUE THREAD

**Issue by alexcarpenter** [11ty/eleventy#116]
Right now I am working on creating a pagination component but running into issues getting back to the landing page `if pagination.pageNumber == 1`.

For example, if I am on `/archives/` and hit an older pagination link to bring me to `/archives/page/1` now I am trying to set the newer navigation link back to `/archives/`.

**Comment by zachleat** [comment]
Can you attach your pagination template?

Also what do you mean by “older pagination link”?

**Comment by kleinfreund** [comment]
> Also what do you mean by “older pagination link”?

They are referring to the *Older*/*Newer* links going to the *next* or *previous* page.

**Comment by alexcarpenter** [comment]
Here is the pagination code I am working with

```
<nav class="c-pagination">
  {% if pagination.nextPageLink -%}
    {%- assign nextPageNumber = pagination.pageNumber | plus: 1 -%}
    {%- assign nextPageLink = nextPageNumber | prepend: 'page/' -%}
    <a class="c-pagination__item" href="{{ page.url }}{{ nextPageLink }}" rel="prev">Older</a>
  {%- endif %}
  {% if pagination.previousPageLink -%}
    {%- assign previousPageNumber = pagination.pageNumber | minus: 1 -%}
  {%- if pagination.pageNumber == 1 -%}
    <!-- How do I get back to landing paginated page -->
    {%- assign previousPageLink = page.url -%}
  {%- else -%}
    {%- assign previousPageLink = previousPageNumber | prepend: 'page/' -%}
  {%- endif -%}
    <a class="c-pagination__item" href="{{ previousPageLink }}" rel="next">Newer</a>
  {%- endif %}
</nav>
```

And here is where it is used https://github.com/alexcarpenter/alexcarpenter.github.io/blob/develop/src/_includes/layouts/index.liquid#L8

I am not sure how to set the link to get back to the initial paginated landing page.

**Comment by alexcarpenter** [comment]
Solved in the latest release, making use of `page.fileSlug`.
