### ISSUE TITLE
Is it possible to pre-process a Javascript template and return the content to a Liquid/Nunjucks one?

### ISSUE THREAD

**Issue by noelforte** [11ty/eleventy#1160]
**EDIT 05/11/2020:** Simplified my original question to avoid confusion about what I'm asking.

If I have multiple javascript templates (.11ty.js) that do different things and then return some content, ie 

```
// do stuff to get results

module.exports = class {
  render() {
    // return results
  }
}
```

and want to include their results it into a liquid/nunjucks template, I'm thinking I could just do a:

```
{% include "dynamic-content.11ty.js" %}
```

but that only inserts the raw content of the js template rather than what it renders. Is it possible to have Eleventy process the JS template first and then have the results included in a different template? Or is this something better handled by a shortcode?

**Comment by noelforte** [comment]
Adding a follow-up, went through the documentation for [javascript templates](https://www.11ty.dev/docs/languages/javascript/) and even with the case of raw values i.e.:

```
module.exports = "<p>Zach</p>";
```

...in a `myinclude.11ty.js` file and then in a `page.liquid` file:

```
{% include "myinclude.11ty.js" %}
```

returns:

```
module.exports = "<p>Zach</p>";
```

as is, rather than returning the value itself. To clarify my question further, is there a way I can ask eleventy to process my javascript first, before including it in my liquid files?

**Comment by zachleat** [comment]
I believe this is a duplicate of enhancement request #148—do you agree?

**Comment by zachleat** [comment]
A short-term thing you can do is put the stuff into a collection and reference that.

**Comment by noelforte** [comment]
@zachleat possibly? I was poking around on #272 and am in this case experimenting with using 11ty to run some simple build steps to generate CSS, JS, etc. 

While the flexibility of rendering one template type within another would certainly be awesome, what I'm hoping to do currently is handle the processing of output within a template, and if it's small enough, inline it. 

My quick fix so far is to have these sorts of things handled by a universal shortcode that could either run in a nunjucks/liquid template and inline the result or run in a JS template and render the result with the output permalink being `/main.css` or something to that end.

I'll look at the documentation again, how would a collection help order the processing steps?

**Comment by LostKobrakai** [comment]
I stumbled over this by trying to have an SSR components' html included in otherwise plain old html. I tried to include an `.11ty.js` file from an `.ejs` file naively thinking I can compose multiple ways of templating just parts of a website. This would be awesome an super simple way to do that.

**Comment by noelforte** [comment]
Coming back to this: filters and shortcodes ended up being the best solve for me with regard to "computing a thing"/"injecting results in template". With a configured shortcode that either takes additional parameters or not, I can either use it within a template to return the results of the job, or create a template that just contains the shortcode to generate a file containing the results of the job.

In addition, if I dont need to access the shortcode project-wide, then I can cut overhead by having a JS template run what would have otherwise come from the shortcode, or import the shortcode function from a config file. Lots of choices. Thanks for all the responses on this, going to close now.
