### ISSUE TITLE
Website has no `background-color`

### ISSUE THREAD

**Issue by runxel** [11ty/eleventy#1162]
Not really a documentation _content_ wise, but still a minor issue: The website has no background-color set, but a text color, leading to this look:

![website](https://user-images.githubusercontent.com/2277182/81495004-4ef68e00-92ad-11ea-9008-0933249a237b.png)

Maybe it`s time for a dark theme? 😉

**Comment by reubenlillie** [comment]
Related to [#406](https://github.com/11ty/11ty-website/issues/406) and [#407](https://github.com/11ty/11ty-website/issues/407).

**Comment by zachleat** [comment]
I believe this was fixed awhile back, he says embarrassingly.
