### ISSUE TITLE
Error messaging when you attempt to set reserved Eleventy Data names

### ISSUE THREAD

**Issue by Dexus** [11ty/eleventy#1173]
I would like to see a Documentation with alle reserved variables like `page` && `page.xxx` or `content` if you use it with markdown and a layout file in nunjucks or something else.

It is difficult to find all the reserved variables, and it looks like if I use them as file in `_data` folder, it will not merged or respected.

**Comment by zachleat** [comment]
https://www.11ty.dev/docs/data-eleventy-supplied/ does exist

Going a little further, I think we should add some error messaging if you try to set one of these. I’m going to swap this issue to include that as well.

One of these issues is using `alias: page` with pagination (see https://github.com/11ty/eleventy/issues/2161#issuecomment-1146697538)

**Comment by zachleat** [comment]
Swapping to bug behavior. Some of this work is finished to freeze the `pkg` and `eleventy` properties in global data in this branch: https://github.com/11ty/eleventy/tree/frozen-reserved-data

We’ll give an escape hatch here to let folks disable this behavior in configuration: `eleventyConfig.setFreezeReservedData(false);`

**Comment by zachleat** [comment]
Fixed by #3251 Shipping with 3.0.0-alpha.7

**Comment by zachleat** [comment]
Preview docs deploying here: https://11ty-website-git-v3-11ty.vercel.app/docs/data-eleventy-supplied/#frozen-data
