### ISSUE TITLE
Passthrough on Different Environment Variables?

### ISSUE THREAD

**Issue by huphtur** [11ty/eleventy#1177]
In `.eleventy.js` I have the following line: `eleventyConfig.addPassthroughCopy('./src/styles.css');` and the styles file is passed through just fine (as expected). 

Is it possible to disable the passthrough of that particular file [on production](https://www.11ty.dev/docs/data-js/#example-exposing-environment-variables) via `ELEVENTY_ENV=production`?

**Comment by huphtur** [comment]
Oh wait, this worked:

```javascript
  if (process.env.ELEVENTY_ENV != 'production') {
    eleventyConfig.addPassthroughCopy('./src/styles.css');
  }
```

**Comment by hirusi** [comment]
@huphtur Please close the issue if you see fit. Looks like it's solved! :)
