### ISSUE TITLE
Deprecation warnings on install

### ISSUE THREAD

**Issue by mmc41** [11ty/eleventy#1178]
**Describe the bug**
Deprecation warnings on install that affect unsupported code, supported node versions and potential security issues.

```
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

**To Reproduce**
npm install

**Expected behavior**
No warnings on install.

**Environment:**

- OS and Version: Mac
- Eleventy Version 0.11.0

**Additional context**

**Comment by Ryuno-Ki** [comment]
Could you run the following commands and share their output?

```sh
npm ls chokidar
npm ls fsevents
npm ls resolve-url
npm ls urix
npm ls core-js
```

This way, we can see, which dependency pulls in the deprecated version.

**Comment by mmc41** [comment]
**npm ls chokidar**
npm ls fsevents
npm ls resolve-url
npm ls urix
npm ls core-js/...
└── (empty)

**npm ls fsevents**
npm ls resolve-url
npm ls urix
npm ls core-js/...
└── (empty)

**npm ls resolve-url**
npm ls urix
npm ls core-js/...
└── (empty)

**npm ls urix**
npm ls core-js/...
└── (empty)

**npm ls core-js**
...
└── (empty)

**Comment by josebolos** [comment]
I'm not getting the same deprecation warnings as OP, but all of the dependencies seem to be coming from `browser-sync`, except for `core-js` which comes from `pug`:

```sh
$ npm ls chokidar@2.1.8 fsevents@1.2.13 resolve-url@0.2.1 urix@0.1.0 core-js@2.6.11
eleventysite@0.0.1 /home/josebolos/devel/eleventy
└─┬ @11ty/eleventy@0.11.0
  ├─┬ browser-sync@2.26.7
  │ ├─┬ chokidar@2.1.8 
  │ │ └── UNMET OPTIONAL DEPENDENCY fsevents@1.2.13 
  │ └─┬ micromatch@3.1.10
  │   └─┬ snapdragon@0.8.2
  │     └─┬ source-map-resolve@0.5.3
  │       ├── resolve-url@0.2.1 
  │       └── urix@0.1.0 
  └─┬ pug@2.0.4
    └─┬ pug-code-gen@2.0.2
      └─┬ constantinople@3.1.2
        └─┬ babel-types@6.26.0
          └─┬ babel-runtime@6.26.0
            └── core-js@2.6.11 
```

**Comment by mmc41** [comment]
In relation, I am today getting this new security warning from npm when I install eleventy:

                                                                             
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ yargs-parser                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @11ty/eleventy                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @11ty/eleventy > browser-sync > localtunnel > yargs >        │
│               │ yargs-parser                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1500                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ yargs-parser                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @11ty/eleventy                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @11ty/eleventy > browser-sync > yargs > yargs-parser         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1500                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 2 low severity vulnerabilities in 708 scanned packages
  2 vulnerabilities require manual review. See the full report for details.

**Comment by Ryuno-Ki** [comment]
Hi @mmc41,

please read https://github.com/11ty/eleventy/issues/1025#issuecomment-601680218 and open a new issue (in case it wasn't reported yet).

Thanks.

**Comment by zachleat** [comment]
`browser-sync` npm audits are filed here https://github.com/11ty/eleventy/issues/1164

**Comment by 21RichyRich** [comment]
I'm getting the same issue, ive been trying to resolve it for 2-3 days now.

**Comment by prajapatarun** [comment]
i am also facing this issue
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by hubgit** [comment]
Using `yarn global add @11ty/eleventy` shows just two deprecation warnings, from `browser-sync`:

```
warning @11ty/eleventy > browser-sync > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @11ty/eleventy > browser-sync > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
```

**Comment by zachleat** [comment]
An update here regarding these deps specifically on master:

```
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

![image](https://user-images.githubusercontent.com/39355/92277319-478c6d80-eeb8-11ea-9c86-f39da909078e.png)
![image](https://user-images.githubusercontent.com/39355/92277326-4b1ff480-eeb8-11ea-89de-d5f8467609b9.png)

* urix is no longer in use

* this looks like an issue, but it’s only via a dev dependency so probably a low priority. Filed at #1394
![image](https://user-images.githubusercontent.com/39355/92277434-95a17100-eeb8-11ea-8d53-8c0319ea014e.png)


Going to close this! Follow along at #1394 for the valid core-js issue
