### ISSUE TITLE
Arbitrary JavaScript Template Type

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#118]
Add JavaScript as a template type in the project. This would allow you to add your own arbitrary JavaScript inside of a specific one-off template. While technically you could use this to add support for Vue templates for example (see #117), you’d have a lot of repeated code littered throughout to wire up the Vue instances and the renderers.

This is more of an underlying precursor to #117.

For example:

## Return a string (does not process data)

``` js
module.exports = "<p>Zach</p>";
```

## Return a function

``` js
module.exports = function(data) {
  return `<p>${data.name}</p>`;
};
```

## Return  a class with a render method

``` js
class Test {
  render(data) {
    return `<p>${data.name}</p>`;
  }
}

module.exports = Test;
```

## Render a Vue template (probably don’t do it this way, see #117)

``` js
const Vue = require("vue");
const renderer = require("vue-server-renderer").createRenderer();

module.exports = async function(data) {
  var app = new Vue({
    template: "<p>Hello {{ data.name }}, this is a Vue template.</p>",
    data: function() {
      return { data };
    }
  });

  return renderer.renderToString(app);
};
```

(Hopefully you can see why #117 would be preferable to the above code)

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

The enhancement backlog can be found here: https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+

**Comment by zachleat** [comment]
Work for this is in progress on the `js-tmpl` branch.

**Comment by zachleat** [comment]
`.11ty.js` templates will be supported in v0.7.0.

**Comment by triptych** [comment]
So great! thanks for your continued work on this! 11ty is my favorite static site generator.
