### ISSUE TITLE
Search form

### ISSUE THREAD

**Issue by sdelon** [11ty/eleventy#1182]
Hello, I am trying to add a search input on my website to reach for posts according to input value, but can't find a proper way to do this. Would you know a way to add this functionality or maybe a third-party js package ? Thanks a lot !

**Comment by pdehaan** [comment]
Maybe https://www.raymondcamden.com/2019/10/20/adding-search-to-your-eleventy-static-site-with-lunr or https://www.hawksworx.com/blog/adding-search-to-a-jamstack-site/?

**Comment by sdelon** [comment]
Thanks ! I looked on the web but didn't get on these very useful links :-)

**Comment by zachleat** [comment]
https://pagefind.app/ is a great option too!
