### ISSUE TITLE
Front matter 'date' key issue.

### ISSUE THREAD

**Issue by WebShapedBiz** [11ty/eleventy#1188]
I'm creating content with NetlifyCMS where on each post I have a published date field named `date`, with specific local display configuration that I've managed to get working in NetlifyCMS `config.yml` file. It works nicely in admin and on the front-end.
However, I'm getting `date front matter value is invalid` error from 11ty.

Luckily, if I rename this date filed in NetlifyCMS configuration to `datum` (meaning 'date' in my language) everything runs smoothly.

I would like to know are there any other keys that 11ty is sensitive about and is this behavior intentional?

- OS and Version: elementaryOS 5.1.4. Hera Linux
- Eleventy Version: 0.10.0

Cheers.

**Comment by pdehaan** [comment]
I'm not aware of any other frontmatter that would have similar side-effects, but I think the docs say the `date` should be in "YYYY-MM-DD" format so if NetlifyCMS is returning it in a differently localized format it might cause some issues like the one you're seeing.

https://www.11ty.dev/docs/dates/

**Comment by WebShapedBiz** [comment]
Oh, I must have missed this detail in docs, my bad.
However, while I can convert this with filter for the front-end, this wouldn't work in the NetlifyCMS admin area where dates in the entry lists would be wrongly formated. For me, it's no issue whatsoever, but I'm not happy when I need to present to my clients the wrong date format.

Since clearly there is a conflict with the `date` key between 11ty and NetlifyCMS, I'll just continue using a different name for my dates.

Cheers.
