### ISSUE TITLE
Enhancement: A repo/location to document 11ty, nunjucks, etc. recipes

### ISSUE THREAD

**Issue by jasonday** [11ty/eleventy#1190]
Because 11ty in combo with js, nunjucks, etc. is so elastic, there is a lot of potential and different solutions to various goals. 

A lot of these are captured in the issues of the eleventy repo, but it may more effective to elevate these solutions (or recipes) to their own repo, wiki, site, etc. This way the eleventy documentation captures the primary use cases and introductions to features, etc., but if a user needs additional context, how to, etc. there would be a place for them to start to piece together solutions for their site.

**Comment by zachleat** [comment]
https://www.11ty.recipes/ and https://11ty.rocks/ are examples of two of these but we’re always open to PRs that add Quick Tips! https://www.11ty.dev/docs/quicktips/

**Comment by zachleat** [comment]
Feel free to open issues for specific use cases we need to capture!
