### ISSUE TITLE
Transformers do not get passed the inputPath

### ISSUE THREAD

**Issue by daKmoR** [11ty/eleventy#1191]
**Describe the bug**
In a Transformer I would like to have access to the inputPath.

**To Reproduce**
1. Add to `.eleventy.js`
```js
  eleventyConfig.addTransform('async-transform-name', async function (
    content,
    outputPath,
    inputPath,
  ) {
    console.log({ content, outputPath, inputPath });
  });
```
inputPath will be undefined

**Expected behavior**
inputPath is defined

Funny enough in the source code it already is mentioned 😅
https://github.com/11ty/eleventy/blob/master/src/Template.js#L609

this solves it
```diff
- content = await this.runTransforms(content, page.outputPath); // pass in page.inputPath?
+ content = await this.runTransforms(content, page.outputPath, page.inputPath); 
```

If this is the way forward I can certainly create a pull request 🤗
just let me know 👍

**Comment by pdehaan** [comment]
See #789

**Comment by zachleat** [comment]
Yeah, this is a super easy change but I was kind of wondering if I could better solve this related problem: https://github.com/11ty/eleventy/issues/789#issuecomment-629688643

Closing as duplicate though, please continue discussion over at #789—thanks!
