### ISSUE TITLE
Trigger build from Sanity data change?

### ISSUE THREAD

**Issue by leefisher** [11ty/eleventy#1198]
How do I trigger changes when I update data in sanity?  I saw an old issue about webhook but couldn't find any solution so what is the preferred way for handling this?

**Comment by jamesgrubb** [comment]
Hi did you ever work this out? Thanks

**Comment by leefisher** [comment]
> Hi did you ever work this out? Thanks

No I haven't yet gotten back to it, James.

**Comment by treb0r** [comment]
The documentation for this is [here](
https://www.sanity.io/docs/webhooks).

**Comment by jamesgrubb** [comment]
Nice one thanks

**Comment by leefisher** [comment]
The issue is how to handle it on the eleventy side.  There is potential workaround in #1358 , but you still basically end up setting up your own endpoint.

**Comment by antgel** [comment]
I think https://github.com/11ty/eleventy/pull/3085 and https://github.com/11ty/eleventy-dev-server/pull/70 should help with this, if anyone is reading and interested.

**Comment by zachleat** [comment]
@treb0r was likely the most correct — you’ll want to set up a webhook to trigger a build on your web host.

For folks wanting something on your local build, please subscribe to #3085 as @antgel linked — thank you!

**Comment by antgel** [comment]
@zachleat Great to see you here and congrats on going full-time, Gem Agile looks forward to chipping in to the pot. :) I need to rebase the PRs involved and am happy to do this. When rebased will they be merged into main at some point?

**Comment by zachleat** [comment]
Hey @antgel! I’m cleaning up the issue tracker and I’ll circle to project PRs next (I think your PR shouldn’t require much updating, if any)! Thank you!
