### ISSUE TITLE
Using Algolia for search

### ISSUE THREAD

**Issue by nhoizey** [11ty/eleventy#12]
I would be great if we could use [Algolia](https://www.algolia.com/) for search.

The easy part is the user facing search interface, because it doesn't depend on eleventy.

The hard part is indexing. Here's [an overview of indexing into Algolia](https://www.algolia.com/doc/guides/indexing/indexing-overview/).

**Comment by JonasBa** [comment]
@zachleat @nhoizey I work at Algolia and would be happy to assist you on this.
Let me know once you've evaluated it and if you give a green light, I'd be happy to open a PR.

P.S. happy holidays 🎄

**Comment by zachleat** [comment]
Moving this comment here since it’s more relevant to this ticket:

> Also can be used for:
> https://twitter.com/ChrisFerdinandi/status/949022607390707712
> JSON file mapping all of the content for RSS/Search

cc @cferdinandi

**Comment by chrisdmacrae** [comment]
IMO this could easily be done if we could output different file formats than `.html`.

Especially with EJS. Just create a special collection w/ the fields you want, and then put this in your template:

`eleventyConfig.js`:
```
module.exports = (eleventyConfig) => {
  eleventyConfig.addCollection("algolia", function(collection) {
    var algoliaCollection = collection.getAll().map(hit => {
        return {
          title: hit.title,
          // any other fields you want...
        }
    })
  });
}
```

`index.json`:
```
---
templateEngineOverride: ejs
---
<%= JSON.stringify(collections.algolia) -%>
```

**Comment by zachleat** [comment]
Interesting @chrisdmacrae! You can output any file/extension with `permalink`, no?

**Comment by zachleat** [comment]
Rather, use `index.ejs` and use `permalink: index.json`.

**Comment by chrisdmacrae** [comment]
Amazing. Phenomenal. Eleventy is great.

**Comment by zachleat** [comment]
This repository is now using lodash style issue management for enhancements (see https://twitter.com/samselikoff/status/991395669016436736)

This means enhancement issues will now be closed instead of leaving them open. The enhancement backlog can be found here: https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+

**Comment by zellwk** [comment]
Slight error here

```
<%= JSON.stringify(collections.algolia) -%>
```

Should be 

```
<%- JSON.stringify(collections.algolia) -%>
```

This lets EJS creates an unescaped JSON file (which is what we're after).

**Comment by zachleat** [comment]
I did implement a local search on the 11ty.io docs, might be of interest to people on this issue. Might expose this as a plugin later.

Data file here: https://github.com/11ty/11ty.io/blob/master/docs/searchData.njk
https://twitter.com/eleven_ty/status/1197550926636158982

**Comment by Ryuno-Ki** [comment]
Yes please :-)
Would also be interesting to see, how to optimise the rank on large collections of content.

**Comment by distinctperspective** [comment]
Is there a way to know which collection the hit came from??? I need to know that.

**Comment by siakaramalegos** [comment]
Updated link to Zach's data file: https://github.com/11ty/11ty-website/blob/master/src/docs/searchData.njk

I'm starting to look into this too, but still early stage.

**Comment by nhoizey** [comment]
@siakaramalegos if it can help, here's the JSON template I use to index my content in Algolia:
https://github.com/nhoizey/nicolas-hoizey.com/blob/main/src/tools/algolia.njk

I have a `cleanForAlgolia` filter that removes some content (footnotes, Giphy GIFs, headings links):
https://github.com/nhoizey/nicolas-hoizey.com/blob/main/src/_11ty/filters/html.js#L16-L27

(It currently uses Cheerio, I have to move to linkedom.)

I use [atomic-algolia](https://github.com/chrisdmacrae/atomic-algolia) to index only what changed.

I explained here a little how I use Algolia on my site:
https://nicolas-hoizey.com/articles/2020/11/02/enhancing-archives-navigation-step-2/

Hope this helps!
