### ISSUE TITLE
Single Posts Can't Be Rendered Into Pagination?

### ISSUE THREAD

**Issue by BayuAngora** [11ty/eleventy#1205]
I have Hugo site and clone it to Eleventy site with same structure like this ->
https://github.com/BayuAngora/eleventy 

Every single posts are live successful like this ->
https://my-eleventy.onrender.com/blog-post-01/

But why those single posts can't be rendered into pagination?
https://my-eleventy.onrender.com/blog/

**Comment by pdehaan** [comment]
I was able to get this working locally (or at least the /blog/ page, but I had to change it to 
```diff
+{% for post in collections.blog %}
-{% for post in pagination.blog %}
```
at https://github.com/BayuAngora/eleventy/blob/3f1b23014810b3bf3b107c79a4631de9414e97d8/content/blog/index.html#L7

And I had to comment out the redeclaring of the "blog" collection at https://github.com/BayuAngora/eleventy/blob/3f1b23014810b3bf3b107c79a4631de9414e97d8/.eleventy.js#L12-L13

![Blog___Bayu_Angora](https://user-images.githubusercontent.com/557895/82708192-83b20000-9c32-11ea-92f7-0bad78294730.png)

**Comment by BayuAngora** [comment]
> I was able to get this working locally (or at least the /blog/ page), but I had to change it to
> 
> ```diff
> +{% for post in collections.blog %}
> -{% for post in pagination.blog %}
> ```
> 
> at https://github.com/BayuAngora/eleventy/blob/3f1b23014810b3bf3b107c79a4631de9414e97d8/content/blog/index.html#L7
> 
> And I had to comment out the redeclaring of the "blog" collection at https://github.com/BayuAngora/eleventy/blob/3f1b23014810b3bf3b107c79a4631de9414e97d8/.eleventy.js#L12-L13
> 
> ![Blog___Bayu_Angora](https://user-images.githubusercontent.com/557895/82708192-83b20000-9c32-11ea-92f7-0bad78294730.png)

Thanks for reply. The list is rendered now. But still not paginated yet. I added front matter like this before ->
```
pagination:
  size: 2
  data: collections.blog
```
But I getting an error. Any idea how to implement pagination for list page such blog, poem, quote?

Repo updated ->
https://github.com/BayuAngora/eleventy/tree/master
