### ISSUE TITLE
Emoji's not rendering properly with Nunjucks

### ISSUE THREAD

**Issue by jan-dh** [11ty/eleventy#1210]
**Describe the bug**
I try to use emoji's in my .md and .njk files, but they are being transformed.

**To Reproduce**

1. Make a .md and/or .njk file
2. Add this emoji: 🌶
3. See output: `ð¶`

I tried to escape them, using the `{% raw %}` filter, but that doesn't seem to help. Also tested this on a Nunjucks playground website: https://np.bauke.xyz/ and had no issues there.

**Expected behavior**
Would like to see the emoji.

**Screenshots**
This is my test on the playground. As you can see on the right-hand side, the emoji's being shown ok.
![image](https://user-images.githubusercontent.com/5801781/82757393-78043c00-9de0-11ea-9bbd-3c2e334666ea.png)

**Comment by pdehaan** [comment]
I was unable to reproduce this on macOS w/ Chrome w/ Eleventy v0.11.0 (and whatever versions of Nunjucks/Liquid that includes).

https://github.com/pdehaan/11ty-1210

![localhost_8082_test2_](https://user-images.githubusercontent.com/557895/82760856-30af8880-9dab-11ea-9fe7-0a4cad7ca4d8.png)

I also didn't see any difference between just displaying the chili emoji vs wrapping with `<!DOCTYPE html>` and adding `<meta charset="utf-8"/>` (not that those would hurt).

What OS/browser are you using?

**Comment by jan-dh** [comment]
I'm testing this on Chrome and macOS (Mojave).  My base layout templates has those tags:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
```

I'm on `"@11ty/eleventy": "^0.10.0",`, will try and upgrade to see if this fixes the issue.

**Comment by jan-dh** [comment]
![image](https://user-images.githubusercontent.com/5801781/82762819-7a2bc200-9e03-11ea-9eee-377d1a1e8503.png) outputs:

![image](https://user-images.githubusercontent.com/5801781/82762837-90398280-9e03-11ea-970f-0f4cfe8f4dcb.png)

**Comment by jan-dh** [comment]
Nevermind, seems to be something wrong with the Snowpack setup. If I run 11ty alone it works.
