### ISSUE TITLE
mention a recommended meta generator tag

### ISSUE THREAD

**Issue by revelt** [11ty/eleventy#1217]
Automated website stack detection tools like wappalyzer currently don't recognise 11ty. The "official" way to recognise the static generator is by `<meta generator="x">` tag.

1. Let's agree on the default, "official" 11ty `meta` generator tag's value. I propose it to be in format: 

```html
<meta name="generator" content="11ty v0.11.0" />
```

value format being: `11ty` + space + `v` + (semver in `x.y.z` format)

2. Once agreed, let's mention this in the documentation and encourage users to put this tag in their markup. Currently we don't have a machine-readable way to tell the world it's built on 11ty.

**Comment by brycewray** [comment]
There also is the plugin that @Ryuno-Ki created: https://github.com/Ryuno-Ki/eleventy-plugin-meta-generator. I haven't used it but agree with its spelling out "Eleventy" rather than just "11ty," so as to cover all search possibilities.

On a separate but related subject: would be nice if the version number were exposed in the Eleventy API for just this purpose, for easy insertion in one's `<head>` partial along the lines of what's being suggested in this issue.

**Comment by Ryuno-Ki** [comment]
I was about to update my plugin for v0.11.
If @zachleat agrees, I can update its value, no problem.

I just came up with *something* to make it somehow discoverable.
I pull the number from the `package.json` of the installed package.

**Comment by brycewray** [comment]
> I was about to update my plugin for v0.11.
> If @zachleat agrees, I can update its value, no problem.
> 
> I just came up with _something_ to make it somehow discoverable.
> I pull the number from the `package.json` of the installed package.

Any chance you could add some `.11ty.js`-friendly instructions in the README? 😄

**Comment by Ryuno-Ki** [comment]
Sure. Fill an issue at https://github.com/Ryuno-Ki/eleventy-plugin-meta-generator/issues/new so I can keep a reference to it, please.

**Comment by brycewray** [comment]
> Sure. Fill an issue at https://github.com/Ryuno-Ki/eleventy-plugin-meta-generator/issues/new so I can keep a reference to it, please.

Done. Thanks!

**Comment by denisbrodbeck** [comment]
> **Edit**: In the meantime, I added the following to my `head.js` partial to provide automatic version info:
> 
> ```
> const jsonInfo = require(`../../../../package.json`)
> var eleventyVersion = jsonInfo.devDependencies['@11ty/eleventy']
> if (eleventyVersion.charAt(0) == "^") {
>   eleventyVersion = eleventyVersion.substring(1)
> }
> 
> module.exports = function(eleventyConfig) {
> 
>   eleventyConfig.addShortcode('headTag', function(data) {
> 
>     return `
>     <head>
>     <meta name="generator" content="Eleventy - 11ty - https://11ty.dev - Version ${eleventyVersion}" />
> ```

@brycewray You can require 11ty's version directly with `require(`@11ty/eleventy/package.json`).version`.
No version parsing needed 😃 

```javascript
module.exports = function (config) {
  config.addShortcode(`addGenerator`, () => {
    return `<meta name="generator" content="Eleventy - 11ty - https://11ty.dev - v${require(`@11ty/eleventy/package.json`).version}" />`;
  })
}
```

**Comment by brycewray** [comment]
> @brycewray You can require 11ty's version directly with `require(`@11ty/eleventy/package.json`).version`.
> No version parsing needed 😃

[Slapping own forehead] Ah. Thanks!

**Comment by Ryuno-Ki** [comment]
Related to #1283

**Comment by nhoizey** [comment]
I'm now using `<meta name="generator" content="Eleventy v0.11.0" />` as Zach told us in #1283 that `Eleventy` is the "software package specifically".

**Comment by binyamin** [comment]
@nhoizey I use that format as well.

Note that if you use the latest (unstable) version of Eleventy from GitHub (ie. with `npm install github:11ty/eleventy`), you can write `v1.0.0-beta.0+sha:<commit-hash>` [as per the semver spec](https://semver.org/#spec-item-10). Not sure if it's necessary, although you would at least want to distinguish between GitHub and NPM.

**Comment by nhoizey** [comment]
@binyamin you're right, if we use the optional version number, it should be accurate! 👍

**Comment by brycewray** [comment]
Proving once again that it **does** pay to look through the documentation (and I’m talking to myself on that one :smile), here is a method that works just fine in Nunjucks templates and uses Eleventy’s [built-in `pkg` data value](https://www.11ty.dev/docs/data-eleventy-supplied/):

```njk
<!-- from `head.njk` -->
{% set eleventyVersion = pkg.devDependencies['@11ty/eleventy'] | replace("^", "") %}

  <head>
    <meta name="generator" content="Eleventy v{{ eleventyVersion }}" />
```
I suspect it would be equally useful, with obvious alterations, in other templating options. Of course, you must change that `pkg` part to `pkg.dependencies` if you have Eleventy just plain installed and not `--save-dev` installed. :wink

**Comment by brycewray** [comment]
> Note that if you use the latest (unstable) version of Eleventy from GitHub (ie. with `npm install github:11ty/eleventy`), you can write `v1.0.0-beta.0+sha:<commit-hash>` [as per the semver spec](https://semver.org/#spec-item-10). Not sure if it's necessary, although you would at least want to distinguish between GitHub and NPM.

@binyamin Could you also advise where to find docs (such as they may be) for the beta? Your post here is the first I’ve seen that gives the `npm` command for obtaining it. Thanks.

**Comment by binyamin** [comment]
@brycewray I don't know that they exist, to be honest.

**Comment by zachleat** [comment]
Shipped here, docs already up https://github.com/11ty/eleventy/issues/2293#issuecomment-1081659583

**Comment by zachleat** [comment]
Docs: https://www.11ty.dev/docs/data-eleventy-supplied/#eleventy-variable

Pending addition to `eleventy-base-blog` here: https://github.com/11ty/eleventy-base-blog/issues/127

**Comment by zachleat** [comment]
The small benefit to using the `eleventy.generator` global data is that we normalize away prerelease version suffixes there

**Comment by brycewray** [comment]
Not yet in 2.0.0-canary.4, correct? Or does it have to exposed in `.eleventy.js` somehow?

**Comment by pdehaan** [comment]
@brycewray Looks like this was added today in https://github.com/11ty/eleventy/commit/089ab8f205a6b1ed790a45d1a234438649f91b74, but it looks like the latest 2.0.0 is "canary.4" from 2022-03-17:

```sh
npm info @11ty/eleventy time --json | grep "canary" | tail -3

  "2.0.0-canary.3": "2022-03-10T22:12:06.738Z",
  "2.0.0-canary.4": "2022-03-17T15:21:10.123Z",
  "1.0.1-canary.4": "2022-04-15T20:57:45.575Z"
```

**Comment by nhoizey** [comment]
Looking for meta generator values elsewhere, I saw most don't add a `v` before the version number.

But I couldn't find any specification about the meta value. 🤷‍♂️

**Comment by Ryuno-Ki** [comment]
The specification would be https://html.spec.whatwg.org/multipage/semantics.html#meta-generator 

> The value must be a free-form string that identifies one of the software packages used to generate the document. This value must not be used on pages whose markup is not generated by software, e.g. pages whose markup was written by a user in a text editor.

(Content Warning: Could bring back memories)

**Comment by djpowers** [comment]
Apologies for bumping an old/closed issue, but since Wappalyzer was specifically highlighted as motivation for this change, I wanted to mention that I submitted a technology suggestion to the Wappalyzer team that was just approved so keep an eye out for that shortly:
> The status of your request 'Technology suggestion: Eleventy' has been updated: 
> 
> Accepted: The technology will be included in the next release. This may take a few weeks.
