### ISSUE TITLE
nunjucks shortcodes content from file

### ISSUE THREAD

**Issue by Miosame** [11ty/eleventy#1218]
Is there a way to use another *.njk template file as the content for shortcodes? instead of a function or having to resort to some sort of reading the other template inside that function.

Something like:
`eleventyConfig.addPairedNunjucksShortcode("user", "./path/to/file.njk");`

Thanks!

**Comment by Miosame** [comment]
Nevermind, the goal was to use it with component'esque workflow, that can be achieved via imports too, since it inherits the data after all (slightly confusing in the docs), so something like this will work:

```
{% for file in files %}
    {% import "components/file.njk" %}
{% endfor %}
```

**Comment by Miosame** [comment]
Sadly that's not how it works after all - it was just not rebuilding in `--serve`, as there was errors, so it looked like it worked.

**Comment by Miosame** [comment]
So after more experimenting, that's what seems to work:

```nunjucks
{% import "components/file.njk" as file_component %}
{% for file in files %}
    {{ file_component.render(file) }}
{% endfor %}
```

file.njk now containing a macro called `render()`

Is there a **_better_** way of doing that?

**Comment by dawaltconley** [comment]
I think that's the best way to do it for `*.njk` files / macros. If you just want the shortcode's javascript function to live in a file other than the config you could `require` it from the config? Or is the point to do Nunjucks templating within the shortcode?

Not much different from the above, but [i think](https://mozilla.github.io/nunjucks/templating.html#import) you can also do:

```
{% from "components/file.njk" import render %}

{% for file in files %}
    {{ render(file) }}
{% endfor %}
```

**Comment by Miosame** [comment]
@dawaltconley idea was to be able to use multiple "components" too, thus each had to have a sensitive import name (all with a `render` macro), I suppose there's no other way then, thanks!
