### ISSUE TITLE
Can I use nested shortcodes in Eleventy?

### ISSUE THREAD

**Issue by adrian5** [11ty/eleventy#1227]
As an example, consider writing documentation (made up syntax):

```
{% note %}
Before starting the server, be sure to add a {% file "server.yml" "config" %} file.
{% /note %}
```

Which might do build-time path verification (file exists), and output something like:

```html
<div class="note">
  <div class="header">Note</div>
  <div class="body">
    Before starting the server, be sure to add a
    <span class="file"><a href="/data/article-name/server.yml">config</a></span> file.
  </div>
</div>
```

I was disappointed to find that Jekyll, Hugo, etc. cannot do this with their template engines. It made a whole part of my intended workflow non-viable. If I have to write inline HTML for things like "Note" elements, or use separate singular tags instead of a single pair-template, it hurts DRY and maintainability.

**Comment by tedw** [comment]
Yes, you can nest them:
https://www.11ty.dev/docs/shortcodes/#paired-shortcodes

However, I can’t seem to get nested aysnc shortcodes to work. Not sure if that’s possible or not.

FYI, note that paired shortcodes work differently in markdown files:
https://www.11ty.dev/docs/languages/markdown/#why-cant-i-return-markdown-from-paired-shortcodes-to-use-in-a-markdown-file
