### ISSUE TITLE
Extend BrowserSync with Configuration API

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#123]
Requested in https://github.com/11ty/eleventy/pull/120#issuecomment-388577253

cc @paulrobertlloyd

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

The enhancement backlog can be found here: https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+

**Comment by zachleat** [comment]
Notably @davemcnally wanted local certificates on this, per https://www.browsersync.io/docs/options/#option-https as requested here https://twitter.com/davemcnally/status/1045414234308452352

**Comment by edwardhorsford** [comment]
In my case, I'd like to be able to set `ignorePaths` so that certain urls don't refresh on change. For the time being I've directly edited eleventy to achieve this.

**Comment by wesruv** [comment]
Hard to say if this is what I want... I think it is?

Collection pages aren't reloading HTML when a child page in the collection is updated. I'd like to force the browser to refresh on any `.njk` file being updated, similar to `--no-inject-changes` on BrowserSync's CLI:
https://www.browsersync.io/docs/command-line

But maybe there's a more direct way to fix the issue I'm experiencing, I wouldn't mind "RELOAD ALL THE THINGS ON CHANGE" option.

**Comment by zachleat** [comment]
PR for this is ready to ship for 0.7.0 and docs have been added to the site for this feature.

https://www.11ty.io/docs/config/#override-browsersync-server-options

**Comment by paulrobertlloyd** [comment]
Works like a charm! 👍🏻
