### ISSUE TITLE
.history folder issues

### ISSUE THREAD

**Issue by logicman** [11ty/eleventy#1234]
A newbie here. 

Just playing arouond with 11ty since yesterday and started a new project with the **eleventy-base-blog**. I have successfully managed to get the starter blog to work on my localhost and even push the code to github. 

One issue I am facing is that every time I make a change to any of the pages (which are on the top nav - Home, About etc.), a copy of that nav link gets created next to it. I realized that .history/ is creating a .md file with every change. If I gitignore the .history folder and remove those file (e.g. about_20200605131408.njk), everything works fine and I don’t see duplicate nav links. 

So, should one ignore the .history directory in git for any new Eleventy projects? I didn't see this in the docs or anywhere else. 

Thanks in advance for your help.

**Comment by zachleat** [comment]
I believe this was resolved on Twitter, right? Thanks!

**Comment by logicman** [comment]
Yes. The .history folder was created by a history extension in VSC. Removed extension and deleted the folder. Works well.
