### ISSUE TITLE
Where to learn how to use NodeJS packages as plugins with 11ty

### ISSUE THREAD

**Issue by f618** [11ty/eleventy#1235]
Hey guys, 

Total newbie here, thirsty for knowledge,

The plugin documentation skips over where I am at skill wise, so I'm wonder where i should look to start levelling-up?

My practical issue is that I want to be able to integrate https://www.npmjs.com/package/are.na with my site, but may like to add additional packages later on. 

Thanks for your support,

**Comment by f618** [comment]
bump

**Comment by zachleat** [comment]
what’s the bump for

**Comment by sullyD64** [comment]
Hi @f618,

As you know, Eleventy runs on Node, which means you can use any other Node module or 3rd part library anywhere in your build pipeline (inside data files, templates or eleventy's configuration). In fact, Eleventy plugins are Node libraries too, the only difference is that they are specifically built to extend Eleventy's functions (adding filters, shortcodes, etc.).

Regarding installation, you can add any package you want in your Eleventy project in the same way you've installed Eleventy: using npm or yarn (though you probably would want to install those packages locally).

As for using the libraries, that depends on their purpose. I don't know what are.na is for, but given its readme I guess you need it to perform some API calls, so in any of the above locations you can import that module and write a javascript function which uses it. For example, [here](https://github.com/jlengstorf/lets-learn-eleventy/blob/master/_data/puppers.js) you can see how they used Axios to fetch some data from an API and then made that data available in a global data file, which then is used to dynamically create pages from that fetched data.

**Comment by f618** [comment]
Sorry for the bump that was totally superfluous. 

@sullyD64 Thank you that makes a lot of sense,  I briefly used Gatsby which had GraphiQL which made it visually easier to see / test what data could be pulled in - is there tool similar that which can be used with 11ty?

If you can think of any tutorials / resourceful which might help please let me know

**Comment by djiest** [comment]
There is https://discord.com/channels/741017160297611315/741017160297611319

**Comment by zachleat** [comment]
For future visitors we do have plugins documented on our docs: https://www.11ty.dev/docs/plugins/ (including consuming and creating)
