### ISSUE TITLE
Image Sitemap Generator

### ISSUE THREAD

**Issue by ManzDev** [11ty/eleventy#1241]
Exist some approximation to a Image Sitemap Generator?

I want create a `imagemap.xml` similar to:
https://support.google.com/webmasters/answer/178636

With 11ty collections is very easy create a standard sitemap.xml, but... Does anyone have any first approach to extract URLs with images from markdown files? Any library or system to begin?

**Comment by denisbrodbeck** [comment]
@ManzDev The easiest way forward would be adding the links to your images into your front matter manually.

```md
---
title: Some Title
created: 2020-03-13T12:24:37.380Z
images:
 - /assets/images/image1.jpg
 - /assets/images/image2.jpg
 - /assets/images/image3.jpg
---

Content goes brrrr.
```

This makes the data available for use in your template engine.

From here on we can generate a `sitemap.xml.njk`:

```nunjucks
---
permalink: /sitemap.xml
eleventyExcludeFromCollections: true
---
{#- Google: Build and submit a sitemap (https://support.google.com/webmasters/answer/183668?hl=en) -#}
{#- List only canonical URLs in your sitemap -#}
{#- Google ignores `<priority>` and `<changefreq>` values, so don't bother adding them. -#}
{#- Google reads the `<lastmod>` value, but if you misrepresent this value, we will stop reading it. -#}
{#- A sitemap can contain only ASCII characters, escape &,',",>,< -#}
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
{%- for item in collections.all -%}
  {%- if not item.data.excludeFromSitemap %}
  <url>
    <loc>{{- item.url | url | absoluteUrl(site.url) -}}</loc>
    <lastmod>{{- item.date | dateToISO -}}</lastmod>
    {%- for image in item.data.images %}
    <image:image>
      <image:loc>{{- image | url | absoluteUrl(site.url) -}}</image:loc>
    </image:image>
    {%- endfor %}
  </url>
  {%- endif -%}
{%- endfor %}
</urlset>
```

The only other way I see is parsing the parsed markdown or hooking into your markdown parser, but that might be overkill 🤔

**Comment by ManzDev** [comment]
Very thanks @denisbrodbeck.

Yes, I think that frontmatter is easiest way. 

But, IMHO, I have multiple markdown content and manage images in frontmatter isn't very modular and counterproductive (my particular case).

Do you consider a good strategy to iterate markdown files and extract the images with regexp pattern? 
Any better approach? I use `markdown-it` as library.

**Comment by denisbrodbeck** [comment]
It depends on your markup. You could just regex the hell out of your markdown files. There are multiple ways to include an image inside markdown.
You could use the default `![alt](src)`, but many use raw html `figure` instead for that extra `figcaption`, or a `picture` element.

I think with a few practice regexp's this could be doable.

**Comment by ManzDev** [comment]
Yeah, thanks @denisbrodbeck.

Finally I create a node script that run on my last step workflow (before deploy):

1. Recursive readdirSync my `input` folder of `.md` files
2. readFileSync for every markdown
3. `/(?:!\[(.*?)\]\((.*?)\))/gm` regexp for extract `![alt](src)` images on every markdown (only use this format)
4. writeFileSync for save `.xml` imagemap

Works like a charm! Just 1 sec for multiple markdowns.

Very thanks!!

**Comment by Maximization** [comment]
I ended up creating a filter function and doing the RegEx extraction there. The benefit of this is that I could also include the cover images which aren't part of the markdown. In `.eleventy.js`:

```js
// Given a page's data, return an array of image path/alt extracted from Markdown content
// including the cover images from front matter
// Note: Markdown extraction only works for ![]() notation
eleventyConfig.addFilter('extractImages', (page) => {
  const content = page.template.inputContent;
  const coverImage = page.data.coverImage;
  const coverImageAlt = page.data.coverImageAlt;
  const images = [];

  if (coverImage) {
    images.push({ path: `/images/${coverImage}`, alt: coverImageAlt });
  }

  const imagesInMarkdown = new RegExp(/!\[(?<alt>.*?)]\((?<path>.+?)\)/g);
  const captures = Array.from(content.matchAll(imagesInMarkdown));
  if (captures.length) {
    const capturedImages = captures.map((capture) => {
      return {
        path: capture.groups.path,
        alt: capture.groups.alt,
      };
    });

    images.push(...capturedImages);
  }

  return images;
});
```

And in `sitemap.njk`:

```twig
---
permalink: "/sitemap.xml"
eleventyExcludeFromCollections: true
---
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  {%- for page in collections.all %}
  {%- if not page.data.canonical %}
  <url>
    <loc>https://maximorlov.com{{ page.url }}</loc>
    {%- for image in page | extractImages %}
    <image:image>
      <image:loc>https://maximorlov.com{{ image.path }}</image:loc>
      {%- if image.alt %}
      <image:caption><![CDATA[{{ image.alt | safe }}]]></image:caption>
      {%- endif %}
    </image:image>
    {%- endfor %}
  </url>
  {%- endif %}
  {%- endfor %}
</urlset>
```

**Comment by zachleat** [comment]
Thank you everyone!
