### ISSUE TITLE
Nunjucks filter multiple parameters

### ISSUE THREAD

**Issue by Miosame** [11ty/eleventy#1244]
Currently the [documentation](https://www.11ty.dev/docs/languages/nunjucks/) does not cover at all that you are able to use parameters in filters just fine and that the filtered object will be passed as the first argument:

```javascript
eleventyConfig.addFilter("testParams", function(input,param1,param2) {
    return [input,param1,param2].join("-");
});
```

then: `{{ "1" | testParams("2","3") }}` works - and outputs: `1-2-3`.

Which was important to know to implement proper jinja'esque rejectAttr filters e.g. here: https://github.com/11ty/eleventy/issues/910

Note that this had to be tested, because even nunjucks docs don't seem to mention it at all.

**Comment by vimtor** [comment]
This will be awesome!

**Comment by octos4murai** [comment]
This came in useful for me today. Thanks @Miosame! To give it more visibility, I'd like to add this to the relevant [documentation page](https://www.11ty.dev/docs/languages/nunjucks/).

This will be my first time contributing to Eleventy so I'm unfamiliar with the community's preferences and would appreciate some guidance. I think this issue should instead go in [this repo](https://github.com/11ty/11ty-website). Should I create a similar GitHub issue there and then submit a PR for for my change? Or would just a PR (with no issue) be sufficient?

**Comment by pdehaan** [comment]
I think just a PR with a link to this issue is probably sufficient. ❤️

**Comment by zachleat** [comment]
Merged @octos4murai PR, this will be on the docs shortly!

Thanks y’all!

**Comment by kitschpatrol** [comment]
Thanks for this. Variadic functions / spread syntax also works fine if you're dealing with an indeterminate quantity of args!

Filter:
```
  eleventyConfig.addFilter("testVariadicParams", function (input, ...params) {
    return [input, ...params].join("-");
  });
```

Template:
```
{{ "1" | testVariadicParams("2","3","4","5") }}
```

Rendered:
```
1-2-3-4-5
```
