### ISSUE TITLE
Custom serve with Eleventy

### ISSUE THREAD

**Issue by ManzDev** [11ty/eleventy#1248]
Can Eleventy CLI set a custom serve like es-dev-server ( https://open-wc.org/developing/es-dev-server.html ) or sirv ( https://github.com/lukeed/sirv )?

`eleventy --custom-serve es-dev-server`, for example.

I want a highlight-color 404/200 code error for easy check links while watch files for development.

**Comment by osukaa** [comment]
I think you could run `es-dev-server` inside the generated `_site` folder 🤔

**Comment by ManzDev** [comment]
The problem is use `eleventy --watch` with `es-dev-server`.

I can run `es-dev-server` over end static finish files but I can't run without `npm-run-all -p` or similar (for watch development).

Maybe, I'm wrong...

**Comment by lirantal** [comment]
@ManzDev just an idea but maybe you can configure nodemon to watch the generated static `_site` dir, and then do the `es-dev-server` thing on that

**Comment by jrdnrich** [comment]
@ManzDev I may be way off base here but it is possible to add a custom start and/or build for Eleventy.
It's handled in your package.json file in your root directory for example 

```

"scripts": {
  "build": "npx eleventy",
  "serve": "npx eleventy --serve",
  "debug": "DEBUG=* npx eleventy"
},

```
will allow you to run `npm run serve` when you want to load the live enviro for local development and it watch your changes. They did a it a little different but really good short video on the concept here: https://egghead.io/lessons/11ty-create-an-eleventy-11ty-site-from-scratch?pl=build-an-eleventy-11ty-site-from-scratch-bfd3

**Comment by melissamcewen** [comment]
It seems like all the solutions for this problem involve running both `eleventy --serve` and another server at the same time. For example [Snowpack 11ty](https://github.com/snowpackjs/snowpack/tree/main/create-snowpack-app/app-template-11ty) or [this webpack solution](https://statickit.com/guides/eleventy-webpack). If there were a way to maybe hook into the process through a plugin or such maybe that would make it easier to build custom server setups?

**Comment by zachleat** [comment]
There are a couple of options here, you can run eleventy without a web server with `--watch`:

```
"scripts": {
  "watch": "npx eleventy --watch",
  "serve": "npx http-server _site",
  "start": "npm-run-all -p watch serve"
},
```

For super advanced use cases in 2.0+ you can use Eleventy’s Server API to write your own adapter. Here’s the Browsersync one we provide: https://github.com/11ty/eleventy-server-browsersync/blob/main/server.js (via https://www.11ty.dev/docs/dev-server/)
