### ISSUE TITLE
Overriding .gitignore with .eleventyignore

### ISSUE THREAD

**Issue by Wilto** [11ty/eleventy#125]
As probably-expected at this point, I’m doing something weird: my site’s content is a git submodule. I edit my markdown in the submodule directory, and when I commit it, a precommit hook `rsync`s the files back to the root of my Eleventy install. To do this, I added the content files to my the root repo’s .gitignore: 

```
_site/
node_modules/
package-lock.json
img
_src/recipes/*.md
_src/recipes/*.json
!_src/recipes/recipes.json
_src/articles/*.md
_src/reviews/*.md
_src/offline/*.md
```

But in doing so, they’re omitted from the Eleventy build. Would it be possible to set `.eleventyignore` up in such a way as to _override_ things specified in `.gitignore`? Something like:

<img width="670" alt="image" src="https://user-images.githubusercontent.com/439942/40077779-a872b98e-5850-11e8-8aa3-54ab816fd006.png">

**Comment by zachleat** [comment]
I think what I’d rather do is have an option to globally bypass the automatic .gitignore import, which would require you to duplicate and copy any .gitignore entries into .eleventyignore. Would that work for you?

**Comment by Wilto** [comment]
Absolutely it would.
