### ISSUE TITLE
When setting permalink to false using Directory Data Files, exclude such items from tag collection

### ISSUE THREAD

**Issue by MaybeThisIsRu** [11ty/eleventy#1251]
**Describe the bug**
I use a directory data file to set blog posts or pages to `permalink: false` to exclude them from build on production, if the file is marked as a draft in my Git-based CMS.

The files marked as `draft: true` correctly get assigned the computed property of `permalink: false`. However, if accessing the collection using the following syntax, they are still included in this collection:

```liquid
{% for article in collections[tag_name] reversed %}
  // do something
{% endfor %}
```

As a temporary workaround, I also check the permalink value manually:

```liquid
{% for article in collections[tag_name] reversed %}
  {% if article.url != false %}
    // do something
  {% endif %}
{% endfor %}
```

**To Reproduce**

1. Have a directory called `posts` with blog posts written in Markdown inside it
2. Assign tags to this post so that Eleventy makes a tag collection
2. Create a directory data file called `posts.11tydata.js`
3. Set `permalink` to `false` on some blog posts based on your own criteria
4. Access the collection elsewhere using the `collections[tag_name]` syntax.
5. Collection will include posts which have permalink set to false

**Expected behavior**
collections[tag_name] should exclude files that have `permalink` set to `false`.

**Environment:**

- OS and Version: Pop!_OS 20.04 LTS
- Eleventy Version: 0.11.0

**Comment by hirusi** [comment]
@makkabi [raised this issue on DEV.to](https://dev.to/makkabi/comment/13330) as well.

**Comment by makkabi** [comment]
I think there are usecases where you want to set permalink to false, but still NOT exclude the content from collections. For example, you could have a folder with "testimonials", and while you don't want to generate single pages for every testimonial (which you can do by setting permalink to false), you still want to have a collection with all testimonials, so you can display them on e.g. your frontpage. 
So not automatically excluding content without permalink is not a bug, but a useful feature. I think a draft status, which completely excludes content in the production build, should be separate from the permalink setting.
It would be great if the docs would include a description how to implement "drafts" in an easy way. (By easy I mean without e.g. GIT features like draft branches, which may be too complicated for many users.)
Even better would be a native draft feature in eleventy, e.g. just setting "draft" to true in frontmatter.

**Comment by edwardhorsford** [comment]
[Drafts are discussed in this feature request / issue.](https://github.com/11ty/eleventy/issues/188)

@hirusi for your case, you can additionally set [eleventyExcludeFromCollections](https://www.11ty.dev/docs/collections/#option-exclude-content-from-collections) wherever you set `permalink: false`

**Comment by makkabi** [comment]
@edwardhorsford Thanks! If you would not set eleventyExcludeFromCollections directly to false, but use eleventyComputed to either set it to true or false, based on whether there is a frontmatter of draft: true AND you are in production mode. If you then also use eleventyComputed to set permalink to false, as described by @hirusi in her dev.to post, you pretty much have a draft status feature.

**Comment by edwardhorsford** [comment]
@makkabi 

Here's how I use them - I reference a env var that determines whether they're true or not - no need for `eleventyComputed` (which didn't exist when I was working on these pages).

<img width="1113" alt="Screenshot 2020-08-03 at 15 20 49" src="https://user-images.githubusercontent.com/2204224/89192958-3096ea80-d59d-11ea-9ba1-7d8c14a4b7ad.png">


I would say they're not quite a substitute for draft. Even with `eleventyExcludeFromCollections`, eleventy _still_ processes the file. In my case, some of my templates are very costly to process. So even though they have `permalink: false` and `eleventyExcludeFromCollections: true`, they still take ages to be processed. In the end I've had to manually add them to `eleventyIgnore` to work around this.

**Comment by makkabi** [comment]
@edwardhorsford Thanks! In the end all the discussed solutions are workarounds for a very basic feature, and I hope that 11ty will soon have a built-in (and optimized) way to do this.

**Comment by zachleat** [comment]
#188 is the home base for this one
