### ISSUE TITLE
addPassthroughCopy doesn’t respect .eleventyignore entries

### ISSUE THREAD

**Issue by gem0303** [11ty/eleventy#1252]
**Describe the bug**
When I use a glob in addPassthroughCopy, it appears to be overriding or ignoring my .eleventyignore file.

**To Reproduce**
I am using the "glob" method with addPassthroughCopy as described in the docs.

```
module.exports = function(eleventyConfig) {
  eleventyConfig.addPassthroughCopy("**/*.css")
  eleventyConfig.addPassthroughCopy("**/*.js")
}
```

Site is also set up to copy jpg, png, gif, mp4, and pdf.

My .eleventyignore file looks like this:
```
_site/
node_modules/
```

When I run Eleventy, I end up with a node_modules folder inside my output folder (_site). If I run Eleventy again, my _site folder has another _site folder nested inside it. Subsequent runs also throw multiple errors for TemplatePassthroughError, TempateWriterWriteError, TemplatePassthroughManagerCopyError, and Error ENOENT no such file or directory.

The .eleventyignore file does not seem to be working.

**Expected behavior**
My site should process to the _site folder, and NOT include anything from node_modules. If I run Eleventy again, my _site folder should not have another _site folder nested inside it.

**Environment:**

- OS and Version: WIndows 10
- Eleventy Version 0.11

**Additional context**
addPassthroughCopy works if I do not use glob syntax, like this:
```
eleventyConfig.addPassthroughCopy("culture/*/*.gif")
eleventyConfig.addPassthroughCopy("culture/facts.js")
```

But I have css, js and image files located in several different subfolders. I did not want to have to keep "whitelisting" every file that needed to be passed through. Therefore the glob method made more sense, even though it's slower.

**Comment by samuelpath** [comment]
Same issue as #1134 ?

**Comment by gem0303** [comment]
@samuelpath Yes, looks like the same problem. Could've sworn I searched the issues list to avoid posting a duplicate, but here we are. Would you like me to close this issue or is there a way to merge it into the other one?

**Comment by b3u** [comment]
@gem0303 I like how much detail you put in yours. I would close this issue, and add any thoughts to #1134.
