### ISSUE TITLE
TypeError: Expected a non-empty string

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#1253]
I believe this is filed upstream here: https://github.com/mrmlnc/fast-glob/issues/276

Until it’s fixed you can declare `"fast-glob": "3.2.2"` in your dependencies in package.json alongside eleventy and that should fix it.

e.g.:

```
    "@11ty/eleventy": "^0.11.0",
    "fast-glob": "3.2.2",
```

**Comment by mrmlnc** [comment]
Must be fixed by [`fast-glob@3.2.4`](https://github.com/mrmlnc/fast-glob/releases/tag/3.2.4). I'm sorry about this situation. I wrote the missing tests.

**Comment by zachleat** [comment]
No worries @mrmlnc—really appreciate the quick resolution! I’ll retest

**Comment by zachleat** [comment]
Resolved—thank you!

Because we use `^3.2.2` in Eleventy this is fixed as it’ll pick up `3.2.4` automatically.
