### ISSUE TITLE
JSTL Language Support

### ISSUE THREAD

**Issue by jonathantneal** [11ty/eleventy#1268]
I was super excited to see that Eleventy supports Template Literal files today!

https://www.11ty.dev/docs/languages/jstl/

I was super sad to see that there was not language support for JSTL files on VSCode. So I wrote one!

https://marketplace.visualstudio.com/items?itemName=jsxtools.jstl

Feel free to close this, but I’ve shared it in case you highlight this kind of support in the docs or elsewhere.

**Comment by zachleat** [comment]
Ah super sorry @jonathantneal—this template type was removed form core in 1.0, we’re recommending the JS one instead 

https://www.11ty.dev/docs/languages/jstl/
