### ISSUE TITLE
Sidebar on searchpage bugged

### ISSUE THREAD

**Issue by Miosame** [11ty/eleventy#1270]
If you are on: https://www.11ty.dev/docs/search/ and try to select / click most of the sidebar, it's not working, some parts of the sidebar work, others don't.

Starting with `Working with Templates` submenu item: `Layouts` going all the way through to `Configuration` submenu item `Events`.

![image](https://user-images.githubusercontent.com/8201077/85096199-fe4f4a80-b1f3-11ea-8ef9-ff40bb01a1d8.png)

**Comment by raduchiriac** [comment]
I think it got fixed with https://github.com/11ty/11ty-website/commit/2bca2b17730ca9a539005e37816a316b8f744886

**Comment by Miosame** [comment]
Can confirm, closing!
