### ISSUE TITLE
url filter does not work inside markdown

### ISSUE THREAD

**Issue by Miosame** [11ty/eleventy#1271]
`pathPrefix: "/test/"`

It doesn't matter if the engine for markdown is set to liquid (default) or nunjucks via `markdownTemplateEngine: "njk"` both ignore the `url` filter, easy test it to create a markdown file and throw in `{{ "img/test/test.png" | url }}` - all nunjucks / liquid built in filters work (e.g. `length` in njk), but the url filter is ignored, even though it works in e.g. `njk` template files just fine. 

The above example outputs just `"img/test/test.png"`, yet it should output `"/test/img/test/test.png"`.

**Comment by denisbrodbeck** [comment]
@Miosame This works as intended, using it myself.

The conversion rules are explained [here](https://www.11ty.dev/docs/filters/url/).

Using `{{ "img/test/test.png" | url }}` doesn't work (covered by the [docs](https://www.11ty.dev/docs/filters/url/)).

Try `{{ "/img/test/test.png" | url }}` instead.

**Comment by Miosame** [comment]
@denisbrodbeck odd, I was absolutely sure I've tried it with a prefixed slash, guess I've got now other questions regarding this behavior, but not anymore as a bug report, thanks!
