### ISSUE TITLE
How can I access the content/body when iterating through a collection of .md files with njk

### ISSUE THREAD

**Issue by Simon-Yung** [11ty/eleventy#1275]
Hello, I'm probably missing something obvious but I can't figure out the proper way to access the main content of a markdown file when referenced as an object within a nunjucks layout.

I'm trying to display the main content, (the whole part after the front matter, not just an excerpt ), of several markdown files all stored within the same folder.

So created a collection of them:
> eleventyConfig.addCollection("allFiles", function(collectionApi) {
> > return collectionApi.getFilteredByGlob("_all_the_files/*.md"); 

> }

And used a for loop to display their content:
 >   {%- for file in collections.allFiles %}
 > > \<h1>{{ file.data.title }}\</h1>
 > > \<p>{{ file.content | safe }}\</p> 

 > {%- endfor %}

But
 > <h3>{{ file.content | safe }}</h3>
doesn't actually work. 
Neither does {{ file.data.content }}{{ file[content] }}{{ file content }} nor does {{ file.data.body }}{{ file[body] }} and {{ file }} just return [object Object].

Is what I'm trying to do even implemented ?

**Comment by mslooten** [comment]
@Simon-Yung Have you tried file.templateContent? This will output the rendered HTML of the markdown contents: https://www.11ty.dev/docs/collections/#collection-item-data-structure

Tried it myself, it seems to be what you're after (unless there's another way but this is the one I could find).

**Comment by Simon-Yung** [comment]
Thanks, I felt like I was missing something.
I was looking for the unrendered content but this will do fine.

Thanks again.
