### ISSUE TITLE
How to refer to Eleventy?

### ISSUE THREAD

**Issue by MaybeThisIsRu** [11ty/eleventy#1283]
Hi, so this has been confusing me for a while. When talking about Eleventy, I'm not sure what is the intended way to refer to it.

Is it:

* 11ty
* eleventy
* Eleventy
* @11ty/eleventy

I'd love to have an official response on this, thank you!

**Comment by zachleat** [comment]
Very good question.

The pattern here is that `11ty` is specifically for the logo and URLs. For all other things, `Eleventy` should be standard. We could add some brand guidelines on the web site if that would be helpful to folks.

**Comment by hirusi** [comment]
That makes sense. It would be great if we could find a spot for this in the documentation.

**Comment by zachleat** [comment]
Docs deploying to the glossary here: https://www.11ty.dev/docs/glossary/#where-did-the-name-come-from
