### ISSUE TITLE
Using a for loop in Liquid renders content in <code><pre>... </pre></code> wrapper

### ISSUE THREAD

**Issue by j3ffgray** [11ty/eleventy#1285]
**Describe the bug**
I'm passing in the property "tags" as a comma separated list into a liquid partial. Inside the partial, I'm breaking that into an array using a technique noted in the docs.

    {% assign t = tags | split: ", " %}
    {% for item in t %} <span class="demo-tag"> {{ item }} </span> {% endfor %}

When this is rendered, it wraps that for loop in a code and pre tag wrapper.

<pre><code> &lt;span class="demo-tag"&gt; tacos &lt;/span&gt;  &lt;span class="demo-tag"&gt; burritos &lt;/span&gt;  &lt;span class="demo-tag"&gt; taquitos &lt;/span&gt; 
</code></pre>

**Expected behavior**
Is there a way to prevent that wrapper and cleanly write the HTML in?

**Comment by denisbrodbeck** [comment]
I don't think we can we can triage the issue without a little bit more of your code.
What is the surrounding template code? Does it get transformed multiple time (like you have a markdown file, which first gets transformed through `liquid` and after that through `markdown-it`)?
If that file is a `markdown` file, are you aware that there is an [alternative syntax](https://commonmark.org/help/) for code fences, which automatically parses *every* line with four leading spaces ` ` as a code fence (which is highly annoying and most times not what was intended)?

**Comment by j3ffgray** [comment]
This is the layout of things:
_includes
  layouts
    tutorial.liquid
  partials
    card.liquid
learn
  new-tutorial.md

The new-tutorial.md is using the tutorial.liquid for its general rendering. Occasionally, mixed with the markdown, I'll make a call to a partial so that I can include a design pattern and pass some parameters. So, the markdown looks something like this...

```
---
front-matter: "a setting"
---

# header here

Some text and **something bold** is happening.

{% include partials/card text:"card stuff", tags:"list, of, stuff, with, spaces" %}

## Additional stuff...
```

The card.liquid has something simple like:

```
<div class="card-element">
  <span class="tags">
    {% assign t = tags | split: ", " %}
    {% for item in t %} <span class="demo-tag"> {{ item }} </span> {% endfor %}
  </span>
</div>
```

Rather than the for loop rendering HTML, it ends up wrapping all that content in a pre and code tag, which I can't seem to disable.

Hopefully that provides some additional context.

**Comment by j3ffgray** [comment]
Apologies, I thought I had replied directly after you posted. This information was very helpful, thank you!

**Comment by zachleat** [comment]
I think this is another Indented Code Blocks victim https://www.11ty.dev/docs/languages/markdown/#indented-code-blocks

The default behavior changed in 2.0: #2438
