### ISSUE TITLE
Markdown-it, SmartQuotes and multiple languages

### ISSUE THREAD

**Issue by TigersWay** [11ty/eleventy#1292]
Hi,
I'm trying to use the SmartQuotes feature from Markdown-it. When set globally in my `.eleventy.js` it works fine except I can treat only one language at a time.
I have - of course - different folders for each language.

Anyone has any idea how to set the quote option - access to the markdown "library" - from a template or directory data file?
Thanks

**Comment by zachleat** [comment]
The smart quotes replacements from the `typographer` option in markdown-it are supposed to be “language-neutral”

https://github.com/markdown-it/markdown-it?tab=readme-ov-file#init-with-presets-and-options
https://github.com/markdown-it/markdown-it/blob/master/lib/rules_core/replacements.mjs

This might be a better question for the markdown-it folks https://github.com/markdown-it/markdown-it
