### ISSUE TITLE
Should .data.content work on a collection item?

### ISSUE THREAD

**Issue by smth** [11ty/eleventy#1294]
For example:

``` 
{{ collections.mycollection[0].data.content | safe }}
```

I'm doing something like this in at least one project, with the same version of 11ty (0.11.0) without issue, but today, on a fresh project it's not returning anything.. I'm confused. Here I would normally try `{{ collections.mycollection[0].data | dump }}` but that's giving me a `Converting circular structure to JSON` error. I can get (and dump) `collections.mycollection[0].data.page` fine.

**Comment by DenizAksimsek** [comment]
You could try the following to log the object's properties (at least in Nunjucks): 

```njk
<pre>
{%for prop, val in collections.mycollection[0].data%}
{{prop}}: {{val}}
{%endfor%}
</pre>
```

**Comment by zachleat** [comment]
Support for `collections.mycollection[0].templateContent` was the thing you wanted (he says much too late)

I did _just_ add support for `collections.mycollection[0].content` in 2.0.0-canary.19 with #2695 #1522

The docs have been updated to reflect that https://www.11ty.dev/docs/collections/#collection-item-data-structure

Here are the old docs you wanted for good measure: https://v1-0-2.11ty.dev/docs/collections/#collection-item-data-structure
