### ISSUE TITLE
Improving visited links with localStorage

### ISSUE THREAD

**Issue by pagaidu** [11ty/eleventy#1296]
Am trying to improve visited links by using localStorage as in http://joelcalifa.com/blog/revisiting-visited/

```
localStorage.setItem('visited-'+window.location.pathname,true);
var links = document.getElementsByTagName('a');
for (i=0;i<links.length;i++) {   
  var link = links[i];
  if (link.host == window.location.host
  && localStorage.getItem('visited-' + link.pathname + '/')) {
    link.dataset.visited = true;
  }
}
```
JS is in separate file right above `</body>`

CSS
```
a[data-visited] {
  border-bottom: 1px dashed purple;
}

a[data-visited]:after {
  content: ' (Seen)';
}
```
When all set the CSS styles are not applied to visited links.
Does this solution for Eleventy involves additional work?

**Comment by zachleat** [comment]
Sorry but we are unable to provide general CSS/JavaScript help on this issue tracker!
