### ISSUE TITLE
Tags doesn't work correctly inside eeleventyComputed

### ISSUE THREAD

**Issue by winston0410** [11ty/eleventy#1297]
**Describe the bug**

Tags doesn't work correctly inside `eleventyComputed`.  The collections of that tag returns undefined.

**To Reproduce**

1. Add tags inside front matter
```
---
eleventyComputed:
  tags: ['cv', 'menu-{{index.lang}}']
  permalink: "/{{ index.lang | urlEncode}}/cv/"
---
```
2. Get the value of the collection with `log`
{{ collections.cv | log }}
3. The collection return undefined.

**Expected behavior**

I expect tags being used inside `eleventyComputed` can be functional.

**Screenshots**

**Environment:**

- OS and Version: [e.g. Windows/Mac/Linux] 
- Eleventy Version [via `eleventy --version` or `npx @11ty/eleventy --version`] 0.11.0

**Additional context**

**Comment by zachleat** [comment]
Correct, we have a pretty hefty warning at the top of https://www.11ty.dev/docs/data-computed/ about this
