### ISSUE TITLE
Hot-reloading css behaviour with browsersync

### ISSUE THREAD

**Issue by s-g-k** [11ty/eleventy#1298]
Hello! 

I have an 11ty project with some nunjucks templates and some vanilla CSS-files. 

When I update my CSS file in `src/_assets` Eleventy registers the update:
```
Watching…
[Browsersync] Reloading Browsers...
File changed: src/_assets/style.css
```
11ty then rebuilds all my files before it copies the CSS to the correct directory `dist/assets`. This is painfully slow and means that I don't see an update in my browser for 5–6 seconds. If I try updating the `dist/assets/style.css` file directly, Browsersync updates the browser instantly.

I am expecting/hoping that Eleventy can copy `style.css` to my `dist/assets` directory **without re-building** the template files. 

Is there a way to get this behaviour? 

Maybe I've just missed something very obvious in the documentation? Any help or pointers greatly appreciated! 

My config looks something like this:
```js
module.exports = function (config) {
  config.addPassthroughCopy({ 'src/_assets': 'assets' })

  config.addFilter('localize', function (value, locale) {
    return localize(value, locale)
  })

  config.addTransform("html-pretty", function(content, outputPath) {
    if (outputPath.endsWith(".html")) {
      return pretty(content, { ocd: true })
    }

    return content
  })

  return {
    passthroughFileCopy: true,
    templateFormats: ['njk'],
    dir: {
      input: 'src',
      output: 'dist'
    }
  }
}

```

**Comment by msahyoun** [comment]
Take a look at  #1289 for a potential solution.

**Comment by s-g-k** [comment]
It seems like the behaviour I want should be available using the  `--incremental` flag when running `eleventy`.

Issues #1109 and #977 are more closely related to my issue, some talk about this on #1174 too.

This is **almost** working. Eleventy now starts by building everything (as expected). When I update my CSS, it gets copied over: 

```
[Browsersync] Serving files from: dist
File changed: src/_assets/style.css
----benchmark data
Copied 1 file / Wrote 0 files in 1.41 seconds (v0.11.0)
Watching…
[Browsersync] Reloading files that match: *.css
```

But instead of being copied from `src/_assets` to `dist/assets` as the first build/copy, eleventy now ignores my passThrough config and copies the file to `dist/_assets` instead. Strange behaviour, and probably in need of a new issue.

**Comment by jgerigmeyer** [comment]
@aaadotpm I'm seeing the same thing. It sounds closely related to https://github.com/11ty/eleventy/issues/2182, perhaps?
