### ISSUE TITLE
Document internal data structure for content in /docs/

### ISSUE THREAD

**Issue by chrisdmacrae** [11ty/eleventy#130]
Just requesting a formal doc outlining the data structure for a page. A lot of this is outlined between docs & the readme, it's just spread out.

Right now, it's not clear for new users how to access different data (e.g, URL versus Title) between layouts, pages, pagination, etc.

> Know this from usage in a team; they used to look to the Jekyll reference all the time w/ we used Jekyll

It's also not clear what's available. E.g:

- URL
- InputPath
- OutputPath
- FileSlug
- Custom Data

I propose we take an approach like Jekyll/Hugo. Have a doc per scope (leaf, layout, data file, pagination, collection) that outlines the core data structure.

E.g:

## Leafs (Pages)
| Variable | Description | Usage |
| --- | --- | --- |
| URL | The final web-safe permalink for the page | `url` |
| Input Path | The file path to the source file | `inputPath` |
| Output Path | The file path to the rendered output file | `outputPath` |
| File Slug | A slug derived from the source file's name | `fileSlug` |

**Comment by chrisdmacrae** [comment]
Just to add a note to this:

In a collection, you're accessing things as `collections.all[0].data.varname`

In a template, you're accessing things as `varname`. I.e, you're given direct access to the `data` param from collections.

In pagination, you're accessing things as `pagination.items[0].varname`, i.e, you're given direct access to the `data` param from collections.

**Comment by zachleat** [comment]
Just for posterity as I work on this, some of it is at: https://www.11ty.io/docs/collections/#individual-collection-items-(useful-for-sort-callbacks)

**Comment by zachleat** [comment]
Things I want to have a consistent object structure (please chime in if there are others):

1. The `page` variable available on a leaf template. With this exception that this currently does not include `data`(should this change?), which is currently exposed as globals.
1. An individual item inside a `collection` (e.g. `collections.all[0]`)
1. An individual item inside `pagination.items` (e.g. `pagination.items[0]`)

Outstanding questions:
1. What is `pagination.data` and how is it different from `pagination.items[0].data`?
1. Should `pagination.nextPageLink` and `pagination.previousPageLink` be aliased as `nextPageUrl` and `previousPageUrl` for consistency? (probably) What about `pageLinks`?

@chrisdmacrae is it confusing that pagination is separate in this way? The `pagination.items` array holds the items that are being currently paginated. Would appreciate help understanding where I could improve that.

**Comment by zachleat** [comment]
Related: #338 to fix this instead of adding more docs

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for documentation requests. This means documentation issues will now be closed instead of leaving them open.

View [the documentation queue backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Areactions-%2B1-desc+is%3Aclosed+label%3Adocumentation+label%3Aneeds-votes). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
Some work will ship on this with #1522 (you can see those changes better defined in #2695) but I would consider the inconsistency in collection items that `data` is not available at the top level as properties to be one of the last remaining items here. 

https://www.11ty.dev/docs/collections/#collection-item-data-structure
