### ISSUE TITLE
How to use slug Filter in Shortcodes?

### ISSUE THREAD

**Issue by huphtur** [11ty/eleventy#1308]
Say I have following shortcode (set up based on [eleventy-shortcomps](https://github.com/adamduncan/eleventy-shortcomps) starter project).

```js
// Bio.js
module.exports = (name, bio) => {
  return `
    <img src="/img/${name}.jpg" alt="${name} headshot.">
    <h1>${name}</h1>
    <p>${bio}</p>
  `;
};
```

Which is available via Nunjucks syntax:
```nunjucks
{% Bio 'Zach Leatherman', 'Zach is a builder for the web with Netlify.' %}
```

How can I utilize Eleventy's universal [`slug`](https://www.11ty.dev/docs/filters/slug/) filter on `name` to produce the following result:

```html
<img src="/img/zach-leatherman.jpg" alt="Zach Leatherman headshot.">
<h1>Zach Leatherman</h1>
<p>Zach is a builder for the web with Netlify.</p>
```

**Comment by danjrichardson** [comment]
I'm not 100% on this myself, but you can just use the package directly in your `Bio.js` file, and use the same set up as the slug filter itself:

```
// Bio.js
var slugify = require('slugify')

const slug = (name) => slugify(name, {
	replacement: "-",
	lower: true
})

module.exports = (name, bio) => {
  return `
    <img src="/img/${slug(name)}.jpg" alt="${name} headshot.">
    <h1>${name}</h1>
    <p>${bio}</p>
  `;
};
```

**Comment by huphtur** [comment]
Guess that works. Thanks @danjrichardson

**Comment by pdehaan** [comment]
Not sure if it'd work with your exact setup, but I believe you can also access the built-in filters (in 0.11+) via the `eleventyConfig.getFilter()` method:

```js
module.exports = (eleventyConfig) => {
  eleventyConfig.addShortcode("Bio", (name, alt, desc="") => {
    const slug = eleventyConfig.getFilter("slug");
    return `<div>
      <img src="/img/${slug(name)}.jpg" alt="${alt}" />
      <p>${desc}</p>
    </div>`;
  });

  return {
    dir: {
      input: "src",
      output: "www"
    }
  };
};

```

&mdash; via https://www.11ty.dev/docs/filters/#access-existing-filters
