### ISSUE TITLE
Strategies to help developers mitigate breaking changes in 1.0

### ISSUE THREAD

**Issue by nhoizey** [11ty/eleventy#1322]
There are multiple things that could be done to enhance Eleventy but require breaking changes.

Would it make sense to release a 0.12.0 version to prepare these breaking changes before they happen in version 1.0?

A build in this 0.12.0 could then generate deprecation/change warnings in the console, without actually changing anything from 0.11.0.

Changes I have in mind:
- Better `slugify` function: https://github.com/11ty/eleventy/issues/278#issuecomment-660867932
- Don't ignore files that are in `addWatchTarget` even if they are in `.gitignore` or `.eleventyignore`? (maybe): https://github.com/11ty/eleventy/issues/893#issuecomment-609041756
- Use objects for options to ease future evolution: https://github.com/11ty/eleventy/issues/789#issuecomment-633530985

**Feel free to comment to add others!**

**Comment by Ryuno-Ki** [comment]
References to Liquid #1334.
I think, I found a reason why it wasn't updated yet, but I can't find the issue.

**Comment by edwardhorsford** [comment]
Default to including all items from pagination in `collections.all`

**Comment by zachleat** [comment]
https://github.com/orgs/11ty/projects/5

**Comment by nhoizey** [comment]
@zachleat I understand you still think breaking changes in the 1.0 release don't need any previous deprecation/change warning in an intermediate release?

I know some of the changes I would like to see won't be in 1.0, so I'll have to wait for a 2.0… 😅

**Comment by zachleat** [comment]
I plan to do as much runtime communication in 1.0 as possible. https://github.com/11ty/eleventy/issues/1390 will be a good example of this. If we detect `strictFilters` in your Liquid config, we’ll warn you and provide info on what you need to change

**Comment by zachleat** [comment]
Look for INPUT DIR (if not same as ROOT DIR) `.gitignore` and warn

**Comment by zachleat** [comment]
Some work has started on this here: https://github.com/11ty/eleventy-upgrade-help

**Comment by zachleat** [comment]
Switching to https://github.com/11ty/eleventy/issues/1393 as the home base for this one! Subscribe over there if you’d like!
