### ISSUE TITLE
Filter returning object instead of value

### ISSUE THREAD

**Issue by WebShapedBiz** [11ty/eleventy#1324]
Hi.
I'm trying, for the purpose of having an enclosure in RSS feed, to get the size and MIME type of the post feature image.
Using this as my "size" filter...
```
const request = require("request");
config.addFilter('size', url => {
    return request.head({
      url: url,
      method: "HEAD"
    }, function (err, response, body) {
        return response.headers['content-length'];
    });
  });
```
... I'm getting an object returned, resulting in this in my `feed.njk` enclosure:
```
length="[object Object]"
```
However, if I log to console inside the `function`, instead of `return response.headers['content-length'];`, I'm correctly getting the file length value.

What am I doing wrong here?

Cheers.

**Comment by pdehaan** [comment]
@WebShapedBiz I _think_ that Nunjucks/11ty isn't liking that callback function possibly. I managed to get this working locally using an async `addNunjucksAsyncFilter()` filter:

```js
const request = require("request");

module.exports = (config) => {
  config.addNunjucksAsyncFilter("size", (url, callback) => {
    request.head({
      url,
      method: "HEAD"
    }, function (err, response) {
      if (err) {
        console.error(err);
        return callback(err);
      }
      return callback(null, response.headers["content-length"]);
    });
  });

  return {
    dir: {
      input: "src",
      output: "www"
    }
  };
};
```

Then, in my random .njk file I have the following:

```nunjucks
<p>{{ "https://mozilla.org/" | size }}</p>
```

Which generates the following output:

```html
<p>165183</p>
```

I tried a couple other random sites and not all of them apparently returned a `content-length` header, so you might need a bit more error checking, depending on your situation.

**Comment by pdehaan** [comment]
Also, it looks like the [**request** module is now deprecated](https://www.npmjs.com/package/request), so here's an example that uses **got** (although **axios** is also a great option). Also shows some light error checking for the "content-length" header and uses promises/async just for fun.

```js
const got = require("got");

module.exports = (config) => {
  config.addNunjucksAsyncFilter("size", async (url, callback) => {
    try {
      const { headers } = await got.head(url);
      const clength = headers.hasOwnProperty("content-length")
        ? headers["content-length"]
        : "Unknown";
      callback(null, clength);
    } catch (err) {
      console.error(err);
      callback(err);
    }
  });

  return {
    dir: {
      input: "src",
      output: "www",
    },
  };
};
```

Sample:

```nunjucks
<p>1. {{ "https://s3.amazonaws.com/assets.coveralls.io/badges/coveralls_98.svg" | size }}</p>
<p>2. {{ "https://bing.com/" | size }}</p>
<p>3. {{ "https://abookapart.com/" | size }}</p>

<!--
<p>1. 724</p>
<p>2. 0</p>
<p>3. Unknown</p>
-->
```

**Comment by WebShapedBiz** [comment]
You're golden @pdehaan, thank you sooo much for your time and effort put in this elaborate post.
I am aware that `content-length` header is not a standard response, but I'm developing this for the headless Ghost publishing solution that will be hosted on my DigitalOcean server, so for the known source.

Godspeed.
