### ISSUE TITLE
Bug with passthrough copy `js` file extensions in templateFormats

### ISSUE THREAD

**Issue by stowball** [11ty/eleventy#1325]
**Describe the bug**

Last night I unsuccesfully tried to upgrade my 0.9.0 project to 0.11.0 (also tried 0.10.0) and [tweeted](https://twitter.com/stowball/status/1285925002672406528).

Now, I may have completely the wrong idea of how to integrate JS and SCSS with Eleventy, but I have a separate webpack process which handles the importing and building of that, and my 0.9.0 eleventy config would allow for automatic reloading upon changing either SCSS or JS (it takes saving the assets 2 times for some reason?).

However, as soon as 0.10.0+ encounters the `import` statements in my JS, it explodes with:

```sh
Unhandled rejection in promise ([object Promise]): (more in DEBUG output)
> Unexpected string

`SyntaxError` was thrown:
    /Users/mattstow/Git/stowball/eleventy-bug-repro/src/assets/js/index.js:1
    (function (exports, require, module, __filename, __dirname) { import '../css/index.scss';
                                                                         ^^^^^^^^^^^^^^^^^^^

    SyntaxError: Unexpected string
        at new Script (vm.js:79:7)
        at createScript (vm.js:251:10)
        at Object.runInThisContext (vm.js:303:10)
        at Module._compile (internal/modules/cjs/loader.js:657:28)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        at Module.load (internal/modules/cjs/loader.js:599:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (internal/modules/cjs/helpers.js:22:18)
```

I have pushed a simple, reproducible repo here: https://github.com/stowball/eleventy-bug-repro

My `.eleventy.js` file looks like this:

```js
module.exports = function(eleventyConfig) {
  eleventyConfig.addPassthroughCopy('src/dist');

  return {
    dir: {
      input: 'src',
      layouts: '_layouts',
    },
    markdownTemplateEngine: 'ejs',
    passthroughFileCopy: true,
    templateFormats: [
      'css',
      'ejs',
      'js', // Remove this to make it work in 0.10.0+, but then I can't reload changes to assets like in 0.9.0
    ],
  };
};
```

I have seen some people have eleventy compile their CSS automatically (and insert it in the `head`?), but since I use atomic CSS, my generated file is in the many megabytes, which is why I opt for generating a normal CSS file which I can then purge for production.

**To Reproduce**

1. Clone the above repo
2. In one terminal, run `npm run serve:assets`
3. In another terminal, run `npm run serve:site`
4. The above error is encountered.

**Expected behavior**
For it to continue to build, like 0.9.0 did. Or for someone to point me in the right direction for how I should be working with external assets?

**Environment:**

- OS and Version: Mac 10.14.6
- Eleventy Version 0.11.0

**Comment by MadeByMike** [comment]
I have no idea how this was working in v9 as it should be trying to parse that JS file as a template and not able to read the imports like it says.

You can remove JS from templateFormats or use `.eleventyIgnore` (https://www.11ty.dev/docs/ignores/) - then use `addWatchTarget`: (https://www.11ty.dev/docs/config/#add-your-own-watch-targets) to recompile.

Sorry... I know this doesn't give a reason for the bug.

**Comment by stowball** [comment]
So it appears the best performing solution is to add

```
eleventyConfig.addWatchTarget('./src/assets/css/');
eleventyConfig.addWatchTarget('./src/assets/js/');
```

and set:

```
templateFormats: [
  'ejs',
  'md',
],
```

Although it reloads on saving the files, the built files aren't generated, so I have to save again after webpack is finished before seeing the changes. It would be great if I could figure out how not to have to do that…

I've tried adding a watch target for the `dist` folder, but that doesn't seem to work at all 🤷‍♂️

**Comment by zachleat** [comment]
This is a bug!

I would expect `js` as a template format to passthrough copy as normal. This is the whole reason why we use the extra specific `.11ty.js` suffix for Eleventy JS templates.

HOWEVER, there is a bug with the feature to automatically watch JavaScript dependencies. See https://www.11ty.dev/docs/watch-serve/#watch-javascript-dependencies.

You can disable this with `eleventyConfig.setWatchJavaScriptDependencies(false);` and it should work as expected (although that might be undesirable too). We need to update the dependence tree code to filter out passthrough copy files!

**Comment by zachleat** [comment]
This’ll ship with 1.0

**Comment by MelanieL** [comment]
I'm not sure if this helps anyone, but I fought with this for almost 2 hours. Because I kept seeing that Node 8.0 or higher was required, I assumed Node wasn't the issue because mine was 11.something. 

However, once I updated Node on my system (to 14.15.5) the problem instantly disappeared. I know this doesn't work for everyone, but hopefully it saves someone some frustration. 

Good luck!
