### ISSUE TITLE
Pages created via pagination and eleventyComputed aren't available in collections.all

### ISSUE THREAD

**Issue by tony-navillus** [11ty/eleventy#1326]
**Describe the bug**
When using `pagination` and `eleventyComputed` to dynamically create pages, only the first one is actually added to `collections.all`.  I'm combining the [Pagination](https://www.11ty.dev/docs/pagination/) and [Computed Data](https://www.11ty.dev/docs/data-computed/) so it's possible I just didn't combine the two strategies properly?

**To Reproduce**

I created a minimal repro [here](https://github.com/tony-navillus/11ty-navigation-repro)

1. git clone or `npx degit` the repro to pull it down locally
2. run the `start` or `build` scripts to output the data
3. serve the generated files locally and navigate to the home page
4. follow the `Indoor` and `Outdoor` links in the body of the home page

**Expected behavior**
- All three routes (`/`, `/products/indoor/`, `/products/outdoor/`) should be generated
- `{{ collections.all | eleventyNavigation | eleventyNavigationToHtml | safe }}` should have the `Home` page and 2 child pages, `Indoor` and `Outdoor`

**Actual behavior**
All 3 pages are built, but only `Home` and `Indoor` are included in navigation

**Environment:**

- OS and Version: Windows 10 (19041.388)
- Eleventy Version 0.11.0
- Eleventy Navigation Version 0.1.6

**Comment by ivanov-v** [comment]
I got this bug too.
Generated:
![image](https://user-images.githubusercontent.com/13759065/88460474-1bd39c00-cea5-11ea-858b-860159406c28.png)

Collections:
/ru/
/en/
/en/404/
/ru/404/
/en/vacancies/frontend/
/ru/vacancies/frontend/
/en/vacancies/
/ru/vacancies/

**Comment by ivanov-v** [comment]
@tony-navillus [solution](https://github.com/11ty/eleventy/issues/1262)

**Comment by tony-navillus** [comment]
Thanks @ivanov-v!  I had searched both the docs and closed issues but didn't to check if it was related directly to `pagination` rather than `eleventyComputed`

Closing this bug, it's covered by #1262 and also in the [pagination docs](https://www.11ty.dev/docs/pagination/#add-all-pagination-pages-to-collections)
