### ISSUE TITLE
Adding tags or layout to subfolders

### ISSUE THREAD

**Issue by MatejKustec** [11ty/eleventy#1330]
Is it possible to populate tags automatically to subfolders?

What I've seen so far in examples is only this:

```
├── posts
│   ├── first-post.md
│   ├── second-post.md
│   ├── third-post.md
│   ├── posts.json
```
`posts.json` file
```
{
    "tags": "posts"
}
```
But my folder structure would look like this

```
├── my-first-post
│   ├── index.md
├── my-second-post
│   ├── index.md
├── my-third-post
│   ├── index.md
├── posts.json
```
Now I'm wondering how could I populate tags from `posts.json` to subfolders?

**Comment by nhoizey** [comment]
@MatejKustec if your `my-first-post`, `my-second-post`, etc. folders are in a shared folder (`posts` for example), you can use the same `posts.json` file, it is not limited to one level.

**Comment by MatejKustec** [comment]
@nhoizey Thanks, I see now where I've made the mistake, my root folder name was `blog` but I had `posts.json` file where it should be named `blog.json`. When I've renamed that folder I got the data in the collection.
