### ISSUE TITLE
Directory data in js front matter

### ISSUE THREAD

**Issue by ivanov-v** [11ty/eleventy#1332]
**Describe the bug**
I use Directory Data File for localization (en.json -> {"locale": "en"}), and want to use **locale** variable in front matter.
![image](https://user-images.githubusercontent.com/13759065/88594949-d19c1780-d06a-11ea-97cb-00f5c398dd6e.png)

**To Reproduce**
Use ---js front matter and directory data file:
![image](https://user-images.githubusercontent.com/13759065/88594236-88979380-d069-11ea-9a74-de526f8c4135.png)

**Expected behavior**
I expect to be substituted with the **locale** value "en"

**Environment:**

- OS and Version: Mac
- Eleventy Version: 0.11.0

**Additional context**
It's work with liquid, but I cant use **before** to filter out some item:

![image](https://user-images.githubusercontent.com/13759065/88594541-052a7200-d06a-11ea-8fab-07405f28b5b5.png)

**Comment by samuelpath** [comment]
Hi @ivanov-v 

Looking at the [sources of data](https://www.11ty.dev/docs/data-template-dir/#sources-of-data) documentation, it seems to me that Front Matter Data takes precedence over Directory Data Files.

I think that this implies that you can use only use data from sources higher up in the cascade, meaning that 

I'm not an expert but this is how I understand the documentation.

Does this make sense to you?

Regards,
Samuel

**Comment by samuelpath** [comment]
Maybe related to #915 ?

**Comment by zachleat** [comment]
This is almost certainly related to Data Deep Merge. This is now enabled by default in Eleventy 1.0 and newer https://www.11ty.dev/docs/data-deep-merge/
