### ISSUE TITLE
liquidjs is out-of-date

### ISSUE THREAD

**Issue by binyamin** [11ty/eleventy#1334]
I'm on 11ty 0.11.0, and the version of liquidjs has a bug (https://github.com/harttle/liquidjs/issues/227) which has been fixed in v9.12.0. 11ty is still using v6.4.3. Please update it.

I tested liquid with and without eleventy. The bug is only present when using 11ty.

**Comment by b3u** [comment]
tests pass with updated package

**Comment by muffinresearch** [comment]
FWIW, as a workaround you can add the more recent liquidjs version as a dep and set your own liquidjs instance as detailed here. https://www.11ty.dev/docs/languages/liquid/#optional-set-your-own-library-instance

**Comment by samuelpath** [comment]
Same issue as #862 ?

**Comment by b3u** [comment]
I might be biased, but I think issue is written more clearly. Should @barcia close their issue?

**Comment by hirusi** [comment]
> FWIW, as a workaround you can add the more recent liquidjs version as a dep and set your own liquidjs instance as detailed here. https://www.11ty.dev/docs/languages/liquid/#optional-set-your-own-library-instance

Does this break Eleventy in that it doesn't include `templateContent` or `content` with the collection items or page data any more?

I'll create a repo to check as I believe this is in fact happening.

**Comment by binyamin** [comment]
Fixed in a37a5c675d97268dab50e83e4692e152be9fbf0d

**Comment by sschuldenzucker** [comment]
Polite request to bump one more minor version to `liquidjs-9.17.0` to include my [patch](https://github.com/harttle/liquidjs/commit/768fb79e32d84cdacee79a080f0d07a8a7439558) that makes it much more feasible to use "strict" variables. (tell liquid to report an error for undefined variables)

This can be nice for people to catch errors during web dev. Particularly convenient when converting templates from other generators (like Jekyll), where variables may be named differently.

**Comment by binyamin** [comment]
@sschuldenzucker can you make a PR?

**Comment by pdehaan** [comment]
LiquidJS is already updated to 9.x in **master** branch:
https://github.com/11ty/eleventy/blob/904234193766aa9d9a7fb1e5037dea8838995a0f/package.json#L106

But is still on the older version in **v0.11.x** branch:
https://github.com/11ty/eleventy/blob/094c9851d98d77fdd6723673c71cff32de9a7f0a/package.json#L109

I don't imagine that 0.11.x will get updated to a newer version of LiquidJS, considering it's probably a very breaking change and there were a lot of plumbing changes needed (see #1058).

I'm not even sure if it's possible to update your existing 0.11 with liquidjs@9 using https://www.11ty.dev/docs/languages/liquid/#optional-set-your-own-library-instance docs. I know the 11ty docs are out of date w/ the new LiquidJS v9 API, but even if you changed that, I'm pretty sure there was something broken last time I tried to monkey patch the latest liquid into 11ty.

**Comment by Ryuno-Ki** [comment]
I think, Zach reported that there will be no Liquid v9 in the 0.11.x branch somewhere.
For the same reason you listed here.

@sschuldenzucker Could you open a new issue to highlight the minor update on master branch?
I feel it could get lost otherwise.

**Comment by sschuldenzucker** [comment]
> I'm not even sure if it's possible to update your existing 0.11 with liquidjs@9 using https://www.11ty.dev/docs/languages/liquid/#optional-set-your-own-library-instance docs. I know the 11ty docs are out of date w/ the new LiquidJS v9 API, but even if you changed that, I'm pretty sure there was something broken last time I tried to monkey patch the latest liquid into 11ty.

NB, I've done this. Using my limited javascript skills, it looks like this:

```js
const liquidJs = require("liquidjs").Liquid
[...]
  let liquid_options = { // my options
    // extname: ".html",
    dynamicPartials: false,
    root: ["_includes"],
    strictFilters: true,
    strictVariables: true,
    lenientIf: true
  };
  eleventyConfig.setLibrary("liquid", new liquidJs(liquid_options))
```
