### ISSUE TITLE
Add --ignore-initial option to CLI

### ISSUE THREAD

**Issue by robdodson** [11ty/eleventy#1336]
**Is your feature request related to a problem? Please describe.**
Apologies if this is already solved and I'm just holding eleventy wrong 😅

Gulp watch has a neat feature called [`ignoreInitial`](https://gulpjs.com/docs/en/api/watch/#options) that lets you tell it to watch some files and only run the task if those files change. I believe this feature actually comes from chokidar.

This is slightly different from `eleventy --watch` which will both run eleventy _and_ watch files for changes.

In my npm script I'd like to be able to do something like this:

```
"dev": "npm-run-all clean gulp eleventy --parallel --race gulp:watch eleventy:watch server",
```

This would run clean, gulp, and eleventy in series, and then in parallel it would start gulp watch, eleventy watch, and my server. Because I've configured gulp to `ignoreInitial` it only runs once. But eleventy will run twice ☹️

**Describe the solution you'd like**
`eleventy --watch --ignore-initial` - this would tell eleventy to watch for changes, but don't actually run yet.

I think eleventy is using chokidar under the hood, and it looks like [it has `ignoreInitial` set to true](https://github.com/11ty/eleventy/blob/d3dfcec1a50f86916213eb321137432109717186/src/Eleventy.js#L629) so I'm not sure why this isn't already working. Maybe my feature request is actually a bug? 🐛

**Describe alternatives you've considered**
Using gulp to watch eleventy.

**Comment by zachleat** [comment]
The Eleventy command line flag for `--ignore-initial` is finally shipping with 2.0.0-canary.25
