### ISSUE TITLE
Compiling to binary or unsupported text encoding

### ISSUE THREAD

**Issue by jamesrbedwell** [11ty/eleventy#1340]
I followed the getting started documentation which resulted in the html not compiling correctly.

https://www.11ty.dev/docs/getting-started/

index.html and readme.md would compile to html.

instead it compiled to binary or unsupported text encoding (according to vscode)

![image](https://user-images.githubusercontent.com/9282146/89113268-0fa59b00-d4b2-11ea-88ee-0150f9b0a456.png)

![image](https://user-images.githubusercontent.com/9282146/89113264-061c3300-d4b2-11ea-8e98-b9b19c042f6f.png)

![image](https://user-images.githubusercontent.com/9282146/89113290-3d8adf80-d4b2-11ea-9e56-9c55ce9f0375.png)

![image](https://user-images.githubusercontent.com/9282146/89113296-44195700-d4b2-11ea-822a-9b8d4f09f617.png)

Windows 10
eleventy v0.11.0

Hope its nothing too bad, or something im doing wrong haha, was looking forward to giving it a good crack today!

**Comment by samuelpath** [comment]
Hi @jamesrbedwell 
Could you tell us your Node version, and send us your generated `_site` folder? (even better if you could send us the whole repo, you can just ignore the `node_modules` folder, since it's almost 100 MB large and would not help the troubleshoot)
Looks like some Windows specific encoding issue.
Regards,
Samuel

**Comment by samuelpath** [comment]
Seems like the same issue as #702.

Could you try what worked for @koutbo6, i.e.:

> I think the problem is related to the character encoding from the tutorial website, specifically step 4 of getting started
>
> If you copy and paste the lines to the command line, it will produce the extra characters seen here, might be some hidden characters related to formatting?. I managed to reproduce this using powershell, git bash, and node.js shell (cmd).
>
> When I deleted README.md and index.html and manually typed them in vscode, everything works fine.

**Comment by jamesrbedwell** [comment]
Hey @samuelpath,
https://github.com/jamesrbedwell/eleventy-sample
Node 12.13.0 with NVM
tried with 12.18.3 and same issue.

Also just came across the problem that if node_modules is in gitignore eleventy doesn't work. Not sure if expected so will have a look through issues 

Was writing all this out then saw your latest post, and it works manually typing

Last of the lazy coders it appears, will not copy and past in future ;)

**Comment by jamesrbedwell** [comment]
@samuelpath thanks for looking into it

**Comment by samuelpath** [comment]
My pleasure @jamesrbedwell, I'm actually doing some triage to get a better grasp on Eleventy's internals, so thanks for giving me this opportunity to practice, while also helping @zachleat trimming the overwhelming number of open issues.

And by the way, being lazy is often a quality for coders 😄

**Comment by divillysausages** [comment]
For anyone having the same issue. Creating the files via command line on Windows (I using the powershell terminal in VSCode) saves the files under UTF-16 LE encoding, which seems to cause the problem. Resaving to UTF8 fixes it

**Comment by zachleat** [comment]
Read more about progress on this issue here: https://github.com/11ty/eleventy/issues/2082#issuecomment-2168828502
