### ISSUE TITLE
HTML output with same folder structure like source folder

### ISSUE THREAD

**Issue by rizqinizamil** [11ty/eleventy#1341]
Hello there, new 11ty user here.
 
I want to build my `src` folder to `dist` folder and it will compile from `.njk` to `.html` in the same structure instead of put in `name-file/index.html`.
So basically it will goes something like `src/login.njk` -> `dist/login.html`. How do I do this in 11ty?

Thank you.

**Comment by nhoizey** [comment]
@rizqinizamil you have to define your own permalink, based on the `filePathStem`.

Here's an example from a folder data file:

```javascript
module.exports = {
  eleventyComputed: {
    permalink: (data) => {
        return data.page.filePathStem + '.html';
    },
  },
};
```

This is what the `permalinkFolders` option set to `false` would give you in [Pack11ty](https://pack11ty.dev/):
https://pack11ty.dev/documentation/collections/#permalinks

**Comment by rizqinizamil** [comment]
Thank you @nhoizey. I just knew that we can set the permalink manually using front matter. I think it easier for me for now. But your permalink config on Pack11ty looks great, will look into it then.
