### ISSUE TITLE
Nunjucks, trimBlocks & lstripBlocks - Much nicer templates

### ISSUE THREAD

**Issue by TigersWay** [11ty/eleventy#1342]
**Is your feature request related to a problem? Please describe.**
Nunjucks templates are not exactly the easiest to read. Even the dash like `{{-` or `-%}` does not really help.

**Describe the solution you'd like**
I'd like `trimBlocks` and `lstripBlocks` to be set true when initiating the internal Nunjucks environment. https://github.com/11ty/eleventy/blob/232cb9b21fed147a1f1660696723fcd5fb060c4d/src/Engines/Nunjucks.js#L21

**Describe alternatives you've considered**
For now, I have to set them somewhere in .eleventy.js
```
  const nunjucks = require("nunjucks");
  let nunjucksEnvironment = new nunjucks.Environment(
    new nunjucks.FileSystemLoader(`site/${theme}/includes`), {trimBlocks: true, lstripBlocks: true}
  );
  eleventyConfig.setLibrary("njk", nunjucksEnvironment);
```

**Additional context**
I haven't been using (yet) any other template engine with 11ty, so I won't say much!

**Comment by edwardhorsford** [comment]
@TigersWay I set the settings in a similar way.

Are you suggesting you think they should be _default_, or that the settings should be exposed like other eleventy settings, eg:

`eleventyConfig.setNunjucksConfig({ foo} );

**Comment by TigersWay** [comment]
@edwardhorsford 
While some Nunjucks users do not really care as they 'compress' their resulting HTML, I discovered these last days that some gave up on Nunjucks because of the 'messy' result.

- So, yes, I believe they should be set true by default.
- I'm not sure it should be considered as a 'breaking change'.

And it was one way to let these last users known they can make it more readable/better!

**Comment by juanmiguelguerrero** [comment]
It would be a good idea set true  `trimBlocks` and `lstripBlocks`

**Comment by zachleat** [comment]
Going to punt this one over to https://github.com/11ty/eleventy/issues/895 which describes a much easier way to change these defaults in your project.
