### ISSUE TITLE
How to add `loading="lazy"` to all images automatically

### ISSUE THREAD

**Issue by AjitZero** [11ty/eleventy#1343]
I have a bunch of markdown files where the images involved are almost always written as: `![title](link)`

This gets converted to: `<img src="link" alt="title">`

I want it to become: `<img src="link" alt="title" loading="lazy">`

Is this possible without modifying each and every markdown image link? This can be solved with shortcodes but that would mean replacing all existing files that I have. This can potentially be extended to adding any attribute and value.

Possible improvement request: Only add `loading="lazy"` to all `<img>`s withing an `<article>`.

Other than shortcodes, [arve0/markdown-it-attrs](https://github.com/arve0/markdown-it-attrs) is also a potential solution, but it involves updating all markdown links to include  `{ loading="lazy" }`

**Comment by pdehaan** [comment]
I haven't tried either, but one of these **markdown-it** plugins might work:

- [**markdown-it-img-lazy**](https://www.npmjs.com/package/markdown-it-img-lazy)
- [**markdown-it-image-lazy-loading**](https://www.npmjs.com/package/markdown-it-image-lazy-loading)

**Comment by nhoizey** [comment]
@AjitZero you can add a [transform](https://www.11ty.dev/docs/config/#transforms) to Eleventy to add this attribute to all images in the HTML.

I currently add this attributes thanks to [my configuration](https://github.com/nhoizey/nicolas-hoizey.com/blob/master/src/_11ty/images-responsiver-config.js#L81-L83) for [elevent-plugin-images-responsiver](https://nhoizey.github.io/eleventy-plugin-images-responsiver/).

**Comment by AjitZero** [comment]
> you can add a [transform](https://www.11ty.dev/docs/config/#transforms) to Eleventy to add this attribute to all images in the HTML.

That's exactly what I needed!

**Simple solution:** (for others looking to do something similar)

```js
eleventyConfig.addTransform("addNativeLazyLoading", (content, outputPath) => {
  if (outputPath && outputPath.endsWith(".html")) {
    content = content.replace(`<img`, `<img loading="lazy"`);
  }
  return content;
});
```

The obvious issue with this is that it will also add `loading="lazy"` within code blocks, which can be solved by writing a regex pattern (will do that later).

Thank you @nhoizey @pdehaan
