### ISSUE TITLE
Debugging large build times for large sites

### ISSUE THREAD

**Issue by alistairtweedie** [11ty/eleventy#1346]
I've been using Eleventy on a project for about 18 months now. As I've grown the project the build times have naturally increased. I'm now writing about **1353 files** but my build times are exceeding **30 mins**.

What's the best way to debug in order for me to optimize?

**Comment by edwardhorsford** [comment]
@alistairtweedie Have you seen the new [performance section](https://www.11ty.dev/docs/debug-performance/)?

The times your seeing seem really long to me - though obviously I don't know what processing you're doing.

For reference, my depending on what I build, it can be up to 1500 pages - and it takes about 20s (fast mbp). 30 minutes feels like something is going wrong.

**Comment by alistairtweedie** [comment]
@edwardhorsford Thanks! I was able to do some more digging using the performance docs you linked me to.  Here's a quick break down of my project structure and what I found out:

I'm pulling JSON data from a third party and using the same method as the [GitHub Stargazer example](https://github.com/11ty/11ty-website/blob/ac3579909078f860f4af1185c8f7353d56833c22/_data/github.js) that can be found in the documentation.

**I have the following data files pulling the data:**
``` 
_data/companies.js
_data/jobs.js
```
**The data returned is then stored in my datacache folder as JSON:**
```
_datacache/companies
_datacache/jobs
```

I'm then using the [Create Pages From Data](https://www.11ty.dev/docs/pages-from-data/#create-pages-from-data) method.

For each of these datasets, I have template files `list.njk` and `item.njk`. The `list.njk` template obviously lists the items in each dataset out and `item.njk` generates `html` pages for each item within each dataset.

**My folder structure looks like this:**
```
companies/
    list.njk
    item.njk
jobs/
    list.njk
    item.njk
```

**An example of the `list.njk` files:**
```
---
title: Companies
pagination:
  data: companies
  size: 100
permalink: companies{% if pagination.pageNumber > 0 %}/{{ pagination.pageNumber + 1}}{% endif %}/index.html
---

{% for item in pagination.items %}
    <h1>{{ item.name }}</h1>
{% endfor %}
 ```

The increase in build time seems to be caused when I try and reference "across" datasets. For example:

> I would like Jobs from GitHub to appear on the GitHub Company page.

 **So inside my `companies/item.njk` template file I might have a loop like this:**

```
---
pagination:
  data: companies
  size: 1
  alias: company
permalink: companies/{{ company.name | slug }}/index.html
---

<h1>{{ company.name | slug }}</h1>

{% for job in jobs%}
    {% if (job.company === company.name) %}
         //job details would go here
    {% endif %}
{% endfor %}
```

I've removed all `for loops` and `if statements` from my templates that "cross-reference" data and my build time has plummeted from 30 minutes to 30 seconds. For reference, I have about 500 companies and 700 jobs.

Is there any way to optimize this or do this another way that I'm not seeing?

Thanks

**Comment by sachac** [comment]
If anyone's still wondering about this, one way might be to make a collection of jobs grouped by company, and then either include the company info in that or look up the appropriate entry in the collection.

**Comment by alistairtweedie** [comment]
I found that due to the large data I was looping over there was a ton of whitespace. Throw in the fact I'm minifying the html on build as well and around 3500 odd pages being output this seemed to cause the problem.

I found that using `-` escapes the whitespace and made my builds much quicker:

```
{%- for job in jobs -%}
    {%- if (job.company === company.name) -%}
         //job details would go here
    {%- endif -%}
{%- endfor -%}
```

**Comment by patricknelson** [comment]
Reading through this, I was just curious @alistairtweedie: How much quicker was it after this change vs. the 30min you originally had?

**Comment by RobHud** [comment]
For me it decreased memory usage from 1.2 Gb for 1k pages to 0.3. I have no idea why it works.
