### ISSUE TITLE
Posible to globaly update permlinks?

### ISSUE THREAD

**Issue by helmutgranda** [11ty/eleventy#1348]
After reading the documentation I can see that I can manually update each one of the files I have, however I would like not to do that for every file but rather do it globally. We are going to run a simple website on an older server and uses default.htm as the end point for subdirectories so I would like to have the following

a.md -> a/default.htm
/folder/b.md -> /folder/b/default.htm

Is that possible to do without having to alter hundreds of MD files?

**Comment by nhoizey** [comment]
You can use [directory data files](https://www.11ty.dev/docs/data-template-dir/) to set a permalink.

**Comment by helmutgranda** [comment]
Thanks for the link, I ended up using my parent template to do this for me since all pages inherited one way or another from the "core" or "default" template.
