### ISSUE TITLE
List of opinionated folders in 11ty

### ISSUE THREAD

**Issue by plug-n-play** [11ty/eleventy#1353]
I understand that 11ty has certain opinionated folders for a no config use case, which can be overwritten by adding configurations.

Is `blog` an opinionated folder?
How can this folder be renamed?
Is this information already available in the official docs?

**Comment by zachleat** [comment]
The “magic” directory names are:

* `_data`: https://www.11ty.dev/docs/config/#directory-for-global-data-files
* `_includes`: https://www.11ty.dev/docs/config/#directory-for-includes
* `_site`: https://www.11ty.dev/docs/config/#output-directory

You can change all of these via configuration.
