### ISSUE TITLE
Optionally scope frontmatter under key 'page' in data

### ISSUE THREAD

**Issue by adamkiss** [11ty/eleventy#1360]
**Is your feature request related to a problem? Please describe.**
Everytime I come back to Eleventy after a while doing other things, I get surprised by the fact that while data files and collection items are scoped (i.e. `data.[dataFilename]` and `data.item`), page frontmatter is just in the root, e.g. `data.title`.

**Describe the solution you'd like**
I'd like to have (PR even?) a config option like `scopeFrontmatter` that would put the frontmatter data under the `data.page` scope/key, so you'd use it in layouts/templates like `page.title` or `data.page.title`

**Describe alternatives you've considered**
Take better notes or don't be stupid. Not working out yet.

Thank you.

**Comment by edwardhorsford** [comment]
[Related issue.](https://github.com/11ty/eleventy/issues/338)

**Comment by b3u** [comment]
@adamkiss Thanks for pointing this out. Like @edwardhorsford mentioned, this has been requested before.

Keep in mind that we use [lodash-style issue management](https://twitter.com/samselikoff/status/991395669016436736) here, so enhancements will be be marked as closed. You can vote on #338 with a :+1:, and/or add your thoughts to the discussion.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please visit the eleventy community on discord.

**Comment by edwardhorsford** [comment]
Also - to be a bit clearer - I think there's definite improvements that could be made - there's inconsistency with the various variables, and I often struggle to remember what level I can find something.

**Comment by adamkiss** [comment]
Ah, right. Closing in favor of #338 then

**Comment by adamkiss** [comment]
🙄
