### ISSUE TITLE
addExtension produces filenames that include content

### ISSUE THREAD

**Issue by MadeByMike** [11ty/eleventy#1365]
**Describe the bug**
When adding a custom template format with `addTemplateFormats` and `addExtension` the result of the compile is added to the filename whenever a `permalink` property exists in front-matter:

**To Reproduce**

1. Checkout this branch: https://github.com/MadeByMike/11ty-template-bug
2. npm\yarn install
3. npm run start

Important things to note:

 - Steps used to add custom template format are:
```
  eleventyConfig.addTemplateFormats("new");
  eleventyConfig.addExtension("new", {
    compile: () => () => "Test content - this gets included in the filename",
  });
```
  - Only seeing this bug where there is `permalink` value in the filename

**Expected behavior**
The filename for the page is derived from the permalink - not content.

**Environment:**

- OS and Version: Win and Mac node 12
- Eleventy Version 0.11.0

**Comment by MadeByMike** [comment]
I have test to reproduce here: https://github.com/MadeByMike/eleventy/tree/fix-custom-engine-perma

**Comment by MadeByMike** [comment]
Resolved the cause - The mdx template and this example here ignore the input string and return content from the file-system (or a fixed string in this case) when the dynamic permalink setting is true. Because of the dynamic import MDX needs to resolve from the inputPath and not the string extracted by 11ty.

**Comment by MadeByMike** [comment]
Best work-around for my needs that I can think of is to check if the string matches the file. I understand that we probably don't want to add additional context to these `.compile` functions as they follow the pattern of other template engines... maybe mdx's webpack requirements are special. I do wish I could avoid them entirely.

**Comment by oliverjam** [comment]
Sounds like this is the same issue? https://github.com/11ty/eleventy-plugin-vue/issues/6

**Comment by MadeByMike** [comment]
Closing as duplicate of #1365

**Comment by binyamin** [comment]
@MadeByMike this is #1365!

**Comment by zachleat** [comment]
Reopening this until we know what’s going on 😅

**Comment by zachleat** [comment]
I’m working on the docs for this right now but in canary 48 you can opt out of permalink compilation altogether like this:

```
config.addExtension('css', {
  compileOptions: {
    permalink: false
  }
}
```

or in canary 49 you’ll be able to override it with your own thing:

```
config.addExtension('css', {
  compileOptions: {
    permalink: async function(permalinkString, inputPath) {
       return async function(data) {
          // do your own custom thing
       };
    }
  }
}
```

**Comment by zachleat** [comment]
If you’d like to override permalink compilation or opt-out of it entirely, use `compileOptions.permalink`, docs are now available here: https://www.11ty.dev/docs/languages/custom/#compileoptions

**Comment by Holben888** [comment]
Glad I found this! Helped us [resolve an issue](https://github.com/slinkity/slinkity/issues/148) with permalinks in JSX components 👍
