### ISSUE TITLE
How do I access front matter data of the current page?

### ISSUE THREAD

**Issue by proog** [11ty/eleventy#1370]
I'm migrating a Jekyll site to Eleventy using Liquid templates.

In Jekyll, it's possible to access the current page's front matter data in a layout simply by using the `page` variable. For instance, I can print the page title using `{{ page.title }}`. I understand that in Eleventy front matter is stored under `data`, but `{{ page.data.title }}` gives me nothing, and indeed the entire `data` key seems to be missing.

What's the intended way to access front matter data of the current page (in a layout)?

**Comment by teknetia** [comment]
I'm not sure how much the template engine impacts this, but in liquid I just use `{{ title }}` to get the `title:` item from the front matter. I only use the `.data.` method when working with data from collections.

**Comment by proog** [comment]
Ah, you're right. Thank you!

It is in my opinion somewhat unintuitive that `page` doesn't have the same structure as when reading it from a collection. Adding to the confusion is that both "collection" and "current" forms of the page contain some of the properties I would expect, like `date` and `url`, with the former also defined in the front matter.

I'm closing this as my question was answered.

**Comment by bhideghety-SPC** [comment]
@zachleat 
1. ### **missing page.data** on the frontmatter (post) - will this be addressed?
2. page.data.tags neither page.tags is avail. on the fontmatter
3. varialbes as titlt | tags - **variable pollution**

---
detailed desc.:

there seems to be a **mess** with page object when used in template. it's ok that in collection we have to use item.page but unfortunately **the item.page is not the same as the page object on the given page template.**

so when using custom filter, we might got in trouble if i use:
page | myFilter 
whereas collections['my_coll'][0].page | myFilter would work as intended (as this object does have data property filled)

on the template, we don't have: {{ page.data.tags }}, neither {{ page.tags }} but we do have {{ tags }}. these direct shortcuts probably do hurt also (code / **variable pollution**, that JavaScript tries to solve with IIFE, modules, ...)

---
comparison:

comparing 11ty to other frameworks, when considering the object model, **this shortcoming and inconsistency** is one of the 1st things that really does bother me. haven't found such exception in jekyll, nor hugo, nor hexo (althoug last one I javent checked deeply).
