### ISSUE TITLE
Can Eleventy do conditional pubishing?

### ISSUE THREAD

**Issue by zomars** [11ty/eleventy#1378]
Hear me out. Sometimes I'm have some WIP markdown files that are not quite ready to publish (this would be the default for me).

Wouldn't it be cool to be able to have a markdown file and the when it's ready to publish simply adding something like this into the frontmatter data and use that condition to build the template?

Example:

```md
---
published:  true
---
```

or maybe the desired published date:

```md
---
publishedAt:  2020-08-25
---
```

Or something like that.

Is it possible? Sorry if this is a duplicate, I couldn't find anything in here.

**Comment by DenizAksimsek** [comment]
The following will prevent a file from being published:

```yaml
---
permalink: no
eleventyExcludeFromCollections: yes
---
```

**Comment by zachleat** [comment]
I think this is the same as #188, please follow along over there!

**Comment by zachleat** [comment]
Specifically this comment might be of value to you https://github.com/11ty/eleventy/issues/188#issuecomment-1156986504
