### ISSUE TITLE
Why are there separate async methods for shortcodes, filters?

### ISSUE THREAD

**Issue by luwes** [11ty/eleventy#1382]
Just wondering if there is a reason this has to be explicit? e.g. `addNunjucksAsyncFilter()`

Wouldn't it be possible to derive this from the `async` keyword that is defined before the callback?
Seems a nicer devex, less API's.

For example `addNunjucksFilter('myFilter', async () => {})`

See here for detecting an async function, a lot of test runners use this technique; AVA, Tape, etc
https://stackoverflow.com/a/38510353/268820

**Comment by DenizAksimsek** [comment]
One reason I can think of: not all async functions are `async` functions, one could also implement asynchrony with just `new Promise()` and `.then()`.

Secondly, the SO link you included mentions that some transpilers might transform async functions to normal ones. I'm not sure how many people transpile their `.eleventy.js` but I'm sure there are some.

**Comment by zachleat** [comment]
Took your suggestion!

Read more here: https://www.11ty.dev/docs/filters/#asynchronous-universal-filters
