### ISSUE TITLE
Set 'date' variable from filename

### ISSUE THREAD

**Issue by sdegutis** [11ty/eleventy#1383]
In the dynamic `permalink` I'd like to use `{{date}]` even though it's set in the filename.

[This doc page](https://www.11ty.dev/docs/dates/) says that it's implied to be from the filename. But when I access it in the dynamic permalink, it's absent. Which means it's probably being used internally to eleventy but not accessible to me.

Does it make sense to add this variable into the context that permalink receives? Like, if it's absent, but present in the filename, then set it, so that the permalink can access it?

Thanks for your time.

**Comment by binyamin** [comment]
@sdegutis `{{page.date | date: "%Y-%m-%d"}}` should work.

**Comment by sdegutis** [comment]
I don't think that works inside the dynamic permalink. Either way, I no longer use 11ty so I can't test it. Feel free to close this issue as needed.
