### ISSUE TITLE
How do I create a JSON file of all categories used anywhere in any collection?

### ISSUE THREAD

**Issue by hirusi** [11ty/eleventy#1384]
Given front-matter such as the following in various markdown files:

```
tags: ["foo", "bar"]
```

and

```
category:
- hello
- world
- foo
```

...I want to create a new JSON file that would contain:

```
[
  "foo",
  "bar",
  "hello",
  "world"
]
```

Is this something I can do with Eleventy? If so, any ideas how? If not, how would I approach this? Are there any YAML front-matter parsing libs that would let me do this, perhaps, as a gulp task?

Please note that the format for specifying them could be a list, or an array. The key could be `category` or `tags`.

**Comment by paulrobertlloyd** [comment]
👋 Here’s how I’m doing it. I generate the following JSON file:

```yaml
---
permalink: categories/index.json
---
[{% for category in collections.category %}"{{ category }}"{% unless forloop.last %},{% endunless %}{% endfor %}]
```

This loops through `collections.category`, which is created thus:

```js
function sortByFrequency(array) {
  const frequency = {};

  array.forEach(value => {
    frequency[value] = 0;
  });

  const uniques = array.filter(value => {
    return ++frequency[value] === 1;
  });

  return uniques.sort((a, b) => {
    return frequency[b] - frequency[a];
  });
}

module.exports = collection => {
  const categoryArray = [];
  collection.getAll().forEach(item => {
    if ('category' in item.data) {
      const categories = item.data.category;
      for (const category of categories) {
        categoryArray.push(category);
      }
    }
  });

  return sortByFrequency(categoryArray);
};
```

**Comment by hirusi** [comment]
I internally still use `tags` for categories to rely on Eleventy to do the heavy lifting, made them uniform throughout the site (letting `category` go in favor of `tags`), and this worked a treat with very minor modifications.
