### ISSUE TITLE
How do I set Eleventy to output a working local static site?

### ISSUE THREAD

**Issue by starcorelabs** [11ty/eleventy#1385]
My goal is to open the _site / index.html in Chrome and see my working static site.
Currently Eleventy outputs a version where all of the CSS, JS, and image paths start with "/". 
This leaves the site without styles or images when running without the Eleventy local development server. 

I have experimented with pathPrefix in my config but so far nothing removes the "/". 
Any suggestions on how to fix this?

**Comment by binyamin** [comment]
@starcorelabs Do you mind creating an example repo? For me, the paths are exactly as I wrote them. I wrote them as `./css/style.css`.

**Comment by starcorelabs** [comment]
@binyamin Here's a link to my 11ty repo https://github.com/starcorelabs/11-site
My goal is to have 11ty output a static site that I can then manually upload to https://github.com/starcorelabs/starcorelabs.github.io

To make the pages display correctly before adding them to my github pages. 
I had to manually fix the folder structure and go through all my pages, posts, and projects fixing the link paths. 
They all started as /assets/css/style.css
But within the 11ty default folder structure they needed to be 
either assets/css/style.css or ../assets/css/style.css or ../../assets/css/style.css

I would like a way to control how 11ty outputs the static files so I can use my preferred folder structure.
As well as make sure all my relative paths work.
![preferred structure](https://user-images.githubusercontent.com/2847006/92332127-50f90f80-f049-11ea-99ad-5298f4d72438.png)

**Comment by binyamin** [comment]
To my knowledge, 11ty does not process the urls you provide. In other words, even if you just had a folder with an html and a css file, writing `/style.css` would not work. FYI, `/style.css` means "go to the root of the website or file system" (ie. `C:\style.css` or whatever).

**Comment by starcorelabs** [comment]
I'm not sure what you mean by 11ty not processing URL's. 

I followed the this [YouTube tutorial](https://www.youtube.com/watch?v=z-o1W9ijUhI&list=PLOSLUtJ_J3rrJ1R1qEf8CCEpV3GgbJGNr&index=1) to learn 11ty and convert my static template to work with 11ty.

That tutorial said 11ty required all paths to start with "/" for the local dev server to work.
I've tried removing them in my source code but then the dev version doesn't render the pages properly.

What I'm seeing is when I run npx @11ty/eleventy -- serve the site works locally.
The _site folder outputs a static site and all the links look like this:

![11-source-menu](https://user-images.githubusercontent.com/2847006/92332398-e6959e80-f04b-11ea-8276-622e5f711590.png)

In order for those menu items to work correct on GitHub Pages they need to convert to relative links based on their position in the folder structure.

That same menu needs to look like this:

![working-menu](https://user-images.githubusercontent.com/2847006/92332422-0af17b00-f04c-11ea-95fd-49e47a972d6c.png)

My issue is that I cannot find anything in the documentation that suggests how to change the build process so 11ty will output static files that work when opened locally in Chrome. Without running the dev server.

I'd also like a way to tell 11ty to structure the output in the _site folder to match my preferred structure.
Since this is all just JavaScript I'm sure there is a way to do it.

**Comment by binyamin** [comment]
> ...output static files that work when opened locally in Chrome. Without running the dev server.

I just looked at the GitHub repo you uploaded. Honestly, I think your best bet is to use some sort of server when viewing the files locally. I almost always use a vs code extension called [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) for viewing html files.

> I'd also like a way to tell 11ty to structure the output in the _site folder to match my preferred structure.

I don't know what your preferred structure is, but try setting the permalink in the front-matter of the relevant files.

If you still have questions, you may want to try the Eleventy community [on discord](https://discord.gg/GBkBy9u). You can ping me (`@b3u`) when you're there.

**Comment by pdehaan** [comment]
I'd say +1 to running the local dev server to preview locally. Trying to debug stuff from a file system can be full of odd issues.

If you really want to try debugging via file:// you might be able to do it with a custom filter, but I'm not sure if you can do that globally (kind of doubt it) or if you'd need to reference the custom filter each time you wanted to have some conditional path prefix of `/` vs `./`.

```js
module.exports = (eleventyConfig) => {
  eleventyConfig.addPassthroughCopy("assets/**");

  eleventyConfig.addFilter("pathPrefix", (p) => process.env.NODE_ENV === "local" ? `.${p}` : p);

  return {
    dir: {
      input: "src",
      output: "www"
    }
  };
};
```

Where my test file was:

```md
![Logo]({{ '/assets/logo.png' | pathPrefix }})
```

And my output when running <kbd>eleventy</kbd> for remote was:
```html
<p><img src="/assets/logo.png" alt="Logo"></p>
```

And my output when running <kbd>NODE_ENV=local eleventy</kbd> for local was:

```html
<p><img src="./assets/logo.png" alt="Logo"></p>
```

So while it might be technically possible, I wouldn't recommend it.

**Comment by starcorelabs** [comment]
Allow me to clear up the confusion. 
Deploying to GitHub Pages is the problem. 
I uploaded a short video to my YouTube channel demonstrating the issue.

[11ty Routing Issues](https://youtu.be/VruPZ2_0GQc)

**Comment by pdehaan** [comment]
Not sure what's going on. I did a clone, local build, went into my local _site/ directory, did <kbd>git init</kbd>, set my upstream to my unused pdehaan.github.io repo and pushed your _site/ contents and it looks like it's working for me: https://pdehaan.github.io/#about

**Comment by starcorelabs** [comment]
@pdehaan Wow, that's amazing! I'm blown away that its working. I didn't even try to push it because it wasn't working locally.
Thanks for testing it for me.

**Comment by pdehaan** [comment]
Well, I don’t have a CNAME file or custom domain, but yeah, worked for me. 11ty definitely doesn’t need a fancy JavaScript server to serve static files.
And this is why I wouldn’t test locally with file:// directly (because it rarely works in my experience).

**Comment by starcorelabs** [comment]
@pdehaan I was under the impression that if it didn't work locally it wouldn't work on GitHub Pages. Sometimes its good to be wrong. I love learning new things. Thanks again!

**Comment by starcorelabs** [comment]
Thank you everyone for helping me figure out this issue. 

@pdehaan I pushed the contents of _site to my GitHub Pages repository and its working: http://starcorelabs.com/
So you don't have to keep my site up on your github pages if you don't want to. Or, keep the theme and and use it for your own purposes.
