### ISSUE TITLE
core.js postinstall

### ISSUE THREAD

**Issue by kanchanpriya17** [11ty/eleventy#1388]
i want to just create a simple create-react-app since two day its always shows this error:

> core-js@2.6.11 postinstall C:\Users\hp\Desktop\New folder\firstproject\node_modules\babel-runtime\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@3.6.5 postinstall C:\Users\hp\Desktop\New folder\firstproject\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js-pure@3.6.5 postinstall C:\Users\hp\Desktop\New folder\firstproject\node_modules\core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

+ cra-template@1.0.3
+ react-scripts@3.4.3
+ react-dom@16.13.1
+ react@16.13.1
added 1587 packages from 745 contributors and audited 1591 packages in 140.78s

67 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

i tried to install,uninstall globally create-react-app ,install react-scripts but same error

**Comment by zachleat** [comment]
Hm? I’m confused what you’re asking here—we aren’t associated with create-react-app or react-scripts

**Comment by kanchanpriya17** [comment]
i run npx create-react-app my-app but it didn't work always show postinstall like above and it didn't run npm start

**Comment by brycewray** [comment]
@kanchanpriya17 As @zachleat (the creator of Eleventy) explained, this repository has **nothing** to do with create-react-app. Suggest you try https://github.com/facebook/create-react-app/issues instead.

**Comment by kanchanpriya17** [comment]
ok thank you @brycewray
