### ISSUE TITLE
If you specify a config file and it's . eleventy.js, it runs twice

### ISSUE THREAD

**Issue by melissamcewen** [11ty/eleventy#1389]
**Describe the bug**
I was working with a site that had `npx @11ty/eleventy --config .eleventy.js --serve` as the watch command and I noticed when I added a collection with `eleventyConfig.addCollection` it gave me the error `config.addCollection(docs) already exists. Try a different name for your collection.` Looking at the debug logs I noticed `Eleventy:TemplateConfig Merging config with /Users/me/Sites/snowpack/docs/.eleventy.js +99ms` so I suspected it was running twice. Removing the `--config` solved the problem.

**To Reproduce**

1. Create a new Collection with [`addCollection`](https://www.11ty.dev/docs/collections/) in `.eleventy.js`
2. Run Eleventy with the `--config .eleventy.js` flag

**Expected behavior**
I expected it to use `.eleventy.js` as the only config file

**Environment:**

- Mac Catalina
- Eleventy Version 0.11.0

**Additional context**

**Comment by binyamin** [comment]
Thanks for raising this issue. Yeah, I can confirm that this happens. For now, you can just omit `--config .eleventy.js`.
(By the way, there's a typo in the title of the issue).

**Comment by zachleat** [comment]
I fixed this with https://github.com/11ty/eleventy/pull/1629
