### ISSUE TITLE
PassthroughCopy only passes through allowed template formats when both options are used

### ISSUE THREAD

**Issue by clottman** [11ty/eleventy#1395]
**Describe the bug**
If your project config includes both `setTemplateFormats` and `addPassthroughCopy`, only files in the passthrough folder that use the extensions allowed by `setTemplateFormats` will be passed through.

**To Reproduce**

See <a href="https://glitch.com/edit/#!/rapid-ethereal-silicon">complete code for this repro on Glitch</a>.

The Eleventy config includes these two lines:

```javascript
  eleventyConfig.setTemplateFormats(["html", "njk", "css"]);
  eleventyConfig.addPassthroughCopy("lib");
 ```

The src/ directory includes a lib/ directory with two files, one that's .css and one that is .js. Only the .css is passed through to the output directory on build. 

If you add "js" to the setTemplateFormats array, both files will be passed through.

**Expected behavior**
The docs imply that if you have added a passthrough copy folder, all files inside will be passed through regardless of the file extension.

**Environment:**

- OS and Version: Mac, reproducible on Glitch and during local development
- Eleventy Version: 0.11.0

**Comment by clottman** [comment]
Ok so this is not a bug at all, sorry! Glancing back at the docs, I see: 

> Passthrough File Copy entries are relative to the root of your project and not your Eleventy input directory.

But my lib file was in src/lib, not at the root of my project. So no files were actually getting picked up by the passthrough option, but the .css file was picked up by setTemplateFormats.

**Comment by binyamin** [comment]
@clottman I'm glad you found the answer. Thanks for closing the issue, and adding the solution for others.
