### ISSUE TITLE
`ms each` console output math might be wrong?

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#1399]
```
Copied 24 files / Wrote 66912 files in 332.96 seconds (5.0ms each, v0.11.0)
```

https://github.com/11ty/eleventy/issues/695#issuecomment-688358317

**Comment by binyamin** [comment]
It's not the math. 332.96 seconds ÷ 66912 files = 4.977 ms per file.
Probably, multiple files are being written simultaneously.

**Comment by zachleat** [comment]
haha yeah I’m not sure what I was thinking before 😅

**Comment by binyamin** [comment]
I don't have the slightest idea of computing speeds, but 5.0ms per file doesn't make sense to me. Are the files being written asynchronously? We might have the wrong equation.

**Comment by zachleat** [comment]
I’m not sure what the confusion is here, mine or yours 😅

**Comment by binyamin** [comment]
Basically, is it possible to write a file in under 5ms?

**Comment by zachleat** [comment]
yeah, absolutely. This is just one example project. It really depends on what features you’re using.
