### ISSUE TITLE
Self reference in base.njk has wrong location

### ISSUE THREAD

**Issue by nilsmielke** [11ty/eleventy#140]
I just deployed 11ty using netlify yesterday.  
In the frontend of the sample installation it says "3. Delete this message from _includes/base.njk."  
`base.njk` is located in `_includes/layouts/`, though.
![bildschirmfoto 2018-06-13 um 08 11 02](https://user-images.githubusercontent.com/8496033/41333444-1ed53bea-6ee2-11e8-9475-446584349f0e.png)

**Comment by DirtyF** [comment]
@nilsmielke Care to submit a PR? Source file is in the base blog repo:
https://github.com/11ty/eleventy-base-blog/blob/master/_includes/layouts/base.njk#L26

**Comment by nilsmielke** [comment]
@DirtyF I'm not a very experienced GitHubber. Tried and seem to have don't the right things. Thanks for the encouragement. :)

**Comment by zachleat** [comment]
Beautiful, thanks all!

**Comment by zachleat** [comment]
Closed by https://github.com/11ty/eleventy-base-blog/pull/10
