### ISSUE TITLE
set ignored files in eleventyConfig

### ISSUE THREAD

**Issue by binyamin** [11ty/eleventy#1405]
**Is your feature request related to a problem? Please describe.**
- Users are unable to ignore files based on the current environment. (CC @scottishstoater)
- I'd rather not have a dedicated file for ignoring a single file

**Describe the solution you'd like**
EleventyConfig return object should accept an array of file globs to ignore.

```js
// Example - .eleventy.js
module.exports = function (eleventyConfig) {
    return {
        dir: {
            input: "src"
        },
        ignoredFiles: [
            "readme.md",
            "_drafts/"
        ]
    }
}
```

**Describe alternatives you've considered**
#1403 solves the first problem.

**Comment by binyamin** [comment]
> This repository uses [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with :+1:!

**Comment by binyamin** [comment]
see #894

**Comment by zachleat** [comment]
Shipping with 1.0. Docs will show up at https://www.11ty.dev/docs/ignores/ in a bit

**Comment by scottishstoater** [comment]
Cheers @zachleat
