### ISSUE TITLE
List all incoming and outgoing links

### ISSUE THREAD

**Issue by StarfallProjects** [11ty/eleventy#1407]
Wondering if anyone has already solved this - couldn't find anything when googling or browsing plugins.

I have a very simple site, with a bunch of "notes" in it (similar to blog posts)

On each note, I want to be able to list:

1. All notes that the current note links to (obviously this can also be seen by reading the note, but I want to provide a list of outgoing links as well) There will be links to external sites as well as to other notes, but I need to list just the links to other notes.
2. All notes that link to the current note.

And somewhere on the site I want a visual representation of all the interlinking between notes. Ideally this should be clickable, so usable for browsing. Visually I want something like this, but able to be embedded in the generated site: https://marketplace.visualstudio.com/items?itemName=tchayen.markdown-links (this extension currently isn't working for my 11ty site - possibly because it chokes if there's anything other than .md files - so I can't use it, it's just an example)

I feel like possibly I need a script that generates a JSON representation of the links, which is then accessed during build? I can't think of any other way to get incoming links. But am hoping someone might already have an elegant solution.

Any suggestions/solutions greatly appreciated!

**Comment by binyamin** [comment]
Are you looking display backlinks?

**Comment by StarfallProjects** [comment]
Possibly! I thought "backlinks" was what they were called, but when I googled that I got a ton of SEO-related articles.

**Comment by binyamin** [comment]
Shameless plug: I built an 11ty template site ([eleventy-garden](https://github.com/binyamin/eleventy-garden)) which includes backlinks. Demo: https://eleventy-garden.netlify.app/notes/

**Comment by StarfallProjects** [comment]
It does, thankyou - I think we're building the same type of thing :-)

**Comment by StarfallProjects** [comment]
So if I'm understanding your project correctly, this is where you are finding the backlinks? https://github.com/binyamin/eleventy-garden/blob/master/notes/notes.11tydata.js

Am hitting my JS noobishness - I don't see how it finds files linking TO the current file, it seems to just search the file for links out? But clearly it works. If you have time to talk me through it, that would be really helpful.

**Comment by StarfallProjects** [comment]
So in case anyone else comes across this, @binyamin probably has the most elegant solution. However, I've gone another route, which also seems to work, and fits my use case slightly better:

1. A PowerShell script that creates a JSON of all the notes and links in the `src/notes` directory, and saves this JSON in the `_data` directory [TODO: translate into Bash if/when I open source the project)
2. A couple of bits of Nunjucks to get links (am very open to feedback on ways to improve these - they can't be the nicest way) `linkMap` is the JSON.

```
<h2>Links to . . . </h2>
  {% set pageName = page.fileSlug %}
  {% for link in linkMap[pageName] %}
    {% for note in collections.notes %}
      {% if note.filePathStem == link %}
      <a href="{{ link }}">{{ note.data.title }}</a>
      {% endif %}
    {% endfor %}    
  {% endfor %}

  <h2>Linked from . . . </h2>
  {% set pageUrl = page.filePathStem %}
  {% for page, links in linkMap %}
    {% if pageUrl in links %}
      {% for note in collections.notes %}
        {% if note.fileSlug == page %}
          <a href="{{ pageUrl }}">{{ note.data.title }}</a>
        {% endif %}
      {% endfor %}
    {% endif %}
  {% endfor %}
```
3. [TODO] Feed the JSON to some graph generator (probably D3) to create the graphic representation of the link interactions.

Given I need the JSON anyway for (3), it seemed to make sense to use it throughout. It also allowed me to incorporate a link checker to flag broken links.

**Comment by binyamin** [comment]
@StarfallProjects If you feel like your question has been answered, would you mind closing this issue?

**Comment by binyamin** [comment]
By the way, yesterday I refractored/updated the backlinks code in eleventy-garden to make it more readable.
