### ISSUE TITLE
LiquidLib is not a function (only when building on Netlify)

### ISSUE THREAD

**Issue by paulrobertlloyd** [11ty/eleventy#1408]
**Describe the bug**

This is a bit weird. Since [removing my own Liquid instance](https://github.com/paulrobertlloyd/paulrobertlloyd-v4/commit/df5df4b83d1e9ad724e2b09fdab2f3d6b1063536) and deferring back to 11ty’s (now that it’s been updated), builds on Netlify fail with the following error:

```sh
11:24:27 PM: Problem writing Eleventy templates: (more in DEBUG output)
11:24:27 PM: > LiquidLib is not a function
11:24:27 PM: `TypeError` was thrown:
11:24:27 PM:     TypeError: LiquidLib is not a function
11:24:27 PM:         at Liquid.setLibrary (/opt/build/repo/node_modules/@11ty/eleventy/src/Engines/Liquid.js:30:29)
11:24:27 PM:         at new Liquid (/opt/build/repo/node_modules/@11ty/eleventy/src/Engines/Liquid.js:13:10)
11:24:27 PM:         at TemplateEngineManager.getEngine (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateEngineManager.js:67:20)
11:24:27 PM:         at TemplateRender.init (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateRender.js:58:52)
11:24:27 PM:         at TemplateRender.get engine [as engine] (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateRender.js:80:12)
11:24:27 PM:         at Template.get engine [as engine] (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateContent.js:59:32)
11:24:27 PM:         at Template.getInputContent (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateContent.js:133:15)
11:24:27 PM:         at Template.read (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateContent.js:80:36)
11:24:27 PM:         at Template.getFrontMatterData (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateContent.js:167:18)
11:24:27 PM:         at Template.getData (/opt/build/repo/node_modules/@11ty/eleventy/src/Template.js:235:40)
```

I am not getting this error on my local machine however.

**To Reproduce**

This is the relevant portion of my 11ty config file:

```js
eleventy.setLiquidOptions({
  cache: true,
  dynamicPartials: true,
  globals: {
    app: require('./src/data/app'),
    dates: require('./src/data/dates'),
    navigation: require('./src/data/navigation'),
    places: require('./src/data/places')(),
    srcsets: require('./src/data/srcsets')
  }
});
```

**Environment:**

- OS and Version: Netlify
- Eleventy Version: 1.0.0-beta.0 (pulling from `master` branch) 

**Additional context**

[Commit where I reverted back to using 11ty’s internal version of Liquid](https://github.com/paulrobertlloyd/paulrobertlloyd-v4/commit/df5df4b83d1e9ad724e2b09fdab2f3d6b1063536).

**Comment by paulrobertlloyd** [comment]
Narrowed this down. Am locally running Node v14, Netlify was on v12. By ensuring Netlify uses Node.js v14, this issue goes away. So this is an issue for Node v12.

**Comment by zachleat** [comment]
I wonder if this has to do with Netlify’s package caching, especially when you’re pulling from master. I’d guess this started to fail when we merged the latest liquid.js version. Perhaps swapping Node versions invalidated the package cache, causing new versions to download.

It would show up in your Netlify build logs if new packages were downloaded, I think.

**Comment by zachleat** [comment]
Is this still a problem on the newest canaries?

**Comment by paulrobertlloyd** [comment]
Since I upgraded both environments to Node v14, the issue disappeared. Would you like me to test this again on Node v12?

**Comment by zachleat** [comment]
Naw, don’t worry about it @paulrobertlloyd! I’ll keep an eye out in case someone else reports—thank you!

Going to close this for now
