### ISSUE TITLE
Pass object data to onclick function in Liquid template

### ISSUE THREAD

**Issue by camphan12993** [11ty/eleventy#1410]
Hi everyone! From this code below, I want to pass the **item** which is an **object** to onclick function so that I can use in external Js file
However, it only work with string or number data type. Shouls I try other syntax in this case? Thanks
```
      {% for item in portfolios %}
        <a class="cursor-pointer portfolio block relative overflow-hidden w-full mb-6 md:w-1/2 md:mb-0" onclick="toggleGallery('{{ item }}')">
          <div class="captain absolute w-full h-full text-white p-4 flex flex-col justify-center items-center z-10 bg-blue-600">
            <h3>{{ item.name }}</h3>
            {{item.imgs}}
            <p class="mb-0">
              {{ item.description }}
            </p>
          </div>
          <div class="relative pb-2/3">
            <img class="absolute w-full h-full object-cover object-center" src="{{ item.thumnail }}" alt=""/>
          </div>
        </a>
      {% endfor %}

```

**Comment by gobeli** [comment]
You'll have to stringify the `item`. What is probably being sent to your js function is `[object Object]`, because the template tries to convert the object to a string. 

What you could do is create a json filter and use it in your template. (see https://www.11ty.dev/docs/filters/). And then parse the json in your js function.

**Comment by camphan12993** [comment]
I've created `toJson` filter
```
	config.addLiquidFilter("toJson", function (value) {
		console.log(value);
		return JSON.stringify(value);
	});
```
and then tried to use it by this way
```
onclick="toggleGallery('{{ item | toJson }}')"
```
however, it had some problems with the quotes
![error](https://user-images.githubusercontent.com/40196295/93775540-bb669e00-fc4c-11ea-944f-c98392acf2b8.PNG)

**Comment by edwardhorsford** [comment]
@camphan12993 I think you've got an issue with your single and double quotes. Your `JSON.stringify` returns with double quotes, but you're already using them for your outer string. 

Maybe have a try with `onclick='toggleGallery({{ item | toJson }})'`

**Comment by camphan12993** [comment]
@edwardhorsford great! I've updated my liquid format config to single quote and it worked well! thanks so much!
