### ISSUE TITLE
Question about eleventyComputed usage

### ISSUE THREAD

**Issue by babouinette** [11ty/eleventy#1413]
Hello everyone,

I have a `_data/products.js` file where I query my products, and an `index.liquid` file in my `/products` folder:

```
---
layout: products.liquid
eleventyComputed:
    productsComputed : "{{products}}"
---
```

I would expect `products` and `productsComputed `to be the same thing.

In my `_includes/products.liquid` file, if I do:

```
`{{products}}
 {{productsComputed}}

 {% if products != productsComputed %}
     Not the same
  {% endif %}`
```

What is printed by the first two lines seem to be exactly the same. 
But the "if" outputs : "Not the same"

If I use : 
```
{% for product in products %} 
     {{product.name}}
{% endfor %}
```
It works fine, but if I try:
```
{% for product in productsComputed %} 
     {{product.name}}
{% endfor %}
```
It doesn't output anything.

In the end, I would like to do something like : 
```
layout: products.liquid
eleventyComputed:
    products : "{{stickers}}"
```
to replace the products given to `products.liquid` by only a category of products.

I probably don't understand something.

Does someone know why it doesn't work? Why are "products" and "productsComputed" not the same? 

Thank you for your help.

**Comment by binyamin** [comment]
Do you have a repository I could test this with?

**Comment by babouinette** [comment]
> Do you have a repository I could test this with?

I made this small repo to show the issue I have.
[https://github.com/babouinette/11ty-test](url)

Thank you for taking a look :)

**Comment by binyamin** [comment]
So, I realized that `productsComputed: "{{ products }}"` returns a string version of the array. You can change the front-matter to JS, in order to output actual JSON.
```liquid
---js
module.exports = {
    eleventyComputed: {
        productsComputed : function(data) {
            return data.products
        }
    }
}
---
<!-- ... page content -->
```

Maybe it should convert to JSON by default. What do you think?

**Comment by babouinette** [comment]
Hello. 

Thanks for your answer. I got it working by using a directory data file in each folder with: 

`module.exports = {
    eleventyComputed: {
        productsComputed : function(data) {
            return data.productsINeededToReturn
        }
    }
}`

with productsINeededToReturn being a global data file in _data directory.

And using a `{% for product in productsComputed%} `in the `products.liquid `template.

With your help, and reading again the documentation, it was written before my eyes but the first time I didn't understand the **Template string** bit.

From my point of view, and the utility I need and used before, I would say that it could be quite handy to do something like this directly in yaml front matter:

`eleventyComputed:
    productsComputed : "{{stickers}}"`

and it would give us back the stickers data directly instead of the string representation. But I'm sure i'm not seeing the whole picture.

But I don't know if it would really be better, maybe simpler?

But whatever, Thanks a lot now it works :)

**Comment by binyamin** [comment]
Great! I'm closing this issue now, since it's solved.
