### ISSUE TITLE
Add support for the Eta template engine

### ISSUE THREAD

**Issue by nebrelbug** [11ty/eleventy#1416]
Hi! I'm the maintainer of [Eta](https://eta.js.org), an embedded JavaScript template engine.

I'd love to add Eta support to Eleventy. Eta improves on EJS in multiple areas (it has [significantly better performance](https://ghcdn.rawgit.org/eta-dev/eta/v1.6.0/browser-tests/benchmark.html), for example) and also adds new features like plugins and custom delimiters.

What would the process of adding support look like? Can I submit a PR?

**Is your feature request related to a problem? Please describe.**
Eleventy does not support the Eta template engine.

**Describe the solution you'd like**
Add support for the Eta template engine

**Additional context**
[Eta GitHub](https://github.com/eta-dev/eta)
[Eta Website](https://eta.js.org)

**Comment by zachleat** [comment]
Love it! Stay tuned for #117 and you can easily add a plugin yourself!

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by Ryuno-Ki** [comment]
@nebrelbug This might allow you to test the waters: https://github.com/11ty/eleventy/issues/1422#issuecomment-696154131

**Comment by zachleat** [comment]
Removing this one from our enhancement queue, we do want these to live in plugin-land!

**Comment by nebrelbug** [comment]
@zachleat thanks for the update -- I'll start working on a plugin!
