### ISSUE TITLE
Blank line at end of eleventy config file causes TemplateLayoutPathResolver error

### ISSUE THREAD

**Issue by crockwave** [11ty/eleventy#1417]
**To Reproduce**
Add a blank line to the end of the eleventy config file, and it causes the following error:

`TemplateLayoutPathResolver directory does not exist for page.liquid: _includes`

**Expected behavior**
Blank lines at the end of the config file should be ignored

**Environment:**

- OS and Version: Windows and Linux.  Using Sublime in Windows to edit and Ubuntu to run
- Eleventy Version: 0.11.1 

**Additional context**

**Comment by binyamin** [comment]
I do not get this result. Can you please provide some code, or perhaps a repository?

**Comment by crockwave** [comment]
I'm using the Skeleventy repository and had unsucessfully tried to add module.exports = eleventyComputed at the end of the file.  In backing out of that edit, it kept breaking until I compared to the skeleventy repository and noticed no blank line at the end of his config file.

**Comment by zachleat** [comment]
This one needs a reproducible test case, sorry! Whitespace at the end of `.js` files shouldn’t affect Eleventy layouts
