### ISSUE TITLE
Use shortcode in frontmatter permalink?

### ISSUE THREAD

**Issue by jasonday** [11ty/eleventy#1419]
I have a shortcode `{% returnSlug data.value %}` that takes the value from the data and returns a slug (specific to how I do slugs in my headless CMS). I want to use the shortcode in the permalink like so:
`permalink: "standard/{% returnSlug data.value1 %}/criteria/{{ data.value2 }}/index.html"`

Is that possible within nunjucks template frontmatter?

**Comment by araphiel** [comment]
Is it possible to pre-process `value1` in your 11ty data file?

```javascript
const examplePages = [
    {
        title: "Contact",
        category: "company",
        slug: "contact",
    }
]

const transform = string => `yay-${string}`

const transformedPages = examplePages.map(page => {
    page.category = transform(page.category)
    return page
})

module.exports = transformedPages
```

**Comment by zachleat** [comment]
Confirmed this works in the latest Eleventy!
