### ISSUE TITLE
Use last commit as a `date` front matter option

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#142]
This will alleviate the problem of deploying on a remote server and losing all of your file creation/updated dates and also make it unnecessary to hard code dates.

Inspired by vuepress https://vuepress.vuejs.org/default-theme-config/#last-updated

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

The enhancement backlog can be found here: https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+

**Comment by zachleat** [comment]
Related:

* https://www.npmjs.com/package/git-raw-commits
* https://www.npmjs.com/package/git-log-parser
* https://stackoverflow.com/questions/4784575/how-do-i-find-the-most-recent-git-commit-that-modified-a-file#4784629

https://github.com/11ty/eleventy/blob/master/src/Template.js#L615

Maybe worth creating a new abstraction for template dates?

**Comment by BrentARitchie** [comment]
I just wanted to point out that the discussion is mostly about the last commit date so far. There are considerations around first commit date as well, such as if this should operate as if the follow option was specified or not. This would have implications if a file was renamed. The correct behaviour is non-obvious as it would likely need to be dealt with on a case-by-case basis.

Should there be a new config section to specify some of these options? or should it be specified in the front matter of each page?

**Comment by adamduncan** [comment]
We currently have `Last Modified`, which is super handy when building locally. Although have noticed it retruns a possibly misleading value in CI environments.

Would it be helpful to include `Last Changed` as an additional value available for use with Content dates?

I expect it might break the existing understanding of `Last Modified` ([using `ctime`](https://github.com/11ty/eleventy/blob/8a55defd9f57a1aa6ab1c03b5c25c27143648077/src/Template.js#L681-L682) under the hood) vs. `mtime` 🤔 

Or will we still need some git log wizardry to get a file's true Last modified (committed) date?

**Comment by BrentARitchie** [comment]
I've been playing with some ideas and so far the most promising is by using [git-date-extractor](https://www.npmjs.com/package/git-date-extractor) in a prebuild script that drops the created and modified dates into a global datafile. The problem is that the build times do take quite a long time, even after filtering to only files in the sitemap. 24 files takes about 40-ish seconds to crawl and generate in the repo.

May have to look into caching results and truncating the search to recent commits.

**Comment by Ryuno-Ki** [comment]
Thanks, @BrentARitchie.
I looked into the source code. I think, it can be simplified of our use case.
Basically, applying [How to retrieve the last modification date of all files in a git repository](https://serverfault.com/a/401450) with [git log RETTY FORMATS](https://git-scm.com/docs/git-log#_pretty_formats) yields:

```sh
git ls-tree -r --name-only HEAD | while read filename; do echo "$(git log -n1 --format=%aI $filename) $filename"; done
```

In case you can't read bash:
- `git ls-tree`: List the contents of a tree object
- `-r`: Do so recursively
- `--name-only`: Only output the path
- `HEAD`: The latest commit (on main/master)

This yields a list of file names git knows about.
You pipe this into a `while` loop in bash, where the item is assigned to a variable `filename` in each iteration.

- `git log`: Show information
- `n1` (or `-1`): Limit to top one (the latest)
- `--format=%aI`: Use strict ISO format (see the docs)
- `$filename`: Apply to the current file path

I'd suggest to replace the `git ls-tree` and `while` loop in Node to increase the cross-platform compatibility.
Then, trigger a `exec` form `child_process` for each file (or use the `git ls-tree` to compile the list to be sure?).

**Comment by zachleat** [comment]
This adds a `date: "git Last Modified"` option to populate `page.date` with the last git commit.

See https://github.com/11ty/eleventy/blob/8f35e553f80a9a75da3b2eb1a923ecce87f65573/src/Util/DateGitLastUpdated.js and thanks to VuePress for the implementation!

This is slated to ship with 1.0.1

**Comment by nhoizey** [comment]
On a project, I would need a "git First Commited", do you think it would possible to add it?

**Comment by zachleat** [comment]
@nhoizey can you file this as a separate issue? I’d be open to adding an config point for folks to add their own callbacks too

**Comment by kkga** [comment]
Has anyone tried this with Vercel?
It creates a shallow clone of the git repo with only latest 10 timestamps of git history (using `--depth 10`, [source](https://vercel.com/support/articles/how-do-i-use-the-ignored-build-step-field-on-vercel)), so the timestamp returned by `git log` would not actually represent the last commit date for given file in most cases.

**Comment by zachleat** [comment]
Good callout @kkga, probably worth adding a warning to the docs!
