### ISSUE TITLE
How can I combine 'collection.posts' and 'navigation' into one collection sorted by date?

### ISSUE THREAD

**Issue by FA5I** [11ty/eleventy#1423]
Hi,

I have the following `navigation.js` file:

`_data/navigation.js`

```
module.exports = [
    {
      'label': 'my label',
      'url': 'a cool url',
      'date': '2020-09-20'
    },
  ]
```

In my `home.liquid` file this is what it looks like:

```
<ul>
  {% for post in collections.posts %}
  <li>
    <em> {{ post.date | date: "%Y-%m-%d" }} </em> -
    <a href="{{ post.url }}">{{ post.data.pageTitle }}</a>
  </li>
  {% endfor %}

  {% for item in navigation %}
    <li>
      <em> {{ item.date | date: "%Y-%m-%d" }} </em> -
      <a href="{{ item.url }}">{{ item.label }}</a></li>
  {% endfor %}
</ul>
```

What I want do is something like (notice the collection.posts + navigation):

```
<ul>
  {% for post in collections.posts + navigation %} 
  <li>
    <em> {{ post.date | date: "%Y-%m-%d" }} </em> -
    <a href="{{ post.url }}">{{ post.data.pageTitle }}</a>
  </li>
  {% endfor %}
</ul>
```

Is there a way to do this in eleventy?

**Comment by pdehaan** [comment]
I’d probably try another file in _data directory that merged your _data/navigation.is with your collection then somehow try tweaking it so they share the same properties (post.data.pageTitle vs item.label)

**Comment by zachleat** [comment]
https://www.11ty.dev/docs/collections/#getfilteredbytags(-tagname-secondtagname-[...]-) is the thing you’re looking for!

**Comment by groenroos** [comment]
@zachleat Is there a way to directly merge two collections; i.e. create a new collection by combining the results of other collections?

I arrived to this issue from Google, trying to combine two collections created with `addCollection` into a single collection sorted by date:

```js
eleventyConfig.addCollection("things", function (collectionApi) {
	return collectionApi.getFilteredByTag("thing").filter(...);
});
eleventyConfig.addCollection("stuff", function (collectionApi) {
	return collectionApi.getFilteredByTag("stuff").filter(...);
});
eleventyConfig.addCollection("thingsAndStuff", function (collectionApi) {
	return ???;
});
```

I could of course just create the `thingsAndStuff` collection from scratch by filtering tags etc, but each collection has some intricate filtering that I'd like to avoid copypasting, and I still do need each separate collection to exist on their own as well.

Perhaps there's a way to cheese this by creating a merged array through computed data or something, but that feels inelegant somehow.
