### ISSUE TITLE
I have released a temp form of eleventy since there has not been a release in 9 months.

### ISSUE THREAD

**Issue by cekvenich** [11ty/eleventy#1424]
I have released a temp fork of eleventy since there has not been a release in 9 months. There were bug fixes since that I need. I will unpublish npm as soon as eleventy pushes a new npm release. So the code is identical, except it has all the bug fixes. In the mean time, if you want to take advantage of the bugs fixed since 9 months ago and under the terms of the license, anyone can:

npm i -g temp-eleventy-temp

**Comment by pdehaan** [comment]
Per npm, I believe v0.11.0 was published 4 months ago. Or you can always install directly from GitHub instead of npm if you want to be dangerously bleeding edge:

```
@11ty/eleventy
0.11.0 • Public • Published 4 months ago
```

**Comment by cekvenich** [comment]
@pdehaan This says 9 months ago:

https://www.npmjs.com/package/eleventy

**Comment by pdehaan** [comment]
If yow want to install via GitHub instead of npm:

```sh
npm i 11ty/eleventy -D

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN 11ty-main@1.0.0 No description
npm WARN 11ty-main@1.0.0 No repository field.

+ @11ty/eleventy@1.0.0-beta.0 ### <--- Note this line says we're installing @11ty/eleventy @v1.0.0.beta.0! \o/
added 393 packages from 315 contributors and audited 393 packages in 20.027s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

```sh
cat package.json
{
  "name": "11ty-github-test",
  "version": "0.1.0",
  "devDependencies": {
    "@11ty/eleventy": "github:11ty/eleventy"
  }
}
```

And note that the devDependencies shows that we're installing from the **github:11ty/eleventy** repo instead of the package registry.

**Comment by binyamin** [comment]
Maybe we should specify on the readme (under installation) that https://npmjs.com/package/eleventy is a different project.
@pdehaan what do you think?

**Comment by pdehaan** [comment]
Curious if @zachleat or anybody has reached out to the people behind https://github.com/102/eleventy and asked if they'd be willing to give up the ["eleventy"](https://www.npmjs.com/package/eleventy) npm package name. I'd be curious how many people are installing that by accident. They get around 400 npm downloads per week, but maybe there are legitimate uses to depending on that module. If Zach owned it, at least we could put up some deprecation notice and say
> "Oh hey, you look like you want to build a website. Did you mean to type @11ty/eleventy?"

https://github.com/102/eleventy/network/dependents?package_id=UGFja2FnZS0xNDMwMzY0NQ%3D%3D seems to imply that there are at least 87 repositories that depend on that other "eleventy" package (where I ignorantly assume they all **mean** to use `@11ty/eleventy`). But not sure I have the current time/patience to do 87 pull requests to random repos today.

Not sure how much adding a disclaimer to **our** readme would help. I assume most people just typo the dependency name and think this project is <kbd>npm i eleventy</kbd>. It's certainly something I've typoed my fair share of times (and a few other people's share as well).

**Comment by edwardhorsford** [comment]
I've long wondered why Eleventy was installed differently than all other npm modules I've used.

**Comment by cekvenich** [comment]
ftw, I deleted the npm fork, and will use the github npm install.

**Comment by pdehaan** [comment]
> I've long wondered why Eleventy was installed differently than all other npm modules I've used.

@edwardhorsford Do you mean why it's "@11ty/eleventy" vs just "eleventy"?
If so, https://docs.npmjs.com/using-npm/scope.html has a lot of great stuff on the magic of scoped packages (which are becoming more and more popular lately).
