### ISSUE TITLE
How can I programmatically set tags?

### ISSUE THREAD

**Issue by araphiel** [11ty/eleventy#1427]
From the [documentation](https://www.11ty.dev/docs/data-computed/), I see:

> It is important to note that Computed Data is computed right before templates are rendered. Therefore Computed Data cannot be used to modify the special data properties used to configure templates (e.g. layout, pagination, tags etc.). These restrictions may be relaxed over time.

Which means this is not possible:

```markdown
---
pagination:
    data: pressReleases
    size: 1
    alias: pr
    addAllPagesToCollections: true
permalink: "/newsroom/{{ pr.slug }}/"
layout: newsroom-base.liquid

eleventyComputed:
  title: "{{ pr.title }}"
  permalink: "/newsroom/{{ pr.slug }}/"
  tags: "{{ pr.category }}" // 😔😔😔 
---
```

A way to define tags and collections for API data would be incredible.
If possible, can anyone point me in the direction on how this can be changed?

**Comment by nhoizey** [comment]
@araphiel I'm computing tags inside a collection creation here:
https://github.com/nhoizey/nicolas-hoizey.com/blob/master/src/_11ty/collections/notes.js

It adds hashtags found in content to the tags added via Front Matter.

Maybe it can serve as inspiration.
