### ISSUE TITLE
Support for org-mode files.

### ISSUE THREAD

**Issue by danielstaleiny** [11ty/eleventy#1430]
**Is your feature request related to a problem? Please describe.**
I used to use pandoc to convert from org-mode to markdown. I wasn't able to parse header data when going back and fort between markdown and org-mode files.  Which is sad. 

**Describe the solution you'd like**
I would like to see support for org-mode files in the future as possible format. There are already parsers for org-mode for example here is one written in Rust https://github.com/PoiScript/orgize 
here is one in js https://github.com/daitangio/org-mode-parser
I have not used them, so I cannot say any of them are any good. One could say that the specification is missing for org-mode and it depends heavily on the implementation of the org-mode in emacs. However I feel that org-mode is not going anywhere and it has been really stable for long time to make this effort worth it. 

There are certain project which you can get inspiration from to see how they parse org-mode files. 
https://github.com/200ok-ch/organice

**Describe alternatives you've considered**
Pandoc works only 1 way. Org-mode files -> markdown. 

**Additional context**
I Love 11ty and I love org-mode. I want them both. I also backed this project financially because I trully believe that not having js framework baked in the SSG is the best way to generate websites. Love the work, and this is just suggestion. <3

**Comment by anton-rs** [comment]
The only reason I use hugo because of 11ty lack of org-mode file support.

**Comment by AtomicNess123** [comment]
What does Eleventy have does Hugo does not? Thanks! Trying to decide myself.

**Comment by JohnJohnstone** [comment]
> What does Eleventy have does Hugo does not? Thanks! Trying to decide myself.

I think you should ask yourself why am I looking to move static site generator? Hot new thing? The nature of 11ty allows for you to use org-mode files with any JS library that you want. The main reason I was attracted to 11ty.

There seem to be two main ways of using hugo with org-mode. One use go-org to badly translate org to html and a slightly better approach which uses some emacs lisp ox-hugo to convert org to markdown and add the neccesary metadata to files. ox-hugo could be used as a base for starting a new exporter for 11ty the options are limitless but you need to acutally do some work.

The work to get org files working is trivial and i feel should not be included in the project as hugo have done. I also feel issues are not the place for, "I wont use your project until you implement X".

**Comment by zachleat** [comment]
We’re trying to decentralize this a bit, subscribe over at https://github.com/11ty/eleventy/issues/117

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
Yeah, that’s fair feedback. I’m going to move this out of the queue and leave it open to folks that want to do this via plugin. Thanks y’all!

**Comment by Snapstromegon** [comment]
@AtomicNess123 I think that back when this issue was created, the [custom template languages](https://www.11ty.dev/docs/languages/custom/) feature didn't exist yet.

Now it does and you can use it to implement support for org-mode files. Maybe it would be good if someone would create a plugin for it.

**Comment by danielstaleiny** [comment]
I have been playing .org files today and the only thing you need to add is this part of the code in .eleventy.js
What you need is pandoc installed globaly and for easy of use, npm dependency `node-pandoc`

For people wondering how the front matter is handled, it seems that front matter is handled before going into the `compile` function, therefore there is no need to do anything with it. 
```javascript
const nodePandoc_ = require('node-pandoc');
const util = require('util');
const nodePandoc = util.promisify(nodePandoc_)
module.exports = (eleventyConfig) => {
  eleventyConfig.addTemplateFormats('org')
  eleventyConfig.addExtension('org', {
    compile: async (inputContent, inputPath) => {
      const output = await nodePandoc(inputContent, "-f org -t html")
      return async () => {
        return output
      }
    },
  })
}
```

**Comment by thamer** [comment]
Can `{{ title }}` be set to `#+title:` from the org file?

Using @danielstaleiny's pandoc example the `{{ title }}` appears empty.

**Comment by gcr** [comment]
@thamer, you can do that by pre-parsing these fields yourself! Try this:

```javascript
let fs = require('fs');

module.exports = function(eleventyConfig) {
    eleventyConfig.addTemplateFormats('org')
    eleventyConfig.addExtension('org', {
      compile: async (inputContent, inputPath) => {
        const output = await nodePandoc(inputContent, "-f org -t html")
        return async () => {
          return output
        }
      },
      getData: true,
      getInstanceFromInputPath: async (inputPath)=>{
        let data = {};
        fs.readFileSync(inputPath, 'utf-8')
          .split(/\r?\n/).forEach(line =>  {
            let match = /^#\+(.*): (.*)/.exec(line);
            if (match) {
              let key = match[1].toLowerCase(),
                  val = match[2].trim();
              if (key == 'date') {
                data['date'] = val.split(" ")[0].replace(/<|>/g, "");
              } else {
                data[key] = val;
              }
            }
          });
        return {"data": data};
      }
    });
}
```

Then, your org mode file could look like this:
```org
#+title: Example Org Mode Title
#+date: <2023-07-17 Mon>
#+layout: post.njk

This is a test of org post ?
```
Of course, `#+layout:` isn't a standard keyword in org. The "right" way of specifying arbitrary key/value metadata is to use `:PROPERTIES:` drawers, and hopefully you can see how to implement that if that matters to you.

As an alternative, eleventy already strips YAML front matter for you before sending the result through pandoc. This doesn't require any extra configuration on your part, but it isn't how org files are usually written in Emacs.

```org
---
title: Org posts
date: 2023-07-17
layout: post.njk
---

This is a test of org post ?
```

**Comment by koddo** [comment]
@gcr, your code works perfectly, thank you for sharing. But could you help me figure out how to make this a two step process? I'd like to generate markdown from org first, in order to pass this markdown to 11ty.

The reason why I'm asking: html generated from org by pandoc in this example is very different from html generated from markdown by 11ty. It's too much work to fix the discrepancies.

I could just run `pandoc -f org -t gfm` manually and save the result to the content folder, but it would be so much better if it was part of the process.

**Comment by koddo** [comment]
Never mind, I figured out the converting org to html through md. Haven't dealt with front matter yet though.

For posterity:

```js
    eleventyConfig.addTemplateFormats('org')
    eleventyConfig.addExtension('org', {
        compile: async (inputContent, inputPath) => {
            const markdownContent = await nodePandoc(inputContent, "-f org -t gfm");
            const htmlContent = await myMarkdownIt.render(markdownContent);
            return async () => {
                return htmlContent;
            }
        },
    });
```

To make it work, add `const markdownIt = require("markdown-it");` and run `npm install markdown-it --save-dev`. Then configure 11ty to use `myMarkdownIt`, as described here: https://www.11ty.dev/docs/languages/markdown/

```js
    let options = {
        html: true,
    };
    const myMarkdownIt = markdownIt(options);
    eleventyConfig.setLibrary("md", myMarkdownIt);
```
