### ISSUE TITLE
The `htmlTemplateEngine` has no affect on Mustache partials (confusing).

### ISSUE THREAD

**Issue by thelucid** [11ty/eleventy#1431]
**Describe the bug**
When setting `htmlTemplateEngine` to `'mustache'`, template files with an `.html` extension are picked up, however, partials still require a `.mustache` extension. This is a little confusing as it fails silently. I personally think it should allow `.html` extensions for partials, but also should raise an error if the partial is not found.

**To Reproduce**

1. Set `htmlTemplateEngine` to `'mustache'`.
2. Try to render a partial with an `.html` extension.
3. Gets ignored with no error.

**Expected behavior**
Renders partial, or throws error if partial not found.

**Environment:**

- OS and Version: Mac
- Eleventy Version: 0.11.0

**Comment by hidegh** [comment]
I'm having a HTML (tried NJK too) partial. The template in **partial** works, but can't use Front Matter in it. **The Front Matter definition just gets simply rendered as plain text.**
