### ISSUE TITLE
Support processing pipelines for content

### ISSUE THREAD

**Issue by snicolai-blog** [11ty/eleventy#1433]
I'd like to write posts that use things like formatted math in them that are fully rendered at build time.  You can use Katex or Mathjax with the JS running in the client, but I'd like it to run in the build step.  There are other such tools that I'd like to be able to run, js-sequence-diagrams is another one.

These processors probably should run before the main markdown processor, since they output HTML or SVG, which can be inlined into the markdown and will be passed through by the markdown processor.

The configuration should contain a list of the pipelines to use, probably giving each pipeline a name and configuring the various components of the pipeline.

Having multiple pipeline configurations can speed up builds by not running unneeded processors on posts.

Then I'd like to be able to configure how the pipelines are selected for use by either matching on tags on the post or a customer field in the header material.  So I can configure all posts with the tag Math to run through a pipeline with Katex in it.  But I'd also like to be able to use custom fields in the header to control it, maybe giving a name of a configured pipeline.  This could override the tag mechanism if I have something special in the post.  You'll also need a default pipeline.

A pipeline processor should also be able to terminate processing for this piece of content, skipping it.  This way a processor could be used to implement a draft flag, and publishAfter and ExpiresAfter date processing.  The processor should be able to get at command line flags so that a user can indicate whether drafts should be processed or what timestamp to generate the contents for.

If 11ty already supports this, then turn this into a documentation request, as I didn't see how to do it.

**Comment by binyamin** [comment]
@snicolai-blog how about setting a custom markdown-it instance, and adding a markdown+math plugin?

**Comment by jkomyno** [comment]
@binyamin hi, how would you do what you propose?

**Comment by binyamin** [comment]
There's a nice explanation on 11ty's website for [setting your own library instance](https://www.11ty.dev/docs/languages/markdown/#optional-set-your-own-library-instance) & adding your own plugins. Lmk if you need more help.

**Comment by snicolai-blog** [comment]
markdown-it plugins can configure multiple plugins for markdown content, but 11ty handles other types of content in addition to markdown that the 11ty processors don't have such flexible plugin schemes.  The HTML handlers are not nearly as flexible for example.

**Comment by zachleat** [comment]
I think this request is #117 and to use the new extension as a markdown preprocessor? Is that right?

If so we can organize at #117 please!
