### ISSUE TITLE
Returning results from a promise within a shortcode

### ISSUE THREAD

**Issue by noelforte** [11ty/eleventy#1434]
I'm trying to figure out what the best way is to return the results of an async function to be used as a shortcode. I've come across a few issues on this repository that suggest various ways to do this, but none that appear to match my case exactly— it's probably because of my lack of experience trying to wrap my head around promises, but alas here's what I'm trying to accomplish.

I'm using eleventy in combination with [babel](https://github.com/babel/babel) and [terser](https://github.com/terser/terser) to process my javascript files by:

a) using a shortcode that takes the path of a .js file
b) passing that path to a `require`d module
c) the module `exports` a function that returns the transpiled + minified result

**Example:**
```
<module imports ...>

module.exports = async filepath => {
  const babelResult = await babel.transformFileAsync(filepath, {
      presets: [["@babel/preset-env"]],
  });
  const terserReuslt = await minify(babelResult.code);
  return terserResult.code;
};
```

However, when I run `eleventy` the resulting output from the shortcode is always `[object Promise]` even though I've `await`ed the promise to be resolved. What's puzzling is that doing a `console.log(terserResult.code);` yields the expected code. Am I missing something?

Some brief googling took me to this page on [Eleventy Shortcodes](https://www.11ty.dev/docs/languages/nunjucks/#asynchronous-shortcodes), and further exploration took me to the [deasync package](https://www.npmjs.com/package/deasync) on npm. If possible I'd like to run eleventy without extra dependencies, as well as without needing to rely on specific templates— I'd like my shortcodes to stay as universal as possible for flexibility.

**Comment by noelforte** [comment]
An update on this: @louh commented over in the terser repo (https://github.com/terser/terser/issues/801#issuecomment-687678477) about the importance of synchronous minification within templating languages and synchronous code that is core to Eleventy. In the meantime, going to continue exploring the best way to deal with async operations within shortcodes, or find a way to minify my scripts synchronously.

**Comment by binyamin** [comment]
Have you seen https://www.11ty.dev/docs/quicktips/inline-js/?

**Comment by noelforte** [comment]
@binyamin, I have. The caveat with that setup is that Nunjucks is the only templating language that supports async operations, so not the most viable solution. I ended up going back to using `babel-minify` for the time being as I have the option to do sync stuff with babel, and can cut a few dependencies out of my project. I'll leave this issue open for a bit in case people want to discuss more.

**Comment by Joel-Torres** [comment]
Hello,

I have tried unsubscribing multiple times now. Is there an admin person who
can take me off the email list?

**Comment by binyamin** [comment]
@Joel-Torres This is not an email list; it's an issue on GitHub. It looks like GitHub us sending notifications to your email. Log into GitHub, and unsubscribe from whatever you want.

**Comment by Ryuno-Ki** [comment]
https://docs.github.com/en/free-pro-team@latest/github/managing-subscriptions-and-notifications-on-github/configuring-notifications and https://docs.github.com/en/free-pro-team@latest/github/managing-subscriptions-and-notifications-on-github/managing-your-subscriptions describe the process of notifications on GitHub.

**Comment by noelforte** [comment]
Going to mark this as closed since my issue was addressed and this appears to now be drifting off topic.
