### ISSUE TITLE
Run transform on all pages after all pages have been built

### ISSUE THREAD

**Issue by kaicataldo** [11ty/eleventy#1436]
Hi! Thanks for Eleventy - I really love it! I'm working on a plugin that allows users to use React as a templating language ([eleventy-plugin-react](https://github.com/kaicataldo/eleventy-plugin-react)), and I'm attempting to create a bundle of interactive components that are then hydrated on the client after all pages have been built. Besides the upcoming [`afterBuild` hook](https://www.11ty.dev/docs/events/#afterbuild), is there another way to achieve this?

Additionally, ideally this would occur in a transform that could then modify all the pages by inserting the script tag on any pages that have interactive components.

Another way I could achieve this is if I have a list of all pages found before the transform runs, because I could use an async transform and track the in progress pages, deferring the resolution of the transform until all pages have been created. Does that make sense? Not sure about Eleventy's internals here, but figured I'd ask and see if someone more knowledgeable might have an answer. Thank you!

**Comment by kaicataldo** [comment]
I _think_ I've found a way to implement this with the current available APIs: https://github.com/kaicataldo/eleventy-plugin-react/commit/b0df90cd071c6e84253b19491539376cee6f735a#diff-f85c36a1cc8952fb5e6fc7200a89ceaaR137-R188

**Comment by zachleat** [comment]
Just making sure you are aware of the Transforms functionality built into configuration: https://www.11ty.dev/docs/transforms/ (and it looks like your link makes use of that)
