### ISSUE TITLE
Ignore empty frontmatter

### ISSUE THREAD

**Issue by freshyill** [11ty/eleventy#1437]
Is there any way to ignore empty yaml keys in frontmatter? Forestry leaves/creates empty strings, like `layout: ''` and then my pages render without a layout, which is not good. 

It seems like an empty `layout: ''` in the frontmatter is taking precendence over the `"layout" : "post.njk"` that I have specified in my `posts.json` file.

I can work around this in my templates, but it it's still a problem there too. Is this possible?

**Comment by binyamin** [comment]
This sounds like a bug, where empty strings count are processed as values. Additionally, I tested this myself and `layout: null` produces the same result.

**Comment by edwardhorsford** [comment]
I fixed [something similar](https://github.com/11ty/eleventy/pull/557) to this for tags a while back. Sounds like a general fix / doing the same for all 'processed' keys is needed.

**Comment by freshyill** [comment]
Since it seems like this is a bug, I guess I'll try to work around it with computed data in the meantime. Thanks!

**Comment by zachleat** [comment]
Hmm—not sure what to do here—I believe that is an important feature of the data cascade—definitely not a bug. But maybe worth an opt-in feature to override. This will take some thinking

**Comment by zachleat** [comment]
This might also be something Forestry might need to change? Not sure

**Comment by edwardhorsford** [comment]
@zachleat I'm guessing the feature is to let someone explicitly clear the value?

In which case, could you follow the same pattern as `permalink`? eg users can explicitly set it to `false` if needed. But empty strings will be ignored.

**Comment by freshyill** [comment]
Hi! Jumping back in for a second. 

As for Forestry, I can't imagine it's an intentional feature, because it's confusing for non-technical users, and in some cases, impossible to undo without editing the Markdown file directly. To anybody who doesn't know what's going on under the hood, they just see the page they created just show up with no layout, empty things showing up, with no way to remove them, etc.

**Comment by freshyill** [comment]
A very late follow up: I filed a support question with Forestry, and they have no plans to address this.

**Comment by zachleat** [comment]
Howdy y’all! I think the best way forward here is to use Forestry’s Default value or Validation options to prevent users from setting those empty values:

e.g. https://forestry.io/docs/settings/fields/text/#options

If that doesn’t work, I think the best way forward is probably https://github.com/11ty/eleventy/issues/1528, please subscribe over there!
