### ISSUE TITLE
Don't generate html from data files

### ISSUE THREAD

**Issue by SirePi** [11ty/eleventy#1439]
Is is possible to have eleventy use, for example, an .md file's frontmatter to populate collections, without having the same md file generate its corresponding .html file? 

I'd like to use .md files for a gallery, where I only need a couple of links to images and a title, I don't want to have its relative empty page. Of course I could just ignore the folder when copying the site, but I'd like a clean solution, if possible

**Comment by marcuse** [comment]
Setting `permalink: false` in the frontmatter seems to suppress file generation. Not sure if it's a feature or a happy accident.

**Comment by SirePi** [comment]
Wow! I completely missed that in the docs. Thanks a lot 👍

**Comment by Nooshu** [comment]
A note for folks coming across this using version 3.0.0. When I tried `permalink: false` in an MD file, it outputs a really nasty error, so this functionality may have been removed?

**Comment by zachleat** [comment]
@Nooshu can you open a new issue? I’d guessing it’s related to some code in an Eleventy transform (but the error messaging is clearly not great)

**Comment by Nooshu** [comment]
Done @zachleat issue raised [here](https://github.com/11ty/eleventy/issues/3503).
