### ISSUE TITLE
Liquid Custom Tag, Need Help

### ISSUE THREAD

**Issue by navarrorc** [11ty/eleventy#144]
Hi.

I just created a Universal filter and it works
```
 // Universal filters (Adds to Liquid, Nunjucks, and Handlebars)
  eleventyConfig.addFilter("cacheBuster", function(value) {
    let milliseconds = Date.now();
    return value + "?Rev=" + milliseconds;
  });
```
It's being used as follows
```
<script src="{{ '/dist/vendor.js' | url | cacheBuster}}"></script>
```
And it returns `<script src="/dist/vendor.js?Rev=1529687538285"></script>`

<hr>
How can I make this into a liquid tag? The intent is to use it as follows

`{% cacheBuster %}`

It should return `?Rev=1529686251216`

My failed attempt was the following:
```
  eleventyConfig.addLiquidTag("cacheBuster", function(scope, hash) {
    let milliseconds = Date.now();
    return Promise.resolve("?Rev=" + milliseconds); // ?Rev=1529686251216
  });
```
The issue is that there is no output from the tag.

Thanks for the help in advanced.

**Comment by zachleat** [comment]
If you’re reading this on email, I edited the code!

**Comment by navarrorc** [comment]
I will give it a try tomorrow. Thanks again.

**Comment by zachleat** [comment]
Hmm @navarrorc after looking at this again, I think what I sent you was wrong—so sorry. In fact, I think the example I had on the docs was wrong too.

I’ve added a better documented (and correct) example to the docs:
https://www.11ty.io/docs/custom-tags/

This is what you want

```js
eleventyConfig.addLiquidTag("cacheBuster", function(liquidEngine) {
  return {
    parse: function(tagToken, remainingTokens) {},
    render: function(scope, hash) {
      let milliseconds = Date.now();
      return Promise.resolve("?Rev=" + milliseconds);
    }
  };
});
```

**Comment by zachleat** [comment]
Please reopen if you have more questions!

**Comment by navarrorc** [comment]
Hi @zachleat the code you provide works great. Thank you.

You do have a problem in the documentation, however; shouldn't the `Liquid.evalValue(...)` call be `liquidEngine.evalValue(...)` instead? I get an error,  `Liquid is not defined` when trying to use `uppercase` tag.

**Comment by zachleat** [comment]
You’ll notice a `require` that includes the Liquid lib on the docs example but you’re right—this can be simplified! I’ve updated the docs—thanks!
