### ISSUE TITLE
[Tests] Why are we testing the dependency-graph module?

### ISSUE THREAD

**Issue by binyamin** [11ty/eleventy#1440]
Why are we testing an external dependency? If it makes sense, shouldn't the reason be noted in a comment?

https://github.com/11ty/eleventy/blob/330191c10b9ab4b93a3abcf6406bbc350a47aa7d/test/DependencyGraphTest.js#L3-L5

**Comment by zachleat** [comment]
Just some checks to make sure my assumptions about how the library worked were correct when I was learning how to use it. I don’t think there’s much harm in leaving it there, is it causing an issue?

**Comment by binyamin** [comment]
I was just trying to understand the testing section. It might confuse future contributors.
