### ISSUE TITLE
top-level svg in .html include fails to render when opening tag split into multiple lines

### ISSUE THREAD

**Issue by boneskull** [11ty/eleventy#1442]
**Describe the bug**

When:

- you have an included `.html` file, and
- the top-level tag of the file is `svg`, and 
- the _opening tag_ is _spread over multiple lines_, then

...the SVG fails to render in the browser.

**To Reproduce**

1. Go to https://gist.github.com/boneskull/390aaea1c837188ae84e3a7b5ef0829e
2. Grab `include-ok.html` add to 11ty site, and include it in a layout
3. Build site; see it renders similarly to: ![image](https://user-images.githubusercontent.com/924465/95620668-63d67980-0a25-11eb-90eb-5f5202d88bbf.png)
4. Replace `include-ok.html` with `include-broken.html`, build site and refresh
5. See something broken like: 
![image](https://user-images.githubusercontent.com/924465/95620805-94b6ae80-0a25-11eb-92a9-b202451f23b4.png)

You can then see the problem is fixed by trying `include-ok-wrapped.html`, which wraps the `svg` in a `div` tag.  It doesn't even need to be wrapped; the first tag can be an empty div like `<div></div>` followed by `<svg ..>`, and it will render properly.

**Screenshots**

See above

**Environment:**

- OS and Version: macOS 10.15.7
- Eleventy Version: v0.11.0

**Additional context**

may be the fault of something else in our configuration (it's in the gist).

Ref: https://github.com/mochajs/mocha/pull/4440

**Comment by binyamin** [comment]
@boneskull sorry for the wait. I'll try to take a look within 24 hours.

**Comment by boneskull** [comment]
no rush, it's a corner case w/ a trivial workaround.

**Comment by binyamin** [comment]
Test results:
- Breaks with markdown+liquid
- Does not break with nunjucks
- Does not break with just liquid
The problem may actually be with [markdown-it](https://github.com/markdown-it/markdown-it), which Eleventy uses under the hood. I'd open an issue there. Be sure to mention that the svg include works when wrapped in a div.

In the meantime, you could always try using a different markdown parser.

**Comment by Ryuno-Ki** [comment]
If you want to change the markdown parser, this section in the docs explain how to do that:
https://www.11ty.dev/docs/languages/markdown/#optional-set-your-own-library-instance
(Eleventy doesn't care, whether the set library is still `markdown-it`).

**Comment by zachleat** [comment]
Yeah, this is a markdown-it parser bug I think! Can you file it there instead? https://github.com/markdown-it/markdown-it/issues

https://markdown-it.github.io/

broken:
<img width="1273" alt="image" src="https://github.com/11ty/eleventy/assets/39355/e9546b54-b94a-42f5-8ad3-89ca34773cfe">

broken:
<img width="1257" alt="image" src="https://github.com/11ty/eleventy/assets/39355/6e639845-d8e5-4315-ba7d-225cd6276ef3">

working:
<img width="1218" alt="image" src="https://github.com/11ty/eleventy/assets/39355/b3b57111-8a45-40f3-9197-ccb4d85802be">
