### ISSUE TITLE
addWatchTarget ignored when used in a custom config file

### ISSUE THREAD

**Issue by gael-ian** [11ty/eleventy#1448]
Hi,

When used in a custom config file, `addWatchTarget` is ignored.

**To Reproduce**

1. Clone [this repository](https://github.com/gael-ian/11ty-addwatchtarget-issue) and install dependencies.  
    It's nothing more than [Eleventy's Getting started](https://www.11ty.dev/docs/getting-started/) with 2 config files: `.eleventy.js` and `config/eleventy.js`. Both contain a call to `addWatchTarget`.
2. Run `DEBUG=Eleventy npx @11ty/eleventy --serve`.
3. `addWatchTarget` works:  
   ```
   Eleventy Watching for changes to: [ './assets/**', './**/*.liquid', […], './**/*.11tydata.js' ] +5ms
   ```
3. Rename the default `.eleventy.js`: `mv .eleventy.js ._eleventy.js`
4. Run `DEBUG=Eleventy npx @11ty/eleventy --config=config/eleventy.js --serve`
5. `addWatchTarget` is broken:  
   ```
   Eleventy Watching for changes to: [ './**/*.liquid', […], './**/*.11tydata.js' ] +5ms
   ```

**Expected behavior**

`addWatchTarget` should work when called from a custom config file.

As a bonus, should `.eleventy.js` even be loaded when Eleventy is called with a custom config file ?

**Comment by binyamin** [comment]
Confirmed. `addWatchTarget()` does not work with any custom config file.
@gael-ian Thanks for the detailed bug report.

**Comment by dafiulh** [comment]
Has this been fixed?

**Comment by TigersWay** [comment]
Still not fixed and pretty annoying! Any trouble with #1568 from @dafiulh ?

**Comment by davidbwaters** [comment]
OMG, thanks for this.

**Comment by einomi** [comment]
Any updates on this? Look like this PR adds a fix for this issue? https://github.com/11ty/eleventy/pull/1568

**Comment by zachleat** [comment]
> As a bonus, should .eleventy.js even be loaded when Eleventy is called with a custom config file ?

Confirmed this as already fixed (tested in 2.x and 1.x)

As for the PR #1568 I was able to confirm that this issue is no longer relevant on 1.x:

```
DEBUG=Eleventy* npx @11ty/eleventy --watch --config=eleventy.config.js
```

```
[11ty] Wrote 0 files in 0.08 seconds (v1.0.1)
Eleventy Watching for changes to: [ './assets/**',          './**/*.liquid', './**/*.ejs',           './**/*.md', './**/*.hbs',           './**/*.mustache', './**/*.haml',          './**/*.pug', './**/*.njk',           './**/*.html', './**/*.11ty.js',       './**/*.11ty.cjs', './_includes/**',       './_data/**', './eleventy.config.js', './**/*.json', './**/*.11tydata.cjs',  './**/*.11tydata.js' ] +5ms
```

```js
// eleventy.config.js
module.exports = function(eleventyConfig) {
  eleventyConfig.addWatchTarget("assets/**");
};
```

Thanks everyone! (please speak up if I’m wrong!)
