### ISSUE TITLE
Html template code is broken 

### ISSUE THREAD

**Issue by agrittiwari** [11ty/eleventy#1449]
echo '<!doctype html><html><head><title>Page title</title></head><body><p>Hi</p></body></html>' > index.html

The above is not working because one extra  > is required.

echo '<!doctype html><html><head><title>Page title</title></head><body><p>Hi</p></body></html>'  >> index.html

**Comment by binyamin** [comment]
Thanks for the heads-up. Which page is this?

**Comment by agrittiwari** [comment]
https://www.11ty.dev/docs/getting-started/


step 4

**Comment by binyamin** [comment]
@agrittiwari `echo foo > file.txt` is valid bash syntax (See https://askubuntu.com/a/420983). When you say "the above is not working", why is it not working?

**Comment by agrittiwari** [comment]
I was mentioning the code snippet, HTML expression particularly
the error was:   > unexpected.

And I was using cmd. Maybe it's about bash particularly

**Comment by binyamin** [comment]
huh. I get this error with the command prompt, but not with powershell. Try powershell.

**Comment by Ryuno-Ki** [comment]
@agrittiwari Which OS are you using? I could check with a bash / sh on GNU/Linux.

**Comment by agrittiwari** [comment]
yep only with cmd. Got it. so I used >> instead of > in cmd
@Ryuno-Ki I am using windows.

**Comment by Ryuno-Ki** [comment]
On (ba)sh, `>>` would append (instead of (over)write a file). But if it works in your case, I guess, it's fine.

**Comment by Ryuno-Ki** [comment]
@agrittiwari Thinking of it. Would you add a PR to the documentation (at 11ty-website) to update the docs for Windows?

**Comment by zachleat** [comment]
https://techpp.com/2021/08/22/create-file-using-command-prompt-guide/ seems to report that `>` works in Windows, fwiw
