### ISSUE TITLE
Handlebars excaping outputs additional '}' character

### ISSUE THREAD

**Issue by rpk506** [11ty/eleventy#145]
Where you have triple-braces in a template file like this

```
<div class="container">

        <div class="row">
            <div class="col-sm-3">
                <h2>This is where the sidebar would live</h2>
            </div>
            <div class="col-sm-9">
                {{{content}}}
            </div>
        </div>
    </div>
```
The output to the browser from the compiled Eleventy html file includes an extra '}' closing brace character. 

This is the same behaviour for both Handlebars and Mustache template files
[pattern-library.zip](https://github.com/11ty/eleventy/files/2130680/pattern-library.zip)

**Comment by zachleat** [comment]
Ah, a couple of issues here:

1. Your `.eleventy.js` is hardcoded to only parse `md` files. You may want to leave this to eleventy defaults and just delete it. At the very least, you’ll want to add `html`, `mustache`, and `hbs`, I think?
2. `html` files by default (like your `mytemplate.html` file) are parsed using the `liquid` templating engine. This is configurable, see https://www.11ty.io/docs/config/#default-template-engine-for-html-files. So the problem there is that your file is being parsed as a Liquid template, which doesn’t use the triple-stash `{{{` notation.

**Comment by zachleat** [comment]
Please reopen if you have more questions!

**Comment by rpk506** [comment]
Damn, well don't I feel silly. Sorry about that, but thank you for the detailed reply.

**Comment by zachleat** [comment]
Happy to help!
