### ISSUE TITLE
How to implement an async nunjucks filter

### ISSUE THREAD

**Issue by davegardner** [11ty/eleventy#1450]
I am developing an image gallery where metadata is extracted from the jpg files and used to annotate the images.
I cannot find a way to add the metadata to the image, and am pretty sure I am doing something wrong but cannot work out what. Maybe someone with more JS skills than I have can provide a pointer to what I am doing wrong.

In eleventy.js I have this code:

```js
// Import exif data extractor
  const exifr = require("exifr");
  
  // Nunjucks Async Filter to extract image metadata and add it to to each image in imageList
  eleventyConfig.addNunjucksAsyncFilter("getExifAsync", function(imageList, params, callback) {
    if (imageList) {
      imageList.forEach(async image => {
        image.meta = await exifr.parse(image.name, params);
        //console.log(image);
      });
    }
    callback(null, imageList);
  });

```
If I uncomment the console.log line then the metadata is printed to the console correctly.

Here is the template:
```njk
<div >
    {% for image in mediaList | sort(mediaList, reverse, caseSens, attr) | getExifAsync( ['LensModel', 'Model', 'ISO'] ) %}
        <figure class='gallery'>
            <img class='thumbnail' src="{{ image.url }}" alt="" title="">
            <figcaption>iso {{ image.meta.ISO }}</figcaption>
        </figure>
    {% endfor %}
</div>
```
The images are displayed but the metadata (just ISO in this example) is not.

How can I get metadata to display?

**Comment by Ryuno-Ki** [comment]
You're not awaiting the Promises in the `forEach`.

Try this:

```js
  const exifr = require("exifr");
  
  // Nunjucks Async Filter to extract image metadata and add it to to each image in imageList
  eleventyConfig.addNunjucksAsyncFilter("getExifAsync", function(imageList, params, callback) {
    if (imageList) {
      Promise.all(imageList.map(async image => {
        image.meta = await exifr.parse(image.name, params);
        //console.log(image);
        return;
      })).then(() => {
        callback(null, imageList);
      });
    }
    callback(null, imageList);
  });
```

An `async` function is always returning a Promise (by definition). You need to wait until all `exifr.parse` operations are completed before invoking the `callback`.

**Comment by davegardner** [comment]
Thank you! That was the missing concept. The final code is:
```js
 // Nunjucks Async Filter to add image metadata to each image
  eleventyConfig.addNunjucksAsyncFilter("getExifAsync", function (imageList, params, callback) {
    if (imageList) {
      Promise.all(imageList.map(async image => {
        image.meta = await exifr.parse(image.name, params);
      })).then(() => {
        callback(null, imageList);
      });
    }
  });
```

**Comment by davegardner** [comment]
Many thanks Andre

**Comment by Ryuno-Ki** [comment]
Thanks for sharing the working solution.

I'm wondering, though, what happens if `imageList` is falsy?

**Comment by davegardner** [comment]
I was a bit over-enthusiastic removing the final callback(). So now I have an 'else':

// Nunjucks Async Filter to add image metadata to each image
  eleventyConfig.addNunjucksAsyncFilter("getExifAsync", function (imageList, params, callback) {
    if (imageList) {
      Promise.all(imageList.map(async image => {
        image.meta = await exifr.parse(image.name, params);
      })).then(() => {
        callback(null, imageList);
      });
    } else {
      callback(null, imageList);
    }
  });

**Comment by akelmj** [comment]
According  to Nunjucks  documentation you need to add true flag to the filter:

or you can use the code and add your code inside:

`eleventyConfig.addFilter('asyncFilter', async (src, parameter , callback) => {
  const result = await  .....;
  callback(null, result);
}, true);
`

`// Nunjucks Async Filter to add image metadata to each image
  eleventyConfig.addNunjucksAsyncFilter("getExifAsync", function (imageList, params, callback) {
    if (imageList) {
      Promise.all(imageList.map(async image => {
        image.meta = await exifr.parse(image.name, params);
      })).then(() => {
        callback(null, imageList);
      });
    } else {
      callback(null, imageList);
    }
  },**true**);`
