### ISSUE TITLE
Extracting body content from an item in a collection

### ISSUE THREAD

**Issue by declanbyrd** [11ty/eleventy#1453]
To give context to this question, I'm trying to build an interactive presentation using 11ty. What I'd like to do is to create a new markdown file for each slide and have the slide content output into a html `<article>` so that all the slides are output to a single html file.

Is there a way I can access the HTML output of the markdown file so that I can add it to the template?

**Comment by binyamin** [comment]
Try looping over the collection, and accessing the `content` property.
```html
{% for slide in collections.slides %}
  <article>
    {{slide.content}}
  </article>
{% endfor %}
```

**Comment by declanbyrd** [comment]
Hi @binyamin, thanks for your reply. I get undefined when I log `slide.content` using `{{slide.content | log}}`. I managed to get this working using:

```html
{% for slide in collections.slides %}
<article>
  {{slide.templateContent | safe}}
</article>
{% endfor %}
```
