### ISSUE TITLE
pathPrefix without leading slash doesn’t serve right in browsersync

### ISSUE THREAD

**Issue by indcoder** [11ty/eleventy#1454]
On production , our blog will be tucked under a subdirectory of our root domain, most probably blog. As such I made the pathPrefix change in 11ty config to check out on our local server [I have given the pathPrefix "XAZ" to observe what changes are made in the repo + generated output under _site]

![image](https://user-images.githubusercontent.com/2099300/93105561-dd03da80-f6cc-11ea-8a61-bd1e4ebd6e7c.png)

But the posts(blog index) does not get displayed when we run the npm run serve.

![image](https://user-images.githubusercontent.com/2099300/93105983-569bc880-f6cd-11ea-98ca-3ce3f89908d8.png)

Can we test this functionality on our local workstation during development  or is there some other changes we need to make?

**Comment by zachleat** [comment]
While the URLs being generated from Eleventy using pathPrefix were coming out right, BrowserSync did expect a leading slash from the pathPrefix. This’ll be fixed automatically the next version of Eleventy.
