### ISSUE TITLE
Nunjucks blocks are reordered when using layout in frontmatter

### ISSUE THREAD

**Issue by mubaraqwahab** [11ty/eleventy#1456]
**Describe the bug**
Given this `layout.html` Nunjucks layout

```njk
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ title }}</title>
    {%- block styles -%}{%- endblock -%}
  </head>
  <body>
    {{ content | safe }}
  </body>
</html>
```
and this template:

```njk
---
layout: layout
title: Home
---

{%- block styles -%}
  <style>
    body {
      color: white;
      background-color: black;
    }
  </style>
{%- endblock -%}
```

Eleventy generates the following HTML:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home</title></head>
  <body>
    <style>
    body {
      color: white;
      background-color: black;
    }
  </style>
  </body>
</html>
```

Notice that the content of the `style` block has been moved into the `body` element. If I use Nunjucks own `extends` tag instead of the `layout` in the frontmatter, it works fine. I suspect that the block is considered as part of the `content` variable. Is this an intended behaviour? I should also mention that the `content` variable doesn't seem to work when using `extends`.

**To Reproduce**

1. Visit [this code sandbox](https://codesandbox.io/s/relaxed-neumann-ivl9l). `index.html` there uses frontmatter layout field. `index2.html` uses Nunjucks `extends` tag.
2. Open a new terminal tab and run `npx eleventy`
3. Compare the two generated HTML files in the `_site/` folder

**Expected behavior**
This output:

```njk
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home</title><style>
    body {
      color: white;
      background-color: black;
    }
  </style></head>
  <body>
    
  </body>
</html>
```

**Screenshots**

**Environment:**

- OS and Version: Ubuntu 18.04
- Eleventy Version: 0.11.0

**Additional context**

**Comment by andyford** [comment]
anyone who lands on this page should read through this thread: https://github.com/11ty/eleventy/issues/853

the overview is if you want to use nunjucks blocks, then you should declare the template via a nunjucks `{% extends %}` statement and not via the `template` keyword in the frontmatter.

so instead of this:
```
---
layout: layout.html
title: Home
---

{%- block styles -%}
  <style>
    body {
      color: white;
      background-color: black;
    }
  </style>
{%- endblock -%}
```

...you should be able to use this:
```
---
title: Home
---

{%  extends "layout.html" %}

{%- block styles -%}
  <style>
    body {
      color: white;
      background-color: black;
    }
  </style>
{%- endblock -%}
```

**Comment by mubaraqwahab** [comment]
Thank you!
