### ISSUE TITLE
Include TypeScript types for configuration files

### ISSUE THREAD

**Issue by NotWoods** [11ty/eleventy#1459]
**Is your feature request related to a problem? Please describe.**
It's often unclear what configuration options are available, and it would be great to have documentation available on hover in my editor.

**Describe the solution you'd like**
By distributing TypeScript types, config files can use TypeScript's JSDoc checking to verify their configuration is set up properly. 

```js
/** @type {import('@11ty/eleventy').LocalConfig} */
const config = (eleventyConfig) => {
  // Add a filter using the Config API
  eleventyConfig.addFilter( "myFilter", function() {});

  // You can return your Config object (optional).
  return {
    dir: {
      input: "views"
    }
  };
};

module.exports = config
```

**Describe alternatives you've considered**
The types could alternatively be distributed by DefinetlyTyped instead. Consumers would install a `@types` package in addition to Eleventy.

**Additional context**
I have a type file [already written](https://github.com/NotWoods/11ty-plugins/blob/typescript/packages/types/index.d.ts)! I'm happy to send a PR with tests if you're OK with this change.

**Comment by Ryuno-Ki** [comment]
My PR https://github.com/11ty/eleventy/pull/720 is still awaiting going forward.

Related to #814

**Comment by zachleat** [comment]
Yes! @Ryuno-Ki is our expert here on jsdocs 😅 I have been merging PRs with those additions.

I will close this though, feel free to continue the pattern of @Ryuno-Ki’s work though!

**Comment by Ryuno-Ki** [comment]
Thanks, @zachleat.

My current plan is to submit PRs for one file after the order (so Zach won't get overburden too much). I hope to get JSDoc annotations in before the v1 release (outside of beta).

I'm leaning into https://gils-blog.tayar.org/posts/jsdoc-typings-all-the-benefits-none-of-the-drawbacks/ here.
The type declarations could be turned into a `.d.ts` file via `tsc --emitDeclarationOnly true` then.
