### ISSUE TITLE
Ability to load .hbs partials from sub folders

### ISSUE THREAD

**Issue by rpk506** [11ty/eleventy#146]
At the moment, you can only load handlebars partials from the root of the _includes folder. However, it would be good to be able to specify where those partials are located. 

For us, for example, we want to be able to put our partials in the same folder as the .md files that load them, like this:

--components
|----listings
|--------listing.md
|--------listing.scss
|--------listing.hbs

Although my example is limited to handlebars, I'm sure other types of templates (nunchucks, html, etc.) would benefit from the use of being able to specify a location folder - just like we can with layouts.

**Comment by chrisdmacrae** [comment]
I tackled this for EJS in a different way in a PR.

EJS has the idea of "absolute" imports and "relative" imports.

Absolute imports get included from the `_includes` folder, whereas relative includes get included relatively from the file they're called in.

Wondering if we can emulate this behavior across the board, as it's _super_ useful.

**Comment by rpk506** [comment]
Thanks for that Chris. I did manage to get something working where you can inline the partials directly in the .md file and then use it again and again in the same file.

This works ace, but I'm not sure how I feel about it. I'm leaning towards wanting it in a separate .hbs file ideally.

**Comment by chrisdmacrae** [comment]
@rpk506 I think all three methods have their place. I use your method in some scenarios:

- Inline partials for repeating content of a specific partial: e.g, a menu partial that has a repeating list item.
- Relative partials for separation of concerns in content (e.g, separating code samples from documentation)
- Relative partials for really complicated related files for a single partial
- Absolute partials for general partials, components, etc

**Comment by zachleat** [comment]
Ah, I see what you mean by this @rpk506. This will be fixed in 0.5.0

**Comment by zachleat** [comment]
Test added here: https://github.com/11ty/eleventy/blob/master/test/TemplateRenderHandlebarsTest.js#L44
