### ISSUE TITLE
Ejs includes not working

### ISSUE THREAD

**Issue by dm19** [11ty/eleventy#1463]
**Describe the bug**
Eleventy cannot find includes when following the [documentation](https://www.11ty.dev/docs/languages/ejs/). `<% include [path from _includes]/[file name] %>` should be correct, but produces the errors below:

```
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble writing template: _site/index.html

`TemplateWriterWriteError` was thrown
> ./_includes/layouts/base.ejs:1
 >> 1| <% include /partials/header %>
    2|

partials is not defined

`ReferenceError` was thrown:
    ReferenceError: ./_includes/layouts/base.ejs:1
     >> 1| <% include /partials/header %>
        2|

    partials is not defined
        at eval (./_includes/layouts/base.ejs:10:17)
        at base (/home/me/Projects/bugreport/node_modules/ejs/lib/ejs.js:691:17)
        at /home/me/Projects/bugreport/node_modules/@11ty/eleventy/src/Engines/Ejs.js:50:14
        at TemplateLayout.render (/home/me/Projects/bugreport/node_modules/@11ty/eleventy/src/TemplateLayout.js:152:31)
        at async Template.renderPageEntry (/home/me/Projects/bugreport/node_modules/@11ty/eleventy/src/Template.js:606:17)
        at async Template.writeMapEntry (/home/me/Projects/bugreport/node_modules/@11ty/eleventy/src/Template.js:619:21)
        at async Promise.all (index 1)
        at async Eleventy.write (/home/me/Projects/bugreport/node_modules/@11ty/eleventy/src/Eleventy.js:745:13)
        at async Eleventy.watch (/home/me/Projects/bugreport/node_modules/@11ty/eleventy/src/Eleventy.js:652:5)
Wrote 0 files in 0.02 seconds (v1.0.0-beta.0)
```

**To Reproduce**
Create a test site containing:
-  _includes/layouts/base.ejs
-  _includes/partials/header.ejs
- index.ejs

File contents:
base.ejs:
`<% include /partials/header %>`

header.ejs:
`[anything]
`
index.ejs:
```
---
layout: layouts/base.ejs
---
```

**Expected behavior**
Eleventy builds without issue and includes the header content on the created page.

**Screenshots**

**Environment:**

- OS and Version: Arch Linux
- Eleventy Version: 1.0.0-beta.0

**Additional context**
I tried playing around with various combinations of quotes and parentheses around the path, but don't really know what I'm doing and couldn't get anything to work. Trying to use the `<% include 'user/show' %>` format produced an unexpected string error.

**Comment by dm19** [comment]
I got `<%- include('path') %>` syntax to work (without the `-` the include gets all escaped I think), but it still doesn't look like the first examples in the documentation page work.

**Comment by binyamin** [comment]
@dm19 Can you please link to the problematic repo?

**Comment by Nixinova** [comment]
Having the same issue, if I have file `ad.html` in _includes I have to use `<% include ../../_includes/ad.html %}` (or equivalent) instead of just `<% include ad.html %>`

**Comment by pdehaan** [comment]
@Nixinova I have a version of EJS includes working using `<%- include('/header'); %>` where my header.ejs file is in ./src/_includes/header.ejs.

I pushed the sample repo to https://github.com/pdehaan/11ty-ejs.

**Comment by Nixinova** [comment]
Thanks, I will try that

**Comment by zachleat** [comment]
Eleventy 0.x has `ejs` v2 and Eleventy 1.0 has `ejs` v3.

This is a breaking change in `ejs` v3.

Read more at https://github.com/11ty/eleventy/issues/1392
