### ISSUE TITLE
Looked up page by permalink

### ISSUE THREAD

**Issue by pspeter3** [11ty/eleventy#1470]
**Is your feature request related to a problem? Please describe.**
It would be nice if templates had the ability to look up a page by permalink. Today you need to loop through all of the collections and filter to the pages with the permalink.

**Describe the solution you'd like**
Add a mapping from permalink to file.

**Describe alternatives you've considered**
- Add a shortcode which loops over all collections to find the file.
- Add an `eleventyComputed` property which creates this map.

**Additional context**

**Comment by nhoizey** [comment]
I don't understand if that's exactly what you need, but I released a plugin a few days ago that adds a nunjucks tag to link to another internal content in Eleventy, using the slug, filePathStem or URL:
https://github.com/nhoizey/eleventy-plugin-link_to#readme

**Comment by edwardhorsford** [comment]
@pspeter3 I have a Nunjucks filter for doing that. The code doesn't really look like syntax that I'd use, so I'd guess that I copied it from another github issue here.

```
exports.filterPostsByUrl = function(items, slug, exactMatch=false) {

	var output = items.filter( item => {
		if (exactMatch==false && (typeof item.url === 'string' || item.url instanceof String)) return item.url.includes(slug)
		if (exactMatch==true && (typeof item.url === 'string' || item.url instanceof String)) return item.url == slug
		else return false
	})

	// Return false if no items found
	return (output && output.length > 0) ? output : false
}
```

**Comment by pspeter3** [comment]
@edwardhorsford yeah, that's definitely an alternative but I'm hoping that we can have a solution that is not O(n) every time.

**Comment by zachleat** [comment]
Related https://github.com/11ty/eleventy/issues/399 https://github.com/11ty/eleventy/issues/544

> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
This shipped with https://github.com/11ty/eleventy/issues/84#issuecomment-1882250490 (removing from queue)
