### ISSUE TITLE
beforeBuild and afterBuild events not run on Netlify build

### ISSUE THREAD

**Issue by f-elix** [11ty/eleventy#1472]
**Describe the bug**
I use the build events beforeBuild and afterBuild in my pipeline to process my assets, and they are working great when I run a local build, but they are not getting fired when the command is run by Netlify. 

I inserted console logs at several steps to keep track of the build process. I can see the messages printed on my local console but can't see any in the Netlify deploy logs. Moreover, my assets are dependant on the code that runs in those events to be inserted in the final build folder, and they are not in said folder once Netlify is done.

**To Reproduce**

1. Use eleventy events (ideally with console logs)
2. Run a local build and notice the events are called properly
3. Deploy the repo on Netlify
4. Look at the Netlify logs and final output, and notice the events weren't called

**Expected behavior**
The events should be run both locally and on Netlify.

**Environment:**

- OS and Version: Windows 10
- Eleventy Version 0.11.1

**Comment by binyamin** [comment]
@f-elix You might want to try https://community.netlify.com first. That's their support community. Also, can you link to the repo that's causing you trouble?

**Comment by f-elix** [comment]
Sure, here you go: https://github.com/f-elix/eleventy-starter

I'll ask in the Netlify forum and will let you know if I find anything.

**Comment by f-elix** [comment]
All I got no answer on the Netlify community forum, but I was able to deploy the repo successfully on Vercel, with all the build events getting called.

I'm closing this issue as this is clearly an issue with Netlify.

Thanks!

**Comment by f-elix** [comment]
UPDATE:

I found out what the problem was with Netlify. 

I was setting the NODE_ENV variable to production in my site settings. As per Netlify's docs, when that's the case, Netlify won't install the devDependencies during the build process (why that is, I cannot understand). Since Eleventy was in my devDependencies (among other things), nothing was being built with my actual setup.
