### ISSUE TITLE
eleventyignore should pick up changes without a restart

### ISSUE THREAD

**Issue by tcurdt** [11ty/eleventy#1473]
**Is your feature request related to a problem? Please describe.**

I am using `eleventyignore` to hide parts of my sites.
When I change the file I need to restart the server (`eleventy --serve`) to see the change.

**Describe the solution you'd like**

I wish eleventy would also watch the `eleventyignore` file and pick up the changes without a restart.

**Comment by zachleat** [comment]
Shipping with 2.0.0-canary.19 from the excellent PR from #2480. Thanks @Snapstromegon !
