### ISSUE TITLE
Prism twig makes eleventy build fail

### ISSUE THREAD

**Issue by jan-dh** [11ty/eleventy#1474]
**Describe the bug**
I'm using `11ty/eleventy-plugin-syntaxhighlight` to highlight code with prism in a `.md` file.
When trying to highlight twig syntax, eleventy fails to build and I get:

```
> Having trouble rendering liquid (and markdown) template ./src/posts/test-post.md

`TemplateContentRenderError` was thrown
> Having trouble compiling template ./src/posts/test-post.md

`TemplateContentCompileError` was thrown
> tag set not found, file:./src/posts/test-postmd, line:12

`ParseError` was thrown
> tag set not found

`AssertionError` was thrown:
    AssertionError: tag set not found
     ....
```

I'm assuming this is because I'm trying to output this:

```twig
....
{% set url = lang.getBaseUrl() %}
```

**To Reproduce**

1. Install eleventy-plugin-syntaxhighlight
2. paste this in a markdown file:
 ```twig
{% set test = 'test '% }
```
3. See error

**Expected behavior**
I would expect that everything in prism tags gets ignore and is not interpreted as actual code

**Environment:**
- MacOS Catalina 10.15.7
- Eleventy Version 6.14.4

**Comment by binyamin** [comment]
@jan-dh what templating language are you using (eg. liquid, njk)? Also, can we get a link to the problematic code?

**Comment by jan-dh** [comment]
Managed to solve this by switching from `.ejs` to `.njk`.  Issue was with `.ejs`, don't have the code live anywhere I'm afraid. Did start of from https://github.com/ixartz/Eleventy-Starter-Boilerplate

**Comment by zachleat** [comment]
For future folks, if the syntax you’re trying to highlight conflicts with the syntax of the parent template, many template languages have a `raw` output feature. Wrap your syntax highlighted block of code with the `raw` tag!

Liquid: https://liquidjs.com/tags/raw.html#sidebar
Nunjucks: https://mozilla.github.io/nunjucks/templating.html#raw
