### ISSUE TITLE
Failing to render JSON files

### ISSUE THREAD

**Issue by aarongustafson** [11ty/eleventy#1479]
**Describe the bug**
When I set up a Nunjucks template to generate a JSON file (using a `permalink` ending in ".json"), all I get is "[object Object]" in the render.

**To Reproduce**
Use the following template (`test.njk`):

```njk
---
permalink: test.json
---
{ "foo": "bar" } 
```

**Expected behavior**
I would expect this to be generated as a JSON file.

**Environment:**
- OS and Version: Mac
- Eleventy Version: 0.11.0

**Additional context**
* If you change the permalink to ".html", it renders fine
* If you change the template file extension to ".liquid" the output is still "[object Object]"
* I have tested other JSON-rendering plugins (like JSON feed) and they suffer from the same issue.

**Comment by aarongustafson** [comment]
Also tried an 11ty.js template:

```js
class Test {
  data() {
    return {
      permalink: "test.json"
    };
  }

  render(data) {
    return `{"foo": "bar"}`;
  }
}

module.exports = Test;
```

And, again, if I change the permalink to ".html" it’s fine.

**Comment by zachleat** [comment]
Sounds like you probably have a transform in your config file! Look for addTransform

**Comment by aarongustafson** [comment]
> Sounds like you probably have a transform in your config file! Look for addTransform

THANK YOU! I was beating my head against the wall with that one. It was the js minifier transform I picked up in the starter blog. Adding a quick & dirty exclusion for .json files fixed it a treat.

```js
  // Minify JS output
  eleventyConfig.addTransform("jsmin", function(content, outputPath) {
    if (outputPath.indexOf(".js") > -1 &&
        outputPath.indexOf(".json") < 0) {
      let minified = UglifyJS.minify(content);
      return minified;
    }
    return content;
  });
```

**Comment by zachleat** [comment]
Follow along at #1487 for that warning.
