### ISSUE TITLE
Universal Filters for Template Rendering

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#148]
Nunjucks example:
```
{% set myMarkdown %}
# My Header
{% endset %}
{{ myMarkdown | renderUsingMarkdown }}
```

Outputs: `<h1>My Header</h1>`

Would allow rendering of any supported template type inside of another template type.

* `renderUsingMarkdown`
* `renderUsingNunjucks`
* `renderUsingLiquid`
* `renderUsingHandlebars`
* etc

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

The enhancement backlog can be found here: https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+

**Comment by zachleat** [comment]
Maybe better with using the #13 Shortcodes feature. (Maybe both?)

**Comment by zachleat** [comment]
https://twitter.com/jmegs/status/1017469023263608832

**Comment by nhoizey** [comment]
You can wrap Markdown into a container `<div>` with https://github.com/markdown-it/markdown-it-container so maybe there's something to explore there…

**Comment by kleinfreund** [comment]
Universal shortcodes and filters are available since [v0.5.0](https://github.com/11ty/eleventy/releases/tag/v0.5.0). This issue can be removed from the enhancement backlog.

**Comment by zachleat** [comment]
@kleinfreund not quite! This would be a pack of cross-template shortcodes that would allow you to render any language in any other template.

So, for example—in a Nunjucks template I could render a markdown block. Or I could render a Nunjucks template in a Liquid template! 😱

**Comment by zachleat** [comment]
This request supports a long term vision to allow design systems or style guides to output multiple template language versions of components.

**Comment by jackysee** [comment]
A usecase here where I need to use the system markdown engine.

`.eleventy.js` configured both `eleventy-img` and `markdown-it` to render a markdown block.
```
const markdownIt = require('markdown-it');
const Image = require("@11ty/eleventy-img");

async function imageShortcode(src, alt="", classes="", title="") {
   let metadata = await Image('./src' + src, {
        widths: [null],
        formats: ["avif", "webp", "jpeg"],
        outputDir: './build/img/'
    });

    let imageAttributes = {
        alt: alt || '',
        loading: "lazy",
        decoding: "async",
    };
    return Image.generateHTML(metadata, imageAttributes);
}

let markdownLibrary = markdownIt({
        html: true,
        breaks: true,
        linkify: true,
        typographer: true,
    });
module.exports = function(config) {
    config.setLibrary("md", markdownLibrary);
    config.addNunjucksAsyncShortcode("image", imageShortcode);
    config.addPairedShortcode("markdown", (content, clazz) => {
        return `<div class="prose ${clazz || ''}">`+markdownLibrary.render(content) + '</div>';
    });
    return {
        markdownTemplateEngine: "njk",
    };
};

```

page.njk
```
Other non-markdown content....

{% markdown %}
##  Some title

Some content
{% image "/img/foo.png", "" %}

{% endmarkdown %}

Other non-markdown content....

```
Currently, this won't work because the `markdown` shortcode receives the content with nunjucks syntax inside and `markdown-it` would render broken. In normal md file it would work because the `markdownTemplateEngine` setting is applied so nunjucks syntax is transformed before markdown.

**Comment by maxogden** [comment]
I ended up doing something simple:

```
// to eleventy.js
const markdown = require("markdown-it")({
  html: true
})

  eleventyConfig.addFilter('markdown', value => {
    return `<div class="md-block">${markdown.render(value)}</div>`    
  })
```

and in my template:

```
{{ group.description | markdown | safe }}
```

**Comment by zachleat** [comment]
Shipping with 1.0.0-beta.6

Docs request at #2087 

Teased at https://twitter.com/zachleat/status/1459385129353293827

**Comment by zachleat** [comment]
Docs for this are deploying now to https://www.11ty.dev/docs/plugins/render/

**Comment by TigersWay** [comment]
Hi,
While I believe this new plugin is a treasure, which avoid tinkering with already installed packages (nunjucks, liquid, etc) there seems to be 2 troubles left with `renderFile`:
- "project root relative path" should probably be `dir.input` relative path (or even `dir.includes`)
- it doesn't "import" the data context of the template it's called from.
Thanks

**Comment by zachleat** [comment]
Related issue: https://github.com/11ty/eleventy/issues/2098

**Comment by zachleat** [comment]
Hey @TigersWay can you file those as a separate enhancement request? project root relative path is the safest/widest default, we can look at adding more lookup locations as an enhancement later

**Comment by TigersWay** [comment]
Hi @zachleat
- Just did it for the `root path` part while agreeing that "project root relative path is the safest/widest default" :smile:
- But don't get the "scoped data is kind of a feature". I am of course thinking the exact opposite :innocent:
Should I open a discussion?

**Comment by antiprism** [comment]
Hi

I am new to eleventy.

I am building pages from fragments of content, some of which are markdown (and using the markdown shortcode pair mentioned earlier in this issue), and using a nunjucks 'include'. I want sections in the layout to be conditional depending on whether a content fragment file exists or not.

To do this I wrote a shortcode to turn a src-relative path into an _include-relative path, and return an empty string if the file did not exist.
```
eleventyConfig.addShortcode("file_exists", function(fname) {
    full_fname = 'src/' + fname;
    fail = '';
    if (!fs.existsSync(full_fname) || !fs.statSync(full_fname).isFile())
       return fail;

    rel_fname = '../../' + fname;
    return rel_fname;
  });
```

In the template I can then test if the file exists and I have the correct path to include it (for a page called pagename.md, there are fragments called pagename_help.md, pagename_examples.md, etc)
```
  {% set src_inc_start = "docs/prog_sects/" + page.fileSlug %}
  <article class="programhelp">

  {% set inc_fname %}{% file_exists src_inc_start + "_help.md" %}{% endset %}
  {% if inc_fname %}
<h2>Help</h2>
     <div class="proghelp">
       <pre class="proghelp">
{% include inc_fname %}
       </pre>
     </div>
  {% endif %}
```

Is this a reasonable approach (I am not sure if the relative paths will always work), or is there already a facility in eleventy to acheive this?

Adrian.

**Comment by pdehaan** [comment]
@antiprism It might be better to move this to a new issue so we can keep things a bit clearer.
I've moved this issue into https://github.com/11ty/eleventy/issues/2119 and will reply there. ❤️
