### ISSUE TITLE
how do I link to tag pages in a post collection?

### ISSUE THREAD

**Issue by jrdnrich** [11ty/eleventy#1481]
Hello all
currently I have a for loop going for a collection posts  tagged music. How do I also display the tag in the front matter along with the link to the respective tag page?

This is what I have so far: 
`{% for post in collections.music -%}`
`<li><a href="{{ post.url }}" >{{ post.data.title }}, {{ post.data.date | dateformat }}</a></li>`
`Filed under:{{ post.data.tag }} ????`
`{% endfor -%}`

the goal is to have have each post that has tags link to the that tag page

example - Filed under: {{tag}} - (this is the code)
                  Filed under: music - (this is what is public )

I managed to already have the auto-generated tag pages via the quick tip and that works well see - https://www.11ty.dev/docs/quicktips/tag-pages/ (thanks for that documentation)

But how do I link to those tag pages in a post collection per post? 

The eleventy base-blog has this accomplished somehow by creating a postlist.njk file and creating a for loop for a collection tags with a tagURL see (https://github.com/11ty/eleventy-base-blog/blob/master/_includes/postslist.njk) 
but I don't understand how that tag collection was made and how the tagURL was created and can't get that to work from my copy/paste strategy so far ; ).

below is an example from the eleventy base-blog
` {% for tag in post.data.tags %}
      {%- if collections.tagList.indexOf(tag) != -1 -%}
      {% set tagUrl %}/tags/{{ tag }}/{% endset %}
      <a href="{{ tagUrl | url }}" class="post-tag">{{ tag }}</a>
      {%- endif -%}
    {% endfor %}`
    
Thanks in advance

**Comment by solution-loisir** [comment]
Hi @jrdnrich, the path to your tag page is under the `permalink` property of your paging file. If I followed correctly, you could do something like this:
```twig
{% for post in collections.music %}
  // Your code...
  <p>
    Filled under:
    {% for tag in post.data.tags %}
      <a href="/tags/{{ tag }}/"> {{ tag }} </a>
    {% endfor %}
  </p>
{% endfor %}
```
Here I assume that `post.data.tags` is an array. I didn't test this code, but I feel it should work. Let me know if there's a problem! 😊

**Comment by jrdnrich** [comment]
Hey @solution-loisir  Thanks so much for your help. It got me a step closer.
Now I'm trying to learn how to actually turn it into a working hyperlink it looks like it is simply spitting out the raw html within the for loop. 

I have the tag for loop within a postlist.njk in my _includes folder for layouts. It looks like this 
```

<ul>
{% for post in collections.post %}
<li><a href="{{ post.url }}">{{ post.data.title }}</a></li>
{% for tag in post.data.tags %}
      <a href="/tags/{{ tag }}"> {{ tag }} </a>
    {% endfor %}
{% endfor %}
</ul>
```
my hunch is do I need to add some sort of template .eleventy.js configuration to allow for html to be rendered in for loops?

not sure what you mean by having the post.data.tags in a array. I'm so so close. Thanks again for helping out. 

<img width="584" alt="Screen Shot 2020-12-15 at 23 44 25" src="https://user-images.githubusercontent.com/3683251/102306123-7d1d0a00-3f2f-11eb-8fbf-08f0fc7221d2.png">

**Comment by solution-loisir** [comment]
Ah, I guess your problem is html here. You try to nest an `a` element inside of `ul` which is not valid HTML. Only `li`is allowed inside `ul`. So maybe try something like that:
```twig
<ul>
{% for post in collections.post %}
<li><a href="{{ post.url }}">{{ post.data.title }}</a></li>
    {% for tag in post.data.tags %}
      <ul>
          <li><a href="/tags/{{ tag }}"> {{ tag }} </a></li>
      </ul>
    {% endfor %}
{% endfor %}
</ul>
```
Here I nested another `ul` just to make a clear relation to the title.

To answer your last question, the value of `tags` can be a single string or an array of string depending on the syntax you use and how many tags you have. Exemple:

*Single string syntax*
```twig
---
tags: post
---
```
*Array syntax*
```twig
---
tags:
  - post
---
// Or
---
tags: ['post']
---
```
I suspect that Eleventy might "normalize" `tags` as an array in the `collections`. Looping through a string will return every character which is probably not what you want. That being said, if everything works for you I wouldn't worry about that.

Hope this solves your problem. If so, don't forget to close the issue.

Best of luck!

**Comment by jrdnrich** [comment]
@solution-loisir You're right it was the invalid HTML, I'm now able to link to the 'post" tag but now I'm running into even more problems when I have more than one tag. Also I have no idea how to remove the 'post' tag from that tag list, because it will be repeated across every "post" collection. Which is probably beyond the scope of this issue.

At least you've shown me that the post.data.tags thing works which puts me in a good space to one day figure it out. 

Although I'm not all the way there, I'm closer than I was. Really hope someone does a good tag tutorial one day. It would be certainly appreciated. Shoot hopefully if I learn I can contribute to the open source tutorial/docs 

I'll close this out because the basic concept of linking to tags has been explained.

Thanks again!

**Comment by solution-loisir** [comment]
Feel free to open a new discussion as I think the maintainers [prefer that over education issues](https://github.com/11ty/eleventy/discussions/1452).

As a side note, you can filter tags out of the result display with an `if` statement (note that I placed the nested `ul` outside of the tag loop to provide a cleaner output).
```twig
<ul>
{% for post in collections.post %}
  <li><a href="{{ post.url }}">{{ post.data.title }}</a></li>
  <ul>
    {% for tag in post.data.tags %}
        {% if tag !== "post" %}
          <li><a href="/tags/{{ tag }}"> {{ tag }} </a></li>
        {% ending %}
    {% endfor %}
  </ul>
{% endfor %}
</ul>
```
Also, I think that this discussion on a different chanel about listing tags might interest you: https://community.piccalil.li/t/calling-all-eleventy-collections-automatically-in-separate-figures/275?u=mathieu-huot.

**Comment by jrdnrich** [comment]
Wow! Thank you so much for for the additional information.  I'll definitely check out the discussion board and give this a shot. Looks like I need to really learn this template language syntax. I was so stuck until you chimed in thanks again.
