### ISSUE TITLE
Remove benchmarking logs with quiet mode

### ISSUE THREAD

**Issue by nickcolley** [11ty/eleventy#1484]
When I use quiet mode I'd like to see no logs as I'm using Eleventy as part of a different command line application.

I'm not sure if this is already possible, let me know :)

**Comment by zachleat** [comment]
Oh interesting—do you rely on any of the existing console output? Where does this manifest? Can you give any more detail?

**Comment by nickcolley** [comment]
I'm building a little command line thing that takes your instagram data download and opens it up in your browser so you can check the contents.

(Not published yet)

```
npx instagram-download-viewer --input archive.zip
```

It's working well just would be nice to not output any Eleventy stuff, only thing that I cant silence is the benchmarking. Not a big deal though.

**Comment by zachleat** [comment]
After a quick review of the source code I believe this is how I intended it to work but it wasn’t functioning correctly. This fix will roll with 1.0.

**Comment by Ryuno-Ki** [comment]
> (Not published yet)

I'd be interested in hearing once this is live!
Would like to port it to [Nostalgia](https://nostalgia-dev.github.io/) then :-)

**Comment by nickcolley** [comment]
@zachleat thanks Zach appreciate it :)

The tool I smashed together is here:

https://github.com/nickcolley/instagram-archive-viewer

Warning: It's very 'smashed together' code :)
