### ISSUE TITLE
Timing of beforeBuild event seems to take place AFTER the data cascade has started

### ISSUE THREAD

**Issue by ethancalvo** [11ty/eleventy#1488]
It appears that the "beforeBuild" event actually happens after the data cascade starts. 

I execSync-ed an API call to a CMS in the beforeBuild handler.
The code did wait till all the data was downloaded before it continued with the build.

However, the newly downloaded data into the _data dir was ignored, and the site was built with the previous values that were in the _data dir before "beforeBuild" was called.

Running the same beforeBuild code as a npm script before running @11ty/eleventy worked as expected.

**Comment by zachleat** [comment]
Howdy! This is the same issue as #2207 and I’m hoping to coalesce over there.

Specifically this is my comment: https://github.com/11ty/eleventy/issues/2207#issuecomment-1041993296
