### ISSUE TITLE
Also look for eleventy.js or eleventy.config.js configuration files by default

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#1490]
Some complaints that .eleventy.js was a hidden file (and I agree). I’d like the option to look for one other non-hidden option, not sure if it should be `eleventy.js` or `eleventy.config.js`—opinions?

**Comment by nhoizey** [comment]
I would prefer `eleventy.config.js`.

**Comment by Ryuno-Ki** [comment]
I second @nhoizey.
`eleventy.config.js` is making it more clear, what the file is about.

**Comment by zachleat** [comment]
Oops this is a duplicate of #1029. We’ll use `eleventy.config.js`, thanks for the comments! 👍🏻
