### ISSUE TITLE
How to combine different data (different formats) in a page?

### ISSUE THREAD

**Issue by kuworking** [11ty/eleventy#1492]
Still understanding how 11ty works, what I'm trying to do is to build a single page with data from `markdown` and `javascript` (or `json`)

The way I'm trying to do this is to have a main index file in `markdown`, something like this

```md
---
layout: base.njk
---

<div>

{% include c1.md %}
{% include c2.md %}
{% include c3.md %}

{% include r1.js %}
{% include r2.js %}
{% include r3.js %}

</div>
```

In the `base.njk` layout, I define the html of the doc

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TITLE</title>
    <meta name="description" content="DESCRIPTION">
    <link rel="stylesheet" href="/css/styles.css">
  </head>
  <body>
      {{ content | safe }}
  </body>
</html>
```

With this I get the `md` files being included and parsed

-----------

Then the `r1.js` files are something like this

```js
module.exports = () => ({
  layout: "specific.njk",
  image: "01.jpg",
  title: "TITLE",
  data: 'examples',
});
```

Then, unknowing how to do this, I imagined that that `js` file could use the `specific.njk` layout to render the resulting html, and that that html would then be included in the file (not the case)

So how could I do this? Or is this entirely wrong and not the way I should structure my single web page?

*my `.eleventy.js` file

```js
module.exports = function(eleventyConfig) {
  eleventyConfig.addPassthroughCopy("img");
  eleventyConfig.addPassthroughCopy("css");

  return {
    templateFormats: [
      "md",
      "njk",
      "html",
      "liquid"
    ],

    markdownTemplateEngine: "liquid",
    htmlTemplateEngine: "njk",
    dataTemplateEngine: "njk",

    dir: {
      input: ".",
      includes: "_includes",
      data: "_data",
      output: "_site"
    }
  };
};
```

**Comment by kuworking** [comment]
As a workaround (there's something I'm missing here), I've used a filter to process my now `json` files

The r1.js file

```json
{
  "image": "01.jpg",
  "title": "TITLE",
  "data": "examples",
}
```

In `index.md`

```md
{% include c1.md %}
{% include c2.md %}
{% include c3.md %}

{% js %}
{% include r1.js %}
{% endjs %}
```

And in `.eleventy.js` file

```js
  eleventyConfig.addPairedShortcode("js", (content) => {
    const data = JSON.parse(content);
    return `
<div>
    <img src="/images/${data.image}.jpg"/>
  </div>
    `;
  });
```

**Comment by mubaraqwahab** [comment]
Hey.

If I understood you correctly, you want to include the images specified in the JS files in your markdown page.

In that case you can [use a data file](https://www.11ty.dev/docs/data-global/). Move the JS files into a `_data` directory in your input directory. The exported object of `r1.js` will be available to your templates as an `r1` object. Similarly, the export of `r2.js` will be available as an `r2` object in your templates.

You can now update your markdown file to something like this:

```md
​---
layout: base.njk
---

<div>

{% include c1.md %}
{% include c2.md %}
{% include c3.md %}

![R1 image alt text](r1.image)
![R2 image alt text](r2.image)
![R3 image alt text](r3.image)

</div>
```

You may also use JSON files instead of JavaScript files.

You might even merge the three files into one if they have the same schema:

```json
[
  ​{
    ​"​image​"​: ​"​01.jpg​"​,
    ​"​title​"​: ​"​TITLE​"​,
    ​"​data​"​: ​"​examples​"​,
  },
  {
    ​"​image​"​: ​"​02.jpg​"​,
    ​"​title​"​: ​"​TITLE​"​,
    ​"​data​"​: ​"​examples​"​,
  },
  {
    ​"​image​"​: ​"​03.jpg​"​,
    ​"​title​"​: ​"​TITLE​"​,
    ​"​data​"​: ​"​examples​"​,
  },
] 
```

And then loop over the array in your template.

The data file I've demonstrated is a global data file. Eleventy allows you [specify data for your templates in other ways](https://www.11ty.dev/docs/data/) too. 

Hope this helps 👋🏾

**Comment by kuworking** [comment]
It does help. thanks a lot :)

However, in your solution (that reading the docs I believe it seems the way to go) I just find it confusing in the sense that I have data in `md` and data in `json` (or another pure data format), but it looks like I should store them in different places (`_includes` and `_data_`)

And in my solution, I am storing the "format" in the `njk` template and in the `.eleventy.js` file, which is also confusing
 
There must be a way to combine data from different sources / formats in a more direct / simple way (?) (maybe not, I'm just still trying to adapt to 11ty)

*it doesn't store just an image link, but data without any kind of format

**Comment by mubaraqwahab** [comment]
> I have data in `md` and data in `json` (or another pure data format), but it looks like I should store them in different places (`_includes` and `_data_`)

I don't get what you mean by data in `md`. 

> And in my solution, I am storing the "format" in the `njk` template and in the `.eleventy.js` file, which is also confusing

Sorry I also don't get this. Do you mean the `templateFormats` array in the eleventy config? If so, how are you storing it in the `njk` template?

**Comment by kuworking** [comment]
Sorry, I'll try to explain myself better:

The way I am structuring my web page is to have an `index` page that I compose from different parts of data that are stored in different file types

So I have data in `markdown .md` files, and data in `.json` files

Out of the box I think I can't do this, all data should be in the same format, so then I have 2 options:

**Option 1:**

`index.md`

```
---
layout: base.njk
---

{% include part1.md %}
{% include part2.md %}

{% js %}
{%- include part3.json -%}
{% endjs %}
```

This allows me to store all the data in the same folder `_includes`, which is good since I store all data in the same place

```
|- _includes/part1.md
|- _includes/part2.md
|- _includes/part3.json
```

But, then I need to split the formatting of the document in two places, which is bad since conceptually I'd want to have all the formatting at the same place

Now I have the part regarding the `markdown` files in the layout  `base.njk`

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  </head>
  <body>

    <header>
    </header>

    <main>
      {{ content | safe }}
    </main>

    <footer></footer>
  </body>
</html>
```

And the part of the `json` files in the filter at `.eleventy.js`

```js
  eleventyConfig.addPairedShortcode("js", (content) => {
    const data = JSON.parse(content);
    return `
<div>
  <div class="image">
    <img src="/images/${data.image}"/>
  </div>

  <div class="title">${data.title}</div>

  <div class="info">
    <div>
      <span>${data.otherstuff}</span>
    </div>
  </div>

  <ul>
    ${data.steps.map((el) => `<li>${el}</li>`)}
  </ul>
</div>
    `;
  });
```

-------

Then I could also do what you suggest

**Option 2:**

```
---
layout: base.njk
---

{% include part1.md %}
{% include part2.md %}
```

And store the `.json` files in a different place

```
|- _includes/part1.md
|- _includes/part2.md
|- _data/part3.json
```

I personally don't like this, since I'm storing the same data in different places

But on the other hand, by doing this I can have all the formatting in the layout `base.njk`, since there I would have access to the global `_data` files

--------

So, the question is, does it make sense what I've just said? and, is there any option that I'm not thinking about?

**Comment by mubaraqwahab** [comment]
Hey, sorry for the late response.

I think I get you now. I'll explain by differentiating what is considered "data" in Eleventy from "include".

Includes are basically template fragments. Pieces of a template. You wouldn't expect such files to be rendered as separate pages. They go in an `_includes` directory, by default, in the input directory. They are usually included (i.e. dumped) _as is_ within another template. For example, you might have a Nunjucks navigation template `navigation.njk` as an include:

```njk
<nav>
  <a href="/">Home</a>
  <a href="/blog/">Blog</a>
</nav>
```

Then you could include it in other templates:

```njk
<!doctype html>
<html>
  ... 
  <body>
     {% include "navigation.njk" %}
     ... 
  </body>
</html>
```

Eleventy also expects to find layout files in the includes directory by default. Note that you can have include files in a different templating language than the including template. 

As for data files, you can think of them as for raw content that you would transform to use in your templates. Eleventy currently supports JavaScript modules and JSON files for data. Global data files live in a `_data` directory by default. Consider this JSON data file, `_data/post.json`:

```json
{
  "title": "Hello, world!", 
  "date": "2020-11-05",
  "body": "Hey there, this is my first post."
}
```

You wouldn't use this include this directory in your templates. Rather you'll transform it, perhaps by wrapping it in some markup:

```njk
<article>
  <h1>{{ post.title }}</h1>
  <time>{{ post.date | formatdate }}</time>
  <p>{{ post.body }}</p>
</article>
```

Notice that the data of `_data/post.json` is available as a `post` object in your templates. Also notice the use of a custom filter `formatdate`.

I hope this is clear.

**Comment by kuworking** [comment]
Great, then what happens is that when I'm using `include` to compose a component with different parts, I'm actually not using `include` the way it is meant to be used

So I guess that the question would be, can I place in `_data` content in `markdown` format? (I see that no, only `js` and `json` files)

So then, I infer that to do what I want to do as described above, is simply a use case not yet covered in Eleventy?

**Comment by mubaraqwahab** [comment]
> when I'm using `include` to compose a component with different parts, I'm actually not using `include` the way it is meant to be used

Yes, you're using it correctly. Check the navigation example above again.

**Comment by kuworking** [comment]
Then, would this description be accurate, understanding "format" as anything that is not raw data?

- `_include` when one want to organize/include data **with** format
- `_data` when one want to organize/include data **without** format

**Comment by mubaraqwahab** [comment]
Yeah typically. Includes are usually used directly in templates, data are transformed in some sense.

**Comment by kuworking** [comment]
Perfect, and thanks!
