### ISSUE TITLE
In LiquidJS include is now deprecated

### ISSUE THREAD

**Issue by stefanfrede** [11ty/eleventy#1493]
**Is your feature request related to a problem? Please describe.**
In favour of `render` `include` is now deprecated (https://liquidjs.com/tags/include.html).

**Describe the solution you'd like**
I would like to be able to use `render` instead of `include`.

**Comment by binyamin** [comment]
This will be fixed in v1.0.0, which you can test by running `npm install --save-dev 11ty/eleventy`
