### ISSUE TITLE
Nunjunks doesn't support tags with hyphen

### ISSUE THREAD

**Issue by bflorat** [11ty/eleventy#1497]
Hi !

Just had a hard time figuring out why my collections were empty using nunjunks templates (at the same time, the same liquid template was filled). My tag was `blog-tech`. It is fixed by using `blogtech` instead.

I feel that this should be emphazed in :
- https://www.11ty.dev/docs/pitfalls/
- https://www.11ty.dev/docs/collections/

(Sorry, I tried to make a PR but current eleventy Git repo .md docs only contain redirections now..)

BTW, thanks for this GREAT framework, it helps a lot.

**Comment by brewhousedigital** [comment]
Hey bflorat, a similar thing happens if you try that with a title too. you can just wrap those in double quotes like
`
---
layout: layouts/post-video.njk
title: "What about mRNA?"
tags:
- "science"
- "super-biology"
videoID: "T4-DMKNT7xI"
---
`

**Comment by zachleat** [comment]
It should be noted that Nunjucks does allow dashes, but via square bracket a la `collections["blog-tech"]`. This should work as expected.

**Comment by zachleat** [comment]
Related #567

**Comment by zachleat** [comment]
Docs on `collections` pushing here: https://www.11ty.dev/docs/collections/#a-note-about-using-in-tags
