### ISSUE TITLE
How can I call a custom function in njk template after adding it with addJavaScriptFunction?

### ISSUE THREAD

**Issue by gremo** [11ty/eleventy#1498]
I used `addJavaScriptFunction` to add the `hello` function:

```js
module.exports = eleventyConfig => {
  eleventyConfig.addJavaScriptFunction('hello', name => `Hello ${name}!`);

  return {
    dir: {
      input: "src",
      output: "dist"
    }
  }
};
```

How do I call it from my `index.njk`? `{{ hello('Marco') }}` doesn't work:

> Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering njk template ./src/index.njk
>`TemplateContentRenderError` was thrown
> (./src/index.njk) [Line 3, Column 8]
>  Error: Unable to call `hello`, which is undefined or falsey

**Comment by TheFrugalDeveloper** [comment]
The `addJavascriptFunction` method is actually used for adding methods to javascript or .11ty.js templates.

What you want is the `addNunjucksFilter` method or simply `addFilter`. You would then call it in nunjucks like:

```
{{ 'marco' | hello }}
```

**Comment by gremo** [comment]
Ok, it was not so clear from the documentation. Thanks!

**Comment by zachleat** [comment]
Also the new `addNunjucksGlobal` feature in 1.0, see https://github.com/11ty/eleventy/pull/1060

**Comment by hidegh** [comment]
@gremo I used this config:
```javascript
module.exports = function (eleventyConfig) {

    // extending with functions
    fncs = require('./src/scripts/fncs');

}
```
The script was like this:
```js
/**
 * This module is used to extend eleventy with custom functions that can then be used in the JS front matter.
 * 
 * Inside .eleventy.js config just add:
 *  const fncs = require('./src/scripts/global-fncs');
 *
 * Inside the template simply use it:
 * ---JS
 *  {
 *      title: `Test /${fncs.echo('123')}/`
 *  }
 * ---
 */
module.exports = {

    echo: function (params) {
        console.debug('echo: ', params)
        return params;
    }

}
```
Then in the template (EJS or NJK):
```
<%= fncs.echo("abcd") %>
```
