### ISSUE TITLE
Eleventy build throwing errors in Windows, but not in macOS

### ISSUE THREAD

**Issue by luntta** [11ty/eleventy#1500]
**Describe the bug**
When I build my eleventy site on a Windows machine, it throws errors, but doesn't throw those errors on macOS.

```
Error with passthrough copy: (more in DEBUG output)
> Having trouble copying './Repository/src/assets'

`TemplatePassthroughManagerCopyError` was thrown
> EPERM: operation not permitted, open 'C:\Users\USER\Repository\dist\assets\images\subfolder\some-image.png'

`Error` was thrown:
    Error: EPERM: operation not permitted, open 'C:\Users\USER\Repository\dist\assets\images\subfolder\some-image.png'
Error writing templates: (more in DEBUG output)
> Having trouble copying

`TemplateWriterWriteError` was thrown
> Having trouble copying './Repository/src/assets'

`TemplatePassthroughManagerCopyError` was thrown
> EPERM: operation not permitted, open 'C:\Users\USER\Repository\dist\assets\images\subfolder\some-image.png'

`Error` was thrown:
    Error: EPERM: operation not permitted, open 'C:\Users\USER\Repository\dist\assets\images\subfolder\some-image.png'
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble copying

`TemplateWriterWriteError` was thrown
> Having trouble copying './Repository/src/assets'

`TemplatePassthroughManagerCopyError` was thrown
> EPERM: operation not permitted, open 'C:\Users\USER\Repository\dist\assets\images\subfolder\some-image.png'

`Error` was thrown:
    Error: EPERM: operation not permitted, open 'C:\Users\USER\Repository\dist\assets\images\subfolder\some-image.png'
Copied 298 files / Wrote 0 files in 1.27 seconds (v0.11.1)
error Command failed with exit code 1.
```

**To Reproduce**

1. Run `eleventy` in repository on a Windows
2. See error

**Expected behavior**
Build should be successful on a Windows machine.

- OS and Version: Windows 10
- Eleventy Version: "@11ty/eleventy": "^0.11.1",

**Comment by Ryuno-Ki** [comment]
That's unrelated to Eleventy. I observe it with general `npm installs` as well. Try again until it works.

Researching on the web hints on checking directory permission or your antivirus.
Of course, you could also [mess with your system](https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/), but I can't tell you about the potential drawbacks this might have.

**Comment by luntta** [comment]
I managed to fix this specific issue by removing `eleventyConfig.setTemplateFormats([...])` from my Eleventy config. Turns out I don't need to set template formats in my use case.

**Comment by kylesloper** [comment]
I'm experiencing the same issue.

`Error writing templates: (more in DEBUG output) Error: EPERM: operation not permitted, open 'C:\Users\kyles\Desktop\moonface\_site\static\img\715580bf-9f2c-4e74-b0c5-7649f02ebfa1.webm' Writing _site/login/index.html from ./login.html. Writing _site/admin/index.html from ./admin/index.html. Writing _site/email/Confirmation/index.html from ./email/Confirmation.html. Writing _site/email/Email-change/index.html from ./email/Email-change.html. Writing _site/email/invite/index.html from ./email/invite.html. Writing _site/email/Recovery/index.html from ./email/Recovery.html. Error: EPERM: operation not permitted, open 'C:\Users\kyles\Desktop\moonface\_site\static\img\715580bf-9f2c-4e74-b0c5-7649f02ebfa1.webm' > Having trouble copying `TemplateWriterWriteError` was thrown > Having trouble copying './static/img/715580bf-9f2c-4e74-b0c5-7649f02ebfa1.webm' `TemplatePassthroughManagerCopyError` was thrown > EPERM: operation not permitted, open 'C:\Users\kyles\Desktop\moonface\_site\static\img\715580bf-9f2c-4e74-b0c5-7649f02ebfa1.webm' `Error` was thrown:`

**Comment by sschuldenzucker** [comment]
Same issue still here. Happens often for one particular image, only with `--serve`.
