### ISSUE TITLE
`include` does not find files with no file extension

### ISSUE THREAD

**Issue by jameshfisher** [11ty/eleventy#1504]
**To Reproduce**
Steps to reproduce the behavior are in this repo: https://github.com/jameshfisher/11ty-bug-include-no-file-extension

1. Create a file in `_includes` with no file extension, e.g. `_includes/Makefile`
2. In any template, add `{% include Makefile %}`
3. `npx eleventy`

**Expected behavior**
The string `{% include Makefile %}` is replaced with the contents of `_includes/Makefile`

**Actual behavior**
11ty tries to be clever and looks for a file called `Makefile.liquid`, which fails.
```
$ npx eleventy
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering liquid (and markdown) template ./page-about-make.md

`TemplateContentRenderError` was thrown
> ENOENT: Failed to lookup Makefile.liquid in: _includes,., file:./page-about-make.md, line:12

`RenderError` was thrown
> ENOENT: Failed to lookup Makefile.liquid in: _includes,.

`Error` was thrown:
    Error: ENOENT: Failed to lookup Makefile.liquid in: _includes,.
Wrote 0 files in 0.08 seconds (v0.11.1)
```

**Desired fix:**
If `include` fails to find `foobar.liquid`, it should fall back to just `foobar`. This seems backward compatible.

**Environment:**

- OS and Version: macOS 10.15.7
- Eleventy Version: 0.11.1

**Additional context**
I'm trying to convert my site (https://jameshfisher.com/) from Jekyll to 11ty. My expectations come from Jekyll's behavior. I'm typically using this behavior to include code files as part of blog posts. It's useful to maintain these code files outside of the blog post in order to execute them etc.

If the behavior is intentional, I'd appreciate any guidance on how to work around it.

**Comment by jameshfisher** [comment]
OK, it looks like this is liquidjs behavior, and this is the underlying issue: https://github.com/harttle/liquidjs/issues/41

**Comment by jameshfisher** [comment]
Following advice there, this works for me:

```js
module.exports = function(eleventyConfig) {
  eleventyConfig.setLiquidOptions({
    extname: ''
  });
};
```

However, I'll leave this issue open, because this workaround possibly breaks behavior for other users. Maintainers can decide whether this constitutes a bug.

**Comment by binyamin** [comment]
@zachleat any objection to changing the relevant default option?

https://github.com/11ty/eleventy/blob/1d7a96737912ff93f7d149a648419b84c9012a7e/src/Engines/Liquid.js#L48-L53

**Comment by zachleat** [comment]
This is probably too obtrusive for a defaults change, sorry!
