### ISSUE TITLE
Passthrough without processing the files?

### ISSUE THREAD

**Issue by svivian** [11ty/eleventy#1505]
Not sure if this is a bug, missing feature, or misunderstanding on my part, but I don't see a way to do passthrough file copy without 11ty processing html/md files. Using v0.11. I started off this this:

    eleventyConfig.addPassthroughCopy('static');

This worked fine for images/css in that folder, but when I added some HTML files (plain HTML I was using for demos), 11ty processed those files, added my site layout etc. So for example a file like `static/demos/example.html` ends up as two files:

- `_site/static/demos/example.html` (copied)
- `_site/static/demos/example/index.html` (with site design)

The only way I found to stop 11ty processing the files is to add the directory to `.eleventyignore`. But now it doesn't watch that directory for changes. It will copy the files when doing a straight build with `eleventy`, but on `eleventy --serve` it doesn't copy the files when they change. If I change one of my posts in another directory, it detects the change and does copy over the static files.

Is there something I'm missing?

**Comment by mubaraqwahab** [comment]
Eleventy considers `.html` files to be templates, so it will process them. You can disable this by specifying your own [template formats](https://www.11ty.dev/docs/config/#templateFormats) in your configuration file:

```js
module.exports = function(eleventy Config) {
  // ... 
  return {
    templateFormats: ["md", ...],
    // ... 
  }
}
```

It seems unusual that you would not consider HTML files as templates however. If what you want is for Eleventy to keep directory structure, i.e. `static/demos/example.html` should become `_site/static/demos/example.html` and not `_site/static/demos/example/index.html`, then you can use the special [`permalink`](https://www.11ty.dev/docs/permalinks/) front matter variable:

```html
---
permalink: static/demos/example.html`
---

<!doctype html>
... 
```

**Comment by Ryuno-Ki** [comment]
Note, that there are ways to automatically compute the value of `permalink` via Directory Data file (for example).

**Comment by svivian** [comment]
Thanks for the help. In the end I found another way to solve this - putting all my posts in a subfolder `src` and telling 11ty to use that as the input directory. Took me a while to get it working (needed to move all the templates too) but seems like a sensible approach to keep things separate.

Closing this as I think the passthrough is working as intended, even if unintuitive.
