### ISSUE TITLE
CSS issue in docs

### ISSUE THREAD

**Issue by cfjedimaster** [11ty/eleventy#1506]
While looking at this page (latest Edge browser, Windows), I saw this:

![image](https://user-images.githubusercontent.com/393660/98706435-743f8400-2344-11eb-8243-b2b72ae2c3d8.png)

The white block, when highlighted, reads: New in v0.7.0

**Comment by Ryuno-Ki** [comment]
A few things here:

1. Should be [filled against the website](https://github.com/11ty/11ty-website/issues) ;-)
2. Document in question is [ignores.md](https://github.com/11ty/11ty-website/blob/20261bd6d61253ffd75648209fafb7789701cadf/docs/ignores.md#ignore-template-files) / [Ignore Files](https://www.11ty.dev/docs/ignores/)
3. The CSS for `addedin` mini links does not consider dark mode, yet:

https://github.com/11ty/11ty-website/blob/8b0449ad0effe5ea76b24140019673b907b44c07/_includes/components/minilink.css#L73-L88

**Comment by cfjedimaster** [comment]
Dangit - I thought maybe I had the wrong repo. Will re-file, copy your notes, and close.
