### ISSUE TITLE
How can I run tests with Jest in Eleventy?

### ISSUE THREAD

**Issue by tannerdolby** [11ty/eleventy#1507]
I've started writing tests for client-side JS on my website using Jest and encountered some unexpected behavior. 

When I try exporting functions from a file using `module.exports` like demonstrated below,

```js
/**
 * Removes any whitespace or non-word characters from 
 * manually created id attributes for a sub heading.
 * 
 * @param {String} id The manually created id value from HTML element. 
 * @returns {String} The ID with unwanted characters removed.
 */
function removeChars(id) {
    const regex = new RegExp(/[\s\W]+/, "gm");
    return regex.test(id) ? id.replace(regex, " ") : id;
}

module.exports {
    removeChars,
    ...other functions
}
```

I get the following error: `Uncaught ReferenceError: module is not defined`. Why is this happening? I'm new to using Jest for testing client-side JS in Eleventy and may be overlooking something.

My immediate thoughts: 
- I know the Configuration API in `.eleventy.js` uses `module.exports = eleventyConfig => ..` which could be messing with my ability to export functions using `module.exports`?
- Maybe I should be using ava? 

Any feedback would be greatly appreciated!

**Comment by Ryuno-Ki** [comment]
`module` is used in a CommonJS format.
Could it be, that `export` works? (That would be ES Modules syntax)

**Comment by tannerdolby** [comment]
> Could it be, that export works? (That would be ES Modules syntax)

It still seems to be not working correctly. I tried using `export` as shown below but the test suite doesn't run as the functions `removeChars` and others aren't being exported. 

```js
module.export = {
    removeChars,
    someOtherFunc
}
```

I'm using the functions in a Jest test file `heading-highlight.test.js` with `require` 

```
const { removeChars, someOtherFunc } = require('../_includes/js/heading-highlight.js');
```

For the time being as my workaround, I'm commenting out the `module.exports` within the client-side scripts after I run my tests with Jest. This is not ideal, but I haven't found any similar issues so I'm grasping at straws. 

Would CommonJS need to be installed via npm to get rid of the reference error for `module`?

**Comment by Ryuno-Ki** [comment]
CommonJS is nothing you could install. It's a syntax / pattern you write modules in.

I was thinking about, whether `export = { removeChars, someOtherFunc }` do the trick. (No `module.`!)

**Comment by tannerdolby** [comment]
Ah, that makes more sense now. CommonJS defines the format for writing modules. Thanks for the clarification!

Without `module` and only using `export = { removeChars, someFunc }` , VS code throws an error `'export=' can only be used in a .ts file.`

Using `exports = { stuff }` doesn't show any syntax errors but when I run my tests the functions aren't exported throwing `TypeError: removeChars is not a function` in the tests output.

**Comment by Ryuno-Ki** [comment]
Okay, we're getting closer then!

What happens to this? (Note the leading `export` before `function`)

```js
export function removeChars(id) {
    const regex = new RegExp(/[\s\W]+/, "gm");
    return regex.test(id) ? id.replace(regex, " ") : id;
}
```

**Comment by tannerdolby** [comment]
We are getting closer!

With the leading `export` before `function`

```
export function removeChars(id) {}
```

it throws a new error within my test file

```
SyntaxError: Unexpected token export

    > 1 | const { uniqueID, removeChars }  = require("../_includes/js/heading-highlight");
```

The trace provided some links to Jest Configuration options that might be helpful. 

```
    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html
```

Maybe I need to enable ECMAScript Modules?

**Comment by Ryuno-Ki** [comment]
You do.
ES stands for ECMAScript.

**Comment by tannerdolby** [comment]
> ES modules are not supported in Node. Since Jest is running in Node, when it hits the import statement, we're getting that syntax error. 

Node.js treats JavaScript code as CommonJS modules by default, so I added a `type: "module"` field to `package.json` in order to define the module format as ES Module instead of CommonJS.

After having a look at [enabling ES Modules](https://jestjs.io/docs/en/ecmascript-modules), I created a `transform` key within `jest.config.js` and added `"\\.[jt]sx?$": "babel-jest"` to configue Jest for non-default behavior.

```
// jest.config.js
module.exports = {
    moduleFileExtensions: ["js"],
    transform: {
        "\\.[jt]sx?$": "babel-jest"
    },
    transformIgnorePatterns: ['<rootDir>/node_modules/']
}
```

I tried using ES module format with
```
// script.js
export function uniqueID(id) { 
    // code
}

// script.test.js
import { uniqueID } from "../path-to-file"`
```
but the tests weren't running because `uniqueID` wasn't being exported properly and therefore not available inside the test file.

Jest cannot handle the `import` behavior from ES modules even though I've specified in `package.json` the `type` field and updated the Jest config to what the docs recommend. I'm either missing something very important or the experimental support still needs some work.

The documentation for enabling ES Modules is a bit wonky. I was reading through a [similar issue - Vue.js and Jest](https://github.com/vuejs/vue-cli/issues/1584) which answered some of my questions. 

From [node.js - ecmascript modules](https://jestjs.io/docs/en/ecmascript-modules). Jest ships with experimental support for ECMAScript Modules (ESM). So this is a story for another day that I will continue tinkering with.

**Comment by tannerdolby** [comment]
Netlify Build Error when keeping `type: "module"` in `package.json`. I removed `type` and the site builds successfully. 

```
$ npm run build
10:39:18 PM: > 11ty-gallery@1.0.0 build /opt/build/repo
10:39:18 PM: > eleventy build
10:39:19 PM: Eleventy fatal error: (more in DEBUG output)
10:39:19 PM: > Error in your Eleventy config file '/opt/build/repo/.eleventy.js'.
10:39:19 PM: `EleventyConfigError` was thrown
10:39:19 PM: > Must use import to load ES Module: /opt/build/repo/.eleventy.js
10:39:19 PM: require() of ES modules is not supported.
10:39:19 PM: require() of /opt/build/repo/.eleventy.js from /opt/build/repo/node_modules/@11ty/eleventy/src/TemplateConfig.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
10:39:19 PM: Instead rename .eleventy.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /opt/build/repo/package.json.
```

**Comment by tannerdolby** [comment]
I'm still a bit stumped by this, my question remains: "How can I use import/export with ESM or require with CommonJS in an 11ty project within javascript files?"

@zachleat I'm sure there is something simple i'm missing, but if you could shed some light that would be much appreciated.

**Comment by coryasilva** [comment]
@tannerdolby 
You are on the right track, but you will need to add and configure babel...

I am bundling files in `./src/_scripts/` with `esbuild` and was able to get jest working with `esbuild-jest`.  Though, esbuild-jest is a bit jenky and does not report line numbers back correctly, *sigh*.  (I just refuse to install and configure webpack + babel.)  I also test eleventy filters and such by putting them into a `./util` directory and importing/require'ing them into `.eleventy.js`

```js
// npm install -D esbuild esbuild-jest
// ./jest.config.js
module.exports = async () => {
  return {
    verbose: true,
    transform: {
      '^.+\\.js?$': 'esbuild-jest',
    },
  }
}
```

**Comment by tannerdolby** [comment]
@coryasilva ah yes that makes sense, thank you so much for shedding some light on this.
