### ISSUE TITLE
Glob passthrough breaks watch in subdirectories

### ISSUE THREAD

**Issue by sschuldenzucker** [11ty/eleventy#1513]
**Describe the bug**
I keep each page in its own directory (so `post/my-post/my-post.md` contains the content for `/post/my-post/`) and images in that same directory that are passthrough-copied. The purpose of this is to keep a post together with its assets.

However, this breaks watch: Changes to the `*.md` files do not trigger a rebuild.

**To Reproduce**

1. Create a file `post/A/A.md` and the following config:
```
eleventyConfig.addPassthroughCopy("post/**/*.png")
```

2. Also create a file `post/B.md`.

3. Run `eleventy --serve`.

The site is generated & served correctly. We could check this via a browser at `localhost:8080/post/A`.

4. Modify and save `A.md`.

**Expected behavior**
Eleventy automatically re-generates the site when A is saved.

**Actual behavior**
Nothing happens.

When we save `B.md`, the site regenerates (including the changes to `A.md`).

**Environment:**

- Windows 10
- Eleventy 0.11.1

**Remarks**

- It is not important whether `post/A/` in our example actually contains any files that are matched by the glob.
- This only happens for files in subdirectories. I.e., the problem doesn't occur for `B.md` above.
- Removing the `addPassthroughCopy(...)` line eliminates the problem.

**Comment by Snapstromegon** [comment]
I just want to add, that I just stumbled upon the exact same issue.

My usecase is building components with different frontend frameworks and render the results for each component to an asset folder specific for that component imlementation.

I have these lines in my eleventy config:
```js
eleventyConfig.addWatchTarget("src/**/assets/**");
eleventyConfig.addPassthroughCopy("src/**/assets/**");
```

If I know (with a build script) change/replace the content of the assets folder, no new build is triggered by eleventy.

**Comment by zachleat** [comment]
Cross linking https://github.com/11ty/eleventy/issues/893 which may be relevant

**Comment by zachleat** [comment]
I tested this on both 1.x and 2.x and both are operating as expected

**Comment by zachleat** [comment]
I think this one may have been fixed along the way. Closing for now but please let me know if you see further issues!
