### ISSUE TITLE
Eleventy fails in Windows 10 with a starter with ELEVENTY_EXPERIMENTAL (works in WSL2 Ubuntu)

### ISSUE THREAD

**Issue by kuworking** [11ty/eleventy#1515]
I've opened an issue to the repo itself (https://github.com/signalkuppe/eleventy-react/issues/1), but since there are no errors but the process simply exits, I think it may actually be a problem of `11ty`

To reproduce it, simply clone (https://github.com/signalkuppe/eleventy-react/) and try to run the repo under a W10 environment, using `cross-env`

```
    "dev": "cross-env ELEVENTY_EXPERIMENTAL=true eleventy --serve",
    "build": "cross-env ELEVENTY_EXPERIMENTAL=true eleventy",
```

Eleventy doesn't complain about anything, but the process simply exits

```
PS C:\...\eleventy-react> npm run dev

> eleventy-react@0.2.2 dev C:\...\eleventy-react
> cross-env ELEVENTY_EXPERIMENTAL=true eleventy --serve

Warning: Configuration API `addExtension` is an experimental Eleventy feature with an unstable API. Be careful!
PS C:\...\eleventy-react> 
```

And when using 

```
    "debug": "cross-env DEBUG=Eleventy* ELEVENTY_EXPERIMENTAL=true eleventy --serve",
```

I can't see any clue of what's wrong

----------------------------------------------------

**EDIT:**
I have just cloned and successfully run the repo in a Linux environment with W10-WSL2, so definitively this is something with Windows

**Comment by zachleat** [comment]
Sorry for the late reply here—going to close this as stale since we don’t require ELEVENTY_EXPERIMENTAL any more and 1.0 is stable released supporting the `addExtension` API
