### ISSUE TITLE
Duplicate permalink with differing tag capitalization

### ISSUE THREAD

**Issue by ItaiAxelrad** [11ty/eleventy#1516]
I use Netlify's CMS to let users create posts with `tags` being a list widget that the author can populate. My issue arises from the potential for duplicate tags with varied capitalization - for example `blog` vs `Blog`.  

I use the following computed fronmatter for generating permalinks in my tag.njk template (similar to [eleventy-base-blog](https://github.com/11ty/eleventy-base-blog/blob/master/tags.njk) but with the added slug filter)

`permalink: /tags/{{ tag | slug }}/`

Which results in the following error

```
Output conflict: multiple input files are writing to `_site/tags/blog/index.html`. Use distinct `permalink` values to resolve this conflict.
``` 

Any thoughts on how to resolve this issue?

**Comment by binyamin** [comment]
without seeing the input data, it's very difficult to help you. Do you have a repository we can look at?

**Comment by Ryuno-Ki** [comment]
Related to https://github.com/11ty/eleventy/discussions/1461 ?

**Comment by ItaiAxelrad** [comment]
@binyamin this issue can be replicated using the official [eleventy-base-blog](https://github.com/11ty/eleventy-base-blog). Just throw a couple of tags with differing capitalization in there.

@Ryuno-Ki yes, very related haha. That is the exact same issue.

**Comment by ItaiAxelrad** [comment]
I'll close the issue and monitor [#1461](https://github.com/11ty/eleventy/discussions/1461). Thanks!
