### ISSUE TITLE
Docs for addNunjucksGlobal

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#1517]
https://github.com/11ty/eleventy/pull/1060

**Comment by hidegh** [comment]
@zachleat This is a nice to have (although a lot of cases can be solved differently).

Questions related to this:
1. any plan to do some @next releases on NPM
2. any chance to make some JS available in the **same standardized manner** in all the possible scenarios:
- JS front matter
- NJK/EJS/liquid templates
3. make also filter functions available to be called directly in those engines (if function call is supported, but filters not - e.g. EJS 2.x.x)

I do realize that in case of 2nd req. there are some **limitations** per template language (like the removal of filters in EJS from 2.x.x. onwards), but in most cases we're talking about a JavaScript object, which could be exposed in a standard way (not just via addNunjucksGlobal) and then at least there would be access to it, in case the new version of the template engine allows it's usage. See also: https://github.com/11ty/eleventy/issues/1652

Other frameworks do expose a ```site``` object (for additional context) (nice "namespacing") - this is also what I missed (maybe just missing docs).

**Comment by Ryuno-Ki** [comment]
FWIW, looks like @pdehaan spotted a canary release:
https://github.com/11ty/eleventy/issues/1654#issuecomment-783053286

**Comment by pdehaan** [comment]
> 1. any plan to do some `@next` releases on NPM

11ty currently has a "canary" tag for the v1.0.0 release:

```sh
$ npm info @11ty/eleventy dist-tags

{ latest: '0.11.1', beta: '0.11.0-beta.4', canary: '1.0.0-canary.9' }
```

You can install it via <kbd>npm i @11ty/eleventy@canary</kbd>; or, if you're feeling dangerous, you can install via GitHub directly using <kbd>npm i github:11ty/eleventy</kbd> to get the latest commits.
