### ISSUE TITLE
Add CSS pass-through example to docs (no inlining)

### ISSUE THREAD

**Issue by mtclmn** [11ty/eleventy#153]
I have my templates setup and outputting to the output folder, `_site` in my case.
However, the CSS files in my root don't seem to get passed through.

I saw the "Quick Tip" for inlining CSS (https://www.11ty.io/docs/quicktips/inline-css/), but If I didn't want to do that, is there a way to pass through the CSS to the output folder?

**Comment by mtclmn** [comment]
Ah, I see — looks like it's `.addPassthroughCopy()`.
I used:
```
module.exports = function(eleventyConfig) {
  // file is: assets/style.css - so pass it the assets folder
  eleventyConfig.addPassthroughCopy("assets");  
};
```
Could be helpful to put CSS as an example in passthrough docs? Or maybe an example/quick tip of how to pass through CSS.

Thanks Zach - enjoying 11ty!

**Comment by zachleat** [comment]
Ah—thanks!!

You can also add `"css"` to your templateFormats if you’ve also set `passthroughFileCopy: true`.

```js
// .eleventy.js
module.exports = {
  templateFormats: [
    "md",
    "css"
  ],
  passthroughFileCopy: true
};
```

https://www.11ty.io/docs/copy/

**Comment by zachleat** [comment]
I’ve switched the default example on https://v0-5-0.11ty.io/docs/copy/ to use css instead of png, since I think that’s a higher value example—thanks!

**Comment by zachleat** [comment]
Also added https://v0-5-0.11ty.io/docs/quicktips/concatenate/ inspired by this issue

**Comment by mtclmn** [comment]
Awesome - I think that will be helpful!
