### ISSUE TITLE
Problem writing mapping key at line 10, column -27

### ISSUE THREAD

**Issue by lucabol** [11ty/eleventy#1530]
Hi, I am porting my blog from Hugo and getting this error. I have many posts, and some of them have a `categories` YAML value, while others don't. The error doesn't tell me which file has the problem (assuming that one of my files does). The word 'template'

You can clone this repo to repro: https://github.com/lucabol/MyBlog2

Here is a partial DEBUG output:

Eleventy:TemplatePassthroughManager TemplatePassthrough copy finished. Current count: 0 +4s
  Eleventy:EleventyErrorHandler Problem writing Eleventy templates: +0ms
  Eleventy:EleventyErrorHandler duplicated mapping key at line 10, column -27:
  Eleventy:EleventyErrorHandler     categories:
  Eleventy:EleventyErrorHandler     ^
  Eleventy:EleventyErrorHandler
  Eleventy:EleventyErrorHandler `YAMLException` was thrown: +1ms
  Eleventy:EleventyErrorHandler (error stack): YAMLException: duplicated mapping key at line 10, column -27:
  Eleventy:EleventyErrorHandler     categories:
  Eleventy:EleventyErrorHandler     ^
  Eleventy:EleventyErrorHandler     at generateError (C:\dev\MyBlog2\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
  Eleventy:EleventyErrorHandler     at throwError (C:\dev\MyBlog2\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
  Eleventy:EleventyErrorHandler     at storeMappingPair (C:\dev\MyBlog2\node_modules\js-yaml\lib\js-yaml\loader.js:335:7)
  Eleventy:EleventyErrorHandler     at readBlockMapping (C:\dev\MyBlog2\node_modules\js-yaml\lib\js-yaml\loader.js:1098:9)
  Eleventy:EleventyErrorHandler     at composeNode (C:\dev\MyBlog2\node_modules\js-yaml\lib\js-yaml\loader.js:1359:12)
  Eleventy:EleventyErrorHandler     at readDocument (C:\dev\MyBlog2\node_modules\js-yaml\lib\js-yaml\loader.js:1525:3)
  Eleventy:EleventyErrorHandler     at loadDocuments (C:\dev\MyBlog2\node_modules\js-yaml\lib\js-yaml\loader.js:1588:5)
  Eleventy:EleventyErrorHandler     at load (C:\dev\MyBlog2\node_modules\js-yaml\lib\js-yaml\loader.js:1614:19)
  Eleventy:EleventyErrorHandler     at Object.safeLoad (C:\dev\MyBlog2\node_modules\js-yaml\lib\js-yaml\loader.js:1637:10)
  Eleventy:EleventyErrorHandler     at module.exports (C:\dev\MyBlog2\node_modules\gray-matter\lib\parse.js:12:17) +21ms
  Eleventy:Benchmark Benchmark (Aggregate): Searching the file system took 21ms (0.5%, called 2×, 10.4ms each) +0ms

**Comment by pdehaan** [comment]
Fun!
Per the debug output:

> Eleventy:EleventyErrorHandler (error stack): YAMLException: duplicated mapping key at line 10, column -27:
Eleventy:EleventyErrorHandler categories:

So if we know (or assume) that we have a duplicate "categories:" key in the front matter of one of our ~142 blog posts, we can do a bit of grep to narrow it down:

```sh
# Show all instances of "categories:" string (and their respective line numbers) in our git committed files,
# then filter out to only show results that are on line 10.
git grep -n "categories:" | grep ":10:"

posts/2012-06-18-and-now-andy-has-a-blog.md:10:categories:
posts/2019-01-21-stopping-garbage-collection-in-net-core-3-0-part-ii.md:10:categories:
```

So from 142 files down to 2 likely places.
The problem seems to be in https://raw.githubusercontent.com/lucabol/MyBlog2/main/posts/2012-06-18-and-now-andy-has-a-blog.md

```yaml
categories:
  - C
categories:
  - Miscellanea
```

If I modify that to remove the duplicate key, the blog seems to build as expected:

```yaml
categories:
  - C
  - Miscellanea
```

> Wrote 142 files in 0.55 seconds (3.9ms each, v0.11.1)

**Comment by lucabol** [comment]
And cheers to you, Peter!

**Comment by Ryuno-Ki** [comment]
@pdehaan I'm impressed!
Today I learned a new thing. Thanks!
