### ISSUE TITLE
Extra frontmatter date variable off by one day; page.date is fine

### ISSUE THREAD

**Issue by jeffchiou** [11ty/eleventy#1531]
**Describe the bug**
For my posts I have a datePosted variable in the frontmatter from which I pull the post date. I also use page.date to track my last modified date. page.date.toUTCString() works great (technically I put toUTCString() in a nunjucks filter), but datePosted.toUTCString() is still one day off.

**To Reproduce**

> a-post.md
```yaml
---
datePosted: 2020-11-25
date: "Last Modified"
---
```
> njk-date-filter.js
```javascript
function dayjsFilter(date, format = 'YYYY-MM-DD') {
  return dayjs(date.toUTCString()).format(format)
}
```
> some-layout.njk
```njk
{{ datePosted | formatDate }}
{{ page.date | formatDate }}
```
**Output**
2020-11-24
2020-11-25

**Expected behavior**
2020-11-25
2020-11-25

**Environment:**

- OS and Version: Windows 10
- Eleventy Version 0.11.0

**Comment by jeffchiou** [comment]
A workaround is just storing the date as a string. i.e.:
```yaml
datePosted: "2020-11-25"
```

**Comment by Ryuno-Ki** [comment]
Does this behaviour also appear, when you run `dayjs` in a REPL?
What type is indicated for the `date` argument of your filter? (I'd assume also a string).

**Comment by jeffchiou** [comment]
Ah you're right, I think the normal `page.date` working correctly threw me off of investigating dayjs more. I looked into it and the fix is to require the timezone plugin for dayjs at https://day.js.org/docs/en/plugin/timezone

Then you can run `dayjs(date).tz('utc')` and things work correctly.

Thank you!
