### ISSUE TITLE
For discussion: remove `--passthroughall` feature

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#1532]
Note the huge caveats on https://www.11ty.dev/docs/copy/#passthrough-all-content

**Comment by Ryuno-Ki** [comment]
Perhaps worth to also ask, who's using it at all.

I did some digging. The feature was introduced by https://github.com/11ty/eleventy/commit/34276f57d69bf121a32aab21bbaeff273adc69de for #162.

@alexgleason Do you still have that use case?

**Comment by montanaflynn** [comment]
I really don't understand the risks? I want to allow various files of different extensions. If I enable pass through all I just have to be mindful about what's in my content folder which is just markdown and public assets anyways.

**Comment by zachleat** [comment]
Closing!
