### ISSUE TITLE
Easy way to access global data in a page

### ISSUE THREAD

**Issue by Zearin** [11ty/eleventy#1535]
## Is your feature request related to a problem? Please describe.

This feature request was born out of #1526.  

My original post:

>I just want to print out all the data to look at how it’s structured.
> 
> I basically want to do the equivalent of a console.dir(…) or console.inspect(…), but print the data within a `<pre>…</pre>` element.
> 
> Can I do this?
> 
> How?

(To be clear, I am referring to [global data][2].)
 
An obvious solution was nowhere to be found. But thanks to some help from @pdehaan and @Ryuno-Ki, I was about to figure out that a page can access all global data in 2 steps.

1. Create a `debug` filter in Eleventy’s config (@pdehaan’s [example is here][1])
2. Use the `debug` filter like this: `{{ collections.all[0].template.templateData.globalData | debug }}`

This works…but it was tedious to pull off.  And I would not have figured it out if it weren’t for the help I received in #1526.  

Being able to “just look at” data is an important part of discovery, learning, and adoption of new tools.  For example, now that I know I can do this, I plan to stick with Eleventy a little longer to see what I can do.

## Describe the solution you’d like

I guess I would just like an easy-access variable available to do this.  

* perhaps called `globalData`
* perhaps _defaulting_ to `globalData`, but allowing the user to configure a different name
* perhaps something else? 

**Describe alternatives you've considered**

N/A

[1]: https://github.com/pdehaan/11ty-1526/blob/d167c3cfd8ae3d7f9a49c73cc78d32aca3e70d97/.eleventy.js#L4
[2]: https://www.11ty.dev/docs/data-global/
----

EDIT: Put my writing under the correct questions 👅 
EDIT: Clarify that I mean global data, rather than front matter

**Comment by Zearin** [comment]
@zachleat Could this be part of the Eleventy 1.0 milestone?

**Comment by zachleat** [comment]
Howdy! I think the best way forward is over at #1919, can you upvote and subscribe over there?
