### ISSUE TITLE
Allow opt-out of template/directory data files

### ISSUE THREAD

**Issue by Zearin** [11ty/eleventy#1543]
## Is your feature request related to a problem? Please describe.

I'm porting a personal project that makes heavy use of a data directory.  In my old setup, I had already arranged my data into a hierarchical set of folders and files. I already had the data hierarchy exactly as I wanted it by simply importing (or `require`-ing) the top-level `index.js` file.

Although I think Eleventy’s built-in feature to construct the data hierarchy based on nested folders is a cool feature, I want to turn it off for this particular project.  The data is now bloated with lots and lots of duplicates, and the hierarchy I had previously constructed now requires me to insert a lot of  `.index.` everywhere (`«something».index.«something»`), because I used the standard practice of using index files as the default place for importing data in each subdirectory.  

## Describe the solution you'd like

I want a boolean option in Eleventy’s configuration that allows me to turn off Eleventy’s automatic data-hierarchy feature.

**Comment by zachleat** [comment]
Specifically, you mean this feature right? https://www.11ty.dev/docs/data-template-dir/

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
This is implemented with #1699, pending docs issue #2681

2.0.0-canary.19

Use `dataFileSuffixes: []` to opt-out.
