### ISSUE TITLE
Browsersync without the snippet injection

### ISSUE THREAD

**Issue by pierredewilde** [11ty/eleventy#1549]
**Is your feature request related to a problem? Please describe.**

`eleventy --serve` watches automagically:
```
     --serve
       Run web server on --port (default 8080) and watch them too
```

Therefore, BrowserSync is always added in HTML files:
```
<script id="__bs_script__">//<![CDATA[
--
  | document.write("<script async src='/browser-sync/browser-sync-client.js?v=2.26.13'><\/script>".replace("HOST", location.hostname));
  | //]]></script>
```
This is the normal behavior for hot reloading.
This is also a drawback when testing performance with eg Chrome DevTools Lighthouse.

A possible workaround is to run another HTTP server on _site directory eg https://github.com/lwsjs/local-web-server
```
$ eleventy
$ cd _site
$ ws --http2 --compress
```

**Describe the solution you'd like**
`eleventy --serve --nowatch` will serve static pages without altering pages eg without adding BrowserSync support.

**Describe alternatives you've considered**
`eleventy --serve _site` will serve static pages located in ./_site without altering pages.
`eleventy --serve <path>` will serve static pages located in <path> without altering pages.

**Additional context**
-

**Comment by hendotcat** [comment]
Good news! You can already kind of achieve this for yourself by writing some code in your `.eleventy.js`. Let's reimagine your `--nowatch` flag as an environment variable called `NOWATCH` which you'd pass to Eleventy like `NOWATCH=true eleventy --serve`. You could detect that in `.eleventy.js` and turn off the snippet yourself like this:

```js
module.exports = function(eleventyConfig) {
  if (process.env.NOWATCH) {
    eleventyConfig.setBrowserSyncConfig({
      snippetOptions: {
        blacklist: ["**/*.html"],
      }
    })
  }
}
```

Crossing my fingers that I've understood your request properly and found you a way to get Eleventy to already do what you want!

**Comment by pierredewilde** [comment]
Not yet tested but seems a good workaround. Thanks.

**Comment by zachleat** [comment]
Howdy, here’s another way: https://twitter.com/eleven_ty/status/1402360471634731009

Also in the newest versions of browsersync they shipped `snippet: false` https://github.com/BrowserSync/browser-sync/issues/1882
