### ISSUE TITLE
Undeletable folder as file 

### ISSUE THREAD

**Issue by clavierCreatif** [11ty/eleventy#1550]
Hello, I use permalink in front matter, I created a folder nammed "com.test.".
Windows consider it as a file and when i try to delete this folder, Windows say me this file is not found (but it's folder).
How can I delete this folder please ? 

**To Reproduce**

1. Write in front matter :
---
permalink: "/com.test./README.md"
---

**Screenshots**

![image](https://user-images.githubusercontent.com/20588938/101988428-ceac6700-3c99-11eb-87ff-8ae32ff29954.png)

**Environment:**

- OS and Version: Windows 10
- Version: 0.11.1

**Comment by Ryuno-Ki** [comment]
Hm, do you have some kind of command line at hand?
As far as I know, Windows still comes with CMD (perhaps even PowerShell).
Can you try to delete the file that way? (I'm on a Linux machine, but from work, I recall, the command being `rmdir` for folders and `del` for files).

**Comment by clavierCreatif** [comment]
Thank you for your answer :)
I tried rmdir and del command but Windows say me : file not found (but it's a folder).
I just solved, I move all my files in another partition :/ and I remove partition with the problematic folder.
Not bad, not good :)

**Comment by Ryuno-Ki** [comment]
Would you mind closing this issue then?
