### ISSUE TITLE
code fences converted to single line

### ISSUE THREAD

**Issue by mvolkmann** [11ty/eleventy#1553]
**Describe the bug**
At some point all my code fences for example code in my blog site got converted to single lines.
I probably did something to cause this, but I can't imagine what.

**Expected behavior**
Newlines inside code fences should be retained.

**Screenshots**
For an example, click the "Functions" link at https://mvolkmann.github.io/blog/topics/#/blog/python/python-compared-to-js/.

**Environment:**

- OS and Version: Mac 10.15.7
- Eleventy Version: 0.11.1

**Comment by Ryuno-Ki** [comment]
Duplicate of https://github.com/11ty/11ty-website/issues/877 ?

**Comment by mvolkmann** [comment]
OMG, it was the "axe - Web Accessibility Testing" extension that causes this! I trashed that right away and now everything is working fine. I would have never figured this out on my own. Thank you so much @Ryuno-Ki!

**Comment by Ryuno-Ki** [comment]
*defers the kudos to @tannerdolby, who figured that out
