### ISSUE TITLE
Pagination links break when using eleventyComputed to write permalinks in *.11ty.js templates

### ISSUE THREAD

**Issue by reubenlillie** [11ty/eleventy#1555]
**Describe the bug**
Using `eleventyComputed` to write permalinks in *.11ty.js templates, as described in #1076, does not produce the expected pagination links.

**To Reproduce**

1. :clipboard: Clone the `eleventy-dot-js-blog` starter project to a soon-to-be-bug-ridden project directory and install node packages locally:

```cli
git clone git@gitlab.com:reubenlillie/eleventy-dot-js-blog.git buggy-eleventy-dot-js-blog
cd buggy-eleventy-dot-js-blog
npm install 
```

2. Test that the local development environment is working. Specifically, :eyes: note the following paginated output from `./content/pages/archive.md`:

```cli
npx eleventy --serve
…
Writing _site/blog/index.html from ./content/pages/archive.md.
Writing _site/blog/page-1/index.html from ./content/pages/archive.md.
…
```
_Also, notice how these same pagination navigation links appear in the markup when browsing_ :earth_americas: http://localhost:8080/blog/. The Markdown/Liquid–Nunjucks front matter permalinks work. :ok_hand:

3. :memo: Rename `./content/pages/archive.md` from Markdown to a JavaScript template and translate its content:

```cli
mv content/pages/archive.md content/pages/archive.11ty.js
vim content/pages/archive.11ty.js
```
**NB: code updated on January 19, 2021 since the starter kit now supports ES modules**

```js
// JavaScript-ified ./content/pages/archive.11ty.js
/**
 * @file Defines the chained layout for the archive page
 * @see {@link https://www.11ty.dev/docs/layouts/#layout-chaining Layout chaining in 11ty}
 */

/**
 * Acts as front matter in JavaScript templates
 * @see {@link https://www.11ty.dev/docs/languages/javascript/#optional-data-method Optional `data` in JavaScript templates in 11ty}
 */
export var data = {
  title: '📔 A Blog for the Ages',
  navTitle: '📔 Blog',
  tags: 'nav',
  weight: 3,
  layout: 'layouts/archive',
  templateEngineOverride: '11ty.js',
  pagination: {
    data: 'collections.posts',
    size: 3,
    alias: 'posts',
    reverse: true,
  },
  eleventyComputed: {
    permalink: data => `${data.site[data.locale].postsArchive.url }/${data.pagination.pageNumber > 0
      ? `page-${data.pagination.pageNumber}/` 
      : ''}index.html`
  }
}

/**
 * The archive page content
 * @method
 * @name render()
 * @param {Object} data 11ty’s data object
 * @return {String} The rendered template
 */
export function render(data) {
  return `<!-- ${data.page.inputPath} -->
This is your blog landing page. 🛬`
}
```

4. Run :test_tube: `npx eleventy --serve` again. This time, notice how the output files in the command line interface remain unchanged :smiley:. But, … also notice how in the browser, the pagination navigation links now render as `http://localhost:8080/{{page.fileSlug}}/` :bug:. The proper routes are output by the new JavaScript template, but the pagination navigation is different. 

5. :thinking: These strange pagination navigation links resemble the permalink rules in `./content/pages/pages.11tydata.js`. So, it would seem like the logical next step is to update those to `eleventyComputed` syntax too :man_shrugging::

```js
// Updated ./content/pages/pages.11tydata.js
/**
 * @file Contains data common to all pages, to reduce repetition
 */

/**
 * Directory data module for pages
 * @module content/pages
 * @see {@link https://www.11ty.dev/docs/data-template-dir/ Template and directory data files in 11ty}
 * @see {@link  https://www.11ty.dev/docs/permalinks/ Permalinks in 11ty}
 */
module.exports = {
  layout: 'layouts/page',
  // Note: The permalink value uses Nunjucks/Liquid syntax;
  // a future version of 11ty may allow for JavaScript template literals
  // permalink: '/{{page.fileSlug}}/index.html',
  // Comment out this line ⬆️; add this basically equivalent eleventyComputed object ⬇️
  eleventyComputed: {
    permalink: data => `/${data.page.fileSlug}/index.html`
  },
  tags: [
    'pages'
  ]
}
```
6. Except, this time, if you run `npx eleventy --serve`, notice how the output has changed :beetle::

```cli
…
Writing _site/blog/index.html from ./content/pages/archive.11ty.js. 🤤
…
Writing _site/blog/page-1/1/index.html from ./content/pages/archive.11ty.js. 🤨
…
```
And, in the markup, the pagination navigation links are now `http://localhost:8080/content/pages/archive/` and `http://localhost:8080/content/pages/archive/1/` accordingly, which look more like real pages, but they don’t exist in the output :ant:. That is, both the output and the pagination navigation links are broken after basically exchanging :currency_exchange: Markdown/Liquid–Nunjucks for Eleventy-topped vanilla JavaScript.

**Expected behavior**
The output and pagination navigation links should match, and `eleventyComputed` should continue to be unquestionably awesome.

**Environment:**

- OS and Version: Ubuntu 20.04.1 LTS
- Eleventy Version: v0.11.1

**Additional context**

The pagination navigation is generated from `./_includes/shortcodes/pagination-nav.js`. It’s a built-out version of what I prepared for the [Eleventy docs](https://www.11ty.dev/docs/pagination/nav/). If you `console.log(data.pagination)` somewhere in the return statement for any of steps 3–6 above, you can verify the mutations to that object. But I’ve got no clue why the permalinks are behaving this way with pagination.

**Comment by reubenlillie** [comment]
So, this is hardly a solution, but a “working” set of pagination navigation links can be created to match those built by Eleventy:

```js
// Modified data object in content/pages/blog.11ty.js
export var data {
  eleventyComputed: {
    permalink: data => `${data.site[data.locale].postsArchive.url}/index.html`
  }
}
```

I happened upon this wrench by accident. I was testing to see what would happen if I removed the ternary operator for the `page-` counter. It appears the `/1/` in `_site/blog/1/index.html` is automatically created by Eleventy somehow. And it doesn’t appear possible to modify that behavior as expected to `page-#` or anything else, at least not with `eleventyComputed` in JS templates. But appearances can be deceiving.

**Comment by Ryuno-Ki** [comment]
@reubenlillie I guess, you're right.
I'd need to double check, but I _think_ the URL is built in

https://github.com/11ty/eleventy/blob/7ee3e159b2f5f3609cb1049c06e30e1a337de18d/src/Plugins/Pagination.js#L245

The referenced `outputLink` is some indirection to

https://github.com/11ty/eleventy/blob/26bf0473ae98acac7b90f229e38b6d4dfb8f29a9/src/Template.js#L118-L158

**Comment by reubenlillie** [comment]
@Ryuno-Ki, well, can you imagine a way to override this behavior in JS templates? I'm stumped.

**Comment by Ryuno-Ki** [comment]
Hm, I'd first better understand what's going on. But I can't find log messages in the initial post containing the `Dev:Eleventy:Template` prefix (`DEBUG=Eleventy*` environment variable will turn them on. Filter for those via `grep` or similar)

**Comment by johnpuddephatt** [comment]
I think I'm coming up against the same problem. From the following:

```
class Page {
  data() {
    return {
      pagination: {
        data: 'categories',
        size: 1,
        alias: 'category'
      },
      eleventyComputed: {
        permalink: data => `/api/${data.category.slug}.json`
      }
    };
  }
  render(props) {
    return...
  }
}

module.exports = Page;
```

I'm getting the following files outputted:

```
Writing dist/api/category-slug-one.json from ./src/category.11ty.js.
Writing dist/api/1/category-slug-two.json from ./src/category.11ty.js.
Writing dist/api/2/category-slug-number-three.json from ./src/category.11ty.js.
Writing dist/api/3/category-slug-fourth.json from ./src/category.11ty.js.
```

**Comment by Ryuno-Ki** [comment]
Could you turn on DEBUG mode, @johnpuddephatt?

**Comment by johnpuddephatt** [comment]
Sure – full output here: https://pastebin.com/YNSn7qJs

**Comment by johnpuddephatt** [comment]
Line 144 look 'correct' – i.e. what I'd expect...

`Eleventy:Template Rendering permalink for './src/category.11ty.js': /api/categories/category-number-two.json becomes '/api/categories/category-number-two.json' +1ms`



Line 202 however has an unexpected `/1/`:

` Eleventy:Template dist/api/categories/1/category-number-two.json written.. +0ms`

**Comment by reubenlillie** [comment]
@Ryuno-Ki and @johnpuddephatt,

I'm away from my computer now. I'll try to share some DEBUG ouput soon.

**Comment by Ryuno-Ki** [comment]
I'm pasting the lines relevant to the Debug Log for the Template:

```
Eleventy:Template getMappedDate: using file created time for './src/category.11ty.js' of 2021-01-21T20:58:17.762Z (from 1611262697762.2888) +0ms
Eleventy:Template getMappedDate: using file created time for './src/build.njk' of 2020-12-05T19:40:52.187Z (from 1607197252187.3174) +6ms
Eleventy:Template getMappedDate: using file created time for './src/api/sheets.njk' of 2021-01-21T01:44:20.743Z (from 1611193460743.8162) +5ms
Eleventy:Template getMappedDate: using file created time for './src/index.njk' of 2020-07-22T17:12:25.719Z (from 1595437945719.0203) +1ms
Eleventy:Template getMappedDate: using file created time for './src/pages/about.njk' of 2020-08-16T15:23:03.248Z (from 1597591383248.606) +1ms
Eleventy:Template getMappedDate: using file created time for './src/category.11ty.js' of 2021-01-21T20:58:17.762Z (from 1611262697762.2888) +3ms
Eleventy:Template getMappedDate: using file created time for './src/category.11ty.js' of 2021-01-21T20:58:17.762Z (from 1611262697762.2888) +1ms
Eleventy:Template getMappedDate: using file created time for './src/category.11ty.js' of 2021-01-21T20:58:17.762Z (from 1611262697762.2888) +1ms
Eleventy:Template First round of computed data for './src/category.11ty.js' +1ms
Eleventy:Template Rendering permalink for './src/category.11ty.js': (((((11ty(((((permalink)))))11ty))))) becomes '(((((11ty(((((permalink)))))11ty)))))' +1ms
Eleventy:Template Rendering permalink for './src/category.11ty.js': (((((11ty(((((permalink)))))11ty))))) becomes '(((((11ty(((((permalink)))))11ty)))))' +0ms
Eleventy:Template Rendering permalink for './src/category.11ty.js': /api/categories/category-one.json becomes '/api/categories/category-one.json' +1ms
Eleventy:Template Rendering permalink for './src/category.11ty.js': /api/categories/category-one.json becomes '/api/categories/category-one.json' +0ms
Eleventy:Template First round of computed data for './src/category.11ty.js' +0ms
Eleventy:Template Rendering permalink for './src/category.11ty.js': (((((11ty(((((permalink)))))11ty))))) becomes '(((((11ty(((((permalink)))))11ty)))))' +0ms
Eleventy:Template Rendering permalink for './src/category.11ty.js': (((((11ty(((((permalink)))))11ty))))) becomes '(((((11ty(((((permalink)))))11ty)))))' +0ms
Eleventy:Template Rendering permalink for './src/category.11ty.js': /api/categories/category-number-two.json becomes '/api/categories/category-number-two.json' +1ms
Eleventy:Template Rendering permalink for './src/category.11ty.js': /api/categories/category-number-two.json becomes '/api/categories/category-number-two.json' +0ms
Eleventy:Template First round of computed data for './src/category.11ty.js' +0ms
Eleventy:Template Rendering permalink for './src/category.11ty.js': (((((11ty(((((permalink)))))11ty))))) becomes '(((((11ty(((((permalink)))))11ty)))))' +0ms
Eleventy:Template Rendering permalink for './src/category.11ty.js': (((((11ty(((((permalink)))))11ty))))) becomes '(((((11ty(((((permalink)))))11ty)))))' +0ms
Eleventy:Template Rendering permalink for './src/category.11ty.js': /api/categories/a-third-category.json becomes '/api/categories/a-third-category.json' +0ms
Eleventy:Template Rendering permalink for './src/category.11ty.js': /api/categories/a-third-category.json becomes '/api/categories/a-third-category.json' +1ms
Eleventy:Template First round of computed data for './src/api/sheets.njk' +0ms
Eleventy:Template Rendering permalink for './src/api/sheets.njk': /api/one.json becomes '/api/one.json' +2ms
Eleventy:Template Rendering permalink for './src/api/sheets.njk': /api/one.json becomes '/api/one.json' +0ms
Eleventy:Template First round of computed data for './src/index.njk' +0ms
Eleventy:Template First round of computed data for './src/pages/about.njk' +1ms
Eleventy:Template Rendering permalink for './src/pages/about.njk': /{{ title | slug }}/index.html becomes '/about/index.html' +3ms
Eleventy:Template Rendering permalink for './src/pages/about.njk': /{{ title | slug }}/index.html becomes '/about/index.html' +1ms
Eleventy:Template First round of computed data for './src/build.njk' +1ms
Eleventy:Template Rendering permalink for './src/build.njk': build.txt becomes 'build.txt' +0ms
Eleventy:Template Rendering permalink for './src/build.njk': build.txt becomes 'build.txt' +1ms
Eleventy:Template Second round of computed data for './src/category.11ty.js' +0ms
Eleventy:Template Second round of computed data for './src/category.11ty.js' +0ms
Eleventy:Template Second round of computed data for './src/category.11ty.js' +0ms
Eleventy:Template Second round of computed data for './src/build.njk' +0ms
Eleventy:Template Second round of computed data for './src/api/sheets.njk' +0ms
Eleventy:Template Second round of computed data for './src/index.njk' +0ms
Eleventy:Template Second round of computed data for './src/pages/about.njk' +0ms
Eleventy:Template Writing 'dist/api/categories/category-one.json' from './src/category.11ty.js'. +19ms
Eleventy:Template Writing 'dist/build.txt' from './src/build.njk'. +0ms
Eleventy:Template Writing 'dist/api/one.json' from './src/api/sheets.njk'. +0ms
Eleventy:Template Writing 'dist/api/categories/1/category-number-two.json' from './src/category.11ty.js'. +0ms
Eleventy:Template Writing 'dist/api/categories/2/a-third-category.json' from './src/category.11ty.js'. +0ms
Eleventy:Template Writing 'dist/index.html' from './src/index.njk'. +5ms
Eleventy:Template Writing 'dist/about/index.html' from './src/pages/about.njk'. +0ms
Eleventy:Template dist/api/one.json written.. +3ms
Eleventy:Template dist/api/categories/1/category-number-two.json written.. +0ms
Eleventy:Template dist/build.txt written.. +0ms
Eleventy:Template dist/api/categories/2/a-third-category.json written.. +0ms
Eleventy:Template dist/api/categories/category-one.json written.. +0ms
Eleventy:Template dist/index.html written.. +0ms
Eleventy:Template dist/about/index.html written.. +0ms
Eleventy:Template dist/api/one.json written.. +3ms
Eleventy:Template dist/api/categories/1/category-number-two.json written.. +0ms
Eleventy:Template dist/build.txt written.. +0ms
Eleventy:Template dist/api/categories/2/a-third-category.json written.. +0ms
Eleventy:Template dist/api/categories/category-one.json written.. +0ms
Eleventy:Template dist/index.html written.. +0ms
Eleventy:Template dist/about/index.html written.. +0ms
```

**Comment by Ryuno-Ki** [comment]
@reubenlillie I'm off to bed anywhen soon now.

I'm wondering right now, whether a „nested pagination” like https://github.com/11ty/eleventy/issues/1597#issuecomment-764918105 might work here, too.

The thinking goes in the lines of having a pagination of size - and each of those broken into „sets of pagination”, so that there wouldn't be „a second page”.

**Comment by johnpuddephatt** [comment]
@Ryuno-Ki thanks for your help. #1597 looked promising but I don't think it's practical for a site that will be built in production... it looks to me like the first step outputs the 11ty.js files into the output folder, so they wouldn't be processed?

**Comment by johnpuddephatt** [comment]
In my case I've realised I don't need to use eleventyComputed at all... just setting:

```
      permalink: data => `/api/${data.category.slug}.json`
```
works fine. The question is why I was using it in the first place. I think it came from googling and reading a recent issue on GitHub...

**Comment by reubenlillie** [comment]
@Ryuno-Ki, here’s the trimmed `DEBUG` output from `eleventy-dot-js-blog` v0.2.1. I created a separate branch [`core-#1555`](https://gitlab.com/reubenlillie/eleventy-dot-js-blog/-/tree/core-%231555) if you’d like to check it out. I also pushed the full `DEBUG` output to [`./debug.txt`](https://gitlab.com/reubenlillie/eleventy-dot-js-blog/-/blob/core-%231555/debug-1555.txt) on that branch.

**Comment by Ryuno-Ki** [comment]
@reubenlillie Thanks. I have the tab open but have some other things cooking for this week.
Will come back to you once I have capacity again.

**Comment by monochromer** [comment]
I think, problem is here: https://github.com/11ty/eleventy/blob/26bf0473ae98acac7b90f229e38b6d4dfb8f29a9/src/Plugins/Pagination.js#L185

**Comment by zachleat** [comment]
#1956 merged, which should fix this. I added a test in 34ace73
