### ISSUE TITLE
Netlify deploys fail while local builds succeed 

### ISSUE THREAD

**Issue by dandenney** [11ty/eleventy#1557]
**Describe the bug**
While this is technically a Netlify issue, a little birdie mentioned that it might be good for searching in here. Netlify deploys started failing with no build flow changes. The error indicates a problem with Eleventy, but the reality is that it's a Node version mismatch.

```
8:20:17 AM: `EleventyConfigError` was thrown
8:20:17 AM: 2020-12-10T14:20:17.406Z Eleventy:EleventyErrorHandler (error stack): EleventyConfigError: Error in your Eleventy config file '/opt/build/repo/.eleventy.js'.
```

**To Reproduce**
1. Deploy Eleventy on Netlify without setting the Node version in some way.  
2. Have a dependency, Eleventy or otherwise, that uses a newer Node version with a breaking change

**Expected behavior**
Expected is a stretch a little bit here, but my expectation was that Netlify would be running the same Node version that I was running for my local build.

**Solution**
Set your Node version in some way, based on Netlify's recommendations: https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript

A `.nvmrc` was the quickest and most straight forward solution I found for parity between the two. 

**Additional context**
Full error list on the Netlify Community: https://community.netlify.com/t/eleventy-deployment-failures/28064

**Comment by zachleat** [comment]
I think the other thing to note (fwiw, and perhaps unbeknownst to a fair number of people) is that odd numbers of Node are a bit special. Rule of thumb is that I try to stick to even numbered major versions of Node

You can read more here: https://tamalweb.com/which-nodejs-version

There is also this suggestion on the Node download page:

![image](https://user-images.githubusercontent.com/39355/102365835-9a78c500-3f7d-11eb-88e8-2da13a18b5ad.png)

**Comment by zachleat** [comment]
I see the :tada: emoji here @dandenney—can we close this old one? 😅

**Comment by dandenney** [comment]
@zachleat Yessir, thank you!
