### ISSUE TITLE
Adding search to the documentation

### ISSUE THREAD

**Issue by pixelastic** [11ty/eleventy#156]
Hello,

While learning eleventy, I had to often refer to the documentation to see if a feature was available, and how to do it. I currently have to browse each page and remember where I saw something.

What about adding a searchbox to quickly get to the relevant part of the documentation?

![2018-06-27_11h57m18](https://user-images.githubusercontent.com/283419/41967265-849cdbb6-7a01-11e8-8c6b-8bd08b72706f.gif)

I work at Algolia, and we happen to have developed a tool named [DocSearch](https://community.algolia.com/docsearch/), which will crawl documentation websites every 24h and expose the content through an Algolia index to allow users to search into it. If you're interested, you just have to enter your email and website url on the website I linked above, and we'll send you a small JavaScript snippet and credentials to add to your website.

This is entirely free, pretty fast and handles typo-tolerance out of the box. I already created the config for you (the one I use in the screenshot).

Let me know if you'd be interested :)

**Comment by zachleat** [comment]
Sounds good, I filled it out!

**Comment by pixelastic** [comment]
Hey @zachleat, thanks for your patience in this. I just sent you an email with the instructions to add the search to your website :)

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for documentation requests. This means documentation issues will now be closed instead of leaving them open.

View [the documentation queue backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Areactions-%2B1-desc+is%3Aclosed+label%3Adocumentation+label%3Aneeds-votes). Don’t forget to upvote the top comment with 👍!

**Comment by EdenKupe** [comment]
Hey guys,

I came to the repo to suggest just this! I've worked with DocSearch in the past and Algolia in general so I have some pretty good experience in setting this up. 

I would *love* to help do this for the Eleventy doc site, I can work on a fork and even do some design for the search bar and drop-down.

Let me know if you'd like my help on this.

**Comment by pixelastic** [comment]
Just wanted to let you know that I know longer work at Algolia so won't be able to dedicate much time to this, but if you need any help in setting this up @s-pace would be able to help.

**Comment by s-pace** [comment]
Indeed. Happy to PR it

**Comment by zachleat** [comment]
Unfortunately I decided to go a different direction with search. I’m trying to minimize the amount of third party JS on the docs site.

https://twitter.com/eleven_ty/status/1197550926636158982
