### ISSUE TITLE
Trying to get matching posts for a key

### ISSUE THREAD

**Issue by tBaxter** [11ty/eleventy#1561]
I'm trying to find posts matching a custom tag-like item in the front matter. Sort of a category.  Essentially, it goes like this.... given a bunch of pets, I might tag them as `cat`, `dog`, `hamster`, etc. I also have other tags that aren't necessarily related, so trying to do this off tags would be messy, I think.

In some cases, but not necessarily all, I may want to show content for a particular pet. So I've got an extra item in the front matter:
`petName: Sir Fluffles the Magnificent`

So what I want to do is get just the posts for Sir Fluffles there.

### What I've done so far:
I've created a custom collection to just output the pets, with a URL-friendly version of their name:
```
eleventyConfig.addCollection("petList", function (collection) {
    let petSet = new Set();
    collection.getAll().forEach(function (item) {
      if ("petName" in item.data) {
        let pet = item.data.petName
        petSet({
          name: petName,
          slug: slugify(petName.toLowerCase())
        });
      }
    });
    return [...bikeSet];
  });
  ``` 
 
That works and the page outputs as expected. I also have individual pages for the pets, based on the name and slug from that collection, and those work, too. 
  
 ### Where I'm stuck
 Where I'm stuck is trying to retrieve the posts for the pet. 
 
I've tried following the example from the docs for a template filter like `getPostsForPet`, but the example is looking for instances where the key is present, and I'm not figuring out how to get the posts matching a given value.
  
  I think part of the problem may be how I'm trying to pass data for the filter, based on the `"expected block end in set statement"` error I'm seeing. 

Any suggestions?

**Comment by danurbanowicz** [comment]
You could create an 11ty filter, in this case `_filters/include.js` to output your items based on your custom frontmatter key value, like this (uses lodash):-

```
const lodash = require("lodash");

module.exports = function (arr, path, value) {
  // make lowercase and strip accents etc from the key value
  value = lodash.deburr(value).toLowerCase();
  return arr.filter((item) => {
    let pathValue = lodash.get(item, path);
    pathValue = lodash.deburr(pathValue).toLowerCase();
    return pathValue.includes(value);
  });
};
```

And then in the individual pet template, filter your items based on the `petName` key value, something like this (Nunjucks, not tested):-

```
<h1>{{ name }}</h1> // the current pet’s name e.g. Sir Fluffles the Magnificent

// the 11ty filter
{% set postsByPet = collections.posts | include("data.petName", name) %}

{% for post in postsByPet %}
// the post details in here
{% endfor %}
```

Check out this blog post for a good explanation of working with custom taxonomies in 11ty (the above examples are based on the ones found there): https://www.webstoemp.com/blog/basic-custom-taxonomies-with-eleventy/

Hopefully this gets you closer to a solution!

**Comment by tBaxter** [comment]
If I'm reading that filter correctly, though, it would only capture files in which the filepath/URL matched a slugified version of the value, correct? Unfortunately, I don't have that, and don't particularly want it. I've got posts all under `/posts/whatever/` and don't want to change that so much as just, y'know, provide an alternate way of collecting it.

**Comment by danurbanowicz** [comment]
The example I provided should allow you to output the posts for each pet as long as the `petName` key and value exists in the post front matter. You use it in your template by passing in the key and key value you want to filter on.

Please try it if you can and report back, or let me know if I’m misunderstanding your particular use case!

**Comment by tBaxter** [comment]
I think I've got it, albeit taking a slightly different tack. I figured since I'm already iterating through `collections.getAll` to find the content with the key, I could just append to the data structure I'm already creating. And in the process I figured out I was missing duplicate checking before, so that was a win, too. Here's where I ended up. Suggestions are welcome, of course.

```
eleventyConfig.addCollection("petList", function (collection) {
    let petList = [];
    collection.getAll().forEach(function (item) {
      if ("pet" in item.data) {
        let pet = item.data.pet;
        let petSlug = slugify(pet.toLowerCase())
        // Quick check to see if that pet already exists in the list.
        // PetList is small, so this should be reasonably performant.
        petObj = petList.find(obj => obj.slug == petSlug);
        if (petObj) {
          petObj.posts.push(item)
        } else {
          // the pet is not yet in the List, so we'll create it.
          petList.push({
            name: pet,
            slug: petSlug,
            posts: [item]
          });
        }
      }
    });
    return petList;
  });
  ```

**Comment by tBaxter** [comment]
Since this appears to be working, I'm going to go ahead and close it. @danurbanowicz thank you for your help working through it. Even though in the end I took a different approach, you were still very helpful and I appreciate it.
