### ISSUE TITLE
Global computed data overridden completely when a template uses front matter data?

### ISSUE THREAD

**Issue by gremo** [11ty/eleventy#1567]
As explained in [Computed Data](https://www.11ty.dev/docs/data-computed/) section of the docs, I'm using a global `eleventyComputed.js` in my `data` folder, here is the content:

```js
module.exports = {
  metas: data => {
    let metas = data.metas || [];
    Object.entries({
      'og:type': () => 'website',
      'og:title': data => data.title,
      'og:description': data => data.description,
      'og:url': () => `${data.env.BASE_URL}${data.page.url}`,
      'og:locale': data => data.locale,
    }).forEach(([property, provider]) => {
      if (!metas.filter(meta => property === meta.property).length) {
        metas = [...metas, { property, content: provider(data) }]
      }
    });

    return metas;
  }
};
```

As you can see I'm computing a `metas` array, and it works just fine. I'm **adding data to the existing `metas` array** if any.

In my `index.njk`, I can add other metas or override computed ones this way:

```md
---
title: Example website
decsription: Site description
metas:
  - { property: 'og:image', content: '/img/fb-banner.png' }
  - { property: 'og:description', content: 'Custom site description for Facebook Open Graph' }
---

<h1>{{ title }}</h1>

```

However, when I **try to compute the metas from the front matter data**, those metas will completly override the metas defined in `eleventyComputed.js`:

```md
---
title: Example website
eleventyComputed:
  metas:
    - { property: 'og:image', content: '{{ data.env.BASE_URL }}/img/fb-banner.png' }
---

<h1>{{ title }}</h1>

```

Is this a bug or it's by design?

**Comment by binyamin** [comment]
@gremo According to [the docs on data cascade](https://www.11ty.dev/docs/data-cascade/#sources-of-data), front-matter data has a higher priority than global data. In #1303, which I see you've found, they've set `eleventyConfig.setDataDeepMerge(true)`. That is supposed to tell 11ty to merge values instead of replacing them, but there's no deep merge.

**Comment by gremo** [comment]
I already have `eleventyConfig.setDataDeepMerge(true)` but this doesn't help. So you assume it's by design? It will not fixed changed in the near future? I'm still looking for a workaround/solution to this.

**Comment by binyamin** [comment]
> I already have `eleventyConfig.setDataDeepMerge(true)`...

Sorry, I didn't realize that. You're right, it's the bug from the issue 1303 mentioned above.
