### ISSUE TITLE
Comparing string with number in BenchmarkGroup

### ISSUE THREAD

**Issue by Ryuno-Ki** [11ty/eleventy#1570]
**Describe the bug**
While adding DocStrings for type annotation, I encountered a possible bug in

https://github.com/11ty/eleventy/blob/82d83f55b92624b7b307c3814c80c7f83b264d7f/src/BenchmarkGroup.js#L109

`Number.prototype.toFixed()` is resulting a String. You are comparing it with a number.
This will likely cause JavaScript to apply a type conversion (cannot tell offset which gets converted how).
What are you trying to do here?

**Expected behavior**
Both parts of the comparison should have the same type.

**Screenshots**
![typescript-check](https://user-images.githubusercontent.com/3097194/103425873-95d72200-4bb5-11eb-87f9-4b33376695a9.png)

**Environment:**

- Eleventy Version 904234193766aa9d9a7fb1e5037dea8838995a0f

**Additional context**
Work in Progress Pull Request

**Comment by tannerdolby** [comment]
To avoid JavaScript applying an automatic type conversion, would it be an option just to convert the result of `Number.prototype.toFixed()` to a number like `parseInt(totalForBenchMark.toFixed(0))` within the condition of the `if` statement so the relational operator `>` can properly compare the two numbers?

**Comment by victornpb** [comment]
Number.toFixed() is mostly used for number formatting hence the return type String. So casting it back to number isn't ideal.
Since its being used as a conditional it should probably be changed to

```js
if (Math.round(totalForBenchMark) > 0) { }
// or
if (totalForBenchMark >= 0.5) { }
```

**Comment by zachleat** [comment]
Shipping with 3.0.0-alpha.17
