### ISSUE TITLE
High severity package vulnerability with browser-sync -> localtunnel -> axios

### ISSUE THREAD

**Issue by tannerdolby** [11ty/eleventy#1578]
**Describe the bug**
When installing `@11ty/eleventy` (v0.11.1) with npm in a new project. I'm seeing this high severity vulnerability across all new projects and after updating from v0.11.0 to v0.11.1 in existing projects. After further investigation, here is the [link](https://www.npmjs.com/advisories/1594) for more information and the [Fix commit](https://github.com/axios/axios/commit/c7329fefc890050edd51e40e469a154d0117fc55) in `axios`.

**To Reproduce**
In a fresh project folder (without `@11ty/eleventy` installed):

1. Make sure a package.json exists: `npm init -y`
2. Run `npm install @11ty/eleventy`
3. See the high severity vulnerability warning after `npm install`ing.
4. Run `npm audit` to see a more detailed version of the vulnerability.
5. To fix, just bump `axios` from `0.19.0` to `0.21.1` and update the `integrity` and `resolved` keys for `axios {}` in `package-lock.json` near `localtunnel`.

> Note for workaround: I did a fresh `npm install axios` which uses the latest version `0.21.1` and then copied the `integrity` and `resolved` key values to be used in step 5. Since I didn't need `axios` in my `package.json` as a dependency I simply removed it with `npm uninstall -S axios` after obtaining the values needed to update `package-lock.json`.

When using `npm update @11ty/eleventy` in an existing project that was prev running `v0.11.0` the same high severity vulnerability occurs like mentioned above with `browser-sync -> localtunnel -> axios`.

**Expected behavior**
The most updated version of `eleventy` (v0.11.1) to not have any high severity package vulnerabilities out of the box after installation.

**Screenshots**
<img width="675" alt="Screen Shot 2021-01-05 at 8 42 14 PM" src="https://user-images.githubusercontent.com/48612525/103730111-dc9e9080-4f96-11eb-925c-f2bf095fdc42.png">

**Environment:**

- OS and Version: MacOS
- Eleventy Version: v0.11.1

**Comment by muenzpraeger** [comment]
Plus one to get this fixed.

**Comment by MarcoZehe** [comment]
Adding my +1, too, also see the Discord chat. This number of vulnerabilities increases if you install something like @11ty/eleventy-plugin-rss.

**Comment by PabloC** [comment]
+1 for a workaround or a fix to this!

**Comment by ThewBear** [comment]
It seems that localtunnel hasn't received any updates for 16 months.
https://github.com/localtunnel/localtunnel/issues/377
https://github.com/BrowserSync/browser-sync/issues/1831

**Comment by Hazantip** [comment]
+

**Comment by ragebflame** [comment]
+1

**Comment by zachleat** [comment]
Follow along at this issue also: https://github.com/BrowserSync/browser-sync/issues/1831

This did happen earlier in 2020 and they did release a patch for it, so hang tight. Previous context: https://github.com/11ty/eleventy/issues/1164#issuecomment-629691507

Related: https://github.com/11ty/eleventy/issues/1305

**Comment by zachleat** [comment]
Also I would reiterate that browser-sync is intended for development purposes only—do not run it in production!

**Comment by openmindculture** [comment]
+1

**Comment by waldyrious** [comment]
This issue no longer applies: since browser-sync v2.26.13 (the version [currently used by eleventy](https://github.com/11ty/eleventy/blob/v0.11.1/package.json#L97)) specifies the dependency on [localtunnel dependency](https://github.com/BrowserSync/browser-sync/blob/v2.26.13/packages/browser-sync/package.json#L51) as `^2.0.0`, as soon as localtunnel v2.0.1 (which matches the `^2.0.0` version spec) was [released](https://github.com/localtunnel/localtunnel/commit/485b81619de7ea1196ea91a1d2c5f1993151be5f) with [the fix](https://github.com/localtunnel/localtunnel/commit/67f4ddaed78adfffa1d5d66dd75daafaf1f5415e) (a couple days ago), any new installations of eleventy will now automatically pick that up. Yay for [caret version ranges](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004)!

**Comment by ThewBear** [comment]
I can confirm that localtunnel v2.0.1 fix this.
For existing project, you can update deep dependencies by `npm update --depth=<int>` where **\<int\>** may be `9`

**Comment by tannerdolby** [comment]
If anyone else can confirm the above that `npm update --depth=9` fixes the package vulnerability. I will close this issue as it is now resolved.

**Comment by tannerdolby** [comment]
UPDATE: Tested `npm install @11ty/eleventy` in a fresh project and the high severity package vulnerability no longer exists. The above `npm update --depth=9` doesn't seem to be needed unless for some _odd_ reason the vulnerability is still present for you.
