### ISSUE TITLE
ssl / https support for localhost serve

### ISSUE THREAD

**Issue by mariusa** [11ty/eleventy#1583]
**Is your feature request related to a problem? Please describe.**
I would be useful to test locally over https

**Describe the solution you'd like**
```
npx @11ty/eleventy --serve --https
```

**Additional context**
vue/vite can serve apps with `https: true,`, maybe that can serve as an inspiration

**Comment by willywongi** [comment]
I just found out (from the code, I couldn't find it on the docs) that you can set a config object to be passed to browserSync.
in your `.eleventy.js`:
```javascript
eleventyConfig.browserSyncConfig = {
    https: true
};
```
Please review the related config info here: https://www.browsersync.io/docs/options#option-https

As a bonus, let [mkcert](https://github.com/FiloSottile/mkcert) handle creation of the key/cert for you!

**Comment by mariusa** [comment]
Thanks! That does work, although it says "Your connection is not private"

Since I'm already using mkcert and NODE_EXTRA_CA_CERTS is already setup, couldn't eleventy rely on using this env var to serve the appropriate certificate?

**Comment by willywongi** [comment]
I'm sorry I can't help you now, but I think that most of the SSL stuff is handled by browserSync, so you should have better luck asking [there](https://github.com/BrowserSync)!

**Comment by mariusa** [comment]
Thanks, I'll followup at https://github.com/BrowserSync/browser-sync/issues/1832
