### ISSUE TITLE
`this.ctx` available in filter but not in shortcode

### ISSUE THREAD

**Issue by aomader** [11ty/eleventy#1584]
Is there a particular reason why `this.ctx` is available in a custom filter, but not in a custom shortcode? Is there an alternative approach to access the `ctx` in a shortcode?

**Comment by pdehaan** [comment]
Interesting... What is `this.ctx`? Is that a Nunjucks thing?
Only other reference I found to it was https://github.com/11ty/eleventy/issues/567#issuecomment-504649063

I created https://github.com/pdehaan/11ty-filter-context but it looks like `this.ctx` and `this.getVariables()` only works in Nunjucks (and returns `undefined` for `this.ctx` in LiquidJS, and fails hard on `this.getVariables()`).

**Comment by b52** [comment]
Seems like, initially I assumed it was provided by eleventy. Still, I do not get why it is present in a filter but not in a shortcode.

**Comment by zachleat** [comment]
We could restore ctx, I think?

Related to https://github.com/11ty/eleventy/issues/1522

**Comment by zachleat** [comment]
`this.ctx` will be available in Nunjucks shortcodes in 1.0.0-beta.9
