### ISSUE TITLE
Use markdown inside nunjucks 

### ISSUE THREAD

**Issue by satrya** [11ty/eleventy#1586]
Hi,
I am new to Eleventy, please help with my issue below.

Here's my Base layout `_includes/layouts/base.njk` code
```
<!DOCTYPE html>
<html lang="{{ metadata.lang }}">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>{{ title or metadata.title }}</title>
    {% set css %}
    {% include "web.css" %}
    {% endset %}
    <style>
      {{css | cssmin | safe}}
    </style>

    {% include "meta.njk" %}
  </head>

  <body {% if bodyClass %} class="{{ bodyClass }}" {% endif %}>

    <header class="header">
      <div class="header__wrapper container">
        {% include "components/_brand.njk" %}
        {% include "components/_nav.njk" %}
      </div>
    </header>

    <main class="main-content">
      {{ content | safe }}
    </main>

    <footer class="footer">
      {% include "components/_footer.njk" %}
    </footer>
  </body>
</html>
```

And here's my custom HOME layout `_includes/layouts/home.njk`

```
---
layout: base
---

{% include "home/_hero.njk" %}
{{ content | safe }}
```

My plan is to split home page content into separate files so I can easily manage it. As you can see in the `home.njk` file above I include the hero area then I'd like to add more content after the hero area but with markdown template. I tried this

```
---
layout: layouts/home.njk
---

### Testing
```

But Eleventy seems can't compile it. How do I do this in Eleventy?

I also tried to use `{% include "content.md" %}` but the markdown parser not working.

**Comment by pdehaan** [comment]
@satrya You can use `{% include %}` with a custom markdown rendering shortcode or paired shortcode. There are a few examples in the https://github.com/11ty/eleventy/issues/658#issuecomment-599142642 thread.

**Comment by satrya** [comment]
@pdehaan thanks a lot!
