### ISSUE TITLE
Nunjucks template inheritance path

### ISSUE THREAD

**Issue by octoxalis** [11ty/eleventy#159]
What is the right path to reference the super template from the template inheriting, both located in the same directory (i.e. __includes/layouts_)?
`{% extends "base.njk" %}` gives this error message:

---
* Error: Having trouble rendering template ./_includes/layouts/index.njk: {% extends "base.njk" %}
.....
 * Template render error: (unknown path)
  Error: template not found: base.njk
---

**Comment by octoxalis** [comment]
Closed because I found that Nunjucks had to be configured:
`eleventyConfig.setLibrary("njk", require("nunjucks").configure("_includes/layouts"));`
I use this compact statement, less verbose than [11ty doc  example](https://www.11ty.io/docs/languages/nunjucks/).

**Comment by zachleat** [comment]
Ah, setting a library in Eleventy is an optional step if you want some kind of advanced Nunjucks configuration.

You _may_ run into issues trying to use includes outside of `_includes/layouts` with that setup. I’m not sure if you can pass in multiple directories in `configure` or not—worth investigating!
