### ISSUE TITLE
All collection items missing `url`

### ISSUE THREAD

**Issue by briankoser** [11ty/eleventy#160]
My .eleventy.js has the standard

```
eleventyConfig.addCollection("episodes", function(collection) {
    let episodes = collection.getFilteredByTag("episode");
```

(For a podcast fan site so "episodes" instead of "posts".)

Somehow recently every episode in my collection lost its `url` attribute. 
- I'm checking right after the above code, so I'm not accidentally removing it somehow. 
- It doesn't look like it was moved to a different location in the collection.
- I noticed the issue on 6/10, so is it possible a bug was introduced in v0.3.6?

I created a stripped-down copy of my project at https://github.com/briankoser/eleventy-demo. The issue is `console.log`ged at .eleventy.js line 10.

Let me know if there's anything else I can do to help debug this.

---

By the way, thanks for building eleventy! Finally a static site generator I'm happy with.

**Comment by zachleat** [comment]
Yep, can confirm this regressed. Related to #115. Added tests around this so it won’t happen again—thanks! It’ll be included with 0.5.0
