### ISSUE TITLE
display first element of json with variable naming

### ISSUE THREAD

**Issue by aeon3k** [11ty/eleventy#1608]
Hi guys and thanks for this amazing piece of software.

I'm in the case where I have a njk template and a json data file and a variable that holds a locale value. If the json file is like this
{"title": {
"en" : "my title"
}
}
I'm able to display the title like this :
 {{ title[locale] }} 

But if the json file is like this I can't find a solution to display the title
{
"en" : "my title"
}

Is there a solution?

**Comment by Ryuno-Ki** [comment]
`{{ en }}`.

It also depends on the name of the file and where it is stored.
JSON files in `_data` are globally data directory files. Their file name will become the key you use.
Here, I assume, you have it somewhere else. Here you use the keys as defined in the JSON.

**Comment by aeon3k** [comment]
Sorry I wasn't clear enough. I need to use the "locale" variable that holds the "en" value...

**Comment by zachleat** [comment]
A bunch of solutions in #567 for Nunjucks!

```js
module.exports = function(eleventyConfig) {
  eleventyConfig.addNunjucksFilter("getGlobalVar", function(varName) {
    return this.getVariables()[varName];
  });
};
```

```jinja2
{{ locale | getGlobalVar }}
```

via https://github.com/11ty/eleventy/issues/567#issuecomment-575828788
