### ISSUE TITLE
Passing custom options to pug compile method

### ISSUE THREAD

**Issue by pixelastic** [11ty/eleventy#161]
Hello,

I tried to figure out another way to mimic the `url` filter in pug (cf #154). 

I know it is possible to pass custom variables to the `pug.compile(str, options)` call in raw pug (`options` being an object of key/values to be accessible in the pug rendering). 

I thought I could use that to pass my own `url` method to guess the `pathPrefix` to 
use. I tried passing it using the `eleventyConfig.setPugOptions()` but this seem to only add it to the main pug options (as describe [here](https://pugjs.org/api/reference.html)), not to the final compile call.

Still looking for a way to replicate the `url` filter in pug :)

**Comment by zachleat** [comment]
Hmm, `setPugOptions`  is used in `pug.compile` though:

https://github.com/11ty/eleventy/blob/master/src/Engines/Pug.js#L41

How are you using it? I was able to successfully implement a filter test using something like this:

```
eleventyConfig.setPugOptions({
  filters: {
    "makeUppercase": function(text, options) {
      return text.toUpperCase();
    }
  }
});
```

See https://github.com/11ty/eleventy/blob/master/test/TemplateRenderPugTest.js#L78

**Comment by pixelastic** [comment]
Maybe I'm not using the right terminology then. What I wanted to pass were not really pug options, but maybe more pug "data", to be passed to the rendered function.

Ie., not a global pug configuration like filters, but more a local object containing variables that could be used in the actual pug content. I thought that I could hack into the way you pass global data (from the `_data` folder) to pass a custom function and not only custom variables. I thought `setPugOptions` could do that but that's not what it's used for.

**Comment by zachleat** [comment]
Sorry for the super late response here @pixelastic but I did try passing a function to a pug template and it seems to work okay.

You can define functions in [JavaScript Front Matter](https://www.11ty.io/docs/data-frontmatter/#javascript-front-matter) or other [JS Data Files](https://www.11ty.io/docs/data-js/)

This should work:

```
---js
{
  getName: function() { return "Zach"; }
}
---
p= getName()
```

**Comment by pixelastic** [comment]
Thanks for getting back to me on this. I'm no longer actively working on this project, so I cannot test what you suggested, but thanks anyway :)
