### ISSUE TITLE
Can I process a front matter item like collections processes tags?

### ISSUE THREAD

**Issue by btrem** [11ty/eleventy#1611]
11ty collections can process tags whether a post has one `tag: foo` or whether it has more than one `tag: [foo, bar]`. I have a front matter variable that might have one value, or more than one, i.e., it might be `var: baz` or it might be`var: [baz, bat]`. Can I use a `{% for %}` loop to process it either way? In other words, treat `var: baz` as if var was an array with one item? I tried this:

    {% for item in var %}
        // do something with the item 
    {% endfor %}
It works when there's more than one value. But when there's only one, in the form `var: baz`, it processes the value as an array of letters (which makes sense, but it's not what I want). If it can't be done, I can just use

    var: [baz]
so not the end of the world. But it'd be nice if I could write it without brackets when there's only 1 item.

**Comment by pdehaan** [comment]
Interesting... Nunjucks or LiquidJS?
I'm thinking you could do it with a custom filter which checks to see if the `tag` attribute is an Array or not and wrap it if needed.

**Comment by pdehaan** [comment]
Yeah, custom filter should work: https://github.com/pdehaan/11ty-1611

```js
  eleventyConfig.addFilter("toArray", value => {
    if (Array.isArray(value)) {
      return value;
    }
    return [value];
  });
```
Ref: https://github.com/pdehaan/11ty-1611/blob/fa290cb2d9cb0a8a13fd31acf95986aaf9f26e0e/.eleventy.js#L2-L7

---

```njk
<p>Convert the tag to an array using custom <code>toArray</code> filter:</p>
<ol>
  {% for t in (tag | toArray) %}
  <li>{{ t }}</li>
  {% endfor %}
</ol>
```
Ref: https://github.com/pdehaan/11ty-1611/blob/fa290cb2d9cb0a8a13fd31acf95986aaf9f26e0e/src/pages/single.njk#L18-L23

**Comment by pdehaan** [comment]
> Interesting... Nunjucks or LiquidJS?

You must be using Nunjucks, because LiquidJS seems to "just work"(tm) and return a single "single" value instead of splitting by character.

But for future travellers, if you _are_ using liquidjs, you'll need to use the `toArray` filter in an `{% assign %}` block before looping, as seen below:

```liquid
<p>But the <code>toArray</code> filter should still work too:</p>
<ol>
  {% assign tags = tag | toArray %}
  {% for t in tags %}
  <li>{{ t }}</li>
  {% endfor %}
</ol>
```

**Comment by Ryuno-Ki** [comment]
I _think_ I've saw Eleventy converting it to an array either way under the hood.
Would need to look up the source code, though.

**Comment by btrem** [comment]
The filter works perfectly. I would not have thought to write a custom filter, because I'm new to 11ty. So this resolves the immediate issue, and hopefully will help me solve other problems in the future.

Thanks for your help.
