### ISSUE TITLE
Update liquidjs to 9.17.x

### ISSUE THREAD

**Issue by sschuldenzucker** [11ty/eleventy#1616]
I suggest to update liquidjs to `liquidjs-9.17.0` to include my [patch](https://github.com/harttle/liquidjs/commit/768fb79e32d84cdacee79a080f0d07a8a7439558) that makes it much more feasible to use "strict" variables. (tell liquid to report an error for undefined variables)

This can be nice for people to catch errors during web dev. Particularly convenient when converting templates from other generators (like Jekyll), where variables may be named differently.

Previously discused in #1334 .

**Comment by clottman** [comment]
@sschuldenzucker This was updated [in this commit](https://github.com/11ty/eleventy/commit/f4cb6e7d55eaa492fcbebee1fa0ecc6263eb04b6). :)

**Comment by binyamin** [comment]
Also, it's live in [v0.12.1](https://www.npmjs.com/package/@11ty/eleventy/v/0.12.1)

**Comment by sschuldenzucker** [comment]
Cool, very nice! :)
