### ISSUE TITLE
Sharing URL has a "undefined" in it

### ISSUE THREAD

**Issue by bosslee** [11ty/eleventy#1619]
Hi there 
I just setup my 11ty site
The site is bosslee.co
The post I'm having issue is https://bosslee.co/posts/mr-loh!-monologue-of-my-last-in-camp-training/

**Details**
When I share the post URL from the browser, it will work but if I'm sharing it from iOS share sheet. 
![09C83130-A862-48A6-AD6C-1555715B18FA](https://user-images.githubusercontent.com/993948/106372697-75190c80-63ad-11eb-8e0d-69a74a6821de.jpeg)

**Actual Result**
This is the result of the URL 
https://bosslee.co/posts/mr-loh!-monologue-of-my-last-in-camp-training/undefined/posts/mr-loh!-monologue-of-my-last-in-camp-training/

**Expected Result**
https://bosslee.co/posts/mr-loh!-monologue-of-my-last-in-camp-training/

Not exactly sure where the error is so filing here to seek some help. Thank you very much

**Comment by pdehaan** [comment]
Not sure if your 11ty code is in GitHub or somewhere, but looking at the final HTML in view-source/Devtools it's a problem with your `canonical` and meta `og:url` and `twitter:url` values:

```diff
  <meta itemprop="description" name="description" content="Documenting work on the internet" />
- <link rel="canonical" href="undefined/posts/mr-loh!-monologue-of-my-last-in-camp-training/" />
  <meta property="og:type" content="website" />
- <meta property="og:url" content="undefined/posts/mr-loh!-monologue-of-my-last-in-camp-training/" />
  <meta property="og:title" content="MR LOH! Monologue of my last in camp training" />
  <meta property="og:description" content="Documenting work on the internet" />
  <meta property="og:site_name" itemprop="name" content="This is Bosslee" />
  <meta property="og:image" content="" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta name="twitter:card" content="description" />
  <meta name="twitter:site" content="" />
  <meta name="twitter:creator" content="" />
- <meta name="twitter:url" content="undefined/posts/mr-loh!-monologue-of-my-last-in-camp-training/" />
  <meta name="twitter:title" content="MR LOH! Monologue of my last in camp training" />
  <meta name="twitter:description" content="Documenting work on the internet" />
  <meta name="twitter:image" content="" />
```

Without seeing the code, I'm guessing you have a variable or something for the domain that you're hosting on (`https://bosslee.co/`) so the links will be fully qualified URLs, but for some reason, that protocol+host isn't being found and gets converted to `undefined`.

**Comment by bosslee** [comment]
Thanks for the tip @pdehaan 
I will check on it

Also to share link to my repo: https://github.com/bosslee/This-is-Bosslee

**Comment by pdehaan** [comment]
https://github.com/bosslee/This-is-Bosslee/blob/cd0e94fb338976c51131eef42eee691ebe8953e9/_includes/components/seo.njk#L13-L18 mentions `metadata.canonicalUrl`, but I don't see a `canonicalUrl` in your [`_data/metadata.json` file](https://github.com/bosslee/This-is-Bosslee/blob/80c0710aee79aa4616b8b36772b4d67d8e54d9f8/_data/metadata.json#L1-L5) (only a `url`):

```json
{
  "title": "This is Bosslee",
  "description": "Documenting work on the internet",
  "url": "https://this-is-bosslee.netlify.app"
}
```

**Comment by bosslee** [comment]
Thank you very much @pdehaan :)
