### ISSUE TITLE
npm run build  iframe  html-minifier

### ISSUE THREAD

**Issue by zyj1022** [11ty/eleventy#1621]
**Describe the bug**
Error writing templates: (more in DEBUG output)
[eleventy:prod] > Having trouble writing template: dist/posts/case/advVideo-1/index.html
[eleventy:prod] `TemplateWriterWriteError` was thrown
[eleventy:prod] > Parse Error: <iframe src="https://player.youku.com/embed/XDFSDFWER==" frameborder="0" 'allowfullscreen'="">
[eleventy:prod] </iframe>

....
.....

[eleventy:prod]         at new HTMLParser (/Users/user/Git/eleventy/node_modules/html-minifier/src/htmlparser.js:244:13)
[eleventy:prod]         at minify (/Users/user/Git/eleventy/node_modules/html-minifier/src/htmlminifier.js:980:3)
[eleventy:prod]         at Object.exports.minify (/Users/user/Git/eleventy/node_modules/html-minifier/src/htmlminifier.js:1341:16)
[eleventy:prod]         at Template.htmlmin (/Users/user/Git/eleventy/utils/transforms.js:16:28)
[eleventy:prod]         at Template.runTransforms (/Users/user/Git/eleventy/node_modules/@11ty/eleventy/src/Template.js:369:29)
[eleventy:prod]         at Template.renderPageEntry (/Users/user/Git/eleventy/node_modules/@11ty/eleventy/src/Template.js:609:26)
[eleventy:prod]         at process._tickCallback (internal/process/next_tick.js:68:7)

**To Reproduce**

Adding an iframe to a Markdown file will cause an error at build time。

**Environment:**

- OS and Version: [e.g. Windows/Mac/Linux]
- Eleventy Version [via `eleventy --version` or `npx @11ty/eleventy --version`]

**Comment by zyj1022** [comment]
npm run eleventy:dev builds normally.  This is an error in html-minifier compression，Are there any other plugins to replace it

**Comment by pdehaan** [comment]
```html
<iframe src="https://player.youku.com/embed/XDFSDFWER=="
  frameborder="0"
  'allowfullscreen'="">
```

Some odd single quotes around the `'allowfullscreen'=""` attribute. Wonder if that’s related...

**Comment by zyj1022** [comment]
npm run eleventy:dev builds normally
