### ISSUE TITLE
Why every modification makes all files to rewrite?

### ISSUE THREAD

**Issue by VictorBaudot** [11ty/eleventy#1622]
Every time I changed a single file, it makes all files to rewrite themselves... My laptop is burning.
![image](https://user-images.githubusercontent.com/33088396/106770490-f1be1c00-6635-11eb-8bdb-e545a581b280.png)

**Comment by paulshryock** [comment]
Hi @VictorBaudot , is that changed file an individual piece of content (which Eleventy calls a template), or a layout, or an included partial?

If it were a layout, for example, then any templates using that layout would be rebuilt when it's changed.

**Comment by paulshryock** [comment]
Try this from the CLI:

```bash
npx eleventy --incremental
```

Or this via the undocumented API:

```javascript
// build.js

const Eleventy = require('@11ty/eleventy')
async function html () {
  try {
    const ssg = new Eleventy()

    // Only rebuild modified templates.
    ssg.setIncrementalBuild(true)

    // Write HTML files.
    await ssg.init()
    ssg.write()
  } catch (error) {
    console.error(error)
  }
}
```

**Comment by VictorBaudot** [comment]
Tried both way, still takes 30 seconds every time I update one document...

**Comment by paulshryock** [comment]
> I don't think build.js is called when you're in dev mode.

`build.js` was just an example of a file you could create as part of your toolchain. You could add that code to a `gulpfile.js` or whatever you like to use -- if you wanted to use the JS API. But if you're just using the CLI, you can stick with the `--incremental` flag.
