### ISSUE TITLE
Minify HTML output

### ISSUE THREAD

**Issue by micahmills** [11ty/eleventy#163]
Is there a way to minify the HTML output? I would like to have the output in the _sites folder to be minified. Right now I am doing that with a task runner, but it seems like it should be possible when eleventy complies everything.

**Comment by zachleat** [comment]
Yes! There is a pretty blunt API to transform output.

It’s called `Transforms`

It’s currently sync callbacks only but it could be very easily modified to work with async callbacks. Filed in #164.

https://www.11ty.io/docs/config/#transforms

**Comment by zachleat** [comment]
Make sure you check to make sure the outputPath has an `html` suffix. You don’t want to minify non-HTML stuff (I ran into this).

**Comment by zachleat** [comment]
Please reopen if you have more questions!

**Comment by zachleat** [comment]
@micahmills I just added the exact example you requested here: https://www.11ty.io/docs/config/#transforms

**Comment by micahmills** [comment]
Thanks Zach. This is really helpful. 

Micah
