### ISSUE TITLE
RSS (Feedburner) question

### ISSUE THREAD

**Issue by nathansmith** [11ty/eleventy#1637]
**INTRO**

Forgive me if this question has been answered already. I tried searching the repo issues but didn't see anything related.

I guess first I should ask…

1. Does anyone still use Feedburner?

2. Or is there something better nowadays?

---

**BACKSTORY**

That said…

I recently rebuilt my site using Eleventy. It is awesome (Eleventy, that is).

Because my site is super duper old — I think I registered the domain name 17 years or so ago — I have a lot of past blog posts that are generated to the feed XML file.

Feedburner seems not to like that, as it is over `1024 KB` in file size. I get this error.

> Your feed filesize is larger than 1024K. You need to reduce its size in order for FeedBurner to process it.

I am wondering, what is the Eleventy "best practice" way to handle that?

I suppose I could lob off the most recent `10` posts or something. Yeah?

If that is the best approach, would someone mind pointing me to an example for limiting items in a loop?

I know JavaScript itself fairly well, but not the Nunjucks syntax as much.

---

**OUTRO**

That pretty much covers it.

Thanks for all the hard work y'all have put into Eleventy.

It is a labor of love, and it shows. 🙌

**Comment by pdehaan** [comment]
I believe 11ty has an official [@11ty/eleventy-plugin-rss](https://www.11ty.dev/docs/plugins/rss/) for handling RSS feeds.

I haven't looked at the plugin in a while to see if it does limiting (most recent 10-20 posts or all posts), but Nunjucks should have builtin [`sort`](https://mozilla.github.io/nunjucks/templating.html#sort-arr-reverse-casesens-attr) and [`slice`](https://mozilla.github.io/nunjucks/templating.html#slice) filters you can use to order and transform the data however you want.

**Comment by nathansmith** [comment]
cc: @pdehaan 

Indeed, I am using that plugin.

I will read up on those Nunjucks filters. Thanks!

**Comment by pdehaan** [comment]
Actually, `slice` feels confusing to me (it doesn't take the first X items in an array like in JavaScript, it seems to want to zip them into nested arrays).

I'd say create your own filter to slice/splice the first X items from an array, or you might be able to use Nunjucks' builtin [`batch`](https://mozilla.github.io/nunjucks/templating.html#batch) and [`first`](https://mozilla.github.io/nunjucks/templating.html#batch) filters to get the job done. Ref: https://github.com/pdehaan/11ty-rss-plugin-test/blob/166893b3ffce3ba77aa24b6bd247fb94183287ff/src/feed.njk#L25

**Comment by nathansmith** [comment]
I just wanted to follow up and say I got this working.

As it turned out, all I needed was `| head(5)` at the end of my loop.

```njk
---
# Metadata comes from _data/metadata.json
permalink: "{{ metadata.feed.path }}"
eleventyExcludeFromCollections: true
---
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="https://w3.org/2005/Atom">
  <title>{{ metadata.title }}</title>
  <subtitle>{{ metadata.feed.subtitle }}</subtitle>
  {% set absoluteUrl %}{{ metadata.feed.path | url | absoluteUrl(metadata.url) }}{% endset %}
  <link href="{{ absoluteUrl }}" rel="self"/>
  <link href="{{ metadata.url }}"/>
  <updated>{{ collections.posts | rssLastUpdatedDate }}</updated>
  <id>{{ metadata.feed.id }}</id>
  <author>
    <name>{{ metadata.author.name }}</name>
    <email>{{ metadata.author.email }}</email>
  </author>
  {% for post in collections.posts | reverse | head(5) %}
    {% set absolutePostUrl %}{{ post.url | url | absoluteUrl(metadata.url) }}{% endset %}
    <entry>
      <title>{{ post.data.title }}</title>
      <link href="{{ absolutePostUrl }}"/>
      <updated>{{ post.date | rssDate }}</updated>
      <id>{{ absolutePostUrl }}</id>
      <content type="html">{{ post.templateContent | htmlToAbsoluteUrls(absolutePostUrl) }}</content>
    </entry>
  {% endfor %}
</feed>

```

**Comment by Ryuno-Ki** [comment]
Thanks for sharing the solution.
Would you mind closing this issue now?
