### ISSUE TITLE
Defining a shortcode for markdown

### ISSUE THREAD

**Issue by carlskii** [11ty/eleventy#1638]
Hi,

I need to render a block of HTML as part a blog post in 11ty. I need to add the name of `animation_script` defined in the markdown front matter file like this: 

```
---
title: Why running is incredible medicine for your brain
date: 2019-11-15
featured_image: /images/blog/post-3.jpg
image_caption: Photo by Spencer Dahl on Unsplash
excerpt: Running is a method of terrestrial locomotion allowing humans and other animals to move rapidly on foot. This is in contrast to walking, where one foot is always in contact with the ground, the legs are kept mostly straight.
tags:
    - blog
    - health
 animation_script: /animations/Venafi-Integrations.hyperesources/venafiintegrations_hype_generated_script.js
---
```  

Then have it render this block where the `src` is the value of the `animation_script` defined in the front matter to a where its referenced in the markdown text.

```
<div class="container mx-auto">
  <div id="venafiintegrations_hype_container" class="HYPE_document" style="margin:auto;position:relative;width:500;height:650px;overflow:hidden;">
		<script type="text/javascript" charset="utf-8" src="/animations/Venafi-Integrations.hyperesources/venafiintegrations_hype_generated_script.js?18914"></script>
	</div>
</div>
```

I've used Hugo previously and this is pretty easy using shortcodes, but can't seem to see go to do it in 11ty.

**Comment by pdehaan** [comment]
@carlskii I think there's probably at least 2 ways to do this:

**Option 1:** Using an `{% include %}` and having your shortcode markup in there.

```nunjucks
<!-- ./src/_includes/animation_script_inc.njk -->
<div class="container mx-auto">
  <div id="venafiintegrations_hype_container" class="HYPE_document" style="margin:auto;position:relative;width:500;height:650px;overflow:hidden;">
    <script type="text/javascript" charset="utf-8" src="{{ animation_script }}"></script>
  </div>
</div>
```

> **NOTE:** Since the include file here is a Nunjucks file, we use the `{{ animation_script }}` syntax for variable interpolation.

Then, in your main template, use the global include file like this:

```nunjucks
<aside>
  <h2>Option 1: <code>include</code></h2>
  {% include "animation_script_inc.njk" %}
</aside>
```

---

**Option 2:** Define a custom shortcode in your .eleventy.js config file.

```js
module.exports = (eleventyConfig) => {
  eleventyConfig.addShortcode(
    "animation_script_code",
    (animation_script_href = "") => {
      return `<div class="container mx-auto">
        <div id="venafiintegrations_hype_container" class="HYPE_document" style="margin:auto;position:relative;width:500;height:650px;overflow:hidden;">
          <script type="text/javascript" charset="utf-8" src="${animation_script_href}"></script>
        </div>
      </div>`;
    }
  );

  return {
    dir: {
      input: "src",
      output: "www",
    },
  };
};
```

> **NOTE:** Since this config file is a JavaScript file, and we're using template strings, we use the `${ animation_script }` syntax for variable interpolation, which is different than the Nunjucks example above.

Again, in your main template, use the custom shortcode like this:

```nunjucks
<aside>
  <h2>Option 2: <code>shortcode</code></h2>
  {% animation_script_code animation_script %}
</aside>
```

Notice that we're calling our custom "animation_script_code" shortcode, and passing it a parameter, which in this case is our `animation_script` variable defined in the frontmatter.

**Comment by carlskii** [comment]
Hi thanks very much for the prompt reply, this worked perfectly.
