### ISSUE TITLE
addNunjucksShortcode not working when used inside of a nunjucks include inside of an if/for statement

### ISSUE THREAD

**Issue by Georgegriff** [11ty/eleventy#1639]
**Update**
See comments i've found a solution, nunjucks has asyncEach (which is documented) and ifAsync which seems  undocumented  but works

**Describe the bug**
I've been using `addNunjucksShortcode` to do image transformation, and i've found when using `include` statements inside of other statements such as for loops or if statements, the include seems to fail.

**To Reproduce**
I have created a git repo with reprooduction steps

1. Go to clone   https://github.com/Georgegriff/11ty-async-short-codes-includes
2. npx @11ty/eleventy --serve
3. Open in browser
4. See that an image is missing

The code:

Just renders an image via an async shortcode for demo purposes

Include 'nested-partial.njk' in a template: https://github.com/Georgegriff/11ty-async-short-codes-includes/blob/main/index.md
2. `nested-partial.njk`: https://github.com/Georgegriff/11ty-async-short-codes-includes/blob/6646950b2ab05fb0e4cc3a4d991e74fb3956ead8/nested-partial.njk#L1-L3
3. `image.njk`:   https://github.com/Georgegriff/11ty-async-short-codes-includes/blob/6646950b2ab05fb0e4cc3a4d991e74fb3956ead8/image.njk#L1
4. https://github.com/Georgegriff/11ty-async-short-codes-includes/blob/6646950b2ab05fb0e4cc3a4d991e74fb3956ead8/.eleventy.js#L4-L6

https://github.com/Georgegriff/11ty-async-short-codes-includes/blob/6646950b2ab05fb0e4cc3a4d991e74fb3956ead8/nested-partial-sync.njk#L1-L3

It appears that the key thing  here is using async shortcode inside of includes which are included inside other statement breaks

**Expected behavior**
The repo provided should  render two  images, it only renders one

**Screenshots**
![image](https://user-images.githubusercontent.com/9056958/107878825-02d81a00-6ecd-11eb-8725-0fb64b68a646.png)

**Environment:**

- OS and Version: [e.g. Windows/Mac/Linux]
- Eleventy Version [via `eleventy --version` or `npx @11ty/eleventy --version`]

**Additional context**

**Comment by Georgegriff** [comment]
Its seems  like  for forLoops nunjucls has https://mozilla.github.io/nunjucks/templating.html#asynceach

Which seems to work! 

Not sure about if statements 🤔

**Comment by Georgegriff** [comment]
Wahey! I found an `undocumented?` asyncIf

```{% ifAsync true %}
{% include "image.njk" %}
{% endif %}
```

Which fixes it.


Maybe  the scopeof  this  ticket could be some sort oof documentation🤔

**Comment by dudesek** [comment]
hey george, I got a similar problem. probably the same.
what exactly fixes this?

`{% if page.url==='/'%}
    {% block hero %}
    {% include '../_components/_hero.njk' %}
    {% endblock hero %}
    {% endif %} `
and the hero.njk contains a shortcode which is not executed.

when I just do this...
`    {% block hero %}
      {% include '../_components/_hero.njk' %}
    {% endblock hero %}`
... it works.

sorry I don't even know how to get that code formatted correctly here... :)

**Comment by Georgegriff** [comment]
Here's some examples that worked for me:
if statements:

```html
{%- ifAsync gridCard -%}
{%- include "partials/grid-content.html" -%}
{%- endif %}
```

for loops:
```html
{%- set filteredComponents = helpers.filterComponents(components, collections.components) %}
{%- asyncEach component in filteredComponents -%}
    {%- ifAsync component.type === "custom" -%}
        {%- include component.componentPath -%}
    {%-else -%}
        {%- include component.componentPath -%}
    {%- endif -%}
{%- endeach -%}
```

**Comment by dudesek** [comment]
Thank you very much for the quick answer. I'll try this.
And sorry for the late reply, I was a bit distracted with other stuff...
