### ISSUE TITLE
Async Transforms

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#164]
Currently transforms are sync only.

https://www.11ty.io/docs/config/#transforms

Surfaced in #163.

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

The enhancement backlog can be found here: https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+

**Comment by tivac** [comment]
@zachleat Is this the code that actually applies the transforms?

https://github.com/11ty/eleventy/blob/5c0cd75e3652490eb52d2b2e6dc46f00ce14aa14/src/Template.js#L380-L386

Just started using eleventy and unfamiliar w/ the codebase, but I want to use rollup and am willing to do some work to try and make that happen.

**Comment by zachleat** [comment]
So I just added a test for this and it looks like the code works asynchronously with a single transform because it returns the last promise as `str` there. Starting in 0.7.0 it will work with multiple transform callbacks 😅

**Comment by zachleat** [comment]
This feature will ship with 0.7.0.
