### ISSUE TITLE
Rename .eleventy.js to .eleventyrc.js

### ISSUE THREAD

**Issue by rynz** [11ty/eleventy#1643]
**Is your feature request related to a problem? Please describe.**
Consistency between other `.*rc.js` configurations, eg: `.eslintrc.js`, `.prettierrc.js`

**Describe the solution you'd like**
Rename `.eleventy.js` to `.eleventyrc.js`

**Comment by zachleat** [comment]
Can you add this to https://github.com/11ty/eleventy/issues/1029 instead? We’ll want this to overlap with that one, I think.

**Comment by zachleat** [comment]
Oh I did want to also mention also that you can use `--config=./.eleventyrc.js` on any project today!
