### ISSUE TITLE
Accessing filters and other JavaScript functions inside EJS

### ISSUE THREAD

**Issue by hidegh** [11ty/eleventy#1651]
**Is your feature request related to a problem? Please describe.**

Currently I don't see a way to **access generic filters** added via ```eleventyConfig.addFilter``` inside **EJS**.

1. IT would be great if somehow basic filters, like: url, slug, etc. (and also custom ones) would be available in the templates which does not support filters.

**Describe the solution you'd like**

1. custom filters avail. in EJS

**Describe alternatives you've considered**

**Additional context**
When it comes to creating something more advanced, using JavaScript is straightforward, thus EJS has to be considered as the primary templating engine.

There would be some additional things to add: in case of error, **the EJS linter should output the line num and col num of the error**

**Comment by hidegh** [comment]
Not sure if there's a cleaner way?

Currently I found a way to achieve this. The last line of the ```.eleventy.js``` is:
```js
js = eleventyConfig.javascriptFunctions;
```
And in the template we can use:
```js
<%= js.slug("slugify this text and print it out") %>
```

**Comment by pdehaan** [comment]
TIL: EJS supports filters! https://github.com/tj/ejs#filters

**Comment by hidegh** [comment]
@pdehaan anyhow, those filters are just functions, so if functions are accessible in templates, then we are good.

**Comment by hidegh** [comment]
@pdehaan curious if you saw any EJS template with eleventy, as I'm trying to use one and inside front matter (which still should use liquid or nunjucks in my case) somehow **accessing the data variables (from directory data) are not working with EJS.**

**Comment by pdehaan** [comment]
@hidegh I haven't sorry. But I pretty much only use LiquidJS, Nunjucks, and .11ty.js templates in my projects.

The fact EJS doesn't seem to support filters natively seems like a deal breaker to me personally.

I saw you had it working using something like this:

```js
js = eleventyConfig.javascriptFunctions;
```

But I wasn't sure where `js` was defined, or if it's just leaking that variable into a global scope to make it accessible to your EJS templates.

---

Related: #1103 &mdash; I think that was on the roadmap for v1, but I have no idea when Eleventy v1 will be released and if a final decision was made on core languages vs ones that will be moved into plugins.

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!
