### ISSUE TITLE
Accessing global data inside front matter - is it possible?

### ISSUE THREAD

**Issue by hidegh** [11ty/eleventy#1655]
Was trying to access global YAML data in front matter (plan to use it on permalink) - but it neither works for title!

Is this a **BUG?** Or what's the valid way of using pure YAML to configuring things like title?

```js
---
title: "{{ globals.tags.path }}"
layout: default
permalink: tags/
---

<h1>{{ title }}</h1>

This works: {{ globals.tags.path }}

{% for tag in collections.tagList %}
    <a href="{{ '/tags/' | url }}{{ tag.value }}">
        {{ tag.text | capitalize }}
        <span>{{ tag.count }}</span>
    </a>
{% endfor %}
```

**Comment by pdehaan** [comment]
I think you need to use computed data: https://www.11ty.dev/docs/data-computed/

**Comment by hidegh** [comment]
@pdehaan
I was already using it for title elsewhere, but form permalink I wasn't sure. missed that, because if you check **vredeburg theme** and it's **tag paging**, simply in some cases you are able to access other generated properties/values outside ```eleventyComputed``` so it came natural to do so for simple things, like title.

I missed this, was my fault. **Thank you for the quick head-up.**

![image](https://user-images.githubusercontent.com/6331063/108756520-e8dfac80-7548-11eb-8e9d-a5594cb444c9.png)

Also next on my list is to use the same globals inside one of the filters, will surely work with require...

**Comment by pdehaan** [comment]
Yeah, I think `permalink` might be the only special exception that works w/ computed values without needing to use `eleventyComputed`.

**Comment by hidegh** [comment]
@pdehaan well, seems that not in this case.

anyhow, I'm now curious on something else, creating custom JS functions where I'd need to call the slug | url filters (functions). any cleaner way way to access those than:
```js
const urlFilter = require("@11ty/eleventy/src/Filters/Url");
const slugFilter = require("@11ty/eleventy/src/Filters/Slug");
```
...also if so, I think this might be noted in the documentation - these are some basics, which are needed if we do create paths / links in the templates...

**Comment by pdehaan** [comment]
> ... I'm now curious on something else, creating custom JS functions where I'd need to call the slug | url filters (functions). any cleaner way way to access those than:

I think it might depend on where you're trying to access those filters. Ref: https://www.11ty.dev/docs/filters/#access-existing-filters

But that implies that you have access to the current `eleventyConfig` instance.
Your solution works (require from deep within the `@11ty/eleventy` package), and I've done that in the past, but I also acknowledge that it's somewhat brittle if the paths to the filters change in the future and everything would probably break and throw errors on now-invalid `require()` paths.

**Comment by hidegh** [comment]
@pdehaan **yes, exactly.** currently I'd need the pathPrefix from the eleventyConfig inside my custom JS.

also not sure if the url filter should ensure that the path we provide is rooted - especially as the themes themselves do not use permalinks prefixed with /.
