### ISSUE TITLE
That bug where Eleventy would silently stop watching when a template compilation failed.

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#1658]
1. Run Eleventy in watch or serve mode.
2. Change a template with incorrect syntax so that it fails to compile.
3. Eleventy will stop watching but won’t quit or provide any console feedback. Eleventy will stop processing templates.

**Comment by zachleat** [comment]
Fixed by f39b93a2c372473f6d8dc4952d3e761b94a65423 and the changes for #1646

**Comment by reubenlillie** [comment]
@zachleat, I was convinced this was a feature. Or at least I eventually convinced myself of that as a coping mechanism.

**Comment by zachleat** [comment]
@reubenlillie 😅😅😅😅😅
