### ISSUE TITLE
Add to staticsitegenerators.net

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#166]
GitHub repo: https://github.com/bevry/staticsitegenerators-list
Live site: https://staticsitegenerators.net/

**Comment by jevets** [comment]
Made a pull req, but CI errors w/ different entries. Will keep messing w/ it
https://github.com/bevry/staticsitegenerators-list/pull/324

**Comment by zachleat** [comment]
I just checked this and we are on the site! Thank you for doing this @jevets!!
