### ISSUE TITLE
passthrough copy of .js files

### ISSUE THREAD

**Issue by mariusa** [11ty/eleventy#1663]
**Describe the bug**
Trying to get Eleventy to include .js files copied in /_site

**To Reproduce**
1. Tried
```
 eleventyConfig.setTemplateFormats([
        "md",
        "css",
        "jpg",
        "gif",
        "js",
        "wasm",
        "crane",
        "txt"
    ])
```
Issue: it looks like it's trying to interpret .js files?
```
Unhandled rejection in promise ([object Promise]): (more in DEBUG output)
> jQuery is not defined

`ReferenceError` was thrown:
    ReferenceError: jQuery is not defined
        at Object.<anonymous> (/.../assets/js/asa.js:176:4)
```

2. Tried
```
eleventyConfig.addPassthroughCopy("**/*.js")
```
it gives
```

`TemplateWriterWriteError` was thrown
> Having trouble copying './**/*.js'

`TemplatePassthroughManagerCopyError` was thrown
> Error copying passthrough files: ENOENT: no such file or directory, open '_site/_site/_site/_site/_site/docs/wasm_exec.js'
```

**Expected behavior**
Have a way to copy .js files in various folders, same as .jpg files
Ideally, enabled by default via a whitelist. I've read that nothing is copied so that secrets don't leak. We're building a site... ok to include images/js/css, exclude the rest.

**Environment:**

- OS and Version: Linux Fedora
- Eleventy Version [via `eleventy --version` or `npx @11ty/eleventy --version`]
0.11.1

**Additional context**

**Comment by btrem** [comment]
Is `_site` your input directory? Note that "Passthrough File Copy entries are relative to the root of your project and not your Eleventy input directory."

https://www.11ty.dev/docs/copy/#manual-passthrough-file-copy-(faster)

So you might instead try

    eleventyConfig.addPassthroughCopy("_site/**/*.js")

**Comment by mariusa** [comment]
Hi,

> Is _site your input directory?

no, that's the output. .js files are in `assets/js/` and other folders, same as html.

`    eleventyConfig.addPassthroughCopy("**/*.jpg")` works.

` eleventyConfig.addPassthroughCopy("**/*.js")` gives

```
Error with passthrough copy: (more in DEBUG output)
> Having trouble copying './**/*.js'

`TemplatePassthroughManagerCopyError` was thrown
> Error copying passthrough files: ENOENT: no such file or directory, open '_site/assets/js/components/hs.bg-video.js'

$ ls assets/js/components/hs.bg-video.js
assets/js/components/hs.bg-video.js
```

**Comment by pdehaan** [comment]
I would probably suggest you put your passthrough copy assets in a specific directory. I personally find patterns like '/**/*.js' a bit confusing at quick glance because I don't know if it'd copy the passthrough assets, the input directory assets, the output directory assets, a mix of all 3, or something else entirely. But since I keep my *.js files outside of my source directory, Eleventy won't try and process them and just copies them over as-is.

Here's my sample directory/file structure:

```sh
tree -I node_modules

.
├── package-lock.json
├── package.json
│
├── src # dir.input
│   ├── _includes
│   │   └── layouts
│   │       └── base.liquid
│   └── pages
│       └── index.liquid
│
├── static # addPassthroughCopy()
│   ├── css
│   │   └── site.css
│   └── js
│       └── site.js
│
└── www # dir.output
    ├── index.html
    └── static
        ├── css
        │   └── site.css
        └── js
            └── site.js

11 directories, 9 files
```

and my .eleventy.js config file looks something like this:

```js
const del = require("del").sync;

module.exports = eleventyConfig => {
  // Clean the output directory.
  del("./www/");

  eleventyConfig.addPassthroughCopy("./static/");

  return {
    dir: {
      input: "src",
      output: "www"
    }
  }
};
```

Now when I run a build, it will compile everything in `./src/` and copy everything from `./static/` and put them in my output directory, `./www/`.

I pushed my sample repo to https://github.com/pdehaan/11ty-passthrough-copy if you're curious.

**Comment by mariusa** [comment]
Ok, thanks, getting there.

In `./static/` I have some files, eg robots.txt (just an example) and '/assets'. I'd like these to be copied in the root of the output.

> eleventyConfig.addPassthroughCopy("./static/")

this results in `www/static/assets/...`

How to get `www/assets/...`, `www/robots.txt` ?

I tried `eleventyConfig.addPassthroughCopy("./static/*")` but then only robots.txt is copied, no folders.

**Comment by btrem** [comment]
So this doesn't sound like a bug report, then, but a misconfiguration.

What *is* your input directory? and is www/static/ inside that input directory? It would help if you could sketch out the basic directory structure of your project, as  pdehaan did. It doesn't need to be complete, maybe just the first level directories.

**Comment by pdehaan** [comment]
@mariusa How about this?

```js
eleventyConfig.addPassthroughCopy({ "static": "." });
```

That should give you something like this:

```sh
tree -I node_modules    
.
├── package-lock.json
├── package.json
│
├── src/
│   ├── _includes/
│   │   └── layouts/
│   │       └── base.liquid
│   └── pages/
│       └── index.liquid
│
├── static/
│   ├── css/
│   │   └── site.css
│   ├── js/
│   │   └── site.js
│   └── robots.txt
│
└── www/
    ├── css/
    │   └── site.css
    ├── index.html
    ├── js/
    │   └── site.js
    └── robots.txt

10 directories, 11 files
```

Now if you want the css/ and js/ folders in the output directory at a different level, you can just nest them however you want in the /static/ directory.

**Comment by mariusa** [comment]
Thanks Peter, that works great! Appreciate your time.

This is much easier than the default setup at https://www.11ty.dev/docs/copy/
and .js files work too!
Wish I knew to start with this when learning about 11 (moving from jekyll). Thanks again!

**Comment by mariusa** [comment]
@btrem I googled why jpg/js files aren't copied, and discovered https://www.11ty.dev/docs/copy/
But the setup described above is much better/simpler, should be in the official docs.
