### ISSUE TITLE
Trouble with pagination

### ISSUE THREAD

**Issue by djdrysdale** [11ty/eleventy#1664]
I'm using Eleventy with Eleventy-Garden to host some notes as well as a blog. 

I am trying to use pagination to display the most recently published notes but for some reason it will only display nine notes on the page, no matter how I've set up pagination. 

This is what my code looks like: 

```
---
layout: default
title: Notes
pagination:
  data: collections.notes
  size: 10
  reverse: true
---
```

and then 

 ```
   <div class="row py-4">

      {% for note in pagination.items %}
        <div class="card-body col-12 col-md-6 border-bottom py-10 px-10">
            <p class="card-text">
              <a href="{{ note.url }}">{{ note.data.title }}</a>
            </p>
            <p class="card-text">
              {{ note.data.description }}
            </p>
            <p>
              <a href="{{ note.url }}">Read more...</a>
            </p>

        </div>
      {% endfor %}

    </div>
```

Everything works out great, except no matter what I set as size, it shows nine notes per page.

**Comment by pdehaan** [comment]
Code looks correct (but I've never used Eleventy-Garden, so not 100% sure how it works. or how the collection is created).
Do you have a public repo somewhere I can clone and test locally?

**Comment by djdrysdale** [comment]
Ugh. I feel foolish—I just figured it out. The code above was from a layout file that was being used by an index.md that was setting pagination at 9. I had it in the wrong place. (I'm pretty new to this stuff.)

**Comment by pdehaan** [comment]
No problem. Welcome to Eleventy! 🎉

**Comment by Ryuno-Ki** [comment]
Would you mind to close this issue then?
