### ISSUE TITLE
Get rid of collection object pollution due tag 'over-use'

### ISSUE THREAD

**Issue by hidegh** [11ty/eleventy#1668]
**Describe the bug**
Due to tags the collection object get's easily **polluted** - especially with lot of tags in use - see: https://www.11ty.dev/docs/collections/#multiple-tags-multiple-lines

Plz. consider using a **collection.tags** as an object which holds all the automatically resolved collections by a concrete tag...
...so the code in the sample (documentation) would turn to **collection.tags.cat**, **collection.tags.dog**

Would be ideal to introduce this in a major version change, so 1.x
@zachleat 

**To Reproduce**
See current behavior with 20+ tags...

**Expected behavior**
Minimal change in the collection object, making it less polluted (avoiding eventual overwrites with manually added collections, etc.)

**Screenshots**
n/a

**Environment:**
- OS and Version: w10
- Eleventy Version: 0.11.1

**Additional context**
n/a

**Comment by zachleat** [comment]
Sorry, I don’t think I quite understand—why is `collections.tags.cat` better than `collections.cat`?

**Comment by edwardhorsford** [comment]
@zachleat To me, the current set up pollutes the collections namespace - especially when you have lots of tags. I have lots of other things in frontmatter / under `collections`, and I don't need my tags all at that level too - I'd _much_ prefer if all my tags were collected under a namespace.

The other way of looking at it is that they're all of a certain type of thing - so it makes sense they be under their own namespace. If I was adding other data that has multiple of a thing I'd likely put it under a namepsace to collect them.

I think I've seen a number of issues discuss this - will try to dig up.

**Comment by edwardhorsford** [comment]
Related: https://github.com/11ty/eleventy/issues/1254

**Comment by zachleat** [comment]
Ah hmm—I think we should probably organize over at #1254 for this one. More progress over there, thanks!
