### ISSUE TITLE
Add to Awesome Static Web Site Generators

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#167]
Live site: https://myles.github.io/awesome-static-generators/
GitHub repo: https://github.com/myles/awesome-static-generators

**Comment by jdsteinbach** [comment]
https://github.com/myles/awesome-static-generators/pull/22

**Comment by zachleat** [comment]
Thanks @jdsteinbach!!

**Comment by zachleat** [comment]
Closing.
