### ISSUE TITLE
Add meta name=generator tag to identify page is build using eleventy

### ISSUE THREAD

**Issue by akmittal** [11ty/eleventy#1672]
**Is your feature request related to a problem? Please describe.**
Add a feature to identify that a page is build using eleventy.

**Describe the solution you'd like**
Add a `<meta name="generator" content="eleventy">` to all the build pages. generator meta is a HTML5 standard https://html.spec.whatwg.org/multipage/semantics.html#standard-metadata-names

**Describe alternatives you've considered**
 _

**Additional context**
Almost all static site generator like Hugo, Jekyll, hexo, and other tools like WordPress support it.

If this is something eleventy plan to include, I can work on a pull request for change.

**Comment by nhoizey** [comment]
There is already an issue for this: #1217

**Comment by akmittal** [comment]
Closing this one then.

**Comment by Ryuno-Ki** [comment]
@akmittal I'd welcome if you would open a new issue over at my repo.
Currently quite busy, but I'd have everything I need once I can pick it up again.

**Comment by zachleat** [comment]
Cross posting the solution for this shipping soon https://github.com/11ty/eleventy/issues/2293#issuecomment-1100257803
