### ISSUE TITLE
Build failures from Nunjucks monkey patch

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#1678]
I had to (temporarily?) disable the Nunjucks modifications from #1529 as they were causing numerous test failures on the latest master.

cc @slightlyoff 

Hoping to get some time to re-evaluate.

**Comment by zachleat** [comment]
Shipping with Canary 42

**Comment by Ryuno-Ki** [comment]
The failures or the patch? :grimacing:

**Comment by zachleat** [comment]
the fixed patch!

**Comment by pdehaan** [comment]
Ref #1960. I was able to fix that issue by explicitly opting out of `ELEVENTY_NUNJUCKS_SPEEDBOOST_OPTOUT`, which seems to have been introduced by the related 0eee96d commit in the latest v1.0.0-canary.42 release. /cc @zachleat

**Comment by zachleat** [comment]
As stated in https://github.com/11ty/eleventy/issues/1960#issuecomment-913837973 we’re going to swap this env variable to `ELEVENTY_NUNJUCKS_SPEEDBOOST_OPTIN` and turn it off by default.
