### ISSUE TITLE
Cross-referencing global data in js data files

### ISSUE THREAD

**Issue by stevenk99** [11ty/eleventy#1679]
Can I ask anyone's feedback of referencing eleventy global data in one JavaScript data file from another.
By way of a much simplified made-up example, I've used two global data files, to represent football _divisions_ and _teams_:

**_data/divisions.js** - nosql array of all divisions
```javascript
// returns [{"id":1,name:"Premiership",{"id":2,name:"Division 2"},...]
const fetch = require('node-fetch');
module.exports = async function() {
    let resp = await fetch('/_api.asp?a=divisionsget');
    return await resp.json();
}
```

**_data/teams.js** - nosql array of all teams
```javascript
// returns [{"id":1,name:"Liverpool",divid:1},{"id":2,name:"Arsenal",divid:1},...]
const fetch = require('node-fetch');
module.exports = async function() {
    let resp = await fetch('/_api.asp?a=teamsget');
    return await resp.json();
}
```
Now I understand it is possible to 'cross-reference' global data in a layout, for example, using a filter, say, to pick out the relevant team's division:

**filters/findinarray.js**
```javascript
module.exports = function(arr, propkey, propval) {
    return arr.find(item => item[propkey] === propval);
}
```
**.elevently.js**
```javascript
module.exports = function(eleventyConfig) {
    eleventyConfig.addFilter("findinarray", require("./filters/findinarray"));
}
```
**teams.liquid** - eg "Liverpool play in the Premiership"
```javascript
{% assign this_team_div = divisions | findinarray: "divid", team.divid %}
{{ team.name }} play in the {{ this_team_div.name }}
```
but something similar in the data file does not work, throwing a reference  error "divisions is not defined":

**_data/teams.js**
```javascript
const fetch = require('node-fetch');
module.exports = async function() {
    let resp = await fetch('/_api.asp?a=teamsget');
    let data = await resp.json();
	data.map(team => {
		team.division = findinarray(divisions, "divid", team.divid);
		return team;
	});
	return data;
}
```
This is likely obvious to you why it fails, but I'm not sure. Maybe it is possible somehow, with a require or something. The filter itself is not important, its the access to the other global data I want to understand.

So to get round this, we can throw the data 'sets' into a node module to inter-relate the data:

**mymodules/football.js**
```javascript
const fetch = require('node-fetch');
const getdivisions = async () => {
    let resp = await fetch('/_api.asp?a=divisionsget');
    let divs = await resp.json();
    return divs ;
};
const getteams = async () => {
    let resp = await fetch('/_api.asp?a=teamsget');
    let teams = await resp.json();
    return teams;
};
exports.getdivisions = getdivisions;
exports.getteams = getteams;
```

**_data/divisions.js** - 
```javascript
// each division now includes the teams that belong to it
const football = require('../mymodules/football.js');
module.exports = async function() {
	var divisions = await football.getdivisions();
	var teams = await football.getteams();
	divisions.map(div => {
		div.teams = teams.reduce(team=>team.divid=div.id);
		return div;
	});
	return divisions;
}
```
**_data/teams.js**
```javascript
// each team now includes its division
const football = require('../mymodules/football.js');
module.exports = async function() {
    var teams = await football.getteams();
    teams.map(team => {
        team.division = findinarray(divisions, "divid", team.divid);
        return team;
    });
    return teams;
}
```
Instead of modules, could we place all data into one global data file that every layout refers to, which might mean fewer calls in a pagination build perhaps?:

**_data/footballdata.js**
```javascript
const fetch = require('node-fetch');
module.exports = async function() {
    let resp = await fetch('/_api.asp?a=teamsget');
    let teamdata = await resp.json();
    let resp2 = await fetch('/_api.asp?a=divisionsget');
    let divdata = await resp2.json();
    return { "teams": teamdata, "divisions: divdata }
}
```

What method(s) would you recommend to inter-link global data, principally for more complex models than this example? For example, is the api called unnecessarily and repeatedly when building multiple html files using pagination? I wonder if there is some caching solution. Any thoughts, alternatives, recommendations or feedback would be appreciated.

**Comment by NVolcz** [comment]
Did you find a solution for your question? I am facing the same challenge
