### ISSUE TITLE
Can Eleventy make page for each binary file?

### ISSUE THREAD

**Issue by alihardan** [11ty/eleventy#1680]
Hello,

It's my first message on this project and I want to thank you very much for this excellent project.

**Is it possible to make Eleventy generates html file for each binary file? How?** In this case, I want to make html output for each mp3 file, and I will read metadata tags of each mp3 using third-party library and print them in html output.

**Comment by pdehaan** [comment]
@alihardan Yeah, should definitely be possible.

I have a /_data/mp3s.js [global data file](https://www.11ty.dev/docs/data-global/) which finds all *.mp3 files using a glob pattern and returns the filename+id3 info (using the [**node-id3**](http://npm.im/node-id3) module, then you can [paginate](https://www.11ty.dev/docs/pagination/) over that array and build dynamic pages.


```js
// /_data/mp3s.js
const path = require("path");

const globby = require("globby");
const NodeID3 = require("node-id3");

const baseDir = path.join(__dirname, "..", "assets");
const mp3Path = path.join(baseDir, "*.mp3");

module.exports = async () => {
  const mp3s = await globby([mp3Path]);
  const res = [];
  for (const file of mp3s) {
    const id3 = await NodeID3.read(file);
    res.push({ file: file.replace(baseDir + path.sep, ""), ...id3 });
  }
  return res;
};
```

```js
---
# /index.liquid
layout: layouts/base.liquid
pagination:
  data: mp3s
  size: 1
  alias: mp3
permalink: "{{ mp3.file | replace: '.mp3', '' }}/"
eleventyComputed:
  title: "{{ mp3.file }}"
---

<h1>{{ mp3.file }}{% if mp3.genre %} ({{ mp3.genre }}){% endif %}</h1>

<pre>{{ mp3 | json }}</pre>
```

I pushed my repo to https://github.com/pdehaan/11ty-id3-test, but I didn't have a lot of mp3s locally, so it will probably have a few issues with more complex metadata. I also didn't push any mp3s into GitHub, so I think you'd have to clone the repo, and put your mp3s into ./src/assets/ if you wanted to see if that works for you.

**Comment by alihardan** [comment]
@pdehaan, Thank you very much for your quick explanation and answer. I have cloned your [11ty-id3-test](https://github.com/pdehaan/11ty-id3-test) repo and tested it, It did the job without any problem 😉.

Thank you again for your quick & clean explanation.

**Comment by pdehaan** [comment]
No problem. Feel free to close the issue.
