### ISSUE TITLE
FR / Docs - how to write a plugin, that has a partial template which is then accessible in the main solution

### ISSUE THREAD

**Issue by bhideghety-SPC** [11ty/eleventy#1681]
The basic idea is to provide some functionality within a plugin, **along with some basic rendering.**

**Based on the current code-base I do not see how a _include/** from the plugin directory would be added to the main eleventy.**

Expectations:
1. inside plugin, we could be limited to use the default _includes directory
2. but inside the final eleventy solution, the overrides (to includes) should be honored

Sample:
```{% include 'partials/sample-partial.html' %}``` - where the partials/sample-partial.html is part of the plugin...

NOTE: Some other JAMSTACK projects do have a way to include full themes (which are having almost the same structure as the main project).

**Comment by Ryuno-Ki** [comment]
Related to #930.

**Comment by bhideghety-SPC** [comment]
@Ryuno-Ki yes, **partially** it's related.

**On the other hand, the current behaviour of templates inside the _include/partials folder can be considered as a bug (or a falsy expectation).**

**Comment by zachleat** [comment]
#1612 is this feature!
