### ISSUE TITLE
Markdown fenced code gets interpreted by templating language

### ISSUE THREAD

**Issue by ThePeach** [11ty/eleventy#1683]
**Describe the bug**
I am using Markdown files and Handlebars.JS as templating language.
In my file I have some examples that illustrate how Handlebars works including some fenced code using Handlebars in it like the following
```
`\``handlebars
<h1>{{title}}</h1>
`\``
```

This cause the whole `{{title}}` part to be interpreted, although by being wrapped around a `<pre><code class="language-html.handlebars"></code></pre>` as expected.

**Expected behavior**

the output should be exactly as written.

**Environment:**

- OS and Version: [e.g. Windows/Mac/Linux] Linux
- Eleventy Version [via `eleventy --version` or `npx @11ty/eleventy --version`]: 0.11.1

**Additional notes**
Fenced out code shouldn't be interpreted. 
If this is the intended behaviour, I'd expect some way to be able to disable the interpretation of the markdown-generated HTML, so it won't be interpreted entirely by the downstream templating language.

**Comment by pdehaan** [comment]
@ThePeach I think you need to wrap your code blocks w/ `{% raw %}...{% endraw %}` if you don't want their contents parsed by the template engine.

https://liquidjs.com/tags/raw.html
https://mozilla.github.io/nunjucks/templating.html#raw

**Comment by ThePeach** [comment]
thanks a lot @pdehaan I completely missed that!
