### ISSUE TITLE
BrowserSync config lost in Canary 1.0

### ISSUE THREAD

**Issue by TigersWay** [11ty/eleventy#1684]
**Describe the bug**
it seems we lost being able to set a browsersync config in eleventy config file.

**To Reproduce**
```
module.exports = (eleventyConfig) => {
  eleventyConfig.setBrowserSyncConfig({
    port: 3000,
    open: true,
  });
...
```
Setting port (or anything else) inside eleventy config file (default one or not) will not be used.

**Expected behavior**
Same as the official version of course :-) as of today v0.11.1

**Environment:**

- Windows 10
- Eleventy v0.11.1 vs v1.0.0-canary.10

**Comment by btrem** [comment]
I am using 11ty 0.11.1 and I can successfully change the port number to 3000 using your code. I can change other options inside my `setBrowserSyncConfig` block. Are there any error messages when you run `11ty --serve`?

**Comment by TigersWay** [comment]
> I am using 11ty 0.11.1 and I can successfully change the port number to 3000 using your code. I can change other options inside my `setBrowserSyncConfig` block. Are there any error messages when you run `11ty --serve`?

Everything works with @11ty/eleventy@0.11.1 with the standard config file and with a differently named one.
Strangely, with the last "canary" a differently named one is read but the browser-sync part is not used.

**Comment by pdehaan** [comment]
@TigersWay Interesting. I can reproduce w/ canary.10 (latest on npm's `@canary` dist-tag):

```sh
> eleventy --serve

{ label: 'before', cfg: {} }
{ label: 'after', cfg: { port: 5000, open: true } }
Writing www/index.html from ./src/index.njk
Wrote 1 file in 0.07 seconds (v1.0.0-canary.10)
Watching…
[Browsersync] Access URLs:
 ----------------------------------
    Local: http://localhost:8080
 External: http://192.168.0.27:8080
 ----------------------------------
[Browsersync] Serving files from: www
```

```js
module.exports = (eleventyConfig) => {
  console.log({label:"before", cfg: eleventyConfig.browserSyncConfig});

  eleventyConfig.setBrowserSyncConfig({
    port: 5000,
    open: true,
  });

  console.log({label:"after", cfg:eleventyConfig.browserSyncConfig});

  return {
    dir: {
      input: "src",
      output: "www",
    }
  };
};
```

So even though I specified port 5000, it used 8080. Not much of a workaround, but I was able to set the port via the CLI using the `--port=4003` arg, although your `open:true` is still ignored.

**Comment by TigersWay** [comment]
Exactly @pdehaan! No worry yet, it's just a "canary" :-) But preparing a new starter when 1.0 will come, I had to share!

**Comment by pdehaan** [comment]
yeah, I was playing with something else the other week (using Eleventy as an API, I believe) and noticed a fairly big refactoring in how the configurations worked between 0.11 and 1.0@canary, so maybe there are still a few bugs to be worked out, or maybe the Canary tag was just for testing something else and is still pre-alpha. 🤷 

Good find though! :+1:

**Comment by zachleat** [comment]
Sorry about that! I pushed a fix, it’ll go up with canary 16
