### ISSUE TITLE
Advice for creating photography portfolio

### ISSUE THREAD

**Issue by kaviars** [11ty/eleventy#1685]
Hello,

Not sure how to tackle the Eleventy to structure the content. Hopefully someone can give advice.
Photographs are divided into groups (tags): interior, portraits, miscellaneous. Each has seperate page, f.ex. `website.com/miscellaneous/` where photographs are stacked one after other. My concern is pages, which has inner pages with multiple photographs. F.ex. `website.com/interior/cottage-house/` which is accessed from `website.com/interior/ `that just like `website.com/miscellaneous/` has photos stacked one after another.

If I would not have the inner pages, I could get my website done by JSON file stored in _data, but since some photographs have links "see more", I dismiss the idea using JSON.

To describe the desired result, see raw sketch:
![portfolio](https://user-images.githubusercontent.com/43539461/110932353-088e1780-8334-11eb-9533-2cd61b1109c8.png)

**Comment by btrem** [comment]
I'm not sure I follow what you're asking. Like why having sub pages mean you can't use json. Can you provide an example of the json you would use if there weren't sub pages? Just a small example should suffice. With that, maybe I can see your problem more clearly.

**Comment by zachleat** [comment]
Howdy! Sorry about this but I really think this would be better suited on the Discussions board! https://github.com/11ty/eleventy/discussions

I’m going to try Converting it, we’ll see if that works.
