### ISSUE TITLE
"TypeError: cannot eval as value" in Nunjucks block inside markdown file when `if` inside `for` loop

### ISSUE THREAD

**Issue by lieuzhenghong** [11ty/eleventy#1693]
A perfectly correct Nunjucks template will throw a TypeError when put in a `.md` rather than a `.njk` file. I think this could be related to the render rules of nunjucks blocks inside markdown files.

In a `test.njk` file have the following template:
```njk
<ol>
{%- for post in collections["6.824"] -%}
  {%- if post in collections.lab -%}
    <li><a href="{{ post.url | url }}"> {{post.data.title}} </a></li>
  {%- endif -%}
{%- endfor -%}
</ol>
```

This will render with no problems.

In a `test.md` file also do the following:
```njk
# Test
<!-- This will throw a TemplateContentRenderError -->
<ol>
{%- for post in collections["6.824"] -%}
  {%- if post in collections.lab -%}
    <li><a href="{{ post.url | url }}"> {{post.data.title}} </a></li>
  {%- endif -%}
{%- endfor -%}
</ol>
```

You will get the following error:

```
> Having trouble rendering liquid (and markdown) template ./root/moocs.md

`TemplateContentRenderError` was thrown
> cannot eval 'post in collections.lab' as value, file:./root/moocs.md, line:35

`RenderError` was thrown
> cannot eval 'post in collections.lab' as value

`TypeError` was thrown:
    TypeError: cannot eval 'post in collections.lab' as value
```

**Comment by pdehaan** [comment]
I'm a bit confused. Is the issue that Nunjucks supports the `if post in collections.lab` syntax, but LiquidJS doesn't?

If you don't want to use LiquidJS as your default .md template engine, you should be able to set it to Nunjucks using https://www.11ty.dev/docs/config/#default-template-engine-for-markdown-files

**Comment by pdehaan** [comment]
> _"I think this could be related to the render rules of nunjucks blocks inside markdown files."_

Ah, I think I misunderstood your original issue. By default **LiquidJS** parses .md files, not Nunjucks. So you'll need to set that `markdownTemplateEngine: "njk"` in your .eleventy.js config file if you want Nunjucks to preprocess your Markdown files.

**Comment by lieuzhenghong** [comment]
@pdehaan  Thanks for the heads up! I didn't know that LiquidJS was the default template engine.

Putting `templateEngineOverride: njk, md` in the front matter of my markdown file (documentation [here](https://www.11ty.dev/docs/languages/#templateengineoverride-examples) fixed the issue.

Closing.
