### ISSUE TITLE
add more tutorials

### ISSUE THREAD

**Issue by TrentonAdams** [11ty/eleventy#1694]
Hi Guys,

I think the documentation for eleventy is really great, and covers everything that's needed.  The only critique I'd have is that the tutorials seem to just end, without giving newcomers a complete picture of how eleventy works.  The first two provide really nice and simple examples of their respective subjects.  I see these tutorials as "points of reference".  

Posting a bunch of links to random blog posts is great too, but without a point of reference for understanding the ins/outs of eleventy, they aren't quite as valuable as they could be.

Currently eleventy has two tutorials.  I think it would be useful to continue with those, and provide more very concise examples of different core features of eleventy. If those tutorials were completed, then all the blog posts would be super valuable because they are now providing info on "ways that eleventy can be used", to sort of broaden people's understanding of all the features eleventy has.

1. Level 3 - Use collections and adding new ones
2. Level 4 - Data Cascade - the simplest of overviews of the cascade, as it's already thoroughly documented.  I think this one is important as there's quite a bit of docs on the data cascade and how it works, and they are too long for a concise post about it.  But, it should maybe also cover some various examples, and perhaps a list of data cascade types (data files, js files, sub directory json/js files, computed data, etc.
3. Level n - Perhaps just links to some of the other docs.  e.g. layouts, creating pages from data, etc

Thanks.

**Comment by DirtyF** [comment]
For anytone looking for a complete tutorial on Eleventy, just read the awesome [Learn Eleventy from Scratch](https://piccalil.li/course/learn-eleventy-from-scratch/) by Andy Bell. You'll get the full tour as well as best front end practices.

---

For people looking to write documentation, this talk by Daniele Procida might help.

[![documentation-map](https://user-images.githubusercontent.com/103008/127234736-bf826fc6-afce-42b5-a2c2-6bc3b0cbd529.png)](https://youtu.be/qC1OYK5oqDo "Watch What you Need to know about your documentation on youTube")

Documentation usually ecompasses:
- Tutorials (realise a project like the one above to learn by doing)
- How-to guides (complete specific tasks, e.g. https://www.11ty.dev/docs/quicktips/, https://www.11ty.recipes)
- Explanations (to clarify a particular topic)
- Reference (the one you refer to when in doubt on some part of the machinery)

Open source Software using this documentation pattern: [Gatsby](https://www.gatsbyjs.com/docs), Cloudflare,[ Django CMS](https://docs.django-cms.org/en/latest/)

**Comment by zachleat** [comment]
https://11tybundle.dev/categories/ is a _great_ resource too!
