### ISSUE TITLE
Un-ignore rules have no effect

### ISSUE THREAD

**Issue by dan-welty** [11ty/eleventy#1695]
**Describe the bug**
Un-ignore rules have no effect in either `.gitignore` or `.eleventyignore`.

**To Reproduce**

Ignore files in `.gitignore`:
```
/src/asset/style/*.css
```

Un-ignore an ignored file in either `.gitignore` or `.eleventyignore`:
```
!/src/asset/style/base.css
```

Build the site (`npx @11ty/eleventy`) and notice that the un-ignored file (`/asset/style/base.css`) does not exist in the built site.

**Expected behavior**
The un-ignored file (`/asset/style/base.css`) should appear in the built site.

**Environment:**

- OS and Version: Kubuntu 20.04
- Eleventy Version: 0.11.1

**Comment by pdehaan** [comment]
Possibly related/relevant: #693

**Comment by dan-welty** [comment]
> Possibly related/relevant: #693

Yes, this issue appears to be a duplicate of #693. My apologies; I only searched through open issues before opening this one.

**Comment by zachleat** [comment]
Yes please subscribe to #693! Thanks!
