### ISSUE TITLE
[Feature req] Add a 'builtFiles' array to the afterBuild event

### ISSUE THREAD

**Issue by matt-auckland** [11ty/eleventy#1706]
**Is your feature request related to a problem? Please describe.**
Currently I run an `afterBuild` event hook with prettier to tidy up my built files so they look  pretty when you "View Source". 

However, because prettier is kind of slow, I don't want to format all my built files on every save (while using `--serve`), because not every file is going to be rebuilt. Because prettier has no context of what 11ty is doing I've had to figure out what files have changed myself and then tell prettier what to format.

Basically I create a dictionary of `filePaths:fileHashes` and after build I check if any files have changed by comparing against this, and then I use prettier to format any files that changed.

https://github.com/matt-auckland/personal-site/blob/master/utils/formatFiles.js

**Describe the solution you'd like**
Similar to how the `beforeWatch` event passes through a `changedFiles` array, I was thinking that the `afterBuild` event could pass a `builtFiles` array that would have the paths of all recently built files. 

This would allow for prettier to be told which specific files to format. It also opens up opportunity for other post build processes that people might implement to run more efficiently/be simpler to write.

**Describe alternatives you've considered**
I could just turn off formatting while using `--serve` but that could prevent me from catching any prettier related bugs caused by formatting.

EDIT: I am open to helping create a PR to add this feature, but I'll need a bit of guidance, 11ty internals seem slightly complicated without any context

**Comment by zachleat** [comment]
Code for this would live here https://github.com/11ty/eleventy/blob/975816f9d53d480fc22d757b91d69a785dfd50aa/src/Eleventy.js#L947

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
This shipped with https://github.com/11ty/eleventy/commit/685543ec4b929885055ef2b36d99a532f2de2cb6 as part of the work for https://github.com/11ty/eleventy-plugin-vite/ https://github.com/11ty/eleventy/commit/d1f48f77462d09d8b77ddcf0bbaa7faffb306e51

Available in Eleventy 2.0.0-canary.4

**Comment by zachleat** [comment]
See the `results` prop on `eleventy.after` https://www.11ty.dev/docs/events/#eleventy.after
