### ISSUE TITLE
Typo in eleventy-img docs' SYNCHRONOUS USAGE

### ISSUE THREAD

**Issue by hyunbinseo** [11ty/eleventy#1713]
Following is the example code in [SYNCHRONOUS USAGE](https://www.11ty.dev/docs/plugins/image/#synchronous-usage) docs.

There is a typo in `metadata = Image.statsSync(source, options);`.

Variable `source` is not defined. Appears to be typo of `src`.

```
const Image = require("@11ty/eleventy-img");
function imageShortcode(src, cls, alt, sizes, widths) {
  // 'options' is never reassigned. Use 'const' instead.
  let options = {
    widths: widths,
    formats: ['jpeg'],
  };

  Image(src, options);

  // 'imageAttributes' is never reassigned. Use 'const' instead.
  let imageAttributes = {
    class: cls,
    alt,
    sizes,
    loading: "lazy",
    decoding: "async",
  };

  // 'metadata' is not defined.
  // 'source' is not defined. ← Typo of 'src'
  metadata = Image.statsSync(source, options);
  return Image.generateHTML(metadata, imageAttributes);
}
```

Therefore, proposing the following example code.

```
const Image = require('@11ty/eleventy-img');

const imageShortcode = (src, cls, alt, sizes, widths) => {
  const options = {
    widths,
    formats: ['jpeg'],
  };

  Image(src, options);

  const imageAttributes = {
    class: cls,
    alt,
    sizes,
    loading: 'lazy',
    decoding: 'async',
  };

  const metadata = Image.statsSync(src, options);
  return Image.generateHTML(metadata, imageAttributes);
};
```

Changed to arrow function as it is used in [USAGE](https://www.11ty.dev/docs/plugins/image/#usage) example code.

**Comment by pdehaan** [comment]
@hyunbinseo I think you might need to file this in the documentation repo at https://github.com/11ty/11ty-website/.

Or if you want to submit a Pull Request with the changes, the file seems to be https://github.com/11ty/11ty-website/blob/master/docs/plugins/image.md

**Comment by hyunbinseo** [comment]
@pdehaan Thank you for the mention.

The description for the issue template `Documentation` is as follows.

```
Documentation!
A thing that Eleventy does needs to be documented better or is currently documented incorrectly!
```

Since the doc. `is currently documented incorrectly!`, the issue is created in this repo .

If this issue is legitimate, I will indeed create a Pull Request at the above provided [link](https://github.com/11ty/11ty-website/blob/master/docs/plugins/image.md).

**Comment by hyunbinseo** [comment]
Fixed in https://github.com/11ty/11ty-website/commit/5cc76e201dc7f960c98c04ad45983846e9848c15
