### ISSUE TITLE
Could not resolve pagination key in template data

### ISSUE THREAD

**Issue by einomi** [11ty/eleventy#1739]
**Describe the bug**
I'm trying to generate pages from _data/data1.json file using the pagination feature but get `Could not resolve pagination key in template data` error during the build. This is the example repo https://github.com/frontenso/500k-pages-with-11ty
What do I do wrong?

**To Reproduce**

1. Go to https://github.com/frontenso/500k-pages-with-11ty
2. Run `npm run start`

- Mac
- Eleventy Version 0.12.1

**Additional Information**
pages.njk contents:
```
---
title: Hello
layout: "base.njk"
pagination:
    data: data1.items
    size: 1
    alias: item
permalink: "{{ item.slug }}/"
---

{% block content %}
  <h1>{{ item.name }}</h1>
{% endblock %}
```

**Comment by pdehaan** [comment]
I think your code and logic is correct, but per https://www.11ty.dev/docs/config/#directory-for-global-data-files, the `_data/` directory should be within your `src/` directory.

**Comment by einomi** [comment]
Oh, thanks @pdehaan! It works now.

By the way, I don't know how to add a custom error handler to 11ty so I ended up with spawning a process with a custom script 
https://github.com/frontenso/500k-pages-with-11ty/blob/master/scripts/eleventy-dev.js
but I will probably create a new issue on this
