### ISSUE TITLE
Default change: `dataTemplateEngine: false` in Configuration Object

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#174]
For performance reasons.

This appears to be an underutilized feature and could be disabled by default. If you make use of data preprocessing, please chime in here!

**Comment by zachleat** [comment]
Docs:
* https://www.11ty.io/docs/data-preprocessing/
* https://www.11ty.io/docs/config/#default-template-engine-for-global-data-files

**Comment by zachleat** [comment]
The other thing here is the #155 `js` data files will unlikely support any sort of preprocessing there.

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

The enhancement backlog can be found here: https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+

Don’t forget to upvote the top comment with 👍!

**Comment by cfjedimaster** [comment]
I never knew it was a feature and if it's a performance hit, I'd be in favor of this. You could do the same with a .js file instead of .json, right? So if you can get the same result, I'd say go ahead.

**Comment by httpsterio** [comment]
Well, it's the first major version so breakage is allowed. I guess you can't really see how many users have this currently enabled, but we could check the submitted starter templates (as most start with those) and base on that?

If a significant amount of starters don't use it then it makes sense especially if there's a performance hit.

**Comment by zachleat** [comment]
As clarification we would only turn this off by default. You could opt-back in very easily with config https://www.11ty.dev/docs/config/#default-template-engine-for-global-data-files

**Comment by zachleat** [comment]
Default change of `"liquid"` to `false` will ship with 1.0.

**Comment by zachleat** [comment]
Docs added at https://github.com/11ty/11ty-website/commit/607f9d887bedc3a0c810760cc309a7f32353da84

**Comment by zachleat** [comment]
Deprecation warning added https://github.com/11ty/11ty-website/commit/0a3bf7cbc2d7ed4f0995ca801993c3ea3fe2f0a6
