### ISSUE TITLE
output directories one level up break with `addPassthroughCopy`

### ISSUE THREAD

**Issue by simonsarris** [11ty/eleventy#1748]
An output directory that's one-level-up from the 11ty project works generally, but fails if there's usage of `addPassthroughCopy`

**To Reproduce**

Have a config like this, note specifically the `outputDir`:

```javascript
module.exports = function (eleventyConfig) {
  const inputDir = '../site';
  const outputDir = '../out/_site';

  eleventyConfig.addPassthroughCopy({ "./_tmp/style.css": `${outputDir}/assets/css/style.css` });

  return {
    dir: {
      input: inputDir,
      output: outputDir
    }
  };
};
```

If you change from `'../out/_site'` to `'./out/_site'`, it works. Otherwise, you will see these errors:

```shell
`TemplatePassthroughManagerCopyError` was thrown
> Destination is not in the site output directory. Check your passthrough paths.

`TemplatePassthroughError` was thrown:
    TemplatePassthroughError: Destination is not in the site output directory. Check your passthrough paths.
```

**Environment:**

Windows 10 with 11ty version 0.11.1

**Comment by Alexs7zzh** [comment]
According to [the doc](https://www.11ty.dev/docs/copy/#change-the-output-directory), it seems you don't need to include `outputDir` in the path. Can you try the following?
```js
eleventyConfig.addPassthroughCopy({ "_tmp/style.css": 'assets/css/style.css' });
```

**Comment by simonsarris** [comment]
Oh shoot. You're very right. So my code was actually inappropriately going up one level and the error was I think legitimate. Sorry!
