### ISSUE TITLE
eleventyComputed & permalink: false lost in Canary 1.0

### ISSUE THREAD

**Issue by TigersWay** [11ty/eleventy#1754]
**Describe the bug**
it seems we lost being able to set `permalink:false` inside a `eleventyComputed`.

```
> Having trouble writing template: false

`TemplateWriterWriteError` was thrown
> The "path" argument must be of type string. Received type boolean (false)

`TypeError` was thrown:
    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean (false)
        at validateString (internal/validators.js:124:11)
...
```

**To Reproduce**
somefolder.11tydata.js
```
module.exports = {
  eleventyComputed: {
    permalink: false
  }
};
```
Silly example I know, my real code is dealing with drafts or admin pages...
And to be clear this next one is working
```
module.exports = {
  permalink: false
};
```
but less useful!

**Expected behavior**
Same as the official version of course :-) as of today v0.12.1 => no page/document in that 'folder' should be generated.

**Environment:**
- Windows 10
- Eleventy v0.12.1 vs v1.0.0-canary.16

**Comment by TigersWay** [comment]
Did some more tests today....
Confirmed the trouble, and it appeared since the April 9 commit: https://github.com/11ty/eleventy/commit/1e47d66bdbcc6ff0c03318e750545f565ce1cb8c but I don't understand it enough to propose a PR 😢

**Comment by zachleat** [comment]
Thanks for the report! I’ll have a look

**Comment by zachleat** [comment]
Fix currently resides in `zl/serverless` branch.

**Comment by TigersWay** [comment]
Just tried, without changing anything else: from v0.12.1 to zl/serverless...
- **I can "now" use `permalink:false`**! Pretty nice, I'm going to be able to work again on drafts and publishing dates.
- But I have a bunch of "unclassified" (unfinished) markdown files under both `eleventyExcludeFromCollections: true` and `permalink:false` where it now seems to break. While they can be ignored I will have to spend some time testing.

Thanks!!!!

**Comment by zachleat** [comment]
@TigersWay can you provide more information about the `eleventyExcludeFromCollections: true` `permalink:false` failure? I added a test and it seems to be working ok but I’d love to learn more

**Comment by TigersWay** [comment]
Hard to tell in my current configuration - too many parameters - but it seems the current page `page` inside a layout is undefined and is not with v0.12.1
**Will try to build a small repo around this in the next hours.**

Little note: It seems that when there's a breaking error in a layout, DEBUG gives the layout but not the current template.

**Comment by TigersWay** [comment]
> @TigersWay can you provide more information about the `eleventyExcludeFromCollections: true` `permalink:false` failure? I added a test and it seems to be working ok but I’d love to learn more

You're not going to learn much more here. This is totally my mistake: my ancestry plugin has a bug, easy to correct, and proof again that we can't always think about all the imaginable tests 😊 

Hoping for the official release but already closing this issue!

**Comment by zachleat** [comment]
Thanks for following up!

**Comment by vnourdin** [comment]
I reproduce the exact same bug (`eleventyExcludeFromCollections: true` + `permalink:false` give me `The "path" argument must be of type string.` error) using Eleventy `v1.0.0-beta.2`.
Isn't the bugfix included in this version ?

**Comment by vnourdin** [comment]
Hi there :wave: I still have this behavior with the 1.0.0 release, any clue ?

**Comment by pdehaan** [comment]
@vnourdin Hhmm, interesting... Can you please file a new issue and include a link to your repo or some source code.

I tried this w/ a directory data file and it's not writing any of the files in my /src/ directory (which is expected):

```js
// ./src/src.11tydata.js
module.exports = {
  tags: ["content"],
  eleventyExcludeFromCollections: true,
  permalink: false,
};
```

Wondering if there is possibly something else subtly breaking something here.

@11ty/eleventy v1.0.0

**Comment by vnourdin** [comment]
I set `eleventyExcludeFromCollections` and `permalink` in my `src/_data/eleventyComputed.js`, so maybe the problem is only from within `eleventyComputed`.
There is already the issue https://github.com/11ty/eleventy/issues/2167 which is probably relative. I'll try to refine the problem and open a new issue if it's not the same thing.
