### ISSUE TITLE
How to get single post data.

### ISSUE THREAD

**Issue by mikeyakymenko** [11ty/eleventy#1761]
I have index.njk, basically home page. Wanna display latest topic full: title, tags, content etc... and 5 next topics as links with titles. And didn't find in documentation how to do it. 

What I try?

```
{% set postslist = collections.blog | reverse %}
{% set latest = postslist[0] %}

<h1><a href="{{ latest.url }}">{{ latest.data.title }}</a></h1>
<article>{{ latest.data.content | safe }}</article>
```

Doesn't work. Then I find 

```
{% set postslist = collections.blog | reverse %}

{{ set latest = collections.posts | getCollectionItem(postslist[0].data.page) }}
```

So my question is, how to get single topic (any and latest in my case)?

**Comment by mikeyakymenko** [comment]
I solve this with next code in `.eleventy.js`

```
  eleventyConfig.addFilter('latest', (postList) => {
    return postList[0]
  })
```

I don't know is the right way or not :)

**Comment by mikeyakymenko** [comment]
Hm.. sorry, was some cached html. Doesn't work.

**Comment by pdehaan** [comment]
This works for me:

```nunjucks
---
title: HOME
---

<h1>{{ title }}</h1>

{%- set postslist = collections.blog | reverse -%}
{%- set latest = postslist[0] -%}

<section>
  <h1><a href="{{ latest.url }}">{{ latest.data.title }}</a></h1>
  <article>{{ latest.templateContent | safe }}</article>
</section>
```

Where my ./src/blogs/post-5.njk file looks like this:

```nunjucks
---
title: Blog Post 5
---

<h1>{{ title }}</h1>

<p>I am a blog post. There are many like it. But this one is mine</p>
```

And my ./src/blogs/blogs.11tydata.json directory data file adds the tags like this:

```json
{
  "tags": ["blog", "post"]
}
```

Finally, my generated output looks like this:

```html
<h1>HOME</h1>
<section>
  <h1><a href="/blog/post-5/">Blog Post 5</a></h1>
  <article>
    <h1>Blog Post 5</h1>
    <p>I am a blog post. There are many like it. But this one is mine</p>
  </article>
</section>
```

**Comment by pdehaan** [comment]
FWIW, Nunjucks has a built-in [`first`](https://mozilla.github.io/nunjucks/templating.html#first) filter which should "get the first item in an array or the first letter if it's a string", if you want to shorten that slightly:

```nunjucks
{%- set latest = collections.blog | reverse | first -%}
```

**Comment by mikeyakymenko** [comment]
`{%- set latest = collections.blog | reverse | first -%}` – this doesn't work also. I think some package probably broken on my machine. Will try purge and reinstall nodejs. Cause it's weird :)

**Comment by pdehaan** [comment]
And for future travellers who are curious "how even?", here's my two debugging filters I used:

```js
const inspect = require("util").inspect;

module.exports = eleventyConfig => {

  eleventyConfig.addFilter("inspect", inspect);
  eleventyConfig.addFilter("json", value => JSON.stringify(value, null, 2));

  // ...
};
```

Node's `util.inspect` is useful for logging potentially circular references and displaying as a not-really-JSON string.

And the `JSON.stringify()` just prints a pretty string representation of a [non-circular] object for easier debuggery.

**Comment by pdehaan** [comment]
> `{%- set latest = collections.blog | reverse | first -%}` – this doesn't work also.

I'm using @11ty/eleventy v0.12.1 (latest stable) on macOS/Catalina (10.15.7) w/ Node v14.16.1.

**Comment by pdehaan** [comment]
@mikeyakymenko If you have a public repo somewhere, I can take a look.

**Comment by mikeyakymenko** [comment]
@pdehaan not yet, just decide rewrite my old python-based blog, and start with 11ty. Like it, and face this trouble. :)

**Comment by mikeyakymenko** [comment]
@pdehaan Tnx. Was some issue with nodejs. Totally reinstall it and now works with `templateContent ` also TNX for debug!
