### ISSUE TITLE
Register in tags

### ISSUE THREAD

**Issue by mikeyakymenko** [11ty/eleventy#1763]
**Describe the bug**

Tags sensitive to register

**To Reproduce**

just create a two topics with tags

topic 1 tags: [Main, Life]
topc 2 tags: [Main, LIfe]

and you'll get error

```
`DuplicatePermalinkOutputError` was thrown:
    (Repeated output has been truncated…)
        at TemplateMap.checkForDuplicatePermalinks
```

**Expected behavior**
Probably create a Different tags or ignore register in tags functionality?

**Environment:**

- Mac OS
- 0.12

**Comment by mikeyakymenko** [comment]
So here is a tag https://github.com/mikeyakymenko/mike.yakymenko.online/blob/develop/src/blog/2016/12/itogi-2016.md `Итоги года`

and here https://github.com/mikeyakymenko/mike.yakymenko.online/blob/develop/src/blog/2016/01/itogi-2015-god-byl-iarkii-i-tiazhelyi.md is another `Итоги гОда`

in tags.njk I use `permalink: /tags/{{ tag | slug }}/` for prevent bad urls like `/tags/%D0%B6%D0%B8%D0%B7%D0%BD%D1%8C/` so everything throw slug. But got this error when `Итоги года` and `Итоги гОда`

So my question is, how to prevent it?

**Comment by pdehaan** [comment]
I’m not sure how/if you can fix that, unless changing the tag cases so they match is an option.

https://github.com/11ty/eleventy/discussions/1461 Seems to be related, but I didn’t see any answers there, just discussions or requests.
