### ISSUE TITLE
Deprecation warming while serving a local project. 

### ISSUE THREAD

**Issue by chokden** [11ty/eleventy#1765]
**Issue**
After installing and creating a new project. The following error pops up when trying to run the server locally. 

(node:51735) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/local/lib/node_modules/@11ty/eleventy/node_modules/emitter-mixin/package.json' of 'y'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)

**To Reproduce**
Just create any new 11ty project and try running locally. 

**Temporary Solution** 

I removed the *y* from the  `/node-modules/emitter-mixin-package.json` main. 
Idk if this workaround is accepted, but hope someone will comment on it.  It's working fine now . 

**Content of emitter-mixin**
 {
     "name": "emitter-mixin",
     "version": "0.0.3",
     "description": "Node's EventEmitter mixin",
     "main": "y",
     "scripts": {
       "test": "make test"
     },
     "repository": {
       "type": "git",
     "url": "https://github.com/yields/emitter-mixin"
    },
    "keywords": [
     "emitter",
     "mixin",
    "EventEmitter",
    "events"
    ],
   "author": "Amir Abu Shareb <amir.abu.shareb@me.com>",
    "license": "MIT",
    "devDependencies": {
      "mocha": "*",
      "should": "*"
   }
  }

**Comment by AndiKod** [comment]
I have that message too, since upgrading NodeJS to v16.0.0 (npm v7.12.0) 
Tried to "report it to the module author" but the repo is in Archived state.

**Comment by nikolowry** [comment]
An issue was opened 2 weeks ago in the `recurisve-copy` repo which depends on `emitter-mixin`, but seems to be getting neglected -- https://github.com/timkendrick/recursive-copy/issues/24.

Outdated dependencies and "project rot" are the main reasons I migrated from Metalsmith to 11ty. Hopefully `recursive-copy` can push a new release soon-ish, or 11ty finds a well maintained substitute. 

---

Sidebar: For anyone wanting to get rid of the warning prior to a new release, you can use the following diff with https://github.com/ds300/patch-package by saving it as `emitter-mixin+0.0.3.patch` in your repo's patch directory:

```diff
diff --git a/node_modules/emitter-mixin/package.json b/node_modules/emitter-mixin/package.json
index 4d37556..c78087c 100644
--- a/node_modules/emitter-mixin/package.json
+++ b/node_modules/emitter-mixin/package.json
@@ -2,7 +2,6 @@
   "name": "emitter-mixin",
   "version": "0.0.3",
   "description": "Node's EventEmitter mixin",
-  "main": "y",
   "scripts": {
     "test": "make test"
   },
```

**Comment by AndiKod** [comment]
A real solution will be needed, but until then, thx  @nikolowry for the patch-package hack.

**Comment by romellem** [comment]
I opened a PR for this - https://github.com/timkendrick/recursive-copy/pull/27

Since [`emitter-mixin`](https://www.npmjs.com/package/emitter-mixin) is MIT licensed, it can be copied into recursive-copy directly.

**Comment by chapeladmin** [comment]
recursive-copy doesn't seem all that active either. No commits since August of last year. No comments on issues or pull requests. Not even pushing through any changes from their dependencybot. recursive-copy utilizes the ISC license according to its package.json file, so could be included inline by adding a license file. Ideally these packages would be forked by someone willing to maintain them and submitted as replacements to npm.

**Comment by madsem** [comment]
That is pretty bad lol. I just wanted to move from Hugo to 11ty, and I already fail to even start using it because of this bug.

**Comment by pdehaan** [comment]
Interesting, I just installed the latest node@16 and didn't see this warning (on macOS/Catalina):

```sh
npm i @11ty/eleventy

npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

added 358 packages, and audited 359 packages in 15s

17 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

```sh
npm version

{
  '11ty-16': '1.0.0',
  npm: '7.15.1',
  node: '16.3.0',
  v8: '9.0.257.25-node.16',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '93',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '6.0.2',
  openssl: '1.1.1k+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```

**Comment by zachleat** [comment]
Fixed upstream https://github.com/timkendrick/recursive-copy/issues/24#issuecomment-869203004 and confirmed locally using Node 14 and Node 16 in both 1.0 and 0.12.x branches
