### ISSUE TITLE
Liquid include is not working 

### ISSUE THREAD

**Issue by kleinfreund** [11ty/eleventy#177]
I’m trying to include a template from another template like this:

```liquid
{% include "layouts/post__header.liquid" %}
```

The file `_includes/layouts/post__header.liquid` exists. The same include works when using Nunjucks, but not with Liquid. Any pointers?

```
Problem writing eleventy templates (more info in DEBUG output): 
 * Error: Having trouble rendering template ./_includes/layouts/post-list.liquid: ...
 * RenderError: ENOENT: Failed to lookup 'layouts/post__header.liquid' in: _includes, line:7
```

*(Running eleventy 0.5.0)*

**Comment by zachleat** [comment]
Have a look at the tests here:
https://github.com/11ty/eleventy/blob/master/test/TemplateRenderLiquidTest.js#L188

Basically, the issue with Liquid was discussed quite a bit here:
* https://github.com/harttle/liquidjs/issues/61
* https://github.com/11ty/eleventy/issues/72
* https://github.com/11ty/eleventy/issues/73

😱

If you want to use quoted includes in Liquid templates you need to enable the dynamicPartials option. Buncha examples how to do that on https://www.11ty.io/docs/languages/liquid/

OR, you can use unquoted like this without any other changes: `{% include layouts/post__header.liquid %}`

Not ideal but this is an upstream requirement out of our control—sorry!

Please re-open if you continue to have issues here!

**Comment by kleinfreund** [comment]
Yikes, guess I didn’t search thorough enough because I did search and didn’t find something helpful. Anyway, sure, that’s not pretty, but it works and is not a big deal for me. Thanks for looking into it!
