### ISSUE TITLE
Enhanced generation of pages from javascript data

### ISSUE THREAD

**Issue by npavkovic** [11ty/eleventy#1778]
I've generated pages from data using pagination but am looking for a more elegant and flexible way to do so. In particular, chunk sizes and aliases always seemed like they were workarounds for limitations in YAML's data representation. If my chunk size is 8 and I'm editing manually, it's easy to make a mistake. The variables names that end up on the page are not  helpful — if you use, say, "custom" as your alias, what {{ custom[4] }} means is not immediately apparent.

I'd like to generate pages from a javascript array of objects:
```
[
  {
    permalink: "/enroll/sitelink1.html",
    title: "Welcome",
    headline: "Headline Here",
    subhead: "",
    seoDescription: "some text",
    pageTemplate: "default.html"
  },
  {
    ...
  },
  ...
]
```
A "renderer" would iterate over this structure, merging each page item with the data cascade and creating a page using a given page template, which could have standard Liquid variable substitution for the headline, subhead, etc.

If this were to work within the current file structure, perhaps a _generate folder could contain these structures, or they could be identified in some way within the _data folder.

Perhaps something like this is already possible?

**Comment by zachleat** [comment]
```
---
pagination:
  data: yourArray
  size: 1
---
```

I’m still not quite sure what you’re looking for above and beyond this sample?

**Comment by npavkovic** [comment]
Indeed! I just have to stop using YAML. Thanks, Zach.
