### ISSUE TITLE
Plugin request: Responsive images shortcodes

### ISSUE THREAD

**Issue by asdevgit** [11ty/eleventy#178]
Hi
I'm using netlify blog template and have been experimenting with eleventy! Very nice!
Any suggestions on where we should store images and how can we implement some sort of lightbox/responsive image presentation.

Adjust markdown-it to produce a nicer <img ... with a link to an appropriate lightbox/rwd script?

Added this:
  templateFormats: [
      "md",
      "njk",
      "html",
      "jpg",
      "png"
    ],

to get static files to push through.

**Comment by asdevgit** [comment]
Thanks. Yes I’d already did this. 
This moves images over but interested in how I can ensure images in deployed pages appear responsive. 
I guess two things need to take place. 
1. Generate several images (small, medium, large) 
2. Add appropriate html markup to display the image. 
Suggestions appreciated.

**Comment by zachleat** [comment]
Yes—love the idea. We don’t have this feature yet but I’d love to see a community plugin for responsive images. I’m going to move this to a feature request.

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

The enhancement backlog can be found here: https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+

**Comment by zachleat** [comment]
I think the image creation stuff will require some additional infrastructure, likely requiring #117 

But for the markup stuff I’d recommend starting with a shortcode! https://www.11ty.io/docs/shortcodes/ Lemme know if you have more questions here

**Comment by idiazroncero** [comment]
I'm using a separate npm script using sharp to generate the assets (thumb, small, medium and large versions of the images on my img/ folder), then I run netlify with addPassThroughCopy to move them to the dist/ folder and finally I created a custom shortcode that generates the <picture> markup with all the responsive srcset stuff. So, baiscally, this is a two-step process (first sharp and then eleventy).

Still, it would be nice if we could include all of this _inside_ the eleventy build process, maybe the same way we use .addTransform to modify HTML files on the run...

**Comment by zachleat** [comment]
Cross linking to the plugin where this lives now https://www.11ty.dev/docs/plugins/image/
