### ISSUE TITLE
Invalid 'main' field in '.../emitter-mixin/package.json' of 'y'

### ISSUE THREAD

**Issue by bobsfriend12** [11ty/eleventy#1781]
**Describe the bug**
I just reinstalled my OS, and now my eleventy doesn't work. This may be because I used [this tutorial](https://github.com/sindresorhus/guides/blob/main/npm-global-without-sudo.md) to make it so that I didn't have to use sudo when I installed packages globally.

when I run any eleventy command I get  this a the top of the output.

```
node:108411) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/bobsfriend12/.npm-packages/lib/node_modules/@11ty/eleventy/node_modules/emitter-mixin/package.json' of 'y'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Running `node --trace-deprecation` doesn't show any output.

**To Reproduce**

Not really sure I just installed eleventy and it shows the error.

**Expected behavior**
Eleventy should not show the error.

**Environment:**

- OS and Version: latest version of Arch Linux as I just reinstalled today.
- Eleventy Version `0.12.1`

**Additional context**
I have looked into the `package.json` file of the `emitter-mixin` package. It shows version `0.0.3`.
Also eleventy does work, I just want to find out why I am getting this error.

**Comment by pdehaan** [comment]
I believe this is a dupe of #1765, which might be specific to node v16 (or more likely npm v7).

**Comment by bobsfriend12** [comment]
Thanks can't believe I didn't see that one . . .
