### ISSUE TITLE
Eleventy-img plugin template render error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by koitaki** [11ty/eleventy#1784]
Trying the eleventy-img plugin for the first time in a hitherto working 11ty dev site.

Docs look good, but the devil if I can get it to work.
I keep getting "Template render error was thrown", with this message
`  Error: ENOENT: no such file or directory, stat '/images/coding/coding.jpg'`

My simplified file structure is this:

├── site
└── src
    ├── admin
    ├── assets
    ├── coding
    ├── _data
    ├── fonts
    ├── images
    │   ├── **coding**  (which includes a file for coding.jpg)
    │   └── uploads
    ├── _includes
    │   ├── css
    │   ├── layouts
    │   ├── partials
    │   └── scripts
    ├── scss

My eleventy.js incorporates the eleventy-img code from the docs, and, simplified to exclude other stuff, looks like this:

```
const Image = require("@11ty/eleventy-img");
async function imageShortcode(src, alt, sizes) {
  let metadata = await Image(src, {
    widths: [600],
    formats: ["jpeg"],
  });
  let imageAttributes = {
    alt,
    sizes,
    loading: "lazy",
    decoding: "async",
  };
  return Image.generateHTML(metadata, imageAttributes);
}

module.exports = function(config) {
  config.addNunjucksAsyncShortcode("image", imageShortcode);
  :
  :
  return {
    templateFormats: ["html", "njk", "md", "liquid"],
    dir: {
      input: "./src",
      output: "./site",
      data: "_data",
      includes: "_includes"
    }
  };
};
```

And then my **index.html** page has this shortcode for the image
`    {% image  site.images + topic.image, topic.imageAlt %}
`
(note: its not a .njk file, but an .html file)

The returned image path "seems" perfectly valid:
'/images/coding/coding.jpg'

Yet, the error says the file is not there.
Any suggestions as to how this might be fixed?

Many thanks in advance!

**Comment by pdehaan** [comment]
What about if you try hardcoding the path to the .jpg file (possibly w/ a leading `.` to make sure it's trying to look locally and not a global `/images/` folder).

```nunjucks
{% image "./images/coding/coding.jpg", topic.imageAlt %}
```

Also, not sure if you'll need to set an explicit `htmlTemplateEngine: "njk"` in your config, since I think the default is LiquidJS, per https://www.11ty.dev/docs/config/#default-template-engine-for-html-files

**Comment by koitaki** [comment]
Thanks for looking at this Peter - I'd covered the issues you pointed out, but didn't mention them due to brevity.
That said, as you pointed out, it was indeed an address issue.
I needed to add ./src to the relative image address in the nunjucks shortcode, as per below.

`{% image "./src" + site.images + topic.image, topic.imageAlt %}`

Presumably because that address is relative to the eleventy.js file.

So in addition to the docs, fwiw if someone else is interested, my understanding of how the images are sourced and produced:

1. Aside from hard-coded URL's, the code looks for the images in the ./src/ pre-compilation folder.
   Hence, the .src needs to be included in the nunjucks shortcode to show the relative path

2. It then produces a folder for the newly created images
    (i) My folder for my original images is **images** 
         (also named this in my site.data json, hence site.images)
    (ii) In the imageShortcode, I added outputDir: "./src/img/"
         This is where the generated images are then saved
    (iii) In the imageShortcode, I added urlPath: "/img/"
         This states where the generated images will be accessed in the compiled site folder
    (iv) I then added a passthrough for that img folder
         `` config.addPassthroughCopy("./src/img");

In case that's of use to anyone.
Many thanks again for looking at this, appreciate the help!
