### ISSUE TITLE
Shortcode: Post excerpt/summary – How to access post content?

### ISSUE THREAD

**Issue by kleinfreund** [11ty/eleventy#179]
I’m currently writing a shortcode for post excerpts/summaries:

```liquid
---
layout: layouts/base.liquid
pagination:
  data: collections.post
  size: 5
  alias: posts
---
{%- for post in posts -%}
<article>
  {% excerpt post %}
</article>
{%- endfor -%}
```

Something along the lines of this:

```js
module.exports = function (eleventyConfig) {
  eleventyConfig.addLiquidShortcode('excerpt', post => {
    if (!post.templateContent) {
      return;
    }

    const content = post.templateContent;
    const excerptEnd = content.includes('<!--more-->')
      ? content.indexOf('<!--more-->')
      : content.indexOf('\n\n');

    return content.substring(0, excerptEnd).trim();
  });

  // …
};
```

Now, it seems like `post.templateContent` doesn’t always contain what I want. Sometimes, this property doesn’t exist. How would I go about this? Do I use `post.inputContent` and strip any front matter myself? Is that safe? Seems odd.

**Comment by zachleat** [comment]
Hey @kleinfreund, where is `posts` coming from there?

**Comment by kleinfreund** [comment]
Ah, yeah, that should’ve been in the original post. In the site I’m converting, I have a bunch of posts that are already tagged (e.g. `tags: dev`, etc.). Therefor, for testing, I have set `pagination.data: collections.dev` in order to test my blog listing plus pagination. That’s related to the tag merging issue (see #147).

When logging `post` in the shortcode JavaScript, I see a whole bunch of data, including `post.templateContent`, but that’s not always there. I haven’t figured out yet, why some posts have that I why some don’t. Probably looking into this tomorrow again.

**Comment by zachleat** [comment]
Ah pagination, yeah. I’m almost certain this is related to #171 but I’ll leave it open until after 0.5.1 is out to confirm.

**Comment by zachleat** [comment]
Well, I’m confident, maybe almost certain is a little too much 😅

**Comment by zachleat** [comment]
The other thing this made me think of is the excerpt feature on `gray-matter`, which we make no use of right now (but might make for a good feature request here).

https://www.npmjs.com/package/gray-matter#optionsexcerpt

```
---
myfrontmatteroption: true
---
this is an excerpt
---
this is my content
```

**Comment by zachleat** [comment]
Just added a few tests around this and it is unique and unrelated to #171.

**Comment by zachleat** [comment]
Hmm, I added some additional tests to confirm that this should work in 0.5.1

**Comment by zachleat** [comment]
I think I spoke too soon. I ended up making a huge refactoring change in the `perf` branch that will fix this. It’s unlikely to land in 0.5.1 but will for sure land in 0.6.0 after I’m comfortable it won’t break everything. Sorry!

**Comment by zachleat** [comment]
Work for this also created most of #108, so we got that going for us 😅

**Comment by kleinfreund** [comment]
No need to apologize. I takes what it takes. It seems very worthwhile.

**Comment by zachleat** [comment]
v0.5.1 is out, please retest! (and reopen if necessary)

**Comment by kleinfreund** [comment]
Yes and no. I’m not quite sure. It works as in every post (i.e. every document in a collection) generates an excerpt, but for the first page in the pagination (with pagination size 5, that’s the first 5 documents), this is still triggered:

```js
if (!doc.hasOwnProperty('templateContent')) {
  console.warn('>>> Failed to extract excerpt: Document has no property `templateContent`.');
  console.warn(doc.data.title);
  return;
}
```

Note that these documents **do have** an excerpt in the output meaning that every document has the `templateContent` property at one point. Maybe something is processed twice in the pagination logic?

Leaving this closed for now as the issue at hand is resolved.
