### ISSUE TITLE
Nunjucks Shortcode output is escaped when using Nunjucks + Markdown

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#180]
Reported by @hankchizljaw here: https://github.com/hankchizljaw/webcomponents.club

**Comment by zachleat** [comment]
As we discovered, this is because your shortcode has extra whitespace!

See: https://github.com/hankchizljaw/webcomponents.club/blob/master/shortcodes/video-poster-shortcode.js

As noted on https://commonmark.org/help/ `indent 4 spaces` triggers a code block in markdown.

So changing

```
let response = `
        <a href="${shareUrl}" aria-label="Watch this video on Youtube">
            …
        </a>
    `;
```

to


```
let response = `
<a href="${shareUrl}" aria-label="Watch this video on Youtube">
    …
</a>`;
```

will fix it!

**Comment by hankchizljaw** [comment]
Thanks @zachleat, hopefully this will help someone out in the long-term who finds themselves in a similar pickle 🙂

**Comment by kleinfreund** [comment]
If that doesn’t suite your code aesthetics, do a `trim()`:

```js
let response = `
    <a href="${shareUrl}" aria-label="Watch this video on Youtube">
      ...
    </a>
`.trim();
```

:sunglasses:

**Comment by zachleat** [comment]
@hankchizljaw yes! It wasn't immediately obvious to me what was happening so I'm sure someone else will run into it too 👍🏻

**Comment by eeeps** [comment]
it me 🥒🏃‍♂️
