### ISSUE TITLE
Unknown Liquid filters fail silently

### ISSUE THREAD

**Issue by kleinfreund** [11ty/eleventy#183]
The following works with or without a `cssmin` filter being defined.

**`example.liquid`**:

```liquid
{% capture testcss %}
  {% include css/test.css %}
{% endcapture %}
<style>{{ testcss | cssmin | safe }}</style>
```

When a filter is not defined, an error should be produced.

*(as seen in [Quick Tip #005—Super Simple CSS Concatenation](https://www.11ty.io/docs/quicktips/concatenate/))*

**Comment by zachleat** [comment]
I did make a fair number of changes to the error reporting stuff in 0.5.4, this is what it reports in Nunjucks:

![image](https://user-images.githubusercontent.com/39355/45360616-b66ab080-b595-11e8-97b4-4a3fbe99b368.png)

But you’re absolutely right that it fails silently in Liquid templates.

**Comment by zachleat** [comment]
Ah, looks like there is a `strict_filters` option: https://github.com/harttle/liquidjs#options

**Comment by zachleat** [comment]
With this option enabled:
![image](https://user-images.githubusercontent.com/39355/45361261-6bea3380-b597-11e8-9ab4-3e5a3a049eea.png)

I added this to the Liquid setLiquidOptions documentation example and created another issue to change this to `true` by default when we go 1.0.

https://www.11ty.io/docs/languages/liquid/

Closing this one—follow along at #222 for the default change—thanks!

**Comment by zachleat** [comment]
https://github.com/11ty/eleventy/issues/222 is shipping with 1.0
