### ISSUE TITLE
Change home global install suggestion to local according to docs

### ISSUE THREAD

**Issue by borispov** [11ty/eleventy#1831]
The landing page ( https://www.11ty.dev/ ) directs the user to install 11ty globally:
`npm install -g @11ty/eleventy`
Whereas the documentation recommends users to install 11ty locally. 

Obviously, it's a simple thing and I'm not sure it's worth opening an issue, for which I'm sorry in advance if this is the case.

**Comment by zachleat** [comment]
Yeah, the reason we do this is that local installation requires a `package.json`. There are a couple of different types of beginners we’re trying to accommodate here:

A. Those that don’t know what `package.json` is
B. Those that do know what `package.json` is and understand local versus global

Global installation is the default that helps with type A. We could add some additional instructions to always recommend local installation, but I haven’t seen enough confusion from folks to necessitate that just yet! If you see other any confusion definitely let me know

Thanks!
