### ISSUE TITLE
Markdown-it not rendering GFM table

### ISSUE THREAD

**Issue by cmcknight** [11ty/eleventy#1849]
**Describe the bug**
I am retrieving a string attribute from a JSON object that contains GFM Markdown for a table. The rendered does not seem to be rendering it correctly. However, it renders the same string when I put it directly into a Markdown (.md) file.

**To Reproduce**

1. Unpack the zip file
2. Run ```npm i``` to install dependencies
3. Run ```npx eleventy``` to trigger the log to display

**Expected behavior**

I expected the renderer to convert the embedded GFM table to an HTML table. What I got was:

```
<p>| col 1 | | col 2 |
| ---- | ---- |
| 0001 | Test text |</p>
```

**Screenshots**
N/A

**Environment:**

- Mac OS v11.4 / 32GB RAM
- Eleventy Version 0.12.1

The attached file contains a minimum viable example of the issue.

[markdownit-no-gfm-render.zip](https://github.com/11ty/eleventy/files/6697800/markdownit-no-gfm-render.zip)

**Comment by pdehaan** [comment]
Not sure if your .eleventy.js config file made it into the ZIP file.

I was able to get it working with the following filter/config:

```js
// .eleventy.js
const md = require("markdown-it")({
  html: true
});

module.exports = (eleventyConfig )=> {
  eleventyConfig.addFilter("markdown", str => md.render(str));

  return {
    dir: {
      input: "src",
      output: "www"
    }
  }
};
```

**Comment by cmcknight** [comment]
Found the issue. Formatting error. Using GFM tables with markdown-it requires an exact match. Also found a typo so all appears to be well on the Western Front...
