### ISSUE TITLE
page is missing data property (title, date, etc.)

### ISSUE THREAD

**Issue by kleinfreund** [11ty/eleventy#185]
One can iterate over a collection to generate a list of *posts*. These posts will have a `data` property holding; for example, the properties `title` and `date`. However, *pages* are missing that data.

Generally, posts and pages shouldn’t be that different in their underlying data structure. They’re both *documents*. Both can have data as specified in the document’s front matter. This data should be available in an predictable location. If posts have a `data` property, so should pages or let’s rather say documents in general.

**Feature request**: Posts and pages should be treated more equally and both yield their data.

**Comment by zachleat** [comment]
When you say pages, you’re referring to output of pagination right?

Can you read #130 and tell me if this is related to what you’re saying here?

**Comment by kleinfreund** [comment]
Ah, this is a terminology issue. Pages in Jekyll-land are general documents (e.g. the about page). Documents that are paginated have the mentioned data.

And yeah, it's absolutely related. We probably should close this over the mentioned issue.

**Comment by zachleat** [comment]
Closing in lieu of #130.
