### ISSUE TITLE
Serverless properties in pagination/permalink prevent build process from building files

### ISSUE THREAD

**Issue by brob** [11ty/eleventy#1858]
**Describe the bug**
When using pagination.serverless and a serverless permalink, the `permalink.build` property is not respected and builds no files.

**To Reproduce**

1. Clone this reduced test case: https://github.com/brob/demo-eleventy-serverless/
2. Run npm start
3. Check logs to see no HTML files are built, but the serverless routes work (serverless route to test: http://localhost:8080/madlibs/dJGUQBWdbrm2_S790dNpO/)

**Expected behavior**
When running in build mode, I would expect serverless key to be ignored (language partially from DM)

**Screenshots**

**Environment:**

- MacOS 10.15.7
- Eleventy Version 1.0.0-canary.36

**Additional context**

**Comment by zachleat** [comment]
(for others, I’ve already verified this one with Bryan and requested he file this)

**Comment by zachleat** [comment]
@brob finally circling back here—this _seems_ to be fixed in Canary 41—can you confirm?

**Comment by zachleat** [comment]
Oops, false alarm. I was looking at the wrong file, sorry @brob—I can confirm it’s still broken

**Comment by zachleat** [comment]
Shipping with Canary 42
