### ISSUE TITLE
Serverless .gitignore example causes looping in --serve

### ISSUE THREAD

**Issue by brob** [11ty/eleventy#1861]
When following the example and [adding a .gitignore](https://www.11ty.dev/docs/plugins/serverless/#step-2-add-to-.gitignore), the `eleventy --serve` command will continue watching files that exist inside the `netlify/functions/possum/*` directory and cause a loop of file creation/watching/creation/etc.

If it's changed to `netlify/functions/possum/` the looping stops.

Not sure if there's a deeper underlying issue or if the docs just need to be updated.

**Comment by zachleat** [comment]
Docs updated, thanks!
