### ISSUE TITLE
Serverless and Firebase Functions.

### ISSUE THREAD

**Issue by robdodson** [11ty/eleventy#1866]
**Describe the bug**
I'm trying to get eleventy serverless working with firebase functions. I _think_ I've set everything up correctly, but when I visit my function I get a Node error saying that it can't find `eleventy-serverless-map.json`.

**To Reproduce**

I put together a gist to show my structure:
https://gist.github.com/robdodson/e223a02a02859d28d555229cd9a73245

**Expected behavior**

When I visit `/possum/` I shouldn't see an error.

**Actual behavior**
I get the following error

```
Cannot find module '/Users/…/functions/eleventy-serverless-map.json
```

**Environment:**

- OS and Version: macOS
- Eleventy Version: 1.0.0-canary.38

**Comment by zachleat** [comment]
This is as far as I got and the error message I’d expect to see on `localhost` right now

https://stackblitz.com/edit/node-txhs9w?devtoolsheight=33&file=.eleventy.js

![image](https://user-images.githubusercontent.com/39355/123875199-dc0c0480-d8fe-11eb-88dd-c7777b9cbe9f.png)

**Comment by zachleat** [comment]
The localhost experience (right now) expects a `handler` function in the `possum/index.js` file. That’s the convention on the serverless hosts I’ve used, but I’m open to extending it!

**Comment by robdodson** [comment]
oh it looks like the stackblitz project is gone (or maybe it's private?)

In my code I did have a handler function in functions/possum/index.js. Unfortunately github gists don't let me show subdirectories so I tried to add the directory paths as comments at the top of the files.

**Comment by zachleat** [comment]
Ah sorry about that! I renamed it https://stackblitz.com/edit/robs-firebase-test

**Comment by robdodson** [comment]
> The localhost experience (right now) expects a handler function in the possum/index.js file.

Oh, so the function literally needs to be named `exports.handler` ?

**Comment by robdodson** [comment]
oh snaaaaap! I got it working. I'll put together an example repo to share.

![image](https://user-images.githubusercontent.com/1066253/124047156-5eacc680-d9c8-11eb-9ba5-528d3b360318.png)

**Comment by robdodson** [comment]
Here's a repo: https://github.com/robdodson/eleventy-serverless-firebase

I did find [one issue](https://github.com/robdodson/eleventy-serverless-firebase#issues) though, the `_data` directory does not seem to work. It works when I do a static build, but not when I let the function render it. I can see that the _data directory is being copied over to the right place, so I'm not sure what's up.

![image](https://user-images.githubusercontent.com/1066253/124049103-9ddd1680-d9cc-11eb-8bb3-9e0363d641c8.png)

**Comment by zachleat** [comment]
Stale per project slipstream changes in #3074.
