### ISSUE TITLE
User API to set configuration options for third party plugins

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#187]
See https://github.com/eeeps/eleventy-respimg/blob/master/README.md

```
module.exports = function( eleventyConfig ) {

	eleventyConfig.cloudinaryCloudName = 'your-cloud-name-here';
	eleventyConfig.srcsetWidths = [ 320, 640, 960, 1280, 1600, 1920, 2240, 2560 ];
	eleventyConfig.fallbackWidth = 640;
	
} );
```

cc @eeeps

**Comment by eeeps** [comment]
I'll admit to not being totally sure what problem's being solved here. Namespacing? So these options would be set via `eleventyConfig.plugins.respimg.cloudinaryCloudName` or something?

**Comment by zachleat** [comment]
well, just _some_ mechanism to prevent collisions on data set on the config object.

At the very least it’d be nice to see something like:

```
eleventyConfig.cloudinaryCfg = {
  cloudName: 'your-cloud-name-here',
  srcsetWidths: [ 320, 640, 960, 1280, 1600, 1920, 2240, 2560 ],
  fallbackWidth: 640
};
```

but nicer to haves might be something that throws an error if your prop collides with existing props on the config object.

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

The enhancement backlog can be found here: https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+

Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
I think our current mechanism for this is sufficient https://www.11ty.dev/docs/create-plugin/
