### ISSUE TITLE
Eleventy Serverless requires a _data folder

### ISSUE THREAD

**Issue by brob** [11ty/eleventy#1872]
**Describe the bug**
When starting Eleventy Serverless from scratch, if there's no _data folder, an error is thrown

Unhandled rejection in promise: (more in DEBUG output)
> ENOENT: no such file or directory, lstat '_data'

`Error` was thrown:
    Error: ENOENT: no such file or directory, lstat '_data'

**To Reproduce**

1. Install 11ty/eleventy@1.0.0-canary.38
2. Install the `EleventyServerlessBundlerPlugin` plugin
3. Create a simple index.html with a serverless route
4. See the error above in the terminal
5. Create an empty _data folder
6. see no error

**Expected behavior**
Eleventy should not try to copy a _data folder if none exists.

**Environment:**

- OS and Version: MacOS 10.15.7
- Eleventy Version: 1.0.0-canary.38

**Additional context**

**Comment by zachleat** [comment]
This is fixed already in master, just needs to cut another canary (it’ll be in 39)

(it also required an _includes folder)

**Comment by zachleat** [comment]
571f8cf5bc124f7a0bd35d891797f377ddb54b0e and 7c198625a477b030b83bf01d2f7d73cde8eb1b26 have it (this previously did not have an official issue though, so I appreciate the home base here)
