### ISSUE TITLE
Docs Quick tip: share slugify filter with Markdown TOC

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#1874]
First noticed it on here but it’s a good idea: https://twitter.com/codingsafari/status/1410682849473277961

Highly related to #278 and the new `slugify` replacement.

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for documentation requests. This means documentation issues will now be closed instead of leaving them open.

View [the documentation queue backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Areactions-%2B1-desc+is%3Aclosed+label%3Adocumentation+label%3Aneeds-votes). Don’t forget to upvote the top comment with 👍!

**Comment by pdehaan** [comment]
That's a neat trick!

Bonus points if we can use the `eleventyConfig.getFilter("slug")` API instead of `eleventyConfig.javascriptFunctions.slug`.
