### ISSUE TITLE
Include outputPath in JSON output

### ISSUE THREAD

**Issue by Snugug** [11ty/eleventy#1877]
**Is your feature request related to a problem? Please describe.**
The current properties of JSON output include `url`, `inputPath`, and `content`, which are all great, but the actual path the file should be output to if it were going to be written to disk isn't included, making it difficult to fully recreate the `write` method with the data from the JSON

**Describe the solution you'd like**
Include `outputPath` where the file would be written to

**Describe alternatives you've considered**
Attaching `index.html` to any URL that doesn't include an extension, but that doesn't seem error-proof

**Additional context**
Related to work for #1786

**Comment by zachleat** [comment]
Oh, interesting. It seems weird to include outputPath when we aren’t writing any files but I’m okay with this addition!

**Comment by zachleat** [comment]
Shipping with 1.0
