### ISSUE TITLE
Eleventy Serverless default “Cannot find module” error on Windows

### ISSUE THREAD

**Issue by Snapstromegon** [11ty/eleventy#1884]
**Describe the bug**
During the first run of ```eleventy serve``` with serverless enabled 11ty tries to copy *node_modules\@11ty\eleventy\src\Plugins\DefaultServerlessFunctionContent.js* to the functions directory, but on windows and nodejs 16 the path gets resolved to an invalid "double absolute" path.

**To Reproduce**

1. Create a repo with serverless enabled (example repo [here](https://github.com/Snapstromegon/eleventy_serverless_demo))
2. run ```npm run serve```
3. The error gets printed in the console

**Expected behavior**
It should create the file correctly / resolve the path correctly.

**Screenshots**
Powershell output
```CMD
PS D:\Documents\DEV\test\eleventy_serverless_demo> npm run serve

> eleventy_serverless_demo@1.0.0 serve
> eleventy --serve

Problem writing Eleventy templates: (more in DEBUG output)
> ENOENT: no such file or directory, open 'D:\Documents\DEV\test\eleventy_serverless_demo\D:\Documents\DEV\test\eleventy_serverless_demo\node_modules\@11ty\eleventy\src\Plugins\DefaultServerlessFunctionContent.js'

`Error` was thrown:
    Error: ENOENT: no such file or directory, open 'D:\Documents\DEV\test\eleventy_serverless_demo\D:\Documents\DEV\test\eleventy_serverless_demo\node_modules\@11ty\eleventy\src\Plugins\DefaultServerlessFunctionContent.js'
Wrote 0 files in 0.02 seconds (v1.0.0-canary.38)
PS D:\Documents\DEV\test\eleventy_serverless_demo>
```

**Environment:**

- OS and Version: Windows 10 20H2 (19042.1052)
- Eleventy Version 1.0.0-canary.38

**Additional context**
The problem occurs, because path.join is called with arguments ```path.join("D:/somepath", "D:/somepath/somethingelse", "somerelativepath")``` and nodejs will join those paths, but a ```path.resolve()``` is what I'd expect here.

According to my 10mins of investigation with the debugger, It seems like the problem is, that in *ServerlessBundlerPlugin.js:writeServerlessFunctionFile()[244]* an absolute path is passed to TemplatePath.absolutePath, which in turn is not meant to handle already absolute paths, since that function joins the current working dir (via ```path.resolve(".")```) with the rest of the paths.

IMO *TemplatePath.js:absolutePath()[155]* should use ```resolve()``` instead of ```join()``` for the paths.

**Comment by Snapstromegon** [comment]
I can verify that this problem does **not** occur on my WSL2 Ubuntu 20.04.

**Comment by zachleat** [comment]
Ah, I think I may have fixed this with https://github.com/11ty/eleventy/commit/21630bfc292a5d42cf61b86f3b51841419c7cd67

Can you verify after Canary 40 is released?

**Comment by Snapstromegon** [comment]
I'm currently mainly AFK, but I gave it a quick test:

```
[11ty] Unhandled rejection in promise: (more in DEBUG output)
[11ty] > Cannot find module './C:\Users\$USER\$PROJECT\netlify\functions\serverless\index'
Require stack:
- C:\Users\$USER\$PROJECT\node_modules\@11ty\eleventy\src\Plugins\ServerlessBundlerPlugin.js
- C:\Users\$USER\$PROJECT\node_modules\@11ty\eleventy\src\Eleventy.js
- C:\Users\$USER\$PROJECT\node_modules\@11ty\eleventy\cmd.js

`Error` was thrown:
[11ty]     Error: Cannot find module './C:\Users\$USER\$PROJECT\netlify\functions\serverless\index'
    Require stack:
    - C:\Users\$USER\$PROJECT\node_modules\@11ty\eleventy\src\Plugins\ServerlessBundlerPlugin.js
    - C:\Users\$USER\$PROJECT\node_modules\@11ty\eleventy\src\Eleventy.js
    - C:\Users\$USER\$PROJECT\node_modules\@11ty\eleventy\cmd.js
        at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
        at Function.Module._load (node:internal/modules/cjs/loader:769:27)
        at Module.require (node:internal/modules/cjs/loader:996:19)
        at require (node:internal/modules/cjs/helpers:92:18)
        at C:\Users\$USER\$PROJECT\node_modules\@11ty\eleventy\src\Plugins\ServerlessBundlerPlugin.js:214:32     
        at call (C:\Users\$USER\$PROJECT\node_modules\connect\index.js:239:7)
        at next (C:\Users\$USER\$PROJECT\node_modules\connect\index.js:183:5)
        at next (C:\Users\$USER\$PROJECT\node_modules\connect\index.js:161:14)
        at next (C:\Users\$USER\$PROJECT\node_modules\connect\index.js:161:14)
        at respModifierMiddleware (C:\Users\$USER\$PROJECT\node_modules\resp-modifier\index.js:80:9)

```

I can verify that netlify\functions\serverless\index.js gets created correctly.

**Comment by zachleat** [comment]
A ha, I see the issue. I took another stab at this, can you retest after Canary 42 ships?

**Comment by zachleat** [comment]
Canary 44 is the latest, can you retest?

**Comment by Snapstromegon** [comment]
Sorry for missing the last canary updates, will retest tomorrow.

**Comment by Snapstromegon** [comment]
Issue is resolved in Canary 44 - Closing the issue.

**Comment by zachleat** [comment]
Yay!
