### ISSUE TITLE
Environment variables documentation

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#1890]
Starting in 1.0 we do have Eleventy supplied environment variables.

https://github.com/11ty/eleventy/blob/616c9f7237c06c0eb1419f13a0b6982d82068f5f/src/Eleventy.js#L399

(Docs issue inspired by #1886)

**Comment by tannerdolby** [comment]
I'm happy to take this on @zachleat !

After reading through #1886 it seems like this might already be partly resolved and I noticed that currently there is documentation on env variables within the main site here: https://www.11ty.dev/docs/data-js/#example-exposing-environment-variables

**Comment by zachleat** [comment]
Awesome! I think for a start it should live on the Eleventy supplied data page

**Comment by zachleat** [comment]
I wouldn't mind at least a cross like to that JS Data Files example too!

**Comment by tannerdolby** [comment]
> Awesome! I think for a start it should live on the Eleventy supplied data page

Ok cool! Yeah, I agree. Having it live on the Eleventy supplied data page makes the most sense since `page` etc are documented there as well.

**Comment by tannerdolby** [comment]
> I wouldn't mind at least a cross like to that JS Data Files example too!

Deal! I will spin something up and submit a PR within the next few days.

**Comment by zachleat** [comment]
Look for this at https://www.11ty.dev/docs/data-eleventy-supplied/#environment-variables

**Comment by tannerdolby** [comment]
Looks great @zachleat! 🚀
