### ISSUE TITLE
Remove fs-extra dependency

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#1891]
With the `fs.mkdir` recursive option and the promises API on all Node versions we support I think we can start phasing this one out.

**Comment by Snapstromegon** [comment]
Related to this issue:
Maybe "parse-filepath" can be removed as a dependency too.
According to my quick search in the code it seems like ```path.parse``` should be a working replacement.

**Comment by zachleat** [comment]
Merged, thanks @Snapstromegon !
