### ISSUE TITLE
Reverse sort paginated collection

### ISSUE THREAD

**Issue by rolandtoth** [11ty/eleventy#192]
I can't reverse sort posts (collection name: work) when using pagination.

```
pagination:
  data: collections.work
  size: 2
  alias: works
```

```
<ul>
{% for page in works %}
  <li>
    <a href="{{ page.url | url }}">{{ page.data.title }}</a>
  </li>
{% endfor %}
</ul>
```

If I use `works.reverse()` it reverses the current chunk size, not the whole collection. So instead 4-3, 2-1 I got 2-1, 4-3 (if there are 4 pages). I tried data: collections.work.reverse() but no joy.

I also tried custom sorting in .eleventy.js but nothing worked, eg (config is eleventyConfig in my setup):

```
  module.exports = function (config) {
    // Use the default sorting algorithm in reverse (descending dir, date, filename)
    // Note that using a template engine’s `reverse` filter might be easier here
    config.addCollection("work", function (collection) {
      return collection.getAllSorted().reverse();
    });
  };
```

I'm new to eleventy so bear with me :)

**Comment by zachleat** [comment]
Hmm, there is no frontmatter key to reverse pagination, which would be useful. Filed as #194.

However, I would expect that the configuration file sorting would work! If you remove the `.reverse()` call does it operate how you would expect? (Maybe it’s doing ascending and not descending by default)

**Comment by rolandtoth** [comment]
Interestingly now the config sorting started to work, and I could get the pagination work with custom permalink, so it' all fine now. I have changed the file extension from .md to .njk, perhaps that's why? markdownTemplateEngine is set to "njk". Anyway, perhaps it was something I overlooked.

The .reverse() would be a nice addition though, thanks for considering.

**Comment by zachleat** [comment]
Awesome, thanks. I’ll close this one in lieu of the enhancement request at #194. Make sure you upvote over at #194!
