### ISSUE TITLE
[Serverless] TemplateLayoutPathResolver can't find _includes directory

### ISSUE THREAD

**Issue by robdodson** [11ty/eleventy#1929]
**Describe the bug**
When I try to use a `layout` with my eleventy serverless project, I get a TemplateLayoutPathResolver error saying that it can't find the _includes dir.

**To Reproduce**
Clone this repo: https://github.com/robdodson/eleventy-serverless-netlify
npm install then run netlify dev

**Expected behavior**
Layouts should work.

**Environment:**

- OS and Version: macOS Big Sur 11.5.1
- Eleventy Version: 1.0.0-canary.41

**Comment by zachleat** [comment]
Some discussion here https://twitter.com/rob_dodson/status/1425847096268124165

**Comment by zachleat** [comment]
As noted on https://twitter.com/zachleat/status/1425870026804969475 on the sample demo _is_ using a layout on canary 41: https://github.com/11ty/demo-eleventy-serverless/

**Comment by zachleat** [comment]
![image](https://user-images.githubusercontent.com/39355/129364516-9621b399-f9f6-4f1b-95bd-3eb955b82ae5.png)

I deleted the netlify folder and let the `index.js` serverless function file regenerate (which worked) and revealed the issue.

Looks like you changed your `inputDir` after the file was generated? This deserves some better runtime error messaging.

**Comment by zachleat** [comment]
I pushed a change to that will now use a separate metadata json file for the inputDir rather than hardcoding it in the `index.js` serverless file. That way any changes to the input directory will be kept up to date without having to modify the serverless file (which is versioned).

It’ll ship with Canary 42.
