### ISSUE TITLE
Add convenience method/property to set markdown/data/html template engine at once

### ISSUE THREAD

**Issue by pdehaan** [11ty/eleventy#1930]
**Is your feature request related to a problem? Please describe.**
It can sometimes be frustrating to set the template engine for markdown, data, and HTML separately (and I _assume_ most of the time you'd want to set them to the same thing).

```js
  return {
    markdownTemplateEngine: 'njk',
    dataTemplateEngine: 'njk',
    htmlTemplateEngine: 'njk',
    dir: {
      input: 'src',
      output: 'dist'
    }
  };
```
&mdash; per https://github.com/andy-piccalilli/11ty-base/blob/598a7159e0589af5c1d104979dff612fc771b2b8/.eleventy.js#L25-L33

**Describe the solution you'd like**
Not sure if we can do something like `defaultTemplateEngine` in the return statement, which would default all 3 to the specified engine (unless they were overwritten). Although that might be tricky.
Conversely, if we had some `eleventyConfig.defaultTemplateEngine("njk")` method which sets the `markdownTemplateEngine`, `dataTemplateEngine`, and `htmlTemplateEngine` all at once for you.

**Describe alternatives you've considered**
Continue setting all 3 separately.  Not a huge deal. I mean, not a hill I'll die on or nothing.

**Additional context**
Nope. Loving what you do! 💯

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

Related: https://github.com/11ty/eleventy/issues/1502

**Comment by zachleat** [comment]
Note that the data preprocessing piece was deprecated and removed in v2 https://github.com/11ty/eleventy/issues/2728

Per #4079 we have added methods for the other two in v4!

This leaves us with an unlikely decision to add a combo method to combine two calls, so I’m going to remove this one for the queue, sorry!
