### ISSUE TITLE
Could you help update ejs in 0.12.2 release for @11ty/eleventy?

### ISSUE THREAD

**Issue by evansrobert** [11ty/eleventy#1932]
Hi, @zachleat, I'd like to report a vulnerability introduced by package **ejs**:
### Issue Description

   I noticed that a vulnerability is introduced in **_@11ty/eleventy@0.12.1_**:
     Vulnerability **SNYK-JS-EJS-1049328** affects package **_ejs_** (versions:<3.1.6):  [https://snyk.io/vuln/SNYK-JS-EJS-1049328](https://snyk.io/vuln/SNYK-JS-EJS-1049328)
  The above vulnerable package is referenced by **_@11ty/eleventy@0.12.1_** via:
`@11ty/eleventy@0.12.1 ➔ ejs@2.7.4`

Since **_@11ty/eleventy@0.12.1_** ([15,045 downloads per week](https://www.npmjs.com/package/@11ty/eleventy/v/0.12.1?activeTab=versions)) is referenced by a large number of downstream projects (e.g., [@cor-web/cor-design-system 0.1.77](https://www.npmjs.com/package/@cor-web/cor-design-system) (latest version), [nucleum 5.3.4](https://www.npmjs.com/package/nucleum) (latest version), [reslate 3.0.0-5](https://www.npmjs.com/package/reslate) (latest version), [@giddyup/cli 0.0.21](https://www.npmjs.com/package/@giddyup/cli) (latest version), [eleventy-plugin-metagen 1.4.0](https://www.npmjs.com/package/eleventy-plugin-metagen) (latest version)), the vulnerability [**SNYK-JS-EJS-1049328**](https://snyk.io/vuln/SNYK-JS-EJS-1049328) can be propagated into these downstream projects and expose security threats to them via the following package dependency paths:
 (1)`@cor-web/cor-design-system@0.1.74 ➔ @11ty/eleventy@0.12.1 ➔ ejs@2.7.4`
(2)`@visual-framework/vf-component-library@1.1.12 ➔ @11ty/eleventy@0.12.1 ➔ ejs@2.7.4`
  **......**

If **_@11ty/eleventy@0.12.\*_** removes the vulnerable package from the above version, then its fixed version can help downstream users decrease their pain.

**Given the large number of downstream users, could you help update your package to remove the vulnerability from @11ty/eleventy@0.12.1 ?**

### Fixing suggestions

In **_@11ty/eleventy@0.12.2**, maybe you can kindly try to perform the following upgrade :
`ejs ^2.7.4 ➔ ^3.1.6`; 

**Note:**
_**ejs@3.1.6**(>=3.1.6) has fixed the vulnerability [**SNYK-JS-EJS-1049328**](https://snyk.io/vuln/SNYK-JS-EJS-1049328)._

Thank you for your attention to this issue and welcome to share other ways to resolve the issue.

Best regards,
^_^

**Comment by zachleat** [comment]
Major template engine bumps require an Eleventy major version bump. We definitely wouldn’t do a 0.12.2 for this.  We _could_ do a 0.13.x but that would still require semver opt-in (and relies on those weird pre 1.0 exceptions in semver that I don’t agree with)

That said, we did migrate to ejs 3.x for the impending Eleventy 1.0: https://github.com/11ty/eleventy/issues/1392

If `ejs` wants to issue a fix for this in their 2.x branch, that’d be the best way for Eleventy 0.x forward.

Open to pushback for a 0.13.x if some others weigh in.

**Comment by pdehaan** [comment]
I don't think I'd be opposed to 0.13.x release that only bumps ejs. I think it might depend on if you have an ETA for when v1 is released (weeks-vs-months).

But makes me wonder if we should reconsider https://github.com/11ty/eleventy/issues/1103 since it means you could modify engines plugins independently of having to bump Eleventy versions.
Or if we release Eleventy v1 in a month, and then a week later LiquidJS updates to v10 and if that means we'd have to bump to Eleventy v2 (per "Major template engine bumps require an Eleventy major version bump.")

**Comment by zachleat** [comment]
If I had to guess there are 7 non-docs issues left on the milestone—I’d guess 2-4 weeks

**Comment by kleinfreund** [comment]
@zachleat @11ty/eleventy@1.0.1 uses ejs@3.1.6 (see https://github.com/11ty/eleventy/blob/v1.0.1/package.json) so I think this can be closed.

**Comment by zachleat** [comment]
Thanks @kleinfreund—yes! This somehow was left out of the release milestone but 1.0 does have ejs 3.x
