### ISSUE TITLE
CLI help does not mention port

### ISSUE THREAD

**Issue by cfjedimaster** [11ty/eleventy#1938]
**Describe the bug**
Run `eleventy --help`. The --port flag is not mentioned.

**Expected behavior**
It should mention it. :)

**Screenshots**

**Environment:**

- Eleventy Version: 0.12.1

**Comment by Snapstromegon** [comment]
The help mentions the flag in the description of ```--serve```:
```
     --serve
       Run web server on --port (default 8080) and watch them too
```

I agree with @cfjedimaster that it's probably better to add a seperate entry for ```--port``` (maybe right beneath serve) so that it's easier to find.
Maybe something like the following would do the trick:
```
     --serve
       Run web server on --port and watch them too
     --port
       Run the --serve web server on this port (default 8080)
```

**Comment by cfjedimaster** [comment]
Wow, didn't even notice it "under" --serve. It should (imo) definitely be at the top level.
