### ISSUE TITLE
Advanced Serverless Docs

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#1944]
Fill in these sections:

https://www.11ty.dev/docs/plugins/serverless/#re-use-build-time-collections

https://www.11ty.dev/docs/plugins/serverless/#swap-to-dynamic-using-the-data-cascade-and-eleventycomputed

https://www.11ty.dev/docs/plugins/serverless/#how-do-dynamic-templates-and-tags-work-together

**Comment by p-ob** [comment]
@zachleat Do you by chance have examples of https://www.11ty.dev/docs/plugins/serverless/#swap-to-dynamic-using-the-data-cascade-and-eleventycomputed?

I'm looking to explore hooking this up to enable optional auth for all pages in an 11ty site, and I'd be happy to submit an MR to fill in that section once completed if you're looking for assistance.

**Comment by zachleat** [comment]
Docs are building
