### ISSUE TITLE
Two separate collections: problem to output its own tags for each one

### ISSUE THREAD

**Issue by rocc-o** [11ty/eleventy#1951]
I have two separate collections and I want in each directory the tags output like this:
/sights/tags/(all tags for sights);
/sounds/tags/(all tags for sounds).

But instead I get:
/sights/tags/(all tags for sights and sounds);
/sounds/tags/(all tags for sounds and sights).

It seems that permalink, as I have it, cannot use dynamic data (I get errors). So I tried Computed data to define the permalink but I can't figure it out how to do it porperly; even tried filters and I failed miserably.

I have a repo here: https://github.com/rocc-o/raw-test-git

If anyone could suggest me how to solve this I would be very grateful. Thanks.

**Comment by rocc-o** [comment]
@pdehaan

something strange is happening.

With your changes it works perfectly, tags are not mixed up anyomre and all tags outputs are fine.

But, as soon as I use my own tags on each article, e.g.:

in  /sights/video-one.njk

tags:
  - documentary
  - Miles Davis
  - jazz

instead of your tags:

tags:
  - video one.1
  - video one.2
  - video one.3

I get:

`PS C:\Users\ricca\OneDrive\Documenti\Websites\rawriddims> npx @11ty/eleventy --serve

Problem writing Eleventy templates: (more in DEBUG output)
> Output conflict: multiple input files are writing to `_site/sights/tags/documentary/index.html`. Use distinct `permalink` values to resolve this conflict.
  1. ./sights/tags.njk
  2. ./sights/tags.njk

`DuplicatePermalinkOutputError` was thrown:
    (Repeated output has been truncated…)
        at TemplateMap.checkForDuplicatePermalinks (C:\Users\ricca\OneDrive\Documenti\Websites\rawriddims\node_modules\@11ty\eleventy\src\TemplateMap.js:547:13)
        at TemplateMap.cache (C:\Users\ricca\OneDrive\Documenti\Websites\rawriddims\node_modules\@11ty\eleventy\src\TemplateMap.js:308:10)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async TemplateWriter._createTemplateMap (C:\Users\ricca\OneDrive\Documenti\Websites\rawriddims\node_modules\@11ty\eleventy\src\TemplateWriter.js:170:5)
        at async TemplateWriter.writeTemplates (C:\Users\ricca\OneDrive\Documenti\Websites\rawriddims\node_modules\@11ty\eleventy\src\TemplateWriter.js:203:5)
        at async TemplateWriter.write (C:\Users\ricca\OneDrive\Documenti\Websites\rawriddims\node_modules\@11ty\eleventy\src\TemplateWriter.js:254:25)
        at async Eleventy.write (C:\Users\ricca\OneDrive\Documenti\Websites\rawriddims\node_modules\@11ty\eleventy\src\Eleventy.js:743:13)
        at async Eleventy.watch (C:\Users\ricca\OneDrive\Documenti\Websites\rawriddims\node_modules\@11ty\eleventy\src\Eleventy.js:650:5)
Copied 91 files / Wrote 0 files in 0.70 seconds (v0.12.1)
Watching…
[Browsersync] Access URLs:
 ------------------------------------
       Local: http://localhost:8080
    External: http://192.168.1.8:8080
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 ------------------------------------
[Browsersync] Serving files from: _site`

**Comment by pdehaan** [comment]
Duplicate permalink error from same page… My guess is that it might be something like one page uses “documentary” and another uses “Documentary” where the case is different but they resolve to the same slug. Just a guess, but worth a check. 
Apart from that, I’d need to check your repo and see what your dynamic pagination permalink key is for sights/tags.njk is to see what else might be colliding.

**Comment by rocc-o** [comment]
Your guess is right, sir! Capital D in one documentary tag it was.
Now it works properly, except on /sounds/index.njk there's no output for /sounds/tags/(any-tag)/
![immagine](https://user-images.githubusercontent.com/89341472/131222334-808226d7-c2ce-4e90-bc13-da00b998cfd9.png)

**Comment by pdehaan** [comment]
If you push your latest code to the GitHub repo, I can take a look later today.

**Comment by rocc-o** [comment]
I hope i did it correctly - I'm new on Github - I've done: Approve. Submit feedback and approve merging these changes.

**Comment by pdehaan** [comment]
Yeah, I think you just approved the changes from my PR, but not merged them. You'll need to click the green merge button, or just push your local version of the repo to the main/master branch and I can repull it locally.

Or if the latest/only changes are what I had in that approved PR, I can just try that locally and see if I can reproduce (but probably better to use your front matter data and content, plus a good exercise in git/GitHub).

**Comment by rocc-o** [comment]
@pdehaan

I think I did push my local version of the repo to the main/master branch with the latest changes from your "A few random tweaks #2" plus my own tags to reproduce the last problem: on /sounds/index.njk there's no output for /sounds/tags/(any-tag)/. I can see it updated on my repo now. I don't see any green merge button right now. I will have to come back tomorrow to make some exercise in git anyway - I'm starting now to understand how it works. if you need me to do anything else please just let me know and tomorrow I will dedicate myself full time. Thanks!

**Comment by pdehaan** [comment]
Here's what I see when I build locally and look at a /sounds/tags/{{tag}}/ page:

![localhost_8080_sounds_tags_mixtape_](https://user-images.githubusercontent.com/557895/131228978-12c7ec0d-b949-4011-845f-8acbf8e28e03.png)

**Comment by rocc-o** [comment]
This morning I build locally and the missing output at /sounds/tags/{{tag}}/ page was gone.
I suppose I had this problem yesterday because I did not delete sights and sound directories in _site output before building and perhaps it was a sum of errors, maybe, I really don't know. Anyway, this morning I ran a fresh build and everything works properly now.

 I have some questions, please:

1) in https://github.com/rocc-o/raw-test-git/pull/2 I see a list of "Conflicting files" on all files that have been modified, except /sounds/index.njk. What does it mean?


2) in https://github.com/rocc-o/raw-test-git/pull/1
 #.eleventy.js
```
  eleventyConfig.addFilter("head", (arr = [], idx = 0) => {
    if (idx < 0) {
      return arr.slice(idx);
    }
    return arr.slice(0, idx);
  });
```
You write: "You can probably ignore this...". I removed it. Is it ok? I've tried some more builds and no problem occurs at this moment.


3) Do I have to write comments in Nunjucks files only like this {# some comment #} ?


Thank you so much Peter for your great help, I was totally lost.

**Comment by rocc-o** [comment]
Sorry Peter, it's me again

the missing output is now happening at /sights/index.html
I did delete sights and sounds directories in _site output to avoind any possible error and ran builds several times but the problem persists. I did not change anything since this morning when it was working fine.

I have updated my repo, but I did not change anything from your previous modifications, I've just changed the index.njk in my repo, which I'm not running here locally and so it cannot be the problem. Locally I have an index.njk with html code only .

Here's the _site html output for /sights/index.njk where you can see there's no output data into the last part of html code for item.date; item.data.title; item.data.details. There's only the item.url outpupped and working at the beginning <a href="/sights/tags/sun-ra/">:

```
                        <article class="card">
                            <div class="article-cards-item">
                                <a href="/sights/tags/sun-ra/">
                                    <div class="article-cards-img-cntr">
                                        <picture>
                                            <source sizes="(min-width: 1760px) 335px, (min-width: 1280px) calc(16.96vw + 40px), (min-width: 1040px) calc(28.64vw - 17px), (min-width: 768px) 42.5vw, 85vw" srcset="544w, 638w, 690w, 852w" type="image/webp"><img sizes="(min-width: 1760px) 335px, (min-width: 1280px) calc(16.96vw + 40px), (min-width: 1040px) calc(28.64vw - 17px), (min-width: 768px) 42.5vw, 85vw" srcset="544w, 638w, 690w, 852w" src="" width="852"
                                                height="480" alt="" loading="lazy"></picture>
                                    </div>
                                    <p class="article-cards-date"><time datetime=""></time></p>
                                    <h2 class="article-cards-title"></h2>
                                    <p class="article-cards-details"></p>
                                </a>
                            </div>
                        </article>
```

**Comment by rocc-o** [comment]
Sorry again, I've noticed that when I comment out the "head filter" in eleventy.js the problem does not occurs anymore:

```
// (?) You can probably ignore this. I think it was from the index.njk and was throwing errors saying there wasn't a "head" filter,
// so I took a random guess. But then ended up using Nunjucks comments to comment out those code blocks anyways.
// https://github.com/rocc-o/raw-test-git/pull/1
//  eleventyConfig.addFilter("head", (arr = [], idx = 0) => {
//    if (idx < 0) {
//      return arr.slice(idx);
//    }
//    return arr.slice(0, idx);
//  });
```

I'm running now more build ad libitum to see if some magic happens. Hopefully that was the problem.

**Comment by pdehaan** [comment]
> 1. in [A few random tweaks rocc-o/raw-test-git#2](https://github.com/rocc-o/raw-test-git/pull/2) I see a list of "Conflicting files" on all files that have been modified, except /sounds/index.njk. What does it mean?

That means that a bunch of files changed in the target branch (main/master) from the time that I submitted the PR and now. So if you merged that PR somehow, you might overwrite newer changes. In order to fix that, I'd need to modify my PR to sync with the latest changes and then resolve any git conflicts. If your code is all working in the main/master branch, we can just ignore/close those PRs.

---

> 2. in [A few random tweaks rocc-o/raw-test-git#1](https://github.com/rocc-o/raw-test-git/pull/1)
>    #.eleventy.js
> 
> ```js
>   eleventyConfig.addFilter("head", (arr = [], idx = 0) => {
>     if (idx < 0) {
>       return arr.slice(idx);
>     }
>     return arr.slice(0, idx);
>   });
> ```
>
> You write: "You can probably ignore this...". I removed it. Is it ok? I've tried some more builds and no problem occurs at this moment.

Yeah, I think this was an issue w/ index.njk (or maybe the README.md file) where it was referencing some `head` filter which wasn't in the .eleventy.js file, so I took a stab at implementing it. Then I realized which code was calling the filter and then just commented that code out.

---

> 1. Do I have to write comments in Nunjucks files only like this {# some comment #} ?

You don't HAVE to, but there are some subtle "gotchas" with comments sometimes. I think of Nunjucks as a preprocessor. So if you do HTML style `<!-- ... -->` comments, Nunjucks will still process all that content to your page and just hide it in the HTML output. Can be useful for debugging in some cases. But if you do Nunjucks style `{# ... #}` comments, Nunjucks won't try processing any of that and it won't be rendered into the output file. This was the `head` comment I was making earlier. Since the code was in an HTML comment, Nunjucks was still processing those tags and looking for a filter that didn't exist and was throwing errors, so I switched to Nunjucks comments since the code in question was more an internal discussion and TODOs.

**Comment by pdehaan** [comment]
If you're getting empty output, you might need to confirm which collection you are looping over. Remember, your custom `sightsTagsList` collection is only an array of tag names, not actual posts. So you might need to do something like this:

```diff
diff --git a/index.njk b/index.njk
index 474a758..c3aff02 100644
--- a/index.njk
+++ b/index.njk
@@ -14,17 +14,12 @@ eleventyNavigation:

 <h2>Latest articles in Sights</h2>
 {# START articles #}
-    {% set postslist = collections.sightsTagsList | head(-4) %}
-    {% set postslistCounter = collections.sightsTagsList | length %}
+    {% set postListItems = collections.sights | head(-4) %}
     {% include "partials/components/post-list.njk" %}
 {# END articles #}

-
 <h2>Latest articles in Sounds</h2>
 {# START articles #}
-    {% set postslist = collections.soundsTagsList | head(-4) %}
-    {% set postslistCounter = collections.soundsTagsList | length %}
+    {% set postListItems = collections.sounds | head(-4) %}
     {% include "partials/components/post-list.njk" %}
 {# END articles #}
```

**Comment by rocc-o** [comment]
Thanks Peter, I will look this matter of Lates post later, because now I have that missing output problem I was mentioning before keeping coming:
After several builds, without touching any code at all, I get the missing output sometimes in /sights/index.njk and sometimes in /sights/index.njk.
I really have no clue.

**Comment by pdehaan** [comment]
Oh interesting. I think I saw that once where it wasn't outputting the title and stuff, but then it disappeared after a rebuild and I don't remember seeing it again. I figured it was just I didn't save one of my templates while debugging. But not sure why that would ever be intermittently rendering.

I'll take another look at sights/index.njk and see if anything looks curious.

**Comment by pdehaan** [comment]
OK, this is weird. Sometimes it renders 2 pages, sometimes 8. I think its semi-related to the pagination of the tags as well. So the intermittent issue might be due to which order the stuff gets built. If it gets to sights/tags/ pagination first, then there are 8-ish templates that it finds. If it does sights/index.njk first, then it seems to only write 2 files (because I guess there are 4 videos with a pagination size of 2).

I'm still trying to think of a workaround or explanation.

**Comment by pdehaan** [comment]
OK, maybe not ideal, but one workaround seems to be changing ./sights/tags.njk to ./sights_tags.njk so it sits outside the ./sights/ folder and doesn't get picked up by that `collection.getFilteredByGlob("./sights/*.njk");` collection glob. After trying that locally I always seem to get the expected 34 files built.

**Comment by rocc-o** [comment]
I see. But in this way I will have a confusing site navigation. I'd rather to upload the site (directly the output _site) to github / cloudflare pages only and when the build is done correctly.

**Comment by pdehaan** [comment]
The site navigation doesn't change, the permalinks in the sights/sounds tags.njk files still write the files to the same place.

I don't think there is ever a guaranteed order in which eleventy pipeline builds the site. But something feels a bit strange here so I'll see if I can create a simpler test case that reproduces the error and file that as a new bug.

**Comment by rocc-o** [comment]
Ok, I see. Now it's 23.00 pm here in Italy. Tomorrow morning I will change into ./sights_tags.njk and ./sounds_tags.njk, run some more builds, check how many files are written each time and I will let you know.
Thank you Peter.

**Comment by rocc-o** [comment]
Hi Peter,
I've changed to ./sights_tags.njk and ./sounds_tags.njk, made several builds and each time is working properly without rendering empty blocks and it's always the same number of files built. I've noticed though that the order in which Eleventy pipeline builds the site is different each time. 
Please note I'm running Eleventy v0.12.1 with Node v14.16.1 on Windows 10.

**Comment by rocc-o** [comment]
Peter, meanwhile I'm trying your change for latest posts on homepage
```
     {% set postListItems = collections.sights | head(-4) %}
     {% include "partials/components/post-list.njk" %}
```
But i get:
```
File changed: index.njk
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering njk template ./index.njk

`TemplateContentRenderError` was thrown
> (./index.njk)
  Error: filter not found: head
```

**Comment by pdehaan** [comment]
> Sorry again, I've noticed that when I comment out the "head filter" in eleventy.js the problem does not occurs anymore:
> 
> ```
> // (?) You can probably ignore this. I think it was from the index.njk and was throwing errors saying there wasn't a "head" filter,
> // so I took a random guess. But then ended up using Nunjucks comments to comment out those code blocks anyways.
> // https://github.com/rocc-o/raw-test-git/pull/1
> //  eleventyConfig.addFilter("head", (arr = [], idx = 0) => {
> //    if (idx < 0) {
> //      return arr.slice(idx);
> //    }
> //    return arr.slice(0, idx);
> //  });
> ```

Make sure you uncomment out that custom filter in your .eleventy.js file.

**Comment by rocc-o** [comment]
Yes Peter, now it works. Thank you very much for everything. Thanks to you now I begin to understand something more about SSG and Eleventy.

**Comment by pdehaan** [comment]
Awesome, congrats!
Feel free to close this issue and we can open a new one (or use the Discussions tab) if you run into any other issues.

**Comment by rocc-o** [comment]
Ok 🥇
