### ISSUE TITLE
Proposed: Switch from path-to-regex to urlpattern-polyfill

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#1954]
Pre-1.0 status it might be awesome to attempt to switch the serverless URL matching code from https://www.npmjs.com/package/url-pattern to the future standard https://www.npmjs.com/package/urlpattern-polyfill

Documented at https://web.dev/urlpattern/

This will likely pay dividends later and keep us on the standards track for this feature.

Inspired by https://twitter.com/wanderview/status/1433535232268017665

**Comment by Snapstromegon** [comment]
I think this is a great idea, since 11ty is still at a stage where such a switch is the least painful to adopt.
The next point after 1.0 would be 2.0 IMO and that is probably some time away.

Also I think that URLPattern is stable enough so we don't need to fear that it will change in the future in any significant way.

I think 11ty should try to make as many open/upcoming breaking changes while upgrading to 1.0 as it can, so that 11ty can be stable after that.

**Comment by zachleat** [comment]
Blocked upstream by https://github.com/kenchris/urlpattern-polyfill/issues/38

**Comment by zachleat** [comment]
Alternatively, switch to https://github.com/pillarjs/path-to-regexp as a smoother transition step if `urlpattern-polyfill` isn’t gonna fit the timeline

Reasoning here is that `path-to-regexp` is the basis for the URLPattern syntax https://github.com/WICG/urlpattern/blob/main/explainer.md#urlpattern

**Comment by zachleat** [comment]
Filed the above comment at https://github.com/11ty/eleventy/issues/1988 and moved this one out of the 1.0 milestone.

**Comment by zachleat** [comment]
Officially, `path-to-regexp` shipped with 1.0.0 Canary 45 and Beta 1.

This issue is now for a migration from `path-to-regexp` to `urlpattern-polyfill`

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
Milestoning this to 2.0

**Comment by zachleat** [comment]
After further research I’m not sure `URLPattern` can quite get us there. It can’t generate URLs quite yet!

Related:
https://github.com/WICG/urlpattern/discussions/41
https://github.com/WICG/urlpattern/issues/73

We currently rely on this from `path-to-regexp` for the `serverlessUrl` filter https://github.com/11ty/eleventy/blob/27f54aaa30230d18fd6ddf13b5f007b9367a54c8/src/Filters/ServerlessUrl.js#L7

Related:
https://www.npmjs.com/package/path-to-regexp#user-content-compile-reverse-path-to-regexp

**Comment by zachleat** [comment]
De-milestoning from 2.0, sorry y’all! Re-adding to the enhancement queue.

> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
Removing from queue per Serverless retirement https://www.11ty.dev/docs/plugins/serverless/
