### ISSUE TITLE
How to sort a list of names with custom key in front matter?

### ISSUE THREAD

**Issue by rocc-o** [11ty/eleventy#1959]
In my article pages I have a key in front matter for each contributor and a specific tag "post" just to create the collection:

``
tags:
  - sometag
  - someothertag
  - post
contributor: johnny
``

and I'm using this filter to sort each contributor's articles

``
   eleventyConfig.addFilter("getContributor", (contributors,label) => {
 		let contributor = contributors.filter(a => a.key === label)[0];
 		return contributor;
 	});
``
``
 	eleventyConfig.addFilter("getPostsByContributor", (posts,contributor) => {
 		return posts.filter(a => a.data.contributor === contributor);
 	});
``

Everything works. But now I'd like also to create the list of all contributors with links to their pages. This is what I am trying, but without succeeding:

``
{% set myContributor = contributors | getContributor(contributor) %}
<a href="/contributors/{{ contributor }}">{{ myContributor.name }}</a>
``

Also, about that specific tag "post" I was mentioning before: in my article pages I output the related tags like this

``
        {% for item in tags %}
        <a href="/sights/tags/{{ item | slug }}" class="tags"> {{ item }} </a>
        {% endfor %}
``

but it outputs also that specific tag "post" that I'm using just to create the collection and I really don't want to show it.
I do have in my tags.njk "filter: - post" and it works, but in article pages it doesn't. There is any other way to exclude that "post" tag from the output on my article pages?

**Comment by pdehaan** [comment]
```njk
{% set myContributor = contributors | getContributor(contributor) %} <a href="/contributors/{{ contributor }}">{{ myContributor.name }}</a>
```

Do you have a public repo somewhere? I'm curious what `contributors` looks like and where it comes from.

**Comment by pdehaan** [comment]
```njk
{% set myContributor = contributors | getContributor(contributor) %}
<a href="/contributors/{{ contributor }}">{{ myContributor.name }}</a>
```

If I'm reading this correctly, `contributors` would be an array of objects (with at least a `key` and `name` field), and I'm guessing `contributors` might be from a global data file. You also use your custom `getContributor` filter which takes the contributor key/label as an attribute and returns the first matching object from the `contributors` array.

Not sure I'm understanding how that fits together. I think it makes sense if you're on an individual article page and you want to display the info for the current contributor. But not sure if it'd work like I'm imagining for generating a list of _all contributors_.
I figured you'd want something more like this for a contributors archive page:

```njk
{% for contributor in contributors %}
  <a href="/contributors/{{ contributor.key | slug }}/">{{ contributor.name }}</a>
{% endfor %}
```

**Comment by pdehaan** [comment]
> ```njk
> {% for item in tags %}
>   <a href="/sights/tags/{{ item | slug }}" class="tags"> {{ item }} </a>
> {% endfor %}
> ```
> 
> but it outputs also that specific tag "post" that I'm using just to create the collection and I really don't want to show it.
> I do have in my tags.njk "filter: - post" and it works, but in article pages it doesn't. There is any other way to exclude that "post" tag from the output on my article pages?

Not sure about excluding tags without using pagination or other custom filters. I usually just get lazy and throw in an extra `{% if %}` statement.

```njk
{%- for item in tags %}
  {%- if item !== "post" %}
    <a href="/sights/tags/{{ item | slug }}" class="tags"> {{ item }} </a>
  {%- endif %}
{%- endfor %}
```

### OUTPUT

```html
<a href="/sights/tags/one/" class="tags"> one </a>
<a href="/sights/tags/two/" class="tags"> two </a>
<a href="/sights/tags/seven/" class="tags"> seven </a>
<a href="/sights/tags/archived/" class="tags"> archived </a>
<a href="/sights/tags/index/" class="tags"> index </a>
<a href="/sights/tags/home/" class="tags"> home </a>
```

Although if it's a pattern you repeat often, it might be worth wrapping it in a custom filter.

```js
eleventyConfig.addFilter("no_posts", (values=[]) => values.filter(value => value !== "post"));
```

Or you could get more clever and pass an array of tags/strings to exclude:

```js
eleventyConfig.addFilter("exclude", (values=[], ...ignores) => values.filter(value => !ignores.includes(value)));
```

---

```js
// .eleventy.js
module.exports = eleventyConfig => {
  eleventyConfig.addFilter("inspect", require("util").inspect);

  eleventyConfig.addFilter("no_posts", (values=[]) => values.filter(value => value !== "post"));
  eleventyConfig.addFilter("exclude", (values=[], ...ignores) => values.filter(value => !ignores.includes(value)));

  return {
    dir: {
      input: "src",
      output: "www"
    }
  };
};
```

### Sample njk template:

```njk
---
title: HoMe
tags:
  - one
  - two
  - post
  - seven
  - archived
  - index
  - home
---

{{ tags | no_posts | inspect | safe }}

<hr/>

{{ tags | inspect | safe }}

{{ tags | exclude("post") | inspect | safe }}

{{ tags | exclude("post", "home", "index") | inspect | safe }}
```

### OUTPUT

```html
[ 'one', 'two', 'seven', 'archived', 'index', 'home' ]

<hr/>

[ 'one', 'two', 'post', 'seven', 'archived', 'index', 'home' ]

[ 'one', 'two', 'seven', 'archived', 'index', 'home' ]

[ 'one', 'two', 'seven', 'archived' ]
```

**Comment by rocc-o** [comment]
Hello Peter, nice to hear from you! 

For the contributor thing I've just updated it with your change and it works. Thank you!

Conecerning the "post" tag: I'm trying your custom filter but I can't make it work. 
I have now updated my repo with it: [https://github.com/rocc-o/raw-test-git](url)
Also, if possible,  I would like the tag not to be produced in the tags folder to avoid indexing of search engines.

**Comment by rocc-o** [comment]
Ok, I finally found a way.
Placed " filter:  - post" in both tags.njk pages to prevent the "post" tag from being placed in the tags folders, and added your  extra {% if %} statement on each page where there is a tag output. 
It seems to work. Anyway i'm trying some other builds to avoid strange surprises and i'll let you know.

**Comment by pdehaan** [comment]
@rocc-o That's great! Feel free to close the issue if it answered your question.

**Comment by rocc-o** [comment]
Ok. Thank you.
