### ISSUE TITLE
Nunjucks loop variable no longer working

### ISSUE THREAD

**Issue by mmontevil** [11ty/eleventy#1960]
**Describe the bug**
Some nunjucks loop variables are not accessible or wrong in the last canary version

**To Reproduce**

1. Use loop.index0 in a nunjucks template, for example: {{loop.index0}} in a for loop
2. Run eleventy
3. Open the resulting html
3. No output (loop.index always yields 1)

**Expected behavior**
Should work like described in
https://mozilla.github.io/nunjucks/fr/templating.html#for

**Environment:**

- OS and Version: Linux
- Eleventy Version: 1.0.0-canary.42

**Additional context**
Work as expected in 1.0.0-canary.41
The bug appears with a minimal working example attached
[test.zip](https://github.com/11ty/eleventy/files/7112500/test.zip)

**Comment by pdehaan** [comment]
Well, that's certainly interesting! Good catch!

Don't even need collections or anything fancy. I can reproduce it w/ a simple array:

```njk
---
title: "@11ty/eleventy #1960"
permalink: "index.{% 11ty_version %}.html"
---

<h1>{{ title }}</h1>

<ul>
{%- for post in [1,2,3,4,5,88] -%}
  <li>loop.index {{ loop.index }}, loop.index0 {{ loop.index0 }} &mdash; {{ post }}</li>
{%- endfor -%}
</ul>

<hr/>

<p>@11ty/eleventy: {% 11ty_version %}</p>
<p>nunjucks: {% nunjucks_version %}</p>
```

```js
// .eleventy.js
module.exports = (eleventyConfig) => {
  eleventyConfig.addShortcode("11ty_version", () => require("@11ty/eleventy/package.json").version);
  eleventyConfig.addShortcode("nunjucks_version", () => require("nunjucks/package.json").version);
  return {
    dir: {
      input: "src",
      output: "www"
    }
  };
};
```

### OUTPUT

```html
<ul>
  <li>loop.index 1, loop.index0 0 &mdash; 1</li>
  <li>loop.index 2, loop.index0 1 &mdash; 2</li>
  <li>loop.index 3, loop.index0 2 &mdash; 3</li>
  <li>loop.index 4, loop.index0 3 &mdash; 4</li>
  <li>loop.index 5, loop.index0 4 &mdash; 5</li>
  <li>loop.index 6, loop.index0 5 &mdash; 88</li>
</ul>

<hr />

<p>@11ty/eleventy: 0.12.1</p>
<p>nunjucks: 3.2.3</p>
```

```html
<ul>
  <li>loop.index 1, loop.index0 &mdash; 1</li>
  <li>loop.index 1, loop.index0 &mdash; 2</li>
  <li>loop.index 1, loop.index0 &mdash; 3</li>
  <li>loop.index 1, loop.index0 &mdash; 4</li>
  <li>loop.index 1, loop.index0 &mdash; 5</li>
  <li>loop.index 1, loop.index0 &mdash; 88</li>
</ul>

<hr />

<p>@11ty/eleventy: 1.0.0-canary.42</p>
<p>nunjucks: 3.2.3</p>
```

```html
<ul>
  <li>loop.index 1, loop.index0 0 &mdash; 1</li>
  <li>loop.index 2, loop.index0 1 &mdash; 2</li>
  <li>loop.index 3, loop.index0 2 &mdash; 3</li>
  <li>loop.index 4, loop.index0 3 &mdash; 4</li>
  <li>loop.index 5, loop.index0 4 &mdash; 5</li>
  <li>loop.index 6, loop.index0 5 &mdash; 88</li>
</ul>

<hr />

<p>@11ty/eleventy: 1.0.0-canary.41</p>
<p>nunjucks: 3.2.3</p>
```

**Comment by pdehaan** [comment]
If you have npm 7, you can get the diff from canary.41..canary.42 w/ the following:

<kbd>npm diff --diff @11ty/eleventy@1.0.0-canary.41 --diff @11ty/eleventy@canary</kbd>

Or since they are tags, you can probably compare them in GitHub much easier: https://github.com/11ty/eleventy/compare/v1.0.0-canary.41...v1.0.0-canary.42

**Comment by pdehaan** [comment]
@mmontevil In the meantime, I think you can fix this locally by disabling Nunjucks speedboost via an env var:

```bash
ELEVENTY_NUNJUCKS_SPEEDBOOST_OPTOUT=1 eleventy
```

```html
<h1>@11ty/eleventy #1960</h1>

<ul>
  <li>loop.index 1, loop.index0 0 &mdash; 1</li>
  <li>loop.index 2, loop.index0 1 &mdash; 2</li>
  <li>loop.index 3, loop.index0 2 &mdash; 3</li>
  <li>loop.index 4, loop.index0 3 &mdash; 4</li>
  <li>loop.index 5, loop.index0 4 &mdash; 5</li>
  <li>loop.index 6, loop.index0 5 &mdash; 88</li>
</ul>

<hr/>

<p>@11ty/eleventy: 1.0.0-canary.42</p>
<p>nunjucks: 3.2.3</p>
```

**Comment by zachleat** [comment]
This is a very good catch. This is suspiciously similar to the issue that @SaraSoueidan ran into recently, although Canary 42 wasn’t released yet.

I’m going to swap this env variable from OPTOUT to OPTIN and turn it off by default.

https://twitter.com/SaraSoueidan/status/1431569014162173957
https://twitter.com/SaraSoueidan/status/1431712492137455621

**Comment by zachleat** [comment]
Shipping with Canary 43.

**Comment by zachleat** [comment]
Canary 43 is released!

**Comment by mmontevil** [comment]
I'm glad it helped. 
Canary 43 indeed works as expected, that was a bug promptly squashed, thank you!

**Comment by SaraSoueidan** [comment]
Thank you @zachleat ! I had the same issue again on another project and couldn't fix it on the other one by updating Node and re-installing. I'm happy I saw this issue today 💕
