### ISSUE TITLE
Can’t access `fileSlug` when iterating through collection items

### ISSUE THREAD

**Issue by paulrobertlloyd** [11ty/eleventy#197]
On a page, I can access the following values:

```
url: {{ page.url }}<br>
inputPath: {{ page.inputPath }}<br>
outputPath: {{ page.outputPath }}<br>
fileSlug: {{ page.fileSlug }}
```

and output the following:

```
url: /projects/bradshaws_guide.html
inputPath: ./src/_content/projects/bradshaws_guide.md
outputPath: www/projects/bradshaws_guide.html
fileSlug: bradshaws_guide
```

However, when I iterate though each item within a collection, like so:

```
{% for item in collections.projects -%}
  url: {{ item.url }}<br>
  inputPath: {{ item.inputPath }}<br>
  outputPath: {{ item.outputPath }}<br>
  fileSlug: {{ item.fileSlug }}<br>
{%- endfor %}
```

I get the following output:

```
url: /projects/bradshaws_guide.html
inputPath: ./src/_content/projects/bradshaws_guide.md
outputPath: www/projects/bradshaws_guide.html
fileSlug: 
url: /projects/24_ways.html
inputPath: ./src/_content/projects/24_ways.md
outputPath: www/projects/24_ways.html
fileSlug: 
…
```

As you can see, no value is returned for {{ item.fileSlug }}.

**Comment by jevets** [comment]
You can get to it via `{{ item.data.page.fileSlug }}`, but I'd also like to see it readily available under `item`, just like `item.url`.

**Comment by jevets** [comment]
Note `item.data.page` is probably undefined if the collection items come from JSON data. (I haven't checked this)

**Comment by paulrobertlloyd** [comment]
Ah-ha, so `item.x` values are (typically) alias corresponding `item.data.page.x` values? Did you find this by examining the code? Anyway, thanks for the pointer. And another issue in support of #130.

**Comment by jevets** [comment]
Sure thing! I think I found it via many calls to `console.log(item)` and just digging :)
Indeed, more support for #130

**Comment by zachleat** [comment]
This will be available in `item.fileSlug` as well as in `item.data.page.fileSlug` in 0.5.3.

Additional data standardization work will continue to happen in #130.

**Comment by paulrobertlloyd** [comment]
Excellent, thanks @zachleat!
