### ISSUE TITLE
Trying to paginate each contributor's articles created with custom filter

### ISSUE THREAD

**Issue by rocc-o** [11ty/eleventy#1974]
I'm filtering each contributor's articles sothat each contributor's page outputs a list of his articles only, like this:

```
   eleventyConfig.addFilter("getContributor", (contributors,label) => {
 		let contributor = contributors.filter(a => a.key === label)[0];
 		return contributor;
 	});

 	eleventyConfig.addFilter("getPostsByContributor", (posts,contributor) => {
 		return posts.filter(a => a.data.contributor === contributor);
 	});
```

```
---
contributor: gertrude
---

{% if contributor %}
{% set myContributor = contributors | getContributor(contributor) %}

<h3>Articles by {{ myContributor.name }}</h3>
{% set posts = collections.post | getPostsByContributor(myContributor.key) %}
<ul>
{% for post in posts | reverse %}
	<li><a href="{{ post.url }}">{{ post.data.title }}</a> &mdash; <time datetime="{{ post.data.date | dateymd }}">{{ post.data.date | datefriendly }}</time></li>
{% endfor %}
</ul>

{% endif %}
```
And everything works. But I cannot find a way to paginate each contributor's articles.
I've tried in front matter:
```
pagination:
  data: collections.post
  size: 2
  alias: post
```
and then ` {% include "partials/components/pagination.njk" %}` 
But it doesn't outputs 2 articles per page. Instead - if there are let's say 5 articles of that contributor - outputs 5 pages, but each page is showing all articles of that contributor.

If you need more details, here's [ my repo:](https://github.com/rocc-o/raw-test-git)

**Comment by pdehaan** [comment]
This was oddly tricky&hellip;

I think the best solution I've found so far is to just create custom collections for each contributor:

```js
// .eleventy.js snippet

  const contributors = require("./src/_data/contributors.js");
  for (const contributor of contributors) {
    eleventyConfig.addCollection(`contributor_${contributor.key}`, (collectionApi) => {
      return collectionApi.getFilteredByTag("post")
        .filter(post => post.data.contributor === contributor.key);
    });
  }
```

This will create a custom collection for each contributor with the name `collections.contributor_gertrude` (or `contributor_johnny` or `contributor_andrea`).

Then you can use the custom collection in your pagination like below (although you have to define your contributor name in two places now; in the `contributor` key, and in the `pagination.data` value):

```njk
---
contributor: gertrude
pagination:
  size: 2
  alias: contributorPosts
  data: "collections.contributor_gertrude"
---
```

I also tried using the [`pagination.before` callback](https://www.11ty.dev/docs/pagination/#the-before-callback), but that felt more awkward.

Ideally I was hoping I could add the contributor posts to the global contributors JS/JSON file, but I don't think that works because the global data file wouldn't have access to the collection data.

**Comment by rocc-o** [comment]
I've tried your custom collections with front matter: it outputs the desired number of pages, but again each page has the complete list of all articles for each contributor. Updated my repo accordingly: [https://github.com/rocc-o/raw-test-git](url)

**Comment by pdehaan** [comment]
I don’t think you’re using your custom collection
https://github.com/rocc-o/raw-test-git/blob/0a4467a7d4314877db51dff35b830bd736b276fa/contributors/gertrude-vacher.njk#L23

**Comment by pdehaan** [comment]
```njk
<h3>Articles by {{ myContributor.name }}</h3>
{% set posts = collections.post | getPostsByContributor(myContributor.key) %}
<ul>
{% for post in posts | reverse %}
```

actually, I think this should loop over the paginated `contributorPosts` alias.

**Comment by rocc-o** [comment]
{% set posts = collections.contributor_gertrude %}

Is this correct? 
I'm having the same issue.

**Comment by pdehaan** [comment]
I just cloned the repo and built the site and here's the snippet from _site/contributors/gertrude-vacher/index.html:

```html
<h3>Articles by Gertrude Vacher</h3>

<ul>
	<li><a href="/sounds/audio-three/">Audio 3 Title</a> &mdash; <time datetime="2021-07-22">22 July, 2021</time></li>
	<li><a href="/sights/video-four/">Video Test Four</a> &mdash; <time datetime="2021-07-10">10 July, 2021</time></li>
</ul>
```

Which I verified against the actual sites/sounds contributors using:

```sh
git grep "contributor: gertrude"

contributors/gertrude-vacher.njk:contributor: gertrude
sights/video-four.njk:contributor: gertrude
sounds/audio-three.njk:contributor: gertrude
```

**Comment by pdehaan** [comment]
We can also semi-confirm w/ `contributor: andrea` as well:

```html
<h3>Articles by Andrea Berardi</h3>

<ul>
	<li><a href="/sounds/audio-one/">Audio 1 Title</a> &mdash; <time datetime="2021-07-24">24 July, 2021</time></li>
	<li><a href="/sights/video-two/">Video Test Two</a> &mdash; <time datetime="2021-07-09">9 July, 2021</time></li>
	<li><a href="/sights/video-one/">Video Test One</a> &mdash; <time datetime="2021-07-06">6 July, 2021</time></li>
</ul>
```

And the following:

```sh
git grep "contributor: andrea"

contributors/andrea-berardi.njk:contributor: andrea
sights/video-one.njk:contributor: andrea
sights/video-two.njk:contributor: andrea
sounds/audio-one.njk:contributor: andrea
```

Which is interesting, because there is also a _site/contributors/andrea-berardi/1/index.html, so we know pagination is doing _something_ but it's also showing the same 3 results on the ./index.html and ./1/index.html page.

The problem seems to be we're looping over the unpaginated collection. Here's the fix:

```diff
<h3>Articles by {{ myContributor.name }}</h3>
-{% set posts = collections.contributor_gertrude %}
<ul>
-{% for post in posts | reverse %}
+{% for post in contributorPosts | reverse %}
	<li><a href="{{ post.url }}">{{ post.data.title }}</a> &mdash; <time datetime="{{ post.data.date | dateymd }}">{{ post.data.date | datefriendly }}</time></li>
{% endfor %}
</ul>
```

**Comment by rocc-o** [comment]
Yes! Your fix is working! But please give me a few hours before to close this as I have to make some more test. Thank you very much, Peter!

**Comment by rocc-o** [comment]
Ok. Everything is fine. Thank you again!
