### ISSUE TITLE
Template and Directory Specific Data Files does not work

### ISSUE THREAD

**Issue by tereska** [11ty/eleventy#1976]
According to documentation: (point nr 4)

https://www.11ty.dev/docs/data-template-dir/

I can create "local" data file for my template.

Lets say I have project/src/colors/colors.njk template file.
I should be able to create /project/src/colors/colors.11tydata.json file and this should be accessible to my colors.njk file.
Unfortunately I dont have access to data from colors.11tydata.json.

```
project/src/colors/colors.njk:
hello

{{ colors | dump }}

{{colors}}
```

```
project/src/colors/colors.11tydata.json:
{
    "some": "data"
}
```

I does not work also when I will create colors.11tydata.js (and return some data)
How I can create data that is "local" to one template? (I cant use front matter).
Why this is not working?

**Comment by pdehaan** [comment]
I think the issue is that the values from colors.11tydata.json are available in your template, but not in a "colors" namespace, but they'll appear as local variables.

Since your colors.11tydata.json has a "some" key, try the following:

```njk
{{ some | dump }}
{{ some }}
```

That should give you something like the following output:

```html
'data'
data
```

**Comment by pdehaan** [comment]
And I think one other important note is that this appears to be a DIRECTORY data file, not a TEMPLATE data file (even though the directory and template are both named "colors/" and "colors.njk" respectively).

If you create a project/src/colors/foo.njk file, the same `some` variables [from colors.11tydata.json] should be available in that template as well.

**Comment by tereska** [comment]
Thank you! your suggestion works like a charm!

It also works in the same way when using .js data files:

```
project/src/colors/colors.11tydata.js:
module.exports = function() {
    return new Promise((resolve, reject) => {
        resolve({some: [
            {title: "title1", slug: "slug1"},
            {title: "title2", slug: "slug2"}
        ]});
    });
};
``
