### ISSUE TITLE
Access .eleventy.js data in templates

### ISSUE THREAD

**Issue by rolandtoth** [11ty/eleventy#198]
Is there a way to access .eleventy.js data in template files? I would like to eg. add a `data-subdir="{{ eleventyConfig.pathPrefix }}"` attribute to the DOM to read with JavaScript and prepend it to paths (eg. for AJAX calls).

I did some search and tried config, eleventyConfig, eleventy but nothing seemed to work. It would be useful as it would help avoiding duplicate declarations (and possible errors).

**Comment by kleinfreund** [comment]
Duplicate of #184.

**Comment by rolandtoth** [comment]
Thanks, closing this then.

**Comment by zachleat** [comment]
Thanks @kleinfreund!
