### ISSUE TITLE
Problems with output for latest articles on homepage, etc.

### ISSUE THREAD

**Issue by rocc-o** [11ty/eleventy#1983]
The outputs for my blog are fine, but in the following pages where I'm trying specific outputs I'm having problems

1) Latest posts in homepage does not outputs the very last article, but it starts from the second-last.

/index.njk

```
<h2>Latest articles in Sights</h2>

{% set postListItems = collections.sights | head(-4) %}
{% include "partials/components/post-list.njk" %}

<h2>Latest articles in Sounds</h2>

{% set postListItems = collections.sounds | head(-4) %}
{% include "partials/components/post-list.njk" %}
```

2) In a page where are shown the articles for each contributor with pagination, the articles are sorted with no consequentiality between the pages: 

Page 1
article dated 19 September
article dated 17 September

Page 2
article dated 22 September
article dated 20 September

Page 3
article dated 23 September
article dated 22 September

/contributors/gertrude-vacher.njk

```
{% for post in contributorPosts | reverse %}
	<li><a href="{{ post.url }}">{{ post.data.title }}</a> &mdash; <time datetime="{{ post.data.date | dateymd }}">{{ post.data.date | datefriendly }}</time></li>
{% endfor %}
```

Please for more details see my repo: [https://github.com/rocc-o/raw-test-git](https://github.com/rocc-o/raw-test-git)

**Comment by pdehaan** [comment]
> 1. Latest posts in homepage does not outputs the very last article, but it starts from the second-last.

I don't really know your data so I'm not sure what is last and not last or what's expected, but here's the output I see on index.html:

> ## HOMEPAGE
> ### Latest articles in Sights
>
> 10 July, 2021
> **Video Test Four**
> Promo, 2020
>
> 9 July, 2021
> **Video Test Two**
> Ident, 2021
>
> 9 July, 2021
> **Video Test Three**
> Docu, 2020
>
> 6 July, 2021
> **Video Test One**
> Ident, 2019
>
> ### Latest articles in Sounds
> 24 July, 2021
> **Audio 2 Title**
> Audio promo, 2020
>
> 24 July, 2021
> **Audio 1 Title**
> Audio promo, 2021
>
> 22 July, 2021
> **Audio 3 Title**
> Audio sound, 2019
>
> 20 July, 2021
> **Audio 4 Title**
> Audio record, 2017

So it appears that the sights and sounds are sorted by date, descending.

**Comment by pdehaan** [comment]
> 2. In a page where are shown the articles for each contributor with pagination, the articles are sorted with no consequentiality between the pages:

Ah, I think we need to sort the custom collection.

```js
// create custom collections for each contributor
// in order to paginate each contributor's articles on his contributor's page
const contributors = require("./_data/contributors.json");
for (const contributor of contributors) {
  eleventyConfig.addCollection(`contributor_${contributor.key}`, (collectionApi) => {
    return collectionApi.getFilteredByTag("post")
      .filter(post => post.data.contributor === contributor.key)
      .sort((a, b) => Date.parse(b.date) - Date.parse(a.date));
  });
}
```

Then you can probably remove the "reverse" filter on the contributor pages [since we're pre-sorting the collection in reverse order]:
```njk
{% for post in contributorPosts %}
```

**Comment by rocc-o** [comment]
Ok for contributor pages, your fix is working. Thanks!
But for latest posts in homepage I do have a problem at my ends, which I see it doesn't occurs to you in the repo. In fact I do get sights and sounds sorted by descending date, but the latest article - the last one I add, the newest one - is missing both in sights and sounds. The eleventy config at my ends is slightly different from the one in my repo as I've added an rss plugin and a filter for search function. So please let me check better tomorrow if there is some conflict, I'll run some test and in case I will update my repo if the problem persists.

**Comment by rocc-o** [comment]
It seems that when there are more than four posts in a direcotry, the Latest Posts shown on the homepage stop to the fourth post starting from the oldest, and therefore not showing the last one added (the fifth post).

For example, if in direcotry Sounds there are the following posts:
- audio-zero.njk (date: 2021-09-24 - the last one added, the fifth post)
- audio-one.njk (date: 2021-07-24)
- audio-two.njk (date: 2021-07-24)
- audio-three.njk (date: 2021-07-22)
- audio-four.njk (2021-07-20)

I get in homepage Latest Posts:
- audio-one.njk (date: 2021-07-24)
- audio-two.njk (date: 2021-07-24)
- audio-three.njk (date: 2021-07-22)
- audio-four.njk (2021-07-20)
(audio-zero.njk, the last one added is missing)

I have now updated my repo with a fifth post in each directory, Sights and Sounds, in order to reproduce this issue: https://github.com/rocc-o/raw-test-git

**Comment by pdehaan** [comment]
As close as I can figure, the `collections.sights` and `collections.sounds` are already sorted by date (descending). So you want the first 4 [newest] items, not the last 4 [oldest] items. I think you just need to change the `head(-4)` to `head(4)` (for sights and sounds) and that should work.

```njk
{% set postListItems = collections.sights | head(4) %}
```

> ### Latest articles in Sights
>
> 23 September, 2021
> **Video Test Zero**
> Session, 2020
>
> 10 July, 2021
> **Video Test Four**
> Promo, 2020
>
> 9 July, 2021
> **Video Test Two**
> Ident, 2021
>
> 9 July, 2021
> **Video Test Three**
> Docu, 2020

**Comment by rocc-o** [comment]
Yes Peter, now it works! Thank you so much!
