### ISSUE TITLE
Tag archive generates same page for every tag

### ISSUE THREAD

**Issue by freshyill** [11ty/eleventy#1997]
I'm pulling my hair out trying to find out what I could possibly be doing wrong. I had nice, working tag archives for a while, but now something is wrong. Even using the simplest possible example, from the ["zero-maintenance tag page" quick tip](https://www.11ty.dev/docs/quicktips/tag-pages/), I'm getting this issue:

1…  Every tag page is the same: The content that appears in the "birds" archive is identical to the "frogs" archive

2… The tag pages are _wrong_. Even though pages are generated at `/tags/frogs/index.html` and `/tags/birds/index.html`, it is not the correct content for either of them. 

Every page is just a repeat of the page for the first collection Eleventy encounters. With the most basic example, I get the content for the `all` collection. If I filter out `all`, I get `note`. If I filter `note`, I get whatever comes next, and so on. I'm logging the tag on the page, so the pattern is obvious.

I must be breaking something outside of this very simple template, but I have no idea what it can be. Is there a common mistake I might be making?

```njk
---
layout: base
pagination:
  data: collections
  size: 1
  alias: tag
  filter:
    - all
permalink: /tags/{{ tag | slug }}/
---
{% block content %}

  <h1>{{ tag }}</h1>

  {{ tag | log  }} {# Each collection appears in the log as expected, but every page is the first one repeated for the first collection. #}

  {% set taglist = collections[ tag ] %}

  {% for post in taglist | reverse %}
    <li><a href="{{ post.url | url }}">{{ post.data.title }}</a></li>
  {% endfor %}

{% endblock %} 
```

**Comment by pdehaan** [comment]
Do you have a public repo somewhere I can clone to take a look?

**Comment by freshyill** [comment]
Not currently, but I can work on putting one together.

**Comment by freshyill** [comment]
OK, while I don't understand the problem, I've identified what's causing it for me. I'm using the [eleventy-load plugin](https://github.com/gregives/eleventy-load). 

The issue appears immediately when I add the plugin to my .eleventy.js. Even this empty rule set triggers it:

```js
  config.addPlugin(require("eleventy-load"), {
    rules: []
  });
```

This is a bummer because the plugin seems incredibly helpful. I'll file an issue for the plugin.
