### ISSUE TITLE
Unable to override Liquid include arguments locally after upgrading to v1.0.0-beta.1

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [11ty/eleventy#2000]
**Describe the bug**

On beta 1 (which appears as canary 44?), one of my includes is breaking because I'm doing this:

```liquid
{%- assign arg = '12' | append: arg -%}
```

Somewhere else:

```liquid
{% include theFile.html arg: '34' %}
```

Expected result: `arg` is now `1234` locally, within the context of the include file.

Here's the line: https://github.com/AleksandrHovhannisyan/aleksandrhovhannisyan.com/blob/master/src/_includes/img.html#L2

Unfortunately, while this works on 0.12.1, it does not work in beta 1. I logged the value of the overridden variable before and after that line, and it remains unchanged. 

**To Reproduce**

1. Install beta 1.
2. Use Liquid.
3. Create an include file with a single argument.
3. Use the include and provide an argument.
4. Attempt to reassign the argument locally within the include.
5. Log its value before and after.
6. Observe that it's the same value.

**Expected behavior**
It's weird that this changed, so I'm wondering if it's something on Liquid's end that changed to disallow this kind of overriding. If I rename the local variable so that it doesn't shadow the include's argument, then I don't get the error anymore.

**Environment:**

- Eleventy: 1.0.0-canary.44 (attempted install of beta 1 is showing as this version for some reason)
- Liquidjs: 9.28.0

**Additional context**

I'm using a custom Liquid config as follows:

```js
const { Liquid } = require('liquidjs');
eleventyConfig.setLibrary("liquid", new Liquid({
  extname: '.liquid',
  dynamicPartials: false,
  root: ['src/_includes'],
}));
```

**Comment by zachleat** [comment]
You should be able to use the installation instructions on https://www.11ty.dev/blog/eleventy-v1-beta/

**Comment by zachleat** [comment]
I spent a little time looking at this and I think it needs to be filed upstream at https://github.com/harttle/liquidjs

Good needs is that repo is well maintained!

I would note that this exhibits the same issue (logging `34` twice):

```
{{ arg | log }}
{%- assign arg = 12 -%}
{{ arg | log }}
```

**Comment by AleksandrHovhannisyan** [comment]
Oh, that's unfortunate

I don't want to bug the owner of the repo, so I'm waiting to hear back on the status. I fixed this issue but broke other tests 😅

**Comment by AleksandrHovhannisyan** [comment]
I believe this is resolved now thanks to #2071. Going to close, but feel free to reopen!

**Comment by AleksandrHovhannisyan** [comment]
Worth noting that the fix was only for `{% render %}`, not `{% include %}`, which is deprecated. So maybe it's not fixed? 🤷 

https://github.com/harttle/liquidjs/releases/tag/v9.28.4

**Comment by AleksandrHovhannisyan** [comment]
Hmm, this is still technically a problem on beta 5; the solution is to use `{% render %}` instead of `{% include %}` according to the PR that got merged.
