### ISSUE TITLE
ndjson output is not including a newline

### ISSUE THREAD

**Issue by cfjedimaster** [11ty/eleventy#2006]
**Describe the bug**
Using `--to=ndjson` and I'm not seeing a newline in the result.

Here's a sample from a site with two simple pages:

```ndjson
{"url":false,"inputPath":"./foo.liquid","outputPath":false,"content":"\ni wont save"}{"url":"/","inputPath":"./index.liquid","outputPath":"_site/index.html","content":"Hello World: 2021-10-07 09:27"}
```

**Expected behavior**
A line break between each item,

**Environment:**

- OS and Version: WSL
- Eleventy Version [via `eleventy --version` or `npx @11ty/eleventy --version`] beta

**Comment by zachleat** [comment]
Shipping with 1.0.0-beta.3
