### ISSUE TITLE
Collection loops are incomplete in first-request and truly-dynamic serverless pages

### ISSUE THREAD

**Issue by kkgthb** [11ty/eleventy#2013]
See https://github.com/kkgthb/web-site-11ty-09-serverless

Ideally, the sitemap in the footer of every page would list all pages that have a "pages" tag assigned to them, which would be:

1. https://11ty-serverless-hopefully.netlify.app _(build-time-render)_
2. https://11ty-serverless-hopefully.netlify.app/slessposter/ _(first-visit-render; forgive the weird name; has to do with the project I was starting to build)_
3. https://11ty-serverless-hopefully.netlify.app/alwaysrenderthis/ _(always-rerender)_

In reality, the build-time render is aware of all 3 pages and lists a full sitemap, but #2 and #3 only list themselves in their footer.

It might be useful to make this more prominent in notes about what happens when a person chooses to render URLs with 11ty serverless.

**Comment by zachleat** [comment]
Stale per project slipstream changes in #3074.
