### ISSUE TITLE
Can't get Liquid filter to return async function.

### ISSUE THREAD

**Issue by thisanimus** [11ty/eleventy#2014]
**Describe the bug**
Can't figure out how to add a liquid filter that uses an async function.

**To Reproduce**
in .eleventy.js an async shortcode like this works:
```js
module.exports = function (eleventyConfig) {
  eleventyConfig.addLiquidShortcode('exif', getExif);
}
async function getExif(file) {
	let metadata = await exifr.parse('./assets/img/' + file);
	return metadata.Make;
}
```
```
{% exif image %}
```

But eventually I'd like to grab the whole object, not a single value.  So I tried changing it to a filter: 
```js
module.exports = function (eleventyConfig) {
  eleventyConfig.addLiquidFilter('exif', getExif);
}
async function getExif(file) {
	let metadata = await exifr.parse('./assets/img/' + file);
	return metadata.Make;
}
```
```
{% assign metadata = image | exif %}
{{ metadata }}
```
This always gives me an empty object.

If I change the function a a synchronous function, I can pass data to the template without any issues.

**Expected behavior**
I would expect liquid filters to also be able to call async functions.  Am I missing something, or is this just not possible?

**Comment by zachleat** [comment]
Thanks y’all!
