### ISSUE TITLE
Eleventy-Serverless and Content Management System (NetlifyCMS) Preview Example

### ISSUE THREAD

**Issue by stevenmilstein** [11ty/eleventy#2019]
The Serverless documentation [page](https://www.11ty.dev/docs/plugins/serverless/) mentions:
> Server side rendering for fully dynamic pages, e.g. content preview in your Content Management System

and in [A First Look at Eleventy Serverless, with Zach Leatherman | Some Antics](https://someantics.dev/first-look-eleventy-serverless/) @zachleat mentions a Sanity CMS implementation.

It would be very helpful if there was an example of how to implement Eleventy-Serverless in [NetlifyCMS](https://www.netlifycms.org/) so shortcodes could be rendered in the Preview Pane.

I raised the [question on Discord](https://discord.com/channels/741017160297611315/741017160297611319/896054755653210183) but haven't received any traction :-(

Any insight or links would be greatly appreciated!

**Comment by zachleat** [comment]
I think you’ll want to attend the Eleventy Meetup in 2 days!

https://11tymeetup.dev/events/ep-4-11ty-s-data-cascade-and-instant-preview-with-11ty-serverless/

> One of the challenges with static site generators has been previewing changes before they go live. Especially when they grow large and you need to rebuild the whole site on a staging branch. Nobody got time for that! With 11ty Serverless you can build a preview of a page on-demand in no time. This talk shows how it can be done, and how it can be integrated with Sanity Studio for a smooth editorial workflow.

After that video is up we’ll definitely want to link to it from the serverless docs
