### ISSUE TITLE
Can't create dynamic permalinks using post title and slug/slugify

### ISSUE THREAD

**Issue by antoni-devlin** [11ty/eleventy#2024]
**Describe the bug**
Putting either of these in the front matter of a post.md file:
`permalink: /blog/{{title|slug}}/index.html`
or
`permalink: /blog/{{title|slugify}}/index.html`

or if I try to define a default permalink structure in posts.json by using this:

```json
{
  "layout": "layouts/post.html",
  "permalink: "/blog/{{title|slug}}/index.html"
}
```

I get a url that looks like this on the front end:
`http://localhost:8080/blog/%7B%7Btitle%7Cslug%7D%7D/index.html`

The problems are:
- The url is badly encoded
- The url does not dynamically pull through the post `{{title}}`

**To Reproduce**
As above

**Expected behavior**
I expect the input above to generate a permalink that looks like this:
`http://localhost:8080/blog/slugified-post-title-here/index.html`

**Environment:**

- OS and Version: MacOS Big Sur
- Eleventy Version: 0.12.1

**Additional context**
I'm not sure if this is related, but when I tried testing the `slug` and `slugify` filters in the body of my post.md file (not in the frontmatter, I get the following error:

```bash
Template render error` was thrown:
    Template render error: (./src/posts/yet-another-post.md)
      Error: filter not found: slugify`
```

This is how I display the url on my homepage:

```njk
{% extends "layouts/base.html" %}
{% block content %}
{% for post in collections.blogPosts | reverse %}
<section class="post-teaser">
  <img src="{{ post.data.hero.url }}" alt="{{ post.data.hero.alt }}">
  <a href="{{post.data.permalink}}"><h1>{{post.data.title}}</h1></a>
  {# TODO: Dynamic excerpts #}
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod...</p>
  <p class="date">{{post.date|dateFilter}}</p>
</section>
{% endfor %}
{% endblock %}
```

Any help would be really appreciated!

**Comment by tusamni** [comment]
In your code, did you use quotes around the permalink? Not sure if that's causing the issue, but it could be related:

https://www.11ty.dev/docs/permalinks/#warning-about-yaml-objects

**Comment by pdehaan** [comment]
I wasn't able to reproduce on macOS 11.6 (Big Sur) w/ Eleventy 0.12.1 (see https://github.com/pdehaan/11ty-2024)

If you have a public repo somewhere I can try cloning locally and debugging.
