### ISSUE TITLE
Emulate on-demand builders (first-request render) on local dev

### ISSUE THREAD

**Issue by stevenmilstein** [11ty/eleventy#2025]
**First, wonderful feature!!!**

**Describe the bug**  
[Serverless—Eleventy, a simpler static site generator](https://www.11ty.dev/docs/plugins/serverless/) lists [11ty/demo-eleventy-serverless: Run Eleventy in a serverless function](https://www.11ty.dev/docs/plugins/serverless/) as one of the Serverless examples with three deployment options:
- [Source code (localhost)](https://github.com/11ty/demo-eleventy-serverless)
- [Deploy to Netlify](https://app.netlify.com/start/deploy?repository=https://github.com/11ty/demo-eleventy-serverless)
- [Try on StackBlitz](https://stackblitz.com/github/11ty/demo-eleventy-serverless)

**Problem**
localhost and Stackblitz deployments do not behave as expected, as on Netlify:

**Netlify**
- Clicking on the _Build Time_ link does not render new dates
- Clicking on the _first request only_ link renders new dates only once
- Clicking on _every request_ renders new dates on every click

**localhost and StackBlitz**
Both exhibit the same problem for the serverless routes: 
- Clicking on _first request only_and _every request will **always** update ```new Date()``` and **never** update ```page Data.date```. Check the logs to see both serverless routes execute on every click.

![2021-10-14_16-27-13 (1)](https://user-images.githubusercontent.com/66161/137390560-02e0a979-4798-4dbd-9ec4-ab5e04d00150.png)

**To Reproduce**
1. Go to https://www.11ty.dev/docs/plugins/serverless/
2. Under ![](https://hackmd.io/_uploads/H1e3gGIHt.png)

1. Deploy each of the options 

**Environment:**

- OS and Version: Mac 10.13.6 (17G14042)
- Eleventy Version 1.0.0-canary.41 (as in repository), updated localhost to 1.0.0-canary.44 and 1.0.0-beta.2.

**Additional context**
On localhost, I verified:

_./netlifyfunctions/dynamic/index.js_
```
// Choose one:

// Netlify Function (runs every time)
exports.handler = handler;

// Netlify On-demand Builder (runs one request)
// const { builder } = require("@netlify/functions");
// exports.handler = builder(handler);
```

_./netlifyfunctions/serverles/index.js_
```

// Choose one:

// Netlify Function (runs every time)
// exports.handler = handler;

// Netlify On-demand Builder (runs one request)
const { builder } = require("@netlify/functions");
exports.handler = builder(handler);
```

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!
