### ISSUE TITLE
Docs for custom template extensions

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#2036]
Paired with https://github.com/11ty/eleventy/issues/117

**Comment by zachleat** [comment]
Awesome help here at https://github.com/11ty/11ty-website/pull/1240/files

**Comment by zachleat** [comment]
@j-f1 I do want to mention that your PR was extremely valuable in establishing a good baseline list of features that needed to be included. If you would like to contribute, I think it’d be super valuable if you’d read through the final version and offer feedback if you have any! https://github.com/11ty/11ty-website/blob/master/src/docs/languages/custom.md

**Comment by zachleat** [comment]
Live version is available https://www.11ty.dev/docs/languages/custom/

**Comment by j-f1** [comment]
I’d be happy to! Opened up https://github.com/11ty/11ty-website/pull/1267 with some questions, comments, and suggestions
