### ISSUE TITLE
Two posts, each one in a different collection, but with the same tag, are both outputted in both collections

### ISSUE THREAD

**Issue by rocc-o** [11ty/eleventy#2048]
I have two separate collections: /sounds and /sights 
and in each directory the tags output like this:
/sights/tags/(all tags for sights);
/sounds/tags/(all tags for sounds).

But when I have two posts, one in /sounds and one in /sights, both with the same tag, the posts are repeated in both directories.

Posts:

/sights/video-one.njk (tag: jazz-funk)
/sounds/audio-one.njk (tag: jazz-funk)

Outputs:

/sights/tags/jazz-funk/
 - audio-one.html
 - video-one.html
(but it should be only video-one.html)
 
/sounds/tags/jazz-funk/
 - audio-one.njk
 - video-one.njk
(but it should be only audio-one.html)

Here's my repo which reproduce the problem: https://github.com/rocc-o/raw-test-git

The two posts, each one in a different collection but with the same tag (jazz-funk), are: 
/sights/video-one.njk
/sounds/audio-one.njk

**Comment by pdehaan** [comment]
I get the following error when trying to build your site: 

```
> You’re trying to use a layout that does not exist: _below-layout.njk (undefined)
```

Also, you should add a package.json with your dependencies to the repo. Makes it easier to clone and get started.
