### ISSUE TITLE
Bump liquidjs back to latest stable npm v9 release?

### ISSUE THREAD

**Issue by pdehaan** [11ty/eleventy#2059]
Currently liquidjs is pinned to v9.25.1 in packge.json, per https://github.com/11ty/eleventy/commit/2824db33bab6ef5e8790f2f15a651d331c146f30 (re: https://github.com/harttle/liquidjs/issues/395).

https://github.com/11ty/eleventy/blob/19b4884e83e420a3b42f334aa922140f9cb18353/package.json#L107

According to https://github.com/harttle/liquidjs/issues/395#issuecomment-953075824 this might be                       fixed in 9.28.3. Not sure if we want to pin liquidjs back to "latest".

**Comment by zachleat** [comment]
Yeah—we’re following along locally on this one at https://github.com/11ty/eleventy/issues/1995 !
