### ISSUE TITLE
Add support for permalink:"false" to convert from String to Boolean

### ISSUE THREAD

**Issue by pdehaan** [11ty/eleventy#2079]
**Is your feature request related to a problem? Please describe.**
https://github.com/11ty/eleventy/issues/1185#issuecomment-629690050
> Make a separate `notes-empty.liquid` template that uses a `permalink: "{% if collections.notes.length %}/notes/{% else %}false{% endif %}"` though I wonder if we handle `"false"` the string versus `false` the boolean there correctly, hmm.

Doesn't look like we do. I was playing w/ a similar solution in https://github.com/11ty/eleventy/discussions/2078#discussioncomment-1603244 and the `permalink: "false"` was creating a `_site/false` file, so I had to revert to using JavaScript frontmatter and `eleventyComputed` to write strings-vs-booleans.

**Describe the solution you'd like**
Add a check somewhere if the `permalink` is `"false"` string, and cast it to a `false` Boolean.

**Describe alternatives you've considered**
```njk
---js
{
  "//": "/cats.pagination.empty.njk",
  title: "No cats found!",
  eleventyComputed: {
    permalink(data) {
      return (data.cats.length === 0) ? "/cats/" : false;
    }
  }
}
---

<h1>{{ title }}</h1>
```

**Additional context**

**Comment by zachleat** [comment]
Hmm, this is one of those YAML things I don’t think we should override. YAML is kind of unpredictable as is.

I went down a big rabbit hole thinking about this.

https://twitter.com/zachleat/status/1457740284599623684

Basically, we’d be re-enabling a subset of the dreaded YAML 1.1 syntax when we’re very lucky to be on 1.2 on all versions.

https://twitter.com/zachleat/status/1457745602108923906

We _could_ show a warning if we find `"false"` (the string) but that should be a valid output filename. Note (just for completeness) that `permalink: false` works as expected.
