### ISSUE TITLE
Improve Serverless Error Messaging

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#2083]
Not quite good enough, here!

https://contrast-11ties.netlify.app/contrast/?foreground=%23ffffff&background=NOVALUE

```
{
  "error": "Couldn’t find any generated output from Eleventy (URL path parameters: {})."
}
```

via https://twitter.com/m_andrasch/status/1459074004707426308

**Comment by zachleat** [comment]
For future me: we should solve this in a better way upstream in the toJSON (and related) calls to show error information?

Things to think about:
* `toJSON` returns an array at the top level. I wish it used `{ results: [] }` instead which would allow for `{ error: {} }`—we may need a better way around this.
* We may need to be careful about being _too_ open about error messaging in serverless mode, which may have implications if we console.log the full error stack to the end user.

**Comment by vnourdin** [comment]
Hi, is there any workaround to send custom errors **from rendering** to final user ?

Currently, I raise an error from some filters/globals with custom message and statusCode field, but it is caught and replaced by "Having trouble rendering njk template ..." before reaching the `.catch` which follows `elev.getOutput()` and thus my users ever see a 500 without details.

**Comment by zachleat** [comment]
Closing as irrelevant in 3.0.
