### ISSUE TITLE
frontmatter data parsing / not responding on njk file.

### ISSUE THREAD

**Issue by damianroiz** [11ty/eleventy#2086]
**Describe the bug**
when I turn a html into njk and add frontmatter data to it, it is not passing through, and it is parsing on top of the file like with the --- turning into -- - like in this example: 

-- -title : 'example'
layout : 'base.njk'
-- -

This issue is not happening on the _includes files 

**To Reproduce**

**Expected behavior**
I just want the frontmatter data to remain in this format and its information to be passed through the file, (in this example, I want to be able to see the title change browsed)

---
title : 'example'
layout : 'base.njk'
---

**Screenshots**

**Environment:**

- OS and Version: [e.g. Windows/Mac/Linux]
- Eleventy Version [via `eleventy --version` or `npx @11ty/eleventy --version`]

**Additional context**

**Comment by pdehaan** [comment]
@damianroiz Do you have a public repo or something where this is happening?

Only thing I can think of is this note in the [11ty Nunjucks docs](https://www.11ty.dev/docs/languages/nunjucks/#supported-features):

> _`{% include 'included.njk' %}` looks in `_includes/included.njk`. Filenames must be in quotes. Does not process front matter in the include file._

**Comment by zachleat** [comment]
The other thing I would mention here is that you cannot use front matter inside of includes?

I don’t think this test case has enough info to reproduce—sorry!

**Comment by zachleat** [comment]
Please attach a test case and we can revisit!

**Comment by damianroiz** [comment]
Hello, 

Thank you for your reponse, you can check [this repo here](https://github.com/damianroiz/11ty-blog/blob/main/src/index.njk) with one file in which the frontmatter data is parsed: 

It seems I have some auto-formater like Prettier could be causing this....

**Comment by pdehaan** [comment]
Yeah, I see it in the https://github.com/damianroiz/11ty-blog/blob/86fb59084c401b7a8bbb06556c5703f58a2385bf/src/_includes/article.njk#L1-L2 layout too.

If you manually fix it and save your files, does it auto reformat again? I think you're right and it could be some VS Code setting.

**Comment by damianroiz** [comment]
@pdehaan I have just found the issue [on a similar post in SoF](https://stackoverflow.com/a/45991715/14580447), I followed this exact answer and the parsing issue seems to have resolved. Thanks for following up!
