### ISSUE TITLE
Liquid include path as variable

### ISSUE THREAD

**Issue by jchck** [11ty/eleventy#209]
Hi - 
Fantastic project! I've been using Eleventy for a few months now and reciently ran into something that doesn't seem quite right. I'm using Liquid and am attempting to create include path's dynamically by:

```
# index.liquid

---
namespace: project_name
---
{% include 'header' %}
```

```
# header.liquid

{% capture path %}
  {{namespace}}/logo-header
{% endcapture %}
{% include {{path}} %}
```

The `path` var inside the include throws a render error: `Failed to lookup: project_name/logo-header.liquid` yet that file exists.

Any guidance would be greatly appeaciated!

**Comment by jchck** [comment]
Thanks, @zachleat 
I have `dynamicPartials: true` in my config yet `{% include path %}` and `{% include {{path}} %}` are both throwing the same error as above.

**Comment by zachleat** [comment]
Definitely stick with `dynamicPartials: true` and `{% include path %}` but I’m guessing that your includes folder probably isn’t where you expect.

Have you reviewed https://www.11ty.io/docs/config/#directory-for-includes ?

If your input directory is `.` then it will expect your includes folder (by default) to be in `./_includes/` which means that it’s looking for your file in `./_includes/project_name/logo-header.liquid`

Does that make sense?

You can change these directories in your config file.

**Comment by zachleat** [comment]
Please reopen if you have additional questions!

**Comment by jeremenichelli** [comment]
Hi @zachleat, I've been playing around with eleventy and I'm actually considering it for my personal site. First of all, thanks for all your work on this 💟 

I'm aving an issue related to this (sorry if it's a liquidjs thing and not an eleventy one), my case is that I'm dynamically including a file but leventy takes its literal name instead.

The file containing the include looks like this:
```liquid
<head>
  {% capture stylesPath %}
    styles/{{layout}}.liquid
  {% endcapture %}
  <style>{% include stylesPath %}</style>
  <link href="https://fonts.googleapis.com/css?family=Fira+Sans:400,400i,700" rel="stylesheet">
</head>
<p>stylesPath</p>
```

I have `dynamicPartials: true` set in the config and the file exists and is in the right folder (`_includes/styles/home.liquid`), but I get an error that says:

```
> ENOENT: Failed to lookup stylesPath.liquid in: _includes (Error):
    Error: ENOENT: Failed to lookup stylesPath.liquid in: _includes
```

Looks like eleventy doesn't understand that the name passed is a variable holding the actual path, am I missing something?
