### ISSUE TITLE
Add layout example to documentation.

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#21]
Couple of ways to do layouts. You can use template engine specific stuff (blocks in nunjucks, for example) or eleventy provides a template agnostic way:

## File: `_includes/mylayout.njk`
```
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>{{title}}</title>
	</head>
	<body>
		{{_layoutContent | safe}}
	</body>
</html>
```

## File: `template.njk`

```
---
layout: mylayout
title: This will go into the title
---
Template Content
```

**Comment by nsteiner** [comment]
Ah, I was just wondering about this. The above works great for me - I think users will want to know the equivalent syntax for other template types (liquid, html, etc). Does this work with all types?

**Comment by zachleat** [comment]
Yep, layouts can be of any type! As long as you reference the `_layoutContent` variable.

## Another example, using EJS:
```
<div id="layout">
  <%- _layoutContent %>
</div>
```

Also worth noting that you can chain layouts too. Layout files can reference their own `layout`.

**Comment by zachleat** [comment]
https://github.com/11ty/eleventy/blob/master/docs/layouts.md
