### ISSUE TITLE
Nunjucks: Asynchronous Shortcodes inside of `{% set %}`

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#2108]
Failing test case:

```
{% set myVar %}
{% asyncShortcode %}
test content
{% endasyncShortcode %}
{% endset %}
```

Discovered via https://github.com/11ty/eleventy/issues/2100#issuecomment-974385976

Local PR that has some progress on a similar issue: https://github.com/11ty/eleventy/pull/1749

Nunjucks Related Issues:
https://github.com/mozilla/nunjucks/issues/815
https://github.com/mozilla/nunjucks/pull/1362
https://github.com/mozilla/nunjucks/issues/1363

I tested https://github.com/mozilla/nunjucks/pull/1357 locally and it did not resolve the issue.

## Related: macros

Note that the `macro` docs warn about using async stuff: https://mozilla.github.io/nunjucks/templating.html#macro 

> Important note: If you are using the asynchronous API, please be aware that you cannot do anything asynchronous inside macros. This is because macros are called like normal functions. In the future we may have a way to call a function asynchronously. If you do this now, the behavior is undefined.

This repo has a `setAsync` custom tag that I looked into but I don’t think it solved the issue: https://github.com/namshi/nunjucks-setasync

**Comment by CodeFoodPixels** [comment]
Do you need any more from my PR for this? Happy to do more work on it

**Comment by zachleat** [comment]
I merged it! It is amazing, thank you @CodeFoodPixels!

**Comment by zachleat** [comment]
`1.0.0-beta.9` will have a new `setAsync` Nunjucks paired shortcode.

The first argument is a string.

```
{% setAsync "liquidOutput" %}
{% renderTemplate "md" %}
# Title
{% endrenderTemplate %}
{% endsetAsync %}
```
