### ISSUE TITLE
Dynamically including files w/ Nunjucks

### ISSUE THREAD

**Issue by pdehaan** [11ty/eleventy#2119]
_Originally posted by @antiprism in https://github.com/11ty/eleventy/issues/148#issuecomment-976289813_

Hi

I am new to eleventy.

I am building pages from fragments of content, some of which are markdown (and using the markdown shortcode pair mentioned earlier in this issue), and using a nunjucks 'include'. I want sections in the layout to be conditional depending on whether a content fragment file exists or not.

To do this I wrote a shortcode to turn a src-relative path into an _include-relative path, and return an empty string if the file did not exist.
```
eleventyConfig.addShortcode("file_exists", function(fname) {
    full_fname = 'src/' + fname;
    fail = '';
    if (!fs.existsSync(full_fname) || !fs.statSync(full_fname).isFile())
       return fail;

    rel_fname = '../../' + fname;
    return rel_fname;
  });
```

In the template I can then test if the file exists and I have the correct path to include it (for a page called pagename.md, there are fragments called pagename_help.md, pagename_examples.md, etc)
```
  {% set src_inc_start = "docs/prog_sects/" + page.fileSlug %}
  <article class="programhelp">

  {% set inc_fname %}{% file_exists src_inc_start + "_help.md" %}{% endset %}
  {% if inc_fname %}
<h2>Help</h2>
     <div class="proghelp">
       <pre class="proghelp">
{% include inc_fname %}
       </pre>
     </div>
  {% endif %}
```

Is this a reasonable approach (I am not sure if the relative paths will always work), or is there already a facility in eleventy to acheive this?

Adrian.

**Comment by pdehaan** [comment]
@antiprism Since you said you're using Nunjucks, one interesting thing from their docs is the "ignore missing" option for the `{% include %}` tag: https://mozilla.github.io/nunjucks/templating.html#include
>
> `include` actually accepts any arbitrary expression, so you can pass anything into it, as long as the expression evaluates to a string or a compiled Template object: `{% include name + ".html" %}`.
>
> It might be useful to not throw an error if a template does not exist. Use the `ignore missing` option to suppress such errors.
> ```njk
> {% include "missing.html" ignore missing %}
> ```

That said, here's another possible solution:

```js
// .eleventy.js
module.exports = (eleventyConfig) => {
  return {
    dir: {
      input: "src",
      output: "www",
    },
    markdownTemplateEngine: "njk",
  };
};
```

### src/pagename.md

We define an array of .md "partials" to include in our template. So it will convert `page.fileSlug + "_" + section + ".md"` into `pagename_examples.md` and check for that in the `src/_includes/` folder. I have an `_includes/pagename_help.md` and `_includes/pagename_examples.md` file, but no `_includes/something_bad.md` but it will ignore that missing file instead of throwing an error (due to `ignore missing` on the `{% include %}` tag.

```njk
---
title: things
sections:
  - help
  - examples
  - something_bad
---

# {{ page.fileSlug }}

{% for section in sections %}
  {% set filename = page.fileSlug + "_" + section + ".md" %}
  <section data-id="{{ filename }}">
  
  {% include filename ignore missing %}
  
  </section>
{% endfor %}
```

### src/_includes/pagename_examples.md

```md
## EXAMPLES
```

### OUTPUT

```html
<h1>pagename</h1>

<section data-id="pagename_help.md">
  <h2>HELP ME!!</h2>
</section>
<section data-id="pagename_examples.md">
  <h2>EXAMPLES</h2>
</section>
<section data-id="pagename_something_bad.md">
</section>
```

---

Attempt 2: Since this left me with a handful of files in the root of my `_includes/` folder, I tried putting the include partials in a subfolder based on the `page.fileSlug`. I think the only difference here was changing an underscore to a backslash in the `section_filename` variable.

### src/about.md
```njk
---
title: About Me
sections:
  - contact
  - map
---

# {{ page.fileSlug }}

{% for section in sections %}
  {% set section_filename = page.fileSlug + "/" + section + ".md" %}
  <section data-id="{{ section_filename }}">
  
  {% include section_filename ignore missing %}
  
  </section>
{% endfor %}
```

### src/_includes/about/contact.md
```md
## I'm contact info
```

### src/_includes/about/map.md
```md
## I'm a map!
```

### OUTPUT

```html
<h1>about</h1>

<section data-id="about/contact.md">
  <h2>I'm contact info</h2>
</section>
<section data-id="about/map.md">
  <h2>I'm a map!</h2>
</section>
```

**Comment by antiprism** [comment]
Thank you for your reply, 

My layout includes a number of sections, and within those sections is extra formatting as well as the included content. I would like to exclude the whole section if the content file does not exist. If I have understood your suggestion, the whole section content would need to be in the included file in order for the section to be skipped (is that right?)

My whole (test) layout template looks like this, with some sections including the content as preformatted text and others rendering it as markdown.

```
{% extends "layouts/default.html" %}

{% block content %}
{{ content | safe }}

<h1>{{ title }}</h1>
<div class="wrapper">
  {% set src_inc_start = "docs/prog_sects/" + page.fileSlug %}
  <article class="programhelp">

  {% set inc_fname %}{% file_exists src_inc_start + "_help.md" %}{% endset %}
  {% if inc_fname %}
<h2>Help</h2>
     <div class="proghelp">
       <pre class="proghelp">
{% include inc_fname %}
       </pre>
     </div>
  {% endif %}

  {% set inc_fname %}{% file_exists src_inc_start + "_examples.md" %}{% endset %}
  {% if inc_fname %}
<h2>Examples</h2>
     {% markdown %}
{% include inc_fname %}
     {% endmarkdown %}
  {% endif %}

  {% set inc_fname %}{% file_exists src_inc_start + "_notes.md" %}{% endset %}
  {% if inc_fname %}
<h2>Notes</h2>
     {% markdown %}
{% include inc_fname %}
     {% endmarkdown %}
  {% endif %}

  {% set inc_fname %}{% file_exists src_inc_start + "_exthelp.md" %}{% endset %}
  {% if inc_fname %}
<h2>Extended Help</h2>
     <div class="proghelp">
       <pre class="proghelp">
{% include inc_fname %}
       </pre>
     </div>
  {% endif %}

  </article>
</div>
{% endblock %}
```

This is currently working for me, at least with the directories/layout I have, but the relative paths seem fragile and the 'file_exists' shortcode has to be nested on the same line as the 'set', so I am sure this can be improved on, or perhaps replaced by something better.

Adrian.

**Comment by pdehaan** [comment]
@antiprism OK, I think I came up w/ 3 options of varying awkwardness. And not sure if any are better than your solution.

## OPTION 1
Use a custom filter instead of a shortcode.
```njk
  {% set inc_fname = "help.md" | partial_exists %}
  {% if inc_fname %}
    <h2>Help</h2>
    <div class="proghelp">
      <pre class="proghelp">{% include inc_fname %}</pre>
    </div>
  {% endif %}
```

Where my custom `partial_exists` filter (in my .eleventy.js) looks like this:
```js
  eleventyConfig.addFilter("partial_exists", function (suffix="", slug=this.ctx.page.fileSlug) {
    const fname = path.join("src/_includes/docs/prog_sects", `${slug}_${suffix}`);
    if (!fs.existsSync(fname) || !fs.statSync(fname).isFile()) {
      return "";
    }
    return fname;
  });
```
I had to tweak the file paths since I'm doing this in templates, not nested layouts.

## OPTION 2
Includes of includes.
```njk
---
# /src/input.njk
title: input
---

{%- set prefix = "docs/prog_sects/" + page.fileSlug -%}

{% include prefix + "_help.njk" ignore missing %}
{% include prefix + "_examples.njk" ignore missing %}
{% include prefix + "_notes.njk" ignore missing %}
{% include prefix + "_exthelp.njk" ignore missing %}
```

So this will try including `./src/_includes/input_help.njk`, if it exists, and silently fails if not.
And my ./src/_includes/input_help.njk looks like this:
```njk
<h2>Help</h2>
<div class="proghelp">
  <pre class="proghelp">{% include prefix + "/help.md" %}</pre>
</div>
```
So all my custom layout code is in the include file, which includes a partial, in this case `./src/_includes/docs/prog_sects/input/help.md`.

This is similar to my original concept, but now has nested includes for the extra formatting, and ignores the partial if it isn't found for that `page.fileSlug`. 🤷 

## OPTION 3
Nunjucks macros!
```njk
{# src/_includes/macros.njk #}
{% macro examples(slug) %}
  {% set inc_fname = "examples.md" | partial_exists(slug) %}
  {% if inc_fname %}
    <h2 data-fileSlug="{{ slug }}">Examples</h2>
    {% markdown %}{% include inc_fname %}{% endmarkdown %}
  {% endif %}
{% endmacro %}

{% macro exthelp(slug) %}
  {% set inc_fname = "exthelp.md" | partial_exists(slug) %}
  {% if inc_fname %}
    <h2>Extended Help</h2>
    <div class="proghelp">
      <pre class="proghelp">{% include inc_fname %}</pre>
    </div>
  {% endif %}
{% endmacro %}

{% macro help(slug) %}
  {%- set inc_fname = "help.md" | partial_exists(slug) %}
  {%- if inc_fname %}
    <h2>Help</h2>
    <div class="proghelp">
      <pre class="proghelp">{% include inc_fname %}</pre>
    </div>
  {%- endif %}
{% endmacro %}

{% macro notes(slug) %}
  {%- set inc_fname = "notes.md" | partial_exists(slug) %}
  {%- if inc_fname %}
    <h2>Notes</h2>
    {% markdown %}{% include inc_fname %}{% endmarkdown %}
  {%- endif %}
{% endmacro %}
```

This is pretty close to option 1, but hides all the logic in a macro file, which we can import into our files.
Here's my ./src/select.njk file:

```njk
---
title: select
---

{%- import "macros.njk" as macros -%}

{{ macros.examples(page.fileSlug) }}
{{ macros.exthelp(page.fileSlug) }}
{{ macros.help(page.fileSlug) }}
{{ macros.notes(page.fileSlug) }}
```

So here we're importing the ./src/_includes/macros.njk into a "macros" namespace and calling `.examples()` macro and passing the current `page.fileSlug` as an argument.

---

Not sure if any option is better than the others. I like option 3 for the simplicity. And option 2 for the "ignore missing", since it requires the fewest filters/shortcodes, but it also requires nested partials.

There's probably other options, these were just three that I was thinking of today. Like I say, not sure if any of them are better than your current solution.

**Comment by antiprism** [comment]
Hi

Thanks for taking the time to create these alternative solutions. I didn't know that filters would take arguments, and that should simplify setting the fragment file path for the include. I might be able to calculate the relative path from the layout template to the root directory using the layout path, which would make the file_exists part more general, but even just passing the layout template path depth as an argument would be an improvement.on hard-coding the "depth" ("../../" ) as I have it now.

Thanks again.

Adrian.

**Comment by pdehaan** [comment]
Yep. Filters can take multiple arguments, but the syntax is slightly different between Nunjucks and LiquidJS (if that's a concern for you).

```js
  eleventyConfig.addFilter("echo", function (value="", count=1) {
    // The `this` data will be different depending on which template engine you use.
    // console.log(value, this);
    return value.repeat(count);
  });
```

### Nunjucks
```njk
{{ "Nunjucks" | echo }}
{{ "Nunjucks" | echo(2) }}
```

#### OUTPUT
```
Nunjucks
NunjucksNunjucks
```

### LiquidJS
```liquid
{{ "LiquidJS" | echo }}
{{ "LiquidJS" | echo: 2 }}
```

So as you can see, our near-useless `echo` filter takes two args: `(value="", count=1)`.
The first argument, `value`, comes from whatever value is before the vertical `|` pipe. Our second+ arguments, `count`, are passed along after the `echo` filter.
In Nunjucks we use `echo(2)` to set the count to 2 and in LiquidJS we use `echo: 2` to set the count to 2.

**Comment by antiprism** [comment]
Thanks for the example. I added the filter
```
  eleventyConfig.addFilter("as_inc_path", function (fname, count=2) {
    full_fname = 'src/' + fname;
    fail = '';
    if (!fs.existsSync(full_fname) || !fs.statSync(full_fname).isFile())
       return '';  // content fragment file not found
    rel_name = '../'.repeat(count) + fname;
    return rel_name;
  });
```
And now I can do the following, with an option to set the layout depth as a parameter
```
{% set inc_fname = (src_inc_start + "_help.md") | as_inc_path %}
{% if inc_fname %}
...
```
Instead of
```
{% set inc_fname %}{% file_exists src_inc_start + "_help.md" %}{% endset %}
{% if inc_fname %}
...
```
Definitely an improvement!

Adrian.

**Comment by pdehaan** [comment]
```js
  eleventyConfig.addFilter("as_inc_path", function (fname, count=2) {
    full_fname = 'src/' + fname;
    fail = '';
    if (!fs.existsSync(full_fname) || !fs.statSync(full_fname).isFile())
       return '';  // content fragment file not found
    rel_name = '../'.repeat(count) + fname;
    return rel_name;
  });
```

Not 100% certain I understand what it's doing.

You're calling it like `(src_inc_start + "_help.md") | as_inc_path` where `src_inc_start` is:
```nunjucks
{% set src_inc_start = "docs/prog_sects/" + page.fileSlug %}
```

So it looks like you're passing "docs/prog_sects/myPageSlug_help.md" to the filter.
Then the filter sets prefixes `full_fname` w/ "src", turning it into "src/docs/prog_sects/myPageSlug_help.md", and checks the file exists. If not, you return an empty string. If the file does exist, you set the `rel_name` variable to "../../docs/prog_sects/myPageSlug_help.md"&hellip;

OK, actually I think that works. I was wondering if you could hardcode the "docs/prog_sects/" into the custom filter instead of passing it each time, although possibly not worth the effort since you'd still need to call it like:
```njk
(page.fileSlug + "_help.md") | as_inc_path
```

I guess I'm just trying to figure out if there was an easier way to avoid needing "../../". But hard to tell without seeing the repo or directory structure (assuming all these files are in the `_includes/` folder or something).

**Comment by antiprism** [comment]
Hi

The content fragment files are in a folder adjacent to the page files, i.e. not under "_include". In order to check if the files exists from the project root I need to prepend the configured input directort (src/), and in order to create a path that works for the include tag I then have to the prepend the path from the configured includes diectory (src/include_) to the project root (giving ../../). E.g. Fragment file `docs/prog_sects/myPageSlug_help.md` is checked for existence as `src/docs/prog_sects/myPageSlug_help.md` and then included as `../../src/docs/prog_sects/myPageSlug_help.md`

Ideally, I would be able to read the values of the paths of the eleventy configuration directories, but I don't think that is possible. I need to generate my pages twice, as standalone documentation and incorporated into a website, and so I am not fullly sure what parameters I will need for the filter yet. However, for the whole project  I think I will only be using the filter in maybe three or four situations, and could always just hardcode the directory details I need in separate filters, to keep things simple.

I am going to look next at each program having its own directory containg the page (index.md) and the fragment files (ignored by permalink: false in a directory data file), as this arrangement will fit better with other content I want to create web pages for.

Anyway, while not perfect, things are working out. Please mark the issue solved!

Thanks for your help.

Adrian.

**Comment by pdehaan** [comment]
Check out https://www.11ty.dev/docs/data-eleventy-supplied/ if you haven’t seen it yet. Might be something useful there too, aside from `page.fileSlug`.

**Comment by antiprism** [comment]
Just a quick follow up. Putting the fragments in a directory with the page as index.md produced a more natural solution, as it meant the content fragments could just have their section name, and the layout could locate the fragments starting from page.url
```
├── docs
│   ├── programs
│   │   ├── antiview
│   │   │   ├── examples.md
│   │   │   ├── help.md
│   │   │   ├── index.md
│   │   │   └── notes.md
│   │   ├── bravais
│   │   │   ├── examples.md
│   │   │   ├── exthelp.md
│   │   │   ├── help.md
│   │   │   ├── index.md
│   │   │   └── notes.md
```
and the new template, with no hardcoded path
```nunjucks
{% extends "layouts/default.html" %}

{% block content %}
{{ content | safe }}

<h1>{{ title }}</h1>
<div class="wrapper">
  <article class="programhelp">

  {% set inc_fname = (page.url + "help.md") | as_inc_path %}
  {% if inc_fname %}
<h2>Help</h2>
     <div class="proghelp">
       <pre class="proghelp">
{% include inc_fname %}
       </pre>
     </div>
  {% endif %}

  {% set inc_fname = (page.url + "examples.md") | as_inc_path %}
  {% if inc_fname %}
<h2>Examples</h2>
     {% markdown %}
{% include inc_fname %}
     {% endmarkdown %}
  {% endif %}

  {% set inc_fname = (page.url + "notes.md") | as_inc_path %}
  {% if inc_fname %}
<h2>Notes</h2>
     {% markdown %}
{% include inc_fname %}
     {% endmarkdown %}
  {% endif %}

  {% set inc_fname = (page.url + "exthelp.md") | as_inc_path %}
  {% if inc_fname %}
<h2>Extended Help</h2>
     <div class="proghelp">
       <pre class="proghelp">
{% include inc_fname %}
       </pre>
     </div>
  {% endif %}

  </article>
</div>

{% endblock %}
```

**Comment by pdehaan** [comment]
Yeah! I like that directory structure!

Here's my local ./src/docs/programs/antiview/index.md file:

```md
{% if "help.md" | file_exists %}
  ## Help
  <div class="proghelp">
    <pre>
      {%- include "./help.md" -%}
    </pre>
  </div>
{% else %}
  <!-- no help file found -->
{% endif %}

{% if "example.md" | file_exists %}
  ## Examples
  {% markdown %}
    {%- include "./example.md" -%}
  {% endmarkdown %}
{% else %}
  <!-- no example file found -->
{% endif %}
```

Bonus: Here's a dump of the `{{ page }}` object in my ./src/docs/programs/antiview/index.md file for context since we'll be using a few of the values below in our filter:

```js
{
  date: 2021-11-25T15:11:08.977Z,
  inputPath: './src/docs/programs/antiview/index.md',
  fileSlug: 'antiview',
  filePathStem: '/docs/programs/antiview/index',
  url: '/docs/prog_sects/antiview/',
  outputPath: 'www/docs/programs/antiview/index.html'
}
```

And my tweaked .eleventy.js filter:

```js
eleventyConfig.addFilter("file_exists", function (partial="", page=this.ctx.page) {
  // ie: "./src/docs/programs/antiview/"
  const srcDir = path.dirname(page.inputPath);
  // ie: "./src/docs/programs/antiview/help.md"
  const srcFile = path.join(".", srcDir, partial);
  if (!fs.existsSync(srcFile) || !fs.statSync(srcFile).isFile()) {
    return false;
  }
  // ie: "./help.md"
  return "./" + partial;
});
```

> NOTE: This works because Nunjucks will have a `this.ctx` object which we can use as a default `page` argument value when using non-arrow functions. 
> If you're using LiquidJS templating, you'd need to explicitly pass the `page` object to the custom filter:
> ```liquid
> {% comment %} LIQUID CODE {% endcomment %}
>
> {% assign help_exists = "help.md" | file_exists: page %}
> {% if help_exists %}
>   ...
>   {%- include ./help.md -%}
> {% endif %}
> ```

So the custom filter takes the directory of the `page.inputPath`, "./src/docs/programs/antiview/", appends the partial filename, "help.md", and then checks if the file exists.
If the include file _doesn't_ exist, we return `false`.
If the include file _does_ exist we return the relative path to the partial, "./help.md", which is comically unused. It's only used in our index.md as a truthy check, we could have returned `true` from the filter too because now with your pretty folder structure you can do a relative include of `{%- include "./help.md" -%}` directly.

:+1: This was a fun problem, thanks for indulging me.
