### ISSUE TITLE
Running Eleventy with DEBUG set breaks when using ES Modules

### ISSUE THREAD

**Issue by j-f1** [11ty/eleventy#2129]
**Describe the bug**
While Eleventy doesn’t support using ES Modules directly (i.e. as a config file or within `_data/`, ref. #836), it’s still possible to use dynamic `import()` syntax in CommonJS modules on recent Node.js versions. This is necessary to use ESM-only packages.

When the `DEBUG` environment variable is set, Eleventy requires [the `time-require` package](https://github.com/jaguard/time-require), which was last updated in 2014. It overrides `Module._load` to calculate timing information. This is called when requiring or importing a CommonJS module. `time-require` assumes that `_load` will be passed a module name and a `parent`. When ESM code tries to import a CommonJS module, `Module._load` is called with `parent` set to `undefined`. This results in a crash.

**To Reproduce**

1. In an Eleventy project, install `camelcase`
2. In your Eleventy config file, call `import("camelcase")`
3. run `DEBUG='Eleventy:Benchmark*' npx @11ty/eleventy`

**Expected behavior**
No error, ideally helpful timing information is displayed for ES modules in addition to CommonJS ones.

**Environment:**

- OS and Version: macOS 11.6 (20G165)
- Eleventy Version 1.0.0-beta.8

**Additional context**
Ideally, either the `time-require` package would be forked, patched, and updated to work better with ES Modules.

As an alternative, it would be great to make the `time-require` import explicitly opt-in, allowing analysis of CJS-only projects without breaking perf debugging for CJS+ESM projects.

**Comment by zachleat** [comment]
Okay resolution if we remove `time-require` entirely? I don’t get a ton of value out of it, personally.

**Comment by zachleat** [comment]
I went ahead and removed it, you can try that out in 1.0.0-canary.48

**Comment by j-f1** [comment]
It looks like that works! Thanks :)

**Comment by zachleat** [comment]
Great!
