### ISSUE TITLE
Expose page data to filters, shortcodes, and transforms

### ISSUE THREAD

**Issue by mahnunchik** [11ty/eleventy#2135]
**Is your feature request related to a problem? Please describe.**

Where is no clear and predictable way to access `page data` inside:

* `filter`
* `shortcode`
* `transform`

It would be really helpful to access `page data` in way `eleventyComputed` already does.

**Describe the solution you'd like**

Provide `page data` or `context` like `this` or one more argument.

```js
// option 1
eleventyConfig.addFilter('i18n', function(value) {
  // this is data
  return translate(value, this.language);
})

// option 2
eleventyConfig.addFilter('i18n', function(value, context) {
  // context is data
  return translate(value, context.language);
})

```

**Additional context**

Many related issues:

* https://github.com/11ty/eleventy/issues/789 - exposes only part of `data.page`
* https://github.com/11ty/eleventy/issues/741 - this normalized only for njk
* https://github.com/11ty/eleventy/discussions/1591
* https://github.com/11ty/11ty-website/pull/220
* https://github.com/11ty/eleventy/issues/1047
* https://github.com/adamduncan/eleventy-plugin-i18n/issues/12
* https://github.com/adamduncan/eleventy-plugin-i18n/blob/master/.eleventy.js#L21 - hack for njk

**Comment by mahnunchik** [comment]
Hack for Liquid:

```js
  eleventyConfig.addFilter('test', function(value) {
    // page data
    const data = this.context.environments;
    return value;
  })
```

**Comment by zachleat** [comment]
These shipped in 2.0 via #1522.

* this.page and this.eleventy are now available on [Shortcodes](https://v2-0-0.11ty.dev/docs/shortcodes/#scoped-data-in-shortcodes), [🆕 Filters](https://v2-0-0.11ty.dev/docs/filters/#scoped-data-in-filters), [🆕 Linters](https://v2-0-0.11ty.dev/docs/config/#linters), and [🆕 Transforms](https://v2-0-0.11ty.dev/docs/config/#transforms)
* [page and content on Collection entries](https://v2-0-0.11ty.dev/docs/collections/#collection-item-data-structure)

**Comment by mahnunchik** [comment]
@zachleat could you please clarify what is wrong on my use case?

```js
// .eleventy.js
module.exports = function(eleventyConfig) {
  eleventyConfig.addFilter("myFilter", function(value) {
    // this.page is undefined
    // this.eleventy is undefined
    return value + 'myFilter';
  });
}
```
Usage inside `eleventyComputed.js`

```
// eleventyComputed.js
module.exports = function() {
  return {
    testFilter() {
      return this.myFilter(this.page.title)
    }
  }
};
```

**Comment by mahnunchik** [comment]
@11ty/eleventy version 2.0.0

**Comment by zachleat** [comment]
@mahnunchik can you file a new issue please? That’s more likely a bug with computed data than related to this issue—thank you!
