### ISSUE TITLE
Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#2139]
Removing the `fs-extra` dependency in 1.x caused this error to crop back up.

`fs-extra` solved this problem for both reads and writes using `graceful-fs` behind the scenes

https://www.npmjs.com/package/graceful-fs

Marginally related (but probably not related?) issue in 0.x: #1980

**Comment by zachleat** [comment]
Shipping with beta 9 and canary 47

**Comment by mirisuzanne** [comment]
I just upgraded to 1.0, and started getting this error. Not sure if there's something I need to do locally to solve this?

**Comment by epelc** [comment]
@zachleat is there something with passthrough files that could cause this? Was trying on 2.0.0 canary 9, canary 12, and also tried on 1.0.1

We are still seeing this on a project with 368 template files(html) and roughly 15,700 images/other passthrough files(16k total).

 - Only happens on windows, not on mac
 - Doesn't happen if we have around 15,300 passthrough files total
