### ISSUE TITLE
Front matter data from a layout specified by `addGlobalData` is ignored

### ISSUE THREAD

**Issue by j-f1** [11ty/eleventy#2145]
**Describe the bug**
Eleventy’s data cascade merges front matter data from the current page’s layout. However, the code only looks at the local data and the page’s front matter for the `layout` key, meaning that a default layout specified as global data is not included here.

https://github.com/11ty/eleventy/blob/36fc4b74e2f17f3a5d229e1851ebdbf4a647383d/src/Template.js#L384-L386

**To Reproduce**

1. Clone this repo: https://github.com/j-f1/eleventy-issue-2145
2. `npm install`
3. `npm eleventy`
4. View the contents of `_site/*.html`. Note that `some_data` is available to both the template and the page in `front-matter-layout.html`, but completely missing from `global-layout.html`.

**Expected behavior**
Both `.html` files show the value “Hello, world!” in the quotes

**Environment:**

- OS and Version: macOS 12.1 (21C52)
- Eleventy Version `1.0.0-canary.48`

**Comment by zachleat** [comment]
Thank you! This will ship with 1.0.1
