### ISSUE TITLE
Open Collective supporter didn't get Eleventy Contributor account signup email

### ISSUE THREAD

**Issue by oisinq** [11ty/eleventy#2149]
**Describe the bug**
Hey, sorry if this is the wrong place for this kind of question. 

I signed up as a [donator](https://opencollective.com/oisinq) to 11ty's [Open Collective](https://opencollective.com/11ty) page. Donators are supposed to get an email letting them create a [Eleventy Contributor account](https://www.11ty.dev/docs/account/).

I signed up two months ago but never received that email, so I can't create a Contributor account. I tried to click the "Forgot password?" prompt on the log in screen but I got the error "User not found" 

**Expected behavior**
Open Collective donators should get an email letting them create an Eleventy Contributor account.

**Screenshots**
<img width="815" alt="Screenshot 2021-12-23 at 23 54 49" src="https://user-images.githubusercontent.com/5693967/147300481-795c38b3-5368-4e63-9780-c9b481cde1d8.png">

**Environment:**

My email address is hosted on Fastmail, in case that's relevant :)

**Comment by oisinq** [comment]
Just got an email from `noreply@netlify.com` with my signup details so looks like this is working now :)

**Comment by zachleat** [comment]
Sorry about that! This process has one manual step that I haven't automated yet 😭
