### ISSUE TITLE
Contrary to the docs collection.name.reverse() (the reverse bit) doesn't work when used inside markdown

### ISSUE THREAD

**Issue by adamsilver** [11ty/eleventy#215]
I have an `articles.md` file with this inside:

```
{%- for article in collections.article.reverse() -%}
    <div>
       <a href="{{ article.url}}">{{ article.data.title }}</a>
       <time date-time="{{article.date}}">{{article.date | date}}</time>
    </div>
{%- endfor -%}
```

The `.reverse()` call has no effect when inside a markdown file but works just fine inside a Nunjucks file.

**Comment by zachleat** [comment]
Probably related to this https://twitter.com/JeffChausse/status/1017865926476271618

Are you using nunjucks as your default markdown template language? The eleventy default is liquid, for the record.

**Comment by adamsilver** [comment]
@zachleat I am using Nunjucks as the default markdown template language:

```markdownTemplateEngine: 'njk',```

**Comment by zachleat** [comment]
Just tested this and you’re right. The documentation should use `{%- for article in collections.article | reverse -%}` instead. I changed the docs to use the correct syntax.

Per your original comment, in my tests it didn’t work in either a .md file preprocessed with nunjucks or a .njk file.

**Comment by adamsilver** [comment]
Brill, thanks.

**Comment by zachleat** [comment]
Just a future note for anyone that lands here from search—if you’re using `Array` `reverse()` inside of a custom collection see #352
