### ISSUE TITLE
Template included inside switch case statement not working (Nunjucks)

### ISSUE THREAD

**Issue by architchandra** [11ty/eleventy#2151]
Sorry if this is not relevant for Eleventy. I'm not sure if the issue I am facing is related to Nunjucks or Eleventy (or more likely, my own code), so I'm posting in [both](https://github.com/mozilla/nunjucks/issues/1387) places.

I'm using Nunjucks in Eleventy to build a site. 

I've created component templates for various _editor_ blocks to render a blog page, eg. `components/heading.njk`, `components/image.njk`, `components/text`, etc.

I'm trying to add all these to another component called Body (`components/body.njk`), which in turn _includes_ these components (after passing in some inputs). In the blog template, I plan to just include the _body_ component and pass in the blocks corresponding to the content types added by the user (text, image, heading, etc) rather than including these components directly. (This is based on Forestry's [Blocks](https://forestry.io/docs/settings/fields/blocks/) field's templating requirements.)

However, I'm facing an issue where an included template including another template is not working in conjugation with the `switch` statement. I'm getting a `SyntaxError: Illegal break statement` error in Eleventy in the console.

Here are the relevant contents of the templates in case the description wasn't clear.

```
{# blog.njk #}

{% set bodyParams = {
    blocks: body
} %}
{% include 'components/body.njk' %}
```

```
{# components/body.njk #}

{# Parameters #}
{% set bodyBlocksList = bodyParams.blocks if bodyParams.blocks else [] %}
{% set bodyClass = bodyParams.class if bodyParams.class else 'prose mx-auto' %}

{# Output #}
<div class="{{ bodyClass }}">
  {% if bodyBlocksList|length %}
    {% for block in bodyBlocksList %}
      {% set blockType = block.template %}
      {% switch blockType %}
        {% case 'heading' %}
          {% include 'components/heading.njk' %}
        {% case 'image' %}
          {% set imageParams = {
            image: block.image,
            altText: block.altText,
            caption: block.caption
          } %}
          {% include 'components/image.njk' %}
      {% endswitch %}
    {% endfor %}
  {% endif %}
</div>
```

```
{# components/image.njk #}

{# Parameters #}
{% set imageAsset = imageParams.image if imageParams.image else '' %}
{% set imageCaption = imageParams.caption if imageParams.caption else '' %}
{% set imageAltText = imageParams.altText if imageParams.altText else '' %}

{# Output #}
<figure>
  <img class="rounded-md" src="{{ imageAsset }}" alt="{{ imageAltText }}" title="{{ imageAltText }}">
  <figcaption class="font-prose">
    {{ imageCaption }}
  </figcaption>
</figure>
```

**Comment by pdehaan** [comment]
@architchandra I think this would be a Nunjucks issue. The code seems to compile fine if I replace the `{% include "components/heading.njk" %}` statements from the `{% switch %}` blocks with debug output.

One possible workaround is just using a bunch of vanilla `{% if %}..{% elif %}..{% endif %}` boilerplate. Not as pretty, but didn't seem to throw any errors for me locally:

```nunjucks
      {% if blockType == "heading" %}
        {% include 'components/heading.njk' %}
      {% elif blockType == "image" %}
        {% set imageParams = {
          image: block.image,
          altText: block.altText,
          caption: block.caption
        } %}
        {% include 'components/image.njk' %}
      {% endif %}
```

**Comment by architchandra** [comment]
@pdehaan Yes, that's what I noticed as well. Thanks for your suggestion. I'm choosing between going the `{% if %}` route and keeping the `components/body` code in the blog template itself.
