### ISSUE TITLE
New year, but post.date does show last day (31 Dec)

### ISSUE THREAD

**Issue by tcelestino** [11ty/eleventy#2156]
**Describe the bug**

New year, but when wrote a new text today, Eleventy show me "31 Dec 2021".

**To Reproduce**

1. Set a new date in "date". Example: "2022-01-01"
2. `post.date` show "31 Dec 2021" in template

**Expected behavior**

Correct date in the new year.

**Screenshots**
- my list posts
![Screen Shot 2022-01-01 at 20 57 01](https://user-images.githubusercontent.com/190265/147862638-956407e0-af5f-4740-a2ce-c5d32a066e8c.png)
- my post template
![Screen Shot 2022-01-01 at 20 57 13](https://user-images.githubusercontent.com/190265/147862639-b57581bf-a858-43b8-b337-445d3c32150b.png)

**Environment:**

- OS and Version: macOS Catalina 10.15.7
- Eleventy Version: 0.12.1

**Additional context**
I'm using [luxon](https://moment.github.io/luxon/) to date format in my locale (pt).  I don't know, but this issue might to be in `luxon` lib.

**Comment by pdehaan** [comment]
@tcelestino Interesting. I wonder if it's a time zone issue. What happens if you output the `{{ date }}` variable? Is it in GMT or   GMT+1?

**Comment by pdehaan** [comment]
I think I got it working, but I had to modify the Luxon timezone:

```njk
---
# test.njk
date: 2022-01-01
---

{{ date }}
{{ page.date }}

{{ date | dateFmt }}
{{ page.date | dateFmt }}
```

### OUTPUT

```html
Thu Dec 31 2021 16:00:00 GMT-0800 (Pacific Standard Time)
Thu Dec 31 2021 16:00:00 GMT-0800 (Pacific Standard Time)

1 JAN 2022
1 JAN 2022
```

Where my .eleventy.js and custom `dateFmt` filter look like this:

```js
module.exports = eleventyConfig => {
  eleventyConfig.addFilter("dateFmt", function (date) {
    return eleventyConfig.DateTime.fromJSDate(date)
      .setZone("UTC")
      .toFormat("d LLL yyyy")
      .toUpperCase();
  });

  return {
    dir: {
      input: "src",
      output: "www",
    }
  };
};
```

**Comment by tcelestino** [comment]
@pdehaan I'll test it using your suggestion.

**Comment by tcelestino** [comment]
I found the problem: cache.
