### ISSUE TITLE
Re-order documentation in a more user friendly manner

### ISSUE THREAD

**Issue by coolshaurya** [11ty/eleventy#217]
The documentation order currently is - 

- Overview
- Getting Started
- Using Data
- Configuration
- Working with Templates
- Template Languages
- Release History

The problem with this is that it is more sensible and user-friendly to order it in the following manner -

- Overview
- Getting Started
- Working with Templates
- Configuration
- Using Data
- Template Languages
- Release History

**Comment by zachleat** [comment]
wanna open a PR? the order is stored here https://github.com/11ty/11ty.io/blob/master/_includes/layouts/docs.njk#L7

**Comment by coolshaurya** [comment]
@zachleat done - PR #12

**Comment by zachleat** [comment]
Fixed by https://github.com/11ty/11ty.io/pull/12

**Comment by zachleat** [comment]
Thank you!
