### ISSUE TITLE
Eleventy Server: Watch not working (Windows 11)

### ISSUE THREAD

**Issue by dtanzer** [11ty/eleventy#2183]
I recently upgraded to eleventy 1.0.0 from a quite old version, and now "eleventy --serve" is not reliably watching files anymore. For some files it works, for some not:

When I change the file file `docs/editing.md`, it re-generates that file and everything works as expected:
```
[Browsersync] Reloading Browsers...
[11ty] File changed: docs\editing.md
```

When, on the other hand, I change the file `docs/editing/charts/line-charts.md`, eleventy does not re-generate and the browser does not reload the page.

Even though I use Markdown files, all render to HTML files that contain a `<body>`.

I read in issue https://github.com/11ty/eleventy/issues/701 that chokidar might be the problem, so I manually installed the newest version (3.5.3), but this has not effect whatsoever.

I am running eleventy in git bash on Windows 11.

**Comment by zachleat** [comment]
I believe this is a duplicate of #2187, specifically see this comment https://github.com/11ty/eleventy/issues/2187#issuecomment-1062255723

> Pro tip: in WSL2, put the files in ~, not /mnt/c. 11ty just got way faster and auto-rebuilds and reloads correctly.

**Comment by dtanzer** [comment]
@zachleat 
I know this other issue, but I think I do not have the same problem, since I am using git bash and not WSL2. I could be wrong, though...

**Comment by zachleat** [comment]
I'm literally publishing this today, but can you try the new 2.0 canary? It has a new server. If the chokidar dependency is to blame, though, you'll likely still have this problem, unfortunately.

**Comment by dtanzer** [comment]
I think I'm switching to WSL2 now...
