### ISSUE TITLE
Macros rendering as code / pre blocks

### ISSUE THREAD

**Issue by edwardhorsford** [11ty/eleventy#219]
I'm attempting to use my macros file from my old website. It appears that any indentation in the macros file gets interpreted as a code block

Here's a reduced example of one of my macros:
```javascript
{# Output a single portfolio image #}
{% macro portfolio_image_single(image) %}

	<figure class="portfolio-image {{image.class}}">
	</figure>

{% endmacro %}
```
Here's how it renders:
![screen shot 2018-09-10 at 20 47 27](https://user-images.githubusercontent.com/2204224/45320507-c1442780-b53a-11e8-8c4e-d3d9d0b55544.PNG)

Indentation causes macros to render as code.

Most of my macros have some form of indentation for readability. When rendering through Eleventy, initially the contents get rendered in pre blocks. Can this be disabled?

If I go through and remove all indentation it renders ok, but this greatly reduces the readability of the macros.

**Comment by zachleat** [comment]
It sounds like markdown templates are causing you more trouble than you want. Can you switch your root template to be a `njk` file instead?

If not, just keep in mind that indentation can create a code block in markdown:
https://commonmark.org/help/

![image](https://user-images.githubusercontent.com/39355/45328484-cea0e800-b521-11e8-87c2-be9b6735456d.png)

Can you remove the leading whitespace on those `<figure` lines?

Or use whitespace control to remove the whitespace https://mozilla.github.io/nunjucks/templating.html#whitespace-control

**Comment by edwardhorsford** [comment]
Thanks!

It sounds like markdown is being rather more aggressive than I might have wished in rendering outputs from macros. Is there any other solution other than giving up on markdown or adding lots of minus signs to most tags in the macros?

I think what I want is for markdown rendering to never be applied inside of a macro. Is this possible? Or a way to suspend and restart rendering.

Sadly most of my pages are likely to be a 50/50 mix of markdown and macros.

**Comment by edwardhorsford** [comment]
So now I understand a bit better what's going on, I have found an alternate solution which is to pass the output of the macro through the trim filter like so: 

{{ macro.portfolio_image_single({blob}) | trim }}

This is slightly easier to add to my existing setup and feels a bit neater. Can you think of any way I can set up the environment to apply this by default for macros?

**Comment by edwardhorsford** [comment]
@zachleat It looks like Nunjucks [may have some options for this](http://mozilla.github.io/nunjucks/api.html#configure). Is there any way for me to set this from eleventy? can you give me any pointers? we're about at the limits of my technical knowledge.

**Comment by zachleat** [comment]
Hmm, you’re in some weird advanced usage now but this example in your configuration should be the way forward. Looks like `Nunjucks.Environment` takes a second options arg

https://www.11ty.io/docs/languages/nunjucks/#optional%3A-use-your-nunjucks-environment

```
let Nunjucks = require("nunjucks");
module.exports = function(eleventyConfig) {
  let nunjucksEnvironment = new Nunjucks.Environment(
    new Nunjucks.FileSystemLoader("_includes"), // we need to pass in our includes dir here
    { lstripBlocks: true }
  );
  eleventyConfig.setLibrary("njk", nunjucksEnvironment);
};
```

I have not tried this, though! Good luck!

**Comment by edwardhorsford** [comment]
Amazing, thanks!

That seems like it may have fixed my issues, though it seems to take a few restarts to get it to engage.

Needed a more explicit file path and the `trimBlocks` option:
```javascript
let nunjucksEnvironment = new Nunjucks.Environment(
    new Nunjucks.FileSystemLoader("src/site/_includes"), // we need to pass in our includes dir here
    { lstripBlocks: true,
      trimBlocks: true
     }
  );
  eleventyConfig.setLibrary("njk", nunjucksEnvironment);
};
```

**Comment by zachleat** [comment]
Awesome—is this resolved for you? Can we close this one?

**Comment by edwardhorsford** [comment]
Not entirely, sadly. It looks like it corrects whitespace between any nunjucks blocks, but whitespace within html tags is left alone. AFAIK I thought markdown was meant to ignore stuff between tags.

In my macro:
![screen shot 2018-09-11 at 15 39 26](https://user-images.githubusercontent.com/2204224/45367401-0cad1300-b5d9-11e8-986a-457529e3808a.PNG)

Which outputs as code:
![screen shot 2018-09-11 at 15 40 57](https://user-images.githubusercontent.com/2204224/45367430-23ec0080-b5d9-11e8-9437-1df41cdb73a7.PNG)

If I left align the `noscript` block it's a little better, but still doesn't render correctly:
![screen shot 2018-09-11 at 15 41 42](https://user-images.githubusercontent.com/2204224/45367480-3e25de80-b5d9-11e8-8a66-4148b12bde37.PNG)
![screen shot 2018-09-11 at 15 42 39](https://user-images.githubusercontent.com/2204224/45367524-572e8f80-b5d9-11e8-8447-545d3de59a28.PNG)

It looks like I have to remove all indentation from the html too :( like this:
![screen shot 2018-09-11 at 15 43 26](https://user-images.githubusercontent.com/2204224/45367581-7af1d580-b5d9-11e8-8bdd-6d0478184fc5.PNG)

Note other bits of html with indentation look ok - so I wonder if it's something about the noscript tag that's causing the markdown renderer to *not* cancel.

---

I may need to give up on the idea of rending markdown together with macros in the same file - I had high hopes but sadly it's rather awkward.

My ideal would be for markdown rendering to not apply to any content of macros. But it sounds like that isn't possible?

**Comment by zachleat** [comment]
Hm? That renders as I would expect it to render.

```
<noscript>
  <div class="image__container">
    {# TODO: don't assume medium exists #}
    <img src="{{image_filename}}">
  </div>
</noscript>
```

Is correctly rendered by Nunjucks as:

```
<noscript>
  <div class="image__container">
    
    <img src="myfilename.png">
  </div>
</noscript>
```

You might need to brush up on Nunjucks Whitespace Control: https://mozilla.github.io/nunjucks/templating.html#whitespace-control

Try using `{#- TODO: don't assume medium exists -#}` if you want that newline to be removed.

**Comment by zachleat** [comment]
Please reopen if you have more questions or I’ve misunderstood the question!
