### ISSUE TITLE
Unable to override the content date in eleventyComputed property

### ISSUE THREAD

**Issue by mark-reason** [11ty/eleventy#2199]
If I set the date like this in eleventy computed it doesn't override the file date:
```nunjucks
---js
{
  layout: "layouts/base.html",
  pagination: {
    data: "pages",
    alias: "pg",
    size: 1
  },
  permalink: "/",
  eleventyComputed: {
    date: () => "2022-01-25"
  }
}
---
```

It does work however when I move this out of a computed property:
```nunjucks
---js
{
  layout: "layouts/base.html",
  pagination: {
    data: "pages",
    alias: "pg",
    size: 1
  },
  permalink: "/",
  date: "2022-01-25",
}
---
```

The reason I need this is I eventually want to use the page data to set the date.

**Comment by pdehaan** [comment]
See also:
- https://github.com/11ty/eleventy/issues/1249
- https://github.com/11ty/eleventy/issues/1323
- https://github.com/11ty/eleventy/issues/867

---

I don't like it [at all] but this hacky trick might work:

```js
---js
{
  pagination: {
    data: "pages",
    size: 1,
    alias: "pg",
    addAllPagesToCollection: true
  },
  permalink: "/page/{{ pg.date }}/{{ pg.title | slug }}/",
  eleventyComputed: {
    date(data) {
      const _date = new Date(data.pg.date);
      // HACK: Inject the computed date into the internal `page` object. Eeww.
      data.page.date = _date;
      return _date;
    }
  }
}
---

title={{ pg.title }}
pg.date={{ pg.date }}
eleventyComputed.date={{ date }}
page.date={{ page.date }}

page={{ page | inspect | safe }}
```

Where my ./src/_data/pages.js looks like this:

```js
module.exports = [
  { title: "page 1", date: "01/02/2022" },
  { title: "page 2", date: "02/03/2022" },
  { title: "page 3", date: "03/04/2022" },
];
```

### OUTPUT (_./www/page/03/04/2022/page-3/index.html_)
```html
title=page 3
pg.date=03/04/2022
eleventyComputed.date=Fri Mar 04 2022 00:00:00 GMT-0800 (Pacific Standard Time)
page.date=Fri Mar 04 2022 00:00:00 GMT-0800 (Pacific Standard Time)

page={
  date: 2022-03-04T08:00:00.000Z,
  inputPath: './src/index.njk',
  fileSlug: '',
  filePathStem: '/index',
  outputFileExtension: 'html',
  url: '/page/03/04/2022/page-3/',
  outputPath: 'www/page/03/04/2022/page-3/index.html'
}
```

**Comment by mark-reason** [comment]
Thanks @pdehaan!

**Comment by TigersWay** [comment]
@pdehaan Sorry to add on a closed issue, but is there another way than your - yes hacky 😄 - but very practical solution? It seems the only way to pass "information" from a data set to collection built with pagination.

**Comment by RReverser** [comment]
@pdehaan Thanks a lot for this hack, couldn't come up with any solution so I'm happy I stumbled upon this thread. I used it for both `page.date` and `page.url` fields so my blog can now reference posts published on other (corporate) blogs and show them in a list like regular posts.
