### ISSUE TITLE
Issue with embedded macro breaking rendering

### ISSUE THREAD

**Issue by edwardhorsford** [11ty/eleventy#220]
I've got an existing macro I use very frequently as a helper function in my other macros. It works fine in my existing Node / Express / Nunjucks site, but not at all in Eleventy.

It's very possibly my issue, but if anyone could help, that would be great. Note I've removed indentation in the macro because of #219.

The macro lets me output html attributes conditionally based on whether a value exists (has been passed to the parent macro).

Here's the problem macro:
```javascript
{# Output attribute only if value exists #}
{% macro attr?(attribute, value) %}
{% set output = '' %}
{% if value %}
{% set output = attribute + '=' + value %}
{% endif %}
{{output}}
{% endmacro %}
```

Here's an example of it in use:
```javascript
{% macro portfolio_image_single(image) %}

{# Set ID and position if present #}
{% set id? = attr?('id', image.id) %}
<figure {{id?}} class="portfolio-image {{image.class}}">
// image stuff
</figure>

{% endmacro %}
```

Where `image` is an object I pass to the parent macro when calling it. At a minimum it will have a url to an image asset, but it optionally has lots of other fields.

## Expected outcome:
![screen shot 2018-09-10 at 20 57 11](https://user-images.githubusercontent.com/2204224/45321069-411ec180-b53c-11e8-8105-b4f1f745caf4.PNG)
(hardcoded `id?` with `{% set id? = "id=foo" %}`)

## What I get:
![screen shot 2018-09-10 at 20 55 30](https://user-images.githubusercontent.com/2204224/45320973-f43aeb00-b53b-11e8-9bf9-2c076fbd8d15.PNG)

I thought it might be my use of `?` in variable names, but I removed that and still get the issue. Other embedded macros seem to work ok, so I don't think it's that either.

**Comment by zachleat** [comment]
So your macro is a njk file, but what file is consuming the macro? If that is an `.md`, any stray newlines can create a `<p>`

Have you read about nunjucks whitespace control?
https://mozilla.github.io/nunjucks/templating.html#whitespace-control

**Comment by edwardhorsford** [comment]
Yes, it's an md calling the macro file.

I have the same issue if I try to create a macro in place on the page. It would be cool if markdown rendering were suspended between the tags.

With this added info this sounds like a duplicate of #219, so I'll close this in favour of that.
