### ISSUE TITLE
Template error with njk - parseSignature: expected comma after expression

### ISSUE THREAD

**Issue by deejaygraham** [11ty/eleventy#2218]
**Describe the bug**
I'm getting an error which seems to move around between markdown files, depending on which one is processed first I suppose. 
"parseSignature: expected comma after expression"

**Description**
Need some guidance on where else to go. Turning on debug gives lots of extra info but not sure it's helping at all. 

I am converting from a big html repo to markdown. Using a basic nunjucks template and all of the original markup lets the new site generate correctly as expected. Trying to add in a shortcode to move proprietary *code* tags to use eleventy prism plugin. This seems to work fine mostly but then breaks with this error message. I can't find any issue with the line (or around that area) that would cause the problem and the column number does not exist for that line or else it is in the middle of a block of text. Checked the markup and all looks good - unless this error is staring me in the face. Is there a way of seeing intermediate markup? or are the line and column values not related to the source doc?

**Stack Trace**
`TemplateContentRenderError` was thrown
  Eleventy:EleventyErrorHandler (error stack): TemplateContentRenderError: Having trouble rendering njk template ./html/DOC0001_Example.md
  Eleventy:EleventyErrorHandler     at Template._render (C:\Dev\indigo\SDK\Documentation\node_modules\@11ty\eleventy\src\TemplateContent.js:441:15)
  Eleventy:EleventyErrorHandler     at processTicksAndRejections (internal/process/task_queues.js:95:5)
  Eleventy:EleventyErrorHandler     at async Template.getTemplateMapContent (C:\Dev\indigo\SDK\Documentation\node_modules\@11ty\eleventy\src\Template.js:1056:19)
  Eleventy:EleventyErrorHandler     at async TemplateMap.populateContentDataInMap (C:\Dev\indigo\SDK\Documentation\node_modules\@11ty\eleventy\src\TemplateMap.js:461:39)
  Eleventy:EleventyErrorHandler     at async TemplateMap.cache (C:\Dev\indigo\SDK\Documentation\node_modules\@11ty\eleventy\src\TemplateMap.js:360:5)
  Eleventy:EleventyErrorHandler     at async TemplateWriter._createTemplateMap (C:\Dev\indigo\SDK\Documentation\node_modules\@11ty\eleventy\src\TemplateWriter.js:242:5)
  Eleventy:EleventyErrorHandler     at async TemplateWriter.generateTemplates (C:\Dev\indigo\SDK\Documentation\node_modules\@11ty\eleventy\src\TemplateWriter.js:275:5)
  Eleventy:EleventyErrorHandler     at async TemplateWriter.write (C:\Dev\indigo\SDK\Documentation\node_modules\@11ty\eleventy\src\TemplateWriter.js:321:23)
  Eleventy:EleventyErrorHandler     at async Eleventy.executeBuild (C:\Dev\indigo\SDK\Documentation\node_modules\@11ty\eleventy\src\Eleventy.js:986:13) +0ms
[11ty] (./html/DOC0001_Example.md) [Line 46, Column 63]

**Environment:**

- OS and Version: Windows 10
- Eleventy Version 1.0.0

**Comment by pdehaan** [comment]
If you have a public repo I can help take a look.
If not, can you post a sample failing .md file and your .eleventy.js config file?

**Comment by deejaygraham** [comment]
Not a public repo. Think I have found it, my misunderstanding of how to pass data to shortcodes and paired shortcodes. Thanks for the reply :)

**Comment by sbrl** [comment]
@deejaygraham this issue appears very highly in search results. Could you perhaps share some example code to demonstrate the issue and it's solution please?

**Comment by AnitaYCheng** [comment]
For what it's worth, I got this error when using the Eleventy Image shortcode. I fixed it when I removed extra quotes from my alt text value in the shortcode, which was already in quotes.
