### ISSUE TITLE
Unknown Liquid filters and variables block build even if strict is off

### ISSUE THREAD

**Issue by xplosionmind** [11ty/eleventy#2229]
**Describe the bug**
Even though in my `.eleventy.js` I have set the following:
```javascript
  eleventyConfig.setLiquidOptions({
    dynamicPartials: false,
    strictVariables: false,
    strictFilters: false,
    jekyllInclude: true
  });
```
I continue to get errors of filters not being recognized. As side note, I do not even understand why filters that should be supported by LiquidJS are not recognized.

**To Reproduce**

1. In an include named `stuff.html`, write:  
```
{% assign stuff = site.data.stuff | sort: 'current' %}
<section id='stuff' class='row'>
    {% for thing in stuff %}
	<a href='{{ thing.url }}'>{{ thing.title }}</a>
    {% endfor %}
</section>
```
2. Place the include inside the file `stuff-it.html`
3. Build the website
4. The error I get is:
```
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering html template ./pages/stuff.html

`TemplateContentRenderError` was thrown
> Cannot read properties of undefined (reading 'sort'), file:/Users/tommi/tommi.space/_includes/stuff.html, line:1

`RenderError` was thrown
> Cannot read properties of undefined (reading 'sort')

`TypeError` was thrown:
    TypeError: Cannot read properties of undefined (reading 'sort')
        at sort (/Users/tommi/tommi.space/node_modules/liquidjs/dist/liquid.common.js:3306:14)
        at Object.render (/Users/tommi/tommi.space/node_modules/liquidjs/dist/liquid.common.js:1914:26)
        at /Users/tommi/tommi.space/node_modules/liquidjs/dist/liquid.common.js:1807:21
        at Array.reduce (<anonymous>)
        at Object.evalValue$$1 [as evalValue] (/Users/tommi/tommi.space/node_modules/liquidjs/dist/liquid.common.js:1806:29)
        at Object.evalValue$$1 [as evalValue] (/Users/tommi/tommi.space/node_modules/liquidjs/dist/liquid.common.js:3577:26)
        at Object.render (/Users/tommi/tommi.space/node_modules/liquidjs/dist/liquid.common.js:2253:30)
        at Object._callee$ (/Users/tommi/tommi.space/node_modules/liquidjs/dist/liquid.common.js:1851:55)
        at tryCatch (/Users/tommi/tommi.space/node_modules/liquidjs/dist/liquid.common.js:108:40)
        at Generator.invoke [as _invoke] (/Users/tommi/tommi.space/node_modules/liquidjs/dist/liquid.common.js:319:22)
Wrote 0 files in 0.60 seconds (v0.12.1)
```

This happens with `where_exp`, too, as pointed out in #2228

**Expected behavior**
Liquid filter should be ignored if not recognized. Nevertheless, it should be recognized, too!

**Screenshots**: n/a

**Environment:**

- OS and Version: MacOS 12.2.1
- Eleventy Version: 1.0.0

**Additional context**
It would be lovely to get more debugging context for non-developers like I am. I cannot figure out the cause of this not working.

**Comment by pdehaan** [comment]
Seems to work for me. https://github.com/pdehaan/11ty-2229
I suspect it's an issue with your `site.data.stuff` config, and that is evaluating to `undefined` which is breaking the LiquidJS sort filter.
> _Cannot read properties of `undefined` (reading 'sort')_

Here's what my sample /src/_data/site.js file looks like (where `site` is the name of the file, and `data.stuff` are nested properties; with `stuff` being an array so it works with the built-in LiquidJS `sort` filter):

```js
module.exports = {
  data: {
    stuff: [
      { title: "OnE", url: "/one", current: true },
      { title: "TwO", url: "/two", current: false },
      { title: "ThReE", url: "/three", current: false },
      { title: "FoUr", url: "/four", current: true },
      { title: "FiVe", url: "/five", current: false },
    ],
  },
};
```

**Comment by xplosionmind** [comment]
Still, as pointed out in #2228, also `where_exp` filter blocks the build… it should be ignored since not recognized, as it is a Jekyll-only filter!

**Comment by xplosionmind** [comment]
As pointed out in #2234, I am getting so confused because it appears that the problem is not only related `where_exp` or `sort` filters, but to any Liquid filter in general… I cannot pinpoint the origin of the issue. By cloning your repo to test this issue, everything works.

**Comment by AleksandrHovhannisyan** [comment]
I think these errors are red herrings. I vaguely recall that when I was migrating my old Jekyll site to 11ty, I got many similar errors about filters not existing. The filters existed, but I think something was breaking in the build pipeline and throwing off the Liquid parser or 11ty.

**Comment by xplosionmind** [comment]
As noted in #2234, the problems were not the filters themselves, but rather the nature of the object they were applied to.
