### ISSUE TITLE
Use .mst templates with Mustache templates

### ISSUE THREAD

**Issue by coolshaurya** [11ty/eleventy#223]
The `.mst` file extension is preferred for working with mustache files but it doesn't work.

The error given is -
![image](https://user-images.githubusercontent.com/32027323/45361744-9e744a80-b5f0-11e8-9c9b-33ec6c91dbfc.png)

**Comment by zachleat** [comment]
Can you upvote the top comment for #207?

This is a duplicate of that enhancement request
