### ISSUE TITLE
Eleventy advises using debug output when in debug mode.

### ISSUE THREAD

**Issue by edwardhorsford** [11ty/eleventy#224]
I have some kind of issue with my templates causing a render error.

Eleventy advises using debug mode even though I'm already using debug mode. I presume it shouldn't give this advice when in debug mode.
![screen shot 2018-09-12 at 13 00 31](https://user-images.githubusercontent.com/2204224/45423641-daa8b900-b68b-11e8-933a-6764c62b743e.PNG)

---

As an aside - the output can be hard to skim to work out which file has the issue. Most of the errors spat out refer to node modules, rather than the likely culprit files. In this case, it took quite a long time to work out what was wrong as the actual file with the issue isn't stated. All it tells me is it's line 3 of _some file_. I went through all recently changed files moving the lines down by one to work out which file was causing the crash.

**Comment by zachleat** [comment]
Fair point! Some of the error reporting stuff has been already reworked and improved in 0.5.4 but I’m sure it still says this 😎

The debug output tries to give as _much_ information as possible for both you and I to debug the situation. That means that yes, the debug output will spit ugly stack traces—maybe not super helpful to you but they’re necessary.

Hopefully it will read a little better in the next version, we can revisit discussion after that’s released.

**Comment by mathiasbynens** [comment]
I think @edwardhorsford was referring to the `(more info in DEBUG output)` part of the output. This is printed even when in DEBUG mode.

**Comment by zachleat** [comment]
Pushed some code to fix this specific issue. Please reopen a new issue if you see additional problems with error reporting after 0.5.4 is released.
