### ISSUE TITLE
Template changes with Eleventy Serverless do not show up

### ISSUE THREAD

**Issue by cfjedimaster** [11ty/eleventy#2245]
**Describe the bug**
I've got a template using Eleventy Serverless, and if I make a minor change, I see the CLI notice it, I see the browser reload, but it my changes are not reflected. 

If I ctrl+c Eleventy and restart, the changes are there. 

**To Reproduce**
Just make a template using Eleventy Serverless and make some minor HTML change. You'll see the CLI notice a change, the browser reloads, but the change to your HTML is not there.

**Expected behavior**
That the changes are reflected.

**Comment by zachleat** [comment]
This was one of the explicit things I tested with the new Eleventy Dev Server—curious if you can confirm!

https://www.11ty.dev/docs/watch-serve/#eleventy-dev-server

**Comment by cfjedimaster** [comment]
FYI, I tried running @11ty/eleventy@beta, but that's not showing 2.0.

**Comment by pdehaan** [comment]
I think you need to use `@canary` tag for v2.0.0, as `@beta` still points to pre v1.0.0.

**Comment by cfjedimaster** [comment]
Yeah, I should have shared how I fixed my test. I didn't use canary but the version string I saw on npm. Either way it's fixed. :>

**Comment by zachleat** [comment]
Awesome, thank you for confirming!
