### ISSUE TITLE
Nunjucks and async filters - clearer documentation

### ISSUE THREAD

**Issue by cfjedimaster** [11ty/eleventy#2254]
Unless I'm seeing wrong, while Nunjucks does support async filters, it does *not* support them if you do it via a global filter. I had this:

```js
eleventyConfig.addFilter("qrcode", async function(value) {
		return await qrCode.toDataURL(value);
});
```

Which worked fine in Liquid, but returned a pending promise in Nunjucks. Adding this made it work in Nunjucks:

'''js
eleventyConfig.addNunjucksAsyncFilter("qrcode2", async function(value, callback) {
	let result = await qrCode.toDataURL(value);
	callback(null,result);
});
```

I guess my issue here is - it doesn't seem clear to me that the universal async filter should fail in Nunjucks. Can we add something to the doc (I'd say to *both* pages) to clarify this? (Willing to file a PR.)

**Comment by zachleat** [comment]
https://www.11ty.dev/docs/filters/#asynchronous-universal-filters
