### ISSUE TITLE
TypeError: eleventyConfig.getFilter(...) is not a function

### ISSUE THREAD

**Issue by pavelloz** [11ty/eleventy#2257]
https://www.11ty.dev/docs/filters/#access-existing-filters

I just tried to use this feature and it looks like it does not work.

Im getting:
`console.log(eleventyConfig.getFilter);` => `[Function: getFilter]`

Which means it exists.

`console.log(eleventyConfig.getFilter("safe"));` => `undefined`

Which is wrong, because safe filter is built into nunjucks and used in various places of the app.

Having said that, when i console.log(eleventyConfig) i cannot find `safe` filter, even though it is used in many places.

```js
  nunjucksFilters: {
    slug: [Function (anonymous)],
    slugify: [Function (anonymous)],
    url: [Function (anonymous)],
    log: [Function (anonymous)],
    serverlessUrl: [Function (anonymous)],
    getCollectionItem: [Function (anonymous)],
    getPreviousCollectionItem: [Function (anonymous)],
    getNextCollectionItem: [Function (anonymous)],
    htmlDateString: [Function (anonymous)],
    readableDate: [Function (anonymous)],
    eleventyNavigation: [Function (anonymous)],
    eleventyNavigationBreadcrumb: [Function (anonymous)],
    eleventyNavigationToHtml: [Function (anonymous)],
    eleventyNavigationToMarkdown: [Function (anonymous)]
  },
```

Or maybe its not possible to access built-in filters, only defined by me in .eleventy.js?
If so, probably it would be a good idea to mention it in docs :)

---

Maybe context will help. Im trying to make a copy of `safe` filter to liquid. In ruby its called `html_safe`
```js
  eleventyConfig.addLiquidFilter("html_safe", function(value) {
    return `${eleventyConfig.getFilter("safe")(value)}`;
  });
```

**Comment by pdehaan** [comment]
I couldn't find my old test case, but this should do it:

```js
// .eleventy.js
const nunjucksVersion = require("nunjucks/package.json").version; // 3.2.3
const nunjucksFilters = require("nunjucks/src/filters");

module.exports = function (eleventyConfig) {
  eleventyConfig.addGlobalData("nunjucksVersion", nunjucksVersion);
  eleventyConfig.addFilter("inspect", (value) => nunjucksFilters.dump(value));

  return {
    dir: {
      input: "src",
      output: "www",
    }
  };
};
```

```njk
---
# /src/index.njk
title: Nunjucks filter test
---

<h1>{{ title }}</h1>

<pre>{{ page }}</pre>
<pre>{{ page | inspect | safe }}</pre>

<small>{{ nunjucksVersion }}</small>
```

### OUTPUT
```html
<h1>Nunjucks filter test</h1>

<pre>[object Object]</pre>
<pre>{"date":"2022-03-02T17:22:32.614Z","inputPath":"./src/index.njk","fileSlug":"","filePathStem":"/index","outputFileExtension":"html","url":"/","outputPath":"www/index.html"}</pre>

<small>3.2.3</small>
```

Probably not the best approach, but it does let you use Nunjucks filters in Liquid templates (which can be a good or bad thing).

**Comment by pdehaan** [comment]
> Maybe context will help. Im trying to make a copy of `safe` filter to liquid. In ruby its called `html_safe`
> 
> ```js
>   eleventyConfig.addLiquidFilter("html_safe", function(value) {
>     return `${eleventyConfig.getFilter("safe")(value)}`;
>   });
> ```

I might be missing something, but doesn't liquidjs use `"safe"` mode by default?

## Nunjucks

```njk
---
# /src/nunjucks.njk
str: "an <script>alert('ok')</script> unsafe string"
---

default: {{ str }}
safe: {{ str | safe }}
```

### OUTPUT

```html
default: an &lt;script&gt;alert(&#39;ok&#39;)&lt;/script&gt; unsafe string
safe: an <script>alert('ok')</script> unsafe string
```

---

## LiquidJS

```liquid
---
# /src/liquid.liquid
str: "an <script>alert('ok')</script> unsafe string"
---

default: {{ str }}
escape: {{ str | escape }}
```

### OUTPUT

```html
default: an <script>alert('ok')</script> unsafe string
escape: an &lt;script&gt;alert(&#39;ok&#39;)&lt;/script&gt; unsafe string
```

**Comment by pavelloz** [comment]
That is a very good question. I assumed that if nunjucks and liquid-ruby needs it, it will be needed here as well.
I guess i should try instead of reinventing the wheel :)

Thank you for your help Peter :)
