### ISSUE TITLE
Eleventy watcher ignores *unlink* events

### ISSUE THREAD

**Issue by genemars** [11ty/eleventy#2272]
I was wondering why *11ty* does not implement watching of "unlink" events.
When files are deleted from input folder, Eleventy does nothing, not even trigger the browser refresh.
This looks like kind of a bug when deleting an Item that, for instance, is listed on a menu. The item appears to be still there and can also be opened.
The only way to update the page is to stop Eleventy, delete output folder, and restart it.
Watching/syncing of deleted files would be a nice feature to have, at least as a switchable configuration option.

**Comment by genemars** [comment]
I solved writing a separate watcher for passthroughCopyFiles

**Comment by davidvasandani** [comment]
@genemars could you share your fix? 🙏🏻

**Comment by genemars** [comment]
You can find the fix in my Eleventy-based [web-starter](https://zuixjs.github.io/zuix-web-starter/).
In particular [this is the code](https://github.com/zuixjs/zuix-web-starter/blob/1d2439c01d1f3bd9d0d12c8dee0aa01be0f599e8/.eleventy-zuix.js#L139) that does the trick.
The code is not reusable as-is since it takes care of other things as well, but should give an idea of how the fix works.
