### ISSUE TITLE
Unable to get .eleventyignore working

### ISSUE THREAD

**Issue by edwardhorsford** [11ty/eleventy#228]
I'm struggling to get `.eleventyignore` to work and would appreciate help from anyone who as.

I've looked through the docs site but can't find the feature mentioned anywhere - just observed the `.eleventyignore` file in a few starter projects and existing closed issues.

In lieu of drafts support, my short term plan is to put draft posts in a folder `_drafts`. I then plan to ignore this folder.

My site structure is `src/site/_drafts/`

I've set up a `.eleventyignore` in the root of my project, and have tried the following, both individually and all at once:
```
_drafts
_drafts/
_drafts/*
./_drafts
./_drafts/
./_drafts/*
site/_drafts
site/_drafts/
site/_drafts/*
./site/_drafts
./site/_drafts/
./site/_drafts/*
src/site/_drafts
src/site/_drafts/
src/site/_drafts/*
./src/site/_drafts
./src/site/_drafts/
./src/site/_drafts/*
```

Do I need to do something special to initialise the file? any other ideas?

**Comment by zachleat** [comment]
Can you attach your DEBUG output? https://www.11ty.io/docs/debugging/

**Comment by edwardhorsford** [comment]
@zachleat can I send it to you privately?

**Comment by edwardhorsford** [comment]
On a hunch, I moved the `.eleventyignore` in to `src/site/` and it seems to work. 

Is this the intended location of this file? I assumed it would live in the project root like `.gitignore`

**Comment by zachleat** [comment]
Hmm, even worse it looks like there is absolutely no documentation for this feature at all. 😱 Looks like it got lost when I moved from github documentation to 11ty.io. Here’s a link to the old docs: https://github.com/11ty/eleventy/blob/v0.3.5/README.md#ignore-files-optional

Eleventy expects your `.eleventyignore` file to be at the root of your input directory. We could add additional folder checks for this file (feature requests welcome), but that’s where it lives currently.

For my own personal notes, there is more behavior there in the code worth evaluating:

`.gitignore` also lives in the root of the input directory—maybe it shouldn’t? Might make sense to check to see if that lives in the command root instead (more likely to match the repo root)
`node_modules` lives at the command root

**Comment by zachleat** [comment]
Re-added the documentation to https://www.11ty.io/docs/ignores/

Opened related issue for #229 for `.gitignore` location discussion.

If you’d like to open a new enhancement request ticket to discuss adding additional location checks for the `.eleventyignore` file, please do!

Thank you!

**Comment by zachleat** [comment]
Ahh, the special variables section is on the Data page now: https://www.11ty.io/docs/data/
