### ISSUE TITLE
Setting `markdownTemplateEngine: false` prevents you from using  Nunjucks/Liquid in permalink

### ISSUE THREAD

**Issue by pdehaan** [11ty/eleventy#2283]
If you set `markdownTemplateEngine: false` in your frontmatter or a data file, it appears like you can no longer use a `permalink` format like `blog/{{ category | slugify }}`.

Not sure if there is a way to prevent Markdown from preprocessing templates using Nunjucks or LiquidJS while still being able to use some Nunjucks in the `permalink` frontmatter.

---

If you want to disable liquidjs processing of the markdown files, it looks like you CAN set `markdownTemplateEngine: false` in your .eleventy.js config file, but then you'll need to rename your posts/posts.json file to posts/posts.11tydata.js and set the `permalink` using JavaScript instead of liquidjs templating:

```js
// posts/posts.11tydata.js
module.exports = {
  // "permalink": "blog/{{ categories | first }}/{{ title | slugify }}/index.html",
  featured: false,
  layout: "layouts/post.njk",
  eleventyComputed: {
    permalink(data) {
      return `blog/${ data.categories[0] }/${ this.slugify(data.title) }/`
    }
  }
};
```

_Originally posted by @pdehaan in https://github.com/11ty/eleventy/issues/2273#issuecomment-1065840979_

**Comment by zachleat** [comment]
A few other workarounds that might be worth noting:
* Use the [render plugin](https://www.11ty.dev/docs/plugins/render/) to render markdown in the body while keeping the top level engine as liquid or nunjucks
* Using the `raw` shortcode in Nunjucks or Liquid should bypass those engines but keep markdown in place.

Might also be possible to set the permalink in a layout file too?

**Comment by zachleat** [comment]
I don’t think we’re going to fix this one, unfortunately. The template engine informs the syntax through which the permalink will be rendered. The easiest workaround here is to use a JavaScript function for permalink, which is consistent across template languages (though a bit painful to use in YAML front matter, to be fair). #2819 helps there
