### ISSUE TITLE
11ty serverless cannot find internal modules imported into .eleventy.js

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [11ty/eleventy#2288]
## Describe the bug

Some 11ty projects will import things like filters, shortcodes, and utilities into their main `.eleventy.js` config from a separate module to keep things clean and easier to read. In the example tree output below, that module is the `config` folder, which contains a demo file `filters.js` that exports a custom 11ty filter:

```
.
├── config
│   └── filters.js
├── package.json
├── src
│   └── index.md
└── .eleventy.js
```

(See for example: https://www.webstoemp.com/blog/eleventy-projects-structure/)

Here's what the `.eleventy.js` file might look like:

```js
const { EleventyServerlessBundlerPlugin } = require("@11ty/eleventy");
const { increment } = require('./config/filters');

module.exports = (eleventyConfig) => {
  eleventyConfig.addPlugin(EleventyServerlessBundlerPlugin, {
    name: "onrequest",
    functionsDir: "./netlify/functions/",
  });
  eleventyConfig.addFilter('increment', increment);

  return {
    dir: {
        input: 'src',
        output: '_site',
    },
  };
};
```

If you then set up a serverless permalink and try to navigate to it, you'll get the following error:

```
Serverless Error: EleventyConfigError: Error in your Eleventy config file '//sandbox/11ty/netlify/functions/onrequest/eleventy.config.js'. You may need to run `npm install`.

<stack trace omitted for brevity>

originalError: Error: Cannot find module './config/filters'
```

## To Reproduce

1. Clone the repo here: https://github.com/AleksandrHovhannisyan/11ty-sandbox
2. Check out the demo branch: [`serverless-imports-in-eleventy-js`](https://github.com/AleksandrHovhannisyan/11ty-sandbox/tree/serverless-imports-in-eleventy-js).
3. Install dependencies.
4. Run `yarn serve`.
5. Navigate to localhost:8080 and click the link to request building the serverless page.
6. Observe the error:

```
{
  "error": "Error in your Eleventy config file '/sandbox/11ty/netlify/functions/onrequest/eleventy.config.js'.\u001b[36m You may need to run `npm install`.\u001b[39m"
}
```

## Expected behavior

11ty serverless should support internal modules that are imported into `.eleventy.js`.

## Environment

- Eleventy Version: 1.0.0

## Additional context

Slightly different but possibly related issue: https://github.com/11ty/eleventy/issues/2222

**Comment by zachleat** [comment]
I fixed this! Shipping with 2.0.0-canary.5.

If you feel strongly that this to be back-ported to 1.x, please make your case 🙌🏻

**Comment by AleksandrHovhannisyan** [comment]
Awesome, thanks @zachleat! I don't feel too strongly on backporting it for v1; I'll probably be upgrading to v2 anyway.

**Comment by pdehaan** [comment]
@zachleat Do we have an ETA on when Eleventy v2 will be the stable/release version?

**Comment by zachleat** [comment]
@pdehaan It’ll be the focus for stable after 1.0.1 ships! If I had to guess I’d probably say a month? Maybe less? I don’t think it’d take much to backport

**Comment by stevenmilstein** [comment]
@AleksandrHovhannisyan I believe I'm having a similar problem. In my case, Serverless on-demand & dynamic, work on localhost but both fail when deployed to Netlify. The only errors are in the Function logs:
```
Serverless Error: EleventyConfigError: Error in your Eleventy config file '/var/task/netlify/functions/dynamic/eleventy.config.js'. You may need to run `npm install`.
....
originalError: Error: Cannot find module 'dotenv'
```
'dotenv' is the first 'require' in my equivalent of your config.filters.js

Did 2.0.0-canary.5 or later resolve the problem you were experiencing?

**Comment by AleksandrHovhannisyan** [comment]
@stevenmilstein Oh, I haven't tested it yet.

**Comment by stevenmilstein** [comment]
@AleksandrHovhannisyan I tested it with 2.0.0-canary.5  & it works. 

In my case, using `require` inside my equivalent of your config.filters.js still failed.

Fortunately, I came across 2.0.0-canary.8 which is now only a few hours old and everything is working as designed.  

Big 🙏  to @zachleat and everyone else who contributed!
