### ISSUE TITLE
TemplateContentRenderError: 'Illegal filename "undefined"'

### ISSUE THREAD

**Issue by noiseymur** [11ty/eleventy#2305]
After updating to 1.0.0 from 0.11.1, I'm getting this error:

![image](https://user-images.githubusercontent.com/65159986/161570338-fcd288b1-a9a7-4b84-acd3-9d8b611c97f3.png)

I've read a similar issue (#1979) to which it was replied to use upgrade helper, but in my case that does not make any change.

**Comment by pdehaan** [comment]
@noiseymur Did you try setting `dynamicPartials: false` in your Eleventy LiquidJS config?
https://www.11ty.dev/docs/languages/liquid/#optional-use-your-own-options

If this code in a public repo somewhere that I can clone locally, I can help troubleshoot.

**Comment by pdehaan** [comment]
Hhhmm, the AssertionError doesn't sound familiar.
A few older instances in the issues, https://github.com/11ty/eleventy/search?q=assertionerror+is%3Aissue&type=issues but nothing obvious.

There were also some changes around default Liquid strict filters in v1, so maybe a typo in a filter name? Hard to tell from a truncated error message+stack. You could see if it disappears if you set `strictFilters: false` in your Liquid config; https://www.11ty.dev/docs/languages/liquid/#optional-use-your-own-options
But if that's the case, you probably have an issue w/ one of your filters.
