### ISSUE TITLE
New Server plugins & Output Directory on the command line

### ISSUE THREAD

**Issue by TigersWay** [11ty/eleventy#2311]
**Describe the bug**
Trying to use `--output=public` on the command line will generate all the expected files in the `public` folder, but the server - new one or even browser-sync - will open `_site`.

**To Reproduce**
`eleventy --output=x --serve` will serve `_site`

**Expected behavior**
Eleventy to serve the output folder (x as in the previous line).

**Environment:**
- Windows 10 OS and Version: [e.g. Windows/Mac/Linux]
- Eleventy 2.0.0-canary.4

**Additional context**
With `dir.output` set in the config file, everything is working

**Comment by zachleat** [comment]
2.0.0-canary.19!
