### ISSUE TITLE
Setting site.url to localhost:3000 (for example) when developing locally

### ISSUE THREAD

**Issue by adamsilver** [11ty/eleventy#233]
Is it possible to override config settings when developing locally. I currently have site.json inside includes/_data and it's set to https://example.com. For development purposes it would be nice if I can set it to http://localhost:3000.

Is this possible?

**Comment by zachleat** [comment]
Have you seen this example that @kleinfreund added? https://www.11ty.io/docs/data-js/#example%3A-exposing-environment-variables

**Comment by kleinfreund** [comment]
Something along these lines will expose `site.url` to your templates.

**`_data/site.js`**:

```js
module.exports = {
  url: process.env.ELEVENTY_ENV === 'development' ? http://localhost:3000 : https://example.com;
};
```

Development:

```
ELEVENTY_ENV=development npx eleventy --serve
```

Production:

```
ELEVENTY_ENV=production npx eleventy
```

**Comment by adamsilver** [comment]
Amazing thanks!

**Comment by zachleat** [comment]
Closing 🎉
