### ISSUE TITLE
Collection's getFilteredByGlob, Array of globs & negative pattern

### ISSUE THREAD

**Issue by TigersWay** [11ty/eleventy#2331]
**Describe the bug**
Little detail left out of the documentation or feature not totally implemented, the `getFilteredByGlob` method does not allow multimatch negative pattern.

**To Reproduce**
```
  eleventyConfig.addCollection("oldposts", function(collectionApi) {
    return collectionApi.getFilteredByGlob(["posts/**/*.md", "!posts/2022/**/*.md"]);
  });
```
**Expected behavior**
I could expect - in this example - to get all markdown documents before 2022.

**Additional context**
As each path of the array is "corrected", any negative pattern will change and be wrong. So not sure I should request a feature which could be implemented another -even slower - way 😄

**Comment by pdehaan** [comment]
Not sure that's supported.  I've been trying to figure out how multimatch's negations work, but haven't had much luck getting your use case to work yet.

In the meantime, it seems to work if you use something like fast-glob and do the file globbing yourself:

```js
const glob = require("fast-glob").sync;

module.exports = function (eleventyConfig) {
  eleventyConfig.addCollection("oldposts", function(collectionApi) {
    const files = glob(["src/posts/**/*.md"], {
      ignore: ["src/posts/2022/**/*.md"]
    });
    return collectionApi.getFilteredByGlob(files);
  });

  return {
    dir: {
      input: "src",
      output: "www",
    }
  };
};
```

```sh
tree src

src
├── index.liquid
└── posts
    ├── 2021
    │   ├── five.md
    │   ├── four.md
    │   └── six.md
    ├── 2022
    │   ├── one.md
    │   ├── three.md
    │   └── two.md
    └── posts.json

3 directories, 8 files
```

And that seems to return an `collections.oldposts` collection with the following templates:

-  /posts/2021/five/
-  /posts/2021/four/
-  /posts/2021/six/

**Comment by TigersWay** [comment]
As usual @pdehaan you are totally right. Having used multimatch in the past, I jumped on the negative pattern featured, which can't work - as is - in Eleventy (every path goes through TemplatePath.addLeadingDotSlash) and **maybe** should be specified in the documentation.
Meanwhile there is some solutions, and yours is great 👍

**Comment by pdehaan** [comment]
I guess the other, potentially easier solution is to just filter the templates in the glob:

```js
  eleventyConfig.addCollection("oldposts", function(collectionApi) {
    const currYear = new Date().getFullYear();
    return collectionApi.getFilteredByGlob("src/posts/**/*.md")
      .filter(post => post.date.getFullYear() !== currYear);
  });
```

Where I'm explicitly setting front matter like:

```liquid
---
title: FOUR
date: 2021-04-14
---

{{ title }}
```

---

Or even something like this would work:

```js
  eleventyConfig.addCollection("oldposts", function(collectionApi) {
    return collectionApi.getFilteredByGlob("src/posts/**/*.md")
      .filter(post => !post.url.includes("/2022/"));
  });
```
