### ISSUE TITLE
Duplicate permalink error with 2.0.0-canary.5

### ISSUE THREAD

**Issue by eatyourgreens** [11ty/eleventy#2333]
**Describe the bug**
I have a paginated template which worked fine up until 2.0.0-canary.4 but now fails with duplicate permalink errors in 2.0.0-canary.5.
```
Output conflict: multiple input files are writing to `dist/groups/the-geological-magazine-or-monthly-journal-of-geology/index.html`. Use distinct `permalink` values to resolve this conflict.
```

**To Reproduce**
My pagination setup looks like this:
```yml
pagination:
  data: groups
  resolve: values
  size: 1
  alias: group
permalink: "/groups/{{ group.name }}/"
```
 The `group` object that's are causing the error looks like this:
```js
groups: {
  ...
  GSC000000m: {
    name: 'the-geological-magazine-or-monthly-journal-of-geology',
    title: 'The geological magazine, or, Monthly journal of geology.'
    ...
  }
}
```

With 2.0.0-canary.4 and earlier, that group writes to:
```
dist/groups/the-geological-magazine-or-monthly-journal-of-geology/index.html
```

With 2.0.0-canary-5, I get the duplicate permalink error and the build fails. I can't see anything else in my setup that's writing to that URL.

**Expected behavior**
The build should continue to work, I guess.

**Comment by zachleat** [comment]
Maybe related to #2167

**Comment by zachleat** [comment]
Can we retest this with `2.0.0-canary.9`? Thank you!

**Comment by eatyourgreens** [comment]
Sure!

**Comment by eatyourgreens** [comment]
Builds are running successfully here:
https://github.com/zooniverse/science-gossip-data/pull/20

I think it’s fixed. Thank you!

**Comment by zachleat** [comment]
Yay!
