### ISSUE TITLE
Add easier way to import global data in Eleventy Edge

### ISSUE THREAD

**Issue by boehs** [11ty/eleventy#2339]
Proposed API is adding a new property to the edge plugin configuration specifying properties of the data object that should be included in precompiled app data

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!
