### ISSUE TITLE
Eleventy Edge build loops

### ISSUE THREAD

**Issue by stevenmilstein** [11ty/eleventy#2345]
**Problem**
1.  Follow the [Edge — Eleventy](https://www.11ty.dev/docs/plugins/edge/) documentation to the end
2. The terminal output after [5. RUN YOUR LOCAL SERVER](https://www.11ty.dev/docs/plugins/edge/#5.-run-your-local-server)  will be similar to: 
> 11ty-edge-demo@1.0.0 start
> netlify dev
◈ Netlify Dev ◈
◈ Ignored .env file env var: NETLIFY_SITE_ID (defined in process)
◈ Ignored build settings env var: NETLIFY_SITE_ID (defined in process)
◈ Ignored .env file env var: NETLIFY_AUTH_TOKEN (defined in process)
◈ Ignored build settings env var: NETLIFY_AUTH_TOKEN (defined in process)
◈ Ignored general context env var: LANG (defined in process)
◈ Using simple static server because '[dev.framework]' was set to '#static'
◈ Running static server from "sm-11ty-edge-demo/_site"
◈ Static server listening to 3999
   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   ◈ Server now ready on http://localhost:8888   │
   │                                                 │
   └─────────────────────────────────────────────────┘
◈ Loaded edge function eleventy-edge
[11ty] Wrote 1 file in 0.27 seconds (v2.0.0-canary.8)
[11ty] Watching…
4.  Modify & save index.liquid
5. The terminal output will loop over the following:
> [11ty] Wrote 1 file in 0.04 seconds (v2.0.0-canary.8)
[11ty] File changed: .netlify/edge-functions/import_map.json

**Solution**
1.  Use dev server watch folder by modifying netlify.toml from:
>[dev]
framework = "#static"
command = "npx @11ty/eleventy --quiet --watch"
[build]
command = "npx @11ty/eleventy"
publish = "_site"
[[edge_functions]]
function = "eleventy-edge"
path = "/*"

to:
>[dev]
framework = "#static"
command = "npx @11ty/eleventy **--input=src** --quiet --watch"
[build]
command = "npx @11ty/eleventy **--input=src"**
publish = "_site"
[[edge_functions]]
function = "eleventy-edge"
path = "/*"

2. Create folder `/src`
3.  Move `index.liquid` to `/src`
4. From the terminal, run the build `npx netlify dev`
6. The output should be similar to:
>
> 11ty-edge-demo@1.0.0 start
> netlify dev
◈ Netlify Dev ◈
◈ Ignored .env file env var: NETLIFY_SITE_ID (defined in process)
◈ Ignored build settings env var: NETLIFY_SITE_ID (defined in process)
◈ Ignored .env file env var: NETLIFY_AUTH_TOKEN (defined in process)
◈ Ignored build settings env var: NETLIFY_AUTH_TOKEN (defined in process)
◈ Ignored general context env var: LANG (defined in process)
◈ Using simple static server because '[dev.framework]' was set to '#static'
◈ Running static server from "sm-11ty-edge-demo/_site"
◈ Static server listening to 3999
   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   ◈ Server now ready on http://localhost:8888   │
   │                                                 │
   └─────────────────────────────────────────────────┘
◈ Loaded edge function eleventy-edge
[11ty] Wrote 1 file in 0.17 seconds (v2.0.0-canary.8)
[11ty] Watching…
[11ty] File changed: src/index.liquid
[11ty] Wrote 1 file in 0.02 seconds (v2.0.0-canary.8)

**Comment by zachleat** [comment]
Apologies for the late response here, I did end up correcting the documentation here. It was missing some `.gitignore` additions!

https://www.11ty.dev/docs/plugins/edge/#3.-additions-to-.gitignore

Adding an input folder that’s not root will also fix this (as you noted!)

**Comment by stevenmilstein** [comment]
@zachleat Thank you for the .gitignore help!
