### ISSUE TITLE
`render` tag in not parsing Liquid tags in content

### ISSUE THREAD

**Issue by patrulea** [11ty/eleventy#2347]
Using the `render` tag to render includes will not parse the Liquid templating inside them. `include`, on the other hand, works properly and serves the same functionality. Though, the latter is slowly being deprecated according to [LiquidJS documentation](https://liquidjs.com/tags/include.html).

###### /_includes/_nav.liquid

```
<span style="color: {{ site.color.text }}">
    Navigation
</span>
```

###### /index.liquid

```
{% render "_nav" %}

{% include "_nav" %}
```

###### /_site/index.html

```
<span style="color: ">
    Navigation
</span>

<span style="color: #00FF00">
    Navigation
</span>
```

### Environment

- macOS Monterey 12.3.1
- Eleventy 1.0.1

**Comment by pdehaan** [comment]
@patrulea I think that mean's it's working! 🎉 

Per https://liquidjs.com/tags/render.html

> ### Variable Scope
> When a partial template is rendered, the code inside it can’t access its parent’s variables and its variables won’t be accessible by its parent. This encapsulation makes partials easier to understand and maintain.

Basically, when you use the `{% render %}` tag, it won't inherit all variables automatically (like it does w/ the `{% include %}` tag), and you need to explicitly pass which variables you want into the partial.

So in this case, you could either pass the _entire_ `site` context to the rendered partial:

```liquid
---
title: 11ty-2347
---

<h1>{{ title }}</h1>

{% render "_nav" site: site %}

{% include "_nav" %}
```

Or you could just pass the one variable you want:

```liquid
{% comment %} index.liquid {% endcomment %}
{% render "_nav" textcolor: site.color.text %}
```

```liquid
{% comment %} _includes/_nav.liquid {% endcomment %}
<span style="color: {{ textcolor }};">
    Navigation
</span>
```

**Comment by patrulea** [comment]
Awesome! Thank you, Peter.
