### ISSUE TITLE
Add JSX Engine

### ISSUE THREAD

**Issue by dj** [11ty/eleventy#235]
Would you be open to a PR to include JSX as an engine? I think I get the gist for how one would be implemented, looking at the code (but would love any pointers on how to implement).

The idea would be to use [ReactDOMServer.renderToStaticMarkup()](https://reactjs.org/docs/react-dom-server.html#rendertostaticmarkup)

**Comment by zachleat** [comment]
Yeah! I think this would be useful.

Related, planning on making this easier in #117.

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

The enhancement backlog can be found here: https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+

Don’t forget to upvote the top comment with 👍!

**Comment by elbotho** [comment]
👍 
This might be a nice small solution without react:
https://github.com/developit/vhtml

**Comment by wommy** [comment]
how does react-static do it?

**Comment by ithinkihaveacat** [comment]
Here's an example of how to use JSX (or the TypeScript variant, TSX) with Eleventy via JavaScript templates (`*.11ty.js`):

https://github.com/ithinkihaveacat/eleventy-jsx

(It uses vhtml!)

**Comment by brkn** [comment]
I want to help with this issue @zachleat. I am not sure how to approach it though. Should it be done with `vhtml`? Can you point me to the docs about adding new handler?

**Comment by jhukdev** [comment]
I've managed to get JSX support using a simple `config.addTransform` method in the config file. 

The important bit is here:
https://github.com/jhukdev/11ty-setup/blob/master/.eleventy.js#L19

I'm using Preact in the repo above.

React has an `isValidElement` function that can be used to conditionally apply `render` to `React.createElement` calls (or `h()` for Preact).

Once that's setup you can return JSX from your `*.11ty.jsx` or `*11ty.tsx` files and it'll be handled for you.

I've only done this using TypeScript's JSX factory, but I'm sure you could replace that with a Babel transform / plugin.

**Comment by shadowtime2000** [comment]
This should probably support other JSX libraries such as [Preact](https://preactjs.com/), [Solid](https://solidjs.com/) or [Inferno](https://infernojs.org/).

**Comment by j-f1** [comment]
I used the new template language support of Eleventy v1.0 to make a plugin that enables JSX support using Babel and the excellent @unifiedjs&#x200b;/@rehypejs ecosystem. Check it out here: https://github.com/j-f1/eleventy-hast-jsx. My hope is that it will be pretty generic but let me know if you need it to do anything else!

**Comment by zachleat** [comment]
Official docs deploying to https://www.11ty.dev/docs/languages/jsx/ Shipping with 3.0.0-alpha.11

Very open to others adding alternate approaches there, via plugins or otherwise!

**Comment by penx** [comment]
> Official docs deploying to https://www.11ty.dev/docs/languages/jsx/ Shipping with 3.0.0-alpha.11
> 
> Very open to others adding alternate approaches there, via plugins or otherwise!


@zachleat I'm getting a bit lost trying to figure out how to import a CSS file when using JSX/TSX in v3 (either locally or from node_modules), I was hoping I could just `import "./test.css";` from my `index.11ty.tsx` template or a layout but I just get `Unknown file extension ".css"`.  I've tried adding the css bundle.

My eleventy.config.js is as follows

```js
import "tsx/esm";
import { renderToStaticMarkup } from "react-dom/server";

export default function (eleventyConfig) {
  eleventyConfig.addTemplateFormats("11ty.jsx,11ty.ts,11ty.tsx");
  eleventyConfig.addBundle("css");
  eleventyConfig.addExtension(["11ty.jsx", "11ty.ts", "11ty.tsx"], {
    key: "11ty.js",
    compile: function () {
      return async function (data) {
        let content = await this.defaultRenderer(data);
        return renderToStaticMarkup(content);
      };
    },
  });
}
```

Any ideas? Is there an example using JSX I could follow that would show this? Or an open issue I could follow? I have searched but am new to 11ty so perhaps I have overlooked something.

**Comment by zachleat** [comment]
@penx can you file a new issue for this? I think it’s more related to CSS bundling.

Though I think this might solve your DX issue: https://github.com/11ty/eleventy/pull/3573 and related future proposal https://github.com/11ty/eleventy/issues/3609
