### ISSUE TITLE
Does markdown in frontmatter get parsed?

### ISSUE THREAD

**Issue by anthmatic** [11ty/eleventy#236]
Using Netlify's markdown widget, I can set a frontmatter value with markdown content. However, it never seems to parse the MD into HTML.

page.md:
```yaml
---
my_field: |-
  ## This is a title

  This is a _sentence_
---
```
when printing out `{{ my_field }}` in my layout, I get:
```
## This is a title This is a _sentence_
```

**Comment by zachleat** [comment]
What is your layout file’s extension? If you use `.md` for your layout it should work correctly (but the transform will occur with the rest of the template content).

If you want to use a different extension and override the template language, you can per this documentation: https://www.11ty.io/docs/languages/

With the exception of `permalink`, no front matter gets template transformed prior to insertion into the template. There is a soon to be documented `renderData` feature which will template the content inside of it, so be on the lookout if that’s what you’re going for here. You can read more about `renderData` here: https://github.com/11ty/eleventy-base-blog/issues/15#issuecomment-420866273

**Comment by zachleat** [comment]
This is logged in #238—thanks!

You may also be interested in #148.

**Comment by danpantinople** [comment]
@anthmatic im having the same problem, where did you add the `templateEngineOverride: njk,md` ?

**Comment by anthmatic** [comment]
@danpantinople In my case, I added it to the frontmatter in the layout file:

**_includes/layouts/home.njk:**
```md
---
layout: layouts/base.njk
section: home
templateEngineOverride: njk,md
---
```

**Comment by zac-heisey** [comment]
@anthmatic @zachleat Hey guys! I've been running into this same issue with parsing both markdown and HTML inserted in a front matter field via Netlify CMS's markdown widget. I tried using @anthmatic's tip of `templateEngineOverride` in my page layout, but that only partially worked. It sort of parsed out the markdown in front matter fields, but it also broke the HTML parsing of the layout itself (basically the same problem mentioned [here](https://github.com/11ty/eleventy/issues/1243#issuecomment-651907618)).

Here's what I currently have:

**.eleventy.js**
```
module.exports = function(eleventyConfig) {

  return {

    markdownTemplateEngine: 'njk',
    dataTemplateEngine: 'njk',
    htmlTemplateEngine: 'njk'

  };

};
```

**_includes/layouts/page.njk**
```
---
layout: "layouts/base.njk"
templateEngineOverride: njk,md
---

<main id="main" role="main" data-page="{% if page.fileSlug == "" %}index{% else %}{{ page.fileSlug }}{% endif %}">

  {{ content | safe }}

</main>
```

**home.md**
```
---
title: Home
description: Home Description
order: 1
permalink: false
header:
  mainHeading: |-
    Good\
    Neighbor
  subHeading: Digital Solutions for Social Impact
  bgImage: https://images.unsplash.com/photo-1541738166768-2e00b3f3098a?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80
blocks:
  - type: content
    body: >-
      ## Your Digital Agency Next Door.


      We help purpose-driven brands and organizations solve problems through strategy, design, and technology. If your mission is to do good, we can help you do it better. Learn more about who we are and what we do.


      We believe in outcomes over deliverables , solutions over services, and people over profit. Take a look at some of our clients and projects to get a feel for the type of work we do. Ready to get to work on your next project? So are we.


      Welcome to the neighborhood.
---
```

**Comment by kylesloper** [comment]
@zac-heisey Just ran into this.. Any update on if you got it working?

**Comment by zac-heisey** [comment]
@kylesloper Yea, I installed [Markdown-It](https://www.npmjs.com/package/markdown-it) and then implemented the 'markdownify' filter that Brad Coffield outlines [here](https://github.com/BradCoffield/kidlitconnection/commit/e42a6dee1021be4b1869e4b62582230aed5db84e).

Check out the `/eleventy.js` and `_includes/partials/macros.njk` in my repo [here](https://github.com/zac-heisey/good-neighbor-agency) for an idea on how I was able to resolve the HTML/markdown parsing issue in my templates.

**Comment by kylesloper** [comment]
Thanks for the info I already found your repo and things worked until I realised I was applying `markdownify` to all content. Everything rendering properly now. Thanks for your help 👍

**Comment by zac-heisey** [comment]
@kylesloper No worries, glad you got things working!

**Comment by damianroiz** [comment]
Thank you for that insight, I cannot seem to find the issue that is causing my frontmatter data to parse on my .njk files, even after installing markdown-it. I think the problem comes from my eleventy.js file. Is there anything wrong in it ?

`//== Eleventy Config File ==//

module.exports = function(eleventyConfig) {

  // Add passthrough directories & files
  eleventyConfig.addPassthroughCopy('./src/style.css');
  eleventyConfig.addPassthroughCopy('./src/assets');

  /* Markdown-It 'markdownify' filter
   * source: https://github.com/BradCoffield/kidlitconnection/commit/e42a6dee1021be4b1869e4b62582230aed5db84e)
  */
  const md = require('markdown-it')({

    html: true,
    linkify: true,
    typographer: true,

  });

    eleventyConfig.addFilter('markdownify', (markdownString) =>
    md.render(markdownString)

  );

  // Manual passthrough template extensions
  return {
    dir: {
    input: "src",
    output: "public",
    markdownTemplateEngine: 'njk',
    dataTemplateEngine: 'njk',
    htmlTemplateEngine: 'njk'
    }
  };
};`

**Comment by pdehaan** [comment]
@damianroiz Seems to work for me (eleventy v0.12.1)

```njk
---
# src/index.njk
title: Eleventy is neat.
subtitle: "Like **SUPER** _neat_!"
---

<h1>{{ title }}</h1>
<h2>{{ subtitle | markdownify | safe }}</h2>
<p>Source: <cite>@pdehaan</cite></p>
```

```js
//== Eleventy Config File ==//

module.exports = function (eleventyConfig) {
  // Add passthrough directories & files
  eleventyConfig.addPassthroughCopy("./src/style.css");
  eleventyConfig.addPassthroughCopy("./src/assets");

  /* Markdown-It 'markdownify' filter
    source: BradCoffield/kidlitconnection@e42a6de)
  */
  const md = require("markdown-it")({
    html: true,
    linkify: true,
    typographer: true,
  });

  eleventyConfig.addFilter("markdownify", (markdownString) =>
    md.render(markdownString)
  );

  // Manual passthrough template extensions
  return {
    dir: {
      input: "src",
      output: "public",
    },
    markdownTemplateEngine: "njk",
    dataTemplateEngine: "njk",
    htmlTemplateEngine: "njk",
  };
};
```

### OUTPUT

```html
<!-- public/index.html -->
<h1>Eleventy is neat.</h1>
<h2><p>Like <strong>SUPER</strong> <em>neat</em>!</p>
</h2>
<p>Source: <cite>@pdehaan</cite></p>
```

In fact, looking closer at your .eleventy.js config, it looks like your `return` might be a bit mis-configured, although not sure if that is related to the question at hand. But I'll go fix it in my snippet above too.

```js
  // Manual passthrough template extensions
  return {
    dir: {
      input: "src",
      output: "public",
    },
    // Don't nest these under `dir` key.
    markdownTemplateEngine: "njk",
    dataTemplateEngine: "njk",
    htmlTemplateEngine: "njk",
  };
```

**Comment by pdehaan** [comment]
I guess also possibly worth pointing out here for future travellers, is that note how the `<h2>` has a nested `<p>`. I believe that's due to markdown-it's `.render()` vs `.renderInline()` (see https://github.com/markdown-it/markdown-it#simple). Specifically this bit:

> Single line rendering, without paragraph wrap:
> ```js
> var md = require('markdown-it')();
> var result = md.renderInline('__markdown-it__ rulezz!');
> ```

Changing the custom filter to use `.renderInline()` instead now gives us the following output:

```html
<h1>Eleventy is neat.</h1>
<h2>Like <strong>SUPER</strong> <em>neat</em>!</h2>
<p>Source: <cite>@pdehaan</cite></p>
```

Not that one is better than the other, just something to be aware of depending on your filter's use case.

**Comment by mitten** [comment]
It took me a while to make this work, so I thought I'd post the fix that fixed it, just in case anyone else is stuck:

In the Eleventy config file, I had to change
```
eleventyConfig.addFilter("markdownify", (markdownString) =>
    md.render(markdownString)
  );
```

to

```
eleventyConfig.addFilter("markdownify", (markdownString) =>
   return md.render(markdownString);
  );
```

(the "return" was missing)

Also, I had better luck with using  `md.renderInline` instead of `md.render` - in my use case, it stops text being double-wrapped in a p element.
