### ISSUE TITLE
Template data file tags are not overridden by frontmatter tags

### ISSUE THREAD

**Issue by AvidSeeker** [11ty/eleventy#2372]
**Describe the bug**
According to [doc](https://www.11ty.dev/docs/data-template-dir/), metadata of `posts/my-section/index.md` should overwrite data from `posts/my-section/my-section.json`, but that's not the case.

**To Reproduce**
In `posts/my-section/index.md`,
```markdown
---
tags: ["new-tag"]
---
test
```
In `posts/my-section/my-section.json`:
```json
{
  "tags": ["old-tag"]
}
```

**Expected behavior**
output of `index.md` should overwrite `old-tag` with `new-tag`. 

**Actual behavior**
output merges the two tags. So the post has `old-tag` and `new-tag`.

**Screenshots**
N/A

**Environment:**

- OS and Version: Windows
- Eleventy Version: 1.0.1

**Additional context**
Managed to successfully override `permalink`, and `layout`.

**Comment by zachleat** [comment]
Arrays are merged as part of the data fee merge feature. Prefix the tags key with `override:` to bypass this behavior on a per property basis. This is documented on https://www.11ty.dev/docs/data-deep-merge/
