### ISSUE TITLE
Overriding `md` with addExtension still reports `(liquid)` on the command line output

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#2386]
Via https://starfallprojects.co.uk/blog/markdoc-eleventy/#enabling-markdoc

We don’t have a unique key or name for these addExtension when overrides are in place, so maybe just say `(custom)`?

**Comment by zachleat** [comment]
3c49f22b31b10e5dae0daf661a54750875ae5d0f

**Comment by Snapstromegon** [comment]
One additional question would be, wether or not to always mark a custom engine as `(custom)` even on newly defined extensions (like .clowd).
I would say so.

**Comment by zachleat** [comment]
Fixed by #2481, shipping with 2.0.0-canary.19!

**Comment by zachleat** [comment]
cc @StarfallProjects whose blog post inspired this one!
