### ISSUE TITLE
--incremental runs a full build if the modified file is in a subdirectory (Windows)

### ISSUE THREAD

**Issue by kelstra** [11ty/eleventy#2400]
From the incremental doc page:

"If you create/update a template file, Eleventy will run the build for that file and only that file".

However, on Windows, the above seems to only hold true if the modified file is located at the project root. For example, ./README.md

If I modify any file in a subdirectory, Eleventy runs the build for all files.

I am testing with a minimal project based on https://www.11ty.dev/docs/getting-started/

My only addition is a third file, ./abc/def.md

I spent some time in the debugger and discovered that the variable **_this.incrementalFile_** contains backlashes. e.g. './abc\\\\def.md'

https://github.com/11ty/eleventy/blob/6ea19449c45dc024956d703161cb80a9bdfaa638/src/TemplateWriter.js#L201-L202

This causes incorrect comparison results in a couple of places. e.g.

https://github.com/11ty/eleventy/blob/6ea19449c45dc024956d703161cb80a9bdfaa638/src/EleventyFiles.js#L411-L420

'./abc/def.md' === './abc\\\\def.md' evaluates to false.

My temporary fix:

``` diff
diff --git a/old/eleventy-utils/src/TemplatePath.js b/eleventy-utils/src/TemplatePath.js
index 5b14890..7890b93 100644
--- a/old/eleventy-utils/src/TemplatePath.js
+++ b/eleventy-utils/src/TemplatePath.js
@@ -353,4 +353,16 @@ TemplatePath.normalizeOperatingSystemFilePath = function (filePath, sep = "/") {
   return filePath.split(sep).join(path.sep);
 };
 
+/**
+ * Accepts a relative file path that may be using a Windows directory separator
+ * and normalizes it using the POSIX separator.
+ * e.g. `.\\my\\dir\\` becomes `./my/dir/` on Windows
+ *
+ * @param {String} filePath
+ * @returns {String} a POSIX file path.
+ */
+TemplatePath.normalizePosixFilePath = function (filePath) {
+  return filePath.split(path.sep).join(path.posix.sep);
+};
+
 module.exports = TemplatePath;
```

``` diff
diff --git a/old/eleventy/src/Eleventy.js b/eleventy/src/Eleventy.js
index 0838915..c19fc11 100644
--- a/old/eleventy/src/Eleventy.js
+++ b/eleventy/src/Eleventy.js
@@ -871,7 +871,7 @@ Arguments:
     let watchDelay;
     let watchRun = async (path) => {
       try {
-        this._addFileToWatchQueue(path);
+        this._addFileToWatchQueue(TemplatePath.normalizePosixFilePath(path));
         clearTimeout(watchDelay);
 
         await new Promise((resolve, reject) => {
```

**Environment:**

- Windows 10
- v1.0.1 (the bug is also present in v2.0.0-canary.11)

**Comment by SiddharthSham** [comment]
This solution also has use in `eleventy-dev-server`  - (see [this](https://github.com/11ty/eleventy-dev-server/issues/35)). It might be useful to normalize all filepaths globally via the proposed `TemplatePath` utility.

**Comment by TigersWay** [comment]
`--incremental` runs a full build:
- if the modified file is in a subdirectory
- or the `input` is not the root folder

Both for Windows I cannot test anything else.

@pdehaan Would you mind to confirm this, please?

**Comment by pdehaan** [comment]
I don't have a Windows VM handy on my laptop, but this seemed to work for me w/ <kbd>--incremental</kbd> and <kbd>--serve</kbd> on macOS 12.6.

On a cold build, it writes both my pages.
After modifying src/pages/about.njk, it only seems to write that one modified file and ignores the unchanged src/index.njk.

```sh
npm run serve 

> 11ty-2400@1.0.0 serve
> eleventy --serve --incremental

[11ty] Writing www/index.html from ./src/index.njk
[11ty] Writing www/pages/about/index.html from ./src/pages/about.njk
[11ty] Benchmark      9ms  19%     2× (Configuration) "now" Nunjucks Shortcode
[11ty] Wrote 2 files in 0.05 seconds (v1.0.2)
[11ty] Watching…
[Browsersync] Access URLs:
 -----------------------------------
    Local: http://localhost:8080
 External: http://192.168.7.121:8080
 -----------------------------------
[Browsersync] Serving files from: www
[11ty] File changed: src/pages/about.njk
[11ty] Skipping www/index.html from ./src/index.njk
[11ty] Writing www/pages/about/index.html from ./src/pages/about.njk
[11ty] Wrote 1 file (skipped 1) in 0.01 seconds (v1.0.2)
[11ty] Watching…
[Browsersync] Reloading Browsers...
```

---

And I can repro similar behavior w/ canary channel:

```sh
npm run serve 

> 11ty-2400@1.0.0 serve
> eleventy --serve --incremental

[11ty] Writing www/pages/about/index.html from ./src/pages/about.njk
[11ty] Writing www/index.html from ./src/index.njk
[11ty] Wrote 2 files in 0.04 seconds (v2.0.0-canary.16)
[11ty] Watching…
[11ty] Server at http://localhost:8080/
[11ty] File changed: src/pages/about.njk
[11ty] Skipping www/index.html from ./src/index.njk
[11ty] Writing www/pages/about/index.html from ./src/pages/about.njk
[11ty] Wrote 1 file (skipped 1) in 0.01 seconds (v2.0.0-canary.16)
[11ty] Watching…
```

**Comment by TigersWay** [comment]
As said by others much before me the trouble is with the path separator... So deeper than the project root and only on *windows*!

**Comment by zachleat** [comment]
I did push some fixes related to this with #2258 for Windows compatibility with incremental. Can you retest with the latest on GitHub? I’ll milestone this to 2.0

**Comment by zachleat** [comment]
I also did merge #2628 for this too

**Comment by kelstra** [comment]
I can confirm that #2628 fixes this issue.

Thanks.

**Comment by zachleat** [comment]
Thank you @kelstra!
