### ISSUE TITLE
directory-based collection always misses a single post

### ISSUE THREAD

**Issue by pracplayopen** [11ty/eleventy#2404]
**Describe the bug**

Using a directory-based collection that looks like

```
src/news/news.json
src/news/2022/month/post-name/index.md <-- these posts do show up
src/news/2021/01/post-name/index.md  <-- this post does NOT show up in news collection (does show up in collections.all and on site permalink)
src/news/2021/02/post-name/index.md   <-- this post shows up in news collection
src/news/2020/month/post-name/index.md  <-- this post shows up in news collection
```

contents of news.json:

```
{
  "layout": "news",
  "tags" : ["news"]
}

```

**To Reproduce**

1. reproduce directory structure above
2. create a post called 'testit.html' with follow contents:

```
COLLECTIONS.ALL
<code>
{% for post in collections.all %}
        item: {{ post.data.title }} <br/>
{% endfor %}
</code>

<p/>

COLLECTIONS.NEWS
<code>
{% for post in collections.news %}
        item: {{ post.data.title }} <br/>
{% endfor %}
</code>


```

4. the first 2021 post doesn't show up in news, but does in all
5. Error still appears if remove/recreate public, restart 11ty, etc

**Expected behavior**

All posts in a directory should be treated the same.

**Screenshots**

**Environment:**

```
$ npx @11ty/eleventy --version
0.11.1
$ npx --version
8.6.0
$ node --version
v14.19.1

```
- OS and Version: [e.g. Windows/Mac/Linux]
- Eleventy Version [via `eleventy --version` or `npx @11ty/eleventy --version`]

**Additional context**

I checked the permissions for the files and directories that are missing, they are identical to those that are showing up.
And again... the files show up in permalink and on the site... just not in summary page for the collection.

**Comment by pracplayopen** [comment]
to check if there was a weird character, i copied content from bad file into a new file.
this worked.

then i noticed that this post had a slightly different front-matter:

````
title: PROBLEM POST
tags:
  - "post-custom-tag"
````

all the other posts had categories attributes rather than 'tags'.

this post started working if tags were removed, or if 'news' tag was added to tags.

doesn't the directory collection in news.json automatically apply those tags to every file in the directory?

is there no way to have additive-only tags in front-matter?

**Comment by pracplayopen** [comment]
the closest description to this found is the data cascade order :+1: 

https://www.11ty.dev/docs/data-cascade/

an extremely useful page and if tags is a single array, it makes sense it would be overriden by default.

presume one could create a shortcode or other fuction that would concat tags, but more than needed.

marking as fixed.

**Comment by pdehaan** [comment]
See also https://www.11ty.dev/docs/data-deep-merge/
Looks like you’re using a quite old version of 11ty, and would need to opt-in to data merging.

**Comment by pracplayopen** [comment]
@pdehaan 

thx i had seen this before but didn't think it applied since only installed 11ty a few weeks ago.

followed instructions here:  https://www.11ty.dev/docs/getting-started/

not sure how i could've ended up with such an old 11ty version following latest getting started.

**Comment by pracplayopen** [comment]
looking at version issue, it seems like npm automatically installed 0.11 because of vulnerabilities in your upstream dependencies.

will open another issue for that.

**Comment by pracplayopen** [comment]
deep data merge did make this work as originally expected: https://www.11ty.dev/docs/data-deep-merge/

we are not a node shop but was super confused that i could get this old a version by running standard getting started.

perhaps deep merge will fix some of other issues with collections....

almost certainly other new users are running on older versions by default tho bc of security vulnerabilities.

thx for quick response.
