### ISSUE TITLE
`write` Does not throw an error even if the build fails.

### ISSUE THREAD

**Issue by LeoArr** [11ty/eleventy#2405]
*Description*
`write` Does not throw an error even if the build fails. To have `write` throw could be an option passed to `Eleventy`.

*How to reproduce*
Have a 11ty project that fails when building. Then run:

```js
const eleventy = new Eleventy()
await eleventy
    .write()
    .then(() => {
         console.log("Always happens")
    })
    .catch((error) => {
        console.log("Never happens")
    })
```

**Comment by LeoArr** [comment]
A work-around is checking `write`'s output.  However I can't see why the build-step shouldn't throw.

```js
const result = await eleventy.write()
if (result.error) {
    /*...*/
}
```

**Comment by zachleat** [comment]
A few perhaps big changes here, upon closer inspection:

1. Running Eleventy via the programmatic API changed `process.exitCode` when it encountered an error. I think this is wrong and I’m going to change this behavior when you use the programmatic API specifically. It makes sense via the CLI.
2. I agree with you that Eleventy should `throw` errors when used programmatically. I’m making that change as well!

These will ship with `2.0.0-canary.12`
