### ISSUE TITLE
page.fileSlug is blank when filename is index.

### ISSUE THREAD

**Issue by edwardhorsford** [11ty/eleventy#241]
I had a use case where I wanted to know if I was on the main site index page.

My site index is `src/site/index.njk`. It has no permalink.

I tried to do:
`{% if page.fileSlug == 'index %}`, but `{{page.fileSlug}}` is blank for this file. I expected it to be `index`, just as for all other pages it returns the original filename without the extension.

---

It's probably not a good thing to be testing (I'm now testing `page.url` instead), but I feel like it being blank is a non obvious result.

**Comment by kleinfreund** [comment]
As per the documentation, this is intentional. It being blank is helpful to create useful permalinks for pagination like so: `permalink: {{page.fileSlug}}/index.html`

**Comment by zachleat** [comment]
Hmm, yeah as @kleinfreund stated, fileSlug was created explicitly for permalinks there and might not make sense for conditional testing like that.

Still, this is useful to have logged in the tracker in case someone else has the same issue.

You can find some of the original discussion around this feature here: https://github.com/11ty/eleventy/issues/75
