### ISSUE TITLE
config.addPassthroughCopy(`.nojekyll`) does not copy .nojekyll file to output folder

### ISSUE THREAD

**Issue by RichardJECooke** [11ty/eleventy#2413]
**Describe the bug**
In the screenshot below you can see I have
- a .nojekyll file in my input folder
- an addPassthroughCopy entry for it
- an output folder with a  missing .nojekyll file!

![image](https://user-images.githubusercontent.com/5468805/170977208-246c7ffd-cea6-4d06-b243-40a465178f79.png)

Furthermore, the other passthrough file, the google.html is being converted into a folder, like a normal template, instead of being passedthrough.

Finally, if I put an image into the media folder I get a build error that two different passthroughs are trying to copy the same file. But how else am I supposed to configure all images in any folder **and** all files in the media folder?

**To Reproduce**

- Add .nojekyll file to your input folder
- Add a passthrough config entry for it
- Build
- Missing file :(

**Expected behavior**
All files named in the config should be copied, even one with only a file extension

**Screenshots**
See above

**Environment:**

- WSL latest on Windows 10
- Eleventy Version 1.0.1

**Additional context**
Thank you!

**Comment by RichardJECooke** [comment]
Ok, if I change the config to 
```js
	config.addPassthroughCopy(`**/.nojekyll`); //stops github using jekyll on the files
	config.addPassthroughCopy(`**/google1515058ef76c5056.html`); //for google analytics
```
then it copies the files, but it ALSO incorrectly makes a google folder with an index.html.

**Comment by RichardJECooke** [comment]
> Shouldn't it be "./src/.nojekyll" (like your "./src/media/" command)?

Thanks, but that part works, it's the other problem now.

**Comment by RichardJECooke** [comment]
Thanks! So 1. and 2. aren't options, as my old blog had some html templates and some plain html files in various places in the source.

I'll look into what a permalink is. Didn't seem relevant when I was reading the tutorials.

Still also have the problem with images on passthrough `Finally, if I put an image into the media folder I get a build error that two different passthroughs are trying to copy the same file. `

**Comment by pdehaan** [comment]
Re: media files, I think you're seeing https://github.com/11ty/eleventy/issues/2174
I haven't played around with that much since I looked at the other bug, but not sure if it's possible to move your "./src/assets/" out of the input directory and then change your other passthrough copies from `**/*.jpg` to `src/**/*.jpg` style and see if that reduces the likelihood of the collisions.

**Comment by pdehaan** [comment]
Re: `permalink` on Google .html file,

I think you should be able to set this front matter in order to have Eleventy write **/google1515058ef76c5056.html** instead of **/google1515058ef76c5056/index.html**

```
---
permalink: "{{ page.filePathStem }}.html"
---
```

**Comment by RichardJECooke** [comment]
Ok, thank you if I remove the passthrough config and use the permalink you gave my html file is copied to the correct place, without duplication.

I'll close this bug and subscribe to the resolution of https://github.com/11ty/eleventy/issues/2174 to make my images work correctly.
