### ISSUE TITLE
.eleventyignore ignores node_modules folder of git submodules

### ISSUE THREAD

**Issue by idiazroncero** [11ty/eleventy#242]
Hello;

I'm stuck on a project for wich I use another GIT repo as a submodule. This repo sits inside the src/ folder of my eleventy project and ,as a separate project, it has its own package.json and its own node_modules.

When trying to compile using `yarn eleventy`, it parses and compiles *every .md file present on the node_modules folder of the submodule*, even if I try to use a .eleventyignore file to completely ignore the whole submodule. 

This is not what is intended. I realized it because it breaks when some .md on some node_module has some characters that throw an error.

Is this a bug or am I doing anything wrong?

Many thanks!

**Comment by idiazroncero** [comment]
`Problem writing eleventy templates (more info in DEBUG output):
 * Error: Having trouble compiling template ./src/huesos/node_modules/decode-uri-component/readme.md: # decode-uri-component`

This is the error. Of course, it shouldn't even  _try_ to parse that .md file.

**Comment by idiazroncero** [comment]
Yes, it was indeed #228 , sorry

**Comment by zachleat** [comment]
Don't apologize! This is good feedback. Any confusion is stuff we want to eliminate. Follow along at #228 to help us land in a good place 👍🏻
