### ISSUE TITLE
11ty runs the filters in incremental mode, even when they’re not needed

### ISSUE THREAD

**Issue by julientaq** [11ty/eleventy#2429]
Hi and thanks for the work on 11ty, amazing tool!

When using the incremental mode, if i update a css file (that is passed to the output through a passthrough copy), eleventy runs any filter used in the layout files. (they are big filters doing some jsdom stuff so they can be quite long). Making it quite hard to design. I looked around if someone had that issue, and asked on the discord, but i can’t find a way to make it work quicker.

**Expected behavior**
11ty only runs the filters when they are needed to produce a page.

**Screenshots**
```
... (a lot of skipped files like the line below)
[11ty] Skipping public/figures/fig.-9.html from ./src/content/figures/Fig-9.md (liquid)
[11ty] Benchmark   9340ms  60%    75× (Configuration) "updateBib" Nunjucks Filter
[11ty] Benchmark   3614ms  23%   110× (Configuration) "addID" Nunjucks Filter
[11ty] Copied 1 file / Wrote 0 files (skipped 261) in 15.58 seconds (v1.0.1)
[11ty] Watching…
[Browsersync] Reloading files that match: *.css
```

**Environment:**

- Mac osx 10.15.7
- Eleventy Version 1.0.1

**Comment by zachleat** [comment]
As a extra-safe default until #108 is implemented, all of the templates are rendered but not written to the file system

https://www.11ty.dev/docs/usage/incremental/

Incremental is still in progress! I’d subscribe to #108 as the home base for this—thanks!
