### ISSUE TITLE
Internationalization Example using JS Data Files

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#243]
https://www.11ty.io/docs/data-js/

Popular i18n libraries:
https://www.npmjs.com/package/messageformat
https://www.npmjs.com/package/i18next
https://www.npmjs.com/package/y18n

**Comment by rolandtoth** [comment]
How to deal with collections for multiple languages? By creating as many collections as the number of languages available? For example collection "news": news_en, news_de, news_fr, etc? 

It would be great if it would be possible to "pass" a language to a collection. Now you can loop over a collection and skip items that are not available at one language, but that would break pagination.

Perhaps there's an easy way - I haven't created a multilanguage site with Eleventy so far but this one comes to my mind as a problem.

**Comment by paulshryock** [comment]
Where is the internationalization example? I don't see it in the linked docs page, although I understand you're saying this can be done with a JS data file. If I wanted to use [y18n](https://www.npmjs.com/package/y18n), for example, is there any Eleventy-specific setup I would need to implement, aside from `npm install`ing y18n and following their documentation?

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for documentation requests. This means documentation issues will now be closed instead of leaving them open.

View [the documentation queue backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Areactions-%2B1-desc+is%3Aclosed+label%3Adocumentation+label%3Aneeds-votes). Don’t forget to upvote the top comment with 👍!

**Comment by hcavalieri** [comment]
@rolandtoth did you find a way to solve the multi-lang collections problem? I'm struggling with this as well 😥

**Comment by rolandtoth** [comment]
No, I had no ML project so far. Probably I would add a frontmatter property to each page, but I haven't tried yet.

**Comment by jeromecoupe** [comment]
Just chiming in for Internationalization and the possibility to have a single collection with multiple languages.

While not being my preferred approach (separate collections make more sense IMHO), you could do it by setting a `locale` key in your front matter for each lgg (I would also add a `translationKey` to create an explicit relation between all lgg versions of the same content items if you need a language switcher).

You can then create a [custom filter](https://github.com/jeromecoupe/eleventy_starter/blob/master/src/_filters/include.js) that you can use to filter any of those multilingual collections using the `locale` key.

As far as pagination go, you could use the [new `before` pagination parameter](https://www.11ty.dev/docs/pagination/#the-before-callback) to only get the data you want from that mixed languages collection.

I did a couple of multilingual websites with Eleventy using this type of setup

**Comment by Dexus** [comment]
Hi, I looking for this support also, becuase you should be able to cross link all languages of the same content. But with the currently support it's not possible to do somthing good with it.

**Comment by jeromecoupe** [comment]
@Dexus Did you have a look at using a translation key in the front matters of your linguistic versions of the same content ? I've used it in several projects and it works well, provided that you can educate the client team if they are maintaining the site

https://www.webstoemp.com/blog/language-switcher-multilingual-jamstack-sites/

**Comment by zachleat** [comment]
New on the docs here: https://www.11ty.dev/docs/i18n/

I’ll publish an i18n-friendly version of `eleventy-base-blog` after 2.0.0-canary.13 ships

**Comment by zachleat** [comment]
Code: https://github.com/11ty/eleventy-base-blog/tree/v2
Demo: https://v2--eleventy-base-blog.netlify.app

Examples for:
* URL scheme: Distinct URLs with implied default language, read more at https://www.11ty.dev/docs/i18n/#distinct-urls-using-implied-default-language
* Dictionary usage, including localized navigation using the [navigation plugin](https://www.11ty.dev/docs/plugins/navigation/)
* localized slugs e.g. https://v2--eleventy-base-blog.netlify.app/es/blog/cuarta-publicacion/
* Automated links to all other versions of the input page, read more: https://www.11ty.dev/docs/plugins/i18n/#locale_links-filter
* How to link to previous/next pages in the collection (locale aware), read more: https://www.11ty.dev/docs/plugins/i18n/#using-with-get*collectionitem-filters

via https://twitter.com/eleven_ty/status/1552415015424196608
