### ISSUE TITLE
liquid tries to process file name inside fenced code blocks

### ISSUE THREAD

**Issue by raffaelj** [11ty/eleventy#2455]
While fiddling with the render plugin and writing notes about bugs, I discovered the next bug. If I have a shortcode with a pathname inside fenced code blocks in markdown, the template engine (currently only tested with liquid/default) reads the path and throws an error, if that file doesn't exist.

**To Reproduce**

empty `.eleventy.js`, no render plugin activated.

`break-eleventy.md`

````md
`test.njk`:

```njk
{% render "path/to/file.njk", myData %}
```
````

run `npm run build`

error:

```text
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering liquid template ./break-eleventy.md (via TemplateContentRenderError)
[11ty] 2. ENOENT: Failed to lookup "path/to/file.njk" in "_includes,.", file:./break-eleventy.md, line:30, col:1 (via RenderError)
[11ty] 3. ENOENT: Failed to lookup "path/to/file.njk" in "_includes,." (via Error)
...
```

If I create `_includes/path/to/file.njk`, that file is rendered inside the code block and the build runs without error.

*edit*: #2453 also happens inside that processed file.

**Expected behavior**

Everything inside fenced code blocks should be ignored by preprocessing and just treated as code/text.

**Environment:**

- OS and Version: OpenSuse TumbleWeed, Node v16.14.2, but it also happens in a docker container with Alpine and Node 18.2.0
- Eleventy Version 2.0.0-canary.11

**Comment by zachleat** [comment]
I understand that this particular feature is confusing but it is by-design.

https://github.com/11ty/eleventy/issues/2434#issuecomment-1156772735

Workarounds at https://github.com/11ty/eleventy/issues/2434#issuecomment-1155346598 but most folks use `{% raw %}` here

**Comment by raffaelj** [comment]
Thanks for the hint. I forgot, that liquid needs raw tags and I wasn't aware, that nunjucks has the same behavior.

I'll stick with `markdownTemplateEngine: false` for now, because I want to separate content and layouts anyway.
