### ISSUE TITLE
Single tags treated as string rather than one item array

### ISSUE THREAD

**Issue by edwardhorsford** [11ty/eleventy#246]
I don't know if this is by design or if I've done something wrong, but it looks like if you have just a single tag on an item, it gets treated as a string rather than a 1 item array.

This means things go funny if you do `{% for tag in tags %}` - it will treat the string as an array of letters and page through each letter in turn.

For my personal site I added a filter to check if tags is an array - but it would be easier if it was one to begin with. It's a real pain not being able to do `{% for tag in tags %}` without first checking for one item.

Another case where it's come up: I'm attempting to recreate the [tags page](https://eleventy-base-blog.netlify.com/tags/) from the starter blog.
Here's what the starter blog looks like:
![screen shot 2018-09-20 at 17 40 35](https://user-images.githubusercontent.com/2204224/45833304-4c23df80-bcfc-11e8-928d-cb43813a3db1.PNG)
When I apply similar to my site, I get this:
![screen shot 2018-09-20 at 17 41 01](https://user-images.githubusercontent.com/2204224/45833322-5cd45580-bcfc-11e8-96d0-051ea2c0b0b3.PNG)
Rather than a single link for the tag 'design', it's created a link for each letter.

In this case, each of these items only has a single tag, applied like this:
![screen shot 2018-09-20 at 17 41 33](https://user-images.githubusercontent.com/2204224/45833384-6d84cb80-bcfc-11e8-84ed-6e4d92baabc1.PNG)

**Comment by kleinfreund** [comment]
front matter is YAML and writing `tags: design` tells YAML that the property `tags` is assigned the value `design` which it reads as a string. You want to define it as an array:

```yaml
tags:
- design
```

**Comment by edwardhorsford** [comment]
I thought it might be something like this. I don't think it's very intuitive though. 
The docs suggest the format 
`tags: design` - this feels like something other users are likely to trip up on too.

**Comment by kleinfreund** [comment]
Uh, okay. You should *always* be able to iterate over something like tags. It’s a plural and implies that there might be one to many items in it. Thus, it always needs to be a collection. `tags: post` is a scalar value, not a collection. You can’t logically iterate over it.

Eleventy uses `tags` as a special front matter property to automatically create collections for each tag. There has to be some internal logic distinquishing between it being a collection or just one element.

I don’t like that, to be honest.

I’d suggest always using collections for things that can potentially include more than one thing. If you know there won’t be a second item, then it’s not a collection and then you would never want to iterate over it anyway.

**Comment by edwardhorsford** [comment]
I think you may be thinking of a different use case. I'm not talking about a single tag used once, but about many pages all having only a single tag. If any one of those pages tries to iterate over it's tags, it breaks.

I have several pages with the tag 'design'. And several pages with the tag 'photography' - right now I'm using collections precisely to group the design posts together and photography posts together. So far so good. Some of the pages may also have other tags.

Now within any page, I want to iterate over the tags for that page - I can't do that now because that page has a single tag (using frontmatter format `tags: tag`), it breaks.

Since eleventy has chosen tag to be a reserved keyword that has extra magic, it feels worth it doing the hard work here.

Any developer can't rely on doing `{% for tag in tags %}` on any page if there's the chance that *any* page has just a single tag. This is rather risky if the authors are not the same as the developers. That it still works for collections is all the more reason I feel it should be an array.

**Comment by kleinfreund** [comment]
I understood you perfectly well. If you want to iterate over tags, your tags need to be iterable. A scalar property like `tags: design` isn’t, `tags: ['design']` is.

**Comment by edwardhorsford** [comment]
Cool, glad we're on the same page.

I'm clear how to fix it for my case - but would like to suggest the current behaviour is risky, particularly for blogs where authors aren't developers.

As an example, here's the [starter blog with a page with a single tag](https://master--serene-dubinsky-354c8d.netlify.com/).
![screen shot 2018-09-20 at 18 23 47](https://user-images.githubusercontent.com/2204224/45835557-55b04600-bd02-11e8-98de-9324262598fb.PNG)
If tags are treated as a special item (collections are really helpful), we should go the whole way and protect against things like this.

**Comment by zachleat** [comment]
Yeah @edwardhorsford that was a thing I added trying to be helpful but it’ll likely end up to be more confusing than necessary. I think what should happen is that if it finds a scalar it should convert to an array behind the scenes, rather than attempt to work with both transparently.

**Comment by kleinfreund** [comment]
That feels like patching YAML with convenience features. Why not just remove it completely?

**Comment by edwardhorsford** [comment]
> That feels like patching YAML with convenience features. Why not just remove it completely?

This is one of a few eleventy specific features though, it's not pure YAML (IMHO). Similar to how permalinks is a special function.

**Comment by zachleat** [comment]
Well, my preference _now_ would be to remove it and we can add a ticket for this removal for discussion, but that’d be a breaking change and it may not be worth it. At the very least, it’d have to go into the next major version 1.0.

**Comment by zachleat** [comment]
Major breaking change discussion/enhancement issue surfaced at #251.

**Comment by zachleat** [comment]
In 0.5.4, Tags will always return an array, even if a single string is passed in.

This will solve most of the resulting issues but keep backwards compatibility.
