### ISSUE TITLE
Feature request: let data files append to existing data

### ISSUE THREAD

**Issue by edwardhorsford** [11ty/eleventy#247]
Right now, anything set in an item's front-matter will override existing values set in a `.json` data file. It would be useful if `.json` data files could set things that get appended as well.

I'd like to be able to use `.json` data files for common metadata to be added to a group of items. This essentially lets me use a folder structure to enforce some of the metadata applied. It also means each individual item has less they need to set, and are more consistent.

For instance, I might want the same classes to be applied to a bunch of items, or the same tags. Rather than adding them all to each post, I can just declare them once.

---

For example, all items in the folder `posts/` with `/posts/posts.json` could have the tag `post` applied. Any item in the `posts/` folder automatically gets the `post` tag. I'd then like individual posts in that folder to be able to declare their own tags - the stuff that's unique for that item - and for those to append to the whatever `posts/posts.json` added.

I don't necessarily have a good suggestion for how this could work, other than that I feel it might be helpful. Equally it could make things too complex.

I suspect I could work around it with `renderData: tags`, but this would need to be applied to every post individually - I'm wary as this adds complexity to a whole lot of post pages.

One idea for `.json`:
```
{
  "permalink" : "/{{page.fileSlug}}/",
  "+tags" : "post"
}
```

Alternate idea:
```json
default : {
  "permalink" : "/{{page.fileSlug}}/",
  "category" : "design"
},
append : {
 "tags" : "post"
}
```

---

I'd be very open for other suggestions for doing this too.

**Comment by zachleat** [comment]
@edwardhorsford does this seem like a duplicate of #147?

**Comment by zachleat** [comment]
I like your `"+tags"` syntax!

**Comment by edwardhorsford** [comment]
Yes, that's **exactly** the sort of thing. I'll move the discussion over there.
