### ISSUE TITLE
How to create sitemap.xml?

### ISSUE THREAD

**Issue by rolandtoth** [11ty/eleventy#248]
Could you provide some hint on how to create a sitemap.xml automatically?

**Comment by paulrobertlloyd** [comment]
Hi @rolandtoth. I’ve created one for my (yet un-launched) site. You can use a template like the following (this uses liquid, but the idea works regardless of template format):

```liquid
---
permalink: /sitemap.xml
---
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
{%- for item in collections.all %}
{%- unless item.data.ignore == true %}
  <url>
    <loc>https://example.com{{ item.url }}</loc>
    <lastmod>{{ item.date | date: '%Y-%m-%d' }}</lastmod>
    <changefreq>{{ item.data.changefreq }}</changefreq>
    <priority>{{ item.data.priority }}</priority>
  </url>
{%- endunless %}
{%- endfor %}
</urlset>
```

For this to work, you’ll need to create a collection (I’ve used `collection.all`) that encompasses all the files you want in your sitemap ([see the documentation](https://www.11ty.io/docs/collections/#getall()) on how to achieve this). You’ll also want to ensure pages have priorities and change frequencies set. I do this by using [directory specific data files](https://www.11ty.io/docs/data-template-dir/), to save adding this to every page I create. Here’s an example for my articles:

```json
{
  "layout": "layouts/article",
  "permalink": "{{ page.date | date: '%Y/%m' }}/{{ page.fileSlug }}.html",
  "changefreq": "monthly",
  "priority": "0.9"
}
```

For other pages, just set the same values in your frontmatter, like so:

```yaml
---
title: 'My great page'
permalink: /path/to/index.html
changefreq: weekly
priority: 1
---
Hello, and welcome to my great page!
```

I also allow pages to be excluded from the sitemap if they have the value `hidden` set to `false`. For example, here’s my 404 page:

```
---
title: '404 - Page Not Found'
layout: layouts/page
permalink: /404.html
ignore: true
---
```

Hope this helps!

**Comment by edwardhorsford** [comment]
Thanks, this looks really useful too! 

Possibly a good candidate for the tutorials section.

**Comment by edwardhorsford** [comment]
@rolandtoth I'm curious what your `valueIfEmpty('foobar')` filter is doing. 

Why not just do `{{ item.data.changefreq | "monthly" }}`?

**Comment by rolandtoth** [comment]
It's a filter I created for nunjucks so that if the variable I apply on doesn't exist then it will use this (or these) values. I tried using your suggestion but the build failed ("Template render error").

```javascript
module.exports = function () {
    for (arg of arguments) {
        if (arg) {
            return arg;
        }
    }

    return false;
};
```

It's not too sophisticated but so far so good. It accepts multiple values, eg. for the SEO description I use something like this:

```
{{ seo_description | valueIfEmpty(excerpt, title) }}
```

So if the frontmatter seo_description is not set, it will try other frontmatter data (excerpt and title) and outputs the first that has value.

**Comment by edwardhorsford** [comment]
Oops, I got my syntax wrong. What I wanted to suggest was this:
`{{ item.data.changefreq or "monthly" }}`

For your case I'm pretty sure you could do: 
`{{ seo_description or excerpt or title}}`

**Comment by edwardhorsford** [comment]
@zachleat is `collections.all` documented? I hadn't seen it. It's not mentioned on the collections page. It's [used](https://www.11ty.io/docs/permalinks/) on the permalinks page.

I'd assumed that since collections group things together by tag, that a tag would be required for it to ever appear. The `collections.all` method is great.

**Comment by rolandtoth** [comment]
@edwardhorsford 

Thanks for the "var1 or var2" syntax, it works. However, if you apply a filter on it, you need to put them in parenthesis, otherwise the filter will be applied to the last item only.

`<lastmod>{{ (item.data.premier.date or item.date) | dateDisplay("toISOString") }}</lastmod>`

**Comment by mathiasbynens** [comment]
Here’s how I did it for v8.dev: https://github.com/11ty/eleventy-base-blog/pull/22 (before I saw this thread)

**Comment by rolandtoth** [comment]
Sorry, I don't have pagination in any project where I have sitemap :)

**Comment by zachleat** [comment]
@edwardhorsford per your comment here https://github.com/11ty/eleventy/issues/248#issuecomment-423777166 it looks like no!  I’ve filed https://github.com/11ty/11ty.io/issues/21

**Comment by zachleat** [comment]
@rolandtoth ah, you might have gotten bit by #253?

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for documentation requests. This means documentation issues will now be closed instead of leaving them open.

View [the documentation queue backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Areactions-%2B1-desc+is%3Aclosed+label%3Adocumentation+label%3Aneeds-votes). Don’t forget to upvote the top comment with 👍!

**Comment by Ryuno-Ki** [comment]
@zachleat Where would you like to see this documented?
I've played around with the tips here and have a working sitemap.xml (for my use case).
So I could open a PR if you tell me, where the file should go to.

I assume, in the docs folder of https://github.com/11ty/11ty.io ?

**Comment by hirusi** [comment]
> per #253, if you're using pagination, are pages that are generated showing up in your sitemap? I found `collections.all` was not listing all the pages.

Additionally, pages generated dynamically such as [tag pages](https://www.11ty.dev/docs/quicktips/tag-pages/) also seem to be hit or miss when it comes to the sitemap.
