### ISSUE TITLE
For-free emulated passthrough copy not working with --incremental

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#2491]
On 2.0.0-canary.12

**Comment by brycewray** [comment]
And still in 2.0.0-canary.15, correct? (In my case, seeing in dev mode even without `--incremental`.)

**Comment by TigersWay** [comment]
Just realized that. Still not working with 2.0.0-canary.15
 `eleventyConfig.setServerPassthroughCopyBehavior("copy");` makes it work, so configuration seems ok!

**Comment by TigersWay** [comment]
@zachleat In fact, it's not even working today back with 2.0.0-canary.12. 
I know I personally made tons of tests on that canary.12 and everything was working great back then.
But there's one big difference and I kinda hope it will tell you everything :smile:
- When eleventy@2.0.0-canary.12 went out, it came with eleventy-dev-server@1.0.0-canary.13
- Today, it's coming with eleventy-dev-server@1.0.0-canary.14

[13..14](https://github.com/11ty/eleventy-dev-server/compare/7032fa8..57e4e3b)

**Comment by azangru** [comment]
Not working with incremental in 2.0.0-canary.15. [This](https://github.com/11ty/eleventy/blob/master/src/TemplatePassthroughManager.js#L247) seems to be the line that causes Eleventy to forget all passthrough paths if an incremental file is changed:

<img width="594" alt="Screenshot 2022-09-18 at 15 47 31" src="https://user-images.githubusercontent.com/6834224/190913074-3caf953e-b960-4046-8f6f-dc86fffef0e2.png">

**Comment by zachleat** [comment]
Fix shipping with 2.0.0-canary.19
