### ISSUE TITLE
Edge Functions and // fetch() is supported natively by Deno!

### ISSUE THREAD

**Issue by stevenmilstein** [11ty/eleventy#2500]
After trying to import `node-fetch` to an Edge Function, I eventually stumbled upon:

`// fetch() is supported natively by Deno!`
in [edge-functions-examples/image-external.ts at b50cb0b330c6ea730887bdba6501777196ac2791 · netlify/edge-functions-examples](https://github.com/netlify/edge-functions-examples/blob/b50cb0b330c6ea730887bdba6501777196ac2791/netlify/edge-functions/image-external.ts#L6)

I certainly got lucky on that one!  But what if I was trying to import another package? It looked like adding the package to `edge-functions-import-map.json`, or `import_map.json` would be the way to go, but they get generated whenever `netlify dev` is run.

Is there a way to import other npm packages?

**Comment by joepavitt** [comment]
Did you ever get a solution to this Steven? Hitting the same issues

**Comment by zachleat** [comment]
Per the Eleventy Community Survey results and our refocus and prioritization towards our roots as a static site generator, we’re going to be deprecating Edge in 3.0 and closing issues related to the Edge plugin. I’m very sorry to have to do this—but unfortunately this was a necessary decision to allow the project to continue forward.

Read more:
https://www.zachleat.com/web/eleventy-side-project/
https://www.11ty.dev/blog/community-survey-results/
