### ISSUE TITLE
Edge shortcode not working in include files?

### ISSUE THREAD

**Issue by slegay** [11ty/eleventy#2508]
**Describe the bug**
Whenever and edge shortcode is added to a njk include file, none of the contents of the file show up in the output

**To Reproduce**

1. Create a njk file with edge shortcode and some content
2. Create a njk template that includes the above file
3. Render the template
4. None of the contents of the include file shows up

**Expected behavior**
I would expect the edge shortcode to behave the same in a layout file, template file or partial / include

**Environment:**

- OS and Version: Linux
- Eleventy Version 2.0.0-canary.13

**Comment by slegay** [comment]
Actually I think it has something to do with the set shortcode, will need more testing,

**Comment by aqilusman45** [comment]
Hi @slegay, were you able to solve this?
