### ISSUE TITLE
Use Transforms for pathPrefix URL transformations

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#2535]
We already use `posthtml-urls` in the RSS plugin to implement this same functionality.

This would simplify a lot of things:

1. Allow folks to remove almost all cases of using the `url` filter (maybe also alias `url` as `addPathPrefix`) not requiring folks to remember to add this to URLs they want to be transformed.
1. Delete extra `url` filter stuff from the Navigation plugin
1. Simplify the i18n plugin stuff (alleviating filter ordering concerns) see #2532

**Comment by TigersWay** [comment]
Just waking up and trying to catch up :upside_down_face:
I love the idea but not sure yet how it's gonna impact all cases I had in mind.

I guess I'll wait coffee and documentation!!

**Comment by zachleat** [comment]
This shipped! https://www.11ty.dev/docs/plugins/html-base/

**Comment by zachleat** [comment]
v2.0.0-canary.15
