### ISSUE TITLE
Does `permalink:"{{ title | slugify }}"` support multi-byte languages like Japanese?

### ISSUE THREAD

**Issue by bissy** [11ty/eleventy#2537]
I set post like below.

**こんにちは.md**
```
title: こんにちは
permalink: "/article/{{ title | slugify }}"
---
```
**hello.md**
```
title: hello
permalink: "/article/{{ title | slugify }}"
---
```

And then, hello.md compiled `/article/hello/index.html`
but こんにちは.md is compiled `/article/index.html`.

Is this issue of slugify? or other issue?

**Comment by pdehaan** [comment]
I believe that is Japanese, correct?
Looking at https://www.11ty.dev/docs/filters/slugify/ (which points me to [@sindresorhus/slugify](https://www.npmjs.com/package/@sindresorhus/slugify)), which _then_ points me towards https://github.com/sindresorhus/transliterate#supported-languages as a list of supported languages. And then https://github.com/sindresorhus/transliterate/issues/1 says that there is currently no support for languages like Chinese, Japanese, Thai, etc.

One workaround might be using the page's filename instead of slugifying the title, if that works.

```js
---
title: こんにちは
permalink: "/article/{{ page.fileSlug }}/"
---

<h1>{{ title }}</h1>
```

**Comment by pdehaan** [comment]
I also found https://github.com/lovell/limax which seems to support Japanese; if you were looking for translated slugified strings.

```js
// Overwrite the built-in `slugify` filter.
eleventyConfig.addFilter("slugify", require("limax"));
```

### src/こんにちは.md
```liquid
---
title: こんにちは
permalink: "/article/{{ title | slugify }}/"
---

<h1>{{ title }}</h1>
```

### OUTPUT
```sh
> eleventy

[11ty] Writing www/article/konnichiha/index.html from ./src/こんにちは.md (liquid)
[11ty] Wrote 1 file in 0.06 seconds (v1.0.2)
```

I'm not sure if that's transliterating correctly, but&hellip; maybe?

**Comment by bissy** [comment]
@pdehaan Thank you sooo much!!

>One workaround might be using the page's filename instead of slugifying the title

`permalink: "/article/{{ page.fileSlug }}/"`

I tried this, and works fine!
Thank you!

**Comment by bissy** [comment]
@pdehaan 
Now, still I confusing..
I can not use Japanese language tag.
e.g.
`tags: ["cat","dog"]` => compiled!
`tags: ["ねこ","犬"]` => failed!

How should I do?

**Comment by pdehaan** [comment]
This seems to work for me in eleventy@1.0.2.


### src/こんにちは.md
```liquid
---
title: こんにちは
permalink: "/article/{{ title | slugify }}/"
tags: ["ねこ","犬"]
---

<h1>{{ title }}</h1>
```

### src/index.md
```liquid
---
title: multibyte 犬 test
---

<h1>collections['犬']</h1>

{% for p in collections['犬'] %}
title={{ p.data.title }}
{% endfor %}
```

### OUTPUT
```html
<h1>collections['犬']</h1>
<p>title=こんにちは</p>
```

**Comment by bissy** [comment]
@pdehaan 

Thank you for your help!

I'm  using [eleventy-base-blog](https://eleventy-base-blog.netlify.app/), 
and I found this.
　
In tags.njk, I change code below.
`permalink: /ja/topics/tags/{{ tag | slugify }}/`
↓
`permalink: /ja/topics/tags/{{ tag }}/`

And now, "猫" tag is working fine.

**Comment by zachleat** [comment]
Pushed some warnings and guidance for this to https://www.11ty.dev/docs/filters/slugify/

Thanks y’all!
