### ISSUE TITLE
v2.0 Dev Server options need better names

### ISSUE THREAD

**Issue by Zearin** [11ty/eleventy#2550]
I was [reading about the upcoming Dev Server in v2](https://www.11ty.dev/docs/dev-server/), and I noticed some issues with the option names.  

I’ll go through the options that raised my eyebrow one by one:

----

```js
// Opt-out of the live reload snippet
enabled: true,
```

Nothing in this option name says anything about live reload.  

Put another way: Could you tell what this option does from `eleventyConfig.setServerOptions({ enabled: true })`?  

To me, it looks like you are simply enabling the server.

I recommend something like `enableLiveReload: true` instead.

----

```js
// Opt-out of DOM diffing updates and use page reloads
domdiff: true,
```

This is a trivial nitpick, but when all other options are camelCase, my brain wants this option to be `domDiff` so that it matches.

----

```js
// Show local network IP addresses for device testing
showAllHosts: false,
```

This option name is decent, but I think something a little more specific would be even better (e.g., `showLocalHosts` or `showLocalDevices`).

----

```js
// Change the name of the special folder name used for injected scripts
folder: ".11ty",
```

This option has the same issue as `enabled`.  What does `eleventyConfig.setServerOptions({ folder: '.11ty' })` tell you?  I would probably read that and think it is setting the root folder to serve files from.

Additionally, since specifying folders is a really common configuration option, I recommend something like:

```js
folder: {
    injectedScripts: ".11ty",
    // ... future folder-related configuration options can be added to `folder`
}
```

**Comment by jeromecoupe** [comment]
As these suggestions are related to [eleventy-dev-server](https://github.com/11ty/eleventy-dev-server), posting this in the corresponding repository would give them more visibility, IMHO.

**Comment by zachleat** [comment]
Ah, thanks for refiling! Closing this one—future visitors please subscribe to https://github.com/11ty/eleventy-dev-server/issues/41
