### ISSUE TITLE
How to generate a collection of shortcode calls (e.g. as a site index)

### ISSUE THREAD

**Issue by behoppe** [11ty/eleventy#2565]
I am building a documentation website for an open-source technology, and the site features a glossary of technical terms. I have created a shortcode `{% defn "term" %}` that outputs an italicized link to the appropriate term in the glossary. There are multiple contributors writing documentation and invoking `defn` links to terms that may or may not actually be included in the current glossary. I would like to create a collection of all the terms that have been used as arguments for `defn`, ideally along with the pages that are associated with each term. Is there a way to do this?

**Describe the solution you'd like**
Just as the Eleventy base blog shows a list of tags, and for each tag shows the associated pages, I hope for something in Eleventy (presumably a collection) that is keyed not on front matter but on shortcodes and their arguments.

**Describe alternatives you've considered**
If necessary, I guess I will write a Python script (or similar) to re-parse my content and provide the diagnostic information I seek.

PS: I am pretty new to Eleventy and a rookie with Javascript. Thank you!

**Comment by Snapstromegon** [comment]
Quick question:
Do you have your "glossary definitions" in a data file and is each definition a seperate page in a glossary directory or are all combined into one output file?

I think what you're trying to do should be possible - if not directly with 11ty, definetly with a plugin.

**Comment by behoppe** [comment]
Thanks @Snapstromegon for your question. To some extent I have it both ways. I have a `/src/doc/reference/glossary` folder in which each term is a file that generates its own page (e.g., `https://mysite.org/doc/reference/glossary/atomic/`), and I also have a `glossary.md` file that programmatically outputs one page with every term under its own header. The headers generate anchor tags and provide another way to see each term (e.g., `https://mysite.org/doc/reference/glossary/#atomic`) -- in the context of the entire list. The part I'm wanting is an inventory of how the `defn` tag gets used throughout the rest of the site. I look forward to hearing more of your thoughts on this.

**Comment by pdehaan** [comment]
Or, this jungle of code might get you close(r).

Basically:
1. loops over every post in `collections.all`
2. parses the [raw?] template contents
3. extracts any `{% defn ... %}` tags (using a questionable [regular expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Groups_and_Backreferences))
4. loops over any matches and extracts the trimmed and de-quoted `term` and `text` arguments
5. returns an array of objects which include `url`, `term`, `text` properties

```js
  eleventyConfig.addCollection("defns", function (collectionApi) {
    const res = [];
    for (const post of collectionApi.getAll()) {
      // see https://github.com/11ty/eleventy/discussions/2153, re: "Tried to use templateContent too early".
      const defs = post.template.frontMatter?.content.trim().matchAll(/{% defn (?<value>.*?) %}/gi);
      for (const { groups } of defs) {
        const [ term, text ] = groups.value.split(",").map(s => s.trim().replace(/"/g, ""));
        res.push({ url: post.url, term, text });
      }
    }
    return res;
  });
```

### OUTPUT
```json
[
  {
    "url": "/doc/tutorials/introduction-to-cilk-programming/",
    "term": "parallel algorithms",
    "text": "Parallel programming"
  },
  {
    "url": "/doc/tutorials/introduction-to-cilk-programming/",
    "term": "OpenCilk"
  },
  {
    "url": "/doc/tutorials/introduction-to-cilk-programming/",
    "term": "Cilk"
  },
  {
    "url": "/doc/tutorials/introduction-to-cilk-programming/",
    "term": "logical parallelism"
  },
  {
    "url": "/doc/tutorials/introduction-to-cilk-programming/",
    "term": "fork-join parallelism"
  },
  {
    "url": "/doc/tutorials/introduction-to-cilk-programming/",
    "term": "spawning"
  },
  {
    "url": "/doc/tutorials/introduction-to-cilk-programming/",
    "term": "parallel loops"
  },
  {
    "url": "/doc/tutorials/introduction-to-cilk-programming/",
    "term": "Cilksan"
  },
  {
    "url": "/doc/tutorials/introduction-to-cilk-programming/",
    "term": "scalability"
  },
  {
    "url": "/doc/tutorials/introduction-to-cilk-programming/",
    "term": "Cilkscale"
  },
  {
    "url": "/doc/tutorials/introduction-to-cilk-programming/",
    "term": "syncing",
    "text": "synced"
  },
  {
    "url": "/doc/tutorials/introduction-to-cilk-programming/",
    "term": "nested parallelism"
  },
  {
    "url": "/doc/tutorials/introduction-to-cilk-programming/",
    "term": "child"
  },
  {
    "url": "/doc/tutorials/introduction-to-cilk-programming/",
    "term": "parent"
  },
  {
    "url": "/doc/tutorials/introduction-to-cilk-programming/",
    "term": "continuation"
  },
  {
    "url": "/doc/tutorials/introduction-to-cilk-programming/",
    "term": "data race"
  },
  {
    "url": "/doc/tutorials/introduction-to-cilk-programming/",
    "term": "serial projection"
  },
  {
    "url": "/doc/reference/glossary/child/",
    "term": "parent"
  },
  {
    "url": "/doc/reference/glossary/computation-dag/",
    "term": "parallel trace"
  },
  {
    "url": "/doc/reference/glossary/complete-step/",
    "term": "greedy scheduler"
  },
  {
    "url": "/doc/reference/glossary/complete-step/",
    "term": "incomplete step",
    "text": "incomplete"
  },
  {
    "url": "/doc/reference/glossary/critical-path/",
    "term": "span"
  }
]
```

**Comment by behoppe** [comment]
Thank you very much @pdehaan. Both of those approaches help, and I tried the "jungle of code" successfully. I think now is the time for me to actually learn some Javascript! With apologies for a possibly simple question, I'm trying to understand how to use the result of the `defns` "collection," because it seems to be an array (`[ ]`) which therefore does not like it when I try methods such as `collections.defns.getFilteredByTag("race condition")`.

To arrive at my index of `term`s, shall I convert `res` from an array into a collection, and then use collection methods? Or would it be better to work directly with the array? I am guessing that converting to a collection is the more "Eleventy" thing to do?

**Comment by pdehaan** [comment]
> I'm trying to understand how to use the result of the `defns` "collection,"

:shrug: I just tried to mimic the behavior of other collections (array of pages). You can adjust to whatever format/structure works best for your use case.
But yes, `collections.defns.getFilteredByTag("race condition")` wouldn't work since `collections.defns` currently returns an array, and `.getFilteredByTag()` API is only available on collection objects (which isn't the right word, but whatever the proper name for that `collectionApi` object would be in `eleventyConfig.addCollection("defns", function (collectionApi) {...})`).

Perhaps the easier question is what you're trying to do w/ the collections and filtered "race condition". Are you just trying to find all pages tagged w/ `"race condition"`? If so we could probably loop over all pages and use a filter to only display/return pages w/ certain tags. Or possibly use some `collections.race_condition` tagging.

**Comment by Snapstromegon** [comment]
@behoppe Sadly the solution I had in mind at first is blocked on #2135 (shortcodes don't have access to the pages data) and the fact that there is no way to setup dependencies between pages.

The best way I've found right now that does not depend on scanning the content of all other pages (e.g. via regex) is not able to generate a page via eleventy, but can only print out the usage to the console or a file manually and requires you to pass the definitions into the shortcode every time you use them and to have the definitions in a data file / somehow available in 11ty data.

<details>
<summary>Example .eleventy.js of my solution</summary>

```js
module.exports = function (eleventyConfig) {
  const usedDfns = new Map();
  const missingDfns = new Map();
  let definitionsCache = undefined;

  // Make sure everything is clean before the build starts
  eleventyConfig.on("eleventy.before", function () {
    usedDfns.clear();
    missingDfns.clear();
    definitionsCache = undefined;
  });

  // Fill usage data during build
  eleventyConfig.addShortcode("dfn", function (word, definitions) {
    // First call?
    if (!definitionsCache) definitionsCache = definitions;

    // definition is missing?
    if (!(word in definitions)) {
      // missing!
      if (!missingDfns.has(word)) {
        missingDfns.set(word, []);
      }
      missingDfns.get(word).push(this.page);
      return `Couldn't find definition for ${word}`;
    } else {
      // exists!
      if (!usedDfns.has(word)) {
        usedDfns.set(word, []);
      }
      usedDfns.get(word).push(this.page);
      return `"${word}" is defined as: "${definitions[word]}"`;
    }
  });

  // Analyze results
  eleventyConfig.on("eleventy.after", function () {
    const pageList2FilesList = (pages) =>
      pages.map((page) => `${page.inputPath} -> ${page.outputPath}`).join("\n");
    
    const unused = Array.from(Object.keys(definitionsCache)).filter(
      (k) => !usedDfns.has(k)
    );
    const used = Array.from(usedDfns.entries()).map(([key, pages]) => ({
      key,
      pages: pageList2FilesList(pages),
    }));
    const missing = Array.from(missingDfns.entries()).map(([key, pages]) => ({
      key,
      pages: pageList2FilesList(pages),
    }));

    // Do something with results
    console.log("unused:")
    console.table(unused);
    console.log("used:")
    console.table(used);
    console.log("missing:")
    console.table(missing);
  });

  // Return your Object options:
  return {
    dir: {
      input: "src",
    },
  };
};
```

</details>


<details>
<summary>Example how to use my solution</summary>

src/test.md

```md
---
hallo: welt
---

# hi

{% dfn "hi", definitions %}
{% dfn "missed", definitions %}

```

src/_data/definitions.json

```json
{
  "hi": "This is the definition text",
  "world": "earth"
}
```

</details>

<details open>
<summary>Example output by my solution</summary>

```
[11ty] Writing _site/test/index.html from ./src/test.md (liquid)
unused:
┌─────────┬────────┐
│ (index) │ Values │
├─────────┼────────┤
│    0    │ 'welt' │
└─────────┴────────┘
used:
┌─────────┬──────┬──────────────────────────────────────────┐
│ (index) │ key  │                  pages                   │
├─────────┼──────┼──────────────────────────────────────────┤
│    0    │ 'hi' │ './src/test.md -> _site/test/index.html' │
└─────────┴──────┴──────────────────────────────────────────┘
missing:
┌─────────┬──────────┬──────────────────────────────────────────┐
│ (index) │   key    │                  pages                   │
├─────────┼──────────┼──────────────────────────────────────────┤
│    0    │ 'missed' │ './src/test.md -> _site/test/index.html' │
└─────────┴──────────┴──────────────────────────────────────────┘
[11ty] Wrote 1 file in 0.09 seconds (v1.0.2)
```

</details>

I think at the moment that your problem is really hard to solve with eleventy and I don't really see an elegant and reliable solution.
I think as a plugin it would be great if one could emit assets after the normal build succeeded or if you could somehow define deoendencies between templates (e.g. the "missing glossary entries" page needs to wait for all pages of the "docs" folder to be ready) or something similar.

**Comment by behoppe** [comment]
Thank you @pdehaan. I will speak to what I'm trying to do, and we can see if that is the easier question :-)

If I had two words, I might say "curating taxonomy." By reviewing our actual glossary against the terms that contributors actually invoke (which may or may not exist in the glossary), I want to 

- Identify "broken links": `defn` shortcodes with terms that aren't yet defined, or that are defined with some other spelling.
- Identify "useless terms": glossary entries that are never used.
- Identify opportunities for development: glossary entries whose usage invites us to split off new terms with distinct definitions.

And perhaps more important than developing new glossary terms is developing new articles that provide insight about terms that are used frequently or with a variety of contexts.

I am deliberately thinking of glossary entries as a sort of tag (and I am still adjusting to the eleventy notion of tag), and so all the tasks that I mention above are things that I hope to do with tags as well as glossary entries. For example, "We've seen a lot of new content about x (e.g., "race conditions") and here's an overview of some things about x that you might want to think about." It's part of my job to identify those opportunities; I don't need to automate all or even most of it, but I am looking for useful ways to stay on top of the task.

**Comment by behoppe** [comment]
Thank you @Snapstromegon. I'm glad to know I wasn't missing something easy :-)

Your solution is very helpful and I follow the general idea. I will need to study some JavaScript to absorb more fully. Perhaps this is a silly question, but are you saying that there is **no way** to define `usedDfns`, `missingDfns`, etc., with something like `addCollection`, so that I could consider a page with `{% for item in collections.usedDfns %}`? I am still getting the hang of the "data cascade" and perhaps that's behind the issue here?

In any case, my intent for now is mostly for behind-the-scenes diagnostics, so the limitations you mention about your solution don't seem too bad for me. Thanks again.

**Comment by Snapstromegon** [comment]
There might also be a solution using collections, but I don't know how without trying around. I think it will be a little harder to access the collections from inside the shortcode (but you can still just pass them in).

There is nothing to feel bad about here... I'm currently among the top five contributers (by number of commits) of eleventy and even I have to look this stuff up and don't always understand it immediatly.

**Comment by pdehaan** [comment]
Doesn't solve all of the use cases, but hacked in some simple checking around definitions:

```js
  // Reuse 11ty's built-in `slugify` filter.
  const slugifyFn = eleventyConfig.getFilter("slugify");

  eleventyConfig.addCollection("defnTerms", function (collectionApi) {
    const defns = collectionApi.getFilteredByTag("glossary");
    // Possibly over-engineered here. We might really only care about the slugified title and not the unslugged version.
    const data = defns.reduce((acc, { data }) => {
      return Object.assign(acc, {[slugifyFn(data.title)]: data.title});
    }, {});
    return data;
  });

  // Shortcode for glossary links
  eleventyConfig.addShortcode(
    "defn",
    function(term='', text='') {
      // Some sneaky stuff here to get the context from the `this.ctx` object so we can access
      // `collections` and `page` variables from within our shortcode.
      const { collections, page } = this.ctx;
      const slug = slugifyFn(term);
      const glossaryUrl = `/doc/reference/glossary/#${slug}`;
      // If our `collections.defnTerms` does NOT include the current slug, it's likely a bad link/defn.
      if (!Object.keys(collections.defnTerms).includes(slug)) {
        console.error(`[${page.url}] Unknown term: "${term}" => ${glossaryUrl}`);
        process.exitCode = 1;
      }
      return `<a class="defn" href="${glossaryUrl}">${text || term}</a>`;
    }
  );
```

And then in the src/doc/reference/glossary/glossary.json file I also added a `tags: ["glossary"]` property so it'd auto create the `collections.glossary` collection (although you might have been manually creating that in the .eleventy.js config file anyways).

Long story longer, here's the output:
```sh
[/doc/tutorials/introduction-to-cilk-programming/] Unknown term: "OpenCilk" => /doc/reference/glossary/#opencilk
[/doc/tutorials/introduction-to-cilk-programming/] Unknown term: "Cilk" => /doc/reference/glossary/#cilk
[/doc/tutorials/introduction-to-cilk-programming/] Unknown term: "Cilksan" => /doc/reference/glossary/#cilksan
[/doc/tutorials/introduction-to-cilk-programming/] Unknown term: "scalability" => /doc/reference/glossary/#scalability
[/doc/tutorials/introduction-to-cilk-programming/] Unknown term: "Cilkscale" => /doc/reference/glossary/#cilkscale
[/doc/tutorials/introduction-to-cilk-programming/] Unknown term: "syncing" => /doc/reference/glossary/#syncing
[/doc/tutorials/introduction-to-cilk-programming/] Unknown term: "nested parallelism" => /doc/reference/glossary/#nested-parallelism
[/doc/tutorials/introduction-to-cilk-programming/] Unknown term: "continuation" => /doc/reference/glossary/#continuation
[/doc/tutorials/introduction-to-cilk-programming/] Unknown term: "data race" => /doc/reference/glossary/#data-race

[11ty] Benchmark    198ms  14%  6209× (Configuration) "url" Nunjucks Filter
[11ty] Copied 81 files / Wrote 155 files in 1.19 seconds (7.7ms each, v1.0.2)
```

**Comment by behoppe** [comment]
Thank you @pdehaan. `this.ctx` looks very sneaky :-)

I tried your solution and it works like a charm. I have a couple questions, if you don't mind:

- My output includes many more lines, mostly about `[11ty] Writing _site/...`. Is there a place I can adjust for less output?
- I am trying to look at `defnTerms` as a collection with something like `{% for entry in collections.defnTerms %}`, but this loop generates nothing. That's different than `{% for entry in collections.defns %}`, which iterates over a non-trivial list. Perhaps this is moot, because (if I understand your code) `collections.defnTerms` is just another way of looking at `collections.glossary`, but I am confused about the scope and use of `defnTerms`.

Overall, I am making great progress, and I really appreciate all this help!

**Comment by pdehaan** [comment]
`this.ctx` is sneaky indeed (and possibly undocumented), and IIRC would be very specific to either LiquidJS or Nunjucks, so your mileage may vary, and might break [hard] in the future if you decide to arbitrarily change rendering engines, but #yolo.

> * My output includes many more lines, mostly about `[11ty] Writing _site/...`. Is there a place I can adjust for less output?

https://www.11ty.dev/docs/config/#enable-quiet-mode-to-reduce-console-noise (re: `eleventyConfig.setQuietMode(true)` or <kbd>eleventy --quiet</kbd>).

Re: `collections.defnTerms`, that would be a bit different since you're looping over an object instead of an array, but interesting that it wouldn't output anything. I would have expected it to maybe output the object keys.

```js
  eleventyConfig.addCollection("defnTerms", function (collectionApi) {
    const defns = collectionApi.getFilteredByTag("glossary");
    // Possibly over-engineered here. We might really only care about the slugified title and not the unslugged version.
    const data = defns.reduce((acc, { data }) => {
      return Object.assign(acc, {[slugifyFn(data.title)]: data.title});
    }, {});
    return data;
  });
```

That creates a new collection named "defnTerms" (based on all terms found in posts tagged w/ "glossary" tag) which is an object w/ slugified `data.title` as keys and the `data.title` as a value so we can do lookups.

Whereas `collections.glossary` is an array of posts, and `collections.defns` is apparently an array of `{ url: post.url, term, text }` objects, if I'm reading earlier posts correctly.

**Comment by behoppe** [comment]
Thanks @pdehaan. I quieted my console and was able to look at `collections.defnTerms` with a page roughly like so:

```
---
title: Defns
---
{{ collections.defnTerms | log }}
{% for key, value in collections.defnTerms %}
{{ key }} : {{ value }}
{% endfor %}
``` 

The `log` filter gave me a look at the object in my console, and the `for` loop worked after I split out `key, value` per [here](https://stackoverflow.com/questions/45223686/cannot-access-data-in-nested-object-within-nunjucks-template). 

I think my next step is upping my JavaScript so I can make use of these solutions. Thanks again.

**Comment by pdehaan** [comment]
Cool cool... Feel free to close the issue, or we can convert it to a discussion if this isn't an Eleventy bug or enhancement or task.
Although I'm not sure if I've ever clicked that "Convert to discussion" and now sure how it'd handle threads and replies and I'm scared.

**Comment by behoppe** [comment]
I will close it. Thanks again.
