### ISSUE TITLE
Liquid bug

### ISSUE THREAD

**Issue by caramiki** [11ty/eleventy#257]
I experienced a regression updating from 0.5.0 to 0.5.3.

I have a loop written in liquid that looks something like this:

```liquid
<ul>
  {% assign i = 0 %}
  {% for post in collections.blog %}
    {% increment i %}
    <li><a href="{{ post.url }}">{{ post.data.title }}</a></li>
    {% if i > 5 %}
      {% break %}
    {% endif %}
  {% endfor %}
</ul>
```

In 0.5.0, this compiled to the HTML I expected:

```html
<ul>
  <li><a href="/blog/some-post">Some Post</a></li>
  <li><a href="/blog/another-post">Another Post</a></li>
  <li><a href="/blog/yet-another-post">Yet Another Post</a></li>
  <li><a href="/blog/wow-much-post">Wow Much Post</a></li>
  <li><a href="/blog/amazing-post">Amazing Post</a></li>
</ul>
```

But now in 0.5.3 where I have `{% increment i %}`, the value of `i` is being outputted to the page, even though content inside `{% %}` shouldn't be visible.

```html
<ul>
  0<li><a href="/blog/some-post">Some Post</a></li>
  1<li><a href="/blog/another-post">Another Post</a></li>
  2<li><a href="/blog/yet-another-post">Yet Another Post</a></li>
  3<li><a href="/blog/wow-much-post">Wow Much Post</a></li>
  4<li><a href="/blog/amazing-post">Amazing Post</a></li>
</ul>
```

(Spacing/indentation has been cleaned up for clarity.)

I have since written a better loop that doesn't require having my own counter, after reading more liquid documentation. But I wanted to note the bug.

**Comment by zachleat** [comment]
Ah unfortunately I think the 0.5.3 behavior is correct!

http://shopify.github.io/liquid/tags/variable/#increment

The docs for increment say that it adds one and outputs the value.

To me this doesn't make any sense and I agree with you that it probably shouldn't do this, but I guess we don't get to make the liquid rules 😭

**Comment by DirtyF** [comment]
@caramiki  why not use `limit` here? ` {% for post in collections.blog limit:5 %}`
https://shopify.github.io/liquid/tags/iteration/

**Comment by zachleat** [comment]
Good tip!

She _may_ already be doing this, per “I have since written a better loop that doesn't require having my own counter, after reading more liquid documentation.”
