### ISSUE TITLE
Edge deployment failures

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#2572]
It looks like deployments relying on the Eleventy generated import map for Edge are failing. We are going to have to workaround the approach which uses the autogenerated import map. This will allow us to delete some code but will also unfortunately require Edge function `import` statements to change (again).

This will apply to **2.0.0-canary.16** and newer.

## Before

```js
import { EleventyEdge } from "eleventy:edge";
import precompiledAppData from "./_generated/eleventy-edge-app-data.js";
```

## After

```js
import { EleventyEdge, precompiledAppData } from "./_generated/eleventy-edge-app.js";
```

## Error message

We’ll also throw a build-time error message for you with instructions:

> Experimental early adopter API change alert! Unfortunately the default imports for Eleventy Edge in the latest canary have changed. The easiest thing you can do is delete your existing `netlify/edge-functions/eleventy-edge.js` and let Eleventy generate a new one for you. The new import should be `import { EleventyEdge, precompiledAppData } from "./_generated/eleventy-edge-app.js";`

## Shout outs

cc @mirisuzanne and @slegay and @MarcL who seem to have been asking around on this one!

(Also ran into #2571 while debugging this)

**Comment by zachleat** [comment]
Shipping with 2.0.0-canary.16

**Comment by zachleat** [comment]
Cross posting https://answers.netlify.com/t/sporadic-errors-this-edge-function-has-crashed-the-deployment-failed-while-serving-the-request/70752/31 and https://answers.netlify.com/t/edge-function-11ty-edge-error/75633

**Comment by mirisuzanne** [comment]
Thanks for the update! Excited to try it out again. :)

**Comment by MarcL** [comment]
Thanks for the quick fix @zachleat! I really appreciate the debugging today. 🎉

**Comment by zachleat** [comment]
Cross posting https://github.com/11ty/demo-eleventy-edge/issues/1

**Comment by zachleat** [comment]
2.0.0-canary.16 has shipped.

**Comment by slegay** [comment]
Awesome, thanks so much!

**Comment by slegay** [comment]
By the way, 11ty Edge is game changing. We're going to be able to serve our gated content to our world-wide audience over CDN with 200ms response times. Authentication tokens are handled via JWTs in cookies that refresh every 15 minutes and validated in edge functions, the user token gets injected as global data into 11ty Edge rendering, and all personalization and signing of video stream URLs happen in 11ty Edge, the whole thing works flawlessly. The only request requiring access backend data is the one refreshing the JWT with a serverless function. Really cool stuff.

**Comment by MarcL** [comment]
I'd love to hear more about your approach here @slegay. We love success stories about teams using Netlify edge functions (and I love hearing how 11ty can be used too!) Your use case sounds really interesting. Reach out if you'd like to chat about it sometime.

**Comment by slegay** [comment]
Hey Marc, sure, would love to chat! I just sent you a connection request on LinkedIn.

**Comment by Kerrick** [comment]
> Hey Marc, sure, would love to chat! I just sent you a connection request on LinkedIn.

Would you be willing to post a link to a public write-up? I'm also curious how you did this and I'm sure I'm not the only one.
