### ISSUE TITLE
Slow performance - Takes 12s to rebuild on each change

### ISSUE THREAD

**Issue by kamranahmedse** [11ty/eleventy#2597]
Hey team, firstly appreciate all the work done on 11ty - love everything about it.

I am currently in the process of migrating [roadmap.sh](https://roadmap.sh) from Next.js to 11ty. The website has around 655 pages and the build + development changes take around 12 seconds to reload.

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/4921183/194747310-a3d8e251-ed26-4de3-b418-bac05b6c60ea.png">

I tried debugging the performance but I am not sure what I am doing wrong here. 

The project codebase can be found here [kamranahmedse/roadmap.sh](https://github.com/kamranahmedse/roadmap.sh).

PS: I am on Eleventy 1.0.2

**Comment by j-f1** [comment]
Can you scroll up to the top of the benchmark output? The bigger contributors to build time should be up there. But also that build time doesn’t seem terrible, my site with ~900 pages takes about 30 seconds to build on GitHub Actions.

**Comment by kamranahmedse** [comment]
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/4921183/194758326-8711f55a-736e-4145-9d22-1fa2b0e051fa.png">

> my site with ~900 pages takes about 30 seconds to build on GitHub Actions

Interesting. What about the development? Is it the same for that as well. I tried `--incremental` flag but on each change it still takes the same time 12 seconds.

**Comment by j-f1** [comment]
My laptop is quite a bit faster than GitHub actions so I get this

```
[11ty] Copied 71 files / Wrote 148 files in 11.46 seconds (77.4ms each, v2.0.0-canary.15)
```

That said, maybe v2 is faster than v1? (for clarity, my site is built from a bunch of pages that are combined into a smaller number of page files)

**Comment by kamranahmedse** [comment]
I tried v2 as well along [with Vite plugin](https://github.com/11ty/eleventy-plugin-vite); 7.25 seconds is the best I got which still is a lot considering the fact that I have to wait for 7 seconds to see my changes.

![image](https://user-images.githubusercontent.com/4921183/194759644-edaa15ce-9959-456f-82c5-935d970e4b22.png)

**Comment by j-f1** [comment]
Huh, what’s taking up the most time for incremental updates like that?

**Comment by kamranahmedse** [comment]
I am not sure what I am doing wrong. Could you possibly take a look? The project is here:    https://github.com/kamranahmedse/roadmap.sh

**Comment by pdehaan** [comment]
Here's what I see locally on my MacBook Pro w/ M1 Max + 64 GB RAM:

> _"[11ty] Copied 30 files / Wrote 655 files in 5.43 seconds (8.3ms each, v1.0.2)"_

```sh
npm run bench

> roadmap-next@1.0.0 bench
> DEBUG=Eleventy:Benchmark* npx @11ty/eleventy

/private/tmp/roadmap.sh/src/_data/topics.js 121 ms
Building Tailwind…

Done in 249ms.

> roadmap-next@1.0.0 build:tailwind
> npx tailwindcss -i src/_includes/styles/main.css -o _site/styles/main.css --minify


Bundling JavaScript files
  Eleventy:Benchmark Benchmark    672ms  11%   648× (Configuration) "cssmin" Nunjucks Async Filter +0ms
  Eleventy:Benchmark Benchmark      4ms   0%   629× (Configuration) "resourceShortCodes" Liquid Filter +0ms
  Eleventy:Benchmark Benchmark    131ms   2%   655× (Configuration) "lastModifiedDate" Nunjucks Async Filter +0ms
  Eleventy:Benchmark Benchmark      2ms   0%     2× (Aggregate) Configuration addPlugin +0ms
  Eleventy:Benchmark Benchmark     13ms   0%     2× (Aggregate) Searching the file system +0ms
  Eleventy:Benchmark Benchmark    123ms   2%     2× (Aggregate) Data File +0ms
  Eleventy:Benchmark Benchmark     32ms   1%    62× (Aggregate) Template Read +0ms
  Eleventy:Benchmark Benchmark     28ms   0%    30× (Aggregate) Passthrough Copy File +0ms
  Eleventy:Benchmark Benchmark     15ms   0%    36× (Aggregate) Template Compile +0ms
  Eleventy:Benchmark Benchmark      2ms   0%     2× (Aggregate) > Compile > ./src/roadmaps/backend/topic.md +0ms
  Eleventy:Benchmark Benchmark    108ms   2%  1916× (Aggregate) Render +0ms
  Eleventy:Benchmark Benchmark     44ms   1%   408× (Aggregate) > Render > ./src/roadmaps/backend/topic.md (Pagination: 136 pages) +0ms
  Eleventy:Benchmark Benchmark      1ms   0%     2× (Aggregate) > Compile > ./src/roadmaps/android/android.md +0ms
  Eleventy:Benchmark Benchmark      9ms   0%     2× (Aggregate) > Render > ./src/roadmaps/android/android.md +0ms
  Eleventy:Benchmark Benchmark     13ms   0%   354× (Aggregate) > Render > ./src/roadmaps/blockchain/topic.md (Pagination: 118 pages) +0ms
  Eleventy:Benchmark Benchmark      1ms   0%     2× (Aggregate) > Render > ./src/roadmaps/angular/angular.md +0ms
  Eleventy:Benchmark Benchmark     17ms   0%   525× (Aggregate) > Render > ./src/roadmaps/devops/topic.md (Pagination: 175 pages) +0ms
  Eleventy:Benchmark Benchmark     11ms   0%   402× (Aggregate) > Render > ./src/roadmaps/frontend/topic.md (Pagination: 134 pages) +0ms
  Eleventy:Benchmark Benchmark      4ms   0%   198× (Aggregate) > Render > ./src/roadmaps/golang/content.md (Pagination: 66 pages) +0ms
  Eleventy:Benchmark Benchmark      1ms   0%     2× (Aggregate) > Render > ./src/roadmaps/postgresql-dba/postgresql-dba.md +1ms
  Eleventy:Benchmark Benchmark      1ms   0%     1× (Aggregate) > Compile > ./src/404.njk +0ms
  Eleventy:Benchmark Benchmark      3ms   0%     1× (Aggregate) > Render > ./src/about.md +0ms
  Eleventy:Benchmark Benchmark      3ms   0%     1× (Aggregate) > Render > _site/about/index.html +0ms
  Eleventy:Benchmark Benchmark      3ms   0%     1× (Aggregate) > Compile > ./src/index.njk +0ms
  Eleventy:Benchmark Benchmark      2ms   0%     1× (Aggregate) > Render > ./src/index.njk +0ms
  Eleventy:Benchmark Benchmark      2ms   0%     1× (Aggregate) > Render > _site/index.html +0ms
  Eleventy:Benchmark Benchmark      1ms   0%     1× (Aggregate) > Render > _site/backend/internet/index.html +0ms
  Eleventy:Benchmark Benchmark      1ms   0%     1× (Aggregate) > Render > _site/backend/internet/how-does-the-internet-work/index.html +0ms
  Eleventy:Benchmark Benchmark      1ms   0%     1× (Aggregate) > Render > _site/backend/internet/what-is-http/index.html +0ms
  Eleventy:Benchmark Benchmark      7ms   0%     1× (Aggregate) > Render > _site/backend/internet/dns-and-how-it-works/index.html +0ms
  Eleventy:Benchmark Benchmark      7ms   0%     1× (Aggregate) > Render > _site/backend/internet/what-is-domain-name/index.html +0ms
  Eleventy:Benchmark Benchmark      1ms   0%     1× (Aggregate) > Render > _site/backend/os-general-knowledge/posix-basics/index.html +0ms
  Eleventy:Benchmark Benchmark      1ms   0%     1× (Aggregate) > Render > _site/backend/learn-a-language/go/index.html +0ms
  Eleventy:Benchmark Benchmark      1ms   0%     1× (Aggregate) > Render > _site/backend/learn-a-language/javascript/index.html +0ms
  Eleventy:Benchmark Benchmark      1ms   0%     1× (Aggregate) > Render > _site/backend/caching/server-side/redis/index.html +0ms
  Eleventy:Benchmark Benchmark      1ms   0%     1× (Aggregate) > Render > _site/backend/web-security-knowledge/ssl-tls/index.html +0ms
  Eleventy:Benchmark Benchmark      1ms   0%     1× (Aggregate) > Compile > ./src/roadmaps.njk +0ms
  Eleventy:Benchmark Benchmark      9ms   0%     1× (Aggregate) > Render > _site/android/index.html +0ms
  Eleventy:Benchmark Benchmark      1ms   0%     1× (Aggregate) > Render > _site/blockchain/dapps/applicability/index.html +0ms
  Eleventy:Benchmark Benchmark      1ms   0%     1× (Aggregate) > Render > _site/angular/index.html +0ms
  Eleventy:Benchmark Benchmark      1ms   0%     1× (Aggregate) > Render > _site/devops/managing-servers/live-in-terminal/uname/index.html +0ms
  Eleventy:Benchmark Benchmark      1ms   0%     1× (Aggregate) > Render > _site/devops/monitoring/logs-management/loki/index.html +1ms
  Eleventy:Benchmark Benchmark      1ms   0%     1× (Aggregate) > Render > _site/frontend/javascript/learn-fetch-api-ajax-xhr/index.html +0ms
  Eleventy:Benchmark Benchmark      1ms   0%     1× (Aggregate) > Render > _site/golang/go-web-frameworks/index.html +1ms
  Eleventy:Benchmark Benchmark      1ms   0%     1× (Aggregate) > Render > _site/postgresql-dba/index.html +0ms
  Eleventy:Benchmark Benchmark      6ms   0%     1× (Aggregate) > Compile > ./src/_includes/layouts/base.njk +0ms
  Eleventy:Benchmark Benchmark      5ms   0%     1× (Aggregate) > Compile > ./src/_includes/layouts/topic.njk +0ms
  Eleventy:Benchmark Benchmark      4ms   0%     1× (Aggregate) > Compile > ./src/_includes/layouts/topic-reference.njk +0ms
  Eleventy:Benchmark Benchmark      2ms   0%     1× (Aggregate) > Compile > ./src/_includes/layouts/svg-roadmap.njk +0ms
  Eleventy:Benchmark Benchmark      1ms   0%     1× (Aggregate) > Compile > ./src/_includes/layouts/md-roadmap.njk +0ms
  Eleventy:Benchmark Benchmark   2976ms  50%   655× (Aggregate) Template Write +0ms
  Eleventy:Benchmark Benchmark    123ms   2%     1× (Data) `./src/_data/topics.js` +0ms
[11ty] Copied 30 files / Wrote 655 files in 5.43 seconds (8.3ms each, v1.0.2)
```

So the biggest (by far)  is that "(Aggregate) Template Write" at 3s (of a 5.5s build). Not sure how to speed that up.
Tailwind seems to compile in ~250ms, and 672ms for "(Configuration) 'cssmin' Nunjucks Async Filter".

I dumped the src/_data/topics.js output to a file and it's about 941 KB minified (or 1.1 MB prettier'ed). That's a lot of data. But  despite it doing a lot of file/directory reading/writing and using gray-matter to preprocess the files, it still seems to finish in 120-125ms. But it still is a lot of data to push to every file in the data cascade.

**Comment by pdehaan** [comment]
Here was some other interesting benchmarking:

> ```sh
> npm run bench
> ```
> _[11ty] Copied 30 files / Wrote 655 files in 4.93 seconds (7.5ms each, v1.0.2)_

> ```sh
> npm run bench # but w/o tailwindcss in eleventy.after event in .eleventy.js
> ```
> _[11ty] Copied 30 files / Wrote 655 files in 3.94 seconds (6.0ms each, v1.0.2)_

> ```sh
> npm run bench # but w/o "htmlmin" transform in .eleventy.js
> ```
> _[11ty] Copied 30 files / Wrote 655 files in 4.76 seconds (7.3ms each, v1.0.2)_

> ```sh
> npm run bench # but w/o "jsonLd" transform in .eleventy.js
> ```
> _[11ty] Copied 30 files / Wrote 655 files in 2.69 seconds (4.1ms each, v1.0.2)_

So looks like the jsonLd transform is pretty expensive, and removing it reduces my local build time by almost 50%.

**Comment by j-f1** [comment]
For the json-ld transform, you might find that a lighter weight tool like rehype might be faster than booting up a full JSDOM instance.

**Comment by kamranahmedse** [comment]
Thanks you guys! It gave me some pointers and I was able to get it down to 1 second on average:

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/4921183/194854427-9f57e9cb-f7f0-44c2-87d7-9eb2a004d741.png">

Here is what I did:

* Removed filter for sorting collection data and [instead used collection](https://github.com/kamranahmedse/roadmap.sh/pull/299/files#diff-c306e0a99961a16f5c5c83996caa0958b94006d97f97475049ea3a08036bb5b0R30-R31). 
  Filters turned out to be much slower than collections.
* Removed `cssmin`, `jsmin` and `htmlmin` filters.
  Replaced with rust based [minify-html](https://github.com/wilsonzlin/minify-html) which was much faster.
* Removed the [resource rendering shortcodes](https://github.com/kamranahmedse/roadmap.sh/pull/299/files#diff-c306e0a99961a16f5c5c83996caa0958b94006d97f97475049ea3a08036bb5b0L45-L49) and put it [inside the data file](https://github.com/kamranahmedse/roadmap.sh/pull/299/files#diff-1df52d8496b3bdd8be6c9b56482b18e0aafca845b41fc31e4d43cef8a56acb46R44).
* Promisified [the data file](https://github.com/kamranahmedse/roadmap.sh/pull/299/files#diff-1df52d8496b3bdd8be6c9b56482b18e0aafca845b41fc31e4d43cef8a56acb46)
* Added [caching to the data file](https://github.com/kamranahmedse/roadmap.sh/pull/299/files#diff-1df52d8496b3bdd8be6c9b56482b18e0aafca845b41fc31e4d43cef8a56acb46R151-R154)
* Moved all the pages to `.md` instead of `.njk` (not sure if it would have any impact though).
* Upgraded to Elevent 2.0.0-canary.16

Here's the PR implementing the changes [if anyone is interested](https://github.com/kamranahmedse/roadmap.sh/pull/299).

Thanks again @pdehaan @j-f1 🙏

**Comment by pdehaan** [comment]
```sh
[11ty] Copied 30 files / Wrote 655 files in 0.82 seconds (1.3ms each, v2.0.0-canary.16)
```
👍 

Another possible optimization (although sub 1s build times for 655 pages is splitting hairs at this point), but you could conditionally add the transforms so you only minify content if you're doing a production build by wrapping the `.addTransform()` cal with a check for `if (process.env.NODE_ENV === "production") {...}` or whatever. Might shave a few ms off your build times (or make local debugging easier on non-minimized assets).

---

Re: _"Moved all the pages to `.md` instead of `.njk` (not sure if it would have any impact though)"_,

This shouldn't have much of an impact, although it is important to point out that .md (and .html) files are preprocessed by a templating engine (default is LiquidJS) although you can opt out of preprocessing by passing `false` to `markdownTemplateEngine` and/or `htmlTemplateEngine` in your .eleventy.js config file:

> ### [DEFAULT TEMPLATE ENGINE FOR MARKDOWN FILES](https://www.11ty.dev/docs/config/#default-template-engine-for-markdown-files)
> Markdown files run through this template engine before transforming to HTML.
>
> MARKDOWN TEMPLATE ENGINE |  
> -- | --
> Object Key | `markdownTemplateEngine`
> Default | `liquid`
> Valid Options | A valid template engine short name or `false`

> ### [DEFAULT TEMPLATE ENGINE FOR HTML FILES](https://www.11ty.dev/docs/config/#default-template-engine-for-html-files)
> HTML templates run through this template engine before transforming to (better) HTML.
>
> HTML TEMPLATE ENGINE |  
> -- | --
> Object Key | `htmlTemplateEngine`
> Default | `liquid`
> Valid Options | A valid template engine short name or `false`

**Comment by kamranahmedse** [comment]
Oh nice, didn't think about that. Brought it down to 500ms on average 🔥 

<img width="665" alt="image" src="https://user-images.githubusercontent.com/4921183/194947744-7d7fc9d3-9e13-4bca-aaaf-9cedd08597fa.png">

**Comment by pdehaan** [comment]
Ah, and another interesting one I forgot to mention earlier. I think because of the way that you're running <kbd>tailwindcss --watch</kbd> via <kbd>npm run dev</kbd>, the Tailwind artifact gets built twice.

```diff
git diff package.json | cat
diff --git a/package.json b/package.json
index 2ba47bcb..5d4b500e 100644
--- a/package.json
+++ b/package.json
@@ -5,10 +5,10 @@
   "private": true,
   "scripts": {
     "clean": "rimraf _site && rimraf .cache",
-    "dev:tailwind": "npx tailwindcss -i src/_includes/styles/main.css -o _site/styles/main.css --watch",
+    "dev:tailwind": "say 'dev'; npx tailwindcss -i src/_includes/styles/main.css -o _site/styles/main.css --watch",
     "dev:eleventy": "npx @11ty/eleventy --serve",
     "dev": "NODE_ENV=dev npm-run-all clean --parallel dev:*",
-    "build:tailwind": "npx tailwindcss -i src/_includes/styles/main.css -o _site/styles/main.css --minify",
+    "build:tailwind": "say 'build'; npx tailwindcss -i src/_includes/styles/main.css -o _site/styles/main.css --minify",
     "build:eleventy": "npx @11ty/eleventy",
     "build": "NODE_ENV=production npm-run-all clean build:eleventy",
     "deploy": "NODE_DEBUG=gh-pages gh-pages -d _site -t",
```

```sh
npm run dev
```

This should now run `dev:tailwind` in parallel w/ `eleventy --serve` which also will run <kbd>npm run build:tailwind</kbd> via `child_process.exec()`, causing it to say "dev" then "build" a second later.

```js
  eleventyConfig.on('eleventy.after', async () => {
    console.log('Building Tailwind…');
    exec('npm run build:tailwind').toString();
```
