### ISSUE TITLE
Allow handlebars partials to be defined in a directory and used globally without relative paths

### ISSUE THREAD

**Issue by offbeat-dev** [11ty/eleventy#2601]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to have a functionality similar to what [handlebars-loader](https://github.com/pcardune/handlebars-loader) provides when using its partialDirs option in order to use any partial without the need of specifying it's relative path.

**Describe the solution you'd like**
Maybe use the custom template extension in order to implement something similar to what handlebars-loader does? I am not completely sure about the best approach.

**Describe alternatives you've considered**
I am using vite for bundling js and css files and would like to avoid using webpack in my project. 
I did considered using webpack just in order to use the handlebars-loader plugin, but if eleventy default config would allow me to use partials without relative paths, I'd rather go with that

Thank you in advance for your help

**Comment by pdehaan** [comment]
Related discussion: https://github.com/11ty/eleventy/discussions/2600

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!
