### ISSUE TITLE
HtmlBasePlugin fails with permalink set to false (i.e. not generated file)

### ISSUE THREAD

**Issue by Maximvdw** [11ty/eleventy#2602]
**Describe the bug**
https://github.com/11ty/eleventy/blob/master/src/Plugins/HtmlBasePlugin.js#L152
HtmlBasePlugin fails when trying to convert an output file with `permalink: false`

**To Reproduce**
Use the HtmlBasePlugin and have a file with `permalink: false`

**Expected behavior**
The file should be skipped

**Environment:**
Eleventy 2.0.0-canary.16

**Comment by zachleat** [comment]
Fixed, will ship with 2.0.0-canary.19
