### ISSUE TITLE
Multiple input directories

### ISSUE THREAD

**Issue by AlexNodex** [11ty/eleventy#2606]
**Is your feature request related to a problem? Please describe.**
Being able to modulerise eleventy would be great, having one input directory is quite restrictive and does not allow for modularity of codebases. For examples imagine a module and theme world where one could simply install themes / modules and enable/add/remove ad-hoc via the `input` key in the `.eleventy.config.js`

**Describe the solution you'd like**
change the current input value to either accept other values aside a string for example an array of folders / globs to use as input sources and or a function based approach that would return those input directories - something akin to the following...

```js
module.exports = function(eleventyConfig) {
  return {
    dir: {
      input: function() {
        const directories = aFunctionToReturnInputPathsBasedOnAConfigFile();
        return directories;
      },
      output: "public"
    }
  };
};
```
or perhaps...
```js
module.exports = function(eleventyConfig) {
  return {
    dir: {
      input: ['src/*.njk','modules/*.njk','themes/*.njk'], // this would walk all of these in turn, this way global data cascades down through modules / themes from the core.
      output: "public"
    }
  };
};

```
This owuld not be a breaking change as it could still accept a string as the basic input, this would simply enhance it making the way for a more themable and modular platform where modules and themes could be configured and included / excluded on the fly.

Edit:

Of course one could just put all the modules / themes below the input directory and have eleventy render them as normal but that would lead to a URL structure that isn't great, and sure, one could most likely change all of the permalinks inside a module to output to a different folder structure but that gets overly complex.

**Comment by pdehaan** [comment]
Probably a dupe of https://github.com/11ty/eleventy/issues/2353. Might also want to add your +1 to that issue.

**Comment by AlexNodex** [comment]
Thanks, I'll close this and +1 that / comment on that issue :)
