### ISSUE TITLE
Javascript front matter returning string of functions

### ISSUE THREAD

**Issue by edwardhorsford** [11ty/eleventy#261]
I'm attempting to use javascript front matter, but I get a string of the function instead of the result.

My page:
```js
---js
{
  title: "A post page",
  foo: function() {
    return (new Date()).toLocaleString();
  }
}
---

{{title}} page: {{foo}}
```

What I get:
`A post page page: function () { return (new Date()).toLocaleString(); }`.

---

I'm using the [same example](https://www.11ty.io/docs/data-frontmatter/#javascript-front-matter) as the docs, except with an extra comma per ([#17](https://github.com/11ty/11ty.io/pull/17)).

Tested on Eleventy 0.5.4.

**Comment by zachleat** [comment]
It's a function so you would need to call it a la `foo()`.

**Comment by edwardhorsford** [comment]
I might as well post my use case in case it's interesting. Possibly related to #216.

Most of my posts have front matter that defines a `primaryImage` - this is used when I link to the post, in thumbnails for the item, and populates opengraph and twitter meta fields.

I was creating an index page that links to my latest x posts. I wanted the `primaryImage` for the index page to be derived the image primary image from the _latest_ post.

Something like:
```
---
primaryImage: collections.post[collections.post.length -1].data.primaryImage
---
```

**Comment by edwardhorsford** [comment]
Raised ([#18](https://github.com/11ty/11ty.io/pull/18)) to show example of using a function in the docs.
