### ISSUE TITLE
Templates with `permalink: false` still appear in collections.all

### ISSUE THREAD

**Issue by edwardhorsford** [11ty/eleventy#262]
Using Eleventy 0.5.4

I'm not sure if this is intentional, but it looks like items with `permalink: false` still appear in `collections.all`, but with some null values.

I'm using `collections.all` to list all pages processed by Eleventy. 
```nunjucks
<ol>
	{% for item in collections.all | sort(false, false, 'url') %}
	<li><a href="{{item.url}}">{{item.url}}</a></li>
	{% endfor %}
</ol>
```

Items with `permalink: false` still appear. In this case `item.url` is false, so I get this:
![screen shot 2018-09-29 at 14 18 30](https://user-images.githubusercontent.com/2204224/46246244-8f640980-c3f2-11e8-8b73-dd3f3599faa1.PNG)

## What I expected

My understanding is that `permalink: false` stops eleventy processing a file. I'd then assume it doesn't get added to the various collections or things. Additionally, I understood `collections.all` to be a collection of all templates processed / generated by Eleventy. Since pages without a permalink shouldn't be processed, I didn't expect them to be listed there.

**Comment by zachleat** [comment]
Hmmmmmmmm. That was intentional, yes.

This is good feedback though.

Importantly, templates with a false permalinks are still processed, they just aren't written to disk.

**Comment by zachleat** [comment]
Maybe? Looks like the implementations listed in #248 have some notion of `ignore` for different pieces of content already.

I’m gonna close this for now, but if anyone else gets confused by this please leave a comment here!
