### ISSUE TITLE
11ty Edge: eleventy.edge.cookies reads from request headers, not response, so cookies set in Edge functions are not immediately available for rendering

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [11ty/eleventy#2657]
**Describe the bug**

Cookies set in Netlify Edge on the server side are not immediately available for use in the 11ty edge template under `eleventy.edge.cookies`. This seems to be because `eleventy.edge.cookies` corresponds to the `Cookie` request header, not the cookies returned by the Netlify Edge response.

**To Reproduce**

Repo: https://github.com/AleksandrHovhannisyan/11ty-edge-cookie-demo

**`index.liquid`**

```liquid
{% edge %}
  {%- assign cookies = "name1,name2,name3" | split: "," -%}
  <h1>Cookie demo (with 11ty and Netlify Edge)</h1>
  <table>
    <caption>Cookies returned from the server</caption>
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Value</th>
      </tr>
    </thead>
    <tbody>
      {%- for cookie in cookies -%}
        <tr>
          <td>{{ cookie }}</td>
          <td>{{ eleventy.edge.cookies[cookie] | escape }}</td>
        </tr>
      {%- endfor -%}
    </tbody>
  </table>
{% endedge %}
```

**`netlify/edge-functions/eleventy-edge.js`**

```js
import { EleventyEdge, precompiledAppData } from "./_generated/eleventy-edge-app.js";

export default async (request, context) => {
  try {
    context.cookies.set({
	name: 'name1',
	value: `value1`,
	path: '/',
	httpOnly: true,
    });
    context.cookies.set({
	name: 'name2',
	value: `value2`,
	path: '/',
       maxAge: 10,
    });
    context.cookies.set({
	name: 'name3',
	value: `value3`,
	path: '/',
       secure: true,
    });
    let edge = new EleventyEdge("edge", {
      request,
      context,
      precompiled: precompiledAppData,
      cookies: ['name1', 'name2', 'name3'],
    });
    return await edge.handleResponse();
  } catch (e) {
    console.log("ERROR", { e });
    return context.next(e);
  }
};
```

Live demo:

1. Visit https://eleventy-cookie-demo.netlify.app/ with dev tools open.
2. Observe that the cookie values are initially empty in the rendered template, but the cookies do get returned by the server:

![A table with two columns: Name and Value. Three rows: name1, name2, name3. All values are empty. The Network tab is open in dev tools and shows three set-cookie response headers.](https://user-images.githubusercontent.com/19352442/203314756-b5aec365-0399-44c5-bea3-05a101aa8050.png)

3. Wait at least 10 seconds. Then reload the page.
4. Observe that the first and third cookies now appear. The second cookie had a max age of 10 seconds.

![A table with two columns: Name and Value. Three rows: name1 value1, name2 (no value), name3 value3. The Network tab is open in dev tools and shows two cookie request headers.](https://user-images.githubusercontent.com/19352442/203315050-115c53a2-84cd-4dff-98ff-24fdd564dd31.png)

This seems to suggest that `eleventy.edge.cookies` is reading the _request_ cookie headers, not the response cookie headers. So the client will always be a render cycle behind the server.

**Expected behavior**

The rendered template should have access to the cookies set on the server side... I think? Or is this working as intended?

**Environment:**

- OS and Version: Windows 10, WSL2
- Eleventy: 2.0.0-canary.16

**Comment by zachleat** [comment]
Per the Eleventy Community Survey results and our refocus and prioritization towards our roots as a static site generator, we’re going to be deprecating Edge in 3.0 and closing issues related to the Edge plugin. I’m very sorry to have to do this—but unfortunately this was a necessary decision to allow the project to continue forward.

Read more:
https://www.zachleat.com/web/eleventy-side-project/
https://www.11ty.dev/blog/community-survey-results/
