### ISSUE TITLE
Resolve special date values for more than just `date`

### ISSUE THREAD

**Issue by j9t** [11ty/eleventy#2660]
(Please let me know about a good way to present a reproducible test case for things like this.)

From testing, it seems that [special date values](https://www.11ty.dev/docs/dates/#setting-a-content-date-in-front-matter) like `Last Modified` are only resolved when used with `date`. That is, front matter constructs like `date_modified: Last Modified` would only be output as “Last Modified”. This is a limitation when `date` is already in use.

Assuming the observation is correct and that there’s no configuration to make this work (pointers appreciated), perhaps any front matter value starting with “date” could allow to use these values?

**Comment by zachleat** [comment]
Putting this one into the enhancement queue!

> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
Duplicate of #3902 which moved to #4020, removing from queue~
