### ISSUE TITLE
Error: You’re trying to use a layout that does not exist

### ISSUE THREAD

**Issue by jtrobinson1993** [11ty/eleventy#2663]
**Describe the bug**
Eleventy 2.0.0-canary.18 is encountering the error `[11ty] Original error stack trace: Error: You’re trying to use a layout that does not exist: /_includes/layouts/default.webc (undefined)` when running `npx @11ty/eleventy --serve`

**To Reproduce**
Have `~/index.webc` file specifying the layout: 
```
---
layout: "/_includes/layouts/default.webc"
---
  <page-header @heading="foo" @subheading="bar"></page-header>
```

layout file `~/_includes/layouts/default.webc`:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Test</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/css/global.css" />
  </head>
  <body>
    <main @raw="content">
    </main>
  </body>
</html>
```

Eleventy config file:
```
const pluginWebc = require('@11ty/eleventy-plugin-webc');
module.exports = function (eleventyConfig) {
	eleventyConfig.addPlugin(pluginWebc, {
		// Glob to find no-import global components
    // This path is relative to the project-root!
		// (The default changed from `false` in Eleventy WebC v0.7.0)
		components: "_components/**/*.webc",
	});
	eleventyConfig.addPassthroughCopy('css');

	return {
		markdownTemplateEngine: 'webc',
		htmlTemplateEnginer: 'webc',
	};
};
```

**Expected behavior**
eleventy will run normally and localhost:8080 will render the default layout containing the page header component.

**Screenshots**

**Environment:**

- Windows 10
- Eleventy 2.0.0-canary.18

**Additional context**

**Comment by j-f1** [comment]
If you set your layouts directory to `_includes` (which is the default) and then set your layout frontmatter property to `layouts/default.webc` it should work! (Or set your layouts directory to `_includes/layouts` and the layout to `default.webc`)

**Comment by jtrobinson1993** [comment]
> 

This solved it - Thank you!
