### ISSUE TITLE
Eleventy Edge could use edge_functions dir location specified in netlify.toml

### ISSUE THREAD

**Issue by whitep4nth3r** [11ty/eleventy#2669]
**Is your feature request related to a problem? Please describe.**

Given that the "advanced options" for [Eleventy Edge](https://www.11ty.dev/docs/plugins/edge/) were advertised as "you probably don’t need these", I didn't think I would need them (!). However, I had an existing netlify.toml file, that specified the location of an edge functions directory in a project that I wanted to use Eleventy Edge in.

On first `netlify dev`,  after installing the EleventyEdgePlugin (without specifying any advanced options), Eleventy added the generated files, as expected, to the default `netlify/edge-fuctions/generated` directory. This made me realise that I did, indeed, need the advanced options.

**Describe the solution you'd like**

It would be nice and user-friendly to be able to detect an existing edge_functions directory location, if already defined in an existing netlify.toml file, and for Eleventy to put the generated files in the custom location — without needing to specify the `functionsDir` advanced option.

For example, here is part of my netlify.toml file that defines a custom edge_functions directory location.

```toml
[build]
  command = "npm run build"
  functions = "src/_functions/"
  edge_functions = "src/_edge-functions/"
``` 

**Describe alternatives you've considered**

Perhaps the documentation could alert readers to the fact that if they are already using Edge Functions and have specified a custom directory for the functions, then they would need to use the advanced option: `functionsDir` — and perhaps the advanced options section on the docs should be expanded.

**Comment by zachleat** [comment]
Per the Eleventy Community Survey results and our refocus and prioritization towards our roots as a static site generator, we’re going to be deprecating Edge in 3.0 and closing issues related to the Edge plugin. I’m very sorry to have to do this—but unfortunately this was a necessary decision to allow the project to continue forward.

Read more:
https://www.zachleat.com/web/eleventy-side-project/
https://www.11ty.dev/blog/community-survey-results/
