### ISSUE TITLE
Enable plugins to be async

### ISSUE THREAD

**Issue by robole** [11ty/eleventy#2675]
**Is your feature request related to a problem? Please describe.**
There is a [11ty plugin for the syntax highlighting library shiki twoslash](https://github.com/shikijs/twoslash/tree/main/packages/eleventy-plugin-shiki-twoslash). This libary uses WASM under the hood and needs to run asynchronously.  In the plugin, they need to fudge synchronous behavior by using the[ `deasync` ](https://www.npmjs.com/package/deasync) to make it run in 11ty. For this reason, the performance is poor.

For example, at the moment, I am currently migrating a website to 11ty with 100 pages and the build time is 1.5seconds, with incremental builds a file change reloads in milliseconds. If I add the twoslash plugin, it pushes the build time to 8 seconds, and incremental builds take the same time. Having that as a dev mode experience is too painful.

**Describe the solution you'd like**
Permitting an async function to be used by `addPlugin()`.

**Describe alternatives you've considered**
Using [ `deasync` ](https://www.npmjs.com/package/deasync)  is the alternative tried.

**Comment by pdehaan** [comment]
I haven't tried twoslash, but aren't async plugins already supported?
Or is this more of an issue w/ overriding the highlighting?

```js
// .eleventy.js
/**
 * @param {import("@11ty/eleventy/src/UserConfig")} eleventyConfig
 * @returns {ReturnType<import("@11ty/eleventy/src/defaultConfig")>}
 */
module.exports = function (eleventyConfig) {
  eleventyConfig.addPlugin(require("./plugins/test"));

  return {
    dir: {
      input: "src",
      output: "www",
    }
  };
};
```

```js
// plugins/test.js
module.exports = async (eleventyConfig, opts={}) => {
  eleventyConfig.addFilter("test_filter", (val) => val.toString().toUpperCase());
};
```

```liquid
---
# src/index.liquid
title: inDex
---

<p>{{ title | test_filter }}</p>
```

### OUTPUT
```html
<p>INDEX</p>
```

**Comment by robole** [comment]
I believe that you can have async filters in v2.0 (see [docs](https://www.11ty.dev/docs/filters/#asynchronous-universal-filters)) and asycn shortcodes (see [docs](https://www.11ty.dev/docs/shortcodes/#shortcodes)), but everything else has to be synchronous. In this case, a filter or shortcode is not what is needed. You need to be able to use `await`
 in the config.

It is this type of behaviour that would be desirable:

```js
// .eleventy.js
const shikiTwoslash = require("eleventy-plugin-shiki-twoslash")

module.exports = function (eleventyConfig) {
  eleventyConfig.addPlugin(shikiTwoslash, { theme: "nord" })
}
```

```js
//index.js of "eleventy-plugin-shiki-twoslash" plugin
const { setupForFile, transformAttributesToHTML } = require("remark-shiki-twoslash")

module.exports = function (eleventyConfig, options = {}) {
  /** @type {import("shiki").Highlighter[]} */
  let highlighters = await setupForFile(options);
 }

  eleventyConfig.addMarkdownHighlighter((code, lang, fence) => {
    code = code.replace(/\r?\n$/, "") // strip trailing newline fed during code block parsing
    return transformAttributesToHTML(code, [lang, fence].join(" "), highlighters, options)
  })
}
```

There is an open issue - [Allow configuration to return a promise (async-friendly)](https://github.com/11ty/eleventy/issues/614) - related to this too.

**Comment by zachleat** [comment]
This will come with ESM, which unlocks top-level async/await in Node.js. Look for a build of this early next year, shortly after 2.0 stable ships

**Comment by zachleat** [comment]
Related to #614

**Comment by zachleat** [comment]
Almost there in PR #3074, we just need to support `async` in `addPlugin` too.

**Comment by zachleat** [comment]
Code is complete to support this (in PR #3074):

```js
await eleventyConfig.addPlugin(async () => {
  // do async stuff
});
```

**Comment by devurandom** [comment]
Is there a workaround for Eleventy 2.0.1 for plugins that `addTemplateFormats` and `addExtension`?

**Comment by zachleat** [comment]
@devurandom that seems unrelated to me, can you file a new issue?

**Comment by zachleat** [comment]
Temporary docs preview building here: https://11ty-website-git-v3-11ty.vercel.app/docs/plugins/
