### ISSUE TITLE
Passthrough File Copy not running when using the --serve option

### ISSUE THREAD

**Issue by barticusprime** [11ty/eleventy#2692]
### Operating system

macOS Monterey 12.6.1

### Eleventy

^2.0.0-canary.18

### Describe the bug

Passthrough file copy does not work when running `npx @11ty/eleventy --serve`.

- ✅ `npx @11ty/eleventy`: Copies files successfully
- ✅ `npx @11ty/eleventy --watch`: Copies files successfully
- ✅ `npx @11ty/eleventy --watch --serve`: Copies files successfully
- ❌ `npx @11ty/eleventy --serve`: Does not copy files

### Reproduction steps

1. Create a new empty project
2. `npm init -y`
3. `npm install --save-dev @11ty/eleventy@^2.0.0-canary.18`
4. Create a folder, `files`, create text files `one.txt`, `two.txt` in the `files` folder
5. Configure PassthroughCopy:
```js
// .eleventy.js
module.exports = function(eleventyConfig) {
  eleventyConfig.addPassthroughCopy("files");
};
```
6. Run `npx @11ty/eleventy --serve`

### Expected behavior

Expect that `/files`, configured to Passthrough Copy, and its contents will be copied to the output folder (`_site`) when running `@11ty/eleventy` with the `--serve` option.

This works as expected in 1.0.2. Thanks!

**Comment by j-f1** [comment]
See https://www.11ty.dev/docs/copy/#passthrough-during-serve — in v2, the files are not actually copied by default when running the server and instead are served out of their original location instead.

**Comment by zachleat** [comment]
Yeah, apologies, this will be communicated in a more prominent way with 2.0.

There is also an opt-out method on the docs that @j-f1 posted! https://www.11ty.dev/docs/copy/#passthrough-during-serve

**Comment by zachleat** [comment]
I am also curious if `npx @11ty/eleventy --watch --serve` should throw an error, hmm.

**Comment by zachleat** [comment]
I filed and fixed #2693 for my last comment

**Comment by barticusprime** [comment]
Thanks for the clarification @zachleat! That makes sense, and I swore I had seen something about differences in passthrough in canary, but couldn't find it when I needed it (of course).

**Comment by zachleat** [comment]
Just for future visitors the passthrough copy default was reverted for 2.0 (beta and stable)
