### ISSUE TITLE
How to optimize?

### ISSUE THREAD

**Issue by ndaidong** [11ty/eleventy#270]
I see eleventy is great new one generator tool. After a quick test, it looks like it doesn't process CSS/JS files, just keeps the SCRIPT and STYLE tags as they are. If I didn't miss something, here is my few questions:

- How to minimize JS/CSS files?
- How to merge them to just 1 .css file at header and 1.js at the end of body tag?
- How to process CSS files with `postcss`?

Thank you.

**Comment by zachleat** [comment]
Hey @ndaidong did you see our tutorials page? https://www.11ty.io/docs/tutorials/

**Comment by ndaidong** [comment]
@edwardhorsford 
@zachleat 
thank you, I've taken a look at the documentation. It seems we have to write the filters, not already to use.

**Comment by zachleat** [comment]
Ah, okay. I’ve opened #272 to continue that discussion for an officially supported asset pipeline. Let me know if you have other questions!
