### ISSUE TITLE
Files don't get served with emulated passthrough file copy, if output directory is changed to "/"

### ISSUE THREAD

**Issue by azangru** [11ty/eleventy#2709]
_I hope I've diagnosed the problem correctly and am reporting it to the appropriate repo. Sorry if not._

## Version of eleventy
2.0.0-canary.15

## Description of the problem
Given the following directory structure:

```
<projectRoot>/src/static/css/styles.css
```

And the following config:

```js
  eleventyConfig.addPassthroughCopy({
    'src/static': '/'
  });
```

I would expect the css file to be served at `/css/styles.css`. Indeed, if I run a build with the above configuration, I am seeing a `css` directory in my output directory, containing the `styles.css` file. However, when I run `eleventy --serve`, the dev server cannot resolve the `/css/styles.css` path.

I've confirmed that the dev server works correctly when:
- the config for the output directory is not provided (i.e. `eleventyConfig.addPassthroughCopy('src/static');`)
- the config has an output directory that is different from `/`. For example, this works:

```js
  eleventyConfig.addPassthroughCopy({
    'src/static': '/assets'
  });
```

## P.S.
I am gradually discovering that the passthrough is very unstable, and that updating files (be it nunjucks templates, markdown files, or static assets) often confuses the dev server such that it stops serving the passthrough files until a restart. No errors in the console, or anything that might help diagnose the problem further. Might be related to the fact that I am using the `--incremental` option with eleventy serve.

**Comment by zachleat** [comment]
A few issues were outstanding here, most notably that dev server aliases weren’t being applied during subsequent builds!
