### ISSUE TITLE
Idea: option to skip processing on pages with future dates

### ISSUE THREAD

**Issue by edwardhorsford** [11ty/eleventy#271]
I read this [interesting blog](https://flaviocopes.com/netlify-auto-deploy/) about using daily deploys on netlify to 'schedule' blog posts.

Essentially the posts are given a date in the future, and the static site generator doesn't process them until that date is in the past. The author set up Netlify to redeploy his site daily - so when the post he'd already pushed eventually had a date in the past, it gets rendered that day.

I think you could probably do this now with Eleventy using permalink=false and some javascript testing for the current date - but not very cleanly as the templates need extra code to make it work.

Cleaner would be config in eleventyConfig - which people could make conditional depending on whether they're running in production or dev

Possibly if draft support comes to eleventyConfig, that might support this too. Something like:
```
eleventyConfig.ignoreFiles(function(file) {
    return (process.env.DRAFT === 'true') ? false : page.date > currentDate;
  });
```

**Comment by zachleat** [comment]
Hmm, to me this seems like a duplicate of #188?

**Comment by edwardhorsford** [comment]
Yeah, possibly - depending on how #188 is implemented. If you think they're close enough I'll close this.

If it's possible to do in `eleventyConfig` it might be nice to have a section in the docs showing what code you'd need.

**Comment by edwardhorsford** [comment]
I should add - I'd be happy to put in PR to add something to the docs.
