### ISSUE TITLE
Check for user misnaming config file `.eleventy.js` as `eleventy.js`

### ISSUE THREAD

**Issue by Kylebrown9** [11ty/eleventy#2721]
### Is your feature request related to a problem? Please describe.

Yes, on Windows 10 when I misname my config file as `eleventy.js` and run `npx eleventy --serve`, instead of getting a sensible error it attempts to open `eleventy.js` as a file through the system (e.g. with whatever editors I have installed).

### Describe the solution you'd like

Instead of doing what I describe above, which is strange and unintuitive, the `eleventy --serve` command should print out an error indicating the file is named incorrectly and exit.

### Describe alternatives you've considered

You could also allow users to name their files other things, but it's much safer to just do some extra validation and add a clean error.

**Comment by zachleat** [comment]
Moving forward (once 2.0 ships stable) we’ll recommend that folks primarily use `eleventy.config.js` rather than `.eleventy.js`.

See https://www.11ty.dev/docs/config/#default-filenames

That said, I’m happy to put this into the enhancement queue is other folks are running into this problem!

> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
I think #3654 solved this in a more generic way (we show when a config file is not used)
