### ISSUE TITLE
Permalink false not working for .js directory data files

### ISSUE THREAD

**Issue by abbott567** [11ty/eleventy#2722]
### Operating system

Windows 11 Home 10.0.22621 build 22621

### Eleventy

1.0.2

### Describe the bug

All of the documentation seems to suggest that I can add directory data files to apply `permalink: false` to prevent pages being generated for specific files or folders. But it isn't working when using `.js` files. 

I assume it's a bug, as I've been over it multiple times and it appears it only works as expected if you use a `.json` format.

I've tried with a new project just to make sure, and it's still generating pages when I don't want them to if I use a JavaScript object. 

For example, I have the folder structure:
```
src
- posts
- - post-1.md
- - posts.js
```

In my `posts.js` file I'm using the following:
```js
module.exports = {
  permalink: false,
  tags: "post"
}
```

It's my expectation, that the `permalink: false` attribute should be picked up in the cascade so I don't need to add it to the front-matter in the `post-1.md` file, but it is still being generated.

However, if I rename `posts.js` to `posts.json` and add quotes it works.

```json
{
  "tags": "post",
  "permalink": false
}
```

### Reproduction steps

Steps are outlined in the description of the bug.

### Expected behavior

Expected behaviour is outlined in the description of the bug.

### Screenshots

![image](https://user-images.githubusercontent.com/9450064/210175916-c7f8eb85-d228-4ed6-aa91-c6e7096333cf.png)

**Comment by pdehaan** [comment]
If you’re using a .js file, I think it needs to be “posts.11tydata.js” (versus posts.json or posts.11tydata.json).

**Comment by abbott567** [comment]
Oh man. Somehow missed that. I assumed consistency between formats and spent so long looking at the docs I couldn't see the wood for the trees! Apologies.
