### ISSUE TITLE
Add async support to `addShortcode`

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#2726]
Related to the filters work in #2536 #1382

After spelunking this feature it appears we have had `addAsyncShortcode` and `addPairedAsyncShortcode` methods for quite some time (v0.10.0+)

This feature would be to add `async function()` support to `addShortcode` and `addPairedShortcode`.

**Comment by zachleat** [comment]
This would simplify the `eleventy-img` docs quite a bit too.

**Comment by zachleat** [comment]
Shipping with `2.0.0-canary.24`

**Comment by j-f1** [comment]
fwiw I’ve had a bunch of strange behavior around Nunjucks async shortcodes. In particular `set` as a block doesn’t seem to work with async shortcodes inside. Might be worth documenting that.

**Comment by zachleat** [comment]
@j-f1 yeah you’re absolutely right, this needs to be on the docs. Making sure you’re aware of this feature too: https://github.com/11ty/eleventy/issues/2108

**Comment by zachleat** [comment]
Filed #2727 for that work!
