### ISSUE TITLE
eleventyConfig config object should contain override arguments from CLI

### ISSUE THREAD

**Issue by pdehaan** [11ty/eleventy#2729]
Currently it returns the return object from the root eleventy config file, and doesn't seem to resolve command line arguments or return default values, etc.

```sh
npx @11ty/eleventy --input=pasta --output=noodles
[CONFIG] undefined
[PLUGIN] { input: 'src' }
[11ty] Writing noodles/index.html from ./pasta/index.njk
[11ty] Wrote 1 file in 0.03 seconds (v1.0.2)
```

Where my .eleventy.js is:
```js
const { inspect } = require("node:util");

/**
 * @param {import("@11ty/eleventy/src/UserConfig")} eleventyConfig
 * @returns {ReturnType<import("@11ty/eleventy/src/defaultConfig")>}
 */
module.exports = function (eleventyConfig) {
  console.log("[CONFIG]", inspect(eleventyConfig.dir, { sorted: true }));

  eleventyConfig.addPlugin(require("./plugins/custom"));

  return {
    dir: {
      input: "src",
      // output: "www",
    }
  };
};
```

And my ./plugins/custom.js is:
```js
const { inspect } = require("node:util");

module.exports = (eleventyConfig, pluginConfig) => {
  console.log("[PLUGIN]", inspect(eleventyConfig.dir, { sorted: true }));
  return {};
};
```

And my src/index.njk and pasta.njk are blank files that exist.

---

**UPDATE:** Pushed my sample repo to https://github.com/pdehaan/11ty-config-plugins.

```sh
npm run

Lifecycle scripts included in 11ty-config-plugins@1.0.0:
  test
    echo "Error: no test specified" && exit 1

available via `npm run-script`:
  build
    eleventy
  build:noodles
    eleventy --input=pasta --output=noodles
  build:pasta
    eleventy --input=./pasta
```

```sh
npm run build:noodles

> 11ty-config-plugins@1.0.0 build:noodles
> eleventy --input=pasta --output=noodles

[CONFIG] undefined
[PLUGIN] { input: 'src' }
[11ty] Writing noodles/index.html from ./pasta/index.njk
[11ty] Wrote 1 file in 0.03 seconds (v1.0.2)
```

I think it should resolve the `input` and `output` directories from the command line (and possibly return the defaults if they are not specified; like `output: "_site"`, etc).

_Originally posted by @pdehaan in https://github.com/11ty/eleventy/discussions/2483#discussioncomment-4605752_

**Comment by zachleat** [comment]
Config first run, should have these values:

* `eleventyConfig.dir.input` via `--input`
* `eleventyConfig.dir.output` via `--output`
* `eleventyConfig.templateFormats` via `--formats`
* `eleventyConfig.pathPrefix` via `--pathprefix`

Config plugins should have (in addition to the above):

* `eleventyConfig.dir.data` via `--input` and config return object `data`
* `eleventyConfig.dir.includes` via `--input` and config return object `includes`
* `eleventyConfig.dir.layouts` via `--input` and config return object `layouts`

**Comment by zachleat** [comment]
Work in progress in the `config-dir-values` branch. (Still missing `data`, `includes, `layouts`)

Given the size of this change, I am going to have to punt it out of 2.0 stable, sorry about that!

**Comment by zachleat** [comment]
This is shipping as part of #3244 using the new `directories` property. The `directories` values are project root relative normalized file paths with posix style separators.

`npx @11ty/eleventy --input=content --output=dist`

```js
module.exports = function(eleventyConfig) {
	eleventyConfig.directories.input; // "./content/"
	eleventyConfig.directories.output; // "./dist/"
};
```

Note the caveats documented at #3244 when returning `dir` in your config file.

**Comment by zachleat** [comment]
(Shipping with 3.0.0-canary.6)

**Comment by zachleat** [comment]
`eleventyConfig.directories` didn’t solve everything here, filed #3439 and #3440 as follow-ups
