### ISSUE TITLE
File changes for json files in the global data directory not reflected until restart

### ISSUE THREAD

**Issue by Gr0t3Man** [11ty/eleventy#2735]
### Operating system

macOS BigSur 11.7.2

### Eleventy

2.0.0-canary.26 (started in 2.0.0-canary.21)

### Describe the bug

When making a change in a data file (.json) stored in the _data directory, the changes are not reflected until I restart Eleventy. Eleventy detects that the file has changed (File changed: ... in the terminal) and updates all pages, but the changes are not written to the output files. And displayed on the live page.

The last version with which it worked was canary.20. Now testing in canary.25 and canary.26 the changes fails to be written. 
The bug occurred with --serve and/or --incremental options. 

### Reproduction steps

1. Start Eleventy with eleventy --serve
2. Make a change in the data file home.json that is used in index.njk => Changes not visible in the browser
3. Restart Eleventy => now you will see the changes

### Expected behavior

Eleventy should write/update all pages with the updated data from the file instead of the cached one.

**Comment by Gr0t3Man** [comment]
The issues seems to be the same as [issue 2717](https://github.com/11ty/eleventy/issues/2717).

**Comment by zachleat** [comment]
Just popping in to say: Not necessarily—layout files and JSON files are different, internally.

**Comment by Gr0t3Man** [comment]
I have created a repositorie of a site which use json files in the _data directory for generating the product listing pages. These json file contains a list/order of products which needs the be included in the pages (NL and EN). 

The repositorie can be found [galajurk.11ty](https://github.com/Gr0t3Man/galajurk.11ty)

The live website can be found [galajurk.nl](https://www.galajurk.nl)

**Comment by zachleat** [comment]
2.0.0-beta.2 shipped with some improvements here, can you retest? (thank you!)

**Comment by Gr0t3Man** [comment]
Did a retest with 2.0.0-beta.2 on several projects and the changes to the json files are updated nicely to the output files. Also tested it with the '-serve -incremental' option, this works also fine.

Thanks for solving this issue.

**Comment by zachleat** [comment]
Great thank you!
