### ISSUE TITLE
Cut an Eleventy Dev Server 1.0

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#2739]
https://github.com/11ty/eleventy-dev-server

**Comment by yurivish** [comment]
(just noticed you're working on this: I might have just encountered a bug with the dev server while testing out the latest canary, involving passthrough paths not being served. I'm working on a minimal reproduction...)

This is the line that's misbehaving (works fine with `npm run build` but not `npm run serve`):
```
eleventyConfig.addPassthroughCopy({'legacy/':'.'});
```

Works fine with `--serve` if `eleventyConfig.setServerPassthroughCopyBehavior("copy");` is used.

Anyway, thought I'd mention it in case you wanted a cleaner 1.0 that doesn't need an additional bug fixed. :-)

Will have an issue up soon; I just figured out that it has to do with the fact that my `legacy` directory has subdirectories within it; those get copied over, but not served.

**Comment by zachleat** [comment]
Make sure you’ve upgraded to the latest canary!

**Comment by yurivish** [comment]
This reproduces on `2.0.0-canary.29`, which I'm on since you fixed a bug I filed last week today (https://github.com/11ty/eleventy/issues/2723).

Hmm, my diagnosis might not be correct and I don't have a way to reproduce the issue yet; will keep you posted. Will also double-check that it is, in fact, happening...

**Comment by yurivish** [comment]
I figured it out – the files _do_ get served if you go to them directly, e.g. the URL http://localhost:8080/mobile-wiki/index.html will serve the index file. But the URL http://localhost:8080/mobile-wiki/ will not serve it if the passthrough copy behavior is "passthrough". Not sure if that qualifies as a bug, but definitely had me chasing this down for the past hour.

**Comment by zachleat** [comment]
No worries @yurivish I did file your issue at https://github.com/11ty/eleventy-dev-server/issues/43 though I don’t know that it will make 1.0 (dev server)/2.0 (eleventy)!

**Comment by zachleat** [comment]
This is complete, v1.0 of the Eleventy Dev Server is now available.

**Comment by zachleat** [comment]
https://github.com/11ty/eleventy-dev-server/releases/tag/v1.0.0
