### ISSUE TITLE
How to load a different script for each page with Nunjucks?

### ISSUE THREAD

**Issue by rocc-o** [11ty/eleventy#2744]
I'm trying to load a different .js for each page, like this:

_includes/pages-layout.njk
```
...
{% block content %}

    {# Articles pages #}
    {% if script_media %}
        <script defer src="{{ script_media }}"></script>
    {% endif %}

    {# Contact page #}
    {% if script_pwa-prompt %}
        <script defer src="{{ script_pwa-prompt }}"></script>
    {% endif %}
    
 {% endblock %} 

</body>
</html>
```

contact/index.njk
```
---
layout: _pages-layout.njk
script_pwa-prompt: /assets/js/pwa-prompt.min.js
---
```

articles/article-1/index.njk
```
---
layout: _pages-layout.njk
script_media: /assets/js/io-iframe.min.js
---
```

But it is loading only the first script `script_media`.
I'd like `contact/index.njk` to load `script_pwa-prompt` only,
and `articles/article-1/index.njk` to load `script_media` only,
and so on for other pages as well.

**Comment by zachleat** [comment]
What Eleventy version?

**Comment by rocc-o** [comment]
^1.0.2 just upgraded (waiting and anticipating for v.2.0.0)

**Comment by jeromecoupe** [comment]
Mmhhh did you try it using a {% set %} in nunjucks ?
That should work provided that it is set in a global context (out of blocks, etc.)

**contact/index.njk**
```
---
layout: _pages-layout.njk
---
{% set script_pwa-prompt= "/assets/js/pwa-prompt.min.js" %}

{% block whatever %}
{% endblock %}
```

**Comment by rocc-o** [comment]
Why in `contact/index.njk`? I need to change .js in `_includes/pages-layout.njk` just before the `</body>`.

**Comment by rocc-o** [comment]
This is how is structured my `_includes/pages-layout.njk`
```
<!DOCTYPE html>
<html lang="{{ local }}">

<head>
  {% include "_head.njk" %}
</head>

<body class="header">

<header>
  {% include "_navbar.njk" %}
</header>

<main>
  {{ content | safe }}
</main>

  {% include "_footer.njk" %}

  <script defer src="/assets/js/script.min.js"></script>


{% block content %}

    {# Articles pages #}
    {% if script_media %}
        <script defer src="{{ script_media }}"></script>
    {% endif %}

    {# Contact page #}
    {% if script_pwa-prompt %}
        <script defer src="{{ script_pwa-prompt }}"></script>
    {% endif %}
    
 {% endblock %} 


</body>
</html>
```

**Comment by pdehaan** [comment]
Random idea until I have a few minutes to try recreating this locally, but does changing it from `script_pwa-prompt` to `script_pwa_prompt` make a difference? I wonder if it's not liking that hyphen in the variable name and trying to do some unexpected maths.

**Comment by rocc-o** [comment]
Ahhhhhh... Peter, I believe you are right. I've forgotten that hyphen thing in front matter. Just give an hour and I will try it and let you know. Thanks!
Jerome, I'll be back in an hour and check your examples. Thanks.

**Comment by rocc-o** [comment]
@pdehaan as per your random idea, sir, the hyphen in the variable name was the problem. Now with underscore is properly working. Thank you!

@jeromecoupe what you say is true - DOM and everything - but those specific scripts at the end of the body give me the best overall performance. I've tested them in any possible variation zillions of times. I don't know why is that. Anyway I do not need to load them sooner.
I had thought about `{% extends "_pages-layout.njk" %}` but i couldn't get it to work (many things remain a mystery to me). But your set empty custom_scripts block idea is brilliant and I will definitely try it in the next few days, as I'm refactoring a bit my site. Thank you!

I'm waiting for v.2.0.0 stable as I really want to try that WebC with bundle and slots and also is-land when available. I really like Eleventy and its community. Thank you all!

**Comment by pdehaan** [comment]
> I had thought about `{% extends "_pages-layout.njk" %}` but i couldn't get it to work (many things remain a mystery to me)

I have a basic example of [Nunjucks `extends`](https://mozilla.github.io/nunjucks/templating.html#extends) at https://github.com/pdehaan/11ty-njk-extends

**Comment by rocc-o** [comment]
Great! I'm saving it for a rainy day. Thank you Peter!

**Comment by pdehaan** [comment]
> Great! I'm saving it for a rainy day.

Now I'm afraid that I may have oversold the excitement of how interesting that sample repo is. So apologies in advance for next time it rains and you read the code.

(Also, feel free to close the issue if your life's questions have been answered)

**Comment by rocc-o** [comment]
HAHAHA... To me It's all gravy. And, as some mysteries of life have been revealed to me, I'm closing this issue now. Thanks!
