### ISSUE TITLE
Retrieving data from a JSON

### ISSUE THREAD

**Issue by rocc-o** [11ty/eleventy#2746]
I'm trying to retrieve data filtered by key from a JSON, but I cannot succed -- no errors on build, audio player is there, but data is not retrieved (I'm on Eleventy ^1.0.2):

_data/sounds.json
```
[
	{
		"key":"1",
		"title":"Funkmaster Flex Hot 97 Street Jams 1994",
		"subtitle":"Roc Raida guests on Funk Flex show NYC",
		"url":"https://archive.org/download/Hot97StreetJams-1994/Funkmaster%20Flex%20-%20Hot%2097%20Street%20Jams%201994%20%5BRoc%20Raida%5D.mp3"
	},
	{
		"key":"2",
		"title":"Funkmaster Flex Hot 97 Street Jams 1997",
		"subtitle":"Funk Flex show NYC",
		"url":"https://ia801703.us.archive.org/17/items/FunkmasterFlex-199709/Funkmaster%20Flex%20-%20Hot%2097%20%28Sept%2097%29.mp3"
	}
]
```

.eleventy.js
```
      // Filter for _data/sounds.json
      eleventyConfig.addFilter("getSound", (sounds,label) => {
        let sound = sounds.filter(a => a.key === label)[0];
        return sound;
      });
```

_includes/partials/components/audio-player.njk
```
        {% if sound %}
        {% set mySound = sounds | getSound(sound) %}
                <h3>{{ mySound.title }}</h3>
                <p>{{ mySound.subtitle }}</p>   
                <audio controls src="{{ mySound.url }}"></audio>
        {% endif %}   
``` 

sounds/article-1.njk

```
---
layout: _pages-layout.njk

sound: 1
---
          {% include "partials/components/audio-player.njk" %}
```

**Comment by aloxe** [comment]
I guess you want to have `{% if sounds %}` (with an `s`) in your layout. Also I think that your function `getSound` will expect a label.

**Comment by rocc-o** [comment]
I have made changes as per your suggestion -if I understood them correctly- but still it does not work:

```
        {% if sounds and sound %}
        {% set mySound = sounds | getSound(sounds, sound) %}
```

```
      // Custom audio player filter for _data/sounds.json
      eleventyConfig.addFilter("getSound", (sounds,label) => {
        let soundkey = sounds.filter(a => a.key === label)[0];
        return soundkey;
      });
```

```
---
layout: _pages-layout.njk

soundkey: 1
---
```

**Comment by aloxe** [comment]
if your template frontmatter has `soundkey: 1` then your layout should use it.
```
        {% if sounds and soundkey %}
        {% set mySound = sounds | getSound(sounds, soundkey) %}
``` 
oh and I am not sure what you want to do with the pipe in the layout but I think that nunjucks will not like it.
```
        {% if sounds and soundkey %}
        {% set mySound = getSound(sounds, soundkey) %}
```
should suffice

**Comment by rocc-o** [comment]
```
        {% if sounds and soundkey %}
        {% set mySound = getSound(sounds, soundkey) %}
```
gave an error on `sounds/article-1.njk`: Error: Unable to call `getSound`, which is undefined or falsey (via Template render error).

```
        {% if sounds and soundkey %}
        {% set mySound = sounds | getSound(sounds, soundkey) %}
```
with template frontmatter `soundkey: 1` gave no errors, audio player is again there, but still no data retrieved.

**Comment by pdehaan** [comment]
My guess is that the json is using string keys, but the yaml front matter is using numeric keys. Not sure if wrapping the soundkey yaml front matter value in quotes would work, or if you have to try stringifying the label in your filter function.

**Comment by rocc-o** [comment]
Tried quotes in `soundkey: "1"` does not work. Tried changinh to `"key":"rocc"`, in JSON and front matter does not work. So, I'm trying now to figure out how to use JSON.stringify() in filter function - if I understood correctly.

**Comment by aloxe** [comment]
When I look at the [doc for filters](https://www.11ty.dev/docs/filters/), I see that it is used to filter a string, therefore I am not sure this is what you want to use to retrieive the sound that has a particular key.

I suggest you do this in your nunjunk layout with something like
```
        {% if sound %}
        {% set mySound = sounds | getSound(sound) %}
               {% for sound in sounds %}
               {% if sound.key === soundkey %}
                <h3>{{ sound.title }}</h3>
                <p>{{ sound.subtitle }}</p>   
                <audio controls src="{{ sound.url }}"></audio>
               {% endif %}
               {% endfor %}
        {% endif %}  
```
and get rid of your filter.

**Comment by rocc-o** [comment]
@aloxe Changed with your suggestion in my Nunjucks layout and removed the filter in .eleventy.js
but no data is retrieved and no audio player is there.

**Comment by rocc-o** [comment]
So, a miracle - almost. I've found a [tutorial](https://epsi-rns.gitlab.io/ssg/2020/01/20/11ty-widget-data/)!

I managed, after many hours, to adapt it to my sinister purposes, and it works! 

One question though: why sometimes there are dashes and sometimes not? e.g.:
`{%- for link_id in related_link_ids -%}`
`{% set ids = sounds | keys %}`

**Comment by aloxe** [comment]
I left some parasite ref and didn't update the first `if` in the snippet I gave you. I now I corrected it, this should work.

If not, try to toubleshoot with displaying intermediate results so you can see what works and what breaks
```
{% if sound.key === soundkey %}
  <p>here we have a sound</p>
  <p>{{ sound.key }}</p>
{% elseif %}
  <p>no sound found</p>
{% emdif %}
```

**Comment by rocc-o** [comment]
@aloxe almost a miracle happened - see my previous reply. And there's also my question about dashes when yes and when not. 
What do you think about the solution proposed in such tutorial?

**Comment by pdehaan** [comment]
https://github.com/pdehaan/11ty-2746#readme

For what it's worth, I think your filter approach did work, and it was just a string-vs-number issue: https://github.com/pdehaan/11ty-2746

I did tweak it slightly to use [`Array#find()` API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) which will quit looping on the first matching record. Probably not much of an optimization unless you have hundreds/thousands/millions of array records though (and likely only ever 1 match). But I also added a loud build-failing error message if you pass an invalid label/key and it doesn't find a match, which was helpful in debugging:
```js
  eleventyConfig.addFilter("getSound", (sounds = [], label = "") => {
    // console.log({sounds, label});
    const sound = sounds.find(s => s.key === label.toString());
    if (sound) {
      return sound;
    }
    throw new Error(`Unknown sound key: "${label}"`);
  });
```

```sh
npm run build 


> 11ty-2746@1.0.0 build
> eleventy

[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering njk template ./src/sounds/article-3.njk (via TemplateContentRenderError)
[11ty] 2. (./src/sounds/article-1.njk)
[11ty]   Template render error: (/private/tmp/11ty-2746/src/_includes/partials/components/audio-player.njk)
[11ty]   Error: Unknown sound key: "3" (via Template render error)
[11ty] 
[11ty] Original error stack trace: Template render error: (./src/sounds/article-1.njk)
[11ty]   Template render error: (/private/tmp/11ty-2746/src/_includes/partials/components/audio-player.njk)
[11ty]   Error: Unknown sound key: "3"
[11ty]     at ...
[11ty] Wrote 0 files in 0.03 seconds (v1.0.2)
```

**Comment by rocc-o** [comment]
Wow @pdehaan ! Yours is definitely the best solution. Considering I will hopefully fill that json with hundreds, thousands of data, that loud build-failing error message is a godsend. And the stringify too, which I was going crazy to implement it. Everything is much cleaner now and works perfectly. Thank you so much Peter!

**Comment by aloxe** [comment]
wow @pdehaan, so this means that template filters can filter an array to a string and much more 😮 

If I understood well, it means that `{{ sounds | getSound(sound) }}` will filter `sounds`, being the first argument of the filter callback and `sound` being the second argument. That opens more possibilities. Pity, this is not explicitlly mentionned in [the documentation](https://www.11ty.dev/docs/filters/). Thanks for keeping on with this.

@rocc-o The tutorial you found says it too but your array.filter fits much better for whant you want to do. Ah and also the dash at the begin and end of the `{%- %}` syntax will remove any line breaks in the generated HTML.

**Comment by pdehaan** [comment]
> _"Pity, this is not explicitlly mentionned in [the documentation](https://www.11ty.dev/docs/filters/)."_

I think it's covered separately in the template specific documentation for Nunjucks at https://www.11ty.dev/docs/languages/nunjucks/#filters

But yes, `{{ sounds | getSound(sound) }}` will call your custom filter with `getSound(sounds, sound)`; which isn't always exactly intuitive. But I find filters a very powerful feature, and definitely one of my favorites.

**Comment by pdehaan** [comment]
Unrelated, but if you wanted to implement the audio player as a custom Nunjucks _shortcode_ (versus a custom filter and include), you could do something like this:

```js
  eleventyConfig.addShortcode("audio_player", function (label = "", sounds = this.ctx?.sounds || []) {
    const sound = sounds?.find(s => s.key?.toString() === label.toString());
    if (sound) {
      return `
        <h3 data-key="${ sound.key }">${ sound.title }</h3>
        <p>${ sound.subtitle }</p>
        <audio controls src="${ sound.url }"></audio>
      `.trim();
    }
    throw new Error(`Unknown sound key: "${label}"`);
  });
```

```njk
---
# src/sounds/article-4.njk
key: 2
---

{%- audio_player key -%}
```

### OUTPUT

```html
<h3 data-key="2">Funkmaster Flex Hot 97 Street Jams 1997</h3>
<p>Funk Flex show NYC</p>
<audio controls src="https://ia801703.us.archive.org/17/items/FunkmasterFlex-199709/Funkmaster%20Flex%20-%20Hot%2097%20%28Sept%2097%29.mp3"></audio>
```

**Comment by pdehaan** [comment]
If you're looping over all the entries in _data/sounds.json, you can also use pagination (and some combination of your filter/include/shortcode solution) like so:

```njk
---
pagination:
  data: sounds
  size: 1
  alias: sound
permalink: "sounds/{{ sound.key | slugify }}/"
---

{%- audio_player sound.key -%}
```

**Comment by aloxe** [comment]
Great sharring @pdehaan thx. I have one more question. the ` eleventyConfig.addShortcode` and other  `eleventyConfig.addFilter` do you have them all in `.eleventy.js` or do you create specific `_data/post.js` for them?

**Comment by pdehaan** [comment]
@aloxe If my .eleventy.js file isn't too big/complex, I'd put all the config functions/setup in the one file. If the config file is over 100-200 lines, I'd probably break it up into smaller files which I'd just `require()` from the main .eleventy.js file.
