### ISSUE TITLE
addPassthroughCopy not working for CSS, images

### ISSUE THREAD

**Issue by peruvianidol** [11ty/eleventy#275]
I recently built my personal site based on [eleventy-base-blog](https://github.com/11ty/eleventy-base-blog) and it worked great. I thought I'd try and use Eleventy for a new work project, starting from scratch. For some reason, CSS and images are not copying to `_site` using `eleventyConfig.addPassthroughCopy` and/or `passthroughFileCopy: true`.

I created a dumbed down version of what I'm working on here, that has the same issue:

[https://github.com/peruvianidol/eleventy-test](https://github.com/peruvianidol/eleventy-test)

I've tried rolling back to a previous version of Eleventy (my personal site is on 0.5.2), but that didn't seem to do the trick. I'm guessing this is less an issue with Eleventy and more that I am just missing something, but I can't seem to figure it out.

**Comment by zachleat** [comment]
Haha well I spent an embarrassing amount of time debugging this to find out that your config file is named `eleventy.js` and not the default `.eleventy.js` 😎

Rename the file or use the `--config` param to change the default https://www.11ty.io/docs/usage/#--config-to-change-the-config-file-name

**Comment by Dhruvermafz** [comment]
so, I have tried everything for my CSS file to be visible in the output, but it dint, so, I just noticed that the CSS file/folder that I have created, is not also even visible in the output folder, I just tried a hack, I just copied the folder of my CSS to the output folder and it worked

**Comment by pdehaan** [comment]
@Dhruvermafz Here's my rough setup:

```sh
tree -a . --gitignore
.
├── .eleventy.js
├── package.json
├── public/css/site.css
├── src/
│   ├── index.njk
│   └── pages/about.njk
└── www/
    ├── index.html
    ├── pages/about/index.html
    └── public/css/site.css

9 directories, 10 files
```

```js
// .eleventy.js
/**
 * @typedef {import('@11ty/eleventy/src/UserConfig')} EleventyConfig
 * @typedef {ReturnType<import('@11ty/eleventy/src/defaultConfig')>} EleventyReturnValue
 * @type {(eleventyConfig: EleventyConfig) => EleventyReturnValue}
 */
module.exports = function (eleventyConfig) {
  eleventyConfig.addPassthroughCopy("public");

  return {
    dir: {
      input: "src",
      output: "www",
    }
  };
};
```

### OUTPUT

```sh
npm run build

> 11ty-275@1.0.0 prebuild
> rm -rf www


> 11ty-275@1.0.0 build
> eleventy

[11ty] Writing www/index.html from ./src/index.njk
[11ty] Writing www/pages/about/index.html from ./src/pages/about.njk
[11ty] Copied 1 file / Wrote 2 files in 0.04 seconds (v1.0.2)
```

The thing that I usually forget (repeatedly) is that the passthrough copy is relative to the .eleventy.js config file, not the input directory.
