### ISSUE TITLE
Changes in shortcodes are not recognised when config file (.eleventy.js) is saved.

### ISSUE THREAD

**Issue by dwkns** [11ty/eleventy#2755]
### Operating system

macOS 13.1

### Eleventy

2.0.0-beta-1

### Describe the bug

When you make changes inside a shortcode in `.eleventy.js` the dev server detects the file save but any code changes are ignored. 

Any code changes you make outside a shortcode are processed on save as expected.

### Reproduction steps

Create a template in `index.njk`:
```html
<!DOCTYPE html>
<html lang="en">
  <body>
    <h1>Hello</h1>
    <p>{% doSomething %}</p>
  </body>
</html>
```

Create a config file in `.eleventy.js`
```js
module.exports = (eleventyConfig) => {
  console.log(`[ outside shortcode ]:`, "outside");

  eleventyConfig.addShortcode("doSomething", () => {
    console.log(`[ inside shortcode ]:`, "inside");
    return "This is from the shortcode";
  });

};
```

When you run `npx @11ty/eleventy --serve` you get the output you expect:
```bash
...
[ outside shortcode ]: outside
[ inside shortcode ]: inside
...
```

With the server still running if you change the value of `inside shortcode` and save:

```js
console.log('[ inside shortcode ]:', "inside changed");
```
The server detects the file save but the output is still 
```bash
...
[ outside shortcode ]: outside
[ inside shortcode ]: inside
...
```
With the server **still** running, now change the value of `outside shortcode` to:
```js
console.log(`[ outside shortcode ]:`, "outside changed");
```
The output is:
```bash
...
[ outside shortcode ]: outside changed
[ inside shortcode ]: inside
...
```
The code change within the shortcode is not recognised. But the code change outside the shortcode is. 

Only by restarting the server  are code changes within a shortcode recognised. This appears to be the case for `eleventyConfig.addAsyncShortcode` as well. Any template that uses the shortcode are not updated either. 

### Expected behavior

When you change code within a shortcode or async shortcode, those changes should be reflected when `.eleventy.js` is reloaded. 

You should not need to restart the server to see these changes.

**Comment by zachleat** [comment]
This will ship with v2.0.0-beta.2—thank you!
