### ISSUE TITLE
Plugin compatibility checks mismatch when comparing beta with canary compatibility

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#2758]
Found out via https://github.com/11ty/eleventy-plugin-webc/pull/43 from @colinaut

Ended up discovering a new thing about semver, that prerelease tags are… alphabetic

https://semver.org/#spec-item-11

This only presents a problem when you’re trying to use a beta release 👀 on a plugin that has canary compatibility, especially if that plugin requires a specific minimum version of canary:

* `eleventy-plugin-vite` requires `>=2.0.0-canary.4`
* `eleventy-plugin-webc` requires `>=2.0.0-canary.19`

Practically speaking, if we change these plugins to require `>=2.0.0-beta.1` they will now match all valid canary versions (which is bad).

As they currently stand, they do not match the beta release but only issue a `console.warn` and keep processing gracefully.

All other official Eleventy plugins do not tie to a specific canary release for compatibility and as such are unaffected.

(source: https://fediverse.zachleat.com/@zachleat/109717715197804907)

**Comment by zachleat** [comment]
Also just as a note for me the `versionCheck` method was modified to add support for prereleases in 1.0 via https://github.com/11ty/eleventy/issues/2001

**Comment by colinaut** [comment]
Well that's not something I would have expected. I would have thought it would count them as completely different rather than just letters. Good catch there.

**Comment by zachleat** [comment]
I think moving forward we’ll want to standardize on `alpha` instead of `canary` for prereleases in 3.0.

**Comment by zachleat** [comment]
Shipping withi 2.0.0-beta.2

**Comment by colinaut** [comment]
> I think moving forward we’ll want to standardize on `alpha` instead of `canary` for prereleases in 3.0.

Aww I liked the playfulness of canary. `alpha` is jejune. How about another bird that is also alphabetical like `albatross` or `ashy-throated-bush-tanager` or `apricot-breasted-sunbird`? 

I mean granted an `albatross` release might convey an _entirely different_ meaning than a `canary` release. :)

**Comment by KiwiKilian** [comment]
A strong 👍  on adhering to semver for the next pre-releases. As visible in this screenshot from https://semver.npmjs.com/ it also affects every normal npm install.

![semver](https://user-images.githubusercontent.com/18724559/214508396-9444f033-1af2-4266-bee0-045c2f12bfa2.png)

I do have a plugin which dependens on `@11ty/eleventy` – with a loose depency like `@11ty/eleventy@^2.0.0-canary.1` and the parent project using `@11ty/eleventy@2.0.0-beta.1`. This caused the plugin to install its own latest canary causing errors in the build as main project and plugin used different `@11ty/eleventy` versions.

**Comment by zachleat** [comment]
Just to minimize the impact of this issue I will release a new `canary` with each beta so they’ll match in functionality at least.
