### ISSUE TITLE
--incremental documented as standalone, which is misleading

### ISSUE THREAD

**Issue by sentience** [11ty/eleventy#2760]
The [documentation](https://www.11ty.dev/docs/usage/#incremental-for-partial-incremental-builds) for the `--incremental` flag suggests running this command:

```shell
# Repeat builds only operate on files that have changed
npx @11ty/eleventy --incremental
```

In my testing, this doesn't work as documented. Running that same command multiple times produces a complete build each time. It seems that `--incremental` only works if combined with `--watch` (or `--serve`, which implies `--watch`). Therefore, I suggest that the documentation should be changed:

```shell
# Repeat builds only operate on files that have changed
npx @11ty/eleventy --watch --incremental
npx @11ty/eleventy --serve --incremental
```

Related: #2053

**Comment by zachleat** [comment]
Great feedback, I agree!

**Comment by zachleat** [comment]
Updates are building now!

**Comment by zachleat** [comment]
Cross-linking to new feature #3324
