### ISSUE TITLE
.11ty.js files not rebuilding with --serve

### ISSUE THREAD

**Issue by caseyg** [11ty/eleventy#2774]
### Operating system

macOS Ventura 13.0.1 (22A400)

### Eleventy

2.0.0-beta.1

### Describe the bug

.11ty.js files (e.g. index.11ty.js) are being watched, but not rebuilding when running

`npx @11ty/eleventy --serve`

When I try a Markdown index file instead, it does rebuild as expected.

Here's a debug log of running the above command: https://github.com/caseyg/eleventy-sample/blob/main/terminal.log

Is this possibly an issue with my system/Ventura? First noticed this on another 11ty repo: https://github.com/tweetback/tweetback

### Reproduction steps

1. Clone repo and NPM install
2. run `npx @11ty/eleventy --serve`
3. Edit text returned in `index.11ty.js`
5. See that file is being watched but page content does not refresh, until server is stopped and started manually

### Expected behavior

Expect that content in .11ty.js files will rebuild upon change when `npx @11ty/eleventy --serve` is running

### Reproduction URL

https://github.com/caseyg/eleventy-sample/

**Comment by zachleat** [comment]
Yeah! I just noticed this too and filed #2773 on it (fixed yesterday), will ship with 2.0.0-beta.2.

Thank you!

**Comment by caseyg** [comment]
Awesome! Thanks so much @zachleat!
