### ISSUE TITLE
`compileOptions.permalink` default changed from `true` to `"raw"` for Custom Template Syntaxes

### ISSUE THREAD

**Issue by danburzo** [11ty/eleventy#2780]
### Operating system

macOS Ventura 13.1

### Eleventy

^2.0.0-beta.2 / 1.0.2

### Describe the bug

Found while poking around replacing the built-in Markdown engine (see #2777) that when setting a replacement with `.addExtension('md', { ... })`, [as exemplified in the docs](https://www.11ty.dev/docs/languages/custom/#overriding-a-built-in-template-language), any explicit permalinks present in the frontmatter of `.md` sources will get processed with the replacement engine, as observed a while back (#1019).

This is a problem because most Markdown processors (including `marked` and `remark`) will wrap a plain string such as `/path/to/output/` in `<p>` tags, thus breaking the output. I'm not sure if the default engine skips the Markdown step or whether `markdown-it` simply doesn't wrap a plain string, but the issue only manifests when changing to a different engine.

### Reproduction steps

Eleventy config:

```js
const marked = require('marked');
module.exports = config => {
	config.addExtension("md", {
		compile: inputContent => data => marked.parse(inputContent)
	});
};
```

Content file:

```md
---
title: Hello world
permalink: hello-world/
---

## Heading

Paragraph.
```

Running Eleventy outputs the HTML to `_site / <p>hello-world / < / p>`.

### Expected behavior

If permalinks passing through the Markdown engine is inevitable, it would be great to get enough arguments to the `compile()` function for authors to be able to discern when to skip Markdown processing.

**Comment by danburzo** [comment]
The workaround is to use the `compileOptions.permalink` option, which can be set to `"raw"` in case all permalinks in the project are static. 

For dynamic permalinks, the solution depends on a fix to #2777, as they are not currently pre-processed with Liquid/Nunjucks when the Markdown template engine is swapped.

**Comment by zachleat** [comment]
I think a very good case can be made to make the default `raw` and encourage permalink callback functions in custom syntaxes by default!

**Comment by zachleat** [comment]
Shipping with 3.0.0-alpha.13

**Comment by zachleat** [comment]
Docs deep link https://www.11ty.dev/docs/languages/custom/#compileoptions.permalink-to-override-permalink-compilation

**Comment by danburzo** [comment]
Cool, thanks!

**Comment by jnv** [comment]
I suppose this change disables permalink templating globally, rendering [Use template syntax in Permalink](https://www.11ty.dev/docs/permalinks/#use-template-syntax-in-permalink) and [part of front matter documentation](https://www.11ty.dev/docs/data-frontmatter/) obsolete:

> Note that only the [permalink](https://www.11ty.dev/docs/permalinks/) and [eleventyComputed](https://www.11ty.dev/docs/data-computed) front matter values can contain variables and shortcodes like you would use in the body of your templates.

The fix here is really to put the permalink under `eleventyComputed` (or switch `compileOptions.permalink` back to `true`). In my case, I keep the path of RSS feed in metadata file and reuse it on various part of the site, including the feed's njk template itself. So I put the following into the template's frontmatter:

```
---
eleventyComputed:
  permalink: "{{ metadata.feed.path }}"
```

**Comment by zachleat** [comment]
No @jnv—this change is limited to Custom template languages that did not have a `compileOptions.permalink` default already set in plugin code.

**Comment by jnv** [comment]
@zachleat Thanks for clarification, now I realize it's off topic for this issue since the issue I mentioned affects Nunjucks. I will try to investigate it and open a new issue if I manage to reproduce it with built-in template syntax.
