### ISSUE TITLE
Error generating pages from json data

### ISSUE THREAD

**Issue by bulecampur** [11ty/eleventy#2803]
### Operating system

Windows 11 Home 21H2

### Eleventy

2.0.0

### Describe the bug

I am trying to generate pages from data stored in global data. I am using this: 
``
---
pagination: 
    data: coffeeFeatured
    size: 1
    alias: coffee
permalink: "kaffee/{{ coffee.name | slugify }}/"
layout: base.njk 

---

This is {{ coffee.name }} from {{ coffee.country }}
``
But when I try to build, I receive the error: 

[11ty] Output conflict: multiple input files are writing to `_site/kaffee/{{ coffee.name | slugify }}/index.html`. Use distinct `permalink` values to resolve this conflict.
[11ty]   1. ./src/kaffee/kaffee-pages.njk
[11ty]   2. ./src/kaffee/kaffee-pages.njk
[11ty]   3. ./src/kaffee/kaffee-pages.njk
[11ty]   4. ./src/kaffee/kaffee-pages.njk
[11ty]   5. ./src/kaffee/kaffee-pages.njk (via DuplicatePermalinkOutputError)
[11ty]

### Reproduction steps

1. Serve Eleventy

### Expected behavior

I expected that Eleventy would auto generate pages for each Array in the data in the json file. 

### Reproduction URL

https://github.com/bulecampur/tw-origins-eleventy/settings

**Comment by pdehaan** [comment]
@bulecampur I think you need to remove `eleventyConfig.setDynamicPermalinks(false);` from your .eleventy.js config since you're trying to set dynamic permalinks.

**Comment by bobmonsour** [comment]
@pdehaan is correct. I have been trying to solve this just as an exercise to learn more about pagination. I was pulling my hair out. Removing that line in the config does the trick. Thanks, Peter.

**Comment by bulecampur** [comment]
Thank you so much for your help!
