### ISSUE TITLE
Array pagination fails on serverless

### ISSUE THREAD

**Issue by ryangittings** [11ty/eleventy#2853]
### Operating system

macOS 13.0 (22A380)

### Eleventy

2.0.0

### Describe the bug

The pagination works expected in build:

/build/
/build/2/
The pagination works here in serverless:

/serverless/

But it doesn't work when you go to page 2:

/serverless/2/

### Reproduction URL

https://github.com/ryangittings/11ty-serverless-pagination-issue

**Comment by zachleat** [comment]
Cross posting our social discussion! https://fediverse.zachleat.com/@zachleat/109994443453826167

I am looking at this today!

**Comment by zachleat** [comment]
Alright I did uncover a temporary workaround for you that works in current versions!

```yaml
---js
{
  title: "Posts",
  pagination: {
    data: "collections.post",
    reverse: true,
    alias: "posts",
    size: 2,
    serverless: "eleventy.serverless.path.page",
    serverlessFilter: function(data, key) {
      let chunks = [];
      // this code assumes a page chunk size of 2 and adds them in reverse order
      for(let j=0, k=data.length; j<k; j+=2) {
        chunks.push([data[j+1], data[j]]);
      }
      return chunks[chunks.length - (key || 0)];
    },
  },
  permalink: {
    serverless: ["/serverless/", "/serverless/:page/"],
  }
}
---
```

**Comment by ryangittings** [comment]
Okay, cool! Is there likely to be a new version that fixes this without a workaround?

If not, how would I be able to generate the dynamic previous and next and make them null if we're at the start/end?

**Comment by zachleat** [comment]
This will ship with v2.0.1

**Comment by zachleat** [comment]
Just pushed a small fix here that unlocks the use of multiple serverless URLs in array pagination (including one without a path param)

```
---js
{
  title: "Posts",
  pagination: {
    data: "collections.post",
    reverse: true,
    alias: "posts",
    size: 2,
    serverless: "eleventy.serverless.path.page",
  },
  permalink: {
    serverless: ["/serverless/", "/serverless/:page/"],
  }
}
---
```

Navigating to `/serverless/` now populates the next page link with `/serverless/1/` as expected!

**Comment by ryangittings** [comment]
Yessss! Wonderful stuff. Thank you ever so much.

**Comment by dwkns** [comment]
Does this also solve: 
https://github.com/11ty/eleventy/issues/2544

And remove the need for this documentation change?
https://github.com/11ty/11ty-website/pull/1489

**Comment by zachleat** [comment]
@dwkns let me look!
