### ISSUE TITLE
Feature Request: Option to supply an array of files that are reloaded on ANY file change. 

### ISSUE THREAD

**Issue by dwkns** [11ty/eleventy#2864]
Consider:
```
// eleventy.config.js
const data = require("./data.js");
module.exports = (eleventyConfig) => {
  console.log(`[ data ]:`, data); // equivalent of doing something with the data
 
  return {
    dir: {
      input: "src",
      output: "dist",
      layouts: "_layouts",
      data: "_data",
    },
  };
};
```

And 
```js
// data.js
module.exports = "this is a test";
```

It is super annoying that every time you make a change in `data.js` you have to:
- Restart the dev server; or
- Also make a change in `eleventy.config.js`
If you don't then `eleventy.config.js` doesn't see the change in the dependent file (`data.js`)

Ideally you'd be able to add something like:

eleventyConfig.setServerOptions({
  ...
  alwaysProcess: [ 'eleventy.config.js', 'some-other-dependency.js']
 });

It would certainly make plugin development a lot easier. 

Thoughts?

**Comment by zachleat** [comment]
https://github.com/11ty/eleventy/issues?q=label%3A%22bug%3A+--serve+restart%22+is%3Aclosed might be a good start to look at dupes

**Comment by dwkns** [comment]
Tested on 2.0.0
Minimal repo to reproduce here:
[https://github.com/dwkns/eleventy-issue-2864](https://github.com/dwkns/eleventy-issue-2864)

I saw this [issue](https://github.com/11ty/eleventy/issues/2838) which suggests you've made changes for 2.0.1, but I'm not sure how I can test against that.

**Comment by zachleat** [comment]
I was able to reproduce this on 2.0.0 and can confirm that 2.0.1 fixes it!
