### ISSUE TITLE
If the build file is named "eleventy.js" instead of ".eleventy.js" (dot in front), eleventy opens it in an editor instead of producing output

### ISSUE THREAD

**Issue by scarletcs** [11ty/eleventy#2875]
### Operating system

Windows 11 Home

### Eleventy

2.0.0

### Describe the bug

Eleventy optionally takes an `.eleventy.js` file. This is fine.

However, if the eleventy file happens to be named `eleventy.js`, with no dot in front, eleventy behaves strangely: running `npx @11ty/eleventy` with that file in the directory _opens that file_ rather than reading it. As in, Windows launches my code editor and opens the file in there, and eleventy produces no further output including console output.

### Reproduction steps

<details>
<summary>Minimal package</summary>

package.json

```json
{
  "name": "eleventy-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "npx @11ty/eleventy"
  },
  "author": "",
  "license": "UNLICENSED",
  "dependencies": {
    "@11ty/eleventy": "^2.0.0"
  }
}
```

.eleventy.js

```js
module.exports = function(eleventyConfig) {
  eleventyConfig.addPassthroughCopy("src/bundle.css");
};
```

src/index.md

```md
# Home
```

src/bundle.css
```css
* { box-sizing: border-box; }
```
</details>

1. Create a new directory for an 11ty project named `eleventy-test`.
2. Create a minimal package containing an `.eleventy.js` file, an `index.md`, and a `bundle.css`. A sample package is above.
3. Run `npm run build` or `npx @11ty/eleventy`. Verify there's output in the `_site` directory. Delete it.
4. Rename `.eleventy.js` to `eleventy.js`.
5. Run `npm run build` or `npx @11ty/eleventy` again.
6. Watch Windows open `eleventy.js`, perhaps launching an editor to open it. Verify there is no console output, warnings, or build output.

### Expected behavior

Eleventy should run reading `eleventy.js` just the same as it would `.eleventy.js`, or run as though the file didn't exist (it's not named `.eleventy.js` after all), or fail with an error, and it should optionally alongside any of these options output a warning about `eleventy.js`'s filename.

Under no circumstance would I expect a compiler to open my config files for editing and silently close. I was completely baffled trying to understand what I'd done wrong.

### Screenshots

Build with `.eleventy.js`:

![good run](https://user-images.githubusercontent.com/4585677/226496542-16c44f73-62f8-442c-be2e-791144b65234.png)

Build with `eleventy.js`, note zero task output confirming file generation:

![bad run](https://user-images.githubusercontent.com/4585677/226496383-f0ce176c-3bbe-4ccb-aced-f70b304c17b4.png)
</details>

**Comment by zachleat** [comment]
This is an `npx` thing, unfortunately. I deleted all of the Eleventy code from `node_modules/@11ty/eleventy/cmd.js` and it still performed the same.

`npx @11ty/eleventy` must imply `npx eleventy.js` somehow per `npx` code, which opens the editor. I agree this is weird and confusing but there isn’t much I can do about this one, disappointingly.

Related: https://github.com/npm/cli/issues/3843
