### ISSUE TITLE
Official support for pnpm

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#2876]
Related issues:
* https://github.com/11ty/eleventy-dependency-tree/pull/3
* https://github.com/11ty/eleventy/issues/2142
* https://github.com/11ty/eleventy/issues/1953

**Comment by zachleat** [comment]
Seems to work okay with a standard build on 2.0.1:

```
~/Temp/pnpm-eleventy-test ᐅ pnpm i @11ty/eleventy
 WARN  3 deprecated subdependencies found: glob@7.2.3, inflight@1.0.6, rimraf@2.7.1
Packages: +215
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 215, reused 215, downloaded 0, added 215, done

dependencies:
+ @11ty/eleventy 2.0.1

Done in 2.9s
~/Temp/pnpm-eleventy-test ᐅ pnpm eleventy        
[11ty] Wrote 0 files in 0.01 seconds (v2.0.1)
```

and 3.0.0-alpha.14:

```
~/Temp/pnpm-eleventy-test ᐅ pnpm i @11ty/eleventy@canary
 WARN  3 deprecated subdependencies found: glob@7.2.3, inflight@1.0.6, rimraf@2.7.1
Packages: +52 -88
++++++++++++++++++++++++++++++++++++++++++------------------------------------------------------------------------
Progress: resolved 179, reused 127, downloaded 52, added 52, done

dependencies:
- @11ty/eleventy 2.0.1
+ @11ty/eleventy 3.0.0-alpha.14

Done in 2.4s
~/Temp/pnpm-eleventy-test ᐅ pnpm eleventy               
[11ty] Wrote 0 files in 0.01 seconds (v3.0.0-alpha.14)
```

Merged https://github.com/11ty/eleventy-dependency-tree/pull/3 and released `@11ty/dependency-tree@3.0.1`, shipping with 3.0.0-alpha.15

**Comment by zachleat** [comment]
Merged https://github.com/11ty/eleventy-dependency-tree/pull/3 and released `@11ty/dependency-tree@3.0.1`, shipping with 3.0.0-alpha.15

**Comment by zachleat** [comment]
As part of this work, `pnpm` and `yarn` commands have been added to the docs on:

* Quick Start https://www.11ty.dev/#quick-start
* Getting Started https://www.11ty.dev/docs/
* Command Line Usage https://www.11ty.dev/docs/usage/

As with the other tabs, this selection syncs to the other relevant package manager tabs instances and persists through page loads so you can save your preferred package manager and we’ll show you the same commands throughout the site.

I think that concludes this issue—please let me know if y’all see any further issues—thanks!

**Comment by uncenter** [comment]
> Run npx @11ty/eleventy --serve to start up a [local development server](https://www.11ty.dev/docs/dev-server/) and open http://localhost:8080/ in your web browser of choice to see your web site.

On https://www.11ty.dev/#quick-start, this paragraph contains the hard-coded `npx` command, though there is the new configurable command block/selector right above it.

**Comment by zachleat** [comment]
> > Run npx @11ty/eleventy --serve to start up a [local development server](https://www.11ty.dev/docs/dev-server/) and open http://localhost:8080/ in your web browser of choice to see your web site.
> 
> On https://www.11ty.dev/#quick-start, this paragraph contains the hard-coded `npx` command, though there is the new configurable command block/selector right above it.

Good catch, thank you! Shipping a fix now
