### ISSUE TITLE
Including an njk file doesn't work

### ISSUE THREAD

**Issue by andreapernici** [11ty/eleventy#288]
I get the following error when including template parts from MD files.

```
Problem writing Eleventy templates: (full stack in DEBUG output)
Having trouble rendering template ./index.md (TemplateContentRenderError)
ENOENT: Failed to lookup 'fasce/fascia-acquista.njk' in: _includes, line:6 (RenderError)
ENOENT: Failed to lookup 'fasce/fascia-acquista.njk' in: _includes (Error)
```

but the folder and the file exist inside the _includes folder.

Any hint?

**Comment by andreapernici** [comment]
Uh! Thanks Zac and sorry. Lost that part.

Anyway now I changed the value and I don't get the error anymore, but the included part is not showed the same.

Is there something I'm still missing?

**Comment by andreapernici** [comment]
I tryed to create a new MD file and now the include works, but the .njk included part is not rendered as HTML, but the HTML is converted to text.

This one 
```
<div id="sect-credits">
    <section class="fascia">
        <div class="container text-center">
            <h1 class="fascia-title text-info">Sponsor</h1>
            <hr class="hrSpace20">
            {% for sponsor in sponsors %}
                <a href="{{ sponsor.url }}"><img src="{{ sponsor.image }}" class="img-responsive center-block lazy"></a>
            {%- endfor %}
        </div>
    </section>
    <hr >
</div>
```

is converted in 

![sponsor2](https://user-images.githubusercontent.com/1017981/47723199-4c48c080-dc54-11e8-9d42-0474cd6dc715.png)

**Comment by andreapernici** [comment]
Figured out the problem was the indentation inside the fasce/fascia-acquista.njk file.

Is it possible?

**Comment by edwardhorsford** [comment]
I suspect this might be related to #219.

There's a couple solutions in that thread, but FWIW I'm still having a **nightmare** with it. It's by far the most fragile part of my site - enough that I'm considering ditching markdown rendering, or trying to do it some other way.

**Comment by andreapernici** [comment]
Tried your settings, but nothing changes.

Now I'm going on removing indentation. Thanks for the help @edwardhorsford

**Comment by edwardhorsford** [comment]
I've ended up using the settinsg, adding hyphens before and after nunjucks code, and stripping many comments. *Still* I have issues. It's very frustrating. I'd love to have markdown rendering disabled in macros.

**Comment by zachleat** [comment]
Hmm, I think you might be misunderstanding @edwardhorsford but we should take your question to a new issue maybe?

Markdown isn’t rendered in macros. Nunjucks processing takes place before Markdown processing. So all Nunjucks processing happens first (including macros) and then the output is run through markdown conversion.

Whitespace is important in markdown, specifically this is the part of the spec y’all are running into:
https://spec.commonmark.org/0.28/#indented-code-blocks

For debugging, try using:
```
---
templateEngineOverride: njk
---
```
to remove the markdown processing and look at the output generated by Nunjucks.

https://www.11ty.io/docs/languages/#overriding-the-template-language

Please reopen with additional questions!
