### ISSUE TITLE
Serve does not work in Firefox

### ISSUE THREAD

**Issue by rdimartino** [11ty/eleventy#2881]
### Operating system

macOS Ventura 13.1

### Eleventy

2.0.0

### Describe the bug

`npx @11ty/eleventy --serve` does not work in Firefox (111.0.1)

I followed the [getting started](https://www.11ty.dev/docs/getting-started/) guide and I get a 404 when attempting to view the served content in Firefox. It works in Safari.

### Reproduction steps

1. `npx @11ty/eleventy --serve`
2. Open `http://localhost:8080/` in Firefox
3. Expect to see the sample content, but I get a 404 instead

### Expected behavior

See the content

### Screenshots

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/11539300/227326445-21e1c2a6-0e0c-47f4-970a-52c4c402f416.png">

**Comment by zachleat** [comment]
Can you confirm the contents of your output folder (probably `_site`)?

**Comment by rdimartino** [comment]
```
$ find _site -type f
_site/index.html
_site/README/index.html
```

**Comment by rdimartino** [comment]
Hmmm. I can't recreate it any more either. Not sure what changed, but it works for me now. Sorry for the trouble.

**Comment by zachleat** [comment]
No worries!
