### ISSUE TITLE
Nested Shortcodes not working with Nunjucks and Eleventy Edge

### ISSUE THREAD

**Issue by joepavitt** [11ty/eleventy#2882]
### Operating system

MacOS Ventura 13.0

### Eleventy

2.0.0

### Describe the bug

Detailed here: https://github.com/11ty/eleventy/discussions/2879

Broken when used in a `.njk` file:
```njk
{% edge %}
    {% myshortcode %}
        Text Goes Here
    {% endmyshortcode %}
{% endedge %}
```

Workaround:
```njk
{% edge "liquid" %}
    {% myshortcode %}
        Text Goes Here
    {% endmyshortcode %}
{% endedge %}
```

### Reproduction steps

1. Setup Eleventy Edge
2. Create a paired shortcode in the Eleventy Edge config
3. Render this inside an `{% edge %}` template, within a nunjucks file.
4. Note that it doesn't render

### Expected behavior

`{% edge %}` shouldn't require `"liquid"` to be passed given that the documentaiton says they should work with nunjucks

**Comment by joepavitt** [comment]
Related to https://github.com/11ty/eleventy/issues/2585

**Comment by zachleat** [comment]
I was able to reproduce this one on https://github.com/11ty/demo-eleventy-edge/

**Comment by zachleat** [comment]
Per the Eleventy Community Survey results and our refocus and prioritization towards our roots as a static site generator, we’re going to be deprecating Edge in 3.0 and closing issues related to the Edge plugin. I’m very sorry to have to do this—but unfortunately this was a necessary decision to allow the project to continue forward.

Read more:
https://www.zachleat.com/web/eleventy-side-project/
https://www.11ty.dev/blog/community-survey-results/
