### ISSUE TITLE
files not being updated using addPassthroughCopy

### ISSUE THREAD

**Issue by joelanman** [11ty/eleventy#2888]
### Operating system

macOS 13.2.1

### Eleventy

2.0.0

### Describe the bug

Thanks for all your work!

Maybe I'm misusing or misunderstood, but having problems with addPassthroughCopy. I have it set to `assets`. When I renamed an image file, it didn't get copied until I restarted 11ty serve command, and the old file remained in the _site folder.

### Reproduction steps

Using this config:
```
eleventyConfig.addPassthroughCopy("assets");
```

1. Add file `/assets/images/cookies sticker - cloud convert.svg`
2. Rename that file to `cookies.svg`

The file in _site was not renamed. When I stopped and started `npx @11ty/eleventy --serve`, the new file appeared but the old file remained

### Expected behavior

The file is renamed in _site without having to restart `npx @11ty/eleventy --serve`

**Comment by zachleat** [comment]
Related to #2798 and #19

That said I would expect a new `cookies.svg` to trigger a build if its matches a passthrough copy location. I ran a quick test and verified in a simple project that this behavior does work, so there might be another circumstance happening here. Can you run Debug mode and provide the `Watching for changes to:` line?

https://www.11ty.dev/docs/debugging/

Mine looked like:

```
  Eleventy Watching for changes to: [ './package.json', './**/*.{liquid,ejs,md,hbs,mustache,haml,pug,njk,html,11ty.js,11ty.cjs}', './assets/**', './_includes/**', './_data/**', './.gitignore', './.eleventyignore', './.eleventy.js', './eleventy.config.js', './eleventy.config.cjs', './**/*.{json,11tydata.cjs,11tydata.js}' ] +5ms
  Eleventy Ignoring watcher changes to: [ '_site/**', './**/node_modules/**', './.git/**' ] +0ms
```

**Comment by joelanman** [comment]
Thanks! I just tried again and couldn't replicate, sorry about that. I'll close this and keep an eye on if it happens again
