### ISSUE TITLE
Accessing rendered data from custom collections

### ISSUE THREAD

**Issue by edwardhorsford** [11ty/eleventy#289]
I'm using quite a few custom collections to create groups of content.

I've found though that items provided with `collections.getAll()` don't have the rendered value in `renderData`. Is it possible to get the rendered value?

For reference, I want to create a page that lists all the titles of all the content in a collection - but the tiles are dynamic (they're paginated pages) and rely on `renderData`.

**Comment by zachleat** [comment]
Confirmed that something like this does not have the rendered `renderData` values:

```
{% for post in collections.dog %}{{ post.data.renderData.key2 }}{% endfor %}
```

**Comment by gerwitz** [comment]
I know renderData is a bit of a stopgap, but I'd really love to have this working (for dynamic titles, defined in layouts).

**Comment by zachleat** [comment]
Shipping with the next minor version

**Comment by edwardhorsford** [comment]
Woop! thanks @zachleat
