### ISSUE TITLE
Build process on `--serve` not triggered for `.webc` files

### ISSUE THREAD

**Issue by lucaorio** [11ty/eleventy#2896]
Hello! 👋 I am running Eleventy `2.0.1`.

As shown in the log below, it looks like by running `--serve` the dev server is watching and picking up the updates and triggering a reload, but the build process writes the file without changes.

```
[11ty] Watching…
[11ty] File changed: src/components/navigation.webc
[11ty] Writing dist/index.html from ./src/index.webc
[11ty] Copied 6 files / Wrote 1 file in 0.02 seconds (v2.0.1)
```

Restarting the dev server triggers the build correctly, but the changes made after that are still not reflected in the subsequent builds!

**Comment by zachleat** [comment]
I think there are a few scenarios in which this is still a problem. I’m going to move it over to the eleventy-plugin-webc repo to keep these in the same spot
