### ISSUE TITLE
Add built-in RSS generation

### ISSUE THREAD

**Issue by cferdinandi** [11ty/eleventy#29]
I'm sure one could bolt something in after the fact, but it would be great to create an RSS feed from content so this can be used for a blogging platform without all of the bloat of something like Hugo or Jekyll.

**Comment by zachleat** [comment]
https://github.com/11ty/eleventy-base-blog is up!

Specifically https://github.com/11ty/eleventy-base-blog/blob/master/feed/feed.njk
