### ISSUE TITLE
templateEngineOverride breaks permalink shortcode

### ISSUE THREAD

**Issue by VAggrippino** [11ty/eleventy#2906]
### Operating system

Window 11 (WSL Ubuntu 20.04)

### Eleventy

2.0.1

### Describe the bug

When I use a shortcode in a permalink and `templateEngineOverride` it breaks the permalink and creates a directory in the output folder named with the Liquid or Nunjucks tag that was supposed to execute the shortcode.

**However**, this only happens on the second and subsequent page builds when using `npx @11ty/eleventy --serve`. When the site is built with `npx @11ty/eleventy` it works properly and executes the shortcode. It also works fine on the first build after executing `npx @11ty/eleventy --serve`. The problem only happens when modifying the page with the `templateEngineOverride` while `npx @11ty/eleventy --serve` is running and the page with the `templateEngineOverride` is running.

e.g.: a directory named `{% shortDate page.date %}`

I've created a repo with a more thorough explanation and demonstration of the problem here: https://github.com/VAggrippino/11ty-shortcode-bug

There are a few solutions that make this problem pretty easy to work around. I doubt anyone will want to take the time to figure it out. Still, it was a problem that took me some time to understand. Maybe it warrants a warning box in the section that explains `templateEngineOverride`?

### Reproduction steps

1. Create a shortcode in `.eleventy.js`:
```js
eleventyConfig.addShortcode("shortDate", function (date) {
  const year = date.getFullYear();
  const month = (date.getMonth() + 1).toString().padStart(2, 0);
  return `${year}/${month}`;
});
```
2. Use the shortcode in a permalink and set a `templateEngineOverride`:
```
permalink: "/{% shortDate page.date %}/{{ page.fileSlug }}/"
templateEngineOverride: md
```
3. `npx @11ty/eleventy --serve`
4. Make a change to the file with the `templateEngineOverride`
5. Check your output directory to see the folder named `{% shortDate page.date %}`. Also note that collection items will have a `url` property pointing to the new folder with characters that aren't valid in a URL.

### Expected behavior

I guess I'd expect it not to generate invalid URLs. And to generate an error if it can't generate a valid URL from the data it has.

Before reading [Use Template Syntax in Permalink](https://www.11ty.dev/docs/permalinks/#use-template-syntax-in-permalink) more carefully, I thought Front Matter processing was independent of the rest of the template.

### Reproduction URL

https://github.com/VAggrippino/11ty-shortcode-bug

**Comment by VAggrippino** [comment]
This problem may only exist with my particular development environment configuration. If I close VSCode and edit files with Vim instead everything works as expected.

It could be argued that breaking template tags in permalinks is the expected behavior because of the "parsed with the current template’s rendering engine" statement [on the Permalinks page](https://www.11ty.dev/docs/permalinks/#use-template-syntax-in-permalink). As long as I'm not using VSCode, this works as I initially expected it to.

For more detailed information about how I got here, see my help forum post in the Discord: https://discord.com/channels/741017160297611315/1096864284564279367

I'm still reluctant to close this...

- Why does it rebuild the site with every keystroke?
- Why does whatever VSCode is doing break Eleventy's build process?

**Comment by zachleat** [comment]
The `permalink` syntax is tied to the template syntax. So if you override the template to markdown, it will render as plaintext (since Eleventy specifically ignores markdown syntax in permalink).

The most robust solution here is to use a JavaScript function for `permalink` instead of a a template string.

The computed data docs touch on this a bit: https://www.11ty.dev/docs/data-computed/

**Comment by koitsu** [comment]
@VAggrippino I can't comment on the true underlying behaviour of this software, but I can comment subjectively on the "refresh on every keystroke" part (at least on Linux) and with vim (and I suspect other editors do this as well).

Linux kernel offers a feature called [inotify](https://en.wikipedia.org/wiki/Inotify) which allows a userland program to "track" or "be informed of" file activity (read, write, delete, modify, etc.).  I believe this can be applied to a directory as well.  11ty, either directly or indirectly, relies on some other Node.js module that uses this kernel feature.  The `--watch` flag is what enables this feature -- although you aren't mentioning use of it, I suspect it is involved here.

What happens under the hood is that the userland application tells the kernel "tell me when you see I/O of any kind on files X/Y/Z".  Now you open your text editor and begin to edit one of the files which is being watched in this fashion.

Different editors have different behaviours.  Vim, for example, is notorious about continually writing to disk *every single operation* you do (read: every keystroke), usually done in a `.swp` file located within the same directory as whatever it is you're editing (although you can override this in your .vimrc if you wish, such isn't ideal).  Lo and behold, every single time you type a character, this temporary work file is updated, causing the software using inotify to be told to do something -- which in this case is probably rebuild the site.

I have seen several other static site generators which offer built-in webservers and inotify/filesystem watch capabilities have this exact same problem.  The solution, for vim that is, is to have that software automatically exclude a list of known file extensions from their watch list.  `.swp` is one such default that is pretty universal, but web developers -- for some reason -- never seem to be aware of this editor behaviour despite it being so prevalent.  I know nothing about Webpack so I cannot comment on that.

As for the WS/WebSocket part is as follows: when a client (web browser) visited the site hosted with `--serve`, there is a long-living TCP connection established between the client (browser) and server (11ty in `--serve` mode).  The server can therefore tell the client to do something -- such as dynamically refresh content, etc. -- whenever it wishes.  I'm sure you can put two and two together with regards to how this could manifest with `--serve --watch` if things run amok.

I suspect Neovim's temporary work file model is substantially different from that of Vim -- possibly it does not use one, possibly it uses one but puts it in /tmp or some other location (read: not a directory that 11ty would be watching), I simply do not know.

HTH, that's all I can offer on this thread.

**Comment by VAggrippino** [comment]
I'm using WSL which is Windows but also sort of Linux. It's basically a VM running on Microsoft's Hyper-V, but it's very tightly integrated into the host operating system. A more detailed explanation doesn't belong here, but I can tell you that applications using inotify only work if I'm working with files on the ext4 filesystems in the WSL instance. If I work on host drives; e.g. *C:*, which is mounted at `/mnt/c` in WSL; inotify doesn't work at all. My project directories are all on the ext4 filesystems for this reason.

### It's not inotify
I tested with both Vim and Neovim and Eleventy doesn't build after every keystroke like it does with VSCode. Besides, the way Neovim writes swap files is identical to the way Vim does it. See `:help swap-file` in either program.

VSCode *doesn't* write files in the project directory or even on the same mount point / filesystem when I make a change without saving. It writes its temporary files in `%APPDATA%\Code\User\WorkspaceStorage` on the host operating system.

It may be inotify that allows it to rebuild when the files it's watching change, but it's something different that's causing it to rebuild when I press keys in VSCode.

### Vim / Neovim are not a problem
When I use Vim **or** Neovim, `npx @11ty/eleventy --serve` does not build the pages after every keystroke like it does when I'm editing with VSCode and it also processes the shortcode in the permalink properly even with `templateEngineOverride: md` set.

### `--watch` with `--serve` is not a problem
I haven't been using the `--watch` argument at all, but it's clear that `--serve` also does `--watch`. Both by it's behavior and the fact that that's how [it's documented](https://www.11ty.dev/docs/usage/#re-run-eleventy-when-you-save).

### Duck test
The reason I believe it's using websockets is that Webpack dev server works the exact same way: update the page after every key stroke. And BrowserSync, [used by `npx @11ty/eleventy --serve`](https://www.11ty.dev/docs/usage/#re-run-eleventy-when-you-save) does support websockets (see [the options](https://browsersync.io/docs/options#option-socket)).

### Further testing
I also did some testing on a real Linux system using the native Linux VSCode and couldn't reproduce the problem at all. It didn't build the page after every keystroke, only after actually saving the file. This supports what I said [here](https://github.com/11ty/eleventy/issues/2906#issuecomment-1512030545). This is a problem with VSCode on WSL.

I can provide a little additional information that I discussed in the Eleventy Discord thread I linked to earlier... VSCode on WSL runs several server processes to support integration between the editor running on the host and the shell running inside WSL. These processes are all setup, configured, and executed automatically without requiring any user intervention. You don't run VSCode on WSL without these processes. *This* is what's telling BrowserSync to build the site after every keystroke.

### *My* Conclusion
This is Microsoft's fault... and the fault of proprietary software. I've got no idea what those server processes are actually doing and M$ has made it very clear that not all components of VSCode are Open Source Software. Eleventy has no fault or obligation here.

On the other hand, I think a lot of people are using this setup. It might be valuable to disable this build-on-keystroke behavior that, to me at least, seems more annoyance than feature. It's not really clear that build-on-keystroke is breaking the shortcode in the permalink. It may be just a coincidence.

This is *my* conclusion, but I'm nobody. I'm just trying to be as useful as I can to people who matter because Eleventy is awesome.

#### Side note
> The `permalink` syntax is tied to the template syntax. So if you override the template to markdown, it will render as plaintext (since Eleventy specifically ignores markdown syntax in permalink).

This is what I understood after reading the referenced documentation more carefully. However, with respect and gratitude to @zachleat for creating this, I have to say that it turns out that this isn't true. **If I override the template to markdown, it will render any shortcodes in the permalink** unless I'm using VSCode on WSL.
