### ISSUE TITLE
Reusing 11ty shortcodes on the Edge ⚡️

### ISSUE THREAD

**Issue by ryangittings** [11ty/eleventy#2911]
### Operating system

macOS 13.3

### Eleventy

2.0.1

### Describe the bug

So, I'm trying to use a shortcode on the Edge. I want to re-use the same one as the main eleventyConfig file. I have an npm dependency function within the filter in my actual use case.

How can I use this shortcode on edge, too, with one source of truth?

### Reproduction URL

https://github.com/ryangittings/11ty-edge-issue

**Comment by zachleat** [comment]
Per the Eleventy Community Survey results and our refocus and prioritization towards our roots as a static site generator, we’re going to be deprecating Edge in 3.0 and closing issues related to the Edge plugin. I’m very sorry to have to do this—but unfortunately this was a necessary decision to allow the project to continue forward.

Read more:
https://www.zachleat.com/web/eleventy-side-project/
https://www.11ty.dev/blog/community-survey-results/
