### ISSUE TITLE
Multiple custom filter which I can't get to work

### ISSUE THREAD

**Issue by rocc-o** [11ty/eleventy#2925]
### Operating system

Windows 10 

### Eleventy

2.0.0

### Describe the bug

I have html in front matter:
```
---
details: This is <strong>strong</strong> and this is <em>italic</em>
---
```
that renders with Nunjucks `safe`

`{{ post.data.details | excerpt | safe }}`

but with `excerpt` filter:
```
eleventyConfig.addFilter("excerpt", (post) => {
  const content = post.replace(/(<([^>]+)>)/gi, "");
  return content.substr(0, content.lastIndexOf(" ", 120)) + "...";
});
```
html is not rendered anymore, only `excerpt` works.
Why? [mozilla.github.io/nunjucks/templating.html#safe](https://mozilla.github.io/nunjucks/templating.html#safe)

**Comment by rocc-o** [comment]
I made it work with {{ post.data.details | truncate(120) |  | safe }}
Without custom filter excerpt. Maybe some conflict?

**Comment by pdehaan** [comment]
> _"html is not rendered anymore, only excerpt works."_

I think I'm confused. Your custom `excerpt` filter RegExp will strip any HTML tags from the string: `const content = post.replace(/(<([^>]+)>)/gi, "");`.

So if I tweak the `excerpt` filter to this:
```diff
  eleventyConfig.addFilter("excerpt", (post) => {
    const content = post.replace(/(<([^>]+)>)/gi, "");
+   console.log({ post, content });
    return content.substr(0, content.lastIndexOf(" ", 120)) + "...";
  });
```

and have an input file, src/index.njk, that looks like this:
```html
---
details: This is <strong>strong</strong> and this is <em>italic</em>
---

<div>
{{ details | excerpt | safe }}
</div>
```

Then the `excerpt` filter render this:
```html
<div>
This is strong and this is...
</div>
```

And log this:
```js
{
  post: 'This is <strong>strong</strong> and this is <em>italic</em>',
  content: 'This is strong and this is italic'
}
```

So also a bit curious that it's truncating the string, even though "This is strong and this is italic" is only 33 characters.

**Comment by rocc-o** [comment]
And I was even more confused as I didn't notice the RegExp. 
I've noticed that character count also includes html tags, so that's 59, but only 26 of 120 are rendered (!)
Anyway, with Nunjucks `truncate()` the character rendering is perfect, not one more, not one less.

**Comment by pdehaan** [comment]
Nice!

Just be aware of the _slight_ edge case depending on your HTML complexity+attributes:

```njk
---
details: This is <strong id="foo">strong</strong> and this is <em>italic</em>
---

<div>
{{ details | truncate(28) | safe }}
</div>
```

```html
<div>
This is <strong...
</div>
```
