### ISSUE TITLE
Need advice on showing list of element grouped by tag

### ISSUE THREAD

**Issue by andreapernici** [11ty/eleventy#293]
I'm experimenting with collections in order to create various list of items and showing them as parte of the home page.

For example:

Home Page:
 - hero
 - text
 - sponsor (and this section should show groups of items of the same category/tag)
 -- supporter
 -- media supporter
 -- partner
 -- etc etc

and inside the group itself I'd like to be able to sort things up, but also be able to order the various group in any way and for example showing them in the following order

- sponsor
-- partner
-- supporter
-- media supporter
-- etc etc

Is there a way to accomplish this?

I already created the "sponsors" collection with single MD for each sponsor and tags to group them, but I don't find an example on how to group/order/show them inside a piece of template using the markdown declaration.

Thanks.

**Comment by zachleat** [comment]
Does something like this example work for you? https://www.11ty.io/docs/collections/#sort-descending You can use your own filter there too, I think.

**Comment by andreapernici** [comment]
At the end I went all with macros.
