### ISSUE TITLE
Deletion of _site is needed

### ISSUE THREAD

**Issue by bsastregx** [11ty/eleventy#2936]
### Is your feature request related to a problem? Please describe.

Sometimes I need to delete the _site folder, stop the server and re-start to see the reflected changes.
As an example:

1. I have a collection of 'posts'. index.njk displays the collection of posts.
2. I remove the 'post' tag from all the posts.
3. I reload the browser, and I still see index.html with the list of posts (expected behavior: index.html shouldn't exist at all, since there is no collection of posts).
4. I stop the server
5. Delete _site
6. Start the server
7. Now I go to the home page and I get `Cannot GET /` which is the expected behavior, since the collection of posts is empty.

**What I would expect to happen**:
1. I have a collection of 'posts'. index.njk displays the collection of posts.
2. I remove the 'post' tag from all the posts.
3. I reload the browser, and when I go to the homepage I get `Cannot GET /` which is the expected behavior, since the collection of posts is empty.

As you can see, 3 steps is much better than 7.

### Describe the solution you'd like

**What I would expect to happen**:
1. I have a collection of 'posts'. index.njk displays the collection of posts.
2. I remove the 'post' tag from all the posts.
3. I reload the browser, and when I go to the homepage I get `Cannot GET /` which is the expected behavior, since the collection of posts is empty.

**Comment by brfignoni** [comment]
@pdehaan Thank you for this soultion. It works nice.
