### ISSUE TITLE
`include` fails silently when inside `if` condition

### ISSUE THREAD

**Issue by pmpinto** [11ty/eleventy#2949]
### Operating system

macOS Ventura 13.3

### Eleventy

2.0.1

### Describe the bug

In a `post.njk` layout I have the following:
```njk
{% if related.length > 0 %}
  {% set posts = [] %}
  {% for path in related %}
    {% set post = collections.post | where('inputPath', path) %}
    {% set posts = (posts.push(post), posts) %}
  {% endfor %}

  {% include "_post-grid.njk" %}
{% endif %}
```

In that `_post-grid.njk` I have something like the following:
```njk
<section class="post-grid">
  <ol class="post-grid__list">
    {% for post in posts %}
      <li class="post-grid__item">
        <a href="{{ post.url }}" class="post-grid__link">
          <div class="post-grid__photo">
            {% image
              post.data.cover,
              post.data.title,
              "(min-width: 1024px) 50vw, (min-width: 768px) 80vw, 100vw",
              "post-grid__image"
            %}
          </div>
        </a>
      </li>
    {% endfor %}
  </ol>
</section>
```

Issue: the `_post-grid.njk` is not imported.
There are 2 things that I know of that can make it work as expected:
* Moving the `{% if related.length > 0 %}` condition inside the `_post-grid.njk` (as `posts.length` instead)
* Commenting out the `{% image %}` block

I checked that `posts` is indeed filled. That's checkable both in the layout as well as in the included file.
Makes absolutely no sense to me… 🤷‍♂️

**Comment by pmpinto** [comment]
Here's my `image` tag in case it's relevant:

```js
  eleventyConfig.addShortcode("image", async function (src, alt, sizes, classname) {
    let metadata = await Image(src, {
      widths: ["auto", 384, 768, 1440, 2160],
      formats: ["jpeg"],
      urlPath: '/static_assets/photos/',
      outputDir: './dist/static_assets/photos/',
      sharpJpegOptions: {
        quality: 80
      },
      filenameFormat: function (id, src, width, format, options) {
        const extension = path.extname(src);
        const name = path.basename(src, extension);
        return `${name}-${width}w.${format}`;
      },
    });

    let imageAttributes = {
      alt,
      sizes,
      class: classname,
      loading: "lazy",
      draggable: "false",
      decoding: "async",
    };

    // You bet we throw an error on a missing alt (alt="" works okay)
    const imageHTML = Image.generateHTML(metadata, imageAttributes)

    return imageHTML;
  });
```


And the `where` filter, in case you're wondering:
```js
  eleventyConfig.addFilter('where', (collection, field, value) => {
    if (!field || !value) {
      return collection
    }

    return collection.find((item) => item[field] === value)
  })

```

**Comment by pdehaan** [comment]
Possibly interesting: https://github.com/11ty/eleventy/issues/1639 and https://github.com/mozilla/nunjucks/issues/838

Apparently there is an undocumented Nunjucks `ifAsync...endif` tag which might do the trick. Unclear on whether _post-grid.njk needs to use `{% asyncEach post in posts %}` instead of the `{% for post in posts %}` (https://mozilla.github.io/nunjucks/templating.html#asynceach)

**Comment by pmpinto** [comment]
@pdehaan Thanks for the tips, it looks like it would be able to solve it. I'll check this later and comment back with the results 👍

**Comment by pmpinto** [comment]
Indeed, `ifAsync` does the trick! Very much appreciated 🙇‍♂️ 

As a solution for the snippet I shared above, here's the working code:
```njk
{% ifAsync related.length > 0 %}
  {% set posts = [] %}
  {% for path in related %}
    {% set post = collections.post | where('inputPath', path) %}
    {% set posts = (posts.push(post), posts) %}
  {% endfor %}

  {% include "_post-grid.njk" %}
{% endif %}
```

I first tried replacing `for` with `asyncEach` instead, and that didn't work for me. After replacing `if` with `asyncIf` I went back to `for` and it worked just fine.
