### ISSUE TITLE
Allow pairedShortcode to strip indentation whitespace

### ISSUE THREAD

**Issue by thylo** [11ty/eleventy#2955]
### Is your feature request related to a problem? Please describe.

Hello,

In an effort to allow "non tech" people to edit the content of their website directly into the code (without creating multiple YAML fields in frontmatter or using a CMS), I discovered the neat [Render plugin](https://www.11ty.dev/docs/plugins/render/) and the `{% renderTemplate 'md' %}`.

This is what I came up with : 

`about.liquid`
![Capture d’écran 2023-05-31 à 11 43 26](https://github.com/11ty/eleventy/assets/1242863/6bdf94c8-6275-4f14-9aee-86903f862c5a)

It looks great and It's super easy for non-tech people to edit

Sadly, it won't work as it seems the `renderTemplate` shortcode is passing the indentation spaces along to the markdown compiler. Which markdown compiler doesn't like.

This however is working great but looks terrible and makes it hard to read :
![Capture d’écran 2023-05-31 à 11 46 13](https://github.com/11ty/eleventy/assets/1242863/4b36b721-b3f9-41c6-b4e6-ef83a2397752)

It's a bit silly, but I like to keep things tidy and indented properly :-P

### Describe the solution you'd like

I currently have no clue of how to achieve it but it would be neat to have an option to get the pairedShortcode's content without the extra whitespaces. 

Instead of `&nbsp;&nbsp;&nbsp;### Some Title\n&nbsp;&nbsp;&nbsp;#### Some subtitle` , getting `### Some Title\n#### Some subtitle`

**Comment by uncenter** [comment]
You might be interested in using Nunjucks/Liquid content blocks! You can define blocks in your pages and use them inside your templates. If you make a thread on the [community Discord](https://www.11ty.dev/blog/discord/) you might get more responses btw.

**Comment by pdehaan** [comment]
I think you can wrap the `renderTemplate` shortcode in a custom shortcode that preprocesses the string with [**dedent**](https://www.npmjs.com/package/dedent) or something similar:

### src/about.liquid
```liquid
---
title: About
---

<!doctype html>
<html lang="en">
<body>

<section>
  <div>

    {% renderTemplate "md" %}
      # I am a title

      * I am a list
      * I am a list
    {% endrenderTemplate %}
    
  </div>
</section>

</body>
</html>
```

### eleventy.config.js

```js
const { EleventyRenderPlugin } = require("@11ty/eleventy");
const dedent = require("dedent");

/**
 * @param {import("@11ty/eleventy/src/UserConfig")} eleventyConfig
 * @returns {ReturnType<import("@11ty/eleventy/src/defaultConfig")>}
 */
module.exports = function (eleventyConfig) {
  eleventyConfig.addPlugin(EleventyRenderPlugin);

  eleventyConfig.addPairedShortcode("renderTemplate", function (content, lang) {
    return eleventyConfig.javascriptFunctions.renderTemplate(dedent(content), lang);
  });

  return {
    dir: {
      input: "src",
      output: "www",
    }
  };
};
```

### OUTPUT (www/about/index.html)

```html
<!doctype html>
<html lang="en">
<body>

<section>
  <div>

    <h1>I am a title</h1>
<ul>
<li>I am a list</li>
<li>I am a list</li>
</ul>

    
  </div>
</section>

</body>
</html>
```

**Comment by thylo** [comment]
Thank you @pdehaan ! It's working flawlessly. I wasn't aware of this `dedent` module. It's now fairly easy to edit the content for non HTML fluent people.
