### ISSUE TITLE
Need advice: is it possible to pass the filter value to a collection dynamically

### ISSUE THREAD

**Issue by andreapernici** [11ty/eleventy#296]
I'm trying to use the filter capabilities like the following

```
module.exports = function(eleventyConfig) {
  // Get only content that matches a tag
  eleventyConfig.addCollection("myPosts", function(collection) {
    return collection.getFilteredByTag("post");
  });
};
```

but I'd like to make it dynamic and allow the user to pass the tag value inside for example a shortcode.

Is there some documentation on how to do that?

**Comment by zachleat** [comment]
Say you have a `myTag` variable in your template that has the value of the dynamic collection you’re trying to retrieve. You can just use that as the object key on your `collections` global.

https://www.11ty.io/docs/collections/

```
{%- for post in collections[ myTag ] -%}
<!-- do something -->
{%- endfor -%}
```

Does that make sense?

**Comment by andreapernici** [comment]
I ended up stop using Collections for my needs as @jevets suggested.

**Comment by koitaki** [comment]
Thanks for your comment Zach, I was able to create a collections page that had a dynamic tag input based on Front Matter.  Eg:

**songs/songs.md**
---
title: Songs
layout: 'layouts/collection.njk'
eleventyExcludeFromCollections: true
collection: songs
---

**pictures/pictures.md**
---
title: Pictures
layout: 'layouts/collection.njk'
eleventyExcludeFromCollections: true
collection: pictures
---

**layout/collections.njk**
{%- for post in collections[collection] -%}
          <img src="{{ site.images }}{{ post.data.imageMain }}">
          <span>{{ post.data.title }}</span>
          {{ post.data.excerpt | safe }}
          <p>Updated: {{ post.date | date("dddd Do MMM YYYY") }}</p> 
        <div><a href="{{ post.url }}">Read more</a></div>
{%- endfor -%}
