### ISSUE TITLE
How to pass a variable to a shortcode

### ISSUE THREAD

**Issue by andreapernici** [11ty/eleventy#298]
I'm trying to create a shortcode that needs to have in input variables

```
eleventyConfig.addShortcode("twittershare", function(canonicalUrl, textToShare, viaName, hastagName) {

	    return `<a target="_blank" href="https://twitter.com/share?url=${ canonicalUrl }&text=${ textToShare }&via=${ viaName }&hashtags=${ hastagName }" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;" class="twitter">Share</a>`;
	});
```

but calling it this way

`{% twittershare "{{ canonical }}", "{{ title }}", "{{ config.twitterViaName }}", "{{ config.twitterHashtagName }}" %}`

doesn't work and the same with

`{% twittershare {{ canonical }}, {{ title }}, {{ config.twitterViaName }}, {{ config.twitterHashtagName }} %}`

I don't understand which is the syntax I should use.

```
Error writing templates: (full stack in DEBUG output)
> Having trouble writing template: _site/news/2/index.html (TemplateWriterWriteError)
> (unknown path)
  TypeError: body is not a function (Template render error)

```

**Comment by edwardhorsford** [comment]
I've not used shortcodes, but you almost certainly don't want curly braces inside of the shortcode.

Try something like:
`{% twittershare canonical , title, config.twitterViaName, config.twitterHashtagName %}`

**Comment by andreapernici** [comment]
Thanks. It works. I only get an undefined for canonical cause of this https://github.com/11ty/eleventy/issues/297#issuecomment-434855189
