### ISSUE TITLE
[trouble]: setFrontMatterParsingOptions behave weirdly

### ISSUE THREAD

**Issue by vadiae** [11ty/eleventy#2981]
### Operating system

debian 12

### Eleventy

2.0.1

### Describe the bug

Hi,

1. As said in the title, setFrontMatterParsingOptions behave weirdly. I have followed the [documentation](https://www.11ty.dev/docs/data-frontmatter-customize/#changing-where-your-excerpt-is-stored) to generate excerpts.

I am using the 'description' tag to store my excerpts in the frontmatter of each notes.
`.eleventy.js`
```js
  eleventyConfig.setFrontMatterParsingOptions({
    excerpt: true,
    excerpt_alias: 'description'
  });
```

then, I use it in my feed
`notefeed.html`
```html
<ul class="notefeed">{% for notes in collections.notes %}
  <li class="notefeed-note">
    <a href="{{ notes.page.url }}">
      <span class="larger">{{ notes.data.title }}</span>
        {% if notes.data.description != nil %}
          {{ notes.data.description | markdownify }}
        {% endif %}
    </a>
  </li>{% endfor %}
</ul>
```

What is weird, is that the excerpt generated have kinda-randomly something more than the content of the description.
Here, it shows the start of the note, with it's index : 
![image](https://github.com/11ty/eleventy/assets/128595105/33638ff1-7872-4fa9-928c-0575fa3ff7bf)

I don't see any reason to add the start of the note, other notes don't behave like that… I'm lost.

2. The second weird behavior, not directly linked I think, is that the code is adding rogue `<p>` in my feed for… reasons.

```html
<li class="notefeed-note">
  <a href="/notes/(In)visibilité">
    <span class="larger">(In)visibilité</span>
      <p>
          <p>À propos de visibilité, ou plutôt, pourquoi j'aimerais rester invisible.
          </p>
      </p>
  </a>
</li>
```
There should only be a unique `<p>`, not 2.. The string stored in description is a string, that's all, and is markdonified, but this rogue `<p>` make no sense. I'm adding it there because I don't know how to resolve the issue, but I can open another issue if you deem it necessary.

### Reproduction steps

the repo is here 
https://git.vadia.eu.org/Vadia/vadia.garden

### Expected behavior

1.  setFrontMatterParsingOptions shouldn't add the content of the note if not asked to.
2. `notefeed.html` shouldn't generate rogue `<p>` when generating the feed

If you can help in any ways, it would be welcome !

Thanks for this program, it's very useful !

Vadia

### Reproduction URL

https://git.vadia.eu.org/Vadia/vadia.garden

**Comment by uncenter** [comment]
If you are storing your description in the front matter l, why are you setting the excerpt alias? Seems easier to me to just use the `description` key directly... can you show us what one of your Markdown documents looks like?

**Comment by pdehaan** [comment]
Markdown can be weird when trying to figure out where `<p>` tags should be when paired with Nunjucks/Liquid. You might need to trim your output using `{%- ... -%}` and `{{- ... -}}`:

```liquid
<ul class="notefeed">
  {% for notes in collections.notes %}
  <li class="notefeed-note">
    <a href="{{ notes.page.url }}">
      <span class="larger">{{ notes.data.title }}</span>
      {%- if notes.data.description != nil -%}
      {{- notes.data.description | markdownify -}}
      {%- endif -%}
    </a>
  </li>
  {% endfor %}
</ul>
```

### OUTPUT
```html
  <li class="notefeed-note">
    <a href="/notes/(in)visibilité">
      <span class="larger">(In)visibilité</span><p>À propos de visibilité, ou plutôt, pourquoi j'aimerais rester invisible.</p>
</a>
  </li>
  <li class="notefeed-note">
    <a href="/notes/liste d’articles à lire">
      <span class="larger">Liste d’articles à lire</span><p>Une liste d'article intéressants.</p>
</a>
  </li>
  <li class="notefeed-note">
    <a href="/notes/en bonne santé">
      <span class="larger">En bonne santé</span><p>Je suis vraiment soulagée/chanceuse d’aller <em>bien</em> en ce moment, comparativement à y’a 2 ans où c’était… tellement compliqué que mon cerveau a oublié à quel point et qu’essayer de se souvenir ressemble à se souvenir d’un cauchemard.</p>
</a>
  </li>
```

**Comment by uncenter** [comment]
> If you are storing your description in the front matter l, why are you setting the excerpt alias? Seems easier to me to just use the `description` key directly... can you show us what one of your Markdown documents looks like?

Yes I think I was right. I took a look at your notes and you don't need to set any front matter parsing options at all! Your description key will work just fine without it.

**Comment by uncenter** [comment]
@vadiae Let us know how that goes. FYI, I think that link you gave is the official documentation!

**Comment by pdehaan** [comment]
> I was seeing it the other day in a liquid code but I didn't manage to find it in liquid documentation. What is the name of the thing ?

https://liquidjs.com/tutorials/whitespace-control.html
https://mozilla.github.io/nunjucks/templating.html#whitespace-control

**Comment by vadiae** [comment]
Thanks for all your answer, I have resolved my primary problem with rogue ’<p>’.  The problem with the excerpt is still a bit of a weird behavior I don’t have answer why, but removing the code resolved my problem for now. Thanks for your answers ✨
