### ISSUE TITLE
Elventy inserts p tag when using indentation

### ISSUE THREAD

**Issue by jcubic** [11ty/eleventy#2986]
### Operating system

Fedora 38

### Eleventy

2.0.1

### Describe the bug

I've just upgraded from 1.0 to 2.0 becasue of a bug where Eleventy added `<pre><code>` in #1285 but now I have `<p>` tags instead:

I have liquid code like this:

```liquid
<nav class="languages">  
  <ul>
    {% for l in collections.langs %}
      {% if l == lang %}
        <li class="selected">({{- l -}})</li>
      {% else %}
        <li><a href="{% if l != "en" %}/{{- l -}}{% endif %}/blog">({{- l -}})</a><li>
      {% endif %}
    {% endfor %}
  </ul>
</nav>
```

(lags is custom collection)

and I've get this output:

```html
<nav class="languages">
  <ul>
<p><li class="selected">(en)</li></p>
<p><li><a href="/pl/blog">(pl)</a><li></p>
  </ul>
</nav>
```

I need to use:

```liquid
<nav class="languages">  
  <ul>
    {% for l in collections.langs %}
      {% if l == lang %}
<li class="selected">({{- l -}})</li>
      {% else %}
<li><a href="{% if l != "en" %}/{{- l -}}{% endif %}/blog">({{- l -}})</a><li>
      {% endif %}
    {% endfor %}
  </ul>
</nav>
```

Which doesn't look good.

## Reproduction:

https://github.com/jcubic/jankiewicz-blog/tree/eleventy-bug

## Steps to reproduce
1. Clone the repo
2. npm install
3. npm run start
4. Open http://localhost:8080/blog

**Comment by pdehaan** [comment]
I think you might just need to trim the leading whitespace from the `{% for %}…{% endfor %}`, `{% if %}…{% endif %}`, and `{% else %}` tags (using a hyphen like `{%- %}`, similar to how you're already trimming leading/trailing whitespace on the `{{- l -}}` variable) since it's probably confusing some Markdown somewhere.

Disclaimer: I haven't looked at your repo yet, so this is somewhat of a [very good] guess.

```liquid
<nav class="languages">  
  <ul>
    {%- for l in collections.langs %}
      {%- if l == lang %}
        <li class="selected">({{- l -}})</li>
      {%- else %}
        <li><a href="{% if l != "en" %}/{{- l -}}{% endif %}/blog">({{- l -}})</a><li>
      {%- endif %}
    {%- endfor %}
  </ul>
</nav>
```

### BEFORE
```html
<nav class="languages">  
  <ul>
<p><li><a href="/de/blog">(de)</a><li></p>
<p><li><a href="/blog">(en)</a><li></p>
<p><li><a href="/es/blog">(es)</a><li></p>
<p><li><a href="/fr/blog">(fr)</a><li></p>
<p><li><a href="/it/blog">(it)</a><li></p>
  </ul>
</nav>
```

### AFTER
```html
<nav class="languages">  
  <ul>
        <li><a href="/de/blog">(de)</a><li>
        <li><a href="/blog">(en)</a><li>
        <li><a href="/es/blog">(es)</a><li>
        <li><a href="/fr/blog">(fr)</a><li>
        <li><a href="/it/blog">(it)</a><li>
  </ul>
</nav>
```

Where my completely arbitrary `collections.langs` looks like this in my local eleventy.config.js file:
```js
  eleventyConfig.addCollection("langs", () => ["de", "en", "es", "fr", "it"]);
```

**Comment by jcubic** [comment]
Sorry but I don't understand your code it's exactly the same as mine. And if you just copy pasted my code I don't see a reason why you do that. My code is in my post. And I remove white space before the tags I will have the same problem. The code should have indentation otherwise it not maintainable

**Comment by jcubic** [comment]
Thanks that solved the issue.
