### ISSUE TITLE
How to add a variable to css?

### ISSUE THREAD

**Issue by andreapernici** [11ty/eleventy#300]
I'm trying to insert dynamic values inside a CSS so I created an .njk file with CSS

```
.footer { 
padding: 10px 0; background: {{ config.stickyFooterPromoBackground }}
}
```

but the value inside the config.json is ignored.

Which is the correct way to pass it?

**Comment by kleinfreund** [comment]
Properties from Eleventy’s configuration aren’t automatically exposed in templates.

However, you can use [JavaScript Data Files](https://www.11ty.io/docs/data-js/) to expose data. [This example should help](https://www.11ty.io/docs/data-js/#example%3A-exposing-environment-variables).

**Comment by andreapernici** [comment]
Mmm sounds strange. I can use the variable in any other njk file. Why not in this .njk?

The same works in js. Why not in css?

**Comment by andreapernici** [comment]
```
/inline-js/filename.njk --> works
/inline-css/filename.njk --> doesn't work
```

obviously the var is defined in _data/config.json

**Comment by edwardhorsford** [comment]
Can you share the contents of `/inline-css/filename.njk`? or a reduced test case?

If you define a variable in frontmatter on that file, does it work if used in the css?

**Comment by edwardhorsford** [comment]
I've just made my own `foo.njk` that outputs to a `css.css` and includes a variable. It seems to work fine using nunjucks variables and global data.

I wonder if you have a syntax error or something else that is causing compilation to not complete correctly?

**Comment by andreapernici** [comment]
Looks like it was a compilation issue cause recompiling again it now works.

Thanks a lot and sorry.
