### ISSUE TITLE
Vite with SCSS works in development mode, but not after build

### ISSUE THREAD

**Issue by zelfroster** [11ty/eleventy#3009]
### Operating system

Arch Linux

### Eleventy

2.0.1

### Describe the bug

I am using these versions of eleventy with vite and scss
```json
"@11ty/eleventy": "^2.0.1",
"@11ty/eleventy-plugin-vite": "^4.0.0",
"sass": "^1.62.1"
```

I have included scss files in the eleventy.addPassthroughCopy and It's workin in dev mode `--serve` but after building the generated css file is not getting linked to the html files.

### Reproduction steps

1. Clone this repo [https://github.com/zelfroster/website](https://github.com/zelfroster/website)
2. Install dependencies with `pnpm install`
3. Run `pnpm start`, It works.
4. Now, Build with `pnpm build`, It doesn't work.

### Expected behavior

All html files should have the css file linked in head tag.

### Reproduction URL

https://github.com/zelfroster/website

**Comment by zelfroster** [comment]
Don't think It's going to be fixed soon, This bug is so annoying I am switching to Hugo.

**Comment by crowne** [comment]
It's a pity I can't see the repo as at the time of the issue, because I'm trygin to get scss to work in dev mode
