### ISSUE TITLE
Need advice on compose a page with different markdown block

### ISSUE THREAD

**Issue by andreapernici** [11ty/eleventy#301]
Is it possible to include different portions of MarkDown content on different page slot?

{{ content | safe }}

Example a page

--> page1.md

that should create something like

![content-block](https://user-images.githubusercontent.com/1017981/48013455-a0581700-e124-11e8-99a5-f2754f3c1193.png)

Is there a way to allow this to be created with a single markdown file or I must follow another way using json or shortcodes?

The question is how much flexibility we have in markdown.

Maybe the question is trivial, but I'm still in the phase of understanding well the framework.

**Comment by andreapernici** [comment]
Any advice? @zachleat

**Comment by octoxalis** [comment]
Of course you can!
You just have to define shortcodes to wrap each content block  and use thses shortcode in your marldown files.

JS file for shortcodes as a module
```
const SHORTCODES = {
  content1: () => {
  return `<div class="aclass">${innercontent}<div>`
  },
  // more shortcodes for other content blocks
}
function shortcodesSet(config) {
  config.addPairedShortcode("content1", function(innercontent) {
    return SHORTCODES.content1(innercontent);
  });
module.exports = shortcodesSet;
```
Markdown file

```
// front matter

{% content1 %}
My content in block 1
{% endcontent1 %}
..... other blocks
```
It's better to put all your shorcodes in a separate module  and then in eleventy.js file just require the shortcodes module. An do not forget that your shortcodes can have arguments to be more flexible in your Markdown context.

**Comment by zachleat** [comment]
(sorry I was on vacation for a bit)

I think you just want to use simple includes!

Nunjucks: https://www.11ty.io/docs/languages/nunjucks/#supported-features
Liquid: https://www.11ty.io/docs/languages/liquid/#supported-features

(Please review the warning on https://www.11ty.io/docs/languages/markdown/)

A few other template langs support this too. Because the markdown processing happens AFTER Nunjucks/Liquid/etc you can put markdown in the include and it should work fine.

Does that help?

**Comment by andreapernici** [comment]
Welcome back from tha vacation @zachleat I were lost without you, but the other guys were so kind in helping me :) 

Includes are not good in my case cause I'm trying to generate something "normal people" can do.

In this case the include could fit only if we can pass variables to the included file. But I don't think it's the case.

Maybe the shortcode stuff is a way of doing that. Not sure includes are flexible enough here cause they are not reusable inside the same MD with different values. Or am I wrong?

**Comment by andreapernici** [comment]
I'm working on them, but at a template level.

Does macros can be used in .MD files?

**Comment by andreapernici** [comment]
Ok I switched from MD to Njk and they work.

**Comment by edwardhorsford** [comment]
@andreapernici yes, you can use macros inside of `.md` files.

You may need to [set nunjucks](https://www.11ty.io/docs/config/#default-template-engine-for-markdown-files) as your default markdown template engine.

Then, include the macros file on each `.md` file. On mine, it looks like this:
`{% import "includes/macros.njk" as macro %}`

**Comment by teamon** [comment]
@andreapernici Could you share a working example? This is exactly what I'd like to do, yet I still haven't found a way to achieve it. Thanks in advance.
