### ISSUE TITLE
Empty pathPrefix causes constant homepage browsersync redirect

### ISSUE THREAD

**Issue by rolandtoth** [11ty/eleventy#302]
If pathPrefix in .eleventy.js is defined but it's empty (""), then the start page is constantly redirected by browsersync (http://localhost:8080/). Subpages are OK. If I conditionally add pathPrefix to the return object in .eleventy.js it works as expected:

```javascript
  out = {
    dir: {
      input: "input",
      data: "data",
      output: "dist",
      includes: "includes"
    },
    templateFormats: ["njk", "md"],
    htmlTemplateEngine: "njk",
    markdownTemplateEngine: "njk",
    dataTemplateEngine: false,
    passthroughFileCopy: true
  }

  // cfg comes from an included cfg.json
  if (cfg.pathPrefix) {
    out.pathPrefix = cfg.pathPrefix;
  }
```

Setting pathPrefix to "/" also works, but it would be better to skip it entirely if it's set to an empty string.

**Comment by zachleat** [comment]
Confirmed and duplicated.

**Comment by zachleat** [comment]
Looks like the default wasn’t enforced if it was an empty string. Moving forward `""` will translate to `"/"` properly.

**Comment by tedw** [comment]
Hey there, I’m also getting the redirect loop when setting `pathPrefix: './'`. Is this expected? I’m building a site for a client who will be hosting it in a subfolder, but the path is TBD and could change so I can’t hard code it. Thanks!
