### ISSUE TITLE
date: now

### ISSUE THREAD

**Issue by elmuerte** [11ty/eleventy#3022]
### Describe the solution you'd like

There are several constructions to define a page's "date": https://www.11ty.dev/docs/dates/

However, there is a big missing one for pages which are generated based on dynamic site content. For example the zero maintenance tag pages example: https://www.11ty.dev/docs/quicktips/tag-pages/

The content of the pages is not based on the content of the source file. So none of the source file's properties properly describe the generated page's date. "now" would probably be the best date indicator for pages like this.

**Comment by zachleat** [comment]
Related: #867

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
Both of the following work to set a date as a `Date` instance. You can use a JavaScript data file too.

```
---js
{
  date: new Date(),
}
---
```

```
---js
let date = new Date();
---
```

Note the last one requires `node-retrieve-globals@6.0.1` https://github.com/zachleat/node-retrieve-globals/issues/6
