### ISSUE TITLE
Javascript in mardown file is being parsed and turned into HTML

### ISSUE THREAD

**Issue by GoOz** [11ty/eleventy#3024]
### Operating system

macOS Ventura 13.4.1

### Eleventy

2.0.1

### Describe the bug

On a tutorial blog post I added a custom javascript script
```js
function hue(str) {
	if (str === null) return;
	let hash = 0;
	for (var i = 0; i < str.length; i++) {
		hash = str.charCodeAt(i) + ((hash << 5) - hash);
		hash = hash & hash;
	}
	return hash % 360;
}

const avatars = document.querySelectorAll(".avatar--custom");

Array.from(avatars).forEach(element => {
		element.style.backgroundColor = `hsl(${hue(element.innerText)},45%,90%)`;
});
```

when inside a markdown code block everything works great, it's shown as it is and not processed but when I put it in a HTML `<script>` tag, I expect it to just appear in the DOM untouched but I get my javascript parsed by the markdown engine.

Arrow functions and literal template specifically seem to cause issues because in my output HTML I get 
```html
<script>
function hue(str) {
	if (str === null) return;
	let hash = 0;
	for (var i = 0; i < str.length; i++) {
		hash = str.charCodeAt(i) + ((hash << 5) - hash);
		hash = hash & hash;
	}
	return hash % 360;
}
<p>const avatars = document.querySelectorAll(&quot;.avatar--custom&quot;);</p>
<p>Array.from(avatars).forEach(element =&gt; {
element.style.backgroundColor = <code>hsl(${hue(element.innerText)},45%,90%)</code>;
});
</script></p>
```

### Reproduction steps

1. Write a markdown blog post
2. Add a HTML `script` tag with an arrow function and/or a litteral template in it
3. Build the post
4. See the script being processed as markdown.

### Expected behavior

I expect any javascript code in a `script` tag to be untouched by the markdwon engine.

**Comment by pdehaan** [comment]
I think I'm a bit confused. If you want to show the code block in the markdown, you can use the code fence like <kbd>```js</kbd> and it should ignore the code (if it's part of the blog post):
````js
```js
function hue(str) {
	if (str === null) return;
	let hash = 0;
	for (var i = 0; i < str.length; i++) {
		hash = str.charCodeAt(i) + ((hash << 5) - hash);
		hash = hash & hash;
	}
	return hash % 360;
}

const avatars = document.querySelectorAll(".avatar--custom");

Array.from(avatars).forEach(element => {
		element.style.backgroundColor = `hsl(${hue(element.innerText)},45%,90%)`;
});
```
````

If you want the Markdown processor to ignore that code block altogether, I believe you'll need to use the [Nunjucks](https://mozilla.github.io/nunjucks/templating.html#raw) or [LiquidJS](https://liquidjs.com/tags/raw.html) `{% raw %}` paired tag so it doesn't try parsing the contents and converting to HTML.


```njk
{% raw %}
<script>
function hue(str) {
	if (str === null) return;
	let hash = 0;
	for (var i = 0; i < str.length; i++) {
		hash = str.charCodeAt(i) + ((hash << 5) - hash);
		hash = hash & hash;
	}
	return hash % 360;
}

const avatars = document.querySelectorAll(".avatar--custom");

Array.from(avatars).forEach(element => {
		element.style.backgroundColor = `hsl(${hue(element.innerText)},45%,90%)`;
});
</script>
{% endraw %}
```

**Comment by GoOz** [comment]
Sorry, it was a bit confusing indeed.
I'm actually using both methods, the first one to show readers the code used and the last to be used in a live example.

I did try `{% raw %}` before and it didn't work… but now it is. So I must have messed up something else before.

Anyway, so I was on the right path. Sorry for the unconvenience and thank you. 

Closing th ticket.
