### ISSUE TITLE
Tips on handling multi-lingual sites

### ISSUE THREAD

**Issue by pieterbeulque** [11ty/eleventy#303]
I'm trying out Eleventy to generate a multi-lingual site and was wondering if anyone had any experience with this? Any advice, tips, examples, … are much appreciated!

Of course, I'll share my findings too 🙂

**Comment by nikosolihin** [comment]
Interested in your findings on this topic

**Comment by zachleat** [comment]
Thank you for this question @pieterbeulque! I think we may have an existing issue for this at #243? Can y’all subscribe and participate over there instead? Thank you!
