### ISSUE TITLE
Usage of i18n "locale_url" with explicit language code behaves unexpectedly

### ISSUE THREAD

**Issue by ScreenDream** [11ty/eleventy#3034]
### Operating system

Windows 11

### Eleventy

2.0.1

### Describe the bug

I try to implement hreflang meta links for my page.
I have German and English pages, de and en.
For the canonical page I want to use the English page as fallback when no fitting language is available.
This is what I tried in my njk template:

`<link rel="alternate" hreflang="x-default" href="{{ meta.url }}{{ page.url | locale_url("en") }}">`

Now in the documentation it states explicitly, that for the normal use of the locale_url filter, the url provided can include a language code. I banged my head against it for a while to find, that this is not true, if one uses an explicit language code to get a specific locale like above.

In above case, I get the warning:
 `Error: Localized file for URL /en/en/about/ was not found in your project.`

I saw that a fix was implemented for similar problems a while ago, but maybe this case was overlooked?

It works if I provide an URL with the language subfolder path removed, but that is a bit tricky to construct and I wonder if it shouldn't work the same as the standard use of locale_url?

Thank you very much! :-)

### Reproduction steps

I hope the above example code is sufficient...

### Expected behavior

I would expect the filter to work the same with an explicit language code as without one, like it is described in the docs:

_If the link argument already has a valid language code, it will be swapped. The following all return /en/blog/ when rendered in /en/* templates (or /es/blog/ in /es/* templates):

{{ "/blog/" | locale_url }}
{{ "/en/blog/" | locale_url }}
{{ "/es/blog/" | locale_url }}_

https://www.11ty.dev/docs/plugins/i18n/#locale_url-filter

**Comment by zachleat** [comment]
Some work was done to fix a bunch of issues with this for 3.0. Related: #2921

Please retest this one after 3.0 alphas ship!

**Comment by zachleat** [comment]
Follow along at #2921 please!

**Comment by ScreenDream** [comment]
Thank you Zach!

**Comment by minimo-io** [comment]
Also looking forward for this!
