### ISSUE TITLE
EleventyHtmlBasePlugin with prefixpath produces incorrect output when in tags attribute

### ISSUE THREAD

**Issue by phineas-pta** [11ty/eleventy#3035]
### Operating system

windows, linux (github actions)

### Eleventy

2.0.1

### Describe the bug

when path not in tags attribute, EleventyHtmlBasePlugin output correct full path with prefix

but if path in tags attribute, prefix gets duplicated in output

### Reproduction steps

1. fresh new project with 11ty
2. config file
```js
const { EleventyHtmlBasePlugin } = require("@11ty/eleventy");
module.exports = (eleventyConfig) => {
	eleventyConfig.addPlugin(EleventyHtmlBasePlugin);
};
```
3. dummy html file
```html
<link rel="stylesheet" href="{{ '/assets/style.css' | htmlBaseUrl }}" />
<p>{{ '/assets/style.css' | htmlBaseUrl }}</p>
```
4. build
```bash
npx eleventy --pathprefix yolo
```
5. output html file
```html
<link rel="stylesheet" href="/yolo/yolo/assets/style.css">
<p>/yolo/assets/style.css</p>
```

### Expected behavior

the output html should be
```html
<link rel="stylesheet" href="/yolo/assets/style.css">
<p>/yolo/assets/style.css</p>
```

### misc

**edit 1** using nunjucks

**Comment by zachleat** [comment]
`htmlBaseUrl` isn’t encouraged there, that’s only for special cases where you want to transform a URL in plaintext or in an HTML comment. Something outside of the normal URL in markup usage.

This is what you’d want:

```html
<link rel="stylesheet" href="/assets/style.css">
```

You can see all of the default tag and attribute combinations here: https://github.com/posthtml/posthtml-urls/blob/e0ea07b921b70f7406178bf8d848a06c45694c0d/lib/defaultOptions.js#L9-L49
