### ISSUE TITLE
improve logger performance

### ISSUE THREAD

**Issue by njfamirm** [11ty/eleventy#3040]
Hi

When I'm review 11ty core codes. see this line in logger,
As far as I understand, this is pointless and is done every time!
It is better to give a default value once in the constructor and update it if needed.
https://github.com/11ty/eleventy/blob/ecd0579a2dded6939510b7c23841388b26eb6d16/src/Util/ConsoleLogger.js#L89
If it is true, I can correct this in the pull request

thanks for building 11ty!

**Comment by njfamirm** [comment]
We wrote the `[@alwatr/logger](https://github.com/AliMD/alwatr/blob/main/core/logger/src/logger.ts)` package for our logging.
**Fast, optimized and readable**

If you really think it is good that we can switch to it or if there is a special feature in mind, we can add it.
Otherwise, we can do things that you think are good. Let's write again in 11ty.

I look forward to doing this

**Comment by njfamirm** [comment]
I look forward to your reply @zachleat @MadeByMike @....

**Comment by njfamirm** [comment]
I look forward to your reply @zachleat @MadeByMike @....

**Comment by zachleat** [comment]
I think this line of code is okay! If you have a trace or flame chart indicating a performance anomaly with this particular code, happy to review it!
