### ISSUE TITLE
Create a collection based on a _data/jsonfile.json

### ISSUE THREAD

**Issue by andreapernici** [11ty/eleventy#305]
Is it possible to create a virtual Collection based on a config data file in order to be able to have single pages based on URL Slug?

**Comment by octoxalis** [comment]
I'm not sure to understand perfectly what you mean by virtual collection, but you can have one or more setting file(s) and access these settings in all templates, if you put it/them in the `_data` folder.
You can also have JS files in this `_data` folder with all the logic you want and you can use all the **Node** modules you want inside those files (you just have to require them). It's up to you to write the extra-logic you need to build your pages.

This is one of the outstanding power of **11ty**: templates (with a strict minimum of logic) and **Markdown** on one side and a bunch of data accessed and processed at build time by **Javascript** with the help of **Node** modules on the other side.

**Comment by andreapernici** [comment]
Ok I figured it out.

We don't need to reference it using .data.
