### ISSUE TITLE
Not detecting {% for %} loop/using collections in templates

### ISSUE THREAD

**Issue by robocone** [11ty/eleventy#3053]
### Operating system

Windows 11 Home

### Eleventy

9.6.6

### Describe the bug

Not sure if it's a bug or just a functional limitation (given the lack of error messages, I'm inclined to believe the latter), but...

I'm trying to generate separate category and tag pages for a blog section on a website I'm developing. After managing to look up/snatch/cobble together some code to actually get the directories to generate correctly _and_ separately from each other (with the following in my config file to show for it:)

```
module.exports = function (eleventyConfig) {
  eleventyConfig.addPassthroughCopy("css");
  eleventyConfig.addPassthroughCopy("assets");
  eleventyConfig.addPassthroughCopy("scripts");
  // Category collection
  eleventyConfig.addCollection('categories', function (collectionApi) {
    const categories = new Set()

    // Loop
    collectionApi.getAll().forEach((item) => {
      // Check for 'categories'
      if (item.data.categories) {
        item.data.categories.forEach((category) => {
          categories.add(category);
        });
      }
    });

    // Convert to array
    return Array.from(categories);
  });

  // Tag collection
  eleventyConfig.addCollection('tags', function (collectionApi) {
    const tags = new Set();

    // Loop
    collectionApi.getAll().forEach((item) => {
      // Check for 'tags'
      if (item.data.tags) {
        item.data.tags.forEach((tag) => {
          tags.add(tag);
        });
      }
    });

    // Convert to array
    return Array.from(tags);
  });


  return {
    dir: {
      input: "src",
      output: "_site",
    },
  };
};
```

I ended up progressing on to a _new_ problem, involving my `category.md` and `tag.md` templates (using just the former for now as the relevant portions are/should be basically identical, values aside):

```
---
pagination:
    data: collections.categories
    size: 1
    alias: category
    addAllPagesToCollections: true
layout: blog-hub
permalink: /blog/categories/{{ category | slugify}}/
title: "{{ category }} Entries"
---
<h1>All {{ category }} entries</h1>
{% for post in categories.items %}
    <li>
        <a href="{{ post.url }}">{{ post.data.title }}</a>
    </li>
{% endfor %}
```

Which end up generating (within the layout context) as just the following in each of the generated .htmls:

```
<h1>All Dev (Back)Log entries</h1>
[blank space in the output here]
```
So, yeah, the 'for' loop is just coming back null. As I said, I'm partially expecting this to just be an inherent limitation of eleventy more than anything, but if I've done something else wrong here, I'm all ears (or if there was a simpler way to go about all this in the first place—I'm pretty green to this as you can probably tell)

**Comment by pdehaan** [comment]
I think I'm missing something and a little confused.
You have a loop like this in your category.md file:
```liquid
{% for post in categories.items %}
    <li>
        <a href="{{ post.url }}">{{ post.data.title }}</a>
    </li>
{% endfor %}
```

But where is `categories` defined? From the look of it, it's expected to be an object with (at least) an `items` property.

If I'm understanding the Eleventy config file correctly, this code is creating a `collections.categories` that is a unique array of category names which you're paginating over:

```js
  eleventyConfig.addCollection('categories', function (collectionApi) {
    const categories = new Set()

    // Loop
    collectionApi.getAll().forEach((item) => {
      // Check for 'categories'
      if (item.data.categories) {
        item.data.categories.forEach((category) => {
          categories.add(category);
        });
      }
    });

    // Convert to array
    return Array.from(categories);
  });
```

Based on this message, it looks like the pagination is working as expected:

```html
<h1>All Dev (Back)Log entries</h1>`
```

Is there code elsewhere that is defining the `categories` object which contains an array of posts based on a certain category?

**Comment by pdehaan** [comment]
A bit of tweaking, but this seems to work.
Instead of having `collections.categories` which was an array of category names, it's now an object containing each categories posts.

```js
module.exports = function (eleventyConfig) {
  // eleventyConfig.addPassthroughCopy("css");
  // eleventyConfig.addPassthroughCopy("assets");
  // eleventyConfig.addPassthroughCopy("scripts");

  // Category collection
  eleventyConfig.addCollection('categories', function (collectionApi) {
    const categories = {};

    // Loop
    collectionApi.getAll().forEach((item) => {
      item.data.categories?.forEach((category) => {
        categories[category] ??= [];
        categories[category].push(item);
      });
    });
    return categories;
  });

  // Tag collection
  eleventyConfig.addCollection('tags', function (collectionApi) {
    const tags = new Set();

    // Loop
    collectionApi.getAll().forEach((item) => {
      // Check for 'tags'
      if (item.data.tags) {
        item.data.tags.forEach((tag) => {
          tags.add(tag);
        });
      }
    });

    // Convert to array
    return Array.from(tags);
  });


  return {
    dir: {
      input: "src",
      output: "www",
    },
  };
};
```

And here we still paginate over `collections.categories` (which just loops over the KEYS of the object), and then we use `{% for post in collections.categories[category] %}` to loop over each categories pages:

```njk
---
pagination:
    data: collections.categories
    size: 1
    alias: category
    addAllPagesToCollections: true
permalink: /blog/categories/{{ category | slugify}}/
title: "{{ category }} Entries"
---

<h1>All {{ category }} entries</h1>
<ul>
{% for post in collections.categories[category] %}
  <li>
    <a href="{{ post.url }}">{{ post.data.title }}</a>
  </li>
{% endfor %}
</ul>
```

Seems to work in my limited testing. Possibly a bit more performant than looping over the entire `collections.all` collection and filtering based on the current category from pagination.

**Comment by robocone** [comment]
Welp, no, you weren't missing something—I was, apparently (regarding that `object` definition, at least!

And your code works for me by the way, but only now did I notice that the page titles are just generating as "{{ category }} Entries" (on my end, at least). Sorry for the tangent, but could I have help with this too?

**Comment by pdehaan** [comment]
Re: `"{{ category }} Entries"`, I believe you'll need to use [`eleventyComputed`](https://www.11ty.dev/docs/data-computed/) for that.

try something like this:
```njk
---
pagination:
    data: collections.categories
    size: 1
    alias: category
    addAllPagesToCollections: true
permalink: "/blog/categories/{{ category | slugify}}/"
eleventyComputed:
    title: "{{ category }} Entries"
---
```

**Comment by robocone** [comment]
Oop—just gave it a shot, but now it's not generating a title at all (just an empty `<title></title>` in the html)...though, I'm guessing that has to do with the Computed Data and pagination conflicts mentioned in the documentation?

**Comment by pdehaan** [comment]
https://github.com/pdehaan/11ty-3053

Worked for me: [src/posts/_categories.njk](https://github.com/pdehaan/11ty-3053/blob/70dabfb29bb958ef1170979c68b26c356dd9e584/src/posts/_categories.njk) has this front matter:

```njk
---
pagination:
    data: collections.categories
    size: 1
    alias: category
    addAllPagesToCollections: true
permalink: /blog/categories/{{ category | slugify}}/
layout: base.njk
eleventyComputed:
  title: "{{ category }} Entries"
---
```

my [src/_includes/base.njk](https://github.com/pdehaan/11ty-3053/blob/70dabfb29bb958ef1170979c68b26c356dd9e584/src/_includes/base.njk) layout looks like this:
```njk
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <title>{{ title }}</title>
  </head>
  <body>
    <main>{{ content | safe }}</main>
  </body>
</html>
```

And the [output](https://github.com/pdehaan/11ty-3053/blob/70dabfb29bb958ef1170979c68b26c356dd9e584/www/blog/categories/peas/index.html) looks like this:
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>peas Entries</title>
  </head>
  <body>
    <main>
      <pre>peas Entries</pre>

      <h1>All peas entries</h1>
      <ul>
        <li>
          <a href="/posts/five/">FIVE</a>
        </li>
      </ul>
    </main>
  </body>
</html>
```

**Comment by robocone** [comment]
Ah, I see—and yeah, it works on my end too. As for my own setup, though, my `src/blog/category.md`'s front matter looks like this:

```
---
pagination:
    data: collections.categories
    size: 1
    alias: category
    addAllPagesToCollections: true
layout: blog-hub
permalink: /blog/categories/{{ category | slugify}}/
eleventyComputed:
    title: "{{ category }} Entries"
---
```

And my `src/_includes/blog-hub.njk` has this in the head section:

```
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="/css/blog.css" rel="stylesheet" media="all">
    <script src="scripts/safe-links.js"></script>
  </head>
```

Which comes out to this in the respective `.html`s under `_site`:

```
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link href="/css/blog.css" rel="stylesheet" media="all">
    <script src="scripts/safe-links.js"></script>
  </head>
```

Oh, and just to cover all my bases, the script I have it set to run is just this:

```
var links = document.querySelectorAll('a');

links.forEach(function(link) {
  var href = link.getAttribute('href');

  if (href && (href.startsWith('http://') || href.startsWith('https://'))) {
    link.setAttribute('rel', 'noopener noreferrer nofollow');
  }
});
```

**Comment by pdehaan** [comment]
Yeah, I don't get it, your code looks exactly the same as my setup. 
Do you have a public repo? I can try cloning your project and running locally and troubleshoot.

**Comment by robocone** [comment]
Just finished putting this together—thanks again! https://github.com/robocone/site-test

**Comment by pdehaan** [comment]
Not sure why, but it seems to maybe be working if I change your src/blog/blog.json to this:
```json
{
    "layout": "blog-post",
    "permalink": "/blog/{{  date | date: '%Y/%m/%d' }}/{{ slug }}.html"
  }
```

I removed the `"title"` definition there. Not sure why that'd break it, but... yeah.

**Comment by pdehaan** [comment]
Yeah, not sure why setting `title` there was causing it to blank out. Might be some timing issue w/ `eleventyComputed`.
Another workaround might be something like this untested gem which will check for a `title` defined in front matter then fall back to a default string:
```js
// src/blog/blog.11tydata.js
module.exports = {
  layout: "blog-post",
  permalink: "/blog/{{  date | date: '%Y/%m/%d' }}/{{ slug }}.html",
  eleventyComputed: {
    title(data) {
      return data.title ?? "GUILDRONE";
    }
  }
};
```
