### ISSUE TITLE
Pages using Pug templates are not rerendering when updating partials included in those templates

### ISSUE THREAD

**Issue by harrislapiroff** [11ty/eleventy#3069]
### Operating system

macOS Ventura 13.3.1 (a)

### Eleventy

2.0.1

### Describe the bug

1. I have a page using a pug template, say `page.pug` and that template includes another pug template with `include partial.pug`.
2. I run `npx @11ty/eleventy --serve` to watch and rebuild my site
3. I update `partial.pug`
4. Changes are _not_ reflected on the site.
5. As a workaround I trigger a save to `page.pug` and changes _are_ reflected on the site.

### Reproduction steps

See the reproduction URL for reproduction details.

### Expected behavior

Pages should be rerendered when partials that the layout template depends on change.

### Reproduction URL

https://github.com/harrislapiroff/11ty-pug-bug

**Comment by aschrab** [comment]
This seems to be the same issue as #2741, and I believe it would be fixed by my PR #3059.

**Comment by zachleat** [comment]
Please follow along at #2741, thank you @aschrab!
