### ISSUE TITLE
Is it possible to compose the global variable name based on another variable?

### ISSUE THREAD

**Issue by andreapernici** [11ty/eleventy#309]
I have a page with lots of iterators based on json _data that should use the same template, but include a different json for each year.

Is there a way to do that?

```
---
anno: 2018
---
{% for sponsor in sponsors_{{anno}} %}
do stuff
{%- endfor %}

{% for partner in partners_{{anno}} %}
do stuff
{%- endfor %}
```

**Comment by zachleat** [comment]
What template language are you using here?

**Comment by zachleat** [comment]
If Liquid I’m guessing you want something like the `assign` or `capture` tags. https://shopify.github.io/liquid/tags/variable/

If Nunjucks I think you’re probably looking for `set` https://mozilla.github.io/nunjucks/templating.html#set

Please reopen if you have more questions!
