### ISSUE TITLE
Images url paths have an extra "/"

### ISSUE THREAD

**Issue by QuentinGibson** [11ty/eleventy#3092]
### Operating system

Windows 11

### Eleventy

2.0.1

### Describe the bug

I am trying to write my first website using eleventy so I am not sure on why this is happening. My image should be found at the url with one foward slash "${host}/public/images/Testemonials-Green-1-2.jpg", but instead the image is found at a similar url with two foward slashes after the host like so, ${host}//public/images/Testemonials-Green-1-2.jpg". This is my first project and I can't seem to figure out why this is happening.

Please help!

### Reproduction steps

Create a eleventy blog using a starter theme using Eleventy’s Base Blog starter theme and add images to the public folder. Use that image as a background image or an image element.

Edit: typeos

**Comment by zachleat** [comment]
There’s some stuff lost in translation here: can you provide some code?

**Comment by Snapstromegon** [comment]
Hey @QuentinGibson, is it possible that your `host` variable contains a trailing slash?
