### ISSUE TITLE
Can I pass arguments to a js data file?

### ISSUE THREAD

**Issue by andreapernici** [11ty/eleventy#310]
anno and files are undefined during compilation, but I think it's obvious cause I need to pass values from the njk
```
module.exports = function (anno, file) {
        const output = require('./'+file+'_'+anno+'.json');
        return JSON.parse(JSON.stringify(output, null, 2));
};
```

**Comment by zachleat** [comment]
How are you calling this from your njk template? Or how would you like to?

**Comment by andreapernici** [comment]
Yes from an NJK

**Comment by jevets** [comment]
@andreapernici Couldn't you just provide the template with the filtered data, instead of having the template ask for the filtered data?

**Comment by andreapernici** [comment]
I need only one template that should include different JSON files and as soon as I understood there's no way to call different paginations on the same template.

I need to create archive pages divided per years that includes list of elements.

IE:

```
/2018/
- list of attendees 2018 (_data/attendees_2018.json)
- list of speakers 2018 (_data/speakers_2018.json)
- list of sponsors 2018 (_data/sponsors_2018.json)
- etc etc
/2017/
- list of attendees 2017 (_data/attendees_2017.json)
- list of speakers 2017 (_data/speakers_2017.json)
- list of sponsors 2017 (_data/sponsors_2017.json)
- etc etc
```

All the years are identical and can vary based on some parameters like rows non active or similar, but this can be easily achievable checking the presence of elements inside the json or the json itself.

I didn't found a proper way to achieve this dynamically. Maybe using shortcodes can do the trick, but it's not so maintainable in terms of layout changes etc etc.

**Comment by zachleat** [comment]
@andreapernici can you put those JSON files in the global data directory? Eleventy can process all of them for you automatically! If you put them in an `anno` folder you could even iterate over the years (a la the comment here https://github.com/11ty/eleventy/issues/304#issuecomment-440678396)

Global Data Files: https://www.11ty.io/docs/data-global/

**Comment by andreapernici** [comment]
Sure I can and before naming them with _anno.json I created the "YEARS" folders, but no way to access those data.

Created an NJK template like this

```
---
layout: layouts/base.njk
anno: 2018
---
{{ content | safe }}

{{ 2018 | dump }}

Array var 2018

{% for key, val in anno %}
{{ key }}
{% endfor %}

Array 2018

{% for key, val in 2018 %}
{{ key }}
{% endfor %}
```

And my _data folder has a  2018 folder with inside sponsors.json, and relatori.json. Both the files are populated.

But the result of the foreach is Empty.

I must create JS data file and not JSON?

**Comment by andreapernici** [comment]
Ok. Figured out the issue is with the folder with a number in the name.

Changing it to a_2018 works, but I can't still make it work passing the folder name as an input parameter. I suppose I must use pagination here. Right?

**Comment by andreapernici** [comment]
Correct me if I'm wrong.

> If you put them in an anno folder you could even iterate over the years 

Here you mean that I should change my data structure creating inside "anno" folder a single file with all the information for each year.

```
anno 
-- 2018.json
---- relatori:
---- sponsors:
-- 2017.json
---- relatori:
---- sponsors:
```

and not

```
a_2018
-- relatori.json
-- sponsors.json
a_2017
-- relatori.json
-- sponsors.json
```

For me the best structure is to leave the current year data structure identycal to the past years data structure, but sure I can change it if is the only way to accomplish what I must do.

**Comment by andreapernici** [comment]
I tried to extrapolate datas using a pagination, but now the issue is that I can extract the various data using the "resolve: values" option in pagination and it becomes impossible to know which is the "key".

Maybe there is a much simpler way and I'm overcomplicating stuff.

**Comment by andreapernici** [comment]
Ended up using macros + njk files and solved my issue. Anyway it could be interesting to understand better how to handle those situations without macros.

**Comment by smth** [comment]
I was just wondering the same thing (I think). To use the [Stargazers tip](https://www.11ty.io/docs/quicktips/eliminate-js/) as a simple example. If you wanted to reuse that code for multiple repos owned by 11ty, what would be the best way of going about it? Could you pass a parameter for the repo name into `_data/github.js`?

```js
return fetch("https://api.github.com/repos/11ty/" + repoName)
```

Then define `repoName` when using the data in a template?

```
{{ github.stargazers | repoName: "eleventy" }} GitHub Stars
```

Or something.

**Comment by MaoX17** [comment]
Have you solved?
I'm interested too

**Comment by marcamos** [comment]
> I was just wondering the same thing (I think). To use the [Stargazers tip](https://www.11ty.io/docs/quicktips/eliminate-js/) as a simple example. If you wanted to reuse that code for multiple repos owned by 11ty, what would be the best way of going about it? Could you pass a parameter for the repo name into `_data/github.js`?
> 
> ```js
> return fetch("https://api.github.com/repos/11ty/" + repoName)
> ```
> 
> Then define `repoName` when using the data in a template?
> 
> ```
> {{ github.stargazers | repoName: "eleventy" }} GitHub Stars
> ```
> 
> Or something.

@smth Did you ever figure this out? I'm in the same boat — trying to get stargazer counts from more than one repo.

**Comment by pdehaan** [comment]
I created https://github.com/pdehaan/11ty-310

I don't think there is a way to pass data to a global data file, but I usually prefer a shortcode or something for this.

```js
// .eleventy.js
// npm i node-fetch@cjs --save-dev
const fetch = require("node-fetch");

module.exports = function (eleventyConfig) {
  eleventyConfig.addAsyncShortcode("stargazers", async function (orgRepo = "") {
    const res = await fetchStargazers(orgRepo);
    return `<p>${res.stargazers} GitHub Stars</p>`;
  });

  return {
    dir: {
      input: "src",
      output: "www",
    }
  };
};

async function fetchStargazers(orgRepo = "") {
  return fetch(`https://api.github.com/repos/${orgRepo}`)
    .then(res => res.json()) // node-fetch option to transform to json
    .then(json => {
      // prune the data to return only what we want
      return {
        stargazers: json.stargazers_count
      };
    });
}
```

```liquid
<!-- src/index.liquid -->
eleventy: {% stargazers "11ty/eleventy" %}
11ty-website: {% stargazers "11ty/11ty-website" %}
```

### OUTPUT

```html
eleventy: <p>11726 GitHub Stars</p>
11ty-website: <p>316 GitHub Stars</p>
```

That's a pretty simple approach. Since you're hitting a third party API (with semi-strict usage restrictions unless you have a token), I'd suggest something like https://www.11ty.dev/docs/plugins/fetch/ to do a bit more caching. Star counts aren't super important, so it generally doesn't matter if they're cached for 15-60 minutes while doing builds. Well, also the data will be cached statically in the HTML page as well, so the stargazer counts won't update between builds/deploys anyways.

**Comment by pdehaan** [comment]
In fact, here's what an [**@11ty/eleventy-fetch**](https://www.11ty.dev/docs/plugins/fetch/) solution might look like (I also added a bit more safety checks around a falsy `orgRepo` attribute, which will just return an empty string instead of `undefined`):

```js
const EleventyFetch = require("@11ty/eleventy-fetch");

module.exports = function (eleventyConfig) {
  eleventyConfig.addAsyncShortcode("stargazers", async function (orgRepo) {
    const res = await fetchStargazers(orgRepo);
    if (!res) {
      return "";
    }
    return `<p>${res.stargazers_count} GitHub Stars</p>`;
  });

  return {
    dir: {
      input: "src",
      output: "www",
    }
  };
};

async function fetchStargazers(orgRepo) {
  if (!orgRepo) {
    return;
  }
  const url = `https://api.github.com/repos/${orgRepo}`;
  return EleventyFetch(url, {
    duration: "10m",
    type: "json",
  });
}
```

### INPUT
```liquid
<!-- src/index.liquid -->test
eleventy: {% stargazers "11ty/eleventy" %}
11ty-website: {% stargazers "11ty/11ty-website" %}
404 city: {% stargazers %}
```

### OUTPUT
```html
eleventy: <p>11726 GitHub Stars</p>
11ty-website: <p>316 GitHub Stars</p>
404 city: 
```

**Comment by marcamos** [comment]
@pdehaan YOU ARE AMAZING, thank you so very much!
