### ISSUE TITLE
html-minifier producing error when <a> tag has a URL parameter in href attribute 

### ISSUE THREAD

**Issue by WebShapedBiz** [11ty/eleventy#3106]
### Operating system

Linux, both local elementaryOS 6.1 and whatever is on Netlify

### Eleventy

2.0.1

### Describe the bug

For half dozen of my projects I'm using `html-minifier ` like this:
```
const { minify } = require('html-minifier');

module.exports = (content, outputPath) => {
  if (process.env.NODE_ENV === 'production' && outputPath.endsWith('.html')) {
    return minify(content, {
      useShortDoctype: true,
      removeComments: true,
      collapseWhitespace: true
    });
  }

  return content;
};
```
but for the first time, I have a project where my client needs a URL parameter in external links, created as a part of content from a rich text editor in Sanity CMS.

Running eleventy produces this error:

```
[11ty:serve] [11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty:serve] [11ty] 1. Having trouble writing to "_site/posts/someslug/index.html" from "./src/content/posts/post.njk" (via EleventyTemplateError)
[11ty:serve] [11ty] 2. Transform `minifyHtml` encountered an error when transforming ./src/content/posts/post.njk. (via EleventyTransformError)
[11ty:serve] [11ty] 3. Parse Error: <a href=https://www.somedomain.com/?ref=ref>Some Webpage</a> ... etc
```

You'll see that there are no double quotes around `href` attribute but they are present in the generated HTML when I remove the `html-minifier` so maybe that's just a way that Eleventy reports this error.

Without the `html-minifier` or with `html-minifier` but without URL parameters, there are no errors whatsoever and everything looks and works fine.

I've searched the issues on https://github.com/kangax/html-minifier but no one ever reported this there so I thought maybe it is an issue with Eleventy.

Cheers.

**Comment by uncenter** [comment]
Can you provide a minimum reproduction example repository? You could also make a help thread in [the 11ty Discord server](https://www.11ty.dev/blog/discord/) if you want faster answers.

**Comment by WebShapedBiz** [comment]
Thank you @uncenter for your time and effort.
Sure, I can produce a minimal reproducible example, and I can easily clone my original GitHub repo, and create a new demo Sanity project with exact content, but it has to wait until next week, I just don't have enough time. I think maybe Sanity can be part of the issue due to `portableText-to HTML` plugin. but what's puzzling me is that everything works fine in the front-end if I don't use `html-minifier`. 

Cheers.

**Comment by WebShapedBiz** [comment]
Hi @uncenter. I have a repo to share, how can we continue this privately?

**Comment by uncenter** [comment]
I'd be happy to continue this on Discord if that's an option, you can direct message me at the username `uncenter` or start a help thread in the public Discord linked in my earlier comment.

**Comment by WebShapedBiz** [comment]
I've sent you a DM on Discord.

**Comment by Snapstromegon** [comment]
@WebShapedBiz please remember to resolve this issue if you are able to solve it in a private conversation and also provide the solution here.
Moving a public discussion private can avoid spam, but for future users it's not helpful to find an issue like this without a resolution.

**Comment by WebShapedBiz** [comment]
Thank you, @Snapstromegon for reminding me, I was planning to do so :-)

**Comment by WebShapedBiz** [comment]
At the end of the day, it was my mistake. I have to use `@portabletext/to-html` to get the content from Sanity's rich text editor and there I failed to correctly configure the handling of the links, I've missed the quotes around the template literals. What threw me off guard is that everything is working fine without `html-minifier`, even with that error of mine.

Thank you very much @uncenter for pointing out my mistake and helping resolve my issue.
