### ISSUE TITLE
Markdown Checkbox Support

### ISSUE THREAD

**Issue by lquenti** [11ty/eleventy#3107]
### Is your feature request related to a problem? Please describe.

I use 11ty for my blog and really like Markdown checkboxes for any kind of progress tracking. Unfortunately, they [don't correctly render](https://lquenti.de/ImpossibleList/) and are instead not interpreted at all.

### Describe the solution you'd like

Translating Markdown checkboxes into HTML ones 

### Additional context

I can try to implement it myself, but I am not a Javascript developer at all. Would this be implemented here or in a downstream dependency? If downstream, where?

**Comment by rothsandro** [comment]
Eleventy uses `markdown-it` as Markdown parser. You can install a plugin for it that renders checkboxes.

- https://github.com/linsir/markdown-it-task-checkbox
- https://www.11ty.dev/docs/languages/markdown/#add-your-own-plugins
