### ISSUE TITLE
Add helpers to pagination for first and last pages.

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#312]

**Comment by zachleat** [comment]
Docs added to https://www.11ty.io/docs/pagination/

**Comment by ajmalafif** [comment]
I can't seem to find a tutorial on this in the docs. Is it not ready yet?

**Comment by zachleat** [comment]
@ajmalafif I believe this is specifically referring to the `firstPageHref` and `lastPageHref` properties on the `pagination` variable. Also looks like you filed #345 which is good, thanks—let’s do this over there.
