### ISSUE TITLE
browsersync not injected into rendered .md files

### ISSUE THREAD

**Issue by slice** [11ty/eleventy#313]
on `@11ty/eleventy@0.5.4`, using `--serve` does not inject browsersync -- automatic reloading does not function correctly

```
~/Code/prj/slice.zone
🡂 eleventy --serve
Writing _site/index.html from ./index.md.
Processed 1 file in 0.21 seconds
Watching…
[Browsersync] Access URLs:
 ----------------------------------
       Local: http://localhost:8080
    External: http://10.0.0.3:8080
 ----------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 ----------------------------------
[Browsersync] Serving files from: _site
File changed: index.md
Writing _site/index.html from ./index.md.
Processed 1 file in 0.03 seconds
Watching…
[Browsersync] Reloading Browsers...
```

`--watch` seems to be working, and browsersync seems to dispatch a reload, but the actual webpage as loaded in my browser doesn't have any of browsersync's javascript injected into it

![image](https://user-images.githubusercontent.com/4206232/48741408-d5c62f80-ec0f-11e8-8059-9d7b6def4fae.png)

i am using markdown:

```md
# slice's zone

hello! this is cool!

aaah
```

**Comment by slice** [comment]
okay, i tried making an `index.html` file, and now the browsersync client was injected. maybe they should be injected for other template types (like `.md`) as well?

**Comment by jevets** [comment]
It should work fine for markdown files, any template files. But I've found that if you don't serve a real HTML document, it often won't work.

Using a layout (wrapping with `<html><head/><body/>` etc.) seems to do the trick.

**Comment by zachleat** [comment]
Can you attach the source for the `.md` file you’re having trouble with, @slice?

**Comment by zachleat** [comment]
Oh, I missed the markdown snippet you included above. I think @jevets has the right idea here, it needs to have a valid HTML structure for browsersync to work with hot reloading

**Comment by zachleat** [comment]
Please comment so we can reopen if we got it wrong here!

**Comment by jronallo** [comment]
Yes, if you are serving a Markdown file you must include a layout so that it has a body.

```markdown
---
layout: layout
---

# Title

More content.
```

**Comment by alexanderameye** [comment]
In my case, I have a .md file without a layout defined in the .md file itself. Instead, I do it through a posts.json file that lives in the posts directory. However, browsersync does not seem to work. Does browsersync require the layout to be set directly in the .md file?
