### ISSUE TITLE
Documentation: The word "content" is reserved for 11ty in layouts

### ISSUE THREAD

**Issue by ironnysh** [11ty/eleventy#3132]
> you override the "content" variable (which holds the content of the child in a layout) with your data. Renaming your `src/_data/content.json` to e.g. `src/_data/info.json` (and changing the references in the templates) fixes the issue.
> 
> I personally don't think this was supposed to work in the old version anyways and because of this wouldn't consider this a bug, but definetly worth documenting.

_Originally posted by @Snapstromegon in https://github.com/11ty/eleventy/issues/3131#issuecomment-1865149644_

**Comment by uncenter** [comment]
I would go as far as to say having a `DATA_DIR/content.{js,json}` file should throw an error, and the same for other reserved keywords.

**Comment by uncenter** [comment]
Seems pretty doable: https://github.com/uncenter/11ty-fork/blob/feat/reserved-keyword-global-data-throw/src/TemplateData.js#L330-L336.

Not sure how to find what keys are reserved though, those are just manual.

**Comment by Snapstromegon** [comment]
@uncenter 
Nice first version for global data, but if we block it in global data, IMO we should block it in ALL top level data (e.g. frontmatter and co.). Sadly I'm unsure how the "content" variable gets used in layouts and if it's just as easy to implement this feature for all data while not breaking how layouts currently work.

**Comment by uncenter** [comment]
That's why I was just thinking global data for now.

**Comment by Snapstromegon** [comment]
I just took a look and found that the content variable is set directly before passing the data into a layout here: https://github.com/11ty/eleventy/blob/main/src/TemplateLayout.js#L229
This means we could block setting any top level data entry to a reserved keyword.
Maybe we could do it here: https://github.com/11ty/eleventy/blob/main/src/TemplateLayout.js#L229 or here: https://github.com/11ty/eleventy/blob/main/src/TemplateData.js#L508

I'm unsure whether or not this works with computed data.

**Comment by zachleat** [comment]
https://github.com/11ty/eleventy/tree/frozen-reserved-data has some of the start of this, freezing `pkg` and `eleventy` data. More to come.

**Comment by zachleat** [comment]
Let’s regroup on this one over at #1173.

**Comment by zachleat** [comment]
Fixed by https://github.com/11ty/eleventy/pull/3251 Shipping with 3.0.0-alpha.7

**Comment by ironnysh** [comment]
Thanks, @zachleat!
