### ISSUE TITLE
If I'm using Ghost as a data source and it provides article content in HTML code, how can I do code highlighting?

### ISSUE THREAD

**Issue by rebron1900** [11ty/eleventy#3137]
### Operating system

windows11 

### Eleventy

2.0.1

### Describe the bug

For example, I added posts to the Collection in eleventy.js and output them to the page in article.njk.

But at this point, it is a block of HTML code ( [ghost conent api](https://ghost.org/docs/content-api/#posts) ). I thought maybe I can use a Filter to manipulate this block of HTML code, but I'm not sure how to do it.

```
    {% if article.html %}
      <div class="u-rich-text u-mt-30" data-s2r-el>
        {{ article.html | safe }}
      </div>
    {% endif %}
```

### Reproduction steps

4. See an error

**Comment by uncenter** [comment]
I think this is a problem that could more easily be solved in [the Eleventy Discord server](https://www.11ty.dev/blog/discord/). Make a thread in the #help channel and we'll help you there.

**Comment by uncenter** [comment]
Yep, with the markdown content you can do it during the build instead of on the client.

**Comment by rebron1900** [comment]
> Yep, with the markdown content you can do it during the build instead of on the client.

But it seems like Ghost doesn't support markdown format, sigh. Can I handle it through 11ty's Transform feature? I tried using jsdom and prismjs library, but it failed. What should I do?

```javascript

const jsdom = require('jsdom')
const { JSDOM } = jsdom
const prismjs = require('prismjs')

module.exports = (content, outputPath) => {
  if (outputPath.endsWith('.html')) {
    const DOM = new JSDOM(content)
    const document = DOM.window.document

    prismjs.highlightAll(document)

```

**Comment by uncenter** [comment]
Can you send your repository? What error did you get?

**Comment by rebron1900** [comment]
> Can you send your repository? What error did you get? What does the HTML look like of the code blocks Ghost returns in the API? This might be easier if you create a forum post over on the [Discord](https://www.11ty.dev/blog/discord/), you'll get faster responses.

Thanks, I'm going now.

**Comment by rebron1900** [comment]
https://discord.com/channels/741017160297611315/1022195881698672650/threads/1189062692636471436
done
