### ISSUE TITLE
"Unhandled rejection in promise" error when saving changes to Markdown files

### ISSUE THREAD

**Issue by ghost** [11ty/eleventy#3146]
Here's my MWE repo to replicate/validate the error: https://github.com/jamesbont11tyrepo/11ty-MWE

To reproduce the error, run `npm start` for the repo and then simply:

1. Open one of the Markdown files.
2. Make changes to the file.
3. Save the changes.

The terminal should show error text like so:
```
[11ty] Unhandled rejection in promise: (more in DEBUG output)
[11ty] Tried to use templateContent too early on ./file/path/with/markdown/file.md (via TemplateContentPrematureUseError)
[11ty] 
[11ty] Original error stack trace: TemplateContentPrematureUseError: Tried to use templateContent too early on ./file/path/with/markdown/file.md
```

The Eleventy Discord group has tried helping me figure out what's causing the error, but we're stumped (discussion topic here: https://discord.com/channels/741017160297611315/1182433386111971338). Sometimes we'd find the error happens on some Markdown files for some of us, but not for other people, so if you don't get the error on one Markdown file, try the other. I hope we can find the cause of this error and a solution!

**Comment by jamesbont11tyrepo** [comment]
Just noticed this other bug has the same issue I'm having, but they're on the 3.0 alphas, whereas I'm on the stable 2.0 version.

https://github.com/11ty/eleventy/issues/3136

**Comment by huphtur** [comment]
This one started happening after I upgraded to 3.0.0-alpha.6, when I save my CSS I occasionally get the error.

**Comment by zachleat** [comment]
#3410 is maybe also related

**Comment by danjordan** [comment]
I'm still seeing this issue on beta 2 when parsing front matter in a markdown file. 

It looks to be when I'm using the following syntax
```
---
tags: 
    - posts
---
```

If I remove that, or put it on one line like `tags: posts` it works fine.

**Comment by danjordan** [comment]
I'm still seeing this issue in 3.0.0-beta.2 within a markdown file. It seems to happen when I have tags in my front matter.

**Comment by zachleat** [comment]
I can’t access the original repo of this one to look.

I did go into Discord and saw a bunch of discussion (wow!) and some links to https://github.com/Aankhen/jamesbont-11tysite @shivjm but I don’t see that repo either.

**Comment by zachleat** [comment]
As the OP’s account was deleted, @danjordan can you file a new issue?

**Comment by Aankhen** [comment]
Sorry, I think I deleted my repository a long time ago, partly because I couldn’t reliably reproduce the issue. I thought I had pinpointed it, then I didn’t, then I did, then… 🤷‍♂️
