### ISSUE TITLE
Enhance convenience and performance of DOM based transforms

### ISSUE THREAD

**Issue by nhoizey** [11ty/eleventy#3162]
### Describe the solution you'd like

I hate to chain a sequence of transforms that all
- read HTML, “load” is as a DOM, change some values, export to new HTML, then
- read HTML, “load” is as a DOM, change some values, export to new HTML, then 
- read HTML, “load” is as a DOM, change some values, export to new HTML, then 

Would it be possible to have a nicer experience by integrating the “read HTML, load is as a DOM” and “export to new HTML” steps inside 11ty, so that we only have to deal with the DOM?

It could use [linkeDOM](https://github.com/WebReflection/linkedom), which is much faster than Cheerio or other.

**Comment by zachleat** [comment]
Related #3194

**Comment by zachleat** [comment]
Even more related #3199

**Comment by zachleat** [comment]
Fwiw I do like the API Lume has here, though it’s probably not too fast.

https://lume.land/

<img width="842" alt="image" src="https://github.com/11ty/eleventy/assets/39355/21a260f2-d4bc-4ea6-b94f-96d21b28d830">

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by nhoizey** [comment]
I couldn't find any documentation about what #3199 provides to authors of plugins performing transforms.

Based on your latest comment about Lume's API, does it mean you're still considering different options, so it's not really available yet?

**Comment by zachleat** [comment]
I’m doing some repo cleanup and putting non-3.0 milestoned enhancements into the enhancement queue!

**Comment by zachleat** [comment]
This one somehow moved to #3714! Please follow along over there!
