### ISSUE TITLE
Test viability of `fast-glob` replacements (`fdir` or `tinyglobby`)

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#3167]
https://www.npmjs.com/package/fdir 

found this one via @rphillips-nz!

**Comment by zachleat** [comment]
Note also that `fs.glob` and `fs.globSync` are coming to Node! https://github.com/nodejs/node/pull/51912

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
https://github.com/11ty/eleventy/issues/3586 via @Ryuno-Ki

**Comment by zachleat** [comment]
another vote for tinyglobby from @43081j: https://bsky.app/profile/43081j.com/post/3ljnbo7qlzk24

**Comment by 43081j** [comment]
Also I feel like is-glob can be replaced by tinyglobby (@superchupudev Will know)

**Comment by zachleat** [comment]
https://github.com/e18e/ecosystem-issues/issues/140

**Comment by SuperchupuDev** [comment]
> Also I feel like is-glob can be replaced by tinyglobby ([@SuperchupuDev](https://github.com/SuperchupuDev) Will know)

pretty sure it can with `isDynamicPattern`, worst case `picomatch.scan().isGlob` can be used (picomatch is already a tinyglobby dependency)

**Comment by zachleat** [comment]
We’ve shipped https://github.com/11ty/eleventy/pull/3680 to v3.0.1-alpha.1
