### ISSUE TITLE
Extension aliasing without including the parent files

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#319]
As it stands currently, the fix for #207 requires the alias target to also be parsed.

That means if you add an alias for `markdown` to target `md` files, that both `markdown` and `md` files would be parsed. As it stands, aliasing works like this:

* `md` only (parent only, no alias)
* `markdown` and `md` (alias and parent)
* NOT ALLOWED YET: `markdown` only (alias only, no parent)

Is this necessary? Is this bad? Should additional work be done to remove this requirement? Thoughts please!

(This ticket should also be considered an enhancement request to remove this requirement, so please leave your upvotes in favor)

**Comment by kleinfreund** [comment]
The most robust is creating a mapping of file extensions and their individual processors. The term alias is not quite right here, as it requires a *default extension* to alias to.

I think Eleventy should know of a set of extensions for each processor: For Markdown, it should know `md` and `markdown` (are there more?) and treat them absolutely identical.

**Comment by jevets** [comment]
I've seen `.mdown`, too

**Comment by zachleat** [comment]
Ah, for the record I think it might be clearer if I call what I have now aliasing (adding an alias for `markdown` will parse both `*.md` and `*.markdown` files as markdown templates)

The thing that is not supported is *renaming* (renaming `md` to `markdown` would parse only `*.markdown` as markdown templates).

**Comment by zachleat** [comment]
Yeah, I think this needs a little more thinking/work before 0.7.0 is released.

**Comment by zachleat** [comment]
I think y’all could see my hesitation in this discussion so this is going to be closed and resolved in a better way for the future #207 implementation so that questions like this are hopefully unnecessary.
