### ISSUE TITLE
Eleventy unable to find and render layouts within _includes

### ISSUE THREAD

**Issue by jonathonpday** [11ty/eleventy#3190]
### Operating system

macOS Sonoma Version 14.2.1

### Eleventy

2.0.1

### Describe the bug

I have a very basic eleventy website set up like this:

.
└── eleventy-crash-course/
    ├── _site/
    │   └── src  /
    │       └── _includes/
    │           ├── index.html
    │           └── layouts/
    │               └── base/
    │                   └── index.html
    ├── node_modules
    ├── src/
    │   └── _includes/
    │       └── layouts/
    │           └── base.njk
    ├── .eleventy.js
    └── index.njk

The `base.njk` looks like this:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ title }}</title>
  </head>
  <body>
    {{ content | safe }}
  </body>
</html>
```

The` index.njk`:

```
---
layout: base.njk
title: Home Page
---

This is a home page
```

And the ` .eleventy.js`

```
module.exports = function(eleventyConfig) {
  return {
    dir: {
      input: 'src',
      output: '_site',
      includes:  '_includes',
    },
    templateFormats: ['md', 'njk', 'html'],
    markdownTemplateEngine: 'njk',
    htmlTemplateEngine: 'njk',
    dataTemplateEngine: 'njk', 
  };
}
```

It is all very simple, but no matter what I do I always get the following error in the log when running `eleventy --serve`

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] TemplateLayoutPathResolver directory does not exist for base.njk: _includes (via Error)
[11ty] 
[11ty] Original error stack trace: Error: TemplateLayoutPathResolver directory does not exist for base.njk: _includes
[11ty]     at TemplateLayoutPathResolver.findFileName (/Users/jonathonday/.nvm/versions/node/v18.13.0/lib/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:105:13)
[11ty]     at TemplateLayoutPathResolver.init (/Users/jonathonday/.nvm/versions/node/v18.13.0/lib/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:74:28)
[11ty]     at new TemplateLayoutPathResolver (/Users/jonathonday/.nvm/versions/node/v18.13.0/lib/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:21:10)
[11ty]     at new TemplateLayout (/Users/jonathonday/.nvm/versions/node/v18.13.0/lib/node_modules/@11ty/eleventy/src/TemplateLayout.js:17:20)
[11ty]     at TemplateLayout.getTemplate (/Users/jonathonday/.nvm/versions/node/v18.13.0/lib/node_modules/@11ty/eleventy/src/TemplateLayout.js:57:20)
[11ty]     at Template.getLayout (/Users/jonathonday/.nvm/versions/node/v18.13.0/lib/node_modules/@11ty/eleventy/src/Template.js:146:27)
[11ty]     at Template.getData (/Users/jonathonday/.nvm/versions/node/v18.13.0/lib/node_modules/@11ty/eleventy/src/Template.js:376:25)
[11ty]     at async TemplateMap.add (/Users/jonathonday/.nvm/versions/node/v18.13.0/lib/node_modules/@11ty/eleventy/src/TemplateMap.js:65:16)
[11ty]     at async Promise.all (index 0)
[11ty]     at async TemplateWriter._createTemplateMap (/Users/jonathonday/.nvm/versions/node/v18.13.0/lib/node_modules/@11ty/eleventy/src/TemplateWriter.js:325:5)
[11ty] Wrote 0 files in 0.03 seconds (v2.0.1)
```

I have tried multiople chnages to .eleventy.js but nothing works and the site will not render as it never seems to find `_includes/layouts`.

IS there anything else I can try?

### Reproduction steps

1. Copy above file structure.
2. Run eleventy --serve

### Expected behavior

Page to run normally and show content.

### Screenshots

<img width="1018" alt="image" src="https://github.com/11ty/eleventy/assets/36718060/e238bb16-9420-4d73-8e4d-255988d667d3">

**Comment by bobmonsour** [comment]
I think you need to change layout: base.njk to layout: layouts/base.njk in your front matter.

**Comment by pdehaan** [comment]
@bobmonsour I don't think the "base.njk" is in the `layouts/` directory though. In fact, it doesn't look like the `layouts/` directory is within the `includes/` directory (based off the file `tree` above):
```
├── src/
│ └── _includes/
│ └── layouts/
│ └── base.njk
```

And looking at the generated `_site/` directory (and it's nested `src/_includes/`, `src/layouts/`, and `src/base/` directories, I'm guessing there is an issue in the `/.eleventy.js` file where it isn't setting the `dir.input` directory to "src/"; but that doesn't make sense given the example .eleventy.js config file above.

```
├── _site/
│ └── src /
│ └── _includes/
│ ├── index.html
│ └── layouts/
│ └── base/
│ └── index.html
```

Actually,... I might be way off on all this... Looking at the VS Code screenshot it gives a different directory structure. It might just be a typo since it looks like the file might be named .nkj instead of .njk.
I'll try rebuilding this locally and see if I can reproduce since I'm scratching my head here.

**Comment by pdehaan** [comment]
https://github.com/pdehaan/11ty-3190
@bobmonsour was 100% correct, you need to specify "layouts/base.njk" (and probably confirm that the layout file has the correct extension in your repo (and not base.nkj, which would cause it to be not found and still cause errors).

**Comment by bobmonsour** [comment]
@pdehaan It looks like we each caught separate issues. I have hit the bad extension problems many times in my own journey.

**Comment by jonathonpday** [comment]
Thanks all for looking.

Unfortunately the issue is still ocurring. I have corrected the extension in base to `njk` and also included `layout: layouts/base.njk` in the front matter.

Still the same error!

I have imncluded shots of the relevent files and structure just to try and make things easier.

<img width="1023" alt="image" src="https://github.com/11ty/eleventy/assets/36718060/69c21665-c76c-4878-9dba-f14f84fe8474">

<img width="807" alt="image" src="https://github.com/11ty/eleventy/assets/36718060/cb11fb26-5324-4217-985f-ea11935573b5">

<img width="184" alt="image" src="https://github.com/11ty/eleventy/assets/36718060/fd8445f9-0d6a-4128-bf0d-feceba4b988c">

**Comment by jonathonpday** [comment]
Sorry - tried the front matter with:
```
layout: layouts/base
layout: layouts/base.njk
```

Neither work:

<img width="803" alt="image" src="https://github.com/11ty/eleventy/assets/36718060/ed7c9671-e324-4f1a-8b8f-849bee9a7edd">

**Comment by ironnysh** [comment]
Looking at the screenshots, it seems that `.eleventy.js` and `index.njk` are in the `layouts` directory.
What happens when you move both outside, so they are directly in the `src` directory?

**Comment by jonathonpday** [comment]
They are out sorry - just how the code editor displays it:

<img width="185" alt="image" src="https://github.com/11ty/eleventy/assets/36718060/8931b617-07d8-4860-a95c-e169a9b9abb9">

**Comment by ironnysh** [comment]
Sorry, `.eleventy.js` should be outside of `src`—in the root

**Comment by ironnysh** [comment]
Like @pdehaan’s tree above:

> https://github.com/pdehaan/11ty-3190 
> 
> ```shell
> tree -a --gitignore -I .git
> .
> ├── .eleventy.js
> ├── .gitignore
> ├── package-lock.json
> ├── package.json
> ├── src/
> │   ├── _includes/
> │   │   └── layouts/
> │   │       └── base.njk
> │   └── index.njk
> └── www/
>     └── index.html
> 
> 5 directories, 7 files
> ```

**Comment by jonathonpday** [comment]
Success!!! - thank you so much.

Just to avoid this in the future do any other files belong in the root or just configs?

**Comment by ironnysh** [comment]
Yay! :-)

I _think_ it’s mostly configs and miscellaneous that you don’t want/need 11ty to process. A `yaml` file of a hosting provider, for example, or a `README` file.

**Comment by jonathonpday** [comment]
Issue appears resolved - need to clarify config files (.eleventy.js etc) must be in the root of the project
