### ISSUE TITLE
docs: document `setChokidarConfig` method

### ISSUE THREAD

**Issue by murtuzaalisurti** [11ty/eleventy#3198]
- Recently came across a scenario where the auto reload feature (watch files) of 11ty wasn't working in a docker container for mounted files.
- You can find the reason here https://syntackle.com/blog/containerizing-a-nextjs-application-using-docker-st_G0u/#live-reloading-hmr.
- Chokidar provides the feature of polling — which you can set in [`chokidar` watch options](https://github.com/paulmillr/chokidar?tab=readme-ov-file#api).
- 11ty does provide a user config method named `setChokidarConfig` to set the chokidar watch options, but I didn't find it documented — instead found it through [mastodon](https://fosstodon.org/@eleventy/111913147362566478).

**Comment by zachleat** [comment]
This should be on the web site shortly, thank you!
