### ISSUE TITLE
Could you tell me more about logo variations generation process?

### ISSUE THREAD

**Issue by aledoroshenko** [11ty/eleventy#32]
How do you use static site generator for those logos?

![](https://i.imgur.com/G3SpJ8O.png)

**Comment by zachleat** [comment]
This is all in the 11ty-logo project: https://github.com/11ty/11ty-logo

Specifically the variations generator is located here: https://github.com/11ty/11ty-logo/blob/master/variations.njk

Basically I feed it a bunch of Google Fonts names in the front matter and then iterate over them in the body to create a ton of different logos. Running eleventy on that project creates a giant HTML test file that looks like this:
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/39355/37967039-c4439cce-318f-11e8-8286-dab5801c43ec.png">

If you have more questions, please ask!
