### ISSUE TITLE
[WARNING] for errors in CI allows build to succeed

### ISSUE THREAD

**Issue by devindford** [11ty/eleventy#3210]
### Operating system

ubuntu:20.04

### Eleventy

2.0.1

### Describe the bug

I currently have a site that is being built with AWS Amplify, recently a stale PR got merged in that had some old frontmatter that was no longer valid (attempting to look for an old layout file). I got the error during the build phase in the CI as expected, but since it outputs as a `[WARNING]` and not an error the build phase was considered successful and the site continued to deploy without content causing an empty site to be deployed. 

Output from followup testing:
```
2024-02-20T15:37:58.251Z [WARNING]: [11ty] You’re trying to use a layout that does not exist: doesnt-have-one.njk (undefined) (via Error)
2024-02-20T15:37:58.251Z [WARNING]: [11ty]
[11ty] Original error stack trace: Error: You’re trying to use a layout that does not exist: doesnt-have-one.njk (undefined)
...
```

It is worth noting that this fails as expected locally, but not in the CI environment.

This is private code but I would be happy to spin up a bare bones example to provide more context here, but I think the issue is fairly straight forward. 

### Reproduction steps

This is tough since it's a specific case to amplify

1. Create a site
2. Add frontmatter to a markdown file `layout: not-real.njk`
3. Push the code up to amplify to build
4. Code should deploy as if there was no error

### Expected behavior

I'd expect this to be an error and not a warning since the site isn't truly being built. Currently I have a custom build script that run and logs any output like this as an error to a text file and check that file prior to the deploy step to fail the builds if the file has content.

**Comment by zachleat** [comment]
We use a non-zero exit code when encountering a fatal error: https://github.com/11ty/eleventy/blob/408563f8daf38b404442d3e0701e752625c2eb2a/src/EleventyErrorHandler.js#L44

AWS should use this and fail your build accordingly!

**Comment by zachleat** [comment]
Are you saying that Eleventy didn’t output an error? I don’t think the `[WARNING]` output is from us

**Comment by devindford** [comment]
@zachleat Appreciate the reply, I'm going to say it's most likely on AWS's side not recognizing the failure. I've added a work around for this, but I think you're correct and the `[WARNING]` comes from AWS. 11ty appears to be outputting the error, but for some reason their CI environment isn't catching it directly and views it as a warning instead of an error. 

The project is fairly basic and simple bash script was able to rectify this issue, but more so now that you've clarified where the error is generated, I guess this is more of a PSA now. Feel free to close 😄

**Comment by zachleat** [comment]
Appreciate it! I did experiment with this for a little bit and the onboarding process for Amplify is _something else_ 😢

**Comment by devindford** [comment]
@zachleat yea it's.... something lol thanks again for taking a look, hopefully they'll get their stuff sorted on the AWS side sometime soon 😅
