### ISSUE TITLE
Trouble rendering files

### ISSUE THREAD

**Issue by EuphoriaCXI** [11ty/eleventy#3217]
I've gotten everything to work mainly, however take the following for example

`{% extends "/_layouts/base.njk" %} {% block title %} Homepage {% endblock %}`

If I don't write src, it gives an error, but my .eleventy.js file is providing an input:

```
module.exports = function (eleventyConfig) {
  return {
    dir: {
      input: "src",
      output: "_site",
      includes: "_includes",
      layouts: "_layouts",
      data: "_data",
    },
  };
};
```

```
1. Having trouble rendering njk template ./src/index.njk (via TemplateContentRenderError)
[11ty] 2. (./src/index.njk)
[11ty]   Error: template not found: /_layouts/base.njk (via Template render error)
```

![screenshot-3217](https://github.com/11ty/eleventy/assets/94039587/deb0d2b8-7ec6-4885-baa9-04db1213af28)

Am I missing something? I've been trying this for a couple of days. Thanks :)

**Comment by Aankhen** [comment]
Could you try `{% extends "_layouts/base.njk" %}`? (A separate layouts directory [comes with caveats](https://www.11ty.dev/docs/config/#directory-for-layouts-(optional)).)

**Comment by EuphoriaCXI** [comment]
I have and it hasn't worked. I don't see the problem using src/_includes as I'm used to referencing like that but from what I'm reading I shouldn't need to, so I'm now thinking that I somehow am linking wrong

**Comment by pdehaan** [comment]
I think you want:
```njk
{% extends "./_layouts/base.njk" %}

{% block title %} Homepage {% endblock %}
```

**Comment by EuphoriaCXI** [comment]
Interesting commit lol.

I'll give that a go, thanks.

**Comment by zachleat** [comment]
https://github.com/11ty/eleventy/issues/67 is the issue you want, thanks!
