### ISSUE TITLE
Duplicate permalink outputs nothing

### ISSUE THREAD

**Issue by danurbanowicz** [11ty/eleventy#322]
Using v6.0.0 I'm setting a default permalink structure for my posts in a directory JSON data file like so:-

```
{
  "permalink": "agenda/{{ page.date | date: '%d-%m-%Y' }}-{{ title | slug }}/index.html"
}
```
Which, as expected outputs a post with the following permalink:-

`/12-01-2019-my-cool-post`

However, when I create a new post with an identical title and date to an existing post, it outputs nothing, and does not output an error.

Expected behaviour would be that Eleventy adds a numeric suffix to the duplicate permalink e.g.

`/12-01-2019-my-cool-post-1`

or that it throws an error.

Could someone try creating a duplicate permalink (using frontmatter data or otherwise) to see what happens?

**Comment by jevets** [comment]
Yup, I'm getting the same behavior. 

I only end up with one file in the build folder, and its contents aren't compiled correctly. Seems to be overwritten by the second post but it's jumbled up.

https://github.com/jevets/eleventy-issue-322

(For now, I'd probably workaround using a `slug` frontmatter data, then update the permalink string to use it or default to the `title | slug` filter.)

**Comment by zachleat** [comment]
A ha! Yes, I agree that a warning (maybe even an error?) is in order here.

**Comment by zachleat** [comment]
We’re going to go with a warning for now and I filed #562 to talk about changing it to an error in the next major version.

**Comment by zachleat** [comment]
Hmm, I think I’m changing my mind on this error behavior. Right now you could get very unpredictable results when you use two permalinks that point to the same output file. I’m leaning towards using a full error for this and failing the build.

**Comment by zachleat** [comment]
Follow along at #562.
