### ISSUE TITLE
Nunjucks file included in Markdown result in unwanted paragraph elements

### ISSUE THREAD

**Issue by josnin** [11ty/eleventy#3232]
### Operating system

Fedora release 35 (Thirty Five)

### Eleventy

2.0.1

### Description
When including Nunjucks files inside Markdown files in Eleventy, the resulting HTML includes unwanted paragraph elements around each loop item in the included Nunjucks file.

### Steps to reproduce
1. Create a Markdown file (`content.md`) with the following content:
    ```markdown
    # My Content
   
    {% include "list.njk" %}
    ```

2. Create a Nunjucks file (`_includes/list.njk`) with the following content:
    ```html
    <ul>
      {% for item in items %}
        <li>{{ item }}</li>
      {% endfor %}
    </ul>
    ```

The resulting HTML  will include paragraph (<p>) tags around each list item:

```html
<ul>
  <p><li>Item 1</li></p>
  <p><li>Item 2</li></p>
</ul>
```

### Reproduction steps

4. See an error

### Expected behavior

The included Nunjucks file should not be wrapped in paragraph tags, maintaining the structure defined in the Nunjucks template.

**Comment by pdehaan** [comment]
@josnin You'll need to look into https://mozilla.github.io/nunjucks/templating.html#whitespace-control to trim the whitespace in the HTML version of the `<ul>`'s `<li>` elements in the `for..in` loop.

**Comment by pdehaan** [comment]
```njk
<ul>
  {%- for item in items %}
    <li>{{ item }}</li>
  {%- endfor %}
</ul>
```

### OUTPUT

```html
<h1>My Content</h1>
<ul>
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
</ul>
```

**Comment by josnin** [comment]
It works, Thanks a lot @pdehaan
