### ISSUE TITLE
Is it possible to know all the pages before execution of a custom transform?

### ISSUE THREAD

**Issue by terpimost** [11ty/eleventy#3238]
### Operating system

Linux

### Eleventy

2.0.1

### Describe the bug

I would like to process all the pages in a deterministic way, but right now pages to custom transform are passed in non deterministic way (order of pages is different on different computers).
Is it possible to somehow have an index of pages before my transform is executed, so I at least can have a sorted list of all pages inside my transform?

**Comment by terpimost** [comment]
Oh, thank you. That helps. Worth of putting it into the docs!

**Comment by zachleat** [comment]
Shipping the `eleventy.contentMap` event to the docs: https://www.11ty.dev/docs/events/
