### ISSUE TITLE
XMPP: Post to PubSub

### ISSUE THREAD

**Issue by sjehuda** [11ty/eleventy#3256]
### Is your feature request related to a problem? Please describe.

I want to publish my 11ty contents over PubSub node items on my XMPP server.

### Describe the solution you'd like

Add support to post to pubsub node items using Moxl library.

### Describe alternatives you've considered

There are no alternatives in a form of a plugin.

### Additional context

Greetings!

In XMPP, using PubSub(1) (XEP-0060), it is possible to store posts as Atom Syndication(2) entries into XMPP(3).

There are several XMPP extensions that apply it, namely XEP-0227 (4) and XEP-0472 (5) which make node `urn:xmpp:microblog:0` as a common choice to manage news for client accounts (e.g. `blog@11ty.dev`), yet a component account (e.g. `pubsub.11ty.dev`) may use all of its nodes for this purpose.

```
pubsub.11ty.dev/
|
|-- updates/
    |-- Sombre
     `-- Varied
|-- releases/
 `-- events/
```
```
pubsub service/
|
|-- node/
    |-- item
     `-- item
|-- node/
 `-- node/
```

A PHP library that can be utilized would be Moxl of Movim.

I have made a script that realizes viewing PubSub node items as Atom XML feeds over HTTP.

1. [XEP-0060: Publish-Subscribe](https://xmpp.org/extensions/xep-0060.html)
2. [RFC 4287: The Atom Syndication Format](https://www.rfc-editor.org/rfc/rfc4287)
3. [Atom Over XMPP](https://datatracker.ietf.org/meeting/66/materials/slides-66-atompub-1.pdf)
4. [XEP-0277: Microblogging over XMPP](https://xmpp.org/extensions/xep-0277.html)
5. [XEP-0472: Pubsub Social Feed](https://xmpp.org/extensions/xep-0472.html)
6. [Moxl](https://github.com/movim/movim/tree/master/src/Moxl)
7. [PubSub Over HTTP](https://codeberg.org/poezio/slixmpp/issues/3526)

**Comment by sjehuda** [comment]
Please reopen it. The effort is small in comparison to the result.

Wrong reference:

> A PHP library that can be utilized would be Moxl of Movim.

There are JS libraries
- http://strophe.im/strophejs/
- https://github.com/xmpp-ftw
- https://github.com/xmppjs/xmpp.js
- https://xmpp4js.sourceforge.net/
- https://stefan-strigler.de/jsjac/

**Comment by zachleat** [comment]
This issue is on the enhancement queue. It needs upvotes!
