### ISSUE TITLE
using a collection in Liquid

### ISSUE THREAD

**Issue by rmschindler** [11ty/eleventy#3264]
### Operating system

macOS Sonoma 14

### Eleventy

2.0.1

### Describe the bug

I’m creating a collection via:
```
eleventyConfig.addCollection("notes", collectionApi => {
    return collectionApi.getAll().filter(note => Boolean(note.data["id"]));
  });
```
I can verify that it works by the messages written in debug mode . but when I want to use it, in my `index.liquid` file, like this:
```
    <ul>
      {%- for note in notes -%}
      <li><a href="{{ note.url }}">{{ note.date }}</a></li>
      {%- endfor -%}
    </ul>
 ```
, nothing shows up . am I missing something?

### Reproduction steps

4. See an error

**Comment by pdehaan** [comment]
I think you need the `collections.` namespace:

```liquid
{%- for note in collections.notes -%}
```

Ref: https://www.11ty.dev/docs/collections/#a-blog-example

**Comment by rmschindler** [comment]
@pdehaan, you nailed it
