### ISSUE TITLE
`---node` frontmatter not documented

### ISSUE THREAD

**Issue by mayank99** [11ty/eleventy#3284]
I was trying to use the Node frontmatter in the 3.0 alpha, and couldn't find any docs on it.

The closest thing I found was this section on custom JavaScript frontmatter: https://www.11ty.dev/docs/data-frontmatter-customize/#example-use-javascript-in-your-front-matter

On that note, I wonder why the built-in functionality uses `---node` and not `---javascript`. The latter seems more accurate, especially since 11ty can now run in alternative runtimes like Deno.

**Comment by mayank99** [comment]
> 11ty can now run in alternative runtimes like Deno.

Actually I couldn't find any docs on this either. Is there an example somewhere?

I'm happy to contribute docs if I can understand how to use it.

**Comment by zachleat** [comment]
Some discussion about this here: https://github.com/11ty/eleventy/issues/2819

**Comment by zachleat** [comment]
Deno information here: https://github.com/11ty/eleventy/issues/3278 and slide 59–60 of this talk: https://www.zachleat.com/web/11tyconf-keynote-2024/

**Comment by zachleat** [comment]
I’m going through the issues closed on the 3.0 milestone and adding `needs-documentation` tags. Let’s use #2819 as the home base for the docs issue for this too.

Can you file a separate issue for your Deno issue? Maybe also have a look at #3278 which shows the command line command that I used to run against `11ty/eleventy-base-blog`.
