### ISSUE TITLE
Eleventy Transform images in RSS feed

### ISSUE THREAD

**Issue by nickcotton** [11ty/eleventy#3294]
Hi! Have been using the new Eleventy Transform feature on my personal site with great success but recently noticed that images in my RSS feed were missing. Upon further investigation, it seems like they aren't getting the same treatment as images in the original posts.

I tried adding xml to the `extensions` option but I guess it doesn't detect img elements within the content of the xml (which totally makes sense). Just wanted to ask if this was supported in some other way I'm not aware of? I couldn't find anything in the docs or other issues.

My feed template is largely copied from the one in the [eleventy-plugin-rss docs](https://www.11ty.dev/docs/plugins/rss/#sample-feed-templates).

Happy to provide any more info that would be helpful. Thanks!

**Comment by zachleat** [comment]
Moving this to core. The root issue here is that HTML transforms don’t execute on collection item `content`. HTML transforms (like the Input Path plugin or Image Transform plugin) only process output `.html` files.

We need a way to programmatically call transforms manually, perhaps via something like a `runTransforms` provided filter.

Also adding https://github.com/11ty/eleventy-plugin-rss/issues/47 related to improvements to the RSS plugin, perhaps we can do this automatically for folks if they use a virtual template for their feed.

**Comment by zachleat** [comment]
The `renderTransforms` filter will ship with 3.0.0-alpha.11.

Usage:

```jinja2
{{ post.templateContent | renderTransforms }}
```

The filter will throw an error if you attempt to use it in a template that already outputs an `.html` file, avoiding double processing there.

**Comment by zachleat** [comment]
This feature is included in https://github.com/11ty/eleventy-plugin-rss/issues/47
