### ISSUE TITLE
Allow addExtension definitions to extend built-in syntaxes (with access to defaultRenderer); working with `tsx` for JSX and TypeScript templates

### ISSUE THREAD

**Issue by pauleveritt** [11ty/eleventy#3300]
My config file extends JavaScript Templates to allow JSX/TSX. It uses `config.addTransform` to render JSX objects into a string.

Everything works fine until I add the `eleventy-img` plugin:

```
  eleventyConfig.addExtension(["11ty.jsx", "11ty.ts", "11ty.tsx"], {
    key: "11ty.js",
  });

  eleventyConfig.addTransform("tsx", async (content: any) => {
    const result = await renderToString(content);
    return `<!doctype html>\n${result}`;
  });

  eleventyConfig.addPlugin(eleventyImageTransformPlugin, {
    formats: ["avif", "png"],
  });
```

Its HTML transform executes before mine. Since it is given an object instead of a string, it returns the string `[object Object]` and my transform no longer has JSX to work on.

The [docs say](https://www.11ty.dev/docs/transforms/): "Transforms added via plugins are inserted via the [second configuration stage for plugins](https://www.11ty.dev/docs/plugins/#creating-a-plugin)." I believe `eleventy-img` is doing its transform before other transforms can step in.

**Comment by pauleveritt** [comment]
Very good, thanks, I'll check when a11 comes out.

**Comment by zachleat** [comment]
See also https://github.com/11ty/eleventy/issues/3298#issuecomment-2140860513

**Comment by zachleat** [comment]
Docs updates shipped here:

https://www.11ty.dev/docs/languages/custom/#overriding-or-extending-an-existing-template-language
https://www.11ty.dev/docs/languages/typescript/
https://www.11ty.dev/docs/languages/jsx/
