### ISSUE TITLE
No “Template render error” or rendering stops when a fault Nunjucks file is inside an if-statement

### ISSUE THREAD

**Issue by Gr0t3Man** [11ty/eleventy#3303]
### Operating system

Pop!_OS 22.04 LTS

### Eleventy

3.0.0-alpha.10

### Describe the bug

Normally Eleventy displays a error “Template render error” and stops processing the rendering when a Nunjucks file/block contains an error, for example is missing a {% endif %} statement.

When the faulty Nunjucks file is placed inside an if-statement, the template rendering is completed without any error. The code inside the faulty Nunjucks file is simply discharged and not rendered in the output file(s).

### Reproduction steps

1. Create a file mood.njk
```
{% if hungry %}
  I am hungry
{% elif tired %}
  I am tired
{% else %}
  I am good!
{% endfor %}
```

2. add a include, inside a if-statement,  to an layout file

        {% if tags == posts %}
          {% include 'mood.njk' %}
        {% endif %}

3. start a eleventy build 

### Expected behavior

When a error is occurred inside an Nunjucks file it's expected that the rendering is stopped and a error is displayed.

**Comment by zachleat** [comment]
Successfully reproduced this one, investigating.

**Comment by zachleat** [comment]
Looks like this one is a Nunjucks issue with an async rendering path in an if statement:

* https://github.com/mozilla/nunjucks/issues/925
* https://github.com/mozilla/nunjucks/issues/372
* https://github.com/mozilla/nunjucks/issues/838
* https://github.com/mozilla/nunjucks/issues/1286

Workarounds include:

* `{% include 'test.njk' if true %}`
* `{% ifAsync true %}{% include 'test.njk' %}{% endif %}`

Not much we can do here, unfortunately. This will need to be fixed upstream in Nunjucks.
