### ISSUE TITLE
Also expose date as extra Luxon object

### ISSUE THREAD

**Issue by flcdrg** [11ty/eleventy#3315]
### Is your feature request related to a problem? Please describe.

I would like to access the original time zone offset that was specified in front matter. eg.

```
2024-03-11T10:00:00.000-07:00
2024-03-31T17:00:00.000+10:30
```

 As far as I can tell, that information is lost when the date is converted to a JavaScript Date.

### Describe the solution you'd like

If there were an additional property eg. luxonDate that was set to the Luxon DateTime object, then that object would be directly available for use.

**Comment by zachleat** [comment]
This is (I believe) solved by #867, shipping soon with 3.0.0-alpha.15! Would love confirmation!
