### ISSUE TITLE
`--quiet=true` doesn't set `config.quietMode` to `true`

### ISSUE THREAD

**Issue by asbjornu** [11ty/eleventy#3316]
When passing `--quiet=true` to the command line, `config.quietMode` isn't set to `true`. I would like to extract the value of `--quiet` in some of my code to silence it in development mode. How do I achieve that?

```js
// .eleventy.js
module.exports = function (config) {
  // always prints `false` regardless of what `--quiet` is set to.
  console.log(config.quietMode);
};
```

I can see from #808 and 727607c0325bcceaba6dabc7a958663d40a25e49 that `isVerbose` is being set, but that property doesn't seem to be exposed in the Eleventy configuration.

**Comment by zachleat** [comment]
Shipping with 3.0.0-alpha.14
