### ISSUE TITLE
`page.outputFileExtension` does not take into account the value of `permalink`

### ISSUE THREAD

**Issue by monochromer** [11ty/eleventy#3323]
### Operating system

MacOS Sonoma 14.5

### Eleventy

2.0.1, 3.0.0-alpha.13

### Describe the bug

I have a template file `index.njk` with this content:

```
---
permalink: '/chart.svg'
---
<svg></svg>
```

In all places, where i can read data cascade variable `page.outputFileExtension` (data files, transforms, etc.), i get value `html` instead `svg`.

Demo Sandbox: https://stackblitz.com/edit/stackblitz-starters-48lqyq

### Reproduction steps

1. Go to https://stackblitz.com/edit/stackblitz-starters-48lqyq
2. Run in the terminal `npm run build`
3. Take a look into console, output should have `svg` instead `html`

### Reproduction URL

https://stackblitz.com/edit/stackblitz-starters-48lqyq

**Comment by monochromer** [comment]
Is `outputFileExtension` only for template engines? Should  i use `outputPath` instead?

**Comment by zachleat** [comment]
Yeah, `page.outputFileExtension` is an alias for the custom engine option here: https://www.11ty.dev/docs/languages/custom/#outputfileextension
