### ISSUE TITLE
`--incremental` is ignored when `--watch` is not present

### ISSUE THREAD

**Issue by LeaVerou** [11ty/eleventy#3324]
Not sure if this is a bug or a feature request. The `--incremental` flag is a wonderful thing: instead of rebuilding a whole site, it rebuilds only the files relevant to the one that changed. However, it seems to only be available when running in watch mode. I’ve often needed to only periodically rebuild; I save often and running the watcher often makes my system veeeery sloooow after a while, especially since I have many 11ty websites that I often edit in parallel. However, this also means I lose access to this wonderful feature: even if I were willing to manually specify the file that changed, there is no way to do so. 

It would be great if `--incremental` worked without `--watch`. It could automatically detect which files have changed by storing the last time it ran somewhere and comparing timestamps. Or, worst case, even if it allowed providing a glob or filename manually, it would still be an immense help.

**Comment by zachleat** [comment]
v3.0.0-alpha.14 will include support for `--incremental=filename` to do an incremental build without `--watch` or `--serve`.

**Comment by zachleat** [comment]
Work based on the `singleTemplateScope` feature that was included for the the serverless plugin: b5fc1c350907e8ca367d6d41e7a52222c6d371d5

More background here: https://www.11ty.dev/docs/plugins/serverless/#compile-the-data-cascade-for-the-project

**Comment by zachleat** [comment]
Example output:

```
npx @11ty/eleventy --quiet --incremental=index.liquid
[11ty/eleventy-img] 1 image optimized (1 cached)
[11ty] Wrote 1 file (skipped 481) in 2.12 seconds (v3.0.0-alpha.14)
```

**Comment by zachleat** [comment]
Subscribe to #984 for full cold-start incremental support!

**Comment by zachleat** [comment]
Filed related issue for `--incremental=glob` enhancement here: #3335

**Comment by deebloo** [comment]
hmmmm to get this working with wireit I need to manually figure out that list of changed files

**Comment by zachleat** [comment]
@deebloo can you file an enhancement request? I’m curious if `--to=json` works for that use case though

**Comment by deebloo** [comment]
@zachleat maybe I am confused then. --incremental=filename only builds that one file right? I was thinking I would need to pass a list of files to 11ty.

**Comment by zachleat** [comment]
@deebloo Ah, no—we’ll generate the dependency map for the file and build the known dependency files too.

**Comment by deebloo** [comment]
gotcha, but if I had two disparate files I would need to do both right? so a.liquid and b.liquid and they had nothing to do with on another

**Comment by zachleat** [comment]
@deebloo sequentially yeah, until we add support for #3334

**Comment by deebloo** [comment]
gotcha I understand now, thanks! it looks like there are other issues that would handle my use-case
