### ISSUE TITLE
Aliasing `markdown` to `md` isn’t quite working right with new `permalink: raw` default

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#3339]
Related to #2780
Conflicting with @paulrobertlloyd’s #3337.

That default change might have been too aggressive, `permalink` strings should still process as `liquid`.

**Comment by zachleat** [comment]
Was a little too loose with “simple” aliases (ones that only contain a `key` on `addExtension` options) in #2780.

In 3.0.0-alpha.15 simple aliases will inherit directly from built-in engines (not a Custom engine).

**Comment by paulrobertlloyd** [comment]
Sweat! Thanks for the quick resolution ❤️
