### ISSUE TITLE
JS import attributes break `watch`

### ISSUE THREAD

**Issue by LeaVerou** [11ty/eleventy#3344]
### Operating system

macOS Sonoma 14.5 (23F79)

### Eleventy

3.0.0-alpha.14

### Describe the bug

If either eleventy.js or any data file contain an import with import attributes, e.g.:

```js
import sections from "../data/sections.json" with { type: "json" };
```

Then `npm run watch` fails with:

<img width="1455" alt="image" src="https://github.com/11ty/eleventy/assets/175836/4b8e4db1-8dbe-4a74-8611-cdd42a5fd789">

`npm run build` works normally.

**Comment by uncenter** [comment]
Duplicate of #3128 (now tracked at https://github.com/11ty/eleventy-dependency-tree-esm/issues/2 though). I'd recommend reading through the first for context on the issue and solutions for it, the second is good to watch if you want to get notifications for when the root issue is resolved.

**Comment by LeaVerou** [comment]
Gah, I should never file issues without searching because "surely nobody else has stumbled on this" 🤦🏽‍♀️ Sorry!
