### ISSUE TITLE
Add support for 11ty.js Virtual Templates

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#3347]
Related: #1612

**Comment by zachleat** [comment]
Shipping with 3.0.0-alpha.15. Pass in the raw JavaScript as the virtual template content, like so:

```js
eleventyConfig.addTemplate("virtual.11ty.js", function(data) {
	return `this is a test ${data.page.url}.`;
});

eleventyConfig.addTemplate("virtual.11ty.js", {
  data: () => ({ var: 2 }),
  render: function(data) {
    return `this is a test ${data.var}.`;
  }
});
```

**Comment by VividVisions** [comment]
Awesome! So, I guess using JS classes as templates (with `data` and `render` methods) will also be as easy as this:

```javascript
import MyTemplateClass from 'mytemplate.js';

const template = new MyTemplateClass({ options: { /* ... */}});
eleventyConfig.addTemplate('virtual.11ty.js', template);
```

**Comment by zachleat** [comment]
@VividVisions any of the 11ty.js formats would work there: https://www.11ty.dev/docs/languages/javascript/

**Comment by zachleat** [comment]
Temporary docs preview URL building here: https://11ty-website-git-v3-11ty.vercel.app/docs/virtual-templates/#javascript
