### ISSUE TITLE
New `IdAttributePlugin` will add `id` attributes to your headings

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#3363]
Rather than rely on template language specific plugins for `id` attributes, a la this one  https://www.npmjs.com/package/markdown-it-anchor we can instead make use of the existing posthtml infrastructure used by the HTML base plugin and the input path to URL plugins to add an `id` attributes to content.

This then pairs nicely with a web component to add anchors to headings for the UX piece, a la @daviddarnes’ https://github.com/daviddarnes/heading-anchors

**Comment by zachleat** [comment]
## Simple usage

```js
import { IdAttributePlugin } from "@11ty/eleventy";

export default function (eleventyConfig) {
	eleventyConfig.addPlugin(IdAttributePlugin);
};
```

## Full options:

```js
import { IdAttributePlugin } from "@11ty/eleventy";

export default function (eleventyConfig) {
	eleventyConfig.addPlugin(IdAttributePlugin, {
		// custom slugify function, otherwise we use Eleventy’s built-in `slugify` filter.
		slugify: function(textContent) {
			// …
		},
		selector: "h1,h2,h3,h4,h5,h6", // default
	});
};
```

**Comment by zachleat** [comment]
(Has the added benefit of removing the unnecessary link markup from your RSS feeds too!)

**Comment by zachleat** [comment]
Temporary docs preview url deploying: https://11ty-website-git-v3-11ty.vercel.app/docs/plugins/id-attribute/

**Comment by SQLKiwi** [comment]
Just to note this enhancement seems to add `id` attributes too late for table of contents generation in a layout.
Why it wasn't working puzzled me for a while, so perhaps the documentation could be clearer on timing?
I ended up reverting to `markdown-it-anchor` for my particular usage.

**Comment by kleinfreund** [comment]
Mainly leaving something here in case others expand on the use of this plugin for generating headings with self-linking anchors.

---

Is there a way to use this plugin (which I'd like as it can add IDs to all HTML not just Markdown) _and_ have some manner of injected HTML in a heading? I currently use markdown-it-anchor not only to add the IDs but also to add some custom markup inside anchors, most notably an anchor link pointing to the heading's ID.

I can see using a custom element for this but I don't want to add any JavaScript to my site as this can be done at build time.

**Comment by rolandsaven** [comment]
Unfortunately, it does not work with `eleventy-plugin-toc` plugin, and the others out there.
