### ISSUE TITLE
Error in variable name when loading Global Data

### ISSUE THREAD

**Issue by buckle2000** [11ty/eleventy#337]
This is related to #231 .

**Expected:**
The variable name should be the relative path to the global data directory.
If I specify `dir.data` as `../_data`, the variable name for `xyz.json` is still `xyz`.

**Actually:**
If I specify `dir.data` as `../_data`, the variable name is `_data.xyz`.

Here is the minimal project to reproduce this code: [archive.tar.gz](https://github.com/11ty/eleventy/files/2659357/archive.tar.gz)

**Comment by zachleat** [comment]
#231 was fixed in 0.7.0 by @kleinfreund, can you have another look @buckle2000?

**Comment by zachleat** [comment]
Test confirming this is fixed has been added https://github.com/11ty/eleventy/blob/f7de5b4844a4d174b1d578a52716f283228036fc/test/TemplateDataTest.js#L324
