### ISSUE TITLE
`renderContent` Universal Filter in Render Plugin

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#3370]
```jinja2
---
hi: "{% test %}"
---
{{ hi | renderContent("njk") }}
```

Related to #3369

This is different from:

```jinja2
---
hi: "{% test %}"
---
{% renderTemplate %}{{ hi }}{% endrenderTemplate %}
```

which renders plain raw text `{% test %}` because only the content `{{ hi }}` is rendered by the `renderTemplate` shortcode (not the return content inside the variable)

**Comment by zachleat** [comment]
Shipping with 3.0.0-alpha.18

**Comment by mar-ver** [comment]
Amazing Thanks!

**Comment by zachleat** [comment]
Temporary docs preview URL deploying here: https://11ty-website-git-v3-11ty.vercel.app/docs/plugins/render/#rendercontent-filter
