### ISSUE TITLE
Throw if `--config` is specified but the file is not found

### ISSUE THREAD

**Issue by LeaVerou** [11ty/eleventy#3373]
I periodically run into this, and it can be quite annoying, sometimes even destructive. 

My 11ty build command usually looks like this:

```
npx @11ty/eleventy --config=somedir/eleventy.js 
```

The current behavior is that if 11ty doesn't find the file specified, it still builds, but using the default config.
This can create a lot of trash in the directory structure that I then need to remove manually.

I’d be inclined to consider it a bug: if I’ve explicitly specified a config file, I literally **never** want to build with the default config. If the config file I specified is not found, that’s a genuine error condition, and 11ty should just let me know and exit early (possibly by helpfully outputting CWD too or the full path it was trying).

**Comment by zachleat** [comment]
I don’t think this is quite accurate! Both 2.x and 3.x alphas do not use any application configuration file when the provided one is not found.

<img width="1552" alt="image" src="https://github.com/user-attachments/assets/b974e850-3777-48d2-ad81-fa0f047a0225">

<img width="1552" alt="image" src="https://github.com/user-attachments/assets/f5ee30db-93e0-4bfd-aa52-5d511ade271f">

I think it’s fair to elevate this to an error though!

**Comment by zachleat** [comment]
I did a bad job and linked to the wrong issue in the commit message https://github.com/11ty/eleventy/commit/d3d03616146126bed029e9db2febad35790e98e9 but this will ship with 3.0.0-alpha.18—thank you!

**Comment by zachleat** [comment]
Temporary docs preview deploying to https://11ty-website-git-v3-11ty.vercel.app/docs/usage/#config-to-change-the-config-file-name
