### ISSUE TITLE
Watch process doesn’t successfully close (3.0.0-alpha.17)

### ISSUE THREAD

**Issue by paulrobertlloyd** [11ty/eleventy#3375]
### Operating system

macOS Sonoma 14.5

### Eleventy

3.0.0-alpha.17

### Describe the bug

Since 3.0.0-alpha.17, its not possible to stop the Eleventy process midway through a build, instead it either:

- appears to close (returned to the terminal prompt) but then new output messages are shown in terminal
- closes but throws an error

The result is that, as I develop locally, and start/stop builds, I’m ending up with many processes running (such that just testing this again now I’m serving my site from port 8087) 

It would appear that `this.watcher` is `undefined` in https://github.com/11ty/eleventy/blob/ff6338f2d2e7a9fce3ee5cb605c180758892bb13/src/Eleventy.js#L1196

Which is odd as this call uses optional chaining.

Likely related to the change in #3361

### Reproduction steps

Error shown after stopping a process mid build:

```
Original error stack trace: TypeError: Cannot read properties of undefined (reading 'close')
     at Eleventy.stopWatch (file:///Users/paulrobertlloyd/Sites/paulrobertlloyd-v4/node_modules/@11ty/eleventy/src/Eleventy.js:1196:22)
     at async process.<anonymous> (/Users/paulrobertlloyd/Sites/paulrobertlloyd-v4/node_modules/@11ty/eleventy/cmd.cjs:120:9)
```

### Expected behavior

Previous behaviour; felt much more robust than it does currently.

**Comment by zachleat** [comment]
Yeah, `await this.watcher?.close();` was added 4 days ago, after 3.0.0-alpha.17. It’ll roll with 3.0.0-alpha.18: https://github.com/11ty/eleventy/commit/6f36fe8d20478bb1fdba53ccd6a9559cb953d849

**Comment by beep** [comment]
Is there any chance this issue might still be occurring? I’m seeing some `eleventy --serve` processes stuck in the Activity Monitor, sometimes for days on end. (11ty v3.0.0, macOS 15.1.1)

**Comment by jackholden** [comment]
I am also experiencing this issue. MacOS 15.2.

Unsure how to debug, will provide a repo shortly.

https://github.com/user-attachments/assets/bccfe19e-5483-466b-8990-4ad5f5ca165c
