### ISSUE TITLE
The code path to produce human-readable error messages if `addFilter()` etc are called on a non-function is throwing

### ISSUE THREAD

**Issue by LeaVerou** [11ty/eleventy#3385]
_(Using 3.0.0.alpha.17)_

As part of almost every 11ty config, I have this little snippet:

```js
for (let name in filters) {
	if (typeof filters[name] === "function") {
		config.addFilter(name, filters[name]);
	}
}
```

Where `filters` is an import containing multiple util functions.

In the project I’m currently working on, at some point I started getting this error message:

<img width="1002" alt="image" src="https://github.com/user-attachments/assets/6389ef64-8b6e-4ea8-ab71-67f5e3306d03">

I was puzzled. There was no `name` anywhere! Clicking through to the call stack revealed this:

<img width="702" alt="image" src="https://github.com/user-attachments/assets/aa8c6999-2e8d-4a0a-a356-759a6ca18d87">

Which made me realize what was happening: I had added some `export const` to my filters file, and trying to add these as filters was understandably throwing.

It looks like there is already a code path to produce a better error message, but _that_ is throwing. 
Fixing it would be a reasonable first step. I’d argue that this is not a reason for complete and total failure either — but I’m going to open another issue for that.

**Comment by zachleat** [comment]
Caught the same in the latest alpha, sorry about that! Fixed here https://github.com/11ty/eleventy/commit/17a065c50425bfab8aec241eb90fdf5da5c2989d#diff-ef495efa0b1aa47730f5ecc48482e10c944d1be2a28f386bd234276a488902d6R309 with https://github.com/11ty/eleventy/pull/3384

Shipping with 3.0.0-alpha.18
