### ISSUE TITLE
eleventy discussions are gone

### ISSUE THREAD

**Issue by btrem** [11ty/eleventy#3391]
Yesterday, I was browsing the 11ty/eleventy discussions forum. Today, every page in discussions returns 404 not found, and the link to discussions (in the navigation with Code, Issues, Pull Requests, etc.) is missing. Was it discontinued?

**Comment by zachleat** [comment]
I’m so sorry I mistakenly clicked the checkbox to disable it on this repo! It’s re-enabled now!

**Comment by btrem** [comment]
I wondered if that was the case. Thanks for re-enabling them so quickly.  :)
