### ISSUE TITLE
Changes to Front Matter Data are only shown after second "save" while running --serve –incremental mode

### ISSUE THREAD

**Issue by Gr0t3Man** [11ty/eleventy#3397]
### Operating system

Pop!_OS 22.04 LTS

### Eleventy

3.0.0-beta.1

### Describe the bug

When running eleventy in --serve –incremental mode the changes mode to the Front Matter Data aren't shown after the first "save" of the file. Only after a second save, the changes are visible in the browser.
I first notices this behavour in 3.0alpha17 and 3.0.0-beta.1 shows the same results.

When running without the –incremental option, the changes are direct visible, after a save.

I have asked in the discord channel if others can reproduce this issue. And others seeing the same problem.

### Reproduction steps

Create a file test.njk
---
title: This a title
text: The first textblock of the page
---

<h1>{{title}}</h1>
<p>{{text}}</p>

After starting npx @11ty/eleventy --serve --incremental.

The page shows:

This a title
The first textblock of the page

Step 2:
When i add some text to the frontmatter data to:
---
title: This a title
text: The first textblock of the page. With a second sentence.
---
And save the file, the screens still shows the old text.

Step 3:
Making an second change to the frontmatter data to:

---
title: This a title, extra long title!
text: The first textblock of the page. With a second sentence.
---

And save the file, the screen displays:
This a title
The first textblock of the page. With a second sentence.

Step 4:
Doing a second save (no text changes), the screen displays:
This a title, extra long title!
The first textblock of the page. With a second sentence. 

### Expected behavior

To display the changes directly in the browser, after saving the file.

**Comment by zachleat** [comment]
Shipping with 3.0.0-alpha.19 and 3.0.0-beta.2
