### ISSUE TITLE
LiquidJS import broken as of latest version, 10.16.5

### ISSUE THREAD

**Issue by lexoyo** [11ty/eleventy#3425]
Edit: I created [a PR here](https://github.com/11ty/eleventy/pull/3426): #3426

### Operating system

Fedora Linux 40

### Eleventy

canary

### Describe the bug

Hello
It's probably me, but i can't get even the most simple use case to work:

```sh
➜ node -v
v18.20.4
➜ echo '# Heading' > index.md
➜ npx @11ty/eleventy@canary --serve
[11ty] Eleventy Fatal Error (CLI):
[11ty] The requested module 'liquidjs' does not provide an export named 'default' (via SyntaxError)
[11ty] 
[11ty] Original error stack trace: file:///home/lexoyo/.npm/_npx/82761691191ced73/node_modules/@11ty/eleventy/src/Engines/Liquid.js:2
[11ty] import liquidLib, { Tokenizer, evalToken } from "liquidjs";
[11ty]        ^^^^^^^^^
[11ty] SyntaxError: The requested module 'liquidjs' does not provide an export named 'default'
[11ty]     at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
[11ty]     at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
[11ty]     at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
[11ty]     at async importModuleDynamicallyWrapper (node:internal/vm/module:432:15)
[11ty]     at async /home/lexoyo/.npm/_npx/82761691191ced73/node_modules/@11ty/eleventy/cmd.cjs:57:24
```

This is supposed to work right? Or did I miss something in v3?

### Reproduction steps

follow the getting started guide but with canary

1. echo '# Heading' > index.md
2.  npx @11ty/eleventy@canary --serve

### Result

Error with the import of liquidjs module

### Expected behavior

build the site in _site

### Notes

1. I tried to run the tests of 11ty source / repo and it fails the same
3. eleventy v2 works fine

**Comment by lexoyo** [comment]
When I clone 11ty source code and run the tests it does the same error, is it just me?

**Comment by lexoyo** [comment]
It is linked to the latest version of liquidjs package

```diff
-        "liquidjs": "^10.10.0",
+        "liquidjs": "^10.16.1",
```

the `10.10.0` works fine

**Comment by rdela** [comment]
@lexoyo thanks for all this work, would you mind re-titling this issue to something more relevant like, for example, “LiquidJS import broken as of latest version, 10.16.5”?

Here are my notes and a temporary workaround…

Looks like there is an upstream issue where Eleventy is broken on the latest version of LiquidJS, 10.16.5, from these changes https://github.com/harttle/liquidjs/issues/739

Overriding Eleventy’s LiquidJS to the previous version, 10.16.4, in package.json resolves this.

```json
"overrides": {
  "@11ty/eleventy": {
    "liquidjs": "10.16.4"
  }
}
```

https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides 

Think this import needs to change: 

```js
import liquidLib, { Tokenizer, evalToken } from "liquidjs";
```

https://github.com/11ty/eleventy/blob/7eb257d2a7f795a7eeb518ba2361158f803bed87/src/Engines/Liquid.js#L2

see #3426

**Comment by lexoyo** [comment]
Nice workaround, thx!

> @lexoyo thanks for all this work, would you mind re-titling this issue to something more relevant like, for example, “LiquidJS import broken as of latest version, 10.16.5”?

Done

**Comment by lexoyo** [comment]
Actually in my case the workaround doesn't work. I'm developing Silex free/libre website builder wich generates 11ty templates along with a .gitlab-ci.yaml file stored on the user's gitlab repo. The gitlab pipeline then relies on npx to run 11ty without using a package.json or package-lock.json. [Example site generated](https://gitlab.com/lexoyo/silex_tuto)

Unfortunately, it looks like this results in Silex sites being broken :-/

I don't see any workaround for that

**Comment by rdela** [comment]
Sorry to hear that Alex. CloudCannon builds are also broken for the same reason. Netlify does respect `overrides` and I was able to get the project I am working on building there with it. 

Silex looks very cool.

**Comment by harttle** [comment]
Default export is removed from liquidjs a long time ago but it still works by CommonJS interop.

While 10.16.5 adds `exports.import` and `exports.require` to package.json which changed the imported bundle from cjs to mjs in this case, thus `default` no longer works. Should there by any more issues with this bundle, please file bug to https://github.com/harttle/liquidjs/issues/new, let's see what we can do.

**Comment by jeromecoupe** [comment]
I can report that overriding the liquidjs version in `package.json` solves the problem in my case.

```json
  "overrides": {
    "@11ty/eleventy": {
      "liquidjs": "10.16.4"
    }
  }
```

**Comment by lexoyo** [comment]
I'm curious why we don't have a `package-lock.json` in the project?
Added to the fact that the dependencies have no exact versions it seems dangerous

**Comment by rabbithawk256** [comment]
Can repro your fix, @jeromecoupe - ran `npm installnpm install liquidjs@10.16.4` and Eleventy now runs without issue

**Comment by zachleat** [comment]
cc @harttle

**Comment by harttle** [comment]
Guys, please try latest v10.16.7, which reverted some changes on 10.16.5.

**Comment by jeromecoupe** [comment]
Removed the override in `package.json`, nuked `node_modules` folder and `package-lock.json`, fresh `npm i` with `@11ty/eleventy 3.0.0-alpha.18` which now installs liquidjs 10.16.15. Happy to report that everything is back to normal.

**Comment by zachleat** [comment]
Some package-lock.json discussion at #3100—please chime in

**Comment by zachleat** [comment]
This issue will affect folks that freshly installed Eleventy v3 when `liquidjs@10.16.5` was the latest version but will not affect folks installing Eleventy with current v3 releases moving forward.

v3.0.0-beta.2 and v3.0.0-alpha.19 will ship with `"liquidjs": "^10.16.7"`

**Comment by zachleat** [comment]
Will consider the PR at #3426 separately, thank you!
