### ISSUE TITLE
Rendering excerpt with renderContent and safe filters renders outside container

### ISSUE THREAD

**Issue by aarongoldenthal** [11ty/eleventy#3474]
### Operating system

Windows 11 (and Linux container)

### Eleventy

3.0.0

### Describe the bug

I was trying to work around the issue outlined in https://github.com/11ty/eleventy/issues/1380, but using the built-in `renderContent` filter instead of a custom filter.

The template has:

```njk
<p class="excerpt">{{ post.data.page.excerpt | renderContent("md") | safe }}</p>
```

Without `safe`, it renders correctly, but is escaped:

```html
<p class="excerpt">&lt;p&gt;The excerpt, correctly rendered, but escaped...&lt;/p&gt</p>
```

With the `safe` filter what's rendered is:

```html
<p class="excerpt"></p><p>The excerpt, correctly rendered...</p><p></p>
```

Without `renderContent`, e.g. `<p class="excerpt">{{ post.data.page.excerpt | safe }}</p>`, the content renders as expected, so doesn't seem specific to `safe`.

### Reproduction steps

1. Setup `excerpt` per [this](https://www.11ty.dev/docs/data-frontmatter-customize/#example-parse-excerpts-from-content)
2. Add `eleventyConfig.addPlugin(EleventyRenderPlugin)` to .eleventy.js
3. Create page with excerpt
4. Create Nunjucks template where the content is within another HTML element, rendered with renderContent, and the `safe` filter
6. Content is rendered after the parent element in the template, with an extra `<p>`

### Expected behavior

Content should render as expected in the containing HTML element.

**Comment by zachleat** [comment]
What’s your content template (with the excerpt) look like? Seems okay with this test `.md` file:

```md
---
key: value
---
# Excerpt
<!-- excerpt -->
Full content
```

**Comment by aarongoldenthal** [comment]
After a closer look and some digging, I understand the problem: nested `<p>` tags are not allowed, and `renderContent()` is wrapping everything in a `<p>`, so the browsers are _fixing_ them by auto-closing (per [this](https://stackoverflow.com/questions/43395847/nested-p-tag-auto-closing-opening), and [the spec](https://www.w3.org/TR/html401/struct/text.html#h-9.3.1)). If I change the containing element to something else (e.g. `<div>`) then all is as expected. But, is there an equivalent of `renderContent()` that only renders the inner contents with no container?

**Comment by zachleat** [comment]
Notably, this is a byproduct of using `renderContent("md")` which renders markdown in block mode. You’re right that you can use a `<div>` or you could do something with the `renderInline` method of `markdown-it`: https://github.com/markdown-it/markdown-it/#simple

I’m not sure if this merits an addition but I’m happy to reconsider if other folks weigh in wanting access to rendering markdown inline instead of block!

**Comment by aarongoldenthal** [comment]
> Notably, this is a byproduct of using `renderContent("md")` which renders markdown in block mode. You’re right that you can use a `<div>` or you could do something with the `renderInline` method of `markdown-it`: https://github.com/markdown-it/markdown-it/#simple

That's basically what I'm doing today, which works:

```js
import markdownIt from 'markdown-it';

export default function (eleventyConfig) {
    ....
    eleventyConfig.addFilter('renderHTML', (content = '') =>
        markdownIt({ html: true, linkify: true }).renderInline(content.trim())
    );
   ...
}
```

I was just thinking it was one more custom piece of code to remove, so I'd support inline if there's enough interest.
