### ISSUE TITLE
Passthrough Copy by Glob - default behavior confusing/documents a thing that maybe doesn't work

### ISSUE THREAD

**Issue by clottman** [11ty/eleventy#3475]
My friend @jskinne3 is setting up his first Eleventy site, and texted me tonight with a perplexing issue. I feel pretty well-versed in random Eleventy issues but I was stumped for a while, too! 

After running `npx @11ty/eleventy`, each subsequent build would add a new layer of folders under _site containing a `fonts/something.woff2` file. Each of those builds would also throw an error (attempting to copy _site/fonts/something.woff2 to a file location that already existed? I'm not sure), but the symptom he noticed first was the recursive directory creation under _site. 

So after a few successive builds, he had `_site/fonts`, and also `_site/_site/_site/_site/_site/fonts/something.woff2`

## Setup/Reproduction Steps 
Using Eleventy 3 at first; problem was reproduced as well with Eleventy 2.0.1. 

He has a pretty basic site structure: 
```
project_root/
   node_modules/
   _site/
   index.html
   fonts/
      something.woff2
      something-italics.woff2
   .eleventy.js
 ```
 
 His .eleventy.js was extremely simple, too: 
 ```
module.exports = function (eleventyConfig) { 
   eleventyConfig.addPassthroughCopy("**/*.woff2")
   
   return {};
}
```

## The docs
The [passthrough copy docs](https://www.11ty.dev/docs/copy/#using-globs) seem to suggest that this glob pattern should work. The docs call out that the globs are relevant to the root directory of the project, not the input directory, but that's fine - my friend isn't specifying a different input directory in his config, nor any special output directory. 

But, I can't see how the glob syntax is supposed to work _unless_ the glob is prefixed with a folder path - `fonts/**/*.woff2` will work without infinite _site/ creation, but just `**/*.woff2` as suggested by the docs will not. 

## related issues 
https://github.com/11ty/eleventy/issues/2461 and https://github.com/11ty/eleventy/issues/1134 both seem related to this, but note that in this case, there is not an .eleventyignore in use, nor is there a custom input or output directory being specified at all.

**Comment by jskinne3** [comment]
* My code exemplifying this problem is in [this GitHub repo](https://github.com/jskinne3/portfolio)
* Also, I wrote a blog post about it: [11ty recursive _site error](https://johnskinnerportfolio.com/blog/11ty_recursive_site_error/index.html)

**Comment by Ryuno-Ki** [comment]
My gut feeling:

Input directory is `.` (a.k.a. current directory).
`**/*.woff2` sees `_site/fonts/something.woff2` as well (because it is under `.` and not `.eleventyignored`).
Since it is under `_site` it will be placed under `_site/_site` (because a directory under `.`).

Rinse and repeat.

Possible solutions: Define a folder with the input data (I personally call it `public`. Others have `content` or similar) and tell Eleventy about it. This way I can have drafts or similar in a sibling folder.
Alternatively, add the output directory to `.eleventyignore`.

**Comment by zachleat** [comment]
#1134 is the upstream issue for this. Also #2461 was related.
