### ISSUE TITLE
permalink: false causes an error with sitemap.xml.njk in v3.0.0

### ISSUE THREAD

**Issue by Nooshu** [11ty/eleventy#3503]
### Operating system

Sonoma 14.7

### Eleventy

v3.0.0

### Describe the bug

Basic setup using the 11ty base blog v9.0.0.
have created a set of Markdown files I want to loop through, but I'm only interested in looping through the data (I don't want any resulting HTML files in the site).
adding `permalink:false` in the front matter as mentioned in [the documentation](https://www.11ty.dev/docs/permalinks/#permalink-false) results in the following error:

```
1. Having trouble rendering njk template ./content/sitemap.xml.njk (via TemplateContentRenderError)
[11ty] 
2. url.startsWith is not a function (via TypeError)
```

### Reproduction steps

See above.

### Expected behavior

No error message in the console and no HTML output for files with `permalink: false` in their front matter.

### Screenshots

<img width="1203" alt="Screenshot 2024-10-24 at 10 19 06" src="https://github.com/user-attachments/assets/fe0919e9-966c-4cce-8d8e-8f03e6196568">

**Comment by zachleat** [comment]
This bug happens specifically when you link to a `permalink: false` template and then try to transform that URL (`false`) using the HTML `<base>` plugin (via `pathPrefix` or a Virtual Template RSS feed)

**Comment by zachleat** [comment]
We’ll improve the error messaging for this in v3.0.1

```
[11ty] Problem writing Eleventy templates:
[11ty] 1. Having trouble rendering njk template ./content/eleventy-plugin-feed-blog-title-atom.njk (via TemplateContentRenderError)
[11ty] 2. Invalid url transformed in the HTML `<base>` plugin. Did you attempt to link to a `permalink: false` page? Received: false
```

I think error messaging is the right approach here otherwise you’ll end up with `<a href="false">`  links (et al) in your output, which seems wrong.

**Comment by murfasa** [comment]
Was having the same issue after attempting to override the URL as detailed in the [docs](https://www.11ty.dev/docs/plugins/navigation/#overriding-the-url) on a blog-site using the 11ty official starter.

Thank you for the input @zachleat , it did turn out to be the sitemap. For anyone else facing this issue, I was able to fix it by checking `{% if page.data.permalink != false %}` before using the htmlBaseUrl filter. 

Here's what a snippet from my sitemap.xml.njk looks like:
`{%- for page in collections.all %}
	{% if page.data.permalink != false %}
		{% set absoluteUrl %}{{ page.url | htmlBaseUrl(metadata.url) }}{% endset %}
		<url>
			<loc>{{ absoluteUrl }}</loc>
			<lastmod>{{ page.date | htmlDateString }}</lastmod>
		</url>
	{% endif %}
{%- endfor %}`
