### ISSUE TITLE
Add Windows to travis-ci builds

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#353]
https://blog.travis-ci.com/2018-10-11-windows-early-release

**Comment by zachleat** [comment]
Windows samples here https://travis-ci.org/11ty/eleventy/builds/478638999

**Comment by kleinfreund** [comment]
Maybe we could do something like sorting both expected and actual results.

**Comment by zachleat** [comment]
Tried this again, looks a bit more straightforward this time: https://travis-ci.org/11ty/eleventy/builds/516470666

**Comment by kleinfreund** [comment]
The errors are related to the `url()` function which has some code producing Windows-style path delimiters. This should never happen when dealing with URLs. Should be easy enough to fix. Unfortunately, I no longer have a Windows system available to me to test this. Maybe a fix is possible without by looking at the Travis results.

**Comment by zachleat** [comment]
Looks like this was fixed in #486! Thank you @AndrewAsquith!!

**Comment by zachleat** [comment]
Heck yeah https://travis-ci.org/11ty/eleventy/builds/518844789

**Comment by kleinfreund** [comment]
Heck yeah indeed!
