### ISSUE TITLE
Upgrade liquidjs to 10.19.0

### ISSUE THREAD

**Issue by lsolesen** [11ty/eleventy#3542]
### Is your feature request related to a problem? Please describe.

The jekyll where is not supported by the currently bundled liquidjs where filter. That is fixed in the new version.

### Describe the solution you'd like

Upgrade to 10.19.0 will solve this. See https://github.com/harttle/liquidjs/issues/768

**Comment by zachleat** [comment]
Shipping with v3.0.1-alpha.1
