### ISSUE TITLE
Allow custom cli options

### ISSUE THREAD

**Issue by andeersg** [11ty/eleventy#355]
I was trying to implement a feature for my site to optionally show drafts (like Jekyll has).

Basically I have a front matter flag on posts:
```
draft: true
```
And if I add `--include-drafts` or `--drafts` I could do a check in my eleventy.js to either include or filter out the posts with `draft: true`.

Example:
```
const includeDrafts = process.argv.filter(i => i == '--include-drafts').length > 0 ? true : false;
```

But this is currently not possible because of this check:
https://github.com/11ty/eleventy/blob/master/src/EleventyCommandCheck.js#L73

I think it would make Eleventy even more powerful if it just ignores options it does not recognise so it's possible to add custom functionality with custom options.

**Comment by andeersg** [comment]
If I comment out `throw new EleventyCommandCheckError` this seems to work, but I don't know if this could cause other problems.

**Comment by zachleat** [comment]
Ah, I don’t think this will probably make it in, unfortunately. This behavior has actually saved my butt a few times when I’ve mistyped a command and it failed immediately without writing files.

You can see the decision making behind the behavior here: https://github.com/11ty/eleventy/issues/66 (Eleventy used to operate how you suggested, but was changed to this model for safety reasons)

I’d encourage you to use environment variables instead. We have an example of those in the docs: https://www.11ty.io/docs/data-js/#example%3A-exposing-environment-variables

Related discussion in the `permalink: false` issue that was implemented: https://github.com/11ty/eleventy/issues/61 docs: https://www.11ty.io/docs/permalinks/#permalink%3A-false

And this feature is actually our top feature request to include in core, so it will very likely get included in core soon: https://github.com/11ty/eleventy/issues/188

Sorry, hope that’s not too disappointing of an answer!

(Closing.)

**Comment by andeersg** [comment]
Not disappointing at all, I can live with environment variables :)

Really love Eleventy so far 👍
