### ISSUE TITLE
`InputPathToUrlTransformPlugin` does not work with file names containing spaces

### ISSUE THREAD

**Issue by xplosionmind** [11ty/eleventy#3559]
### Operating system

Fedora 41

### Eleventy

3.0.0

### Describe the bug

When inserting an url-escaped path to a local Markdown file in a Markdown link, the transformation does not work. I tried both with relative and absolute paths, and I tried both escaping and not escaping the space.

### Reproduction steps

1. In the same directory, create two templates, `templateone.md` and `template two.md`.
2. In `templateone.md`, write `[Link to template two](template%20two.md).`
3. The output does not convert the Markdown link to an existing HTML output file

### Expected behavior

The link to `template two.md` should be transformed and working.

### Reproduction

https://github.com/xplosionmind/tommi.space/tree/transform-bug

**Note 1**: the repository is very messed up, that bransh has been published just to debug this issue. (E.g. It is normal that the CSS is broken)
**Note 2**: Please use the file [`content/jam/public/Test.md`](https://github.com/xplosionmind/tommi.space/blob/transform-bug/content/jam/public/Test.md) for debugging
**Note 3**: The function used to generate permalinks might be relevant? https://github.com/xplosionmind/tommi.space/blob/transform-bug/.eleventy.js#L39-L41

**Comment by xplosionmind** [comment]
Thank you @zachleat! Unfortunately, I did not spot the existing issue…

**Comment by zachleat** [comment]
No worries! It is my job to connect the issues!
