### ISSUE TITLE
 Import attributes not yet supported (Error thrown from acorn dependency)

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#3580]
Tracking issue for https://github.com/11ty/eleventy/issues/3128 and https://github.com/11ty/eleventy-dependency-tree-esm/issues/2

**Comment by zachleat** [comment]
Shipping with 3.0.1-alpha.1

**Comment by zachleat** [comment]
You can get this in your project now (before 3.0.1 ships) by installing `@11ty/dependency-tree-esm@1.0.1`

**Comment by Ryuno-Ki** [comment]
Just ran into https://github.com/xtuc/acorn-import-attributes which felt related to this issue. We've got a solution already so that's something.
