### ISSUE TITLE
Broken "build cost" anchor links on image plugin docs

### ISSUE THREAD

**Issue by kleinfreund** [11ty/eleventy#3581]
On https://www.11ty.dev/docs/plugins/image, all "build cost" anchor links (using `#build-cost-🧰#build-cost-%F0%9F%A7%B0`) don't work as the intended anchor has a different name (`#build-cost-🧰`).

**Comment by zachleat** [comment]
It’s a bug with the InputPathToUrl plugin, looks like!

**Comment by zachleat** [comment]
Shipping with v3.0.1-alpha.1
