### ISSUE TITLE
Input Path To Url plugin has trouble with spaces (encoded or not) and diacritics

### ISSUE THREAD

**Issue by Lamecarlate** [11ty/eleventy#3583]
### Operating system

Ubuntu Linux 24.04

### Eleventy

3.0.0

### Describe the bug

When a markdown link contains spaces (within `<>`) or encoded spaces (`%20`) or diacritics (example: `hypothèse`), InputPathToUrlTransformPlugin does not work as intended.

From a file name `hypothèse.md`, instead of generating "/hypothèse", for example, it outputs `/hypothèse.md`.

Generated files are OK, and an html link to "/hypothèse" is working. This is only about markdown links.

### Reproduction steps

1. Get the archive, extract it, `npm install` in it, and `npx @11ty/eleventy --serve`.
2. Go to home page.
3. Click on links (the first, "Plip", is OK, the last three are html and OK, the others aren't).
5. See a 404 error.

[eleventy-sample-inputPathToUrl-test.zip](https://github.com/user-attachments/files/18093505/eleventy-sample-inputPathToUrl-test.zip)

### Expected behavior

I expect the links to lead to the correctly generated html files, whether they contain spaces, %20, or diacritics.

Thanks for the hard work, I'm hoping this issue is correctly written.

**Comment by zachleat** [comment]
Cross linking https://github.com/11ty/eleventy-img/issues/253 (though this is a separate issue!)

The fix for this one will ship with v3.0.1-alpha.1

**Comment by Lamecarlate** [comment]
(yep, it's me too on eleventy-img 😅 thanks for the answer, I look forward to v3.0.1-alpha.1)
