### ISSUE TITLE
Swap fast-glob for tinyglobby?

### ISSUE THREAD

**Issue by Ryuno-Ki** [11ty/eleventy#3586]
### Is your feature request related to a problem? Please describe.

When I was reading [Vite's 6.0 announcement post](https://vite.dev/blog/announcing-vite6.html) I studied [its CHANGELOG](https://github.com/vitejs/vite/blob/v6.0.3/packages/vite/CHANGELOG.md#breaking-changes) to evaluate whether I will need to make changes to a project I'm working on.

I noticed that one of them swapped fast-glob for something else.
Eleventy [uses fast-glob](https://github.com/11ty/eleventy/blob/v3.0.0/package.json#L132), too.

[tinyglobby](https://www.npmjs.com/package/tinyglobby) is using fewer dependencies (so something I saw Eleventy is aiming for over the last versions) while maintaining most of the same API.

### Describe the solution you'd like

Evaluate whether it makes sense to swap one library for another.

### Describe alternatives you've considered

Sticking to what we always do.

### Additional context

The PR linked from Vite's CHANGELOG: https://github.com/vitejs/vite/pull/18243

**Comment by zachleat** [comment]
Let’s group up at #3167!

**Comment by Ryuno-Ki** [comment]
Good call. Totally missed it.
