### ISSUE TITLE
Example: use GitHub actions to deploy Eleventy to GitHub pages

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#359]
reported by https://twitter.com/acwervo/status/1079502388707250178

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for documentation requests. This means documentation issues will now be closed instead of leaving them open.

View [the documentation queue backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Areactions-%2B1-desc+is%3Aclosed+label%3Adocumentation+label%3Aneeds-votes). Don’t forget to upvote the top comment with 👍!

**Comment by TartanLlama** [comment]
I've made a GitHub Action which runs Eleventy and has an example of how to also automatically publish to GitHub Pages on each push: https://github.com/TartanLlama/actions-eleventy/

**Comment by jonasjohansson** [comment]
I get build error due to unrecognized tags (I have custom 11ty tags and not Liquid), any clue what to do?

**Comment by christian-fei** [comment]
This could help @jonasjohansson  @TartanLlama https://christianfei.com/posts/2019-08-29-Deploy-Eleventy-site-with-Github-Actions-on-AWS-S3/

**Comment by fogrew** [comment]
@TartanLlama I wanted to, but could not take advantage of your action. It would be cool [to use a new approach to API keys](https://github.com/TartanLlama/actions-eleventy/issues/1).

As long as the option above did not work for me, I had to use [my own](https://github.com/fogrew/gurylev.com/blob/master/.github/workflows/eleventy-build.yml). It looks simple enough.

**Comment by zachleat** [comment]
https://www.11ty.dev/docs/deployment/#mini-tutorials
