### ISSUE TITLE
.eleventyignore not ignoring img/

### ISSUE THREAD

**Issue by ericwbailey** [11ty/eleventy#360]
I'm trying to set up a system where `project/src` compiles to `project/dist`, with the idea of using Gulp to supplement Eleventy for things like compiling Sass and optimizing images. Dist will serve as the directory used to serve the site from GitHub pages.

Right now a `.eleventyignore` file that contains `img/` won't prevent Eleventy from copying the contents of `src` to `dist`. I've tried placing `.eleventyignore` in project root and also `src`, as well as different globbing instructions, but nothing really seems to do the trick.

Help me, Obi Wan, you're my only hope!

**Comment by zachleat** [comment]
I’m _guessing_ this is a byproduct of #229. What’s the full path to your `.eleventyignore` file and `img` directory?

**Comment by zachleat** [comment]
If your repo is open source, can you share the url to it?

**Comment by ericwbailey** [comment]
Thanks for taking a look! Our setup is on this branch: https://github.com/a11yproject/a11yproject.com/tree/2019-redesign/develop

`.eleventyignore` is on the project root [here](https://github.com/a11yproject/a11yproject.com/blob/2019-redesign/develop/.eleventyignore).

**Comment by zachleat** [comment]
Ah yes this is definitely a duplicate of #229. Sorry about that! It’s fixed in the upcoming 0.7.0. An `.eleventyignore` file in `src` should do what you want though. Just make sure the entries in the file don’t include the `src` folder. As always the debug output should let you know more information about ignores https://www.11ty.io/docs/debugging/

**Comment by zachleat** [comment]
I’m going to log this as a duplicate for now, please retest after 0.7.0 and confirm that it’s working (unless you use the workaround noted above).

Thank you!

**Comment by ericwbailey** [comment]
Great, thank you!

**Comment by ericwbailey** [comment]
I just upgraded to 0.7.1 and am still experiencing the issue.

**Comment by zachleat** [comment]
I think this is operating how it’s intended after 0.7.0+:

<img width="777" alt="image" src="https://user-images.githubusercontent.com/39355/51078340-42dacc00-1679-11e9-97b7-d0ab2b8a0411.png">

However, those two directories are specified as `passthroughCopy` directories in your `.eleventy.js`:

<img width="595" alt="image" src="https://user-images.githubusercontent.com/39355/51078348-58e88c80-1679-11e9-84bc-78c305dd9307.png">

`passthroughCopy` paths override `.eleventyignore` entries, which I think is what we want to happen? If someone disagrees with that let me know!

**Comment by ericwbailey** [comment]
Ohmygod, I'm a dummy. This worked like a charm, thank you!
