### ISSUE TITLE
Tests invoke illegal constructor TemplateData()

### ISSUE THREAD

**Issue by kleinfreund** [11ty/eleventy#362]
In [`test/TemplateTest.js`](https://github.com/11ty/eleventy/blob/master/test/TemplateTest.js) and [`test/TemplateDataTest.js`](https://github.com/11ty/eleventy/blob/master/test/TemplateDataTest.js), the following is used:

```js
let dataObj = new TemplateData();
```

However, `TemplateData()` takes one argument (`inputData`). This leads to an unexpected data directory path starting with `undefined/`. This is not caught by any of the tests and creates problems for #231.

Possible solutions:

- Never invoke `TemplateData()` in the tests without its required arguments
- Assign a default value to its argument `inputDir`

Since in regular Eleventy application, `TemplateData()` is never invoked without an argument, the tests shouldn’t either. Adding a path like this …

```js
let dataObj = new TemplateData("./");
```

… doesn’t break any tests and avoids the illegal invokation of the constructor, too.

(This is a development-specific bug with Eleventy’s tests.)

**Comment by kleinfreund** [comment]
I updated the original report with information on how to change the tests to not break any tests while avoiding invoking the constructor without an argument.

**Comment by zachleat** [comment]
Sounds good to me! Can submit a PR with `TemplateData("./test/stubs/")` calls? It’s kinda the default directory for test content.

**Comment by kleinfreund** [comment]
@zachleat That would breaks three tests, however. I choose the other string because it broke none. The default directory was my first try.

**Comment by kleinfreund** [comment]
## https://github.com/11ty/eleventy/blob/master/test/TemplateDataTest.js#L105

```diff
TemplateDataTest › Global Dir Directory

  /home/phil/dev/repos/eleventy/test/TemplateDataTest.js:107

   106:                                                                              
   107:   t.deepEqual(await dataObj.getGlobalDataGlob(), ["./_data/**/*.(json|js)"]);
   108: });

  Difference:

  [
-   './test/stubs/_data/**/*.(json|js)',
+   './_data/**/*.(json|js)',
  ]
```

## https://github.com/11ty/eleventy/blob/master/test/TemplateTest.js#L1197 (and L1229)

```diff
TemplateTest › Data Cascade (Deep merge)

  /home/phil/dev/repos/eleventy/test/TemplateTest.js:1210

   1209:   let data = await tmpl.getData();       
   1210:   t.deepEqual(Object.keys(data).sort(), [
   1211:     "datafile",

Difference:

  [
    'datafile',
    'frontmatter',
-   'globalData',
+   'page',
-   'globalData2',
+   'parent',
-   'globalDataFn',
+   'pkg',
-   'page',
+   'tags',
-   'parent',
-   'pkg',
-   'subdir',
-   'tags',
-   'testData',
-   'testDataEjs',
  ]

```
