### ISSUE TITLE
More flexible date options based on parseable inputPaths

### ISSUE THREAD

**Issue by gerwitz** [11ty/eleventy#365]
I am moving a blog site from Middleman, and have hundreds of posts. This makes it laborious to scroll through a single directory, so I break them into years:

    2018/
      12-25-christmas.md
      12-31-last-day.md
    2019/
      01-01-welcome-to-2019.md

This is enabled by Mustermann-style input path matching like `{year}/{month}-{day}-{slug}.md` but given that Eleventy has a point-of-view on date formats, I think it would be appropriate to allow recursive traversal of input files and match directory separator characters as date part separators.

**Comment by gerwitz** [comment]
Indeed, that option would be a great way to enable this without taking a strong stance on input formatting.

**Comment by gerwitz** [comment]
If anyone reading this could give a Node newbie some hints for monkeypatching this as a short-term workaround, I'd be grateful.

**Comment by zachleat** [comment]
This super-overlaps with #335. Maybe even to the point of filing as a duplicate, not sure? Maybe add an upvote over there?

**Comment by zachleat** [comment]
Alright, thanks! Closing this one. :+1:
