### ISSUE TITLE
Should setWatchJavaScriptDependencies(true) traversing through node_modules ?

### ISSUE THREAD

**Issue by okitavera** [11ty/eleventy#375]
It almost takes a half of minutes to get the BrowserSync fired
I don't know if it's normal or not.

![DEBUG=* eleventy --serve](https://i.imgur.com/h1eP2iw.png)

Also, my environment is 
* Eleventy 0.7.0
* Node v11.6.0
* Archlinux

**Comment by zachleat** [comment]
Hmm, this is way costlier than I’d like but I think it’s a mistake on my end. I’m filtering the dependencies at the end and not using `dependency-tree`’s internal `filter` feature, which seems to be much faster. Sorry about that!

**Comment by zachleat** [comment]
This will ship with 0.7.1. Also added a benchmark warning on it.
