### ISSUE TITLE
Always ignore node_modules

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#383]
Previous confusion at #54, #377 (related #382), and #318.

I’d like to turn this on by default, and provide an escape hatch in user configuration to disable it.

Current behavior: `node_modules` are ignored by default only if `.gitignore` does not exist. If a `.gitignore` file does exist, there is no special exception for `node_modules`.

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
More confusion at https://twitter.com/brob/status/1085572161287393281

**Comment by binyamin** [comment]
This could work well with #1405 (eg. as a default value)

**Comment by zachleat** [comment]
Shipping with 1.0—going with @binyamin’s idea to add an `ignores` Set to the config with a `node_modules/**` default!

Docs will show up at https://www.11ty.dev/docs/ignores/ in a bit
