### ISSUE TITLE
how to access directory specific data from a template in that directory

### ISSUE THREAD

**Issue by corderophi678** [11ty/eleventy#385]
Apologies if this is a dupe issue, I've been unable to find what I'm looking for here (closest thing seems to be #273) or in the docs (I would've expected it to be on the [template and directory data files](https://www.11ty.io/docs/data-template-dir/) page. Alternatively, maybe I'm mistaken about the point or role of directory/template data files.

I've got an "About" page on a site I'm working on, built from the files in an `about` folder, in which there's an `index.liquid` file and an `about.11tydata.js` file, from which I export an array of items that I want to iterate through in the `about/index.liquid` file. How might I accomplish this? I was under the impression that having a data file in a template directory would expose the data to the template in that directory (and only that (or those) template(s)). But it's unclear, to me at least, how that data is exposed in the template.

Thanks, cheers, and ❤️

**Comment by zachleat** [comment]
What’s your `about.11tydata.js` file look like?

**Comment by corderophi678** [comment]
`module.exports = [{ name: "potato" }, { name: "clambake" }];`

**Comment by paulshryock** [comment]
I've been using directory data like this:

**File structure:**

```
/src
├─┬ /about
  ├── index.liquid
  ├── about.json
```

**`/src/about/about.json`:**

```javascript
{
  "name": "Raymond Jones",
  "expertise": [
    {
      "name": "Front End Development",
      "skills": [ 'HTML', 'CSS', 'JavaScript' ]
    },
    {
      "name": "Web Design",
      "skills": [ 'Sketch', 'InDesign', 'Photoshop' ]
    }
  ] // etc.
}
```

**`/src/about/index.liquid`:**

```html
<p>Hi, my name is {{ about.name }}!</p>
<p>My expertise:</p>
<ul>
  {% for expertise in about.expertise %}
    <li>{{ expertise.name }}</li>
  {% endfor %}
</ul>
<p>My skills:</p>
<ul>
  {% for expertise in about.expertise %}
    {% for skill in expertise.skills %}
      <li>{{ skill }}</li>
    {% endfor %}
  {% endfor %}
</ul>
```

Does that help?

**Comment by corderophi678** [comment]
Hey Paul, thanks for this. I've tried it with no luck, though. Might there be something I'm missing from my config or frontmatter?

**Comment by paulshryock** [comment]
> no luck, though.

What specifically isn't working? Does the page get generated in your output folder? The dynamic values aren't there?

**Comment by paulshryock** [comment]
**`/src/about/about.json`:**

```javascript
{
	"name": "Raymond Jones",
	"expertise": [
		{
			"name": "Front End Development",
			"skills": [ "HTML", "CSS", "JavaScript" ]
		},
		{
			"name": "Web Design",
			"skills": [ "Sketch", "InDesign", "Photoshop" ]
		}
	]
}
```

**`/src/about/index.liquid`:**

```html
---
title: About
slug: about
---
<p>Hi, my name is {{ name }}!</p>
<p>My expertise:</p>
<ul>
  {% for expertise in expertise %}
    <li>{{ expertise.name }}</li>
  {% endfor %}
</ul>
<p>My skills:</p>
<ul>
  {% for expertise in expertise %}
    {% for skill in expertise.skills %}
      <li>{{ skill }}</li>
    {% endfor %}
  {% endfor %}
</ul>
```

**Comment by paulshryock** [comment]
This is a working example of how to access directory specific data from a template in that directory when using Eleventy: https://github.com/paulshryock/eleventy-page-data

**Comment by corderophi678** [comment]
Ahh, so it's the `slug` frontmatter key that effectively "registers" the appropriate data file? Thanks for your help, Paul. I really appreciate it. Calling this issue closed.

**Comment by paulshryock** [comment]
> so it's the `slug` frontmatter key that effectively "registers" the appropriate data file?

I hadn't mentally made that connection, but you could be right. I was thinking the files just need to be in the same directory. @zachleat, any insight on which it is?
