### ISSUE TITLE
404 support in `eleventy serve`

### ISSUE THREAD

**Issue by clottman** [11ty/eleventy#386]
I'm trying to set up an eleventy site in [Glitch](https://glitch.com), which doesn't have default 404 routing like Github Pages and Netlify do. I've tried futzing around with some advanced Glitch configuration options to set up 404 routing, but it's trickier than I'd like. 

It would be really cool if people who are using the browser-sync server provided by `eleventy serve` could configure it to provide 404 routing. [This issue](https://github.com/BrowserSync/browser-sync/issues/1398) suggests how it could be done in each of the places that `this.server.init` is called in [src/EleventyServe.js](https://github.com/11ty/eleventy/blob/master/src/EleventyServe.js).

I want to work on creating a pull request for this behavior, but I'm not sure how it fits into configuration of eleventy - should it be on by default, or off by default and configured through an option passed in to `serve`? Or an option provided in `.eleventy.js`?

**Comment by zachleat** [comment]
Looks like we need to expose a configuration option for the browsersync init callback here (a method to set this callback if you want to use it): https://www.browsersync.io/docs/api#api-init

would be used here https://github.com/11ty/eleventy/blob/master/src/EleventyServe.js#L146

Config stuff is here https://github.com/11ty/eleventy/blob/master/src/UserConfig.js

**Comment by zachleat** [comment]
(Oh, also to answer your question yes I would be happy to merge this into core after we get it figured out 👍)

**Comment by zachleat** [comment]
Thank you so much for this! Great addition!

**Comment by zachleat** [comment]
This addition was added to the default `eleventy-base-blog`. Thanks! https://github.com/11ty/eleventy-base-blog/commit/e2be85925d9c43f9a56dc4fd2767ca42d2acf2be

**Comment by andersk** [comment]
You should do `res.writeHead(404)` before `res.write(content_404)`, so as to actually serve the 404 page with status 404, not 200.
