### ISSUE TITLE
Recreate a few popular jekyll plugins

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#394]
cc @chrisdmacrae, who provided the following lists:

https://github.com/topics/jekyll-plugin?o=desc&s=stars
https://github.com/planetjekyll/awesome-jekyll-plugins/blob/master/README.md

**Comment by zachleat** [comment]
This needs to be made into more granular issues.

**Comment by chrisdmacrae** [comment]
@zachleat I'm going to be building an SEO plugin, an a11y linter plugin, a menus plugin, and an i18n plugin for my starter. 

So you can strike those from your list. 👍

**Comment by DirtyF** [comment]
Created separated issues for plugins mentioned by @chrisdmacrae 

- [ ] SEO: #417  
- [ ]  a11y: #418 
- [ ]  menus: #419 
- [ ]  i18n: #420

**Comment by chrisdmacrae** [comment]
@dirtyf any other jekyll plugins you think would be good candidates for 11ty?

**Comment by DirtyF** [comment]
Other Jekyll core plugins include sitemap, redirects, import, compose (less powerful than Hugo archetypes) and archives. 

I find myself using the PWA plugin based on Workbox and the Cloudinary plugin to help deal with responsive images.

Images and PWA are amongst most popular [Gatsby plugins](https://www.gatsbyjs.org/plugins/), because they help getting the best performance on LightHouse I guess.

I also use a plugin for HTML minification and purgecss.

**Comment by chrisdmacrae** [comment]
@dirtyf

Sounds good. My SEO plugin will handle meta, sitemap(s), robots.txt and humans.txt, and linting markup. 

I'm going to build a parcel plugin to recreate gatbsy's sharp image plugin in place of something like cloudinary, and can likely get the lazy loading in as well. 

Redirects is a good idea too, but I don't think that's really possible with 11ty right now. 

Parcel already minifies HTML, but a plugin could be created to let vanilla 11ty do this as well. 

Import and compose aren't really possible right now, as you can't extend 11ty's CLI with plugins.

**Comment by Ryuno-Ki** [comment]
Another suggestion: Web Analytics.
With the option to pick Google Analytics, Adobe Analytics, Matomo (formerly known as Piwik) and others.

Oh, and social sharing (Twitter, Facebook, Mastodon, diaspora*, Instagram, …) could be interesting as well.

What about linking to profiles? GitHub, Twitter, Facebook, StackOverflow …

**Comment by bjankord** [comment]
> I'm going to build a parcel plugin to recreate gatbsy's sharp image plugin in place of something like cloudinary, and can likely get the lazy loading in as well. @chrisdmacrae 

That would be amazing! Coming from gatsby, that was one feature I was really missing and had decided to replace that functionality I had with gatsby with https://github.com/eeeps/eleventy-respimg

Not sure if this falls under popular jekyll plugins but a feature to calculate read-time via https://github.com/ngryman/reading-time would nice 👍

**Comment by Ryuno-Ki** [comment]
@bjankord Look at [eleventy-plugin-reading-time](https://www.npmjs.com/package/eleventy-plugin-reading-time) :-)

Would you mind renaming your plugin to start with „eleventy-plugin-” so that once #405 gets resolved it can be discovered more easily?

**Comment by bjankord** [comment]
Oh, the eleventy-respimg plugin is not my plugin, it's @eeeps's plugin. I just found it interesting.

**Comment by jeremenichelli** [comment]
Hi folks, I was thinking on adding filters that Jekyll built on top of Liquid (`date_to_rfc822`, `date_to_xmlschema`, `xml_escape`, `markdownify`) and opened an issue (https://github.com/11ty/eleventy/issues/549) for it. Before starting work on that I wanna ask collaborators, maintainers and author if they agree with adding them :)

**Comment by zachleat** [comment]
Howdy y’all, I collected the new plugin requests on this label: https://github.com/11ty/eleventy/issues?q=label%3A%22enhancement%3A+new+plugin%22+is%3Aclosed

Please file new issues for specific plugins if they come up!
