### ISSUE TITLE
Document the development of plugins

### ISSUE THREAD

**Issue by pheyvaer** [11ty/eleventy#395]
Is there any documentation on the development of plugins? If not, is there a plan to create some?

At the moment I'm thinking of developing a plugin that looks for files with a specific extensions and then processes them before adding the processed data to the data that is available in the templates. Is there anything about something like that? Thanks!

**Comment by bikingbadger** [comment]
Interested in how you are looking at creating plugins. Is there a certain way of doing this or just a method that you hook into in the config file?

**Comment by Ryuno-Ki** [comment]
We have a [list of plugins](https://www.11ty.io/docs/plugins/) you could learn from.
Given that it is a documentation issue, would you mind [opening a ticket in the other repo](https://github.com/11ty/11ty.io/issues/new/choose)?
