### ISSUE TITLE
any plan for PWA for 11ty?

### ISSUE THREAD

**Issue by ajmalafif** [11ty/eleventy#400]
Hi all, I was wondering if there's any plan at all to have PWA support for 11ty? I managed to get all 💯 for my 🗼Lighthouse score, except for PWA of course. 

I was thinking if there's a way to do it manually if it's not thru 11ty plugins 🤔

**Comment by okitavera** [comment]
For me, Google Workbox is the easiest way to get this things done.

If you don't mind debug it while in `eleventy --serve` situation, you can add it on your end of build process on your task runner with workbox-build or directly in your npm script using workbox-cli.

But if you want to workbox to regenerate your service-worker automatically everytime you change something while in the local test environment, you need to either make your own watcher on your task runner, or using [eleventy-plugin-pwa](https://www.npmjs.com/package/eleventy-plugin-pwa).

**Comment by ajmalafif** [comment]
hey @okitavera thanks I wasn't aware of these options, will take a look at Google Workbox, feels like I would go with the latter so I might have to check out the plugin or add own watcher. Thanks again! Feel free to share any example if you have any
