### ISSUE TITLE
[RFC] Refactor Eleventy.js to extend eventEmitter

### ISSUE THREAD

**Issue by chrisdmacrae** [11ty/eleventy#406]
Currently `Eleventy.js` is just a standard JavaScript class with methods.

This makes it very hard to expose Eleventy's lifecycle to end-users.

Refactoring `Eleventy.js` to extend `EventEmitter` will allow you to easily add lifecycle hooks to the Eleventy pipeline, and they could be exposed through `.eleventy.js`.

This would also afford the same functionality as Jekyll hooks.

**Comment by kleinfreund** [comment]
I’d like to see some built-in hooks to be available, in particular one for accessing documents (especially Markdown) before they’re and after they’ve been transformed to HTML. I haven’t wrapped my head around this completely, but I can imagine there being use cases where you want to access unprocessed Markdown or the resulting HTML in transforms. Maybe we should have pre-templating and post-templating transforms?

**Comment by chrisdmacrae** [comment]
@kleinfruend I'm building this feature. 

What kind of hooks would you like to see?

**Comment by dweidner** [comment]
I am exploring ways to rewrite relative image urls in my markdown files. My first attempt intersepts the image renderer in the markdown library. That somehow works, but I do not have access to the front-matter of the corresponding template, which makes the solution a lot less flexible as it is difficult to determine the output path of the page (somehow related to #379). Hooks could help here and would allow plugins to rewrite (relative) image urls in the markdown content before they are passed to the actual parser/library.

**Comment by zachleat** [comment]
Programmatic API related issues: #136

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by chrisdmacrae** [comment]
@zachleat the user config already exposes an eventemitter. So really, it just needs to be implemented at lifecycle events

**Comment by zachleat** [comment]
https://www.11ty.dev/docs/events/
