### ISSUE TITLE
Feature request: support the excerpt feature of gray-matter

### ISSUE THREAD

**Issue by dweidner** [11ty/eleventy#410]
The parser used by eleventy supports post excerpts following the front-matter of a document (see [gray-matter@npmjs](https://www.npmjs.com/package/gray-matter#optionsexcerpt)). Currently eleventy does not enable this feature as noted in https://github.com/11ty/eleventy/issues/179#issuecomment-406822647. I would love to use this feature, instead of introducing an additional front-matter field.

**Comment by kleinfreund** [comment]
If you want to generate post excerpts on your own today, you can define your own shortcode. I use the following:

.eleventy.js

```js
module.exports = function (eleventyConfig) {
  // Defines shortcode for generating post excerpts
  eleventyConfig.addShortcode('excerpt', post => extractExcerpt(post));
};

/**
 * Extracts the excerpt from a document.
 *
 * @param {*} doc A real big object full of all sorts of information about a document.
 * @returns {String} the excerpt.
 */
function extractExcerpt(doc) {
  if (!doc.hasOwnProperty('templateContent')) {
    console.warn('❌ Failed to extract excerpt: Document has no property `templateContent`.');
    return;
  }

  const excerptSeparator = '<!--more-->';
  const content = doc.templateContent;

  if (content.includes(excerptSeparator)) {
    return content.substring(0, content.indexOf(excerptSeparator)).trim();
  }

  const pCloseTag = '</p>';
  if (content.includes(pCloseTag)) {
    return content.substring(0, content.indexOf(pCloseTag) + pCloseTag.length);
  }

  return content;
}
```

Use it like this in your post index:

```liquid
{%- for post in pagination.items -%}
<article>

  {% excerpt post %}

</article>
{%- endfor -%}
```

**Note**: Currently, `doc.templateContent` seems to already be HTML. If you have a minification transform running, it will strip the `<!--more-->` comments which causes the excerpt to not trigger properly. I think transforms should be resolved after shortcodes as we currently have no way of hooking into different stages on transforming documents with Eleventy.

**Comment by dweidner** [comment]
Thank you the snippet @kleinfreund. I will use your solution in the meantime. Better than using a custom front-matter attribute.

**Comment by hellocosmin** [comment]
When using Nunjucks, it's as simple as:

```nunjucks
{% for post in pagination.items %}
<article>

  {{ post.templateContent | striptags(true) | truncate(280) }}

</article>
{% endfor %}
```

**Comment by dweidner** [comment]
Unfortunatly that does not work for the current page, as you do not have access to the `templateContent` property on the current page object (as far as I know). You could however lookup the page entry from `collection.all` first.

Furthermore your solution auto-generates an excerpt from a post. I would love to provide a custom excerpt for some of my pages. This would be super easy if eleventy would allow to customize the settings provided to `gray-matter`.

I could help with a pull-request, if it is of interest for other users as well.

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
Docs are avilable for this: https://www.11ty.io/docs/data-frontmatter/#example%3A-using-front-matter-excerpts

**Comment by zachleat** [comment]
Look for it in 0.8.4
