### ISSUE TITLE
Using fallbacks in the shortcodes (as components)

### ISSUE THREAD

**Issue by j-mes** [11ty/eleventy#412]
:wave: Hello!

Following on the idea from [adamduncan/eleventy-shortcomps](https://github.com/adamduncan/eleventy-shortcomps) which is an interesting concept. I tried this in a test project to see if I could replicate it but using fallbacks i.e. frontmatter variables overrides either inside `_data/file.json` or the defaults in the shortcode.

I am using Handlebars for this project as I'm more familiar with how Handlebars works and I assume this is not a factor. I would love to see how I could fix this and whenever it could be documented in the documentation later for other people to use.

**eleventy.js**
```js
const components = './_includes/components/';
const header = require(`${components}/header.js`);

module.exports = (config) => {

	const handlebars = require('handlebars');
	config.setLibrary('hbs', handlebars);
	
	config.addHandlebarsShortcode('header', header);

	config.addPassthroughCopy('./assets');
	config.setUseGitIgnore(false);

	return {
		dir: {
			input: './',
			output: './_site'
		},
		passthroughFileCopy: true
	};
};
```

**_includes/components/header.js**
```js
module.exports = (title='shortcode title', description ='shortcode description', colour='baby-blue') => {

	// global site setting
	const site = require('../../_data/site.json');
	const siteTitle = site.setting.title;
	const siteDescription = site.setting.description;
	const siteColour = site.setting.colour;

	// page front matter setting
	const pageTitle = title; // not sure how to do this
	const pageDescription = description; // same as above
	const pageColour = colour; // for front matter only

	const headerTitle = pageTitle ? siteTitle : title;
	const headerDescription = pageDescription ? siteDescription : description;
	const headerColour = pageColour ? siteColour : colour;

	return `
		<header class="header ${headerColour}">
			<h1 class="header__title">${headerTitle}</h1>
			<span class="header__description">${headerDescription}</span>
		</header>
	`;
};
```

**_data/site.json**
```json
{
	"setting": {
		"title": "Default Title",
		"description": "Default Description",
		"colour": "ruby-red"
	}
}
```

**index.md**
```md
---
layout: default
title: pageTitle is alive
description: pageDescription is alive.
colour: racing-green
---

# 👋 Eleventy

![A gif of a gif](assets/img/gif.gif)
```
When I run this, it will get the values from the `_data/site.json` fine or from the shortcode itself if I add default values, but not from the frontmatter of `index.md`. Am I missing something really simple :grimacing: ?

Looking forward to seeing other people's insights on this issue I have currently.

Thank you in advance!

**Comment by zachleat** [comment]
Do you have an example of how you’re calling the shortcode inside your `index.md`?

You need to pass in your front matter variables to the shortcode, a la `{{ user firstName lastName }}` on https://www.11ty.io/docs/shortcodes/

`firstName` and `lastName` could be front matter keys there.

**Comment by j-mes** [comment]
Yes, I'll put one up on codesandbox for you today.

**Comment by j-mes** [comment]
Ok, so I passed the shortcode into the `default.hbs` file which is found in `_includes/default.hbs`

```html
<!DOCTYPE html>
<html lang="en-GB">

<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Eleventy 2018 Theme</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" media="screen" href="assets/style.css" />
	<script src="assets/script.js"></script>
</head>

<body>
	{{{ header }}} <!-- This is the shortcode -->
	{{{ content }}}
</body>

</html>
```

If I do not use triple brackets, handlebars will return the `<` or `>` as `&gt;` or `&lt;`. An example of this bit can be seen in this [project](https://github.com/j-mes/eleventy-2018-theme).

Do I need to pass it in the `index.md` file instead of the template file (`default.hbs`)?

**Comment by zachleat** [comment]
I believe your call should be `{{{ header title description colour }}}`

**Comment by j-mes** [comment]
@zachleat Thank you! 

This worked and is something I may overlooked 😬 and I do appreciate you taking the time to look at this issue. I really like Eleventy. It allows me to have more ownership over how I would want to structure a static site generator by doing things like components 😄 

Feel free to close this issue by the way 👍

**Comment by zachleat** [comment]
Awesome! 👍🏻
