### ISSUE TITLE
Invalid Date format 

### ISSUE THREAD

**Issue by DirtyF** [11ty/eleventy#413]
```gherkin
Given I import a blog post from Jekyll
When I run eleventy
Then  an error is raised: `Error: date front matter value (2018-11-20 16:33 +0100) is invalid`
```
According to https://www.11ty.io/docs/dates/, it's not valid. 😞 

That means I have to change the date of all my existing posts?

**Comment by zachleat** [comment]
Where did this date format come from? It’s not a valid YAML or UTC String?

**Comment by DirtyF** [comment]
According to https://yaml.org/type/timestamp.html:
> a more relaxed format is also supported for enhanced readability, using white space separation.

**Comment by zachleat** [comment]
Oh interesting. Are you sure those aren’t accidentally strings? Doesn’t look like YAML tries to parse them at all, as that error comes from a fallback condition where Luxon tries to parse the date string: https://github.com/11ty/eleventy/blob/master/src/Template.js#L613

**Comment by zachleat** [comment]
Can you attach an example of the front matter that’s failing?

**Comment by DirtyF** [comment]
https://raw.githubusercontent.com/DirtyF/11ty.io/bd9eadc58828b4ddfea1597dec09c5d1fc92a86a/docs/test.md.md

**Comment by zachleat** [comment]
Alright I dove in a bit deeper on this and I think it’s a js-yaml bug. We use gray-matter which uses js-yaml.

They have a live demo here: https://nodeca.github.io/js-yaml/

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/39355/54860573-3367a700-4cea-11e9-9730-4a0880afcbd3.png">

Your example returns a string. The following formats do work:

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/39355/54860579-45e1e080-4cea-11e9-83ce-d9d9c2a2f8e6.png">

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/39355/54860583-4d08ee80-4cea-11e9-9fcb-1673875e356f.png">


For comparison YAMLlint thinks your date format is valid, albeit it corrects the formatting by adding a colon to `00:00`:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/39355/54860562-f4d1ec80-4ce9-11e9-8381-3888d05aaf4a.png">
<img width="352" alt="image" src="https://user-images.githubusercontent.com/39355/54860566-0adfad00-4cea-11e9-8991-ba9b86964a5e.png">

Can you file this upstream and provide a link back? https://github.com/nodeca/js-yaml
http://www.yamllint.com/

**Comment by zachleat** [comment]
Hmm, sorry that was closed—but he may be right. 

Note that the string result does match the `pyyaml` implementation:
![image](https://user-images.githubusercontent.com/39355/55975122-deff7980-5c4e-11e9-8cba-8c6f9fad8aff.png)

Here’s the relevant time zone bit from the YAML 1.1 spec (I wasn’t able to actually find this in the YAML 1.2 spec? That might be worth digging deeper into)

`(([ \t]*)Z|[-+][0-9][0-9]?(:[0-9][0-9])?)? # (time zone)`

Note that if the four digit format is used, it requires the `:`.

**Comment by zachleat** [comment]
Hmm, sorry that was closed—but he may be right. 

Note that the string result does match the `pyyaml` implementation:
![image](https://user-images.githubusercontent.com/39355/55975122-deff7980-5c4e-11e9-8cba-8c6f9fad8aff.png)

Here’s the relevant time zone bit from the YAML 1.1 spec (I wasn’t able to actually find this in the YAML 1.2 spec? That might be worth digging deeper into)

`(([ \t]*)Z|[-+][0-9][0-9]?(:[0-9][0-9])?)? # (time zone)`

Note that if the four digit format is used, it requires the `:`.

**Comment by zachleat** [comment]
Hmm, sorry that was closed—but he may be right. 

Note that the string result does match the `pyyaml` implementation:
![image](https://user-images.githubusercontent.com/39355/55975717-305c3880-5c50-11e9-8890-a35cc5635749.png)

Here’s the relevant time zone bit from the YAML 1.1 spec (I wasn’t able to actually find this in the YAML 1.2 spec? That might be worth digging deeper into)

`(([ \t]*)Z|[-+][0-9][0-9]?(:[0-9][0-9])?)? # (time zone)`

Note that if the four digit format is used, it requires the `:`.

**Comment by zachleat** [comment]
Hmm, sorry that was closed—but he may be right. 

Note that the string result does match the `pyyaml` implementation:
![image](https://user-images.githubusercontent.com/39355/55975717-305c3880-5c50-11e9-8890-a35cc5635749.png)

Here’s the relevant time zone bit from the YAML 1.1 spec (I wasn’t able to actually find this in the YAML 1.2 spec? That might be worth digging deeper into)

`(([ \t]*)Z|[-+][0-9][0-9]?(:[0-9][0-9])?)? # (time zone)`

Note that if the four digit format is used, it requires the `:`.

**Comment by zachleat** [comment]
Also note that in the discussion above “a more relaxed format is also supported for enhanced readability, using white space separation” refers to the whitespace between the time and the time zone, not whitespace between the timezone hours and timezone minutes.

`space separated:  2001-12-14 21:59:43.10 -5`

Sorry 😲

**Comment by zachleat** [comment]
Worth noting that feature request #335 may give you an easier out here? Not sure. Might let you avoid having to update all of your data.
