### ISSUE TITLE
Security advisory: update handlebars

### ISSUE THREAD

**Issue by saibotsivad** [11ty/eleventy#424]
Based on https://nodesecurity.io/advisories/755 just need to update the `handlebars` dependency.

> Upgrade to version 4.0.13 or later.

**Comment by zachleat** [comment]
Well that's pretty disappointing considering #371 is a breaking change. Hmm.

**Comment by zachleat** [comment]
Thank you! I was a bit worried this was mustache for a second, which had some breaking major change updates recently 😱
