### ISSUE TITLE
Multi-tier pagination for 'dynamic page' output

### ISSUE THREAD

**Issue by danfascia** [11ty/eleventy#427]
I've read several other issues discussing pagination and I'd like to see how a particular use case is served by current 11ty pagination features.

I'm using this method https://www.11ty.io/docs/quicktips/tag-pages/ to generate tag archive pages for my 'tutorials' collection but run into 2 issues I don't know how to solve:

1. When I end up with a large number of result items for each tag how can I paginate the results. I don't know how to do it because I've already used paginate: to create the archive page.

I'm looking for example.com/tutorial/{{tag}}/  example.com/tutorial/{{tag}}/1..2..3 etc

2. How could I make compound tag archives to return an archive page of 1 or more tags combined?

I'm aiming for example.com/tutorial/maths/difficult where 'maths' and 'difficult' are both separate tags

I guess I'm using this to replace what is traditionally a database query function. Pagination is a really exciting but quite confusing feature of eleventy.

**Comment by zachleat** [comment]
I believe this is the exact thing that was discussed in #332? An example exists over there

**Comment by zachleat** [comment]
Per our discussion on Twitter I’ve also opened #461 to discuss a better core feature for this use case.
