### ISSUE TITLE
Vulnerability with braces

### ISSUE THREAD

**Issue by bridgestew** [11ty/eleventy#428]
I get this warning when fiddling with npm packages for my 11ty based site. I wanted to share in case you hadn't seen it before. 

[screenshot](https://www.dropbox.com/s/amcrdkvao2vaayy/Screenshot%202019-02-23%2013.52.59.png?dl=0)

**Comment by alex-page** [comment]
This should be fixed when this PR gets merged in `browser-sync`:
https://github.com/BrowserSync/browser-sync/pull/1659

**Comment by zachleat** [comment]
Waiting on a new browser-sync version to fix this. For the record, because Eleventy only runs at build time, there shouldn’t be any exposure here.  https://www.npmjs.com/advisories/786

**Comment by zachleat** [comment]
Or https://github.com/BrowserSync/browser-sync/pull/1648 or https://github.com/BrowserSync/browser-sync/pull/1671

**Comment by Ryuno-Ki** [comment]
For the record, nunjucks and browser-snyc have an additional vuln in https://www.npmjs.com/advisories/534.

**Comment by kleinfreund** [comment]
looks like this is fixed in 2.26.4 (https://github.com/BrowserSync/browser-sync/releases).
