### ISSUE TITLE
Using permalinks in templates

### ISSUE THREAD

**Issue by woodscreative** [11ty/eleventy#431]
Hey great job on Eleventy! Is there a way to output the actual permalink in my template when using liquid filters in front matter or when permalink has not been defined?

```
---
permalink: posts/{{ title | slug }}/index.html
---
{{ permalink }}
```

Outputs:

```
posts/{{ title | slug }}/index.html
```

I need to pass the permalink to a Liquid include.

**Comment by zachleat** [comment]
Oh you want the current page URL? I think you want `page.url`: https://www.11ty.io/docs/data/#page-variable-contents%3A

**Comment by woodscreative** [comment]
Delicious. Ta.
