### ISSUE TITLE
Do you use prototypes?

### ISSUE THREAD

**Issue by octoxalis** [11ty/eleventy#433]
In my main **11ty** [site](https://www.chercheurd.art), I have a few different kinds of posts and to speed up creating new ones, I've created Markdown prototype files and JS data prototype files (because I use data files to inject content in my markdown posts).
I had also to create JS files to handle the creation of any new post using the prototype files, replacing place holders with the specific new content.
It's rather heavy (but fast, even checking if any previous markdown content with the same ID of my new post has not already been created, just to avoid to delete a previous one) and I'd like to know whether **11ty** users have some experience (from other static site generators providing a prototype mechanism) to share regarding their **11ty** content creation.

A sample of a JS file creating a new post is there: [`11ty_prototype.js`](https://github.com/octoxalis/11ty_workspace/blob/master/11ty_prototype.js);
The Markdown file with the new post content to be created is there: [`11ty_YYYY_MM_DD-post._md`](https://github.com/octoxalis/11ty_workspace/blob/master/11ty_YYYY_MM_DD-post._md);
and the JS file creating the JS data file and the Markdown content file is there: [`11ty_newpost.js`](https://github.com/octoxalis/11ty_workspace/blob/master/11ty_newpost.js).
This last file is put inside my **global data folder** and processed by **11ty** at the begining of the next build.

**Comment by zachleat** [comment]
Hmm, I’m having trouble following this example without looking at the real project source code. Is it possible to try to restate your question?

**Comment by octoxalis** [comment]
Hi Zach, does it help if you have a glance at the [source tree](https://github.com/octoxalis/11ty_workspace/blob/master/chercheurd.art%2011ty%20source%20tree.txt) of my site?

What I call a _prototype_ file (_archetype_ in **Hugo**) is created inserting new data in some requested "fields" of the `11ty_newpost.js` mentioned above (in my source tree it's the file named `new_post.js` inside the `tools` directory).

Each time I want to create a new post, I have to manually move `11ty_newpost.js` inside the `data/post` directory to be parsed at the next build; the placeholders data fields in the prototype file (`11ty_YYYY_MM_DD-post._md`) are therefore replaced  by the `newPost.createPost` function of`11ty_prototype.js` called at the bottom of `11ty_newpost.js`, using the new data contained in its argument `post_o` object (prototypes files are placed outside the source directory and do not appear in my  [source tree](https://github.com/octoxalis/11ty_workspace/blob/master/chercheurd.art%2011ty%20source%20tree.txt) ).

Clearly, I need three files to create a new post:
1. a **data file** with all new data used to create the new post (_Javascript_ `Object`).
2. a **prototype file** with placeholders (_Markdown_);
3. a **file to process** the prototype file (_Javascript_);

I wonder whether a better process could get the same result and whether 11ty users have a better solution.

**Comment by edwardhorsford** [comment]
I think this idea might be similar to the idea of a post generator / skeleton / blueprint?

It sounds like you want to run a command and that creates x files based on a template with a few things filled in?

**Comment by octoxalis** [comment]
@edwardhorsford : That's right. I use that to avoid mistakes with data I sometimes have to duplicate or to shorten common content creation or to dispatch the same data in different files.

**Comment by zachleat** [comment]
Ah, I don’t think we have any short term plans to put this into core, sorry!

I am reminded of this one from @philhawksworth though! https://github.com/philhawksworth/11up
