### ISSUE TITLE
Directory Data File gets copied to output

### ISSUE THREAD

**Issue by tcurdt** [11ty/eleventy#435]
I am providing some default values (a tag to create a collection) via a json file 

```
posts/
  posts.json
```

but the json file gets copied to the output.
Is that a bug or what am I missing?

**Comment by zachleat** [comment]
Are you using `--passthroughall` by chance?

**Comment by tcurdt** [comment]
Yes, I so. I didn't realize that applies even to those Directory Data Files.

**Comment by zachleat** [comment]
Yeah that feature is pretty blunt. I'd recommend using the other passthrough copy methods instead: https://www.11ty.io/docs/copy/

**Comment by tcurdt** [comment]
Much better. Thanks!
