### ISSUE TITLE
Is there a way to use custom input directory and include files from dependencies?

### ISSUE THREAD

**Issue by thejohnfreeman** [11ty/eleventy#441]
If I want to scope my files under an input directory, then I lose access to the `node_modules` directory, leaving me to copy all the dependency files I use (e.g. CSS) into my input directory. Is there a way I can use a custom input directory without losing access to `node_modules`?

**Comment by zachleat** [comment]
Hmm, if I’m understanding you right—manual pass-through copy is relative to your project root and not your input directory, so it should have access to `node_modules` https://www.11ty.io/docs/copy/#manual-passthrough-copy-(faster)
