### ISSUE TITLE
templateContent missing  in custom collections

### ISSUE THREAD

**Issue by remy** [11ty/eleventy#451]
Reading the docs, I thought I should be able to access the template content from my own custom collections, but the property is definitely missing (though everything else is present and correct).

Could I be missing something obvious?

**Comment by zachleat** [comment]
From inside your configuration file or in your templates? Should be available on the latter but is not available in the former.

**Comment by remy** [comment]
Ah, in the templates.

I'm trying to convert my own blog, but when in trying to dig into parsing
the post content (like for splitting on `<!--more-->`) but the property was
missing when I'm inside the template (or specifically the .pug file I'm
writing).

**Comment by zachleat** [comment]
Ah, hmm yeah that should work. Can you paste the example of the template that’s using it? (Or at least the collection loop?)

Or perhaps even better do you your blog migration progress in a branch on https://github.com/remy/remysharp.com/ ?

**Comment by zachleat** [comment]
Just FYI I wasn’t necessarily asking for a test case just a bit more info.

One thing you could also try is to npm install from the latest version on the `master` branch on github. The collection stuff was refactored quite a bit for the upcoming version 0.7.2 so this could fix the issue you were having.

**Comment by remy** [comment]
It's totally fine. I've got a branch in my blog that uses 11ty - it's just that the result is so riddled with errors it's hard to separate out where the issue is with 11ty and where the issue is with my old .jade templates (not having the locals it's used to). 

The branch is here: https://github.com/remy/remysharp.com/tree/feat/11ty - the collection logic [here](https://github.com/remy/remysharp.com/blob/feat/11ty/.eleventy.js#L24) and I was _trying_ to access `templateContent` [here](https://github.com/remy/remysharp.com/blob/feat/11ty/public/feed.xml.pug#L26) (though the value is empty at the moment).

I'm not sure how useful that is for replication - as there's so much cruft with my own blog and bits breaking due to the port from jade to pug and Harp.js to 11ty.

I've been working on my own bespoke generator (only intended for my own blog) and most of the work has been getting the layouts to render rather than actually transforming the markdown and doing it quickly (i.e. yes, my blog feels _very_ cobbled together!).

**Comment by Ryuno-Ki** [comment]
@remy You're in company here
> yes, my blog feels very cobbled together!
Mine feels like a mess at the moment, too.

**Comment by zachleat** [comment]
Ah hmm @remy I did get your blog checked out but I’m having a little bit of a time figuring out where to go. Maybe we can circle back on this one after 0.7.2 is released and if you’re still inclined you can retest then.

**Comment by remy** [comment]
Totally understand. That's why I was a little wary of filing it in the
first place - my templates are a bit of a wiry mess!!!

**Comment by zachleat** [comment]
@remy do you want to keep this one open?

**Comment by remy** [comment]
Sure, I'll take a run at it during my weekly twitch coding session this week 👍

**Comment by remy** [comment]
This works now. No idea what changed, but all good, can access `templateContent` no problemo.
