### ISSUE TITLE
HTML content being escaped

### ISSUE THREAD

**Issue by sensecall** [11ty/eleventy#454]
I'm really struggling to understand what I'm doing wrong here – any HTML content (inside tags) is being escaped so the tags are visible.

Please could someone give me a pointer as to where I'm going wrong?

**Comment by zachleat** [comment]
Is it this? https://www.11ty.io/docs/layouts/#prevent-double-escaping-in-layouts

**Comment by zachleat** [comment]
Do you have a snippet that shows what you're doing?

**Comment by sensecall** [comment]
> Do you have a snippet that shows what you're doing?

My template is a `.njk` file and I'm using `{{ content | safe }}` to show page content.

The page I'm trying to render is `index.njk` and at the top of that I'm including:
```
---
title: Title here
subtitle: Subtitle here
layout: layouts/layout.njk
---
```

to point to my template file.

**Comment by sensecall** [comment]
Ok, so I've fixed this – it was a mistake on my part (obviously!). Thanks anyway 👍

**Comment by zachleat** [comment]
Great—thanks for checking back in! Closing
