### ISSUE TITLE
Empty paragraphs above and below MarkdownIt custom renderer

### ISSUE THREAD

**Issue by alex-page** [11ty/eleventy#457]
Hey 👋,

I tried to make a custom renderer for an image in markdownIt. This is working great however I get empty paragraphs around the top and bottom of the custom rendered HTML.

I also tested rendering the MD to HTML with only my custom markdown and it doesn't have the empty paragraphs.

I then thought this might be a common pitfall due to whitespace. I removed all the whitespace and the issue was still occuring.

Here is my `.eleventy.js` file:
```js
const MarkdownIt = require("markdown-it");
const MinifyCss = require( 'clean-css' );
const MinifyJS = require( 'uglify-js' );
const Fs = require( 'fs' );


module.exports = ( eleventyConfig ) => {

	/**
	 * cssmin - Minify CSS filter
	 */
	eleventyConfig.addFilter( "cssmin", ( code ) => {
		const minified = new MinifyCss({}).minify( code ).styles;
		return minified;
	});

	/**
	 * jsmin - Minify JS filter
	 */
	eleventyConfig.addFilter( "jsmin", ( code ) => {
		const minified = MinifyJS.minify( code, {
			mangle: true,
			compress: true,
		});

		if( minified.error ) {
			console.log( "UglifyJS error: ", minified.error );
			return code;
		}

		return minified.code;
	});

	// Adjust default browserSync config
	eleventyConfig.setBrowserSyncConfig({
		open: 'local'
	});


	// Create an adjusted version of markdown it
	const MarkdownItRenderer = new MarkdownIt;
	const imageRenderer = MarkdownItRenderer.renderer.rules.image;

	// Change the renderer for images that are links to videos
	// https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md
	MarkdownItRenderer.renderer.rules.image = function (tokens, idx, options, env, self) {
		const token = tokens[idx];
		const aIndex = token.attrIndex('src');
		const link = token.attrs[aIndex][1];

		// If the link is to a youtube video
		if ( link.includes('youtube.com/watch?')) {

			// Get the video ID from the link
			let videoId = link.split('v=')[1];
			if( videoId.indexOf('&') != -1 ) {
				videoId = videoId.substring(0, ampersandPosition);
			}

			// Return an embedded video
			return `<div class="embed-responsive"><iframe src="https://www.youtube.com/embed/${ videoId }?rel=0?version=3&controls=0&showinfo=0" frameborder="0" allowfullscreen></iframe></div>`;
		}

		// Return the default
		return imageRenderer(tokens, idx, options, env, self);
	};

	const data = Fs.readFileSync( './src/talks/index.md', { encoding: 'utf-8' });
	console.log( data );
	const renderedData = MarkdownItRenderer.render( data );
	console.log( renderedData );

	eleventyConfig.setLibrary( "md", MarkdownItRenderer);

	// The configuration object ( optional )
	return {
		dir: {
			input: "src",
			includes: "_includes",
			output: "site"
		},
		templateFormats : ["njk", "md"],
		htmlTemplateEngine : false,
		markdownTemplateEngine: false,
	};
};
```

Here is the markdown I am testing `'./src/talks/index.md`:
```md
### Names and culture

![Alex talking at the Design System Meetup](https://youtube.com/watch?v=-xAKir02gto)

![Alex talking at the Design System Meetup](/assets/img/alex-page.jpg)

I gave a talk at Design System Meetup v4.0.0 about names and culture. I talked about how communication is hard and what we name things affects how well we communicate. 
```

The output in 11ty is:
```html
<h3>Names and culture</h3>
<p></p>
<div class="embed-responsive"><iframe src="https://www.youtube.com/embed/-xAKir02gto?rel=0?version=3&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen=""></iframe></div>
<p></p>
<p><img src="/assets/img/alex-page.jpg" alt="Alex talking at the Design System Meetup"></p>
```

The wanted output that renders correctly in the console ( rendering the markdown with `MarkdownIt.render` ):
```html
<h3>Names and culture</h3>
<p><div class="embed-responsive"><iframe src="https://www.youtube.com/embed/-xAKir02gto?rel=0?version=3&controls=0&showinfo=0" frameborder="0" allowfullscreen></iframe></div></p>
<p><img src="/assets/img/alex-page.jpg" alt="Alex talking at the Design System Meetup"></p>
```

**Comment by zachleat** [comment]
Interesting, hmm. What’s the `breaks` Markdown option set to? Can you explicitly set it to `false` a la https://www.11ty.io/docs/languages/markdown/#optional%3A-set-your-own-library-instance?

**Comment by alex-page** [comment]
Thanks for the reply, according to the [documentation](https://github.com/markdown-it/markdown-it#init-with-presets-and-options) it should be `breaks: false` by default. I tried playing around with those options and I am still getting the same result.

**Comment by zachleat** [comment]
After looking at the code and fixing, I’m really curious if this is related to #466. Do you think you can npm install to the Eleventy master branch on GitHub to test?

**Comment by alex-page** [comment]
Oh that is interesting, I will test it out now.

**Comment by zachleat** [comment]
Hmm, I’m having trouble reproducing this issue in both 0.9.0 and 0.10.0. Without a reproducible issue I can’t move forward here sorry! Can you link to your existing repo that exhibits this issue or create a reduced test case repo? Please reopen when you’ve done this. Again—sorry about this!

**Comment by alex-page** [comment]
@zachleat I made a test repo but it's resolved with the new version of 11ty.
 
Happy for you to remove the needs-test-case label.

**Comment by zachleat** [comment]
Great, thanks!

**Comment by anghelos** [comment]
I'm getting the same issue with a Nunjucks filter:
```
const MarkdownIt = require("markdown-it")({
  html: true,
  breaks: false
});

module.exports = function (eleventyConfig) {
  
}
```
Passing a string through it gives me: 
```
<p></p>
<p>My string</p>
<p></p>

```

**Comment by pdehaan** [comment]
@anghelos What about if you [trim](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim) the content before passing it to `MarkdownIt.render()`?

```js
return MarkdownIt.render(content.trim());
```

**Comment by anghelos** [comment]
It was my bad!
I was calling it as:
```html
<p>{{ content | markdown | safe }}</p>
```
Removing the paragraph tags surrounding this fixed it.

**Comment by macbruker** [comment]
I'm also overriding the **markdown-it** image renderer and adding a caption to my images. When I do that, empty paragraph elements are added above and below the image markup.

Example: `![alt-text](image.jpg "Image caption")`

<img width="397" alt="Screenshot of source code from the test case linked below, showing empty paragraph tags above and below the figure element." src="https://github.com/11ty/eleventy/assets/1032194/2bb0baad-6f79-47a0-9f1a-eb9d4959fa89">

This problem is something I have been struggling with for a while and finally decided to create a test case. In doing that, I discovered that the issue seem to only occur when I return some markup with the `Image.generateHTML` function.

Test Case: https://github.com/macbruker/test-case-empty-paragraphs

Most of the code is from this blog post, explaining how to use Eleventy Image in markdown. https://tomichen.com/blog/posts/20220416-responsive-images-in-markdown-with-eleventy-image/ 

I didn't know whether to open a new issue or commenting on this one, but decided to add a comment here for now.

**Comment by arpit-agr** [comment]
> I'm also overriding the **markdown-it** image renderer and adding a caption to my images. When I do that, empty paragraph elements are added above and below the image markup.
> 
> Example: `![alt-text](image.jpg "Image caption")`
> 
> <img alt="Screenshot of source code from the test case linked below, showing empty paragraph tags above and below the figure element." width="397" src="https://private-user-images.githubusercontent.com/1032194/292515288-2bb0baad-6f79-47a0-9f1a-eb9d4959fa89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NDczOTksIm5iZiI6MTcwNTc0NzA5OSwicGF0aCI6Ii8xMDMyMTk0LzI5MjUxNTI4OC0yYmIwYmFhZC02Zjc5LTQ3YTAtOWYxYS1lYjlkNDk1OWZhODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjBUMTAzODE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTg2YjIyNWQ4MDRkYTFkMTM5MWZhYjFjZTAwY2M4ZWIyMTU5MjI0MjZjNWUzZmJmM2UyYjQyMjk2MTAxZThlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aiXbi4AKxPkHYKH86kwgFQBMly6JoQ5-K4My7yOCQGU">
> This problem is something I have been struggling with for a while and finally decided to create a test case. In doing that, I discovered that the issue seem to only occur when I return some markup with the `Image.generateHTML` function.
> 
> Test Case: https://github.com/macbruker/test-case-empty-paragraphs
> 
> Most of the code is from this blog post, explaining how to use Eleventy Image in markdown. https://tomichen.com/blog/posts/20220416-responsive-images-in-markdown-with-eleventy-image/
> 
> I didn't know whether to open a new issue or commenting on this one, but decided to add a comment here for now.

I'm facing the same issue. For now, I've used the following CSS workaround to hide those empty elements:

```css
p:empty {
  display: none;
}
```

It's not an ideal solution, but it's a temporary fix.

**Comment by WilNichols** [comment]
I have this issue extensively whenever I use html or njk in my markdown. It's _sometimes_ fixed by removing all whitespace from the njk, but that's far from ideal. :/

**Comment by zachleat** [comment]
@WilNichols Make sure you use `{%- ` to start your Nunjucks tags when nested in Markdown files!

docs: https://mozilla.github.io/nunjucks/templating.html#whitespace-control
