### ISSUE TITLE
Using JS Classes. Entire file rendered on page as a string?

### ISSUE THREAD

**Issue by corderophi678** [11ty/eleventy#458]
I've got `TestClass.js`

```js
class Test {
  render() {
    return `<p>Potato</p>`;
  }
}

module.exports = Test;
```
And trying to use it in `test-page.njk`
```nunjucks
---
layout: base
---
{%- include 'elements/TestClass.js' -%}
```

And this is a screencap of `localhost:8080/test-page`
![template_rendering_what](https://user-images.githubusercontent.com/26899349/54760481-8ea07900-4bc6-11e9-900d-986cd39f02d9.png)

Anybody have any idea why things are rendering like this?

**Comment by kleinfreund** [comment]
I believe you’re following https://www.11ty.io/docs/languages/javascript/?

JavaScript templates have the file extension `.11ty.js`, not just `.js`.

**Comment by corderophi678** [comment]
Thanks, @kleinfreund. Unfortunately, that didn't fix it. I'm feeling pretty confident that I *must* be doing something wrong, but I can't for the life of me figure out what it is.

**Comment by zachleat** [comment]
Unfortunately you can’t mix template engines like this. If you use a Nunjucks include, it expects a Nunjucks include file to be included, not an Eleventy JavaScript template.

**Comment by zachleat** [comment]
Keep an eye on https://github.com/11ty/eleventy/issues/189#issuecomment-411544737 which should add this feature to Eleventy!

**Comment by zachleat** [comment]
Keep in mind that if you use `TestClass.js` and `test-page.11ty.js` you could do:

```
const TestClass = require("./path/to/TestClass.js");
class TestPage {
  render() {
    let test = new TestClass();
    return test.render();
  }
}

module.exports = TestPage;
```
