### ISSUE TITLE
Shortcode does not render HTML

### ISSUE THREAD

**Issue by mathiasha** [11ty/eleventy#460]
In my eleventy config I have this shortcode:

    module.exports = function(eleventyConfig) {
      eleventyConfig.addShortcode("testCode", function(name) {
        return \`<div class="some-class">${name}</div>\`;
      });
    }

In my handlebars file I have this
`{{ testCode 'Mathias' }}`

But the shortcode is being rendered as a string. So in the browser it looks like this

`<div class="some-class">Mathias</div>`

Am I doing something wrong?

**Comment by corderophi678** [comment]
It looks like you might be escaping the backticks in your return statement? Might that be the cause?

**Comment by zachleat** [comment]
This is a good question! Handlebars escapes shortcodes by default so you want the triple-stash for unescaped output `{{{ testCode 'Mathias' }}}`.

**Comment by zachleat** [comment]
I will update the documention for shortcodes to make this clearer.

**Comment by zachleat** [comment]
Both https://www.11ty.io/docs/languages/handlebars/ and https://www.11ty.io/docs/shortcodes/ have been updated with this information.

Thanks for filing this! Very helpful!
