### ISSUE TITLE
Core pagination support for double layered pagination

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#461]
Related issue #332, something with a little bit more DX might be warranted since this has come up a few times now.

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by distinctperspective** [comment]
I converted too. @zachleat  I can help you with that.

**Comment by jeromecoupe** [comment]
My 2 cents on this double layered pagination things

**Comment by jeromecoupe** [comment]
Yup, using the same king of approach, albeit using custom taxonomies instead of tags:

https://github.com/jeromecoupe/11ty-paginate-taxonomies

**Comment by MWDelaney** [comment]
Expanding the above into a working example...

After much heartache, and many compromises, I have paginated dynamic tag pages for blogging working.

I made a pull request against ZeroPoint demonstrating it:
https://github.com/MWDelaney/ZeroPoint/pull/31

I'm sure this could be simplified, and pagination more directly modified, but it works!

**Comment by dave-kennedy** [comment]
I'm confused by the status of this issue. It's pinned to the top of the issues list, so I would expect a canonical answer here. @zachleat can you please clarify? Is the recommended solution [this one](https://github.com/11ty/eleventy/issues/332#issuecomment-445236776)? If so, it might make more sense to pin that issue instead.
