### ISSUE TITLE
How to achieve pagination from JS Class Templ?

### ISSUE THREAD

**Issue by corderophi678** [11ty/eleventy#462]
*Disclaimer: I probably don't really know how to talk about these things, so bear with me.*

I'm working with a global data set (`./_data/test_data.json`, an array of objects) and using JS class templates. My template looks like this:
```js
const testData = require("./_data/testData.json");

class TestPage {
  data() {
    return {
      layout: "base",
      pagination: {
        data: testData,
        size: 1
      }
    };
  }
  render(data) {
    return `{...}`;
  }
}

module.exports = TestPage;
```

I get the following error:
```
Problem writing Eleventy templates: (more in DEBUG output)
> Could not resolve pagination key in template data: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object] (Error):
    Error: Could not resolve pagination key in template data: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
```

Is this possible? Or am missing something?

Thanks for your help :yellow_heart:

**Comment by zachleat** [comment]
Oh dang yes it does seem confusing in this light.

Not to minimize the way you did it (which completely makes sense to me) but pagination was originally born as a YAML front matter thing. Pagination data, specifically, expects a string that points to the data in your front matter, not the data itself (although that would be neat too!).

The following should work:

```
const testData = require("./_data/testData.json");

class TestPage {
  data() {
    return {
      layout: "base",
      testData: testData,
      pagination: {
        data: "testData",
        size: 1
      }
    };
  }
  render(data) {
    return `{...}`;
  }
}

module.exports = TestPage;
```

**Comment by zachleat** [comment]
I think the way you did it would be cool so I filed it as an enhancement request at #463 if you want to follow along there.

**Comment by corderophi678** [comment]
Beautiful. That worked a treat. Thanks very much, Zach.

**Comment by zachleat** [comment]
Great!
