### ISSUE TITLE
setLibrary documentation

### ISSUE THREAD

**Issue by LandonSchropp** [11ty/eleventy#464]
I prefer the `marked` library to `markdown-it` and would like to use that with Eleventy instead. I noticed in the documentation there's a `setLibrary` method. In reading through the [source code](https://github.com/11ty/eleventy/blob/e59bcfcdfddae96afaa4efc6d4b7f4e801b6d0ab/src/Engines/Markdown.js), it looks like the only thing I need to provide for a library object is an object with a `render` method.

```
import marked from 'marked';

// Creates an instance of the markdown library.
let markdown = {
  render(source) {
    return marked(source);
  }
};

eleventyConfig.setLibrary("md", markdown);
```

Is this correct? Is this code likely to break in the future? Is there any documentation on the `setLibrary` function that I missed?

**Comment by zachleat** [comment]
Oh—hmm. I don’t think this will work—no. Even if you get it to work short term, it will almost certainly break unpredictably in the future. We make assumptions about the library options and methods available there.

You’ll have to wait for our current top feature request #117 to do this—sorry!

**Comment by Muhammed-Rahif** [comment]
For anyone wondering: 
```js
import { marked } from "marked";

export default function (eleventyConfig) {
	eleventyConfig.addExtension("md", {
		compile: function (inputContent, inputPath) {
			let html = marked.parse(inputContent);

			return function (data) {
				// Example: use `marked` only if useMarked is set in the Data Cascade
				if (data.useMarked) {
					return html;
				}

				// You can also access the default `markdown-it` renderer here:
				return this.defaultRenderer(data);
			};
		},
	});
};
```
_From: https://www.11ty.dev/docs/languages/custom/#overriding-or-extending-an-existing-template-language_
