### ISSUE TITLE
Automatically detect front matter format

### ISSUE THREAD

**Issue by reubenlillie** [11ty/eleventy#465]
The gray-matter package calls for a `---json` flag to indicate JSON syntax in front matter. Or else one would need to create an option like: `matter(string, { language: 'json' })`. Both are not ideal.

In order for 11ty to maintain a framework agnostic position, it should recognize front matter based on native syntax alone (something that Hugo got right in this case, at least in terms of recognizing JSON from `{`). Since Javascript is also viable for front matter in 11ty, there ought to be a way to detect the format behind the scenes--not in the front matter itself.

**Comment by zachleat** [comment]
We _could_ opt-in to JavaScript front matter if the first character is `{`, which should handle both JavaScript and JSON formats right?

**Comment by reubenlillie** [comment]
Perhaps. Do you have suggestions for testing? I'm going out on a limb here, but wouldn't it also be a good idea to validate the front matter either way?

**Comment by zachleat** [comment]
Testing in what regard? This would be an enhancement to Eleventy and require additional code changes to core to facilitate this (and would go through the enhancement queue).

Also what do you mean by validating the front matter?

**Comment by reubenlillie** [comment]
Ok. I wasn't sure what you meant by _could_. Now I get it.

As far as validating front matter, I mean both (a) detecting whether the code block is JSON or JavaScript and (b) determining whether said code block is valid JSON or JavaScript accordingly. Is that clearer?

**Comment by Ryuno-Ki** [comment]
I'd do it like this:

Check, whether frontmatter starts with `{`
- true:
  1. `JSON.parse(frontmatter)` throws an error: JavaScript frontmatter
  1. `JSON.parse(frontmatter)` succeeds: JSON frontmatter
- false: YAML frontmatter

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
Given that #410 is shipping with the next version, I think the ship might have sailed on this request—sorry. To me this is asking a little too much for the flexibility I’d like to offer in Eleventy. It’s akin to saying “Can you auto detect the format of a template without using an explicit file extension?”

It’s likely more trouble than it’s worth. Declaring the syntax of your front matter (for non-YAML front matter types) is just the cost of doing business here I think.

Can you explain more about what you mean by “to maintain a framework agnostic position, it should recognize front matter based on native syntax alone”? I’m not sure I’m following there.

Moving forward, we’re offering “unlimited” front matter types (this in my mind is the language agnostic position) and as such you’ll be required to declare which one you’re using.

Gonna remove this from the enhancement backlog for now. Please feel free to leave more thoughts here, I’m open to listening where I’ve gotten this wrong 👍

**Comment by reubenlillie** [comment]
Ok. I was thinking more for migration purposes rather than simply the language format itself. For example, Hugo recognizes JSON by `{` rather instead of `---`  for yaml or `+++` for TOML. I think it's fine for Eleventy to expand to other formats by requiring language declaration. But I thought ease of content migration from existing SSGs was a major goal of the project.

**Comment by Ryuno-Ki** [comment]
Migrating from other SSG should be done outside of Eleventy, in my opinion.

We have another issue for that: #488
