### ISSUE TITLE
Data and content directories processing order

### ISSUE THREAD

**Issue by octoxalis** [11ty/eleventy#468]
In which order are data and content directories processed?

AFAIK global data files are processed before content markdown files. But  is there a way to know which file **11ty** will process first and which one last? I'd like to be able to create a file when the first content file is processed and to close this file when the last content file is processed . Are there hooks provided to do that?

**Comment by Ryuno-Ki** [comment]
Maybe related to #406

**Comment by octoxalis** [comment]
Exactly what I need.
Thanks for the reference.

**Comment by Ryuno-Ki** [comment]
Can we close this one then?
(Don't forget to upvote the other issue!)

**Comment by octoxalis** [comment]
OK

**Comment by zachleat** [comment]
Thanks @Ryuno-Ki! Closing in lieu of #406.
