### ISSUE TITLE
Problem getting localConfig file

### ISSUE THREAD

**Issue by DirtyF** [11ty/eleventy#47]
Hi Zach,

Just trying to follow your Level 1 tutorial and getting some trouble with locale config.

Given my `locale` is:

```
LANG="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_CTYPE="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_ALL=
```

When I run `DEBUG=Eleventy* eleventy`

Then I get the following error message
```  
Eleventy:TemplateConfig Problem getting localConfig file, { Error: Cannot find module '/Users/frank/11y-giffleball/.eleventy.js' at Function.Module._resolveFilename (module.js:555:15) at Function.Module._load (module.js:482:25) at Module.require (module.js:604:17) at require (internal/module.js:11:18) at TemplateConfig.mergeConfig (/usr/local/lib/node_modules/@11ty/eleventy/src/TemplateConfig.js:44:21) at new TemplateConfig (/usr/local/lib/node_modules/@11ty/eleventy/src/TemplateConfig.js:23:24) at Object.<anonymous> (/usr/local/lib/node_modules/@11ty/eleventy/src/Config.js:5:18) at Module._compile (module.js:660:30) at Object.Module._extensions..js (module.js:671:10) at Module.load (module.js:573:32) code: 'MODULE_NOT_FOUND' } +1ms
```

And generated `_site/index.html` does not interprete liquid syntax:

```
<!doctype html>
<html lang="en">
 <head>
  <meta charset="utf-8">
  <title></title>
 </head>
 <body>
  <h1></h1>
  <ul>

  </ul>
 </body>
</html>
```

**Comment by zachleat** [comment]
@DirtyF Ah, yes—that should be a warning—not an error. The `.eleventy.js` config file is purely optional!

This is good feedback, what do you expect should show in `index.html`?

What does your `index.html` source file look like?

**Comment by DirtyF** [comment]
> What does your index.html source file look like?

It's the one from your demo:
https://github.com/11ty/giffleball/blob/master/index.html

**Comment by DirtyF** [comment]
adding `eleventy.js` file avoid the error message but the liquid template isn't process either.

**Comment by zachleat** [comment]
Can you attach your index.html source file here so I can take a look?

**Comment by DirtyF** [comment]
Nevermind, it compiles fine, I just stumbled into the common html pitfalls :)

**Comment by zachleat** [comment]
Oh, excellent. Thanks!

**Comment by zachleat** [comment]
One more note for posterity, I did open #48 but it has no effect on the functional output of eleventy. The config file is purely optional and it continues on as normal if the file is not found.

Again, thanks! 👍
