### ISSUE TITLE
Open Collective Page

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#472]
It was requested (by an unnamed party) that I create a page so that they could support the project. I’d like to offer y’all a preview of that page just to let you know that it exists and to gather feedback about Open Collective in general and Eleventy being an Open Collective project.

Any and all feedback is welcome. If you’d like to discuss privately, please DM me on Twitter.

Thank you!

https://opencollective.com/11ty

**Comment by Ryuno-Ki** [comment]
Hm, why Open Collective?
I mean, look at [Pepper & Carrot](https://www.peppercarrot.com/en/static2/philosophy). He lists several alternatives:
* [Patreon](https://www.patreon.com/join/davidrevoy?)
* [PayPal](https://www.paypal.me/davidrevoy)
* [Tipeee](https://en.tipeee.com/pepper-carrot)
* [Liberapay](https://liberapay.com/davidrevoy/)
* [G1](https://g1.duniter.fr/#/app/wot/4nosBEwT8xQfMY11sq32AnZF1XcoqzG9tArXJq9mu8Wc/DavidRevoy)

(Note, that some of those sites are focussing on creatives mainly).

**Comment by kleinfreund** [comment]
@Ryuno-Ki That begs the question “why not Open Collective”?

**Comment by Ryuno-Ki** [comment]
I can tell a bit of a story, when my distro [created a Patreon page](https://www.patreon.com/sabayon) on of the first questions was, whether they could not use Liberapay instead. [So they did](https://liberapay.com/SabayonLinux).

My personal criteria: I want to donate via wire transfer. In Euros. If a page does not offer this, I'm out.
(I'm aware, that many US American would go crazy with this standing!)

Other reasons might be Terms and Services (for those fraction of us, who read them) or the donating behaviour (do I have to charge it regularly? Can I split the donation? Can I influence the cadence? etc)

**Comment by zachleat** [comment]
That’s fair feedback—thanks @Ryuno-Ki!

We chose Open Collective for the simple reason that it’s popular with some existing popular Open Source software projects. Though I keep getting GraphQL errors on admin screens when I’m using it for some reason 😱

**Comment by Ryuno-Ki** [comment]
Fair enough :-)

**Comment by zachleat** [comment]
I’m going to close this for now but for future visitors if you stumble upon it later feel free to comment!
