### ISSUE TITLE
how to serve images?

### ISSUE THREAD

**Issue by dcsan** [11ty/eleventy#482]
maybe something is missing from the docs, or maybe I'm stupid but I can't see how to get images to work.

I setup a simple site with an `/img` directory.
Images don't appear when serving the site or get copied to `_site`

searched for "images" on https://www.11ty.io/docs but can't find much. [images](https://cn.bing.com/search?q=site%3Ahttps%3A%2F%2Fwww.11ty.io%2Fdocs+images&PC=U316&FORM=CHROMN)

I _did_ find a couple of closed issues and so I tried the `passThrough` config:

https://www.11ty.io/docs/copy/

I tried both as templateFormats and passThrough files, neither works:

file : `.eleventy.js`

```js
module.exports = function(eleventyConfig) {
  // Copy the `img/` directory
  eleventyConfig.addPassthroughCopy("img");

  return {
    passthroughFileCopy: true
  };
};

```

However it doesn't seem to actual copy the `/img` directory.
build output (naming the config to make sure it is finding it)

```
eleventy --config=.eleventy.js
Writing _site/README/index.html from ./README.md.
Processed 1 file in 0.18 seconds
```

The only thing I found to work is to put the images into `_site` directly.
Is this the recommended process? It seems if there was a `build --clean` then everything would get wiped out. I would also prefer to `.gitignore` the file site output.

It seems adding images to a site is the first thing people would do, so it would be nice if this was a little easier or at least clearer.

**Comment by dcsan** [comment]
```
eleventy --version
0.8.1
```

**Comment by dcsan** [comment]
https://github.com/11ty/eleventy/issues/379
https://github.com/11ty/eleventy/issues/178#issuecomment-406687951
so it should work as above... hmm.

**Comment by dcsan** [comment]
update: works. somehow my `.eleventy.js` managed to get an invisible character at the end of the filename...

**Comment by dcsan** [comment]
however it might still be worth making this more obvious so new users don't have to hunt down pass through just to serve a static image.

**Comment by Maarius** [comment]
I'd definitely support the suggestion by @dcsan. There should be a default `media` or `images` directory or it should be more obvious from the docs.

**Comment by RichardJECooke** [comment]
Sorry to bother but could someone please help?  I've done the entire Eleventy walkthrough (https://rphunt.github.io/eleventy-walkthrough/shortcodes.html) and tried searching in the docs, but I can't see how I'm supposed to put an image in my page, or even where to put stuff like a PDF or mp3, so I can link to it. Thank you!

**Comment by pdehaan** [comment]
@RichardJECooke I got this working. Here's my directory layout and files:

```sh
tree . -aI node_modules
.
├── .eleventy.js
├── assets/
│   └── img/
│       └── image.png
├── package-lock.json
├── package.json
└── src/
    └── index.njk

3 directories, 5 files
```

```js
// .eleventy.js
module.exports = function (eleventyConfig) {
  eleventyConfig.addPassthroughCopy("assets");

  return {
    dir: {
      input: "src",
      output: "www",
    }
  };
};
```

```njk
---
# src/index.njk
title: Test
---

<h1>{{ title }}</h1>

<img src="/assets/img/image.png" width="50" height="50" />
<img src="{{ '/assets/img/image.png' | url }}" width="50" height="50" />
```

**Comment by brachkow** [comment]
Same issue there — I didn't manage to find how to add an image to my page (and gave up using 11ty again)

**Comment by gourdcaptain** [comment]
This is still absolutely baffling to new users, complete with the eleventy-image plugin having all sorts of unexplained and hard to work around behavior like making animated GIFs not animated.

**Comment by rommelnunez** [comment]
has anyone figured out how to keep gifs animated?

**Comment by javiermartinez27** [comment]
@rommelnunez the [docs](https://www.11ty.dev/docs/plugins/image/#output-animated-gif-or-webp) Now mention it. Though it has a bug (which is caused by sharp, as mentioned [here](https://github.com/lovell/sharp/issues/3610)) that makes them way larger in height than they should be.

I made a workaround by using `image-size` and forcing the img tag to use the height it gives me

**Comment by autonomousapps** [comment]
I'm sort of losing my mind on this. I've read through a lot of the docs as well as several related issues, but the images I have that are _generated as part of the build process_ into the `img/` dir aren't getting copied to `_site/img/`. Can anyone take a look? https://github.com/11ty/eleventy/issues/4204
