### ISSUE TITLE
Possible dynamic permalinks bug in 0.8+

### ISSUE THREAD

**Issue by robdodson** [11ty/eleventy#484]
Given the following project structure:

```
en/
  en.11tydata.js
  posts/
    foo/
      index.njk
```

```js
// en.11tydata.js

module.exports = {
  language: 'en',
};
```

```
// foo/index.njk

---
layout: post
---
```

```
// _includes/post.njk

---
permalink: /{{language}}/{{page.fileSlug}}/index.html
---
```

The directory data file should inform the permalink in the layout.

Expected behavior:
```
output/en/foo
```

Actual behavior:
```
output/foo
```

This works as expected in `0.7.1` but seems to break in all versions of `0.8.*`.

**Comment by zachleat** [comment]
Hmm… this is surprising to me. The data aggregation code didn’t really change in 0.8.0 and we have tests around inheriting data from layouts.

Also given your repro steps, it seems to work fine:

<img width="664" alt="image" src="https://user-images.githubusercontent.com/39355/55849412-19193000-5b16-11e9-8011-a596fc586eb8.png">

Does the sample project I created work for you? [eleventy-484.zip](https://github.com/11ty/eleventy/files/3061830/eleventy-484.zip)

What environment are you running in?

**Comment by robdodson** [comment]
The zip you sent over works fine, so it must be something in the way my project is setup. I can consistently reproduce it by toggling versions and cleaning out `node_modules`.

If you grab the [v1 branch of our repo](https://github.com/GoogleChrome/web.dev/tree/v1) you might be able to reproduce it. With 0.7.1 installed, folders like `accessible` and `fast` do not appear outside of `en`. When I switch to 0.8.1, they do.

Apologies in advice for the messiness of the project. It's currently midway through migrating from our hand written build scripts over to eleventy. If you take a look all of the relevant bits are in the `src` dir.

**Comment by zachleat** [comment]
I was able to reproduce this, thanks! More info pending!

**Comment by zachleat** [comment]
This was a little bit of a weird one—our refactored logic to find directory names was subtly incorrect! I’ve added a test for your specific case.

The fix for is in 0.8.3.

cc @kleinfreund please review the commit and test (thanks!) https://github.com/11ty/eleventy/commit/f5f5c618920982d52497775740d75cc02d84338c

**Comment by kleinfreund** [comment]
@zachleat I see. Sorry about that. However, I’m afraid both versions allow for another subtle bug. Your initial version (before the refactoring PR) was more correct.

```js
TemplatePath.getAllDirs("src/_site/src");
//> [ "src/_site/src", "src/_site", "src" ]           // first, yours, correct
//> [ "src/", "src/_site", "src" ]                    // second (current one), mine, incorrect
//> [ "src/_site/src", "src/_site", "src/_site/src" ] // third (this one), yours, incorrect
```

First, this should be test case. I’m looking into it and submitting a fix.

**Comment by robdodson** [comment]
Thank y'all for looking into it, I really appreciate it :)
