### ISSUE TITLE
Markdown Image Tag Styling

### ISSUE THREAD

**Issue by ng-chicago** [11ty/eleventy#490]
Question
I'm moving a Markdown Jekyll site to Eleventy.
For some image tags I sometimes have style for just that image.
e.g.
![screenshot]({{ "Image.png" | absolute_url }}){:height="400 px"}

But that style is not working in Eleventy as it does in Jekyll.
It just prints the style after the image.

I have tried many different variations.
**Any suggestions on how to add style to an image in Eleventy?**

**Comment by zachleat** [comment]
I'm guessing you want to add this markdown plugin: https://www.npmjs.com/package/markdown-it-attrs

https://www.11ty.io/docs/languages/markdown/#add-your-own-plugins

**Comment by ng-chicago** [comment]
Thanks!

**Comment by zachleat** [comment]
You're welcome!
