### ISSUE TITLE
Support globs in addPassthroughCopy

### ISSUE THREAD

**Issue by jevets** [11ty/eleventy#493]
I've come across a use-case where supporting globs in `addPassthroughCopy` would be helpful.

Maybe there's another way to do this, but it seems like something this could be useful:

`config.addPassthroughCopy('src/posts/*/assets')`

For context, imagine this structure:

```
posts/
  index.njk
  hello-world/
    index.md
    assets/
      image-1.png
      image-2.png
  goodbye-world/
    index.md
    assets/
      image-1.jpg
      some-custom-styles-for-the-post.css
```

Where each `index.md` represents the post, and each post "owns" its own assets.

When compiled, the output would mirror the structure:

```
posts/index.html
posts/hello-world/index.html
posts/hello-world/assets/image-1.png
posts/hello-world/assets/image-2.png
posts/goodbye-world/index.html
posts/goodbye-world/assets/image-1.jpg
posts/goodbye-world/assets/some-custom-styles-for-the-post.css
```

Currently it's necessary to pass through a separate images folder, thereby detaching a post from its assets. I know I could add these files' extensions (`.png`, `.css`) as **`templateFormat`s**, but that feels wrong (unless I could limit the copying to the `posts` directory), and the effects could unexpectedly cascade into other sections of the site. 
(Maybe there's already a nice way of handling this that doesn't feel gross.)

This could also be helpful when migrating to or from eleventy, especially from an existing slew of posts organized in this fashion.

Thoughts?

**Comment by kleinfreund** [comment]
That sounds quite like what I thought about in https://github.com/11ty/eleventy/issues/379#issuecomment-453820324.

**Comment by jevets** [comment]
@kleinfreund I like that, too, especially if configurable in multiple places, like data files (as you mentioned). (Sorry I didn't find [that issue](https://github.com/11ty/eleventy/issues/379) when searching, before opening this one)

Adding as `templateFormats` would feel better if they could be assigned and scoped to a directory maybe via a data file, which would restrict the copying to that directory (and its children). e.g.

```
# posts/posts.json
{
  templateFormats: ['jpg', 'png', 'css', 'gif', 'etc']
}
```

**Comment by jevets** [comment]
Of course, something like [my comment in this issue](https://github.com/11ty/eleventy/issues/214#issuecomment-420661116) would take care of this just the same. (Maybe I've faced this before... Closing)
