### ISSUE TITLE
Migrating to Jekyll: Shopify includes syntax to LiquidJS syntax

### ISSUE THREAD

**Issue by benbrignell** [11ty/eleventy#496]
I'm in the process of migrating my site from Jekyll. The syntax between Shopify liquid includes and LiquidJS is different. 

I've 100s of includes on posts going back to 1997 throughout my site which use multiple values.  

### For example:
How I include images within posts:
```
{% include post-image.html image="thinking.jpg" alt="What was I thinking?" caption="What was I thinking?" class="pull-right" %}

```
I noticed @paulrobertlloyd's [article about migrating from jeykyll](https://24ways.org/2018/turn-jekyll-up-to-eleventy/) points towards [passing options to LiquidJS](https://www.11ty.io/docs/languages/liquid/) but I'm not sure if there's scope to help with this (and frankly I don't quite understand it)*.

### I'd appreciate help or pointers
* Can I configure LiquidJS to work with the old syntax? (It doesn't look like it but it's work asking)
* Else; how can I update all the instances where I use includes to use LiquidJS syntax?

*I'm not a developer so please feel free to explain in simple terms or point out if I am being stupid.

**Comment by paulrobertlloyd** [comment]
Hi @benbrignell. I believe the `dynamicPartials` option for LiquidJS relates only to whether you wish to use unquoted include names. Given you would also need to update the rest of your syntax, I’d recommend using quotes, as that is the default and more explicit method.

So, for the above to work with 11ty, you would need to change how you write your parameters, as such:

```
{% include "post-image", image: "thinking.jpg", alt: "What was I thinking?", caption: "What was I thinking?", class: "pull-right" %}
```

In answer to your two questions:
* No, I don’t believe there is a way of having the old syntax work — though this might make for a nice plugin. It’s also worth pointing out that there is no official Liquid implementation for the `include` tag. There is [the syntax Jekyll uses](https://jekyllrb.com/docs/includes/), and then there is [the syntax Shopify uses](https://help.shopify.com/en/themes/liquid/tags/theme-tags#include). LiquidJS opted to use the Shopify syntax (the correct decision IMHO) which sadly creates issues when moving from Jekyll to 11ty.
* As to updating `=` to `:` and adding quotes around the name of the included file, I’m not gunna lie… I did *a lot* of find and replacing! Sometimes a simple yet highly manual process work best. Unless you want to write a regex… but [now you have two problems](https://blog.codinghorror.com/regular-expressions-now-you-have-two-problems/).

Additional note. The [LiquidJS documentation](https://github.com/harttle/liquidjs#include-partials) suggests each parameter needs to be separated by a comma, but in practice I found that this is not the case; leaving out the commas makes no difference.

**Comment by zachleat** [comment]
A side note (and really I am so sorry for even putting this in here), I believe there probably is a way forward here but it isn’t a good one.

For the LiquidJS shortcode implementation, I wrote a custom argument lexer (to work around issue #347). You can see all of the tests in the test suite prefixed with `Issue 347:` https://github.com/11ty/eleventy/blob/master/test/TemplateRenderLiquidTest.js#L438

So, technically someone could likely write a custom LiquidJS include tag named something like `bensCustomInclude` to do this (so you’d have to find and replace `{% include` with `{% bensCustomInclude` instead of a more error prone method).

Code for this is here: https://github.com/11ty/eleventy/blob/master/src/Engines/Liquid.js#L127 (the magic is in `parseArguments`: https://github.com/11ty/eleventy/blob/master/src/Engines/Liquid.js#L99)

**Comment by benbrignell** [comment]
Thanks for these @paulrobertlloyd @zachleat - plenty to think about. I'm stuck between a rock and a hard place with tonnes of unpublished content and sources that needs eleventy to make sensible with tags but I don't have the time (or certainty about which way to do it) to migrate. 

I'm leaning towards writing a custom LiquidJS include tag as a sort of "hope this goes away" middle-ground… but I think it'd be best to see how things develop as I'm sure this will be a common problem for others. 

As a side-effect of all this doggy paddling and breaking/fixing a few things my Jekyll/dart builds are now considerably much faster so I think I'll stay put for now. I'll revisit this in a few weeks when the overall state of my site is in better shape and working how I want. Then I'll think about migrating and how I'll handle includes.

**Comment by zachleat** [comment]
Thanks! Feel free to reopen this later 👍

**Comment by zachleat** [comment]
Filed #545 which you may want to upvote!
