### ISSUE TITLE
Extra slashes in URLs when upgrading from v0.7.1 to v0.8.2

### ISSUE THREAD

**Issue by ckuehl** [11ty/eleventy#497]
I use the following to generate a sitemap:

```
---
permalink: /sitemap.xml
excludeFromSitemap: true
---
<?xml version="1.0" encoding="utf-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
{%- for page in collections.sitemap %}
  {% set absoluteUrl %}{{ page.url | url | absoluteUrl(metadata.url) }}{% endset %}
  <url>
    <loc>{{ absoluteUrl }}</loc>
    <lastmod>{{ page.date | htmlDateString }}</lastmod>
    <priority>{{ page.data.priority }}</priority>
  </url>
{%- endfor %}
</urlset>
```

After upgrading from v0.7.1 to v0.8.2 I noticed that our URLs in our sitemap switched from:

`<loc>https://www.domain.com/pricing/</loc>`

to:

`<loc>https://www.domain.com//pricing/</loc>`

I've reviewed the configuration and can't find anything that's causing this. I also tried using collections.all versus my custom sitemap collection (which handles exclusions and a few other items, but saw the same result.

**Comment by AndrewAsquith** [comment]
I assume you're on Windows?

If so, you can correct this by making this change:
https://github.com/11ty/eleventy/pull/486/commits/19501f5337bc65370119146ecd9dd3bb21181b49

or wait for 0.8.3

**Comment by ckuehl** [comment]
I am using Windows - thanks for the link to the fix!
