### ISSUE TITLE
Backslashed permalinks and links to root directory since 0.8.0

### ISSUE THREAD

**Issue by ssgstarter** [11ty/eleventy#500]
11ty is gorgeous! 
I am making some test cases and I like it.

Since 0.8.0 I have the problem that concatenation does not work for me as described in "Quick tip #5" 
https://www.11ty.io/docs/quicktips/concatenate/

Now, all slashes are transformed to backslashes.

Similar with links to root directory 
<a href="/">Home</a>

They look like this afterwards 
<a href="\/">Home</a>

With 0.7.1 everything was fine and I cannot find out what the problem is.

Any hints or suggestions? Thanks.

**Comment by kleinfreund** [comment]
What are you trying to concatenate? Which template code are you using for concatenation?

**Comment by ssgstarter** [comment]
I concatenate CSS files which are within _includes/baseCSS/
The file which does the concatenation is direct within the input directory.

`---
permalink: css/styles-mix-min.css
---
{% include "baseCSS/base.css" %}
{% include "baseCSS/custom.css" %}`

Furthermore the same for JS files.

**Comment by ssgstarter** [comment]
Using "Insert code" looks strange. Sorry for this.

It looks like this:


---
permalink: css/styles-mix-min.css
---
{% include "baseCSS/base.css" %}
{% include "baseCSS/custom.css" %}

**Comment by AndrewAsquith** [comment]
Are you on Windows?  

It sounds like it is the same as this:
https://github.com/11ty/eleventy/issues/497#issuecomment-483891139

Not sure how it would apply to concatenation but without code I'm just guessing.

**Comment by ssgstarter** [comment]
Yes, I am on Windows.

Awesome, this does the trick @AndrewAsquith.
After replacing line 124 as mentioned, everything works fine for me.

Thank you very much.
