### ISSUE TITLE
Limit posts listed on homepage

### ISSUE THREAD

**Issue by pdkaizer** [11ty/eleventy#503]
I want to limit the posts showing on my home page to the most recent 5 posts. How do I do that?

**Comment by kleinfreund** [comment]
Hey. So, do you already have a post listing on that home page and now it’s just showing all your posts? In other words, you already have something along the lines of this:

`index.liquid`:
```liquid
---
layout: base
---
<ul class="post-list">
  {%- for post in collections.posts -%}
  <li>
      <!-- post content -->
  </li>
  {%- endfor -%}
</ul>
```

Next, we need to (1) reverse that collection (or array) and limit it to a certain number of results. The following should do the trick:

```liquid
{% assign top_posts = collections.posts | reverse %}
{%- for post in top_posts limit:5 -%}
  <!-- post content -->
{%- endfor -%}
```

---

As a side note, I tried the following, but it doesn’t have the expected result.

```liquid
{%- for post in collections.posts reversed limit:5 -%}
  <!-- post content -->
{%- endfor -%}
```

**Comment by pdkaizer** [comment]
@kleinfreund thanks for the tips. Actually putting:
pagination:
  data: collections.post
  size: 4
  reverse: true
into the front matter of my index.md file and then using:
{%- for post in pagination.items -%}
<h2><a href="{{ post.url }}">{{ post.data.title }}</a></h2>
<i class="far fa-calendar-alt"></i> {{ post.date | dateDisplay("LLL d, y") }}
<p>{{ post.data.summary }}</p>
{%- endfor -%}
did the trick.

**Comment by kleinfreund** [comment]
Ah, I see. I didn’t know if you were paginating your blog posts or not and didn’t want to make any assumptions. Glad it works now.

**Comment by granttransition** [comment]
Trying to achieve the as above, using the example I have this…

```
{% assign allproductposts = collections.products limit: 2 -%}
{% for product in allproductposts -%}
{% include "partials/product_card.html" -%}
{% endfor -%}
```
But I just get an error saying, `unknown block tag: assign`

Would really appreciate some guidance

**Comment by binyamin** [comment]
@granttransition Oh no! Can you open a new issue, please?

**Comment by pdehaan** [comment]
@granttransition I think you can do one of the following (assuming you're using .liquid templates):

- Use the [`slice` filter](https://liquidjs.com/filters/slice.html) in your `{% assign %}` tag:
```liquid
{% assign allproductposts = collections.products | slice: 0, 2 %}
```

or 

- Use the [`limit` parameter](https://liquidjs.com/tags/for.html#limit) directly in your `{% for %}` tag:
```liquid
{% for product in collections.products limit:2 %}
```

... but +1 to @binyamin's comment above about creating a new GitHub issue and we can debug further there.
