### ISSUE TITLE
New layouts directory setup breaking build

### ISSUE THREAD

**Issue by tempertemper** [11ty/eleventy#506]
I'm trying to set up the [new layouts directory](https://v0-8-0.11ty.io/docs/config/#directory-for-layouts-(optional)) that was released in v0.8.0 but am hitting an issue. Here's how I've set things up:

1. I added layouts to my .eleventy.js file, following the new docs
2. I moved my layouts out of /_includes/layouts/ and into /_layouts/
3. I changed all references to layouts in front-matter and directory config files to `layout: layouts/base` to `layout: base`

There was no reference to number 3 in the [layout docs](https://www.11ty.io/docs/layouts/) so I assume this is correct and the `layout` key just carries over from how it used to be.

Anyway, with that setup, I'm I'm getting this when I run `eleventy` to build the site:

```
Problem writing Eleventy templates: (full stack in DEBUG output)
> You’re trying to use a layout that does not exist: base (undefined) (Error)
Processed 0 files in 0.14 seconds
```

Can you see what I'm doing wrong? Is it worth giving you the full debug output?

Thanks for taking a look 🙂

**Comment by kleinfreund** [comment]
This looks like it should work like you expect. I’m just guessing now, but can you try adding the file extension of your template (e.g. `layout: base.liquid`, depending on the templating engine you use)?

**Comment by tempertemper** [comment]
Hi @kleinfreund 👋 Adding the file extension doesn't help, I'm afraid 🙁 Still getting the same error:

```
Problem writing Eleventy templates: (full stack in DEBUG output)
> You’re trying to use a layout that does not exist: base.html (undefined) (Error)
Processed 0 files in 0.21 seconds
```

**Comment by kleinfreund** [comment]
I tried this in an isolated project and it works for me. Can you spot any differences? In particular, check if you’re still using the other template directory (i.e. _includes/layouts in your case).

This is the directory structure I use:

- src/
  - _layouts
    - base.liquid
  - index.md
- .eleventy.js

.eleventy.js:

```js
module.exports = function () {
  return {
    dir: {
      input: 'src',
      layouts: '_layouts'
    }
  };
};
```

base.liquid:
```liquid
<!DOCTYPE html>
<html lang="en">
<head>
  <title>test</title>
</head>
<body>
  {{ layoutContent }}
</body>
</html>
```

index.md:
```markdown
---
layout: base
---
# Hello
```

**Comment by miklb** [comment]
I feel like I'm seeing something similar

```
Input Error: You must pass a valid list of files to parse
Problem writing Eleventy templates: (more in DEBUG output)
> TemplateLayoutPathResolver directory does not exist for home.njk: _includes (Error):
    Error: TemplateLayoutPathResolver directory does not exist for home.njk: _includes
```

I have a similar structure src/_layouts and in my eleventy config I have `layouts: "_layouts"` 

`index.jk` calls `home.njk` which then references `base.njk` (I believe these are defaults from elventy-base-blog.

If can provide more info or this is an unrelated issue, please advise.

**Comment by tempertemper** [comment]
Huge thanks to @kleinfreund for his pointers and patience and huge apologies to everyone else for the unwitting red herring, but I've fixed the issue. I've zero idea how I managed it but it looks like I was running version 0.6.0 🤦‍♂️

**Comment by sachin10101998** [comment]
@miklb did you find a solution?

**Comment by miklb** [comment]
I did not and haven’t looked at the project since.

**Comment by sachin10101998** [comment]
I found it. The problem was with .eleventhy.js file itself.
