### ISSUE TITLE
Case insensitive file formats

### ISSUE THREAD

**Issue by veleek** [11ty/eleventy#509]
Currently the default set of file formats is all lower case.  On windows, some tools I've used generated file names with uppercase extensions.  Running eleventy just ignored these files and it took a bit of troubleshooting to determine what the issue is.

I have a feeling that just enabling case insensitivity might be a pretty big can of worms, but what about enabling it by default only on Windows and allowing an override in config?

**Comment by kleinfreund** [comment]
Eleventy should probably transform paths to lowercase when preforming file extension matching in general. I would avoid writing platform-specific code. This is definitely a bug.

**Comment by veleek** [comment]
Just submitted a PR for this item.  Let me know if it looks reasonable.

**Comment by zachleat** [comment]
Merged!
