### ISSUE TITLE
Markdown not rendering code properly when using a template

### ISSUE THREAD

**Issue by nikhiljha** [11ty/eleventy#512]
```
```bash
# Change hostname
echo MY_HOSTNAME > /etc/hostname
hostname MY_HOSTNAME

# Add user
adduser MY_USER # INTERACTIVE
usermod -aG sudo MY_USER

# Disable Xorg
sudo systemctl set-default multi-user.target

# Update
apt update
apt full-upgrade
reboot
\```
```

(no backslash there, just to escape github's formatting)

... is turning into ...

<img width="714" alt="Screen Shot 2019-04-28 at 8 44 20 AM" src="https://user-images.githubusercontent.com/2773700/56866760-2184be00-6992-11e9-91d8-441f4bd39c02.png">

... instead of ...

```bash
# Change hostname
echo MY_HOSTNAME > /etc/hostname
hostname MY_HOSTNAME

# Add user
adduser MY_USER # INTERACTIVE
usermod -aG sudo MY_USER

# Disable Xorg
sudo systemctl set-default multi-user.target

# Update
apt update
apt full-upgrade
reboot
```

**Comment by nikhiljha** [comment]
Meaning, it's in a code block, but for some reason it's rendering the `#` as titles instead of just as `#`.

**Comment by kleinfreund** [comment]
What's the filename of the file containing that code block? What does your .eleventy.js file look like?

**Comment by nikhiljha** [comment]
.eleventy.js looks like

```
const { DateTime } = require("luxon");
const pluginRss = require("@11ty/eleventy-plugin-rss");

module.exports = function(config) {

  // A useful way to reference to the contect we are runing eleventy in
  let env = process.env.ELEVENTY_ENV;

  // Layout aliases can make templates more portable
  config.addLayoutAlias('default', 'layouts/base.njk');

  // Add some utiliuty filters
  config.addFilter("squash", require("./src/filters/squash.js") );
  config.addFilter("dateDisplay", (dateObj, format = "LLL d, y") => {
    return DateTime.fromJSDate(dateObj, {
      zone: "utc"
    }).toFormat(format);
  });
  config.addPlugin(pluginRss);

  // minify the html output
  config.addTransform("htmlmin", require("./src/utils/minify-html.js"));

  // pass some assets right through
  config.addPassthroughCopy("./src/site/images");
  config.addPassthroughCopy("./src/site/school");
  config.addPassthroughCopy("./src/site/keybase.txt");

  // make the seed target act like prod
  env = (env=="seed") ? "prod" : env;
  return {
    dir: {
      input: "src/site",
      output: "dist",
      data: `_data/${env}`
    },
    templateFormats : ["njk", "md"],
    htmlTemplateEngine : "njk",
    markdownTemplateEngine : "njk",
    passthroughFileCopy: true
  };

};
```

and the filename is `armclustertutorial.md`

You can see the site source (without the broken article posted, for obvious reasons) here: https://github.com/nikhiljha/blog

**Comment by kleinfreund** [comment]
Could this be caused by the markdown engine being set to Nunjucks? (I'm on a train right now)

**Comment by nikhiljha** [comment]
Hmm... I added

```
  var hljs = require('highlight.js'); // https://highlightjs.org/

  // Actual default values
  var md = require('markdown-it')({
    html: true,
    breaks: true,
    highlight: function (str, lang) {
      if (lang && hljs.getLanguage(lang)) {
      try {
        return '<pre class="hljs"><code>' +
                 hljs.highlight(lang, str, true).value +
                 '</code></pre>';
        } catch (__) {}
      }
      return '<pre class="hljs"><code>' + md.utils.escapeHtml(str) + '</code></pre>';
    }
  });

  config.setLibrary("md", md);
```

to my .eleventy.js and now it looks like this ...

<img width="714" alt="Screen Shot 2019-04-28 at 10 58 11 AM" src="https://user-images.githubusercontent.com/2773700/56868235-86491400-69a4-11e9-9fee-1d791c3be260.png">

... but only when `breaks: true,`

if `breaks: false,` then it looks like this...

<img width="719" alt="Screen Shot 2019-04-28 at 10 59 08 AM" src="https://user-images.githubusercontent.com/2773700/56868243-a973c380-69a4-11e9-8523-0cd04fe75c8d.png">

I don't think the `breaks` setting should be affecting things in code blocks, so it's still broken but less broken.

**Comment by nikhiljha** [comment]
Actually, even with `breaks: true` some of the code blocks are still broken.

<img width="713" alt="Screen Shot 2019-04-28 at 11 04 41 AM" src="https://user-images.githubusercontent.com/2773700/56868306-6ebe5b00-69a5-11e9-95b9-76d6703c2a3a.png">

is supposed to be

```bash
# Use proper locale
locale-gen en_US.UTF-8
dpkg-reconfigure locales
dpkg-reconfigure keyboard-configuration
localedef -i en_US -c -f UTF-8 en_US.UTF-8
reboot
```

**Comment by nikhiljha** [comment]
Found another weird behavior, *it's only the first line that's broken*.

```
```
# this will be weird

# everything here is
echo ok
\```
```

<img width="710" alt="Screen Shot 2019-04-28 at 7 25 44 PM" src="https://user-images.githubusercontent.com/2773700/56873993-6d178600-69eb-11e9-9ed8-27c22283b063.png">

**Comment by zachleat** [comment]
Having trouble reproducing this:

<img width="242" alt="image" src="https://user-images.githubusercontent.com/39355/56876066-795f0b80-6a0a-11e9-92ec-a537bbe32d10.png">

outputs:

<img width="531" alt="image" src="https://user-images.githubusercontent.com/39355/56876070-80861980-6a0a-11e9-991c-124e32650ace.png">

which seems correct to me.

Are you using a layout? Can you attach the input markdown file and the output HTML file it generates?

**Comment by nikhiljha** [comment]
@zachleat I'm using the eleventyone scaffold; my full source is at https://github.com/nikhiljha/blog and you can find the HTML output at https://nikhiljha.com/.

(An example page with the broken tags can be found at https://nikhiljha.com/posts/neuralnetbaseline/ - which corresponds to `posts/neuralnetbaseline.md`).

**Comment by nikhiljha** [comment]
@zachleat I found a simpler test case.

Just render this page...

```md
---
title: "demo"
---

## This text is required or the bug will not happen.

I'm not sure why, but I think its something to do with nunjucks escaping.

```bash
# Change hostname
echo MY_HOSTNAME > /etc/hostname
hostname MY_HOSTNAME

# Add user
adduser MY_USER # INTERACTIVE
usermod -aG sudo MY_USER

# Disable Xorg
sudo systemctl set-default multi-user.target

# Update
apt update
apt full-upgrade
reboot
\```
```

... through this nunjucks template...

```njx
{{ content | safe }}
```

... it outputs ...

```
<h2>This text is required or the bug will not happen.</h2>
<p>I'm not sure why, but I think its something to do with nunjucks escaping.</p>
<pre class="hljs"><code><span class="hljs-comment"># Change hostname</span>
<span class="hljs-built_in">echo</span> MY_HOSTNAME &gt; /etc/hostname
hostname MY_HOSTNAME
<p><span class="hljs-comment"># Add user</span><br>
adduser MY_USER <span class="hljs-comment"># INTERACTIVE</span><br>
usermod -aG sudo MY_USER</p>
<p><span class="hljs-comment"># Disable Xorg</span><br>
sudo systemctl <span class="hljs-built_in">set</span>-default multi-user.target</p>
<p><span class="hljs-comment"># Update</span><br>
apt update<br>
apt full-upgrade<br>
reboot<br>
</code></pre></p>
```

... which is clearly wrong. It's doing HTML formatting inside my code snippet. If you remove the text and title above it, it renders as expected.

**Comment by Ryuno-Ki** [comment]
Hm, `markdown-it` implements Commonmark.

Your example [looks fine](https://spec.commonmark.org/dingus/?text=---%0Atitle%3A%20%22demo%22%0A---%0A%23%23%20This%20text%20is%20required%20or%20the%20bug%20will%20not%20happen.%0A%0AI%27m%20not%20sure%20why%2C%20but%20I%20think%20its%20something%20to%20do%20with%20nunjucks%20escaping.%0A%0A%60%60%60bash%0A%23%20Change%20hostname%0Aecho%20MY_HOSTNAME%20%3E%20%2Fetc%2Fhostname%0Ahostname%20MY_HOSTNAME%0A%0A%23%20Add%20user%0Aadduser%20MY_USER%20%23%20INTERACTIVE%0Ausermod%20-aG%20sudo%20MY_USER%0A%0A%23%20Disable%20Xorg%0Asudo%20systemctl%20set-default%20multi-user.target%0A%0A%23%20Update%0Aapt%20update%0Aapt%20full-upgrade%0Areboot%0A%5C%60%60%60) there.

**Comment by nikhiljha** [comment]
@Ryuno-Ki As mentioned in my last comment, the bug only happens when you render it through a nunjucks template that looks like `{{ content | safe }}`. It renders perfectly if I don't use templating.

**Comment by Ryuno-Ki** [comment]
Thanks for clarifying the title :-)

I tried to further isolate the issue (to see, which dependency might be offending).

I'm aware that it might sound like heresy, but have you tried adding `console.log`s in the downloaded `eleventy` dependency? That is, checked, what compiled markdown gets fed into Nunjucks.

**Comment by nikhiljha** [comment]
Just tried that and it looks like it's being parsed twice: first the Markdown (which parses correctly), and then when it's parsed again as part of the template, the offending `<p>`s are added.

Here's a really long paste that shows what's happening: https://hastebin.com/ogifuxoqab.log

(The relevant bit is all the way to the right. There's a code segment at the end of the article which you can see.)

**Comment by zachleat** [comment]
Hmm, I tried to check out your repo and go through it but got a bunch of errors unrelated to this issue?

I even tried to make my own test case and use your custom syntax highlighting code from your `.eleventy.js` file, using a markdown file with a nunjucks layout.

I got this:

<img width="846" alt="image" src="https://user-images.githubusercontent.com/39355/59558063-f50f1a80-8fae-11e9-8aed-0dbf8ff6a6f7.png">

That seems right to me?

Sorry about this but if you can fix the other unrelated errors in your repo, please ping this issue again and I’ll be happy to retest.

**Comment by nikhiljha** [comment]
@zachleat It was fixed in the template I was using: https://github.com/philhawksworth/eleventyone

Not sure what the underlying problem is though, but it was fixed.
