### ISSUE TITLE
Feature request: Asynchronous universal filters

### ISSUE THREAD

**Issue by ssgstarter** [11ty/eleventy#518]
May this possible? What is at the bottom of this question is to run multiple PostCSS by filter.

**Comment by kleinfreund** [comment]
Related: https://github.com/11ty/eleventy/issues/508#issuecomment-488725852

**Comment by ssgstarter** [comment]
BTW, as background: 

``` javascript
eleventyConfig.addFilter( "postCSS", function( code ) {
    return postcss( [
            require( 'autoprefixer' )( {
                // options
            } ),
            require( "cssnano" )( {
                preset: [ 'default', {
                    // options
                } ]
            } )
        ] )
        .process( code )
        .then( function( result ) {
            return result.code;
        } )
} );
```

Result in this error:

```
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
```

**Comment by ssgstarter** [comment]
BTW 2, also tried asynchronous Nunjucks filter which seems not to work:

```javascript
eleventyConfig.addNunjucksAsyncFilter( "postCSS", function( value, callback ) {
    setTimeout( function() {
        callback(
            null,
            require('postcss')([
                require('autoprefixer')({
                    // options
                }),
                require( "cssnano" )({
                    preset: ['default', {
                        // options
                    }]
                })
            ])
            .process(value)
            .then( function (callback) {
                return callback.value;
            })
        );
    }, 100 );
} );
```

Same error:

```
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
```

**Comment by kleinfreund** [comment]
This is not an error but a warning and not the source of your asynchronous filter not working.

As for your asynchronous Nunjucks filter, it is used wrong. Try this:

```js
const postcss = require("postcss");
const autoprefixer = require("autoprefixer");
const cssnano = require("cssnano");

module.exports = function (eleventyConfig) {
  eleventyConfig.addNunjucksAsyncFilter("postCSS", function(value, callback) {
    postcss([
      autoprefixer,
      cssnano
    ])
      .process(value)
      .then(function (result) {
        callback(null, result.css);
      });
  });

  return {
    htmlTemplateEngine: "njk"
  }
};
```

The documentation doesn’t make it entirely clear that the `setTimeout` call is just used as an example for an asynchronous API to demonstrate how it is used in general.

**Comment by ssgstarter** [comment]
Terrific, @kleinfreund !

The warning yet appears.

I suppose this solution could be for other people a very important hint! 
Maybe as "Quick tip".

Thank you very much @kleinfreund. 

I am closing this issue now.
This is the right action, isn´t it? (I am a starter here)

**Comment by kleinfreund** [comment]
So we’re dealing with two things here: The asynchronous Nunjucks filter not working and universal filters being synchronous right now. As far as I can tell, not all templating languages support asynchronous filter. That’s why Eleventy currently can’t have asynchronous global filters. Therefore, closing this issue is the right action. Currently.

**Comment by ssgstarter** [comment]
I think it is worth pointing out that the asynchronous Nunjucks filter for PostCSS works as mentioned above by  @kleinfreund.

The warning can be ignored (or is reputed to be suppressible).
