### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by mh166** [11ty/eleventy#521]
I wanted to `npm install -g @11ty/eleventy` this package on one of my machines. But it always fails with an error message. To be honest, I don't think this is a problem with this package directly - at least not per se. But then again, so far it has just been this very package that fails me...

Here's a log:

```
[root@arch2go _logs]# npm install -g @11ty/eleventy
npm ERR! Unexpected end of JSON input while parsing near '...t.io","version":"1.0.'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-06T13_52_35_760Z-debug.log

[root@arch2go _logs]# tail -n20 2019-05-06T13_52_35_760Z-debug.log
192 silly resolveWithNewModule serve-static@1.13.2 checking installable status
193 silly pacote version manifest for ua-parser-js@0.7.17 fetched in 165ms
194 silly resolveWithNewModule ua-parser-js@0.7.17 checking installable status
195 http fetch GET 200 https://registry.npmjs.org/yargs 145ms (from cache)
196 silly pacote version manifest for yargs@6.4.0 fetched in 167ms
197 silly resolveWithNewModule yargs@6.4.0 checking installable status
198 timing stage:rollbackFailedOptional Completed in 4ms
199 timing stage:runTopLevelLifecycles Completed in 2568ms
200 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...t.io","version":"1.0.'
200 verbose stack     at JSON.parse (<anonymous>)
200 verbose stack     at parseJson (/usr/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
200 verbose stack     at consumeBody.call.then.buffer (/usr/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
200 verbose stack     at processTicksAndRejections (internal/process/next_tick.js:81:5)
201 verbose cwd /root/.npm/_logs
202 verbose Linux 4.20.10-arch1-1.0-ARCH
203 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "@11ty/eleventy"
204 verbose node v11.10.0
205 verbose npm  v6.9.0
206 error Unexpected end of JSON input while parsing near '...t.io","version":"1.0.'
207 verbose exit [ 1, true ]

[root@arch2go _logs]# node --version
v11.10.0

[root@arch2go _logs]# npm --version
6.9.0

[root@arch2go _logs]# npm cache verify
Cache verified and compressed (~/.npm/_cacache):
Content verified: 887 (16988252 bytes)
Index entries: 1377
Finished in 12.877s
```

Could you give me any hints on where to find the culprit that prevents me from installing it? If I may provide some more information, just tell me what's required. 😊

**Comment by mh166** [comment]
Mhh... even though the cache was verified (see last command in log above), `npm cache clean --force` solved _that_ issue. Unfortunately, I still can't install this package:

```
[root@arch2go ~]# npm install -g @11ty/eleventy
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
Segmentation fault (core dumped)trip-ansi: sill extract static-extend@0.1.2
```

Even when re-running it multiple times, it always segfaults, even though on different packages. So it's not always the same one.

I just don't get it... Why is it not working? Unfortunately, I have no clue how to get useful information from those core dumps in order to further debug this. Any help would be appreciated!

**Comment by zachleat** [comment]
Hmm, I’m not sure! Can you try a different version of Node? I thought there was something funky about how they did odd version releases?

I can say that we do have Linux tests running on Travis CI and those seem to be running okay: https://travis-ci.org/11ty/eleventy

**Comment by mh166** [comment]
I could narrow it down to v0.7.0 bringing a seemingly breaking change (at least for me on that particular notebook...). Because even with three or four attempts, `npm install -g @11ty/eleventy@0.6.0` (with uninstall beetween them, of course) works without any problems. But with v0.7.0, each and every time I try, it segfaults.

I guess I have to live with that for now, as I don't have too much time to dig into the details of what has changed since. But maybe this helps. :)

_PS:_ while I wrote this addition, you replied. Thanks for your help. I might try it with a different node version. If I understand you correctly, I should try v10 for example? I'll see, if I can manage it.

As for the CI: I can confirm, as well, that the package in general seems to be fine. Tried to install it on two other machines - no problems there. Just this one system is giving me those troubles.

Then again: as you mentioned the node version - both of the other machines do not run the latest v11. Maybe it really is the root cause. I'll look into it. Thank you for giving me a hint. 👍

**Comment by Ryuno-Ki** [comment]
`npm ERR! Unexpected end of JSON input while parsing near '...t.io","version":"1.0.'`

Would you mind sharing the contents of your `package.json`?
Is it valid JSON?
(Note that the version ends with a dot … since eleventy does not have a `1.0` yet, I suspect it might be your own project).

**Comment by mh166** [comment]
@Ryuno-Ki I was trying to install it globally (note the `-g` option), so there's no `package.json` of mine. I guess, it was a corrupted package in the cache, since _this_ error disappeared after force-cleaning it.

@zachleat Tomorrow I'm trying with another node version and will report back. :)

**Comment by mh166** [comment]
You were absolutely right! 😲 Using the LTS version (as of writing, that is v10.5.3), it installs just fine. Thank you sooo much! 👍 

Now I used v10 to `npm install -g` eleventy and switched back to using v11 – and it works like a charm.

As this seems to be quite a corner case, I think this issue can be closed. Unless, of course, you really want to dig into this strange mess... 😉
