### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by GerhardMes** [11ty/eleventy#527]
hi there,
very interesting project. My question is, if there is i18n support or feature?
I need it for my website.

Thanks and greetings from Salzburg, Austria
Cheers Gerhard

**Comment by Ryuno-Ki** [comment]
Hi @GerhardMes,
not yet. See https://github.com/11ty/eleventy/issues/420

**Comment by zachleat** [comment]
Follow along at #420! Thanks
