### ISSUE TITLE
How to factor Liquid template that uses front-matter?

### ISSUE THREAD

**Issue by thejohnfreeman** [11ty/eleventy#528]
The pattern for a Liquid template that injects itself into another template as the `content` variable is well established, and both templates can use front-matter. But if I have a liquid template that wants to *include* another template, then the *included* template's front-matter is ignored, whether I use `{% include child %}` or `{% include 'child' %}` (with `dynamicPartials: true`). The [documentation](https://www.11ty.io/docs/languages/liquid/#supported-features) suggests that the first form should respect the front-matter, but it doesn't in my experience; the whole file, front-matter included, is injected by the `include` directive. Am I doing something wrong? Is there a workaround?

**Comment by kleinfreund** [comment]
Where is it suggested that an included template's front matter can be used? As far as I'm aware, that doesn't work.

**Comment by thejohnfreeman** [comment]
The suggestion is in what is unsaid: https://i.imgur.com/14isX1K.png

**Comment by jevets** [comment]
My experience is the same as @kleinfreund says. The `include`d file's frontmatter is ignored.

The first item in your screenshot I think is just showing that you can exclude the quotes and eleventy will try to locate the named file.

I've never needed an included file's own front-matter. Usually the includer defines the data that the included consumes. More info/context on your use-case? 

If the included file does need its own data, I usually use the template language's way of defaulting, i.e. in njk:

```html
<div class="{{ $classname if $classname else 'my-default-classname' }}">...</div>
```

Or I'll just use global or directory data.

**Comment by thejohnfreeman** [comment]
The use-case is a list of links following a template. Instead of writing out the HTML for every list item, I want to stamp out a template against objects in an array. It is easier to read and write object literals than to read and write HTML. I'll look into global data. How would directory data work for an include in the `_includes` directory?

**Comment by jevets** [comment]
@thejohnfreeman 
Sorry: directory data wouldn't work for `_include`s data, but global data would. Example just below.
(I was thinking of cases where I've used directory data in `config.input.dir[/some/path]` that included files would consume if it exists, i.e. a set of objects that represent menu items which change based on a given section, example way below.)

```js
// _data/items.js
module.exports = [
  { label: 'one' },
  { label: 'two' },
]
```

```njk
// _includes/items.njk
{% for item in items %}
<li>{{ item.label }}</li>
{% endfor %}
```

Usually an `_include` is either a very specific chunk of content or a reusable component that accepts some variable data. 

Sounds like you're looking to define the data directly in the include file itself (and this approach would have its perks, for housekeeping if nothing else), but I don't think any included file in eleventy will read its own front matter, regardless of template language.

**Consider generating a file into _includes:**

You could use an actual template file but write it to `_includes/my-stamped-out-template.liquid` using permalink remapping and [bypassing permalink output](https://www.11ty.io/docs/permalinks/#ignore-the-output-directory). Then you could use liquid to include your generated liquid include. I don't often write templates to `_includes`, but it does have its uses.

---

(example from way above note):

```
section-one/
  section-one.json // "items": [{ label: 'Do A', uri: '/a' }, { label: 'Do B', uri: '/b' }]
section-two/
  section-two.json // "items": [{ label: 'Do C', uri: '/c' }, { label: 'Do D', uri: '/d' }]

// _includes section-menu.njk
{% for item in items %}...{% endfor %}
```

**Comment by zachleat** [comment]
Sorry about that documentation inconsistency @thejohnfreeman, it’s patched up now.

You can read more about where this could be heading here: https://github.com/11ty/eleventy/issues/189#issuecomment-411544737 Subscribe to that issue if you’d like updates!

**Comment by zachleat** [comment]
Closing, follow along at #189!
