### ISSUE TITLE
Unstable collection order

### ISSUE THREAD

**Issue by jeremenichelli** [11ty/eleventy#532]
Hi @zachleat, I'm migrating my Jekyll blog to Eleventy and found a weird case where reversing a collection somewhere alters the order in other templates.

For example, one page featuring the last eight posts and another one with the full archive:

**blog/index.md**
```
{% assign posts = collections.post | reverse %}

<ul class="bloglist">
{% for post in posts limit: 8 %}
  <li class="bloglist__item">
    <a href="{{ post.url }}>{{ post.data.title }} </a>
  </li>
{% endfor %}
```

**archive/index.md**
```
{% assign archive = collections.post | reverse %}

<ul class="archive">
{% for post in archive %}
  <li class="archive__item">
    <a href="{{ post.url }}">{{ post.data.title }}</a>
  </li>
{% endfor %}
```

I'm not using `.reverse()` as it isn't recommended. The weird thing too here is that if I remove one of the `reverse` filter, refreshing the build sometimes reverses the order in archive page, some times the other one, making builds non determinisct (same templates produces different outputs). Am I doing something wrong or is this a bug?

**Comment by jeremenichelli** [comment]
I examined the codebase of liquidjs and found that _reverse_ filter is not a pure function, though I don't know if it's intended so I left a question in an issue: https://github.com/harttle/liquidjs/issues/126

**Comment by chrisssycollins** [comment]
@jeremenichelli I ran into a similar issue - I worked around it by creating a reversed collection in the `.eleventy.js` config. 

```js
// Reverse posts collection
eleventyConfig.addCollection("reversedPosts", function (collection) {
    return collection.getFilteredByTag("posts").reverse();;
});
```

Usage in template (with pagination) 
```
---
pagination:
    data: collections.reversedPosts
    size: 12
    alias: posts
---

{% for post in posts %}
    ...
{% endfor %}
```

**Comment by jeremenichelli** [comment]
Closing this since it was solved in `liquidjs@8.3.2` if I'm not wrong.

**Comment by barcia** [comment]
Hi, I reopen this because I have exactly the same issue. The same code in two pages outputs different order, one reversed and the other not reversed.

@jeremenichelli you comment that Liquid solve this in the version 8.3.2 but the version used currently by 11ty is the [6.4.3](https://github.com/11ty/eleventy/blob/master/package.json#L110).

You have still this issue?

**Comment by jeremenichelli** [comment]
I'm manually creating my own collection on my config file so I don't know the status of this.
