### ISSUE TITLE
Markdown outcome parsed as pre/code tags

### ISSUE THREAD

**Issue by jeremenichelli** [11ty/eleventy#533]
For some reason indentation in liquid templates makes part of them rendered as code, here's a resduced example:

This in Jekyll gets rendered correctly, but in Eleventy content inside if/else statements get rendered inside `<pre><code></code></pre>` tags:
```
<a
      class="archive__link"
      alt="{{ post.title }}"
      {% if post.external_url %}href="{{ post.external_url }}" target="_blank"
      {% else %}href="{{ post.url }}"
      {% endif %}
  >
  {{ post.title }}
</a>
```

To fix this I needed to flatten all indentation:

```
<a class="archivelist__link" alt="{{ post.data.title }}"
{% if post.data.external_url %}href="{{ post.data.external_url }}" target="_blank" rel="noopener noreferrer"
{% else %}href="{{ post.url }}"
{% endif %}>
```

I'm thinking this could be a limitation of JavaScript implementation of Liquid, or the markdown parser, sorry for the noise if that's the case. And let me know if I can help further on this 😃

**Comment by edwardhorsford** [comment]
I suspect this is the same as #219 where markdown is interpreting the whitespace as code. Try using `{%- foo -%}` instead. More [docs](https://shopify.github.io/liquid/basics/whitespace/) here.

**Comment by jeremenichelli** [comment]
Oh, got it! Thanks a lot @edwardhorsford 💯

**Comment by Ryuno-Ki** [comment]
4 spaces are interpreted as beginning of a code block.

**Comment by jeremenichelli** [comment]
@Ryuno-Ki yeah looks like it, don't know if that's common in markdown parsers though, didn't have this output with the same snippet in Jekyll + kramdown.
