### ISSUE TITLE
Allow access to inherited data (permalink, at least) in order to be able to modify it

### ISSUE THREAD

**Issue by idiazroncero** [11ty/eleventy#535]
I'll try to explain myself using a real example.

I'm using Eleventy + Netlify CMS to give end users a CMS for a static site.

For the permalinks, i was using the following code on a Directory Data File (proyectos.json):

````
{
  permalink: /proyecto/{{ title | slug }}{% if url %}/{{ url }}{% endif %}/index.html
}
````

( {{ url }} comes from pagination)

Now, the user asks for a way to be able to override the permalink in some cases. I let them the ability to set a "link" on the front matter (in case you don't know, Netlify CMS allows non-technical users to edit the .md files using an interface) , and so now my code is:

````
permalink: "{% if link %}{{ link }}{% else %}/proyecto/{{ title | slug }}{% endif %}/{{ url }}/index.html",
````
If the user defined a link, output that, if not, the default kicks in.

It works... but it starts to be a little overkill to introduce all of this logic inside a templating language.

Also, i would like to perform some validations / checks on the user input to avoid errors and even build fails.

With the introduction of [Javascript Data Files](https://www.11ty.io/docs/data-js/), i wondered if there is any way to access something like the "current status" of data in order to be able to operate with it and do all of the logic in plain, vanilll JS instead of using template syntax inside an ever-growing string. I didn't found any way to do this, but I find it would be a very interesting feature.

For example, if we had access to some "currentData" variable, my code could be rewritten as this:

````
// Filename: proyectos.11tydata.js
var permalink;

if(currentData.linkOverride) {
  // Introduce some validations here! 
  permalink = currentData.linkOverride;
} else {
  permalink = "/proyecto/{{ title | slug }}{% endif %}/{{ url }}/index.html"
}
// any further cases can be addressed here...

module.exports = {
  permalink: permalink
}
````

This is interesting for data like "permalinks". Most of the data gets through the pipeline down to the template layouts, and the logic can be easily addresed there. But some values, as "permalink", would benefit of this kind of exposition beforehand.

**Comment by Ryuno-Ki** [comment]
Have you tried to implement it as filter instead?

Or using `{% set %}` (in Nunjucks).

**Comment by zachleat** [comment]
I _believe_ this is solved by the enhancement request at #481? It’s explained better (with context) at #480. Can you confirm @idiazroncero?

**Comment by idiazroncero** [comment]
Yes, it does. Many thanks!

**Comment by zachleat** [comment]
Great—thanks!
