### ISSUE TITLE
Error messaging when input file isn’t utf-8

### ISSUE THREAD

**Issue by o-t-w** [11ty/eleventy#537]
I am using 11ty on Windows. I followed along the introductory tutorial. The generated HTML file looks like this: 

<img width="260" alt="11ty" src="https://user-images.githubusercontent.com/29547922/58025541-9ddf6c80-7b0c-11e9-95e7-fb6440047577.png">

**Comment by Ryuno-Ki** [comment]
Can you check the encoding of the file?
I suspect it's not UTF-8 (but cp1252).

**Comment by zachleat** [comment]
@Ryuno-Ki do you know if it’s technically possible to provide error messaging around things like this? I see https://www.npmjs.com/package/utf-8-validate but I don’t know how reliable it is

**Comment by Ryuno-Ki** [comment]
Hm, good question. On a GNU/Linux machine, I'd use [enca](https://linux.die.net/man/1/enconv) for that.
But I didn't found a wrapper around it on npm.

Something which goes into that direction is [is-utf8](https://github.com/wayfind/is-utf8) and [node-fs-iconv](https://github.com/bluelovers/node-fs-iconv) (but I don't speak Chinese).

I'd imagine to have a _meaningful_ error message, i.e. not only „this is not utf-8!”, but „are you using <encoding>?”.

**Comment by zachleat** [comment]
Maybe https://www.npmjs.com/package/utf-8-validate too. I don’t think it necessarily needs to know what encoding it is, just an error if it’s not UTF-8.

I’m going to move this to an Enhancement request, if that’s okay! I’d like better error messaging around this.

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
Related https://www.zachleat.com/web/smorgasbord-windows-terminal/ I’d consider this one resolved there!

**Comment by zachleat** [comment]
History of the above at https://github.com/11ty/eleventy/issues/2082#issuecomment-2168828502 and https://github.com/11ty/eleventy/issues/2323
