### ISSUE TITLE
Ignore node_modules by default

### ISSUE THREAD

**Issue by nsteiner** [11ty/eleventy#54]
It took me a minute to figure out that I was missing a my `.gitignore` file and that without it, eleventy was trying to parse everything in `node_modules`, which leads to strange errors. Maybe it's worth having eleventy preconfigured to ignore that folder unless overwritten in the `.eleventy.js` config?

**Comment by zachleat** [comment]
Note the commit message there:

> Ignore `node_modules` by default ONLY IF `.gitignore` does not exist.

**Comment by zachleat** [comment]
Will be included with v0.2.14
