### ISSUE TITLE
Tag pages difficulty

### ISSUE THREAD

**Issue by o-t-w** [11ty/eleventy#548]
I was trying to follow through QUICK TIP #004—ZERO MAINTENANCE TAG PAGES FOR YOUR BLOG but using Handlebars.

```
---
pagination:
 data: collections
 size: 1
 alias: tag
permalink: /tags/{{ tag }}/
---

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>

<body>
<h1>Tagged “{{ tag }}”</h1>

<ol>
    {{#each lookup collections tag }}
    <li><a href=" {{ this.url }}">{{ this.data.title }}</li>
    {{/each}}
    </ol>
</body>

</html>
```

I am getting the error: 

```
Having trouble rendering hbs template ./tags.hbs (TemplateContentRenderError)
inverse is not a function (TypeError):
```

It would be nice to have examples in more templating languages as I am unfamiliar with Nunjucks.

**Comment by o-t-w** [comment]
I managed to work this out but the documentation for Handlebars is really poor :( 

I needed `{{#each (lookup collections tag) }}`

**Comment by darby3** [comment]
Thanks from 2022!
