### ISSUE TITLE
Add content to a nunjucks block from shortcodes

### ISSUE THREAD

**Issue by bert-bruggeman** [11ty/eleventy#561]
How can I add content to a block in a layout from shortcodes?
I would also like to use variables or objects like "collections" in schortcodes, is this possible?

```
eleventy.js

  let nunjucks = new Nunjucks.Environment(
    new Nunjucks.FileSystemLoader("includes")
  );
  eleventyConfig.setLibrary("njk", nunjucks)

  eleventyConfig.addShortcode("button", (arg = {}) => {
    arg.target = (arg.href.lastIndexOf("http", 0) === 0) ? "_blank" : ""
    return nunjucks.render('components/button.njk', arg)
  })
```

```
components/button.njk
<a href="{{ href }}"{% if target %} target="{{ target }}"{% endif %}{% if id %} id="{{ id }}"{% endif %} class="btn{% if class %} {{ class }}{% endif %}">{{ text }}</a>
{% block js %}
... can't add content to js block in layouts/page.njk
{% endblock %
```

**Comment by kleinfreund** [comment]
Elventy calls "shortcodes for blocks" paired shortcodes. There is documentation for this feature, too: https://www.11ty.io/docs/shortcodes/#paired-shortcodes.

**Comment by bert-bruggeman** [comment]
Thanks for the anwser, but thats not what i mean,... An example: I would like to add a script or additional items to the footer of a page from a shortcode in the content, nunjucks uses "[block](https://mozilla.github.io/nunjucks/templating.html#block)" to accomplish this but I can't seem to find a way to make this work...

**Comment by veleek** [comment]
You've given an example of how you're defining you shortcode but it might be helpful to provide a sample input and expected output so we can see exactly what you're trying to accomplish.

Are you saying that you want a eleventy shortcode to be able to return Nunjucks content which will then be processed by Nunjucks?  I'm not sure if there's an EASY way to accomplish this because it could potentially result problems when the Nunjucks code you're producing ends up calling itself it a loop.

**Comment by bert-bruggeman** [comment]
I now realize that using nunjucks blocks is not a good way to solve my problem,... 
Is it possible to use the current page object in a short code?

**for example:**

For each shortcode I would like to set a script, json property, css, ... in the footer of the current page.

I could set a variable "footerContent" with an empty array for all pages
`footerContent: []`

For each short code I would add an item to "footerContent"
`page.footerContent.push (item)`

In the page layout I can then loop through the array in the footer ...
```
...
</body>
{% for item in footerContent%}
{{item}}
{% endfor%}
```
