### ISSUE TITLE
How to get collections by tag with hyphen or space?

### ISSUE THREAD

**Issue by sarunw** [11ty/eleventy#575]
If I have tag with space to hyphen is there a way to filter collection by that tag?

```
tags:
  - space tag
  - hyphen-tag
```

When I try

`collections.hyphen-tag it return nothing` and I don't know is there a way to filter by `space tag`

**Comment by sarunw** [comment]
That's work, thanks.

**Comment by djmtype** [comment]
However,  something like this doesn't work:  `collections['space tag']`

(and maybe it's just bad practice to use spaces for tags?)

**Comment by dixonge** [comment]
> Have you tried `collections['hyphen-tag']`?

yes! This saved me a lot of time...

**Comment by zachleat** [comment]
if you use

```
tags:
  - "space tag"
  - hyphen-tag
```

it _might_ work?

**Comment by pdehaan** [comment]
Confirmed that this worked:

```
---
title: tag test
tags:
  - with-hyphens
  - with spaces
  - "quoted spaces"
---

<p>tags: <pre>{{ tags | inspect }}</pre></p>
<p>collections: <pre>{{ collections | keys | inspect }}</pre></p>
<p>with-hyphens: <pre>{{ collections["with-hyphens"] | inspect }}</pre></p>
<p>with spaces: <pre>{{ collections["with spaces"] | inspect }}</pre></p>
<p><q>quoted spaces</q>: <pre>{{ collections["quoted spaces"] | inspect }}</pre></p>
```

Although I think the one caveat I've found is that if you're trying to refer to a collection for pagination, the bracket syntax doesn't really work, and I think you have to wrap the collection name in quotes:

```md
---
title: Tag Archive
pagination:
  data: "collections.with spaces"
  size: 1
  alias: spaces
permalink: "tag/{{ spaces.fileSlug | slug }}/"
---

What's this?
```

**Comment by zachleat** [comment]
@pdehaan it uses lodash.get to resolve that path, if that helps. Does that not support bracket notation?

Do you have to wrap in quotes? I thought YAML assumed a string there if the value starts with a letter and doesn't have a colon at the end

**Comment by dixonge** [comment]
> @pdehaan it uses lodash.get to resolve that path, if that helps. Does that not support bracket notation?
> 
> Do you have to wrap in quotes? I thought YAML assumed a string there if the value starts with a letter and doesn't have a colon at the end

I had to use ```collections['tag here']``` syntax. Not quotation marks. Easier than search/replace for all tags in all posts...Also solved a problem I was having with breadcrumbs using tags. If the original tag is a state, for example, it's more readable and easier to use New Mexico and then the breadcrumb will be properly capitalized and spaced automatically. If the tag was newmexico then you have to do all sorts of trickery to make the breadcrumb look right. Same for menu entries. OK this is way too long for GH lol

**Comment by zachleat** [comment]
For completeness, a warning about this lives on the docs here: https://www.11ty.dev/docs/collections/#a-note-about-using-in-tags (some more at #567)
