### ISSUE TITLE
Manually create collections

### ISSUE THREAD

**Issue by MadeByMike** [11ty/eleventy#587]
I think it would be great to manually create collections.

For background: One limitation of many SSGs is that they are heavily tied to the idea that there must be a markdown file to represent a page. Modern JAM stack sites rely more heavily on APIs and it's often the case that we have markdown files with only a small amount of front matter that is a pointer to an API that stores the content. Think of things like contentful or notion used as a CMS.

In a recent example, I wanted to combine a data source that had references to external articles with a collection of local posts that had markdown files.  The markdown pages had an `inputPath` but the external links did not. To create a fake collection that combined these data sources I did the following: https://gist.github.com/MadeByMike/d61800433b5556de90546e2c22e43944

It's not great. I'd rather 11ty was better able to accommodate custom collections. Beyond my specific example I think there are limitations to what types of data markdown can represent and a whole lot of SSG use-cases that need to go beyond markdown.

**Comment by gerwitz** [comment]
Maybe you can do this with a Javascript "data" file?

**Comment by Ryuno-Ki** [comment]
Have you seen `addCollection` [in the docs](https://www.11ty.io/docs/collections/#collection-api-methods)?

If I get you right, you want to merge API responses with file contents?

**Comment by MadeByMike** [comment]
@Ryuno-Ki addCollection() doesn't allow you to create a new collection objects from arbitrary data (as far as I know) You can only filter or merge existing collections.

**Comment by Ryuno-Ki** [comment]
I haven't used it myself yet, but shouldn't [getFilteredByGlob](https://www.11ty.io/docs/collections/#getfilteredbyglob(-glob-)) do that?

You could argue that you don't want to need files for it, but ... we have another ticket for that: #604

**Comment by edwardhorsford** [comment]
@MadeByMike Unless I'm misunderstanding what you want, you can absolutely create collections from arbitrary data. I myself read in some yaml data to make tens of different collections of data.

Starting [here in the docs](https://www.11ty.io/docs/collections/#advanced%3A-custom-filtering-and-sorting) - when you add collection you can return _anything_ - if it's iterable you can use it in pagination, etc.

I use that to read in some yaml /json transform the data, then return an array of objects for use in my templates.

I _think_ this is what you're asking for.

A brief snippet from mine:

In eleventy.js:
```js
eleventyConfig.addCollection("siteImages", require("./utils/collections/siteImages"));
```

In siteImages.js:
```js
module.exports = function(collection) {
  if (fs.existsSync(dataPath + '/siteImagesRenderedData.json', 'utf8')) {
    // console.log('Reading site image data')
    return readSiteImagesData()
  }
  else {
    console.log('siteImagesRenderedData.json not found, generating')
    return generateSiteImagesData(collection)
  }
};
```

You can see that 'collection' is passed in - my `generateSiteImagesData` actually parses this to grab some data from existing collections to use in my new collection. It's a bit house-of-cards, but works well.

**Comment by MadeByMike** [comment]
@edwardhorsford I'm not sure what generateSiteImagesData does but I found there were certain things a collection needed including an `inputPath` without this it would error.

**Comment by gerwitz** [comment]
@Ryuno-Ki indeed getFilteredByGlob should be useful, but see #617

**Comment by edwardhorsford** [comment]
@MadeByMike it's a custom function that reads in some yaml and spits out an array of data - my point was that you can return *anything* from a custom collection.

Per the docs "addCollection callbacks can now return any arbitrary object type and it’ll be available as data in the template. Arrays, strings, objects—have fun with it."

If you're finding inputPath is needed - that sounds like a downstream error - eg your templates expect it. How are you trying to use this data?

**Comment by zachleat** [comment]
https://www.11ty.dev/docs/collections/#return-values support for arbitrary values in collections was added in 0.5.3. Is there a specific bug with this?

That said I don’t think you should be a collection for this at all—why not just use global data for this?

**Comment by MadeByMike** [comment]
TBH I don't remember why anymore... way probably to do with paginating\sorting and looping over a combined set of data that included the external articles as well as local content. 

There are probably other ways to do this and I'm happy to re-open if needed.
