### ISSUE TITLE
Generate a simple output without extension?

### ISSUE THREAD

**Issue by pranasas** [11ty/eleventy#589]
Normally I use Markdown/Nunjucks to generate `.html` output.

However, I also need a very simple file named `_redirects` like
```
/cv        {{ external.cv }}
```
What is the cleanest way to achieve this? I'd hate to rename `_redirects.html` in another script afterwards.

**Comment by Ryuno-Ki** [comment]
Have you tried `permalink: _redirects`?
https://www.11ty.io/docs/permalinks/

**Comment by pranasas** [comment]
> Have you tried `permalink: _redirects`?
> https://www.11ty.io/docs/permalinks/

Thanks, that's exactly what I've been looking for. Somehow missed it...
