### ISSUE TITLE
Named Arguments passed to filters

### ISSUE THREAD

**Issue by cdowdy** [11ty/eleventy#591]
Is there a way to pass named arguments to filters/universal filters? Below is a liquid example.  

```js  
 eleventyConfig.addLiquidFilter( 'example', function( input, k2, k1 ) { ... });
```  

```Liquid  
   {{ 'input' | example: k1: "v1", k2: foo }}
```

I see LiquidJS has it (although eleventy is on 6.4.3 and named arguments is in 8+ https://github.com/harttle/liquidjs/issues/113)  

Right now whatever is passed to the filter has to be in the same order the filter code is written in. So the above would produce in your templates:  
```html  
input k1 v1   
```  

Another example would be a responsive image filter.  

```Liquid
{{ '/path/to/image' | img: alt: 'my alt text', sizes: '100vw', srcset: [ array of sizes here] }}  
```  

then I could generate with my filter the sizes found in the srcset key and not have to worry about getting the order wrong or putting this out for the community and having someone lookup each time they use the filter . 

If this is already possible could someone nudge me the right direction :) 

Thanks for your time everyone!

**Comment by cdowdy** [comment]
I had more time to actually read without glossing over the entirety of the docs and there is a way to pass in named arguments and that is __only possible in__   
  * js templates https://www.11ty.io/docs/languages/javascript/#relationship-to-filters-and-shortcodes
 * nunjucks https://www.11ty.io/docs/languages/nunjucks/#usage-4  

Like i said this is a quick look :)

I was coming from a twig template environment so in order to lessen the cognitive load of learning a new system (ie moving from old cms to eleventy) along with new templating language I stuck with the "defaults".  Nunjucks is closer to twig (nearly identical since its all based on jinja2) so this is actually a better outcome (for me). I had never looked at these other templating languages so this wasn't something I was aware of (benefits cons etc)

So to tidy up my example from the previous example: 

This liquid filter example 
```twig 
{{ '/path/to/image' | img: alt: 'my alt text', sizes: '100vw', srcset: [ array of sizes here] }} 
```  

would be turned into a shortcode in Nunjucks and used like:
```twig  
{% img alt="my alt text", sizes="100vw", srcset="[ array of sizes here]" } %}

So you can close this unless you'd rather leave it open for other newcomers !

**Comment by zachleat** [comment]
Hey @cdowdy! Thank you for checking back in—I love that you answered your own question and left a comment for everyone else!

Also upvote https://github.com/11ty/eleventy/issues/143 if you want twig template support in Eleventy.
