### ISSUE TITLE
I have a writting issue

### ISSUE THREAD

**Issue by claudioandresc** [11ty/eleventy#594]
Hello, I have a writting issue, please if you can help me I really apreciate.
Regards

![image](https://user-images.githubusercontent.com/23406898/60415640-b0d46a80-9ba9-11e9-88fb-59b52a971670.png)

**Comment by chrisssycollins** [comment]
@claudioandresc Can you share the contents of your `.eleventy.js` file what's in the `_includes` dir?

**Comment by claudioandresc** [comment]
sure @chrisssycollins  thanks for your contact, here is the info:
![image](https://user-images.githubusercontent.com/23406898/60467573-f2562b80-9c24-11e9-9ff9-3ea5eceacbb9.png)

.eleventy.js  code:

module.exports = function(eleventyConfig) {
  //eleventyConfig.addFilter("MFiltro", function() {});
  //eleventyConfig.addPassthroughCopy("assets");
  //eleventyConfig.addPassthroughCopy("css");
  //eleventyConfig.addPassthroughCopy("js");
/*
  eleventyConfig.setBrowserSyncConfig({
    callbacks: {
      ready: function(err, browserSync) {
        const content_404 = fs.readFileSync('_site/404.html');

        browserSync.addMiddleware("*", (req, res) => {
          // Provides the 404 content without redirect.
          res.write(content_404);
          res.end();
        });
      }
    }
  });
*/
  return {
    templateFormats: [
      "md",
      "njk",
      "html",
      "liquid"
    ],

    // If your site lives in a different subdirectory, change this.
    // Leading or trailing slashes are all normalized away, so don’t worry about it.
    // If you don’t have a subdirectory, use "" or "/" (they do the same thing)
    // This is only used for URLs (it does not affect your file structure)
    //pathPrefix: "/",

    markdownTemplateEngine: "njk",
    htmlTemplateEngine: "njk",
    dataTemplateEngine: "njk",
    passthroughFileCopy: true
    dir: {
      input: "src",
      include: "_includes",
      layout: "_layouts",
      output: "_site"
    }
  }
}

**Comment by chrisssycollins** [comment]
It could be the missing comma on line 38 of your `.eleventy.js` file. 

Can you try replacing your `.eleventy.js` file with:
```js
module.exports = function (eleventyConfig) {
  //eleventyConfig.addFilter("MFiltro", function() {});
  //eleventyConfig.addPassthroughCopy("assets");
  //eleventyConfig.addPassthroughCopy("css");
  //eleventyConfig.addPassthroughCopy("js");
  /*
  eleventyConfig.setBrowserSyncConfig({
  callbacks: {
  ready: function(err, browserSync) {
  const content_404 = fs.readFileSync('_site/404.html');

      browserSync.addMiddleware("*", (req, res) => {
        // Provides the 404 content without redirect.
        res.write(content_404);
        res.end();
      });
    }
  }
  });
  */
  return {
    templateFormats: [
      "md",
      "njk",
      "html",
      "liquid"
    ],

    // If your site lives in a different subdirectory, change this.
    // Leading or trailing slashes are all normalized away, so don’t worry about it.
    // If you don’t have a subdirectory, use "" or "/" (they do the same thing)
    // This is only used for URLs (it does not affect your file structure)
    //pathPrefix: "/",

    markdownTemplateEngine: "njk",
    htmlTemplateEngine: "njk",
    dataTemplateEngine: "njk",
    passthroughFileCopy: true,
    
    dir: {
      input: "src",
      include: "_includes",
      layout: "_layouts",
      output: "_site"
    }
  }
}
```
Also, as you are using the option to define where your layouts are make sure your 11ty version is` v0.8.0` or above at least.

**Comment by claudioandresc** [comment]
Thanks @chrisssycollins  I used the code that you gave me, but now I have this error:
![image](https://user-images.githubusercontent.com/23406898/60545073-2f372680-9ce8-11e9-9f67-7f9889353d35.png)
Also I remove the layouts folder and move the files to _includes folder.
Im using the 0.8.3 version

**Comment by chrisssycollins** [comment]
@claudioandresc Is the code available on a repo? With the code, I would be able to help you out a lot more.

**Comment by claudioandresc** [comment]
@chrisssycollins  thank you very much for your time, I already fixed, it was a quotation marks that I missed in the includes. I'll keep your contact for the future, can I?

**Comment by chrisssycollins** [comment]
@claudioandresc Great to hear!

**Comment by claudioandresc** [comment]
Yes, sure, thank you very much @chrisssycollins
