### ISSUE TITLE
Keeps crashing with undefined (undefined)

### ISSUE THREAD

**Issue by remy** [11ty/eleventy#595]
I run 11ty with `--serve`. It builds, I make a single change, and it recompiles, but crashes (not exit - just hung state) with `undefined (undefined)` (saying to check DEBUG logs).

The debug logs are clean until this:

```
  Eleventy:TemplateMap Collection: collections.all size: 29 +2s
  Eleventy:TemplateMap Collection: collections.insights size: 16 +0ms
  Eleventy:TemplateMap Collection: collections.all size: 29 +0ms
  Eleventy:TemplateMap Collection: collections.randomLatest size: 2 +1ms
  Eleventy:TemplateMap Collection: collections.articles size: 46 +0ms
  Eleventy:EleventyErrorHandler Unhandled rejection in promise: +0ms
  Eleventy:EleventyErrorHandler undefined (undefined): +0ms
  Eleventy:EleventyErrorHandler (error stack): undefined +0ms
```

Note the rejected promise doesn't include any info.

**To Reproduce**

As always, I'm pretty sure this is exclusive to me, but clone the [ffconf repo](https://github.com/leftlogic/ffconf), `npm install` then `npm run dev`.

Find an article `/src/articles/13.md` and make a change - this kept crashing for me.

**Expected behavior**

Aside from not crashing, I'd hope for the actual rejected error to appear.

**Environment:**

- node -v: v10.14.1
- npm -v: 6.4.1
- npx eleventy --version: 0.8.2
- OS: latest Mac OS

(side note, I'm on holiday away from machine this week - typically filing a bug the morning I leave, so if this doesn't work for you, I'll be picking up in a little over a week when I'm back - sorry!)

**Comment by remy** [comment]
Just to update - I had this happen to me in a production build recently - it left the ffconf website down (I think I need a post build check to make sure the files are generated - but the same thing happened as described, except it was `eleventy` by itself).

**Comment by remy** [comment]
URL to failing production deployment: https://app.netlify.com/sites/ffconf/deploys/5d2b4977e41a280008e74613

I've since had to add `test -e dist/index.html` to the end of the build process, so if it didn't succeed the output file will be missing and it exits non-zero and so netlify won't publish it.

**Comment by zachleat** [comment]
Oh dang hmm. We should always quit with an error code if the build fails. That’s a serious issue.

**Comment by remy** [comment]
I need to review my code to see whether a there's a dataset that might be
honking this somehow.

**Comment by zachleat** [comment]
Well, disappointingly, I can’t reproduce this locally. Your package.json indicates you’re using Eleventy `^0.8.3` and your report indicates it’s using 0.8.2. I tested with both versions using node 8 and node 10.

Can you try adding this to your package.json scripts and tell me what comes out?

![image](https://user-images.githubusercontent.com/39355/61295852-918b2f00-a79e-11e9-8964-7ea60229483e.png)

`npm run version`

**Comment by remy** [comment]
I'll try a clean install too, see if I can replicate.

It's definitely some kind of race condition.

**Comment by zachleat** [comment]
I guess what I was getting at was if `npm scripts` use npx?

`npx eleventy` works but `eleventy` (via `npm run dev`) may be be using a global version of the package and not the locally installed one.

Per must understanding of `npx` the safest command to do is `npx @11ty/eleventy`.

**Comment by remy** [comment]
Since my other issue was already fixed, I decided to have a go at this bug and made some progress.

There's two things that came out of the debugging: 1) the root cause of the crash and 2) the error handling in 11ty for custom errors is…somehow wrong, I think.

First up, here's the problem that's causing the crash that I was seeing:

```
> Tried to use templateContent too early (./src/articles/13.md) (TemplateContentPrematureUseError):
    TemplateContentPrematureUseError: Tried to use templateContent too early (./src/articles/13.md)
        at Object.get templateContent [as templateContent] (/Users/remy/Sites/clones/eleventy/src/Template.js:412:19)
        at Object.memberLookup (/Users/remy/Sites/clones/eleventy/node_modules/nunjucks/src/runtime.js:255:17)
        at eval (eval at _compile (/Users/remy/Sites/clones/eleventy/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:57:59)
        at iterCallback (/Users/remy/Sites/clones/eleventy/node_modules/nunjucks/src/runtime.js:297:11)
        at next (/Users/remy/Sites/clones/eleventy/node_modules/nunjucks/src/lib.js:280:7)
        at eval (eval at _compile (/Users/remy/Sites/clones/eleventy/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:61:1)
        at htmlToAbsoluteUrls.then.result (/Users/remy/Sites/ffconf/node_modules/@11ty/eleventy-plugin-rss/.eleventy.js:26:7)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
```

Being honest, I don't really understand what it's referring to, and the content the error refers to (consistently this particular article/13.md) [looks pretty benign](https://github.com/leftlogic/ffconf/blob/01b2bd517d8a2e3031c99b4f2a0555290921d893/src/articles/13.md).

The error handling is a little weird too (which was causing the `undefined (undefined):`).

The trigger that starts the error is here: https://github.com/11ty/eleventy/blob/56ec610616ac0f83db6fa336ad88b6ed7b9ece56/cmd.js#L24

```
  process.on("unhandledRejection", (error, promise) => {
    EleventyErrorHandler.error(promise, "Unhandled rejection in promise");
  });
```

The logging in `EleventyErrorHandler.js` is looking a the `promise` object (from above) and looking to print `.message` and `.name` properties, but being a promise, it doesn't have these values.

I'm able to actually capture the error using this code instead:

```
  process.on("unhandledRejection", (error, promise) => {
    promise.catch(error => {
      EleventyErrorHandler.error(error, "Unhandled rejection in promise");
    });
  });
```

Which then shows the real error, but also triggers the `rejectionHandled` handler (a few lines lower in `cmd.js`), so the full stack then adds `A promise rejection was handled asynchronously` - which is a bit weird too.

I'm not sure what the clean solution is, but there's definitely something odd at play here.

To add to this, I was looking at the custom error code and I'm not sure it works as intended, **but** I may just being naïve.

The `TemplateContentPrematureUseError.js` extends `EleventyBaseError.js` [here](https://github.com/11ty/eleventy/blob/56ec610616ac0f83db6fa336ad88b6ed7b9ece56/src/EleventyBaseError.js#L2) but I'm not sure that the `originalError` value is ever passed in - looking specifically at where it's used [here](https://github.com/11ty/eleventy/blob/56ec610616ac0f83db6fa336ad88b6ed7b9ece56/src/Template.js#L415-L417) (again, this might be my misunderstanding of how extendings errors work).

I hope this helps. Happy to (try) to help further.

**Comment by zachleat** [comment]
Did this ever crop up again?

I’m guessing it probably has to do with this:
https://github.com/leftlogic/ffconf/blob/01b2bd517d8a2e3031c99b4f2a0555290921d893/.eleventy.js#L132

You’re probably referencing `templateContent` in there, maybe with one of those spreads `...`?

**Comment by remy** [comment]
It was a pretty persistent problem originally but somehow I got around it in my repo - but I honestly can't remember what I did.

I do know that I added some defensive code to prevent the bad build from deploying using [this]:

    eleventy && npm run redirects && test -e dist/index.html

The test at the end was what prevented the build from deploying in netlify, but I appreciate that's off topic.

Happy for you to close this if you can't replicate at all (though I'd still be a bit wary of the error being swallowed).

**Comment by zachleat** [comment]
Unfortunately going to close this one as stale. Happy to try again if you’re interested in trying out 2.x!
