### ISSUE TITLE
Collection Filter not working with Pagination

### ISSUE THREAD

**Issue by alistairtweedie** [11ty/eleventy#598]
I currently have a Collection called 'Companies.' I found this issue [#411](https://github.com/11ty/eleventy/issues/411#issuecomment-463146701) that helped me order the companies within my collection in alphabetically order. Works great!
```js
//.eleventy.js
eleventyConfig.addCollection('companies', collection => {
      return collection.getFilteredByGlob("**/companies/*.md").sort((a, b) => {
        if (a.data.title > b.data.title) return -1;
        else if (a.data.title < b.data.title) return 1;
        else return 0;
      })
  });
```
However, when I introduce Pagination the filter does not work and the companies revert back to being ordered by their Last Modified date. My `companies.njk` template and `companies.json` are below. 

What am I missing?

```html
---
layout: layouts/base.njk
pagination:
  data: collections.company
  size: 5
  alias: companies
---
```
```json
{
  "layout": "layouts/company.njk",
  "permalink": "companies/{{ pagination.pageNumber + 1 }}/{{ page.fileSlug }}.html",
  "tags": [
    "company"
  ]
}
```

**Comment by meganchoy** [comment]
I'm having an issue similar to this where I am having trouble filtering...

`---
layout: layouts/blog
pagination:
  data: tags
  size: 1
  alias: tax
---`

`{% set list_collection = collections.blogpost[tax.tag] | reverse %}`

where `{{ list_collection | dump }}` gives me an empty list

**Comment by zachleat** [comment]
Unfortunately this issue slipped under the radar—I’m finally circling back through some of the old issues on the tracker but I’d love a confirmation that this old one is still relevant before I start debugging! If I don’t hear anything in the next two weeks, I’ll likely close it as stale—sorry (and thank you!)

**Comment by alistairtweedie** [comment]
Hey @zachleat, this is a super old issue for me. Happy for you to close 👍

**Comment by zachleat** [comment]
Thank you @alistairtweedie!
