### ISSUE TITLE
How to pass template engine options?

### ISSUE THREAD

**Issue by cfviotti** [11ty/eleventy#60]
I'm trying to use eleventy with pug and would like to pass custom render options. I'm asking this because I can't even make it work, as I'd like to use includes with relative paths. Pug throws me this error: 
`Error: the "filename" option is required to use includes and extends with "relative" paths`

**Comment by kleinfreund** [comment]
Can you please provide the section of your code where you're trying to include something?

**Comment by zachleat** [comment]
Looking at https://github.com/11ty/eleventy/blob/master/test/TemplateRenderPugTest.js I think there’s something to this. All of my tests are absolute.

Can you be more specific about what pieces of the API reference you’d like to be exposed? https://pugjs.org/api/reference.html

**Comment by cfviotti** [comment]
@kleinfreund Sure, I might even say it wasn't clear enough for me on how to structure my project and how to use includes and extends properly.

**Here's my project structure:**
![image](https://user-images.githubusercontent.com/6797129/36309735-f5c77ab4-130c-11e8-9340-77b94288e0f1.png)

**This is my .eleventy.js file:**
![image](https://user-images.githubusercontent.com/6797129/36309900-77e33b0a-130d-11e8-9afe-5b17e6254572.png)

And I have a `include section-card.pug` inside the **section-about.pug** file for example. 

The relevant error lines eleventy throws me back are:
```
Eleventy:Template Template.render is bypassing wrapping content in layouts for './src/views/includes/section-about.pug'. +17ms
  Eleventy:Template ./src/views/includes/section-about.pug renderContent() using pug +0ms

Problem writing eleventy templates: 
Error: the "filename" option is required to use includes and extends with "relative" paths
```

**Comment by cfviotti** [comment]
@zachleat I do believe for this case I would need the filename option.

**Comment by zachleat** [comment]
This will be included with Eleventy 0.2.15! Support and tests added 👍 

New Pug features are doc’d here: https://github.com/11ty/eleventy/#template-engine-features allows you to configure any pug compile/render options you want.

**Comment by zachleat** [comment]
@cfviotti I should also note (confusingly enough and frustratingly probably too late to change) that `includes` is relative to your `input` directory and not the current directory.

So it’s looking for includes in `src/views/src/views/includes` there.

**Comment by zachleat** [comment]
@cfviotti I filed an improvement to this in #67.
