### ISSUE TITLE
Passing page.url into a Liquid shortcode fails with Invalid Syntax error

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#600]
```
{% pagedoturlshortcode page.url %}
```

fails due to custom argument parsing written for #364 

![image](https://user-images.githubusercontent.com/39355/60814258-e6092b80-a15a-11e9-84c4-2dc2c5e805bc.png)

Reported by @andybelldesign at https://twitter.com/andybelldesign/status/1148214434709606402?s=20

**Comment by zachleat** [comment]
Shipping in the next version!

**Comment by andybelldesign** [comment]
Nice work mate 🙂
