### ISSUE TITLE
Can't use `page.date.toUTCString()` in Liquid template

### ISSUE THREAD

**Issue by codeinpink** [11ty/eleventy#603]
**Describe the bug**
The docs on using dates in templates (https://www.11ty.io/docs/dates/) suggests using `{{ page.date.toUTCString() }}` to display a UTC time zone date, but when I try to do that it displays `function toUTCString() { [native code] }` instead of the actual date.

**To Reproduce**
1. Attempt to use `{{ page.date.toUTCString() }}` in your template

**Expected behavior**
It should display the date.

**Screenshots**

**Environment:**
 - OS and Version: Ubuntu 16.04.5 LTS
 - Eleventy Version: 0.8.3

**Additional context**
I'm using the default template engine (liquid) but I've also tried using nunjucks.  I also get the same results for `toString()`.  Seems related to https://github.com/11ty/eleventy/issues/447

**Comment by zachleat** [comment]
I was able to reproduce this in Liquid but Nunjucks seems to operate just fine.

**Comment by zachleat** [comment]
Hmm, I’m not sure this is a bug—I don’t think Liquid supports calling functions like this. I will update the documentation to be more accurate—sorry about that!

**Comment by zachleat** [comment]
(The accepted method for this in Liquid is to use a custom filter to output the correct string format for the date )

https://www.11ty.io/docs/filters/

**Comment by zachleat** [comment]
Docs updated! https://www.11ty.io/docs/dates/#dates-off-by-one-day
