### ISSUE TITLE
Programmatically triggering an 11ty rebuild 

### ISSUE THREAD

**Issue by khawkins98** [11ty/eleventy#604]
I've successfully mapped a JS object ([like this](https://www.11ty.io/docs/data-js/#example%3A-exposing-environment-variables)) and that's working smoothly. 

What I'd now like to do is for the 11ty watch to trigger when that javascript changes. 

Conceptual example:

`myData.js`
```js
module.exports = {
  numberOfTweets: somePassedObjectOfTweets.tweetCount
};
```

Then when `somePassedObjectOfTweets` changes, I'd like for the 11ty watch to trigger; sort of something like this:

`.eleventy.js`
```js
Object.observe(somePassedObjectOfTweets, function() {
  trigger11tyWatch();
});
```

Any ideas?

## My workaround

For the time being I'm just doing this:

 `.eleventy.js`
```js
const touch = require("touch");
// https://www.npmjs.com/package/touch
Object.observe(somePassedObjectOfTweets, function() {
   touch('src/site/_data/myJsDataFile.js');
});
```

**Comment by chrisssycollins** [comment]
I'm confused, sorry. Do you need/want to rebuild your site when you post a tweet? 
What would cause the contents of your `myData.js` file to change?

**Comment by khawkins98** [comment]
In this case I have a parallel node process running (component library: fractal) and the object of components is exposed to 11ty via data.js file, however I need 11ty to take note when that object updates. 

The data object is successfully passed on fractal update, however 11ty doesn't trigger its `watch` rebuild. 

So for now it's working by "touching" a watched folder on fractal update. 

It would be great if there was some kind of rebuild function available inside `eleventy.js`

**Comment by khawkins98** [comment]
If that's still not clear, here's my commit with my working `touch` workaround: https://github.com/visual-framework/vf-demo-design-system/commit/69f404d7e35fcbff32f16b44452ec8fc101200d3

**Comment by Ryuno-Ki** [comment]
I'm wondering, whether it's the right approach.
I mean, eleventy is a SSG.
I think, what you're looking for is something, which invokes a command whenever a certain event is received.
I'm pretty sure, that there is such a library.
The command would then trigger a build.

**Comment by chrisssycollins** [comment]
@Ryuno-Ki I agree, @khawkins98 I feel your approach is perhaps trying to use the 11ty config as a task runner. I'd probably use gulp to watch the files then trigger an eleventy build when your files have changed.

**Comment by khawkins98** [comment]
The static build aspect is working fine, but what I'd like to do is extend the local development "watch" style behaviour. Much the same as if a process pulled in a Twitter feed to a local json file, then I'd want eleventy's watch to invoke. 

But in my case it's not a file system that's been updated, but a variable. 

Looking at the code for eleventy there are probably two fundamental things that are stopping this:

- the current watch behaviour is designed for filesystem changes, and I want to observe a data object
- alternatively, I can bypass eleventy's watch and create my own data object observer. But that falls short as eleventy is not structured to allow for easy access to `.restart()`, at least not without locally maintaining my own [`cmd.js`](https://github.com/11ty/eleventy/blob/master/cmd.js) (please do let me know if I'm off there)

That said there are two workarounds that would easily work in my case:

- Export the data object to the file system where 11ty would observe the change
- Carry on with the previously mentioned `touch()`-based hack that triggers the watch event

At any rate, my original ask seems clearly not in scope.

**Comment by khawkins98** [comment]
Updated the title again for future googling.

**Comment by Ryuno-Ki** [comment]
Hm … the other day, I was wondering, whether some ideas could be [stolen from harp.js](https://github.com/sintaxi/harp/blob/d93ef32bd59e80f4e7fb5a6571d54b7bcf1a9fa5/lib/middleware.js), which can be used as middleware (in, e.g., Express.js).

As a more broad concept behind this …
@zachleat Shall I open a new issue for this?
