### ISSUE TITLE
Duplicate object keys in TemplateWriterTest.js

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#615]
Specifically the duplicate keys in the objects in the test, here: https://github.com/MadeByMike/eleventy/blob/master/test/TemplateWriterTest.js#L634 and https://github.com/MadeByMike/eleventy/blob/master/test/TemplateWriterTest.js#L673

cc @MadeByMike

from the excellent #452

**Comment by MadeByMike** [comment]
Hi @zachleat, that was deliberate to test how it handled duplicate keys. Essentially it doesn't if you want to map the same key to multiple outputs you need another passthrough.

I don't know how js treats this. Is it an obsolete test?

**Comment by zachleat** [comment]
The object uses the last one so I don’t think those would be visible to the test.

<img width="236" alt="image" src="https://user-images.githubusercontent.com/39355/61425141-91447e00-a8db-11e9-931f-cee45972d60b.png">
