### ISSUE TITLE
Netlify has something different than my local, but everything is pushed

### ISSUE THREAD

**Issue by nhoizey** [11ty/eleventy#62]
Hi, this is the first time I use Netlify, so I don't know if there's something special that could explain why I see a difference between my local instance of Eleventy and the one on Netlify.

Everything is [pushed on Github](https://github.com/nhoizey/photosynthese.net), I don't have anything different on my computer.

On Netlify ([https://photosynthese.netlify.com/](https://photosynthese.netlify.com/)), I get this homepage:

<img width="980" alt="image" src="https://user-images.githubusercontent.com/78213/36390293-e2caa01a-15a2-11e8-8f94-ced1b7cc2772.png">

On my computer, I get this homepage:

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/78213/36390306-f0dff3b2-15a2-11e8-9c30-55aeb0f8f825.png">

Two contents from the `photos/` folder are not listed.

**Comment by zachleat** [comment]
Hmm, here’s what I see when I clone and run your repo:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/39355/36404823-c3ddca46-15b2-11e8-8c14-57fe57a45f69.png">

Looks like it’s iterating over `collections.photos` and `photos` is coming from `.eleventy.js`:

```
  eleventyConfig.addCollection('photos', function(collection) {
    return collection.getFilteredByGlob('photos/**/*.md')
  })
```

I’m guessing your local copy of eleventy is outdated. Make sure you have 0.2.14 installed to use `getFilteredByGlob`.

**Comment by nhoizey** [comment]
@zachleat I am using 0.2.14: https://github.com/nhoizey/photosynthese.net/blob/master/package.json#L25

**Comment by nhoizey** [comment]
Weeeeell, I didn't change anything apart from stopping Eleventy and http-server for a few hours, and now it works…

Sorry, maybe a caching issue.

**Comment by zachleat** [comment]
Hey, no worries!
