### ISSUE TITLE
Trigger builds via JavaScript API without the cli

### ISSUE THREAD

**Issue by paulshryock** [11ty/eleventy#620]
Is it possible to trigger a build via JavaScript without using the cli _(i.e. `npx eleventy`)_?

I've wrapped Eleventy in an Electron application, I would like to trigger new builds on button click, after updating data via form entry--but I'm not sure how to trigger builds via API without running the cli.

**Comment by paulshryock** [comment]
Possibly relevant:

- https://stackoverflow.com/a/31897900/6079274
- https://stackoverflow.com/a/20643568/6079274
- https://github.com/RIAEvangelist/node-cmd
- http://documentup.com/shelljs/shelljs

**Comment by Ryuno-Ki** [comment]
Have you looked at [cmd.js](https://github.com/11ty/eleventy/blob/master/cmd.js)?

**Comment by paulshryock** [comment]
> Have you looked at [cmd.js](https://github.com/11ty/eleventy/blob/master/cmd.js)?

I hadn't looked at it yet, but I think you're right that it could potentially have what I need. Thanks! If I'm able to trigger builds with some of that code, I'll post an update.

**Comment by indo-dev-0** [comment]
I came here to request this feature so that I can use the step-through debugger.

> Have you looked at cmd.js?

This isn't a very ergonomic solution, as I want to be able to just `require()` the package and be done.  Would a pull request for this functionality be welcome?

**Comment by paulshryock** [comment]
> This isn't a very ergonomic solution, as I want to be able to just `require()` the package and be done. Would a pull request for this functionality be welcome?

Right. I haven't had success triggering builds **from my app** via JavaScript, using something like `require()`. I think it might be possible if I were to include 11ty in my project, not as a dependency, but copied into my source code in its entirety (dependencies and all?), but that seems like silly stupid.

**Comment by zachleat** [comment]
I did post a quick example of this here https://twitter.com/zachleat/status/1167115558552244226 but work is ongoing here for something official

**Comment by kmelve** [comment]
So I got this to run from `.eleventy.js` by calling the enclosing function from a `setTimeout`:

```
/**
 * Set up a listener to rebuild on changes made in Sanity.
 * Add a token to .env.development to rebuild on all changes.
 */
const client = require('./utils/sanityClient')
function preview() {
  const Eleventy = require("@11ty/eleventy");
  let inst = new Eleventy();
  client.listen('*').subscribe(async doc => {
    await inst.init();
    await inst.write();
  })
}
setTimeout(() => preview(), 200)
```

It now rebuilds when the listener register changes via the API.

**Comment by zachleat** [comment]
@kmelve Do you think that `setTimeout` is something we’re doing or how Sanity is doing its thing?

**Comment by kmelve** [comment]
One of my colleagues suggested it is because we have modules/files that’s reference each other. So it has nothing to do with Sanity, or Eleventy, but this: https://nodejs.org/api/modules.html#modules_cycles. 

I think I’ll just bring the preview function into a separate file and run it concurrently from package.json. There’s no reason it has to be in the config file outside of having stuff in one place.

**Comment by indo-dev-0** [comment]
If you do build a normal API, it would be *really* nice if 11ty would produce a stream that could be consumed by Gulp.  As it stands, one must built to a temp directory first....

**Comment by PierBover** [comment]
So @zachleat has this example here:

https://gist.github.com/zachleat/5b5ae0ddadbeba6169f18e5b4aa58a66

Problem is, AFAICT, that the config still comes from a `.js` file.

```
this.config = config.getConfig();
```

https://github.com/11ty/eleventy/blob/master/src/Eleventy.js#L30

In a cloud function this could be a problem since you may need to determine paths dynamically at runtime.

Is there a way to pass the config to the constructor instead?

**Comment by zachleat** [comment]
Note that #136 had an additional 37 votes at time of closing.

> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by blake-mealey** [comment]
For anyone that may still be interested, I've found an answer to @PierBover's question

> So @zachleat has this example here:
> 
> https://gist.github.com/zachleat/5b5ae0ddadbeba6169f18e5b4aa58a66
> 
> Problem is, AFAICT, that the config still comes from a `.js` file.
> 
> ```
> this.config = config.getConfig();
> ```
> 
> https://github.com/11ty/eleventy/blob/master/src/Eleventy.js#L30
> 
> In a cloud function this could be a problem since you may need to determine paths dynamically at runtime.
> 
> Is there a way to pass the config to the `Eleventy` constructor instead?

It seems the `config` property is set in the `Eleventy` constructor but not accessed until `init` is called, so you can create the config yourself and set it directly on the instance before calling init, e.g.:

```js
const Eleventy = require("@11ty/eleventy");

(async function() {
	let inst = new Eleventy();
        inst.config = { /*my custom config*/ };
	await inst.init();
	await inst.write();
})();
```

**Comment by paulshryock** [comment]
@PierBover and @blake-mealey, you can also use the [`setConfigPathOverride()`](https://github.com/11ty/eleventy/blob/v0.11.1/src/Eleventy.js#L179-L192) method before calling `init()`:

```javascript
(async function() {
  const ssg = new Eleventy();
  // Pass a JavaScript file which exports an object:
  ssg.setConfigPathOverride('./config/vendor/eleventy.js');
  await ssg.init();
  await ssg.write();
})();
```

**Comment by zachleat** [comment]
Note that 1.0 will have this functionality too. https://twitter.com/zachleat/status/1358966988203323394

Subscribe to https://github.com/11ty/eleventy/pull/1629

**Comment by zachleat** [comment]
Removing this from the enhancement queue, moving to the 1.0 milestone.
