### ISSUE TITLE
Directory Specific Data Files should traverse up directory hierarchy.

### ISSUE THREAD

**Issue by nhoizey** [11ty/eleventy#63]
I have a deep hierarchy of folders in my top folder `photos/`:
https://github.com/nhoizey/photosynthese.net/tree/master/photos/voyages/asie/hong-kong

I would like to use `getFilteredByGlob` to tell Eleventy every Markdown content in this folder and sub-folders are part of the `photos` collection:

```javascript
  eleventyConfig.addCollection('photos', function(collection) {
    return collection.getFilteredByGlob('photos/**/*.md')
  })
```

But the layout is only applied to the Markdown file ([`test.md`](https://github.com/nhoizey/photosynthese.net/blob/master/photos/test.md)) that is directly in the top level folder.

**Comment by zachleat** [comment]
I’m assuming this is very much related to #62.

**Comment by nhoizey** [comment]
Maybe, indeed, but if `getFilteredByGlob()` is not working, why do I have the right layout for `test.md`?

Is `photos/**/*.md` supposed to match any Markdown file in any sub level of the `photos/` folder?

**Comment by nhoizey** [comment]
Definitely not related to #62, it seems…

**Comment by zachleat** [comment]
Are you comfortable attaching your `DEBUG=Eleventy*` output? Maybe also your `npx eleventy --version` too?

**Comment by zachleat** [comment]
When I checked out your project from GitHub and ran it locally, `photos/**/*.md` did indeed match all the markdown files in any sublevel of `photos/`. And this is what Netlify was exhibiting in #62 too.

**Comment by nhoizey** [comment]
Both on local and on Netlify, it finds the content and shows it in the list in the home page, but it doesn't use the template for the page:
https://photosynthese.netlify.com/photos/voyages/asie/hong-kong/symphony-of-lights-from-the-peak/

**Comment by nhoizey** [comment]
Here is the `DEBUG=Eleventy*` log
[build.log](https://github.com/11ty/eleventy/files/1745596/build.log)

**Comment by nhoizey** [comment]
I think I've mixed 2 features, `getFilteredByGlob` to identify collection items and "[Directory Specific Data Files](https://github.com/11ty/eleventy/blob/master/docs/data.md#template-and-directory-specific-data-files)".

I thought adding this [/photos/photos.json](https://github.com/nhoizey/photosynthese.net/blob/master/photos/photos.json) file would be enough to define the layout for any content inside the `photos/` folder, including sub-folders. But it looks like it only works for content directly inside the same folder as the `.json` file.

Maybe any content file could search for its layout in its folders hierarchy, like how `.htaccess` works…

**Comment by zachleat** [comment]
Oh, yes, that is what I’d expect to happen. Although your assumption about the feature would be a welcome change. Going to switch this to be an Enhancement request.

**Comment by nhoizey** [comment]
Awesome enhancement, thanks!
