### ISSUE TITLE
0.9.1-beta: njk include path error

### ISSUE THREAD

**Issue by octoxalis** [11ty/eleventy#633]
Trying the beta release.

(_Using cssmin and jsmin filters to directly generate all my minified css and js files, a very useful feature which let me add, remove an manage my static assets inside 11ty -- see Documentation QUICK TIP #001 for an inline filter_).

Having an issue with `njk include` path, which is not anymore relative to` _includes/layouts` folder as it was in **0.8.3** and **0.7.1** releases (something I thought a bit weird in Nunjucks). `include` path is now relative to the template path itself and breaks my build.

template file: `${SRC_DIR}/static_minify/scripts/_annotations_setup_.njk`
included file: `${SRC_DIR}/includes/static/scripts/setup_annotations.js`

> _annotations_setup_.njk

```
{% set js %}{% include "../static/scripts/setup_annotations.js" %}{% endset %}
```
Build output:

 ` Error: template not found: ${SRC_DIR}/static_minify/static/scripts/setup_annotations.js`

**Comment by zachleat** [comment]
Hey @octoxalis I’m not sure I understand your report here.

Is `${SRC_DIR}/includes/static/scripts/setup_annotations.js` in your _includes directory? What is your includes/layouts directory setup here?

From what I understand, `{% set js %}{% include "../static/scripts/setup_annotations.js" %}{% endset %}` would not have worked in earlier versions either, as it would be searching for `${SRC_DIR}/static/scripts/setup_annotations.js`.

In 0.9.0-beta.1 it searches for `${SRC_DIR}/static_minify/static/scripts/setup_annotations.js` and `${SRC_DIR}/static/scripts/setup_annotations.js` which both don’t exist.

**Comment by octoxalis** [comment]
Well, I reorganized my `source` folder another (more logical) way and I've no more error. **Thanks**.

**Comment by zachleat** [comment]
Ah, okay great. Closing this one out for now.
