### ISSUE TITLE
#551 fix

### ISSUE THREAD

**Issue by octoxalis** [11ty/eleventy#634]
With 11ty **0.9.1-beta** release to try, I had a glance at the source code to find a fix to my [#551](https://github.com/11ty/eleventy/issues/551) issue .

Removing the empty template content test ( `if (!this._templateContent)` ) in `templateContent` getter function removes the error ( **Template.js** lines 450-459).
```
get templateContent() {
  if (!this._templateContent) {
    throw new TemplateContentPrematureUseError(
      `Tried to use templateContent too early (${this.inputPath} page ${this.pageNumber})`
    );
  }
  return this._templateContent;
}
```
 Actually, is this content test necessary? Is there a reason to not simply return `this._templateContent`?

**Comment by zachleat** [comment]
This error is required because it means that `templateContent` was referenced in a template before it was set by Eleventy! Though, hmm—maybe it needs to be `!== undefined` instead? I can make that change to see if it helps you.

**Comment by zachleat** [comment]
If this doesn’t help you (on 0.9.0-beta.2), I’ll need a reduced test case to move forward here!

**Comment by octoxalis** [comment]
The `undefined` test (`if (this._templateContent === undefined )` ) is... fine!
I tried it and I've no more `TemplateContentPrematureUseError`.

**Comment by zachleat** [comment]
Awesome! Thank you for testing!
