### ISSUE TITLE
Templates being rendered multiple times?

### ISSUE THREAD

**Issue by jakearchibald** [11ty/eleventy#638]
**Describe the bug**

It seems like, by accessing the `templateContent` of an item in a collection, within a nunjucks include, it causes the parent template to be built twice.

**To Reproduce**

I have a helper like `{% outputCSS page.url, cssURL %}` which outputs a `<link>` for the CSS, but will output nothing if it's seen this page url + CSS url combination before. The idea is to dedupe stylesheets.

This works, until I add `{{ faq.templateContent | safe }}` within a nunjucks include. `faq` is an item in `collections.faqs`.

At this point, all my CSS disappears, because it hits the 'duplicate' path. It seems like it's doing a full second pass on the page.

If this doesn't ring any bells, I'll try to create a reduced example.

If this multi-pass build is necessary, it'd be create to have some sort of hook to know when a page is being built, so I can 'reset' the deduper.

**Environment:**
 - OS and Version: Mac 10.14.5
 - Eleventy Version: 0.8.3

**Comment by jakearchibald** [comment]
If anyone else encounters the same problem, here's my workaround:

I put `{%- pageStart page -%}` at the very start of my main template. Then I can use the shortcode as a kind of "page start" callback:

```js
eleventyConfig.addShortcode('pageStart', page => {
  // Reset any per-page state here
  return '';
});
```

**Comment by zachleat** [comment]
Eleventy builds a content dependency map based on what we know about the content (tags, collections, other Eleventy specific features) to attempt to render templates with references to `templateContent` in the correct order.

Unfortunately, per our multiple template language support we do not have a window into some of the internals of the different templating engines ahead of time (variable usage being the big one) so we rely on a two-pass algorithm for `templateContent` that you can see here: https://github.com/11ty/eleventy/blob/master/src/TemplateMap.js#L353

**Comment by zachleat** [comment]
The other piece here is Eleventy layouts.

Specifically the leaf template is built and the render is saved. Then for every layout up the chain, another render takes place that injects the previously saved render.

`leaf.md` renders, injected into the render of `first-layout.njk`, which is then saved and injected into the render of `second-layout.njk` and so on.

When do you need this reset to take place?

**Comment by jakearchibald** [comment]
I guess I'm kinda relying on the template to be rendered sequentially, which it kinda is because of how I'm using nunjucks inheritance rather than 11ty for the important bits.

If I wasn't, it'd be back to the drawing board for my CSS deduping solution.

I guess everything here is behaving as intended, and maybe I need to go for some kind of post-processing step for the CSS thing. Thanks for talking it through.

**Comment by zachleat** [comment]
Ah hmm, for the record I am open to adding some kinda hook to know when the template render starts. I just need to understand where it might go.

The thing that I’m a little hung up on is when you add a CSS reference tied to a page.url, why does it need to reset this state? The second render should be the same CSS reference right? Using a Set should de-dupe these?

**Comment by jakearchibald** [comment]
> The thing that I’m a little hung up on is when you add a CSS reference tied to a page.url, why does it need to reset this state? The second render should be the same CSS reference right? Using a Set should de-dupe these?

Right, but if you rerender a page without emptying the set, the second render won't have any `<link>`s, because it sees them all as duplicates.

**Comment by zachleat** [comment]
Oh oh you’re littering the link’s throughout your content? If so, this makes more sense now.

If you put them in your layout (doesn’t necessarily need to be in the `head`, could be anywhere in the `body`) like https://github.com/zachleat/eleventy-sample-css-manager/blob/master/_includes/layout.11ty.js (using https://github.com/zachleat/eleventy-sample-css-manager/blob/master/_includes/css.js) you wouldn’t need to worry about two components adding the same `<link>`.

Does that make sense? and does that make sense for your use case?

**Comment by jakearchibald** [comment]
Yeah, makes sense, although I'm experimenting with littering the links throughout content right now.

Fwiw, I tried to make the switch to JS templates but ran into the lack of includes (https://github.com/11ty/eleventy/issues/625) which we're using a lot in nunjucks to make components pluggable and composable.

**Comment by Ryuno-Ki** [comment]
Was that your blog Jake?
I've read somewhere that adding `<link>`s to the `<body>` could help optimising the critical path / rendering.
But I was wondering how to catch duplicates.
For my website, I currently declare dependencies on CSS and JS in the Frontmatter of a content file.
Right now I just iterate of the list, but could imaginesome deduping there.
Think rendering hooks of WordPressin this regard
