### ISSUE TITLE
How to I reference HTML files from an iframe

### ISSUE THREAD

**Issue by coreybruyere** [11ty/eleventy#659]
I have a few html files I need to dump into iframes. Couldn't find much in the docs. Should it be placed in static? If so, how would I go about referencing those files from a iframe in `pages/home.md` from an iframe?

**Comment by paulshryock** [comment]
What does your project file structure look like?

**Comment by zachleat** [comment]
if your input file is `pages/page1.md` then you’d put the output path from that into another file’s html: `<iframe src="pages/page1/index.html">`. If you’ve changed the default output path using `permalink` the `src` attribute would match the `permalink` value instead.

Does that help?

**Comment by coreybruyere** [comment]
@zachleat - That makes sense thanks 🙏
