### ISSUE TITLE
Eleventy should fail when using unknown options

### ISSUE THREAD

**Issue by kleinfreund** [11ty/eleventy#66]
Running `eleventy` always tries to process the current directory. This might not be intended. Users might just confirm their Eleventy version after upgrading (with the currend working directory often being the home directory after upgrading things) or have a typo in an argument. For example:

```
eleventy -v
```

I think, Eleventy should fail when any unknown option is provided and give an explanation.

Just an example:

```
phil@MONDBASIS in ~/Downloads
👻 jekyll -x
jekyll 3.7.2 | Error:  Whoops, we can't understand your command.
jekyll 3.7.2 | Error:  invalid option: -x
jekyll 3.7.2 | Error:  Run your command again with the --help switch to see available options.
```

**Comment by zachleat** [comment]
Good idea! I like it 👍

Fail fast
