### ISSUE TITLE
How do I build multiple sites from a single install without folder permalinks?

### ISSUE THREAD

**Issue by paulshryock** [11ty/eleventy#662]
I have multiple sites in a single Eleventy install, setup like this:

```
.eleventy.js
--/src
----/site-1
------/pages
--------home.md
--------about.md
----/site-2
------/pages
--------home.md
--------about.md
```

My Eleventy build process puts everything inside `/build`, and my permalinks are such that the files come out like this:

```
--/build
----/site-1
------index.html
------about/index.html
----/site-2
------index.html
------about/index.html
```

I'm serving `/build/site-1` and `/build/site-2` as 2 independent websites on separate domains. But all page `url`s in `site-1` begin with `/site-1` and all page `url`s in `site-2` begin with `/site-2`.

This means that all the links are broken, since they're basically trying to get to `/build/site-1/site-1/index.html` and `/build/site-2/site-2/index.html`, which don't exist.

I would like all of the links in each site to not include the prepended `/site-1` or `/site-2`, but instead start with `/`.

Is this possible?

**Comment by paulshryock** [comment]
I decided to use an environment variable to state which site I want Eleventy to build:

**`.env`:**

```bash
SITE='site-1'
```

And I wrote a script that tells Eleventy to ignore all sites _except_ for the site from the environment variable, by automatically adding them to my `.eleventyignore` file.

**`.eleventyignore`:**

```bash
src/site-2/
```

Then I added npm scripts with custom outputs for each site:

**`package.json`:**

```javascript
{
  "scripts": {
    "eleventy": "npx eleventy",
    "eleventy:site-1": "npx eleventy --output=build/site-1",
    "eleventy:site-2": "npx eleventy --output=build/site-2"
  }
}
```

So now I can leave my directory structure the way it was:

```
.eleventy.js
--/src
----/site-1
------/pages
--------home.md
--------about.md
----/site-2
------/pages
--------home.md
--------about.md
```

and I can leave permalinks alone, without having to prepend `/site-1` or `/site-2`. And when I update the environment variable and build each site, all site links work correctly when served from each directory (`/build/site-1` and `/build/site-2`).

**Comment by hankhero** [comment]
Thanks for the writeup, but shouldn't this be supported in a better way? It must be a fairly common request?

**Comment by pdehaan** [comment]
Another possibility is just specify separate input and output folders (either via CLI arg or via custom config files &mdash; versus trying to manage custom .eleventyignore file). I created a pretty rough prototype at https://github.com/pdehaan/11ty-662

It seems like it should be easy enough to share data files between sites, but sharing layouts might be trickier.

**Comment by dekadentno** [comment]
Did anyone managed to find a nice looking solution for this?

**Comment by bnoctis** [comment]
I've made a prototype multisite builder plugin, https://github.com/bnoctis/eleventy-multisite

**Comment by paulshryock** [comment]
> I've made a prototype multisite builder plugin, https://github.com/bnoctis/eleventy-multisite

Awesome! Great idea for a plugin.

**Comment by cclsn** [comment]
@bnoctis Do you have an example repository where the plugin is implemented? I struggle to get it working with the instructions in the readme file.

**Comment by bnoctis** [comment]
@cclsn No, and don't plan to, not using 11ty at the moment. Maybe should add an unmaintained notice. Btw, a question regarding the plugin may better suit its own place.
