### ISSUE TITLE
Setting --output=. prevents any templates from being found

### ISSUE THREAD

**Issue by mlibby** [11ty/eleventy#663]
Issue: when I set `--output=.` my template is not processed

I have `index.pug` template file in the `pug` directory and I want my .html outputs to go to the project directory.

From the project directory execute:
`DEBUG=Eleventy* eleventy --input=pug --output=. --formats=pug`

Doing this I would expect the file `index.html` to be created in the project directory, but instead no templates are processed.

`Processed 0 files in 0.08 seconds`

If I change `--output=.` to `--output=_site`, the template file is found and processed. But, of course, the output is in `_site\index.html` which is fine for building, but not going to work well if I 

From the debugging info I believe the problem is that when `output` is set to `.` the list of "Searching for" directories includes `!./**` -- I think this excludes all files in the project directory recursively. If I use `--output=_site` this entry is replaced with `!./_site/**`

`Eleventy:EleventyFiles Searching for: [ './pug/**/*.pug', '!./logs', '!./*.log', '!./npm-debug.log*', '!./yarn-debug.log*', '!./yarn-error.log*', '!./pids', '!./*.pid', '!./*.seed', '!./*.pid.lock', '!./lib-cov', '!./coverage', '!./.nyc_output', '!./.grunt', '!./bower_components', '!./.lock-wscript', '!./build/Release', '!./node_modules/**', '!./jspm_packages', '!./typings', '!./.npm', '!./.eslintcache', '!./.node_repl_history', '!./*.tgz', '!./.yarn-integrity', '!./.env', '!./.next', '!./**', '!./pug/_includes/**', '!./pug/_data/**' ] `

**Comment by zachleat** [comment]
This is likely a duplicate of #186, I believe?

**Comment by mlibby** [comment]
I think it is. I tried searching for existing issues but missed that one.
