### ISSUE TITLE
Decouple 11ty.js rendering from Eleventy core

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#668]
Right now JavaScript templates are coupled too tightly to the core project and migration off of Eleventy would be made more difficult because of this.

Even though it’s just JavaScript, we should separate as much of this “template language” out of the core so that it could be used without Eleventy.

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by b3u** [comment]
Also, if I'm understanding this correctly, install could be much easier if the user didn't need to download every single templating engine. That could be as easy as moving them to peer dependencies.
