### ISSUE TITLE
Upgrade markdown-it from 8.x to latest major version

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#669]
updates CommonMark spec from 0.28 to 0.29: https://spec.commonmark.org/0.29/changes.html

via https://github.com/markdown-it/markdown-it/blob/master/CHANGELOG.md#900--2019-07-09

**Comment by devliber** [comment]
Maybe it should be upgraded to 10.x:
https://www.npmjs.com/package/markdown-it

---

For example, with the default _markdown-it_ from eleventy and _markdown-it-attrs_ I get the `Cannot read property 'attrPush' of undefined` error ([similar issue](https://github.com/arve0/markdown-it-attrs/issues/90) here), when I try to render a link that opens in new tab in Markdown:

`[Google](http://google.com){target="blank"}`

For now to fix this I'm importing the 10.x version of _markdown-it_ in _package.json_ using:

    "devDependencies": {
      "@11ty/eleventy": "^0.10.0-beta.1",
      "markdown-it": "^10.0.0",
      "markdown-it-attrs": "^3.0.1"
    }

**Comment by valtlai** [comment]
Markdown-it v12 was just [released](https://github.com/markdown-it/markdown-it/blob/master/CHANGELOG.md). Maybe update for Eleventy 1.0?

**Comment by binyamin** [comment]
"...was _just_ released" You're not kidding!
![image](https://user-images.githubusercontent.com/39805353/96047090-92e45500-0e42-11eb-9d14-cc56c8a68fef.png)

**Comment by binyamin** [comment]
@zachleat From looking at the changelog, there don't seem to be any breaking changes.

**Comment by zachleat** [comment]
Upgraded!

**Comment by zachleat** [comment]
For the record, Eleventy v0.12.0 had markdown-it 10 and Eleventy v1.0.0 has markdown-it 12

**Comment by zachleat** [comment]
For the record:
* v0.10.0 has `markdown-it` 8
* v0.11.0 has `markdown-it` 10
* v1.0.0 has `markdown-it` 12

I think this issue actually belonged in the v0.11.0 milestone? 😱
