### ISSUE TITLE
--host command line param

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#671]
Trying to make these extra instructions unnecessary on Forestry https://forestry.io/docs/previews/instant-previews/#network-details

**Comment by Ryuno-Ki** [comment]
Are there more places needed or is it only https://github.com/11ty/eleventy/blob/098f6c8b6d2b0738cd8852cf2feaa7fdaa5b5315/src/EleventyServe.js#L65 which would need an update?
(Plus, https://github.com/11ty/eleventy/blob/6e294bd7160d44b400810bab84273336009c99db/cmd.js#L39 most likely).

Would you accept PRs?

**Comment by zachleat** [comment]
I don’t remember what this is and the forestry link is broken 😅 Does anyone else recall?

> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by DirtyF** [comment]
I'm not sure I remember either, I _think_ it was when you needed to tweak BrowserSync settings in your Eleventy config file, but that doesn't necessary anymore now, so good call Zach!

**Comment by zachleat** [comment]
Ah in that case I’ll take it out of the queue 😅

**Comment by Ryuno-Ki** [comment]
I don't have to remember.
They are using GitHub :grimacing: 

https://github.com/forestryio/forestry.io/blob/ed428c2839a062920eff18ceac62b6b2476e1756/hugo/content/docs/previews/instant-previews.md#network-details

```
Network Details

{{% warning %}} Your preview needs to run on port 8080 and bind to all network interfaces on 0.0.0.0. {{% /warning %}}

The default command for any NodeJS-based static site generator should be added as an npm script in the package.json.

{{% code_tabs %}} {{% tab "Hugo" %}}

hugo server --renderToDisk --port 8080 --bind 0.0.0.0

{{% /tab %}} {{% tab "Jekyll" %}}

bundle exec jekyll serve --port 8080 --host 0.0.0.0

{{% /tab %}} {{% tab "VuePress" %}}

vuepress dev --port 8080 --host 0.0.0.0

{{% /tab %}}

{{% tab "Gatsby" %}}

gatsby develop -p 8080 -H 0.0.0.0

{{% /tab %}}
{{% tab "Gridsome" %}}

gridsome develop

{{% /tab %}} {{% tab "Eleventy" %}}

eleventy --serve --port 8080 --output=dist

{{% /tab %}} {{% /code_tabs %}}

{{% tip %}} Eleventy: to tell BrowserSync to bind to 0.0.0.0, add the following in your Eleventy configuration file:

/* Forestry instant previews */
if( process.env.ELEVENTY_ENV == "staging" ) {
  config.setBrowserSyncConfig({
    host: "0.0.0.0"
  });
}

Don't forget to set ELEVENTY_ENV environment variable to staging in the preview settings. {{% /tip %}}
```

**Comment by zachleat** [comment]
A ha—awesome, thanks for tracking that down!

In that case I’m happy to remove from the enhancement queue since an existing solution works and it’s no longer on their docs

**Comment by DirtyF** [comment]
The beauty of Git-based content management will never cease to impress me @Ryuno-Ki 😄

**Comment by Ryuno-Ki** [comment]
You're welcome.

I can still see the `enhancement` label, though.

**Comment by zachleat** [comment]
Removing `needs-votes` removes Closed issues from the Enhancement queue (they need both `needs-votes` and `enhancement` labels to be in the queue)
