### ISSUE TITLE
Outputting tags to a post

### ISSUE THREAD

**Issue by pdkaizer** [11ty/eleventy#679]
In my front matter for a post I have tags for example:
tag: inspiration, design, design-inspiration
I want to output those into the compiled post html page. 
I am using Nunjuks as my templating engine.

**Comment by lideo** [comment]
```
---
tags: ['inspiration', 'design', 'design-inspiration']
---
```

And then in your template you could do something like this:

```
<ul>
    {% for tag in tags %}
        <li>{{ tag }}</li>
    {% endfor %}
</ul>
```
More in the documentation: https://www.11ty.io/docs/collections/#tag-syntax

Would this work?

**Comment by Ryuno-Ki** [comment]
Note that you can write them also as

```yml
---
tags:
  - inspiration
  - design
  - design-inspiration
---
```

in the frontmatter.
