### ISSUE TITLE
Access collections using bracket notation

### ISSUE THREAD

**Issue by hacknug** [11ty/eleventy#680]
**Is your feature request related to a problem? Please describe.**
I'm trying to create an include that renders the navigation for a given collection.

This collection is contextual and linked directly to the one and only tag each page is set to. `tags[0]` holds the name of my collection eg: `apples`.

I can access `collections.apples` with no issues (as expected) but I can not write `collections[ "apples" ]` (nor `collections[ tags[0] ]`, of course).

**Describe the solution you'd like**
I'd like to be able to use bracket notation to access collections as exposed.

**Describe alternatives you've considered**
Using a shortcode that takes `tags[0]` as an argument would solve my issue if I was able to access all collections inside the shortcode function (maybe this is already possible and I've missed it?).

**Additional context**
Ended up adding a shortcode that takes `collections` and `tags[0]` as arguments so I could search and replace with a regex.

**Comment by pieterbeulque** [comment]
What renderer are you working with?

**Comment by hacknug** [comment]
Liquid. Sorry, forgot to mention that 😅

**Comment by zachleat** [comment]
Looks like there are some limitations with Liquidjs here.

I added a bunch of tests here, you can have a look: https://github.com/11ty/eleventy/blob/master/test/TemplateRenderLiquidTest.js#L980

The ones prefixed with `test.skip` are failures.

The short answer here is that you need to remove your spaces around your quoted strings. `collections["apples"]` works but `collections[ "apples" ]` fails.

Also `test[ref]` works but `test[ref[0]]` fails. You could probably work around this by assigning `ref[0]` to a new value before you use it.

This might improve when the liquid upgrade ships #469. I’ll try to unskip the tests when that happens.
