### ISSUE TITLE
Could not resolve pagination key in template data: globalDataSet.myData

### ISSUE THREAD

**Issue by Sinevia** [11ty/eleventy#690]
**Describe the bug**
Following the Pagination page example with data file fails.

Problem writing Eleventy templates: (more in DEBUG output)
> Could not resolve pagination key in template data: globalDataSet.myData

`Error` was thrown:
    Error: Could not resolve pagination key in template data: globalDataSet.myData

**To Reproduce**
**globalDataSet.json**
```
{
    "myData": [
      "item1",
      "item2",
      "item3",
      "item4"
    ]
  }
```

**page.html**
```
---
pagination:
  data: globalDataSet.myData
  size: 1
---
<ol>
{%- for item in pagination.items %}
  <li>{{ item }}</li>
{% endfor -%}
</ol>
```

**Expected behavior**
Build pagination

**Environment:**
 - OS and Version: Linux Mint 19.2
 - Eleventy Version 0.91

**Comment by whaleen** [comment]
I'm experiencing the same. Following that same example. latest version of 11ty. Using a fresh install of eleventy-base-blog.

**Comment by pdehaan** [comment]
@whaleen Interesting. What OS are you using?

I just tried a fresh install of eleventy-base-blog and it seemed to compile on macOS Catalina (10.15.3) without any issues:

```sh
% git clone https://github.com/11ty/eleventy-base-blog.git my-blog-name
Cloning into 'my-blog-name'...

% cd $_
% npm i

% npm run build

> eleventy-base-blog@5.0.2 build /Volumes/Dev/github/pdehaan/tmp/my-blog-name
> eleventy

Writing _site/sitemap.xml from ./sitemap.xml.njk.
Writing _site/feed/feed.xml from ./feed/feed.njk.
Writing _site/feed/.htaccess from ./feed/htaccess.njk.
Writing _site/posts/secondpost/index.html from ./posts/secondpost.md.
Writing _site/404.html from ./404.md.
Writing _site/posts/index.html from ./archive.njk.
Writing _site/page-list/index.html from ./page-list.njk.
Writing _site/index.html from ./index.njk.
Writing _site/tags/index.html from ./tags-list.njk.
Writing _site/tags/number-2/index.html from ./tags.njk.
Writing _site/posts/fourthpost/index.html from ./posts/fourthpost.md.
Writing _site/posts/firstpost/index.html from ./posts/firstpost.md.
Writing _site/about/index.html from ./about/index.md.
Writing _site/posts/thirdpost/index.html from ./posts/thirdpost.md.
Writing _site/tags/second-tag/index.html from ./tags.njk.
Writing _site/tags/another-tag/index.html from ./tags.njk.
Copied 2 items / Wrote 16 files in 0.44 seconds (27.5ms each, v0.10.0)
```

**Comment by whaleen** [comment]
@pdehaan roughly the same set-up as you. Thanks for looking into it. 

After your response I went to check  on what @Sinevia originally posted to try it again to confirm. They posted the example that they tried from  https://www.11ty.dev/docs/pagination/#paginate-a-global-or-local-data-file.

They had formatted the JSON correctly which I didn't catch the first time I read their issue. 

However, I found that the formatting of the JSON when copied and pasted from the 11ty docs would not fly and may be why they were getting the same error I did. Perhaps they were running the copied version from the docs.  Can't say. This is why my attempt failed. Copy and pasting from 11ty docs. 

I added quotes to myData as you can see here:

```
{
   "myData":[
      "item1",
      "item2",
      "item3",
      "item4"
   ]
}
```

Works a charm. 

11ty docs have it this way:

```
{
  myData: [
    "item1",
    "item2",
    "item3",
    "item4"
  ]
}
```
Which didn't work for me, and maybe @Sinevia

**Comment by pdehaan** [comment]
Good catch, that isn’t valid JSON. I’ll submit a PR to the 11ty-docs repo in the morning. :+1:

**Comment by Sinevia** [comment]
Good job @pdehaan Thank you
