### ISSUE TITLE
Expose webhook during serve for use with external data

### ISSUE THREAD

**Issue by mattwaler** [11ty/eleventy#691]
**Is your feature request related to a problem? Please describe.**

There is no easy way to trigger an update / rebuild during the serve command when external data changes.

This would be extremely useful in two ways:
- Once external webhooks are configured, would trigger a rebuild/reload locally when content changes (better DX overall)
- Would allow developers to create a "staging" site on another server that is constantly rebuilding with the newest content for preview before triggering a production build

**Describe the solution you'd like**

It would be awesome if the --serve command exposed a webhook that would trigger a rebuild, similar to when actual files change. Something like `{url}/__rebuild`

**Describe alternatives you've considered**

Any alternative would be awesome if it accomplished the same goal, allowing an external webhook to trigger a rebuild.

**Comment by antgel** [comment]
@mattwaler This was a while ago, but why did you close it? I've been looking for something like this for Strapi / 11ty local development and haven't found anything (maybe I've been looking in the wrong places).

**Comment by antgel** [comment]
I think https://github.com/11ty/eleventy/pull/3085 and https://github.com/11ty/eleventy-dev-server/pull/70 should help with this, if anyone is reading and interested.
