### ISSUE TITLE
Is it possible to generate the html directly without index file?

### ISSUE THREAD

**Issue by rawaludin** [11ty/eleventy#694]
What I learned is the the current generate flow is to use folder name as post title and add index.html inside it.

Eg. generate `/2019/01/11/my-post/index.html`

Is it possible to just generate `/2019/01/11/my-post.html` ?

Thanks!

**Comment by danfarrow** [comment]
@rawaludin this might help https://www.11ty.io/docs/data/#filepathstem

**Comment by danfarrow** [comment]
@rawaludin ...if you're starting a new project however you should be aware that [there are good reasons for this default behaviour](https://www.11ty.io/docs/permalinks/#cool-uris-don%E2%80%99t-change)!

**Comment by chrisssycollins** [comment]
Assuming you have a  `_posts` dir create a file in that called `_posts.json`. 

Add the following:

```json
{
  "tags": "posts",
  "permalink": "/{{ page.date | date: '%Y/%m/%d' }}/{{ title | slug }}.html"
}
```

This will be the master boilerplate for files within that directory.

**Comment by rawaludin** [comment]
Thanks all!
