### ISSUE TITLE
Unexpected output from getting started tutorial when using Powershell

### ISSUE THREAD

**Issue by StarfallProjects** [11ty/eleventy#702]
**Describe the bug**
Working through the getting started tutorial, it does not seem to parse index.html correctly.
Instead of a webpage, I get the html printed as text.

**To Reproduce**

1. Work through the getting started tutorial up to [here](https://www.11ty.io/docs/getting-started/#step-5-gaze-upon-your-templates) **in Powershell**
2. Run npx @11ty/eleventy --serve
3. Visit http://localhost:8080/

**Expected behavior**
For a webpage to display just "hi"

**Screenshots**
![image](https://user-images.githubusercontent.com/10284570/65348848-ff5a3980-dbd9-11e9-8645-3c4d2b410bf3.png)

![image](https://user-images.githubusercontent.com/10284570/65349361-1ea59680-dbdb-11e9-9004-308da4e640b5.png)

![image](https://user-images.githubusercontent.com/10284570/65349376-282efe80-dbdb-11e9-84fc-295475aa2697.png)

**Environment:**

- Windows 10
- Eleventy 0.9.0
- Browser is Google Chrome, and am running in the terminal in VS Code (Powershell 5.1)

**Additional**
I deleted both index.html (source and built), and tried creating my own manually and typing the html into the file (instead of using echo), and this worked fine. I then tried in git bash, and it also worked (using echo to create the file exactly as in the tutorial). According to [this StackOverflow answer](https://stackoverflow.com/questions/17623644/what-is-the-difference-between-echo-and-write-host-in-powershell/17623902#17623902), echo in Powershell is aliased to [Write-Output](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-output?view=powershell-5.1) I assume the source of the problem lies somewhere in the behaviour of Write-Output.

**Suggestion**
Either include alternative commands for Powershell, or advise users to work in Bash (git bash on Windows seems fine)

**Comment by koutbo6** [comment]
I managed to reproduce this using the following environment:
- windows 10
- eleventy 0.10.0
- node.js 12.16.1

I think the problem is related to the character encoding from the tutorial website, specifically [step 4 of getting started](https://www.11ty.dev/docs/getting-started/#step-4-create-some-templates)

If you copy and paste the lines to the command line, it will produce the extra characters seen here, might be some hidden characters related to formatting?. I managed to reproduce this using powershell, git bash, and node.js shell (cmd).

When I deleted README.md and index.html and manually typed them in vscode, everything works fine.

**Comment by squalrus** [comment]
Also just experienced this -- thanks for pointing out the encoding!

JFYI (for this or any future encoding issue you may have 😁), there is a way to change the encoding in VS Code (and other IDEs) by clicking the file's encoding, selecting "Save with Encoding", and setting the appropriate value.

![image](https://user-images.githubusercontent.com/1166426/104130125-ee2fc180-5323-11eb-8549-f0dccc274d11.png)

![image](https://user-images.githubusercontent.com/1166426/104130091-add04380-5323-11eb-9ccc-841aaf1d722b.png)

![image](https://user-images.githubusercontent.com/1166426/104130097-b88ad880-5323-11eb-87e9-d0bd8cf98fc0.png)

**Comment by zachleat** [comment]
Howdy! I know I’m super late here but the answer for others is also reported here: https://github.com/11ty/eleventy/issues/1340#issuecomment-766194997

Upvote https://github.com/11ty/eleventy/issues/2323 to add a warning to core
