### ISSUE TITLE
Cannot programmatically set collection items as permalink: false

### ISSUE THREAD

**Issue by kittee** [11ty/eleventy#705]
**Describe the bug**

I used to be able to programmatically set collection items as `permalink: false` in v0.7.1, but as of v0.9.0, this no longer works.

**To Reproduce**

Create a page in a collection. Example:

`/articles/new-post.md`
```markdown
---
title: My New Post
tags: article
---
```

Set permalink to false in `.eleventy.js`

```js
eleventyConfig.addCollection("articles", function(collection) {
  return collection.getFilteredByTag("articles").map(function(article) {
    article.data.permalink = false;

    return article;
  });
});
```

In v0.7.1, this worked to prevent templates from publishing. However, as of updating to v0.9.0, this no longer works.

On the other hand, `permalink: false` still works when setting the attribute in the template itself, like so:

`/articles/new-post.md`
```markdown
---
title: My New Post
tags: article
permalink: false
---
```

I have an entire collection that I don't want pages for, and it was nice when I could do this in `.eleventy.js` and kept things DRY.

**Expected behavior**

When I set a template's permalink to false, whether in the template itself or in `.eleventy.js` before pages are generated, I expect it to not publish a page.

**Environment:**
 - OS and Version: macOS Mojave v10.14
 - Eleventy Version: v0.9.0

**Comment by jeromecoupe** [comment]
Setting `permalink` to `false` for a whole collection seems to work for me using directory data files. Does it work for you if you create an `articles.json` file in your articles directory ?

```json
{
  "permalink": false
}
```

**Comment by zachleat** [comment]
I’d also recommend Eleventy Computed Data if you need something a little bit more advanced. https://www.11ty.dev/docs/data-computed/

One thing we could here is add some warning or messaging if you try to set these special properties in Eleventy at the wrong time. I’d guess that most of the props listed here https://www.11ty.dev/docs/data-configuration/ wouldn’t be available for setting in `addCollection` like that.

**Comment by zachleat** [comment]
Just one more super-late look at this—I don’t agree with the premise of this one (even if it worked before). We don’t want `article.data.permalink` modifications to affect the root template’s data cascade upstream!

But again, the Computed Data feature should be where you want to start here
