### ISSUE TITLE
Missing direct TypeScript dependency in package.json

### ISSUE THREAD

**Issue by TigersWay** [11ty/eleventy#706]
**Describe the bug**
While a "npm" install works, a "pnpm" won't. From my understanding and tests, a direct declared dependency to TypeScript is not set in the package.json.

**To Reproduce**
Just try to use pnpm, and not npm (

**Expected behavior**
npm or pnpm users should be able to start the same way.

**Environment:**
 - Windows 10
 - Node: 12.7.0
 - npm: 6.10
 - pnpm: 3.8.1
 - Eleventy: 0.9.0

**Comment by Ryuno-Ki** [comment]
Can you share the error message?
Is there a specific dependency causing the failure?

**Comment by TigersWay** [comment]
Just tried again this morning, but different things changed:
- node v12.11.1
- pnpm v4.0.0

... and I cannot reproduce the problem!

So, closing this issue!
