### ISSUE TITLE
Programatic Usage (no-CLI) of Eleventy

### ISSUE THREAD

**Issue by Snugug** [11ty/eleventy#713]
I'm attempting to write tests to confirm that 11ty is configured correctly to my needs (basically end-to-end tests for 11ty) but for the life of me I can't figure out how to use 11ty programmatically. What I'd like to be able to do is, in Node, not via the CLI, create an 11ty instance with a provided configuration, and then either pass it files or have it run off of a provided input directory and then capture the output to test against.

Is this currently possible? If so, what's the best way to actually do this?

**Comment by Ryuno-Ki** [comment]
Duplicate of #620?

**Comment by zachleat** [comment]
Yeah sorry, let’s coordinate over at #620 for this.
