### ISSUE TITLE
Custom filter to encode url to base64 

### ISSUE THREAD

**Issue by alistairtweedie** [11ty/eleventy#715]
I’m required to have a url in the front matter to be output as a base64 encoded url.

I’m using Nunjucks as my templating language but there’s not a filter included. I think I’ll need to start by including a package to do the encoding but unsure to how to combine the task of encoding into the filter to use in my templates. Any pointers in the right direction would be greatly appreciated 🙂

**Comment by chrisssycollins** [comment]
@alistairtweedie I might not be solving the problem you have but hope this helps.

In your `.eleventy.js` file you can register [custom filters](https://www.11ty.io/docs/filters/). The filter passes the value into a function as a param and lets you return what you like.

```js
module.exports = function (eleventyConfig) {
  eleventyConfig.addFilter("base64", function(str) {
     return str // You'll want your package to do the encoding here 
  });
};
```

You can then use that as a filter.

```yml
---
url: "https://www.example.com"
---

{{ url | base64 }}
```

If you've got an example project I could probably help more. 😄

**Comment by alistairtweedie** [comment]
Cheers for the heads up @chrisssycollins 

Although not a filter in Nunjucks, encoding to Base64 is baked into Node.js so ended up being really simple!

```js
eleventyConfig.addFilter("base64", function(url) {
      return Buffer.from(url).toString('base64');
});
```
Result!

**Comment by chrisssycollins** [comment]
@alistairtweedie Nice one mate 👍🏼
