### ISSUE TITLE
Serve/Watch not working

### ISSUE THREAD

**Issue by Archeelux** [11ty/eleventy#716]
**Describe the bug**
I have a simple project with a base.njk layout with the default html doc layout and a index.md which takes the layout all correctly. But `eleventry --serve` is not watching the files or refreshing the browser when ever I change anything in the `src/site` folder.

![image](https://user-images.githubusercontent.com/47854865/65881752-cd8c6400-e38b-11e9-8868-8965b04e2e5f.png)

Even when the console does not say that the files have been changed and is stuck on the following:

![image](https://user-images.githubusercontent.com/47854865/65881955-1e03c180-e38c-11e9-8ebd-8c75519d751e.png)

**To Reproduce**
1. Create simple project
2. Run `eleventry --serve`
3. Edit a file and save

**Expected behavior**
The site should have been rebuilt and browser should have been refreshed.

**Environment:**
 - Windows 10
 - Eleventy 0.9.0

**Additional context**
Am I doing something wrong or maybe I am missing something but it is clearly just not working. Thank you!

**Comment by TigersWay** [comment]
Probably #701  Should downgrade chokidar

**Comment by Archeelux** [comment]
Fixed with latest chokidar update 

[#701](https://github.com/11ty/eleventy/issues/701#issuecomment-537224263)
