### ISSUE TITLE
Using a date filter with Nunjucks in a directory data file

### ISSUE THREAD

**Issue by jeromecoupe** [11ty/eleventy#717]
I don't know if this is a bug or if I am missing something, but I cannot seem to get a date filter to work in a directory data file to create a dynamic permalink.

**To Reproduce**
1. Create a universal date filter in Nunjuck w/ moment/luxon and verify that it works in nunjucks templates. `page.date|date('YYYY-MM-DD')` works fine in an `njk` template.
2. Save some markdown files in the `./src/blogposts` directory and create a collection using globs

```js
const moment = require("moment");
const now = new Date();

module.exports = function(eleventyConfig) {
  // blogpost collection
  eleventyConfig.addCollection("blogposts", function(collection) {
    return collection.getFilteredByGlob("./src/blogposts/*.md").filter((item) => {
      return item.data.draft !== true && item.date <= now;
    });
  });

  // date filter
  eleventyConfig.addFilter("date", function(date, format) {
    return moment(date).format(format);
  });

  // Base config
  return {
    passthroughFileCopy: true,
    dir: {
      input: "src",
      output: "dist"
    }
  };
};
```

3. Add a `blogposts.json` file in the `blogposts` directory to define `layout` and `permalink` for all blogposts

```json
{
  "layout": "layouts/blogpost.njk",
  "permalink": "blog/{{ page.date|date('YYYY') }}/{{ page.fileSlug }}/index.html"
}
```

**Expected results**

Expecting blogposts of the same year to be generated in corresponding year folder (2017, 2018, 2019, ...).

Instead I have one folder per blogpost with a name looking like `2013-11-03T00:00:00+01:00`, which leads me to think the filter does not get applied. Both `page.fileslug` and `page.date` seem to be working fine

**Environment:**
 - MacOs High Sierra 10.13.6
 - Eleventy Version 0.9.0

**Comment by jeromecoupe** [comment]
Just a bit more information on this one. I can get the desired results by creating and using a filter with no parameters:

```
// date to Year for permalinks
  eleventyConfig.addFilter("dateToYear", function(date) {
    return moment(date).format("YYYY");
  });
```

Using this in variables for permalinks will work just fine and create the sub-folders for years

```
{
  "layout": "layouts/blogpost.njk",
  "permalink": "blog/{{ page.date|date('YYYY') }}/{{ page.fileSlug }}/index.html"
}
```

So, it seems that it's the format parameter I pass as a string that causes a problem when using date filters to create dynamic permalinks with directory data files. I must say I am a bit confused here.

**Comment by porglezomp** [comment]
I think this might be related to my issue #758, which I've determined is caused by the permalink format engine being selected by the file being formatted, not the template where it's defined. Is your markdown template engine maybe liquid? There's different parameter syntax, so that might be what's breaking things.

**Comment by jeromecoupe** [comment]
@porglezomp Thanks Cassie, this is indeed what caused the problem. The filter in markdown files front matter (or in this case in a `json` directory data file applied to all of those files) was indeed parsed as Markdown. Since the filter syntax is different for multiple parameters ... that caused the issue. Adding `markdownTemplateEngine: "njk"` to my config solved the problem, since the filter is now (correctly) parsed by Nunjucks.

Thank you so much for looking into this. Much appreciated.
