### ISSUE TITLE
How do I configure Eleventy to use 11ty.js layouts?

### ISSUE THREAD

**Issue by miksula** [11ty/eleventy#721]
I am confused how to use JavaScript (`*.11ty.js`) layouts with markdown.

I have a JavasScript layout file:  `_includes/mylayout.11ty.js`and configuration for templates as `templateFormats: ['md', '11ty.js']`. How ever I get `TemplateWriterWriteError` as if JavaScript layouts are not supported. 

`$ eleventy hello.md` -> _TemplateWriterWriteError_

I got this even if `mylayout.11ty.js` is just doing nothing:

`class MyLayout {
  render() {
    return "hello!"
  }
}`

**Comment by zachleat** [comment]
Can you include the full stack trace? Did you module.exports in your layout file?

**Comment by zachleat** [comment]
Confirmed working on 1.x:


test.md

```
---
layout: layout.11ty.js
---
# Hello
```

_includes/layout.11ty.js

```js
module.exports = (data) => {
  return `<!doctype html>
  <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="description" content="">
      <title></title>
    </head>
    <body>
      ${data.content}
    </body>
  </html>`
}
```

outputs:

```html
<!doctype html>
  <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="description" content="">
      <title></title>
    </head>
    <body>
      <h1>Hello</h1>

    </body>
  </html>
```
