### ISSUE TITLE
Hot reloading of MD files

### ISSUE THREAD

**Issue by cfjedimaster** [11ty/eleventy#726]
**Describe the bug**
When trying Eleventy via the very first page of the site (https://www.11ty.io/), it asks you to create a quick markdown file and then run the server. Specifically this line:

"Run eleventy --serve to start up a hot-reloading web server. "

However, hot-reloading won't work at this time. Later on here, https://www.11ty.io/docs/getting-started/, you make an HTML file and another MD file and you will have the same issue. The HTML file should reload as it has a body tag, but not the shorter MD one.

Continuing on in the docs you see a note about how hot reload only works when a body tag is present. This makes perfect sense but I honestly thought Eleventy was broken at first because it wasn't hot reloading. I'd ether change the sample or add the warning a bit earlier.

**Comment by Ryuno-Ki** [comment]
Sounds like https://github.com/11ty/eleventy/issues/313 was still not fixed :-(

**Comment by xuhcc** [comment]
In my case hot reloading is not working for `index.md` files in the following project structure:

```
posts/
  posts.json
  post-1/
    index.md  # Not reloading
  post-2.md  # Reloading
```

**Comment by lonekorean** [comment]
@xuhcc I had that issue too where `.md` files in subdirectories wouldn't trigger hot reload. Was able to fix it by adding the following to `.eleventy.js`:

```js
config.addWatchTarget('posts');
```

Not sure why.

**Comment by zachleat** [comment]
Importantly for some of the commenters here, markdown files _do_ hot-reload but you need to add a layout file around the content with a `<body>` so that Browsersync will work. This is now noted in a better way on the Getting Started guide

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/39355/87214562-5957f700-c2f3-11ea-84ab-4e6c3e42c557.png">

**Comment by zachleat** [comment]
Also noted here https://www.11ty.dev/docs/usage/#re-run-eleventy-when-you-save

**Comment by alexanderameye** [comment]
> Importantly for some of the commenters here, markdown files _do_ hot-reload but you need to add a layout file around the content with a `<body>` so that Browsersync will work. This is now noted in a better way on the Getting Started guide
> 
> <img alt="image" width="1047" src="https://user-images.githubusercontent.com/39355/87214562-5957f700-c2f3-11ea-84ab-4e6c3e42c557.png">

Do markdown files also hot-reload if the layout isn't defined in the .md file itself, but through a "Parent Directory Data File" like a posts.json file with the layout defined there? In my tests, it doesn't work. However, adding 

`eleventyConfig.addWatchTarget('posts');`

does the trick

**Comment by pdehaan** [comment]
@alexanderameye It seems to be working locally for me here if I define the layout (with `<head>` and `<body>` tags) in a directory data file.

### /src/posts/one.md
```md
---
title: ONE
---

## I AM PAGE {{ title }}

More content?
```

### /src/posts/post.json
```json
{
  "layout": "base"
}
```

### .eleventy.js
```js
module.exports = (eleventyConfig) => {
  eleventyConfig.addLayoutAlias("base", "layouts/base.liquid");
  eleventyConfig.setDataDeepMerge(true);

  return {
    dir: {
      input: "src",
      output: "www"
    }
  };
};
```

Now if I run a <kbd>eleventy --serve</kbd> script via package.json `scripts` section, open the http://localhost:8080/pages/one/ in a browser, change and save /src/posts/one.md &mdash; then my browser automatically refreshes and displays my new content in the .md file.

**Comment by alexanderameye** [comment]
> @alexanderameye It seems to be working locally for me here if I define the layout (with `<head>` and `<body>` tags) in a directory data file.
> 
> ### /src/posts/one.md
> ```lisp
> ---
> title: ONE
> ---
> 
> ## I AM PAGE {{ title }}
> 
> More content?
> ```
> 
> ### /src/posts/post.json
> ```json
> {
>   "layout": "base"
> }
> ```
> 
> ### .eleventy.js
> ```js
> module.exports = (eleventyConfig) => {
>   eleventyConfig.addLayoutAlias("base", "layouts/base.liquid");
>   eleventyConfig.setDataDeepMerge(true);
> 
>   return {
>     dir: {
>       input: "src",
>       output: "www"
>     }
>   };
> };
> ```
> 
> Now if I run a eleventy --serve script via package.json `scripts` section, open the http://localhost:8080/pages/one/ in a browser, change and save /src/posts/one.md — then my browser automatically refreshes and displays my new content in the .md file.


Thanks for getting back to me so quickly!

I saw that my setup was different in the sense that instead of having the directory 'posts', I named it 'notes' and I also named the data file 'notes.json'. If I rename these both to use 'posts' instead of 'notes', the reloading works fine. I suspect this is intended behavior and I can set this in the config file?

**Comment by TigersWay** [comment]
> ### /src/posts/post.json
> 
> ```json
> {
>   "layout": "base"
> }
> ```

@pdehaan 😄 I'm guessing it's probably more `/src/posts/posts.json`

@alexanderameye The trick is the json file name is the same as the containing folder name: `posts/posts.json` or `notes/notes.json`

**Comment by alexanderameye** [comment]
> > ### /src/posts/post.json
> > ```json
> > {
> >   "layout": "base"
> > }
> > ```
> 
> @pdehaan 😄 I'm guessing it's probably more `/src/posts/posts.json`
> 
> @alexanderameye The trick is the json file name is the same as the containing folder name: `posts/posts.json` or `notes/notes.json`

Yeah the names between directory/data file match, but if I use

posts (directory) + posts/posts.json (data file) => hot reload works

and if I use

notes (directory) + notes/notes.json (data file) => hot reload does not work

I'm trying to see if I have some special configuration going on that would explain this?

**Comment by pdehaan** [comment]
Yeah, sorry. I meant posts/posts.json, good catch. I’ll try it with notes/notes.json, but I’d be amazed if that was a special case where one works and one doesn’t.

**Comment by pdehaan** [comment]
@alexanderameye Still hot reloads for me locally when running <kbd>eleventy --serve</kbd> w/ Markdown source files and `layout` config [that specifies a `<html>` and `<head>/<body>` tag] when the folder is named /src/notes/ with a directory /src/notes/notes.json file.

I suspect it's something else that's causing the issue (although odd that it seemingly worked with an arbitrarily named /src/posts/ folder). If you have a public repo I can try taking a look.

**Comment by alexanderameye** [comment]
@pdehaan thank you!

https://github.com/alexanderameye/personal-site

This is the repo and for me the .md files under the notes directory do not hot-reload. Renaming the directory to posts (and matching the .json file of course) does work.

**Comment by pdehaan** [comment]
@alexanderameye Works for me (macOS 10.15.7)

1. <kbd>git clone https://github.com/alexanderameye/personal-site.git</kbd>
2. <kbd>cd personal-site</kbd>
3. <kbd>npm i</kbd>
4. <kbd>npm run serve</kbd>
5. Open browser to http://localhost:8080/notes/hand-drawn-rendering/
6. Edit ./notes/hand-drawn-rendering/hand-drawn-rendering.md and change
    ```diff
    -## Introduction
    +## Introductionista
    ```

And my browser auto-refreshed the /notes/hand-drawn-rendering/ page with the updated H2 text.
Didn't see any errors in my DevTools console or any obvious issues with the config/code.
