### ISSUE TITLE
Adding hooks before an eleventy build

### ISSUE THREAD

**Issue by MadeByMike** [11ty/eleventy#729]
**Is your feature request related to a problem?**

This is relates to a broader goal of trying to reduce complicated build processes that occur when you couple SSGs with tools like gulp, webpack, sass compilation or any other additional build steps that should occur before or after an SSG build.

SSGs are notoriously bad at this and it usually results in complex build processes (see how https://github.com/philhawksworth/eleventyone uses gulp as a simple example). Because fo this we frequently end up running build steps more than is necessary or changes cascade through the multipole tools and watchers. ...this is slow.

I want to make 11ty the most friendly SSG for this. We should be able to trigger 11ty in gulp, webpack or programatically as well as respond to changes from when 11ty when it is running in dev.

**Describe the solution you'd like**

I'd like to be able to add watch targets such as in #604.

I'd like to be able to run scripts before and after an 11ty build.

I'd like to be able to tell 11ty to skip a build.

I'd like to be able to trigger an 11ty build programatically including a partical build while it is running in dev.

For additional I had a discussion with @jakearchibald about some of the challenges he had working with SSGs and webpack\rollup which were similar to mine. If I understood correctly, one thing he wanted to be able to do was run a custom series of events via webpack, rollup, gulp or whatever and then at the end of this trigger the SSG build.

The hard part about doing this currently is you end up with each part of the build process trying to own everything end-to-end. I hate this and multiple watchers and build steps is what I am hoping to avoid. i.e Just trigger all the builds from 11ty or trigger 11ty from an external process.

I think perhaps some hooks like `beforeBuild` and `afterBuild` in conjunction with this #641  might allow us to delay an 11ty build then do pre-build stuff outside 11ty if required then return to the build. 

I assume hooks would need to return the files from the watcher that have been changed and a function would return something to continue or false to skip the build. Suggested API:

```js
config.beforeBuild(filesChanged => {
  // Do webpack\sass... or whatever
  const newFilesChanged = doPreprocessing()
  // The watch is delayed for now so files built by the above are not going to trigger a build again
  // return a list of files changed that includes anything done outside 11ty
  // returning an empty array would allow you to tell 11ty to do nothing.
  return [...filesChanged, ...newFilesChanged]
}); 
```

Maybe for triggering manually:
```js
config.disableWatch()

// elsewhere run when required:
eleventy.runWatcher()
```

Please rip this apart and offer alternatives.

**Describe alternatives you've considered**

This is probably related to #604 and definitely related to #641. These might not bel alternatives but pieces of the broader solution to making 11ty work as a configurable part of any build process.

**Comment by zachleat** [comment]
Infrastructure is in place for this, see https://github.com/11ty/eleventy/issues/1042

**Comment by zachleat** [comment]
https://www.11ty.dev/docs/events/ shipped `afterBuild` and `beforeBuild` including a changed files argument to `beforeWatch`. Is that sufficient here?

**Comment by MoritzLost** [comment]
@zachleat I really like the additional of `beforeBuild` and `afterBuild` events! I've tried building a little plugin with those, but to be useful the event listeners need to receive some contextual information from eleventy (I wrote a bit about this [here](https://github.com/11ty/eleventy/pull/1143#issuecomment-687154470)). At the very least, the event listener needs to know the output directory so it can do some post-processing. Of course, the output directory is known when using an event listener in a site configuration file, but inside an eleventy plugin I don't see a straightforward way to get to the output directory. Right now the only way I can think of is having the site that is using the plugin provide it with the output directory, which could get tedious if there are multiple plugins that require it.

In addition, eleventy could pass some more data to the event listeners to enable different use-cases. Like the input directories, information on the build (maybe timing data, list of output files, collections, etc). Not sure, but the more data eleventy can provide to event listeners, the more powerful will they become!

Should I create a separate issue for this?

**Comment by cfjedimaster** [comment]
I want to add on to @MoritzLost here. I'm looking at afterBuild now. At this point in execution, I should have access to the same data that templates have access to from the `_data`

**Comment by MadeByMike** [comment]
Most of this is in place and we could probably close this issue now. Thanks for all this. I had some comments similar to @cfjedimaster on twitter: https://twitter.com/MikeRiethmuller/status/1351012227667648513

Not sure if this issue is the right place for that, maybe a new one

**Comment by Ryuno-Ki** [comment]
If @MadeByMike is okay with it, can we start quoting the relevant parts in addition to a link to Twitter?
(I [suffered from link rot regarding Edison's history](https://twitter.com/AndreJaenisch/status/1353002701366435840) today).

**Comment by zachleat** [comment]
Closing this one! Also wow @MadeByMike you were way ahead of the Serverless idea!
