### ISSUE TITLE
Eleventy ignores template with empty pagination collection

### ISSUE THREAD

**Issue by saenglert** [11ty/eleventy#731]
**Describe the bug**
If pagination is handed an empty collection, the template is ignored.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create empty collection
2. Setup template with pagination and above collection
3. Run build
4. Missing template in output

**Expected behaviour**
If the collection is empty, a site with one page and no entries should be generated (being able to add a custom "no items found" message would be the icing on the cake).

**Environment:**
 - Win 10
 - Eleventy Version 6.4.1

**Comment by Ryuno-Ki** [comment]
Which template language?

(Nunjucks supports an else clause for `{% for %}` which is executed on empty collections)

**Comment by saenglert** [comment]
> Which template language?
> 
> (Nunjucks supports an else clause for `{% for %}` which is executed on empty collections)

Nunjucks indeed. Guess I ll take a look at that.

**Comment by Ryuno-Ki** [comment]
[Docs](https://mozilla.github.io/nunjucks/templating.html#for)

**Comment by cmcknight** [comment]
Would be nice to have an additional YAML parm for a default action to take on empty collections if you want the page rendered anyway.

pagination:
    data: myCoolStuff
    size: 25
    alias: products
    defaultOnEmptyCollection: true | false

 _true_  - Render template
_false_ - Default Eleventy behavior (do not render template)

What gets rendered in the content portion of the template would be controlled by the template if the render flag above is true.

**Comment by zachleat** [comment]
Shipped #1698 and #2208 for this. Will be included with 2.0.0-canary.10

Docs will show up on https://www.11ty.dev/docs/pagination/ shortly
