### ISSUE TITLE
How can I use a global data in a js component (shortcode) ?

### ISSUE THREAD

**Issue by willdante** [11ty/eleventy#742]
Hi,

I'm new to 11ty and JS, and after searching a lot, I can't find what I need.

I have a `imagekit_id` data in my _data/site.js file and I need to use it, not in a njk template but in a .js component/shortcode file.

My js component is working fine, except I can't use my global data in here.

Is there a way to access a global data (defined in _data/site.js) in a js file, maybe in a const ?

I've tried to add this at the top of my .js file: 
``` js
const imagekitId = `${site.imagekit_id}`;
```  

But I got an error `site is not defined` when serving or building.

Thanks in advance.

**Comment by octoxalis** [comment]
Just put your global data in a **module** and **require** it from anywhere!

**Comment by willdante** [comment]
Thank you @octoxalis, it worked ;)
