### ISSUE TITLE
Docs issue with passthrough?

### ISSUE THREAD

**Issue by cfjedimaster** [11ty/eleventy#746]
**Describe the bug**
The docs on Passthrough (https://www.11ty.io/docs/copy/) clearly say this:

"If a file format is not recognized by Eleventy as a valid template file extension, Eleventy will simply copy this file directly to your output."

However I am not seeing this at all. I added files and folders to my site for css, js, and img, and they do not get copied to _site. While I know the options later in the docs would give me a way to make this work, don't the docs say I shouldn't have to do _anything_ in order for them to be copied?

**To Reproduce**
1. Copy images into an img folder inside your site
2. Run eleventy
3. img files are not copied

**Expected behavior**
They should be copied.

**Environment:**
 - Eleventy Version: 0.9.0

**Comment by Ryuno-Ki** [comment]
Can you share:
* your `.eleventy.js`
* Directory structure
* Command to invoke eleventy?

**Comment by cfjedimaster** [comment]
My .eleventy.js is blank. Directory structure is incredibly simple, I've got a root /index.liquid and then a css, js, and img folder, all with a few files. None of them are dynamic in anyway, just foo.css, app.js, etc. Got eleventy installed locally and using npx to run.

**Comment by bikingbadger** [comment]
I think the docs might need rewording but from what I understand is that you still need to add:
```
module.exports = function(eleventyConfig) {
  return {
    templateFormats: [
      "md",
      "css" // css is not yet a recognized template extension in Eleventy
    ]
  };
};
```
This is like you telling 11ty which files to copy. The difference is that for things not recognized as templates it won't need to do any rendering. You still need to tell 11ty though which files to copy. It won't simply copy everything else. That could lead to bigger issues.

**Comment by zachleat** [comment]
Hey, you fixed this! https://github.com/11ty/11ty-website/commit/2064e31e6ea3b8bd14833d1939f600c76169eaa6 😅

Closing

**Comment by cfjedimaster** [comment]
This is a good change... but I have to ask. What is the point of Passthrough Copy if Eleventy ignores things anyway? Or in other words - why do we need -2- changes to tell Eleventy to copy stuff? I assume there must be a logical reason. :) 

I mean... if I just add css to a template format, then I won't need passthrough copy, right?

I've reread stuff a few times now and I'm struggling to understand why I need to use both changes. Is there a security issue if the passthrough setting ... just copied... period?

**Comment by cfjedimaster** [comment]
Further: Per @bikingbadger 's comment... "This is like you telling 11ty which files to copy. " - but why doesn't Passthrough Content tell 11ty which files to copy? 

As for security - that message seems to be saying that 11ty simply won't copy everything. I agree with that. But if I say, copy so and so, shouldn't that work? 

Ok I'll shut up now and let folks respond. ;)

**Comment by zachleat** [comment]
Officially I wish this piece of the docs would disappear https://www.11ty.dev/docs/copy/#passthrough-by-file-extension It isn’t necessary and just complicates things.

Instead of `eleventyConfig.setTemplateFormats(["jpg"]);` I’d recommend using `eleventyConfig.addPassthroughCopy("**/*.jpg");` they should be functionally equivalent and one is much more readable/understandable.

**Comment by zachleat** [comment]
Just more broadly and from a higher level, Passthrough Copy makes Eleventy builds 100% opt-in, which I think is an important security baseline.

**Comment by zachleat** [comment]
> but why doesn't Passthrough Content tell 11ty which files to copy?

I’m not sure the confusion—this is what it does?

**Comment by zachleat** [comment]
> I've reread stuff a few times now and I'm struggling to understand why I need to use both changes. 

What is “both”? If you’re using both methods (file extension and `addPassthroughCopy`), you don’t need to do both!

**Comment by cfjedimaster** [comment]
Yeah sorry if I muddled the waters here a bit - and the original issue was some time ago. :)  

Is addPassThroughCopy *enough* by itself to copy any file, period? I mean outside of things Eleventy already handles, if I tell it to copy X, it will, right? I ask because the doc change says this:

"If a file format is not recognized by Eleventy as a valid template file extension, Eleventy will ignore the file and not copy it to your output. You can modify this behavior by adding supported template formats:"

Which to me says, "If I tell Passthrough Copy to copy X, it won't, even though I said so, if X isn't a supported template property."

Or am I reading it wrong?

**Comment by cfjedimaster** [comment]
I think I was conflating two different things here - and sorry for the noise!
