### ISSUE TITLE
CSS-only changes trigger full rebuild

### ISSUE THREAD

**Issue by jcarpenter** [11ty/eleventy#752]
My situation:

* I have long template build times
  * +4 sec each, due to a regex-heavy Transform which injects citations, using [citation-js](https://github.com/citation-js/citation-js)). If I disable the transform, I get sub-1 second build times. 
* When I'm tweaking CSS, I want instant reload, for faster iteration.
* But when using both `--watch` and `--serve`, CSS file changes trigger full rebuilds—including unchanged templates. This creates long delays between a change and seeing BrowserSync refresh.
* For context: I have a passthrough copy set up for my styles.

Am I seeing intended behavior? I _thought_ that 11ty ignored unchanged files. But after much digging (through docs and issues), I can't find any information either way.

My current workaround is to disable the transform via an environment variable when working on styles, and enable it for full builds (or when editing templates). But obviously this is suboptimal. Just wondering if I'm overlooking something.

**Comment by Ryuno-Ki** [comment]
Related to #416, which was closed to collect the ideas in #108, I guess.

**Comment by zachleat** [comment]
Yeah, going to close this in favor of #108—unless you think this is fundamentally different than #108 somehow!

**Comment by zachleat** [comment]
Note that the larger project is being managed here: https://github.com/orgs/11ty/projects/3

If your issue is _specific_ to passthrough copy incremental, that’s shipping with 0.11.0: https://github.com/11ty/eleventy/issues/977
