### ISSUE TITLE
Collection from a Data File

### ISSUE THREAD

**Issue by alistairtweedie** [11ty/eleventy#754]
I'm pulling data in from an api, similar to the Github Stars tutorial in the [docs](https://www.11ty.io/docs/quicktips/eliminate-js/)

I'm looking to see how I can create a Collection from this data. Here is what I have at the moment:

My data file - `articles`
```json
[
  {
    "date": "01-08-19",
    "title": "Article title 1",
    "url": "..."
  },
  {
    "date": "02-08-19",
    "title": "Article title 2",
    "url": "..."
  }
]
```

My Eleventy file `eleventy.js`
```js
eleventyConfig.addCollection("articles", (collection) =>
    collection.getFilteredByGlob("./_datacache/articles"));
```

Template file - `articles.njk`
```html
{% for article in articles %}

<a href="{{ article.url }}”>{{ article.title }}</a>

{% endfor %}
```

This works and I'm able to loop through the data and output perfectly.

However, I'm also looking for the articles within this collection to generate pages and permalinks for each item. Is there a way to achieve this? 

```
articles/Article-title-1.html
articles/Article-title-2.html
```

**Comment by alistairtweedie** [comment]
Some more digging around previous issues and I found this [#136](https://github.com/11ty/eleventy/issues/136) 

Using pagination could potentially do the job to solve this. I’m not sure it feels natural to get pagination to do this though. Will test and feedback

**Comment by edwardhorsford** [comment]
@alistairtweedie from what you've described, pagination is the correct thing to use. I think the name can be a bit confusing - but as well as pagination it can / should also be used when you want to do a 'page per thing' type setup.

**Comment by alistairtweedie** [comment]
@edwardhorsford pagination did indeed work to solve this for me. However, I'm using advanced Nunjucks template inheritance in my `article.njk` which means the [frontmatter isn't processed](https://www.11ty.io/docs/languages/nunjucks/#supported-features). I've been attempting to solve this by defining pagination in an `articles.json` but no luck yet in getting this to work. All ideas welcome.

**Comment by alistairtweedie** [comment]
Yeh, my initial comment isn't working now. Weird

**Comment by alistairtweedie** [comment]
In the end, [this article](https://www.webstoemp.com/blog/headless-cms-graphql-api-eleventy/) was very helpful and allowed me to solve this issue 🎉
