### ISSUE TITLE
where are instructions on using a starter project?

### ISSUE THREAD

**Issue by dougouverson** [11ty/eleventy#755]
I see the list of Starter Projects at https://www.11ty.io/docs/starter/ but I can't find instructions on how to use them/it.

I've navigated to several pages and used command+f "starter" but nothing. Hmm. I'm sure it's staring me in the face :)

Thanks for the help.

**Comment by bikingbadger** [comment]
@dougouverson The starter projects are a git repo that you should clone to your machine locally. For instance: `git clone git@github.com:11ty/eleventy-base-blog.git` 
This will make a directory called eleventy-base-blog that you can then rename and start playing around with. It's basically a starting off point of what someone has already created. If that doesn't make sense let me know to try explain it a bit better.

**Comment by Ryuno-Ki** [comment]
In case you want to add something: The docs are generated from https://github.com/11ty/11ty.io/blob/a1245d17e05fde388ac35d5a6193e914521e789d/docs/starter.md which reads https://github.com/11ty/11ty.io/blob/a1245d17e05fde388ac35d5a6193e914521e789d/_data/starters.json

**Comment by zachleat** [comment]
I’m guessing this page is probably looking much different than it used to in 2019 😅

https://www.11ty.dev/docs/starter/

Starters have Deploy to Netlify buttons and Try on Stackblitz now!
