### ISSUE TITLE
Do not generate permalinks for entire directory?

### ISSUE THREAD

**Issue by scottwater** [11ty/eleventy#757]
Is there an option/frontmatter/etc which would exclude an entire directory from having permalinks generated? 

My use case is partials. I have a folder with pieces of content I intend to use in other places. I am trying to avoid them from also being accessible at a URL (even if it is obscure and not linked to).

Thanks,
Scott

**Comment by bikingbadger** [comment]
Not sure I  understand. You don't want 11ty to create a directory with html in it? How would you use it in other places if they aren't created? Is there anyway of a getting some example code or layout. I'm not sure how you'd use something without it being created.

**Comment by edwardhorsford** [comment]
@scottwater I think you're talking about `includes` / `partials` - things that get included by other templates. Correct?

[Have a look at the docs](https://www.11ty.io/docs/config/#input-directory) on the various directories. Essentially you probably want a directory for your main templates (that Eleventy processes), and a separate directory for your includes that don't get directly processed, but that other templates call.

**Comment by scottwater** [comment]
@bikingbadger I am trying to build a single page made up of other smaller parts. In short, I am want to write in markdown and build the structure in nunjucks.

My current approach is something like this: 

```html
{% markdown "/site/_home/intro.md" %}
<h2>Projects</h2>
{% markdown "/site/_home/projects.md" %}
```

`markdown` read the file and exports the content as markdown. This works, but there ends up being files at /_home/intro.html. 

@edwardhorsford - I get that, but I do not want content in my includes folder. Just my preference. 

I think I found a workable solution. I am just going to add a full markdown tag

Thanks,

**Comment by bikingbadger** [comment]
Not sure if this is usefule but you could create an _data directory. I have this along with metadata.json file in there. So you could create a file with this type of data and then in the nunjucks file that brings it all together you can use it like this:
```
{{ home.intro }}
<h2>Projects</h2>
{{ home.projects }}
```
This would be hard coded though and in json format.

**Comment by oliverjam** [comment]
For anyone reading this in the future: you can use `permalink: false` in a template's frontmatter to stop Eleventy creating the corresponding HTML output. [Docs for this](https://www.11ty.dev/docs/permalinks/#permalink-false). You can also set this for a whole directory using a [directory specific data file](https://www.11ty.dev/docs/data-template-dir/)
