### ISSUE TITLE
Trying to run Eleventy through Termux on Android

### ISSUE THREAD

**Issue by craigburgess** [11ty/eleventy#763]
**Describe the bug**
I've been setting up my Samsung Note 10+ as a portable dev station by using [Termux](https://termux.com/). I've had good success, until I got to running Eleventy. I've managed to install other NPM packages such as http-server but struggled at Eleventy.

I have installed Eleventy, but when I run the commands in Termux nothing happens.

**To Reproduce**
1. Install Termux on Android.
2. Install eleventy through standard method `npm install -g @11ty/eleventy`
3. Run `eleventy` or `eleventy --serve`
4. Nothing happens

**Expected behavior**

**Screenshots**
[A video of me attempting to run npx and just eleventy is available](https://photos.app.goo.gl/8cTaGwPf546WRxHJ7)

**Environment:**
 - Samsung Galaxy Note 10+ running Android 9 through Termux
 - It doesn't return a version number - I suspect the install hasn't worked properly.

**Additional context**
I'm _very_ aware this a very very very edge case, but it'd make me happy to try and work it out 😃

**Comment by Ryuno-Ki** [comment]
Hm, I have a similiar setup for my Fairphone...
But I don't run node there.
I could try it on a Galaxy Tab A6 🤔

**Comment by mzaini30** [comment]
I too

**Comment by zachleat** [comment]
Ha! I’m working through old issues here and this one is pretty specific 😅 I am curious if the 2.0 canaries work here—we eliminated a lot of dependencies with the new dev server.

Regardless, I think this one might be too specific for our current support burden—but I do wish you luck!
