### ISSUE TITLE
Closing shortcode tag not found

### ISSUE THREAD

**Issue by smth** [11ty/eleventy#766]
Putting content between an opening and closing shortcode tag, as described [here](https://www.11ty.io/docs/languages/liquid/#usage-3) doesn't seem to work. Error says the closing tag is "not found". E.g `tag endtest not found`. I'm using Liquid as the Markdown template engine.

**To Reproduce**
.eleventy.js:
```js
module.exports = function(eleventyConfig) {
  eleventyConfig.addLiquidShortcode("test", function(a, b) {
    return `<p>${a} - ${b}</p>`;
  });
};
```

Markdown file:
```
{% test "my param" %}
  Some content
{% endtest %}
```

**Expected behavior**
I *think* this should output:
```html
<p>Some content - my param</p>
```

**Environment:**
 - macOS 10.14.6
 - Eleventy Version 0.7.1

**Comment by TigersWay** [comment]
If I'm not mistaken you need a pairedShortcode, not a simple one... Bottom of the same page in the doc.

**Comment by smth** [comment]
You are not mistaken @TigersWay (I was), it works after replacing `addLiquidShortcode` with `addPairedLiquidShortcode`.
