### ISSUE TITLE
couple markdown sections in one file .MD

### ISSUE THREAD

**Issue by Slawkomay** [11ty/eleventy#771]
I have a list of properties, all properties have own values like:

```
---
layout: "layouts/services.njk"

Title: Property 1
Bedrooms: 2
Bathrooms: 2
Garage: Yes
Description: lorem ipsun doler simun
---
```

I am editing values in .md file (1 for each property) then exporting to .njk file and HTML looks like here:
http://codeminifier.com/rikada-template/rikada/single-property-1.html

But I want to add in "description" markdown / HTML text? Can I make it? Now I can make only pure text, I can't even make paragraphs. I want to make a couple of sections like "description" but where I can add some markdown / HTML formatting. Is this possible?

**Comment by ogdenstudios** [comment]
Do you have additional content in the `.md` file? You could move the `Description` field out of the front matter and instead write it as actual markdown in the file and then render it with `{{ content }}` in the layout.

**Comment by Slawkomay** [comment]
but if I have a couple of sections where I want to put markdown / html like `Description1` `Description2` `Description3`? I tried also making something like changing files for .njk and in additional content,  I added something like: 

```
---
layout: "layouts/services.njk"

Title: Property 1
Bedrooms: 2
Bathrooms: 2
Garage: Yes
----

{% block Description %}
lorem ipsun doler simun
{% endblock Description %}

```

but after that I have description in 2 places on html, in section where I want 
```
{% block Description %}
{{ content }}
{% endblock Description %}
```
and on top page.

**Comment by ogdenstudios** [comment]
I'm on the road right now, there are a few ways to accomplish this, but maybe this is a useful similar thread for you: https://github.com/11ty/eleventy/issues/658

**Comment by Slawkomay** [comment]
If I understand it correctly, this is more for including different markdown files in the template, I want one file where I have all the details for my properties, like: 

```
layout: "layouts/services.njk"

Title: Property 1
Bedrooms: 2
Bathrooms: 2
Garage: Yes
Description:  
" # this is the title.
Here's a line for us to start with.

This line is separated from the one above by two newlines, so it will be a **separate paragraph**. "

Description2: 
" # this is the title for the next section.
Here's a line for us to start with.

This line is separated from the one above by two newlines, so it will be a **separate paragraph**. "
```
is something like that possible? if not (or is too complicated, I am a beginner) what is the best option to make something similar? I can even put there HTML, markdown is clearer but I need just working solution

**Comment by ogdenstudios** [comment]
Ah, I think I see what you're saying.

You can do a little more with the front matter data, including using JSON, YAML, JavaScript, or even your own custom data. Check out the [alternative front matter formats](https://www.11ty.io/docs/data-frontmatter/#alternative-front-matter-formats) section in the docs. You could write some javascript that uses markdown.

**Comment by Slawkomay** [comment]
ok,  thanks, but do I need to add something in eleventy.js? Now I can't make something like this:

```
layout: "layouts/services.njk"

Title: Property 1
Bedrooms: 2
Bathrooms: 2
Garage: Yes
{
 Description:  
"<h2>Here's a line for us to start with.<h2>
<p>This line is separated from the one above by two newlines, so it will be a **separate paragraph**. </p>"
}

{ 
Description2: 
"<h2>this is the title for the next section.</h2>
<p>Here's a line for us to start with. </p>"
}
```

**Comment by ogdenstudios** [comment]
Make sure you're using the front matter format, like so: 

```
---json
{
  "title": "My page title"
}
---
```

Or for JS: 

```
---js
{
  title: "My page title",
  currentDate: function() {
    // You can have a JavaScript function here!
    return (new Date()).toLocaleString();
  }
}
---
```

Examples from [this page in the docs](https://www.11ty.io/docs/data-frontmatter/#alternative-front-matter-formats)

**Comment by Slawkomay** [comment]
I am trying make it but I think I miss something and my beginner level doesn't help, how to add these example in my file? I have in my .md / njk  file something like this:

```
layout: "layouts/services.njk"

Title: Property 1
Bedrooms: 2
Bathrooms: 2
Garage: Yes 

```
how to insert there this code:

```
---js
{
  title: "My page title",
  
 }
```
I need to add it below (tried and doesn't work)? I need to convert everything and put inside `--js` ? thank you for your help, I think I have all details from you but my skill still doesn't understand it

**Comment by ogdenstudios** [comment]
Not quite! Try this at the top of your file (in place of the current front matter you have)

```
---js
{
    layout: "layouts/services.njk"
    Title: Property 1
    Bedrooms: 2
    Bathrooms: 2
    Garage: Yes
    Description:  "<h2>Here's a line for us to start with.<h2><p>This line is separated from the one above by two newlines, so it will be a **separate paragraph**. </p>"
    Description2: "<h2>this is the title for the next section.</h2><p>Here's a line for us to start with. </p>"
}
---
```

See if that works the way you expect it to.

**Comment by ogdenstudios** [comment]
It looks like you have some markdown in the `Description` you've listed. You'll have to take a few extra steps to process that, or you could remove it and just make it all HTML instead, which might be more straightforward at the moment.

**Comment by Slawkomay** [comment]
ehh it doesn't work: `SyntaxError: Unexpected identifier`, I think I need to study it and get to know better.

**Comment by ogdenstudios** [comment]
Sure! Also I'm happy to take a look if you're able to share the code and give you more specific advice.

**Comment by Slawkomay** [comment]
thank you, I attached repository in my profile "Cards-test" `github.com/Slawkomay/Cards-test`. I tried to clean the code and now I am with my previous version, you see what I want to get in output file (just html, I think using markdown will be too much for me now). I tried with this `---js` but always got `SyntaxError: Unexpected identifier`.

**Comment by ogdenstudios** [comment]
Sweet! I just got around to this. I should be able to check it out
tomorrow. Sorry if you're on a tight time table.

**Comment by ogdenstudios** [comment]
Found a few minutes to check it out and made a PR. Hopefully that helps!

**Comment by Slawkomay** [comment]
yes, thank you for help, this is great and works like as I wanted, now I can write HTML and make formatting. In the future, when I will want to write in the markdown, is this simple or just leave it because there is too much work?

**Comment by ogdenstudios** [comment]
Awesome! Glad it worked for you. 

The reason I recommended using the JavaScript frontmatter is precisely because you wanted to write markdown. I think overall it may be easier to just write out the HTML, especially if it's short snippets like the examples you've shown. But if you decide you really want to write those markdown snippets, you can actually [execute JavaScript functions from the front matter](https://www.11ty.io/docs/data-frontmatter/#javascript-front-matter), and have JavaScript process your markdown.

**Comment by Slawkomay** [comment]
I will leave it for now, this html works for me, thanks once more for help!
