### ISSUE TITLE
Opt in / install only needed template language compilers

### ISSUE THREAD

**Issue by insanetisane** [11ty/eleventy#779]
Original [tweet](https://twitter.com/DillonHeadley/status/1195768007382970368):

> Are all of the template languages included as deps with every install? Is there a way to include only the ones you are using? Or none in the case of javascript templates?

Currently 11ty includes in it's install various template language compilers, pug, ejs, nunjucks, etc... This means you can easily use multiple templating languages in any project but typically (i would thinks) most times there will just be one or two used. That means there are dependencies included for no reason that would have to be kept up to date. This is especially true if using just js templates.

Would it be possible / beneficial to specify which (if any) templating languages are included? Maybe it would be up to the developer to install the package needed from a list of supported compilers. Or maybe even have the ability to pass a `render` function that could be used with any compiler.

I know of [accord](https://github.com/jescalan/accord) and [jstransformer](https://github.com/jstransformers/jstransformer) that have tried to make a unified interface for this kind of thing.

Thoughts and feedback welcomed!

My hope is that this would greatly reduce unnecessary dependencies and the install size of 11ty.

**Comment by Ryuno-Ki** [comment]
I just learned how [better-queue](https://www.npmjs.com/package/better-queue#custom-store) by @diamondio is [solving a similiar challenge](https://github.com/diamondio/better-queue/blob/ad87d7e7b9ef85702a859afa28516012c501c5f0/lib/queue.js#L140).

Comes down to dynamically importing the right templating language.

**Comment by dixonge** [comment]
Just ran across this. Kept getting annoying messages about core-js version being deprecated. ```npm ls core-js``` which tells me that core-js is being used by pug. I only need html, markdown, js and nunjucks for my sites, which leaves SIX different templating engines that I don't need. Six different templating engines with their dependencies.

So yeah, upvoting this as a very nice feature to have...

**Comment by Ryuno-Ki** [comment]
Hm, what about declaring the template engines as peerDependencies similiar to knex?

https://github.com/knex/knex/blob/4feefdf3d2532c23f2f662c538bf2d81700daeb1/package.json#L47-L53

**Comment by b3u** [comment]
**Idea**: Engine-specific files & dependencies are moved to separate packages. @11ty/parser-pug, for example, can contain the code and dependencies required to use pug as the templating engine.

**Comment by zachleat** [comment]
Howdy y’all, trying to clean up the issue tracker a bit. I think we can combine this issue with https://github.com/11ty/eleventy/issues/1103 Thanks!
