### ISSUE TITLE
Docs reference unreleased feature

### ISSUE THREAD

**Issue by cmccoypdx** [11ty/eleventy#780]
The code examples in the section on [pagination navigation](https://www.11ty.io/docs/pagination/nav/) are reliant on a `pagination.pages` object, which is stated to be new in version 0.10.0. The most recent version published via NPM is v0.9.0. 

The code examples should be based on the most recent stable version, or at least flag that the feature being referenced is only available in a development version, with instructions how to access that version.

**Comment by zachleat** [comment]
Yeah—sorry about that! Unfortunately the documentation for previous versions of Eleventy post-dated the 0.9.0 docs release.

As a short term fix you can find the previous version here https://5dbd05f84c2758000840afff--11ty.netlify.com/docs/pagination-nav/

**Comment by zachleat** [comment]
Closing this as 0.10.0 is out!
