### ISSUE TITLE
Plugin: Search

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#785]
Based on https://twitter.com/eleven_ty/status/1197550926636158982

This could be exposed as a plugin

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by binyamin** [comment]
This sounds like a good opportunity for a recipe or a tutorial, rather than a plugin. It's not really changing the 11ty engine; more adding a feature on top.
