### ISSUE TITLE
Ability to configure markdown-it plugins

### ISSUE THREAD

**Issue by paulrobertlloyd** [11ty/eleventy#79]
I’m using a few additional markdown features (footnotes, abbreviations etc.) which are not supported my markdown-it by default. Is there a configuration method available (perhaps `setMarkdownOptions`) that allows authors to use markdown-it plugins?

**Comment by nhoizey** [comment]
I also currently use Kramdown features with Jekyll, including footnotes, so I would be very happy to get such features here too… ;-)

**Comment by zachleat** [comment]
Documented here. https://github.com/11ty/eleventy/blob/master/docs/engines/markdown.md

0.3.0 adds an `setLibrary` method to the Configuration API (for all template engines).
