### ISSUE TITLE
Add the ability to modify content's data values before rendering

### ISSUE THREAD

**Issue by nhoizey** [11ty/eleventy#80]
For example, I have Markdown files which reference an image in front matter, and I would like to add some of the image’s EXIF data to the content data, so that I can use them in the Markdown.

This is the file I have on my filesystem:

```markdown
---
title: The Hong Kong Symphony of Lights from The Peak
date: 2015-08-08
image: hong-kong-symphony-of-lights-from-the-peak.jpg
tags:
  - cityscape
  - long-exposure
---

[A Symphony of Lights](http://www.tourism.gov.hk/symphony/english/details/details.html)
is staged every night at 8:00 p.m. in Hong Kong.
```

I would like to use [the exif package](https://www.npmjs.com/package/exif) to read EXIF data from the `hong-kong-symphony-of-lights-from-the-peak.jpg` image and insert them in the front matter before actual rendering.

So I would be able to use these data in Markdown or the template like if I had this:

```markdown
---
title: The Hong Kong Symphony of Lights from The Peak
date: 2015-08-08
image: hong-kong-symphony-of-lights-from-the-peak.jpg
tags:
  - cityscape
  - long-exposure
exif:
  camera:
    Make: 'Canon'
    Model: '5D Mark II'
  ISO: 200
  CreateDate: '2000:08:04 18:22:57'
  ShutterSpeedValue: 5.5
  ApertureValue: 3
  FocalLength: 8.7
---

[A Symphony of Lights](http://www.tourism.gov.hk/symphony/english/details/details.html)
is staged every night at 8:00 p.m. in Hong Kong.
```

**Comment by zachleat** [comment]
Hmm, I think I’m gonna say no to this one—sorry! We have an existing mechanism to do this and I think it’ll be a better option.

This mechanism is template specific data files: https://github.com/11ty/eleventy/blob/master/docs/data.md#template-and-directory-specific-data-files

Of course you’ll have to create a script to generate/modify those files. Does that make sense? You can then use the data inside the markdown just the same as if it were front matter.

If I’ve misunderstood something, please let me know!
