### ISSUE TITLE
Is it possible to use one layout for different collections?

### ISSUE THREAD

**Issue by abbasarezoo** [11ty/eleventy#805]
Is it possible to use one layout for different collections?

For example, I have a layout named `feed.njk` which has the following loop inside it:

```
<ul class="feed">
  {% for post in collections.posts %}
    <li>{{ post.data.title }}</li>
  {% endfor %}
<ul>
```

Is it possible to use front matter data from a post inside a loop?

I thought I could add some data like this to each collection item:

```
---
title: Europe
collection_type: continents
---
```
And use like so:
```
<ul class="feed">
  {% if collection_type %}
    {% for post in collections.collection_type %}
      <li>{{ post.data.title }}</li>
    {% endfor %}
  {% endif %}
<ul>
```
But this doesn't seem to work.

**Comment by bikingbadger** [comment]
Not exactly sure what you are trying but using the collection is based on tags if I remember correctly.
```
---
title: Europe
tag: continents
---
```
And then
```
<ul class="feed">
  {% for post in collections.continents%}
    <li>{{ post.data.title }}</li>
  {% endfor %}
<ul>
```

**Comment by zachleat** [comment]
You want to review the collection item data structure

https://www.11ty.dev/docs/collections/#collection-item-data-structure

I think the misstep you made in your original code sample was `collections.collection_type` when you wanted something like `collections[collection_type]` instead
