### ISSUE TITLE
Simplify EleventyConfig.addPassthroughCopy (via ability to chain method calls or a plural version).

### ISSUE THREAD

**Issue by kleinfreund** [11ty/eleventy#81]
It could be useful to have [`EleventyConfig`](
https://github.com/11ty/eleventy/blob/master/src/EleventyConfig.js)’s methods return a reference to itself so that method calls can be chained. This is best demonstrated with an example:

Current implementation:

```js
module.exports = function (eleventyConfig) {
  eleventyConfig.addPassthroughCopy('img');
  eleventyConfig.addPassthroughCopy('css');
  eleventyConfig.addPassthroughCopy('js');
};
```

Possible future implementation:

```js
module.exports = function (eleventyConfig) {
  eleventyConfig
    .addPassthroughCopy('img')
    .addPassthroughCopy('css')
    .addPassthroughCopy('js');
};
```

That said, it would still be necessary to repeat `addPassthroughCopy` for each path.

This could be simplified by adding a *plural* version `addPassthroughCopies` with one rest argument `paths`. It would just iterate over `paths` and call `addPassthroughCopy` for each entry. Then, for the example above, chaining would not be very helpful.

That’s just an idea :tm:. I can submit a pull request that implements either of the suggestions.

**Comment by zachleat** [comment]
I like this:

```
module.exports = function (eleventyConfig) {
  eleventyConfig
    .addPassthroughCopy('img')
    .addPassthroughCopy('css')
    .addPassthroughCopy('js');
};
```

I’d be happy to review a PR that added that functionality!

**Comment by zachleat** [comment]
Fixed by https://github.com/11ty/eleventy/pull/82

**Comment by nhoizey** [comment]
@zachleat I see this has been merged with the chainable syntax.

Could you explain why you prefered this over a "simpler" array of resources to copy?

This feels even better:

```javascript
module.exports = function (eleventyConfig) {
  eleventyConfig.addPassthroughCopy(['img', 'css', 'js']);
};
```
