### ISSUE TITLE
Eleventy Server conflicting with Sublime Text

### ISSUE THREAD

**Issue by rphunt** [11ty/eleventy#810]
**Describe the bug:**

On Xubuntu 19.10, when running "npx eleventy --serve" in Terminator or Xterm, getting error:

Unhandled rejection in promise: (more in DEBUG output)
Uncaught exception: (more in DEBUG output)
Cannot read property 'trim' of undefined

TypeError was thrown:
    TypeError: Cannot read property 'trim' of undefined
        at Function.log (/mnt/data_web/www/html/eleventy/eleventy-test/node_modules/@11ty/eleventy/src/EleventyErrorHandler.js:41:26)
        at Function.error (/mnt/data_web/www/html/eleventy/eleventy-test/node_modules/@11ty/eleventy/src/EleventyErrorHandler.js:32:26)
        at process.<anonymous> (/mnt/data_web/www/html/eleventy/eleventy-test/node_modules/@11ty/eleventy/cmd.js:24:26)
        at process.emit (events.js:210:5)
        at processPromiseRejections (internal/process/promises.js:201:33)
        at processTicksAndRejections (internal/process/task_queues.js:94:32)

This error repeats multiple times. More times when there are more files in the project.
It seems to only happen when Sublime Text 3.2.2 is also running.

**To Reproduce:**

1a. No other programs open.
2a. Open Terminator.
3a. CD to project folder.
4a. Run "npx eleventy --serve".
5a. Seems to run fine.

1b. Start Subime Text.
2b. Open Terminator.
3b. CD to project folder.
4b. Run "npx eleventy --serve".
5b. Returns errors mentioned above.
6b. Close Sublime Text.
7b. Run "npx eleventy --serve".
8b. Seems to run fine.

Tried with other programs open, runs fine, incl. VSCode and Atom. It seems to only have a problem with Sublime Text. No packages are installed in Sublime (other than package control). Behaves like this with all Eleventy projects.

**Expected behavior:**

Should return:

[Browsersync] Access URLs:
Local: http://localhost:8080
External: http://192.168.1.5:8080
UI: http://localhost:3001
UI External: http://localhost:3001
[Browsersync] Serving files from: _site

**Screenshots:**

NA

**Environment:**

- OS and Version: Xubuntu 19.10
- Eleventy Version: 0.9.0

**Additional context:**

It works fine on Win 10.

**Comment by Ryuno-Ki** [comment]
Should be fixed with #689 (I'm affected with Vim + Termux, too).
I believe, 0.10.0 will be the next version, though.

**Comment by rphunt** [comment]
This seems to have been resolved in the release of version 0.10.0.
