### ISSUE TITLE
Don't compile files that are only used as data in a template?

### ISSUE THREAD

**Issue by mmlkrx** [11ty/eleventy#811]
**Setup:** I have a collection at `input_dir/team/` containing files like `jane.md`, `joe.md`, etc. The files have frontmatter data (`name`, `imgUrl`, `tags`, etc) and a markdown body (`templateContent`).

In my templates I'm using them like `{%- for teamMember in collections.team -%}` to list them all on the `/about` page.

**The problem:** For every markdown file, eleventy compiles a file like `output_dir/team/jane/index.html` which I'm not using because I just need the file content as data in my templates.

**How can I stop eleventy from generating these html files?**

Also, when I add `input_dir/_includes/base_layout.njk` to my `.eleventyignore`, my templates using the base layout will still compile with data from the layout file. Shouldn't the layout file be also unavailable? Any collection markdown files I add to `.eleventyignore` become unaccessible through `collections.all` as expected.

**Comment by zachleat** [comment]
`permalink: false` is what you want I think! https://www.11ty.dev/docs/permalinks/#permalink-false

**Comment by zachleat** [comment]
combine this with a directory data file to apply to everything in the directory https://www.11ty.dev/docs/data-template-dir/

**Comment by mmlkrx** [comment]
Thanks Zach, that did the trick!

This wasn't super intuitive for me, and being new to 11ty, even if I had found the `permalink: false` option, I don't think I would've thought about combining it with a directory data file straight away.

Maybe it would be helpful to add this as an example use case somewhere under the "Using Data" section. Or a different section?

**Comment by Ryuno-Ki** [comment]
You could fill an issue against the 11ty-website repo to add another [quicktip](https://www.11ty.dev/docs/tutorials/#quick-tips), I guess.

**Comment by zachleat** [comment]
Permalinks are cross linked a bunch of different pages throughout the docs (now)

https://www.11ty.dev/docs/data-configuration/

But I will keep my ears open for more confusion about this feature for beginners!
