### ISSUE TITLE
renderData is not interpolating data in layout file

### ISSUE THREAD

**Issue by crtr0** [11ty/eleventy#816]
**Describe the bug**

`renderData` is not interpolating variable in a layout file.

**To Reproduce**

file.md:

```
---
title: "Accessibility is a Hydra"
speaker: "EJ Mason"
layout: talk
---
```
talk.njk:

```
---
renderData:
    title: "{{ title }} by {{ speaker }}"
layout: layout
---
```

layout.njk:

```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ renderData.title or title }}</title>
  </head>
  <body>
    {{ content | safe }}
  </body>
</html>
```

**Expected behavior**

I expect to see the following rendered:

`<title>Accessibility is a Hydra by EJ Mason</title>`

Instead I see:

`<title>{{ title }} by {{ speaker }}</title>`

**Environment:**

- OS and Version: MacOS
- Eleventy Version: 0.9.0

**Comment by octoxalis** [comment]
You can have variables inside Mardown front matter (only for permalink)!
Just put them in your template:
`<title>{{ title }} by {{ speaker }}</title>`

**Comment by crtr0** [comment]
@octoxalis i believe you can also have variables in a renderData section, although it’s not documented well.

**Comment by zachleat** [comment]
I hunted a little bit on this one and I think it’s worse than we both thought 😭.

See #941

**Comment by zachleat** [comment]
Shipping with the next minor version
