### ISSUE TITLE
Accept more readable date-time format in front matter

### ISSUE THREAD

**Issue by DemianX0** [11ty/eleventy#822]
**Is your feature request related to a problem? Please describe.**
I'm migrating a blog from Hugo to 11ty. The `date:` front-matter fields include timestamp in the format "2019-07-02 22:39:39 +0200" (Hugo accepts it), while 11ty expects [iso8601](https://moment.github.io/luxon/docs/manual/parsing.html#iso-8601) ("2019-07-02T22:39:39+02:00") in [Template.js](https://github.com/11ty/eleventy/blob/e0dc2ac00d8085c7ad3aa30f52e774110fb150c6/src/Template.js#L624).

While deploying to netlify this is the error message:
```
2:58:11 PM: Problem writing Eleventy templates: (more in DEBUG output)
2:58:11 PM: > date front matter value (2019-07-02 22:39:39 +0200) is invalid for ./src/<...>.md (Error):
2:58:11 PM:     Error: date front matter value (2019-07-02 22:39:39 +0200) is invalid for ./src/<...>.md
2:58:11 PM:         at Template.getMappedDate (/opt/build/repo/node_modules/@11ty/eleventy/src/Template.js:611:19)
```

Note: There's no difference in the date syntax, therefore this does not affect dates without a timestamp.

**Describe the solution you'd like**
For easier readability and migration is it possible to accept the following `date:` front-matter format: "2019-07-02 22:39:39 +0200"?

**Describe alternatives you've considered**
* An automatic migration script to convert all `date:` front-matter in a site to iso8601. If there is such a script, please inform.
* Modifying Template.js only for this deployment. Is this possible with netlify, eg. in the .node-modules folder in the git repo?

**Additional context**

**Comment by okitavera** [comment]
#### *Alternative* approach; the "automatic migration script"

On linux, you can use `sed` to replace it :
```bash
sed -i -e "s/^date: \([0-9\-]\+\) \([0-9\:]\+\) +\([0-9]\+\)/date: \1T\2+\3/g" /path/to/post.md
```
and then, you can use `file` and `sed` to make a batch changes across multiple child folders : 
```bash
find "$(pwd)" -type f -iname '*.md' -exec sed -i -e "s/^date: \([0-9\-]\+\) \([0-9\:]\+\) +\([0-9]\+\)/date: \1T\2+\3/g" "{}" \;  
```

**Comment by zachleat** [comment]
Note if it isn’t a string it does the YAML parsing and if it is a string it does Luxon fromISO https://moment.github.io/luxon/#/parsing?id=iso-8601

via https://www.11ty.dev/docs/dates/

Does `eleventyComputed` help here? https://www.11ty.dev/docs/data-computed/
The other thing I’d look into is `gray-matter` options for front matter parsing: https://www.11ty.dev/docs/data-frontmatter-customize/

(sorry for the super late reply!) It does seem unlikely that we’ll add additional date formats for this—sorry!

**Comment by zachleat** [comment]
Seeing this issue and https://github.com/11ty/eleventy/issues/867 has me thinking maybe another config hook is needed. Follow along over there!
