### ISSUE TITLE
.11ty.cjs extension not recognized as JavaScript template

### ISSUE THREAD

**Issue by justinfagnani** [11ty/eleventy#826]
**Describe the bug**
I have a project that has to have `"type": "module"` in its package.json. For other tools simply changing configuration/plugin scripts to have a `.cjs` extension has worked. Templates with `.11ty.cjs` don't work for eleventy however as that extension isn't recognized as a JavaScript template type.

**To Reproduce**

1. Create a `_includes/home.11ty.cjs` template file
2. Add `layout: home.11ty.cjs` to a content file
3. Run eleventy

**Expected behavior**
`_includes/home.11ty.cjs` is treated as a JavaScript template

**Screenshots**

The error:
```
> Unknown engine for docs-src/_includes/home.11ty.cjs

`TemplateRenderUnknownEngineError` was thrown:
    TemplateRenderUnknownEngineError: Unknown engine for docs-src/_includes/home.11ty.cjs
```

**Environment:**

- macOS 10.14
- Eleventy Version 0.9.0

**Comment by zachleat** [comment]
What are the ramifications of this? Is this still accurate? https://2ality.com/2019/04/nodejs-esm-impl.html#filename-extensions

If so it would seem like we should add both `.mjs` and `.cjs` right?

**Comment by justinfagnani** [comment]
The thing with `.mjs` extensions is that they must be imported and not required. That'll be a bigger change, and only work on Node >= 13.2, and probably will require using dynamic import since eleventy is written in CJS. Dynamic import means that code path has to be async. It might be already, but just knowing it was a much larger task I didn't even take a look.

**Comment by zachleat** [comment]
Sorry for all the questions, I’m pretty sure I’m totally on board with this but I’m a little new to the modules discussion and familiarizing myself. If you have any good resources to share I would greatly appreciate them!

So you’re using `"type": "module"` with your existing project? Isn’t that also Node 12+ with `--experimental-modules` or Node 13+ only? Is there some other transpilation happening?

Also thinking ahead a little bit, it seems like additional work will probably need to be done if I want Eleventy to support ESM templates by default (or with `.mjs` files) and whether that even makes sense for our current Node compatibility. Filed this at #836.

**Comment by zachleat** [comment]
Added a few additional TODOs for this task at #837

**Comment by justinfagnani** [comment]
No worries on the modules questions. I happen to know a lot of the details from a lot of different projects, so I'm a good one to ask :) I'll take it to #837
