### ISSUE TITLE
Eleventy should not fail when using unsupported options

### ISSUE THREAD

**Issue by markfarrall** [11ty/eleventy#829]
The use case I'm hoping to support is to simplify setting a base href via my npm scripts.

I'd like to be able to use `eleventy --base-href /otcs/docs/`. Then in a global javascript file I can use something like yargs to get the value, e.g. `baseHref: argv.baseHref || '/',`. As it's probable that I'll be using different hrefs for different deployments I'd prefer to set it in package.json, rather than build the logic in the global javascript file.

This is to make the npm scripts more readable by avoiding using cross-env and node environment variables.

Maybe an alternative approach is to not fail, but warn that it's an unsupported argument?

**Comment by jevets** [comment]
Have you considered using environment variables instead? 

https://www.11ty.dev/docs/data-js/#example-exposing-environment-variables

`ENV_BASEHREF="/octs/docs/" eleventy`

```js
// _data/project.js
module.exports = {
  baseHref: process.env.ENV_BASEHREF || '/'
}
```

```twig
// index.njk
<base href="{{ project.baseHref }}" />
...
```

**Comment by markfarrall** [comment]
I'm currently using environment variables for this in the npm scripts, but with needing to use cross-env to support Windows developers it ends up being harder to reason about than passing through an argument to process.argv, which is the approach we're generally using.

`"build": "npm run clean && npm run styles && cross-env BASE_HREF=/otcs/docs/ eleventy"`
vs
`"build": "npm run clean && npm run styles && eleventy --base-href=/otcs/docs/"'

So far it's a mixed bag of tools that pass through the argument and warn, versus those that fail and those that pass the arguments through silently. 

It's not really that important a change and it's probably coming down to preferences, so happy if you want to close this.

**Comment by zachleat** [comment]
Ah yeah sorry, I think the supported method here should be env variables. Eleventy switched to this behavior (as context) in 0.3.0, discussion here: https://github.com/11ty/eleventy/issues/66
