### ISSUE TITLE
eleventy --watch ignores Pass-through File Copies

### ISSUE THREAD

**Issue by kleinfreund** [11ty/eleventy#83]
Currently, Pass-through File Copies are ignored by `eleventy --watch`; thus, it doesn’t trigger a new build when a static file (e.g. a CSS file) changes.

Is this intended? If so, should it be changed? I think it should.

**Comment by zachleat** [comment]
Yeah 👍 from me!

**Comment by zachleat** [comment]
Related #99

**Comment by kleinfreund** [comment]
To be honest, this is so crucial for development that I consider this a bug, not a feature request.

**Comment by zachleat** [comment]
This is a great change, thanks for pushing back on it!

**Comment by msurdi** [comment]
It seems this is still happening in 0.5.4. 

Running `eleventy --passthroughall --watch --input=src --output=build`, won't update `build/styles.css` when `src/styles.css` changes

**Comment by paulshryock** [comment]
Any progress on this? CSS development is super slow when I have to constantly rebuild.

**Comment by zachleat** [comment]
Hmm, for the record this was fixed for standard passthrough copy but appears to never have worked with `--passthroughall` specifically. Filed this new issue as #439.

As a workaround you can use Pass-through File Copy or Manual Pass-through Copy methods for now which should work fine. https://www.11ty.io/docs/copy/
