### ISSUE TITLE
Support for async filters for Liquid

### ISSUE THREAD

**Issue by jeremenichelli** [11ty/eleventy#831]
**Is your feature request related to a problem? Please describe.**
Sorry if this is actually introducing noise as it might have been discussed previously, but I have the feeling that doing async filters in Liquid is not possible, right? Probably not an issue on eleventy side but a missing feature on the liquid filter package is used.

**Describe the solution you'd like**
I would like to be able to declare an async filter like:

```js
eleventyConfig.addLiquidFilter(async (src) => {
  const result = await someAsyncMethod(src)
  return result
})
```
or
```js
eleventyConfig.addLiquidAsyncFilter(async (src) => {
  const result = await someAsyncMethod(src)
  return result
})
```

If it simplifies the internals by having two separate methods. I know that liquidjs is quite asynchronous already, but don't know if filters are sync specifically.

Right now the result of an async filter gives you a `{}` which I assume is the Promise object.

**Describe alternatives you've considered**
I guess a shortcode passing a reference to what I want to process could work but I know it's not meant for those purposes, for example if I need to pipe a postcss action, most plugins are async, and it makes not possible to inline less and postcss processed styles through includes, which is how I got into this.

**Additional context**
If there's work needed to make this work, and someone can point me into the right direction I can collaborate for sure :)

**Comment by zachleat** [comment]
I did reinstate our Liquid test for async filters in 1.0 and it’s working fine! 👍🏻 It does not work in the old version of Liquid in 0.x.

**Comment by zachleat** [comment]
API method is the same as sync filters https://github.com/11ty/eleventy/blob/a11a8ba97f0d7c1447e8cf711ac861ef5e5a1e0d/test/TemplateRenderLiquidTest.js#L179
