### ISSUE TITLE
More support for `.cjs` files: Config and Data files

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#837]
Items to consider:
- [x] Configuration file `.eleventy.cjs` (works fine with `--config=.eleventy.cjs` but we should probably search for these too)
- [x] Template and Directory Data Files
- [x] Global Data Files
- [x] JavaScript templates (handled by #826 #827)

Related: #836

**Comment by gloryofrobots** [comment]
Created #848 to add support for local and global data files

**Comment by zachleat** [comment]
Moved that default config search to #1028. Closing this! Woo!
