### ISSUE TITLE
Automatically transform resources that point to input file paths to output hrefs.

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#84]
https://twitter.com/cthos/status/974729289844207616

**Comment by zachleat** [comment]
Suggested by @cthos

**Comment by zachleat** [comment]
This repository is now using lodash style issue management for enhancements (see https://twitter.com/samselikoff/status/991395669016436736)

This means enhancement issues will now be closed instead of leaving them open. The enhancement backlog can be found here: https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+

**Comment by gunnarsson** [comment]
> Comment copied from #239:
> 
> Someone showed me this convention from Jekyll and I kinda love it:
> 
> `[some text]({% link _posts/2017-08-31-ampersand.md %})`
> 
> If you could link to input files instead, this would also alleviate some of the pain in #213.

If at all possible I would very much like to use regular markdown links instead of any special syntax, so that the same links work locally in any markdown editor (with autocomplete and all) and on the published site.

**Comment by bobmonsour** [comment]
+1

**Comment by zachleat** [comment]
The `pathToUrl` filter will be available in v3.0.0-alpha.5. We’ll also provide a plugin to do everything transparently via a transform.

Docs deploying now:

https://www.11ty.dev/docs/filters/inputpath-to-url/
https://www.11ty.dev/docs/plugins/inputpath-to-url/

(Note that v3.0.0-alpha.5 has _not_ shipped yet!)

**Comment by mendhak** [comment]
Hey thanks I tested this, only thing I found missing was handling hashes `#anchor`.  I've created a PR for that:  https://github.com/11ty/eleventy/pull/3276

**Comment by xplosionmind** [comment]
Hi! This plugin is extremely useful, definitely a game-changer for me!

The only major limitation I am experiencing is that it does not support relative URLs. I opened an issue about this: #3417
