### ISSUE TITLE
support for reSTructuredText

### ISSUE THREAD

**Issue by charlyoleg** [11ty/eleventy#845]
reStructuredText (*.rst) is another popular mardown format, probably because of Sphinx and readthedocs.com. It would be great that 11ty suppoorts *.rst beside *.md

**Comment by zachleat** [comment]
I think this will be a user-land thing, see #117. But I’ll put into the queue!

> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!
