### ISSUE TITLE
Add a test for fallback layout alias

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#85]
`eleventyConfig.addLayoutAlias("", "layouts/post.njk");` per @wilto does work but probably needs a test to make sure it doesn’t break in the future.

**Comment by kleinfreund** [comment]
What does it do? Setting a some kind of default layout?

**Comment by zachleat** [comment]
@kleinfreund Sets a global default layout!

**Comment by kleinfreund** [comment]
I don’t understand how this works.

In `.eleventy.js`:

```node
module.exports = function (eleventyConfig) {
  eleventyConfig.addLayoutAlias('', 'layouts/base.njk');
  // ...
};
``` 

The file `./_includes/layouts/base.njk` exists and can be used explicitly. For example, `./test.md` specifies `layout: "layouts/base.njk"` in its front matter. This works.

However, without any front matter, `./test.md` is processed by Eleventy as-is. No layout is applied.

Am I wrong assuming that `layouts/base.njk` should be applied?

**Comment by zachleat** [comment]
Hmmmmmmmm, you’re right. The test I added was too specific to the TemplateLayout class.

If I get a re-do here—to be frank—I’d rather it stay unsupported. The “correct” way here is to add a `layout` to a directory specific data file. While that isn’t a true default global layout, it’ll work for most use cases. If people still want a default global layout, we can talk about less clever/more obvious options.

**Comment by kleinfreund** [comment]
Absolutely. This is not obvious at all. I would even consider not allowing layouts that are specified with an empty string.

**Comment by mirisuzanne** [comment]
Another solution might be allowing a directory data file in the content root directory. Has that already been discussed elsewhere? I'd love to set several global defaults that way.
