### ISSUE TITLE
Eleventy plugins should extend some options, not override them

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#851]
If multiple plugins wanted to extend front matter options, it would not be easy to do so as `setFrontMatterParsingOptions` blows any existing options away.

Need a better way to do this.

Also look at other config APIs to make sure they’re behaving in a multi-plugin world.

**Comment by samuelpath** [comment]
What should we do when 2 plugins try to extend the same [front matter](https://www.11ty.dev/docs/data-frontmatter-customize/) option, but with a different value?

Let's say one plugin wants `excerpt: true` while the other wants `excerpt: false`.

Is there any way to gracefully resolve such a conflict?

And how should we decide whether a given plugin's options should take precedence over another one?

**Comment by zachleat** [comment]
Fixed in 3.0 with a deepcopy on `setFrontMatterParsingOptions`: https://github.com/11ty/eleventy/blame/1aa6c5dbb91d39453c095196598af7497de7fc4f/src/UserConfig.js#L798
