### ISSUE TITLE
Inconsistent API: Different date formats for collection and page data 

### ISSUE THREAD

**Issue by paulrobertlloyd** [11ty/eleventy#852]
**Describe the bug**

Eleventy currently exposes two different date formats.

*Pages* use RFC 1123 (?) format, i.e. `Sun Jan 12 2020 22:52:13 GMT+0000 (GMT)` (as documented in [Page variable contents](https://www.11ty.dev/docs/data/#page-variable-contents)):

```
let page = {
  …
  // JS Date Object for current page (used to sort collections)
  date: new Date(),
  …
};
```

*Collections* however use ISO 8601 format, i.e. `2020-01-12T22:52:13.802Z`, (as documented in  [Collection item structure](https://www.11ty.dev/docs/collections/#collection-item-data-structure)):

```
{ inputPath: './test1.md',
  …
  date: 2018-01-09T04:10:17.000Z,
  …
}
```

Given that collections already use the ISO 8601 format (and that a frontmatter typically use ISO 8601 for its `date` field), having different date formats depending on context is inconsistent and unexpected.

**Expected behavior**
Dates to use the same format across the Eleventy API.

**Additional context**
The date format used for pages can also be harder to parse programatically. For example, I have a set of monthly archives pages. For these pages, I filter upon a collection ([using this custom Liquid filter](https://github.com/paulrobertlloyd/paulrobertlloyd-v4/blob/81528278de5b89a5cd2266aa82a827a508124b48/lib/filters/includes.js)) to only show posts that include a certain year and month.

Given the date format of the page object (where the year and month are separated by a day), I need to filter the collection twice, once on the year (i.e. `2020`), then again on month (i.e. `Jan`): 

```
// date = '2020-01'
{%- assign year = date | date: '%Y' -%} // => '2020'
{%- assign month = date | date: '%b' -%} // => 'Jan'
{%- assign items = collections.post | includes: 'data.date',year | includes: 'data.date',month -%}
```

If the page object where to use ISO 8601, I could filter only once:

```
// date = '2020-01'
{%- assign items = collections.post | includes: 'data.date',date -%}
```

**Comment by zachleat** [comment]
Hmm… these should all be standard JavaScript date objects, are they not?

The collections API documentation may be that way because of a different output method of converting Date toString.

For example consider this Nunjucks template:

```
{{ page.date | dump }}
{{ collections.hi[0].data.page.date | dump }}
{{ collections.hi[0].date | dump }}

---

{{ page.date }}
{{ collections.hi[0].data.page.date }}
{{ collections.hi[0].date }}
```

Here’s the output of that in 0.10.0:

```
&quot;2020-01-13T02:04:10.140Z&quot;
&quot;2020-01-13T02:04:24.382Z&quot;
&quot;2020-01-13T02:04:24.382Z&quot;

---

Sun Jan 12 2020 20:04:10 GMT-0600 (Central Standard Time)
Sun Jan 12 2020 20:04:24 GMT-0600 (Central Standard Time)
Sun Jan 12 2020 20:04:24 GMT-0600 (Central Standard Time)
```

**Comment by paulrobertlloyd** [comment]
Ah, I see. I have now [updated my filter](https://github.com/paulrobertlloyd/paulrobertlloyd-v4/blob/df4179ac40df81b0b71caafbe5d294bbd016e79a/lib/filters/includes.js#L21) to detect if a value is a `Date` object, and if so, use `toISOString()`, which gets around this issue.

That said, I wonder if the documentation should be updated to show that both collection and page objects output a JS Date Object? Maybe that would make things more confusing (and dates are already confusing, even more so in JavaScript!) Should there be an explicit ISO date provided by the API? If any of these sounds like potential feature requests, happy to close this and create new issues.

Thanks once again @zachleat! 😃

**Comment by zachleat** [comment]
I _finally_ pushed a docs update to make this clearer on the collections docs—thank you!

If you still want to file additional feature requests, please do!
