### ISSUE TITLE
Error: slugify: string argument expected

### ISSUE THREAD

**Issue by pdehaan** [11ty/eleventy#854]
**Describe the bug**
Not sure if this is by design or not, but it has tripped me up a couple times.
I'm seeing some "Error: slugify: string argument expected" errors when calling `{{ season.number | slug }}` where `season.number` is numeric.
It seems like `slugify()` expects string input and throws an error otherwise.

**To Reproduce**

I'm trying to do some pagination like "/season/1/episode/4", but am having errors when using something like `{{ season.number | slug }}` (where `season.number` is numeric.

```sh
eleventy --quiet

Fetching https://api.tvmaze.com/shows/216/cast
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering njk template ./src/templates/seasons.njk

`TemplateContentRenderError` was thrown
> (./src/templates/seasons.njk)
  Error: slugify: string argument expected

`Template render error` was thrown:
    Template render error: (./src/templates/seasons.njk)
      Error: slugify: string argument expected
        at Object._prettifyError (/Users/pdehaan/dev/github/pdehaan/tvmaze-api-test/node_modules/nunjucks/src/lib.js:36:11)
```

**Expected behavior**
No errors when doing something potentially silly like `{{ 4 | slug }}`.

**Workaround**
I created my own `slug` filter which just calls `.toString()` in the `slugify()` call:

```js
function slug(str) {
  return slugify(str.toString(), { replacement: "-", lower: true });
}
```

**Environment:**

- OS and Version: Mac
- Eleventy Version 0.10.0

```
$(npm bin)/eleventy --version
0.10.0
```

---

**UPDATE (2021-Feb-11):** This also seems to work as a quick workaround if your input string is numeric:
```js
  // Fetch built-in `slug()` filter...
  const slugFn = eleventyConfig.getFilter("slug");
  // Alias our custom `slug` filter which calls the built-in `slug()` filter with stringified content.
  eleventyConfig.addFilter("slug", (url) => slugFn(url.toString()));
```

**Comment by ericwbailey** [comment]
For what it's worth I am also experiencing this issue. I'm attempting to apply slug `id`s to each post in my postlist include.

**Comment by victoratavila** [comment]
Same issue here. Apparently it does not affect my project in fact, but every minimal issue is worrisome. Hope it to be fixed soon.

**Comment by edmondbramhall** [comment]
I'm also having this problem!

**Comment by theappbangla** [comment]
Maybe you're passing `undefined` value in slugify(...)
You can do a console log your variable before slugify it!

**Comment by edmondbramhall** [comment]
> Maybe you're passing `undefined` value in slugify(...)
> You can do a console log your variable before slugify it!

Thanks - you were right! What was happening is that I was processing a large number of json data files. Most of them had a "Title" property with a value, but at least one of them didn't. I had logging on, but none of the successful items were logging - 11ty must fail the whole operation if any pagination item fails. So I wrongly got the impression that none of the pages were successful.

**Comment by binyamin** [comment]
>  I created my own `slug` filter which just calls `.toString()` in the `slugify()` call:
```
@pdehaan where is that `slugify()` function from?

**Comment by pdehaan** [comment]
@binyamin Apparently just `const slugify = require("slugify");` where my old package.json devDependences defines `"slugify": "^1.3.6"`.

I think I was using slugify since that's what 11ty uses internally, per https://github.com/11ty/eleventy/blob/330191c10b9ab4b93a3abcf6406bbc350a47aa7d/package.json#L122

**Comment by zuha-khalid-au3** [comment]
Check if the data which you are calling is coming or not? say if you are doing **slugify(req.body.something)**?  See correctly if you are passing "something" or not

**Comment by Gabrieel777** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by ericwbailey** [comment]
Same.

**Comment by Moony-18** [comment]
same.

**Comment by pdehaan** [comment]
@zachleat Is this something we want to consider for v1.0.0 (considering I think you already tweaked the "slug" filter to accept a config object)?

I think it's a simple 1 liner change where we explicitly call `str.toString()` before passing it to `slugify`.

https://github.com/11ty/eleventy/blob/616c9f7237c06c0eb1419f13a0b6982d82068f5f/src/Filters/Slug.js#L4

Similarly, I guess I should verify if this also happens with the new "slugify" filter in v1-canary.

Or if it isn't something we want to address, should I just close this?

**Comment by zachleat** [comment]
Thanks for resurfacing this! This is absolutely the best time to make this change. I’ll apply it real quick

**Comment by zachleat** [comment]
Both `slug` and `slugify` will convert to string. Shipping with 1.0
