### ISSUE TITLE
11ty.js classes call data() multiple times each build.

### ISSUE THREAD

**Issue by ardouglass** [11ty/eleventy#858]
**Describe the bug**
I created an `11ty.js` template using a class with a `data()` method and a `render()` method as described in the documentation. I noticed that the `data()` method was being called multiple times., though the `render()` method only gets called once (which is what I would expect).

**To Reproduce**

Here's a simplified case without the fetching and stuff I was actually doing.

Make a template like `test.11ty.js`:
```js
let testData = 0;
let testRender = 0;

class Test {
  data() {
    console.log(`Data was called ${++testData} time(s).`);
    return {
      permalink: '/test.html',
    };
  }

  render(data) {
    console.log(`Render was called ${++testRender} time(s).`);
    return 'whatever';
  }
}
module.exports = Test;
```

**Expected behavior**
When running a build, the console output should be:
`Data was called 1 time(s).`
`Render was called 1 time(s).`

**Actual behavior**
Console output is:
`Data was called 1 time(s).`
`Data was called 2 time(s).`
`Data was called 3 time(s).`
`Data was called 4 time(s).`
`Data was called 5 time(s).`
`Render was called 1 time(s).`

**Environment:**

- OS and Version: Mac
- Eleventy Version 0.9.0 and 0.10.0

**Comment by zachleat** [comment]
![image](https://user-images.githubusercontent.com/39355/176969582-703e0f85-a054-490c-9b96-a09ea45f286a.png)

![image](https://user-images.githubusercontent.com/39355/176969600-0e89e3ef-960e-4bd7-af98-7c0c08c45133.png)

Not sure _exactly_ when this was fixed but I can confirm it is fixed in 1.0 and 2.0
