### ISSUE TITLE
Templates compiling to replacement characters

### ISSUE THREAD

**Issue by evlay** [11ty/eleventy#859]
**Describe the bug**
Templates compiling to replacement characters

**To Reproduce**

I produced this bug while following the Getting Started page of the documentation.
1. cmd: mkdir eleventy-sample
2. cmd: cd eleventy-sample
3. cmd: npm init -y
4. cmd: npm install --save-dev @11ty/eleventy
5. cmd: npx @11ty/eleventy
6. cmd: echo '<!doctype html><html><head><title>Page title</title></head><body><p>Hi</p></body></html>' > index.html
7. cmd: echo '# Page header' > README.md
8. cmd: npx @11ty/eleventy --serve
9. visit localhost port in web browser

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/38780115/72382117-351db380-36de-11ea-92dc-91ea7247de21.png)
![image](https://user-images.githubusercontent.com/38780115/72382426-d4db4180-36de-11ea-8e80-d8d545ea0b95.png)

**Environment:**

- OS and Version: Windows 10 Enterprise build 18363.535 version 1909
- Eleventy Version 0.10

**Additional context**
N/A

**Comment by evlay** [comment]
Resolved. Files created using the "echo" command on powershell were UTF-16 encoded files. Changed to UTF-8

**Comment by zachleat** [comment]
Upvote https://github.com/11ty/eleventy/issues/2323 if you’d like!

**Comment by zachleat** [comment]
Read more about progress on this issue here: https://github.com/11ty/eleventy/issues/2082#issuecomment-2168828502
