### ISSUE TITLE
Paginate a collection?

### ISSUE THREAD

**Issue by chrisdmacrae** [11ty/eleventy#86]
I'm looking to add pagination to a series of markdown files (so that I can add prev/next links to them).

Is this possible, or is there a better approach to adding next/prev links to individual files?

I attempted:

```
---
title: Example
pagination:
  data: collections.exampleCollection
  size: 10
---
```

**Comment by zachleat** [comment]
#76 was fixed in the _just_ released v0.3.0! Try it out!
