### ISSUE TITLE
Expose process.env.ELEVENTY_ENV in templates by default, like package.json

### ISSUE THREAD

**Issue by scottishstoater** [11ty/eleventy#861]
Would it be possible to expose `process.env.ELEVENTY_ENV` automatically by default [the same way package.json is exposed as `pkg`](https://www.11ty.dev/docs/data-preprocessing/)?

The reason I've stumbled across this is that I would like to use YAML (personal perference for readability) as a data file but can't expose `process.env` in a YAML file and it's the only thing preventing me from making the move from JS data files. 

My current workaround is having a seperate file `_data/env.js` which returns the value but would be nice to ditch this file 👀.

```js
module.exports = process.env.ELEVENTY_ENV;
```

Happy to attempt the PR if it's something we'd like 😀

**Comment by bentorkington** [comment]
Just checking you know there's nothing special about `ELEVENTY_ENV`, it's only an example of something you might call an environment variable. There's no reason 11ty should make it available by default. What you want to do is choose your own meaningful environment variable names and make them available.

IMO you're already on the right track with `_data/env.js`, which is a great place to integrate `dotenv`, convert your environment variable names to camelCase, and provide default values. [This article](https://css-tricks.com/give-your-eleventy-site-superpowers-with-environment-variables/) covers it all.

**Comment by pdehaan** [comment]
I bet you could do this with a custom filter too

```liquid
{{ “ELEVENTY_ENV” | env }}
```

where your “env” filter just checks `process.env[key]` style lookup.

**Comment by zachleat** [comment]
I don’t think ELEVENTY_ENV is a core thing? It’s just the example we used here: https://www.11ty.dev/docs/data-js/#example-exposing-environment-variables (which also shows how to expose it to your template)

I don’t think we’ll get in the business of exposing non-core ENV variables automatically so I am going to close this.

Some related discussion here https://github.com/11ty/eleventy/issues/1886 and https://github.com/11ty/eleventy/issues/1890
