### ISSUE TITLE
How can I use layouts from node_modules instead of src directory?

### ISSUE THREAD

**Issue by nicjohnson** [11ty/eleventy#864]
I have several layout files that I'd like to reuse across several projects. Ideally, I would version these in a private npm package and include them as a dependency. The trouble I'm finding is that 11ty's layout path lookup always starts at `src` which is a sibling to `node_modules`.  I know I can set a custom `src` directory but I'm not sure how I can take advantage of that to target a directory inside `node_modules`.

I've tried using this `dir` object in `.eleventy.js`:

```
dir: {
  input: 'src',
  output: 'dist',
  data: '_data',
  layouts: '../node_modules/_11tylayouts'
}
```

but it throws this exception: 

```
[eleventy:default] Problem writing Eleventy templates: (more in DEBUG output)
[eleventy:default] > You’re trying to use a layout that does not exist: layouts/intro.njk (undefined)
[eleventy:default] 
[eleventy:default] `Error` was thrown:
[eleventy:default]     Error: You’re trying to use a layout that does not exist: layouts/intro.njk (undefined)
[eleventy:default]         at TemplateLayoutPathResolver.getFullPath (/Users/nicjohnson/code/learning-with-time/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:84:13)
[eleventy:default]         at new TemplateLayout (/Users/nicjohnson/code/learning-with-time/node_modules/@11ty/eleventy/src/TemplateLayout.js:18:7)
[eleventy:default]         at Function.getTemplate (/Users/nicjohnson/code/learning-with-time/node_modules/@11ty/eleventy/src/TemplateLayout.js:38:16)
[eleventy:default]         at Template.getData (/Users/nicjohnson/code/learning-with-time/node_modules/@11ty/eleventy/src/Template.js:218:37)
[eleventy:default]         at <anonymous>
```

The documentation says "// ⚠️ These values are both relative to your input directory." so I figured I'd try to traverse up one level to `node_modules` but it doesn't seem to like that.

Ideas?

**Comment by ogdenstudios** [comment]
I don't have an opportunity at the moment to test this out, but perhaps you can use `includes`: 

https://mozilla.github.io/nunjucks/templating.html#include

And include `{% include "../node_modules/your_template.njk" ignore missing %}`

**Comment by rphunt** [comment]
In version 0.10.0, I'm using:
<pre>
includes: '../node_modules/test'
</pre>
then created a "/test" folder in "/node_modules", then copied over:
<pre>
_foot.njk
_head.njk
layout.njk
</pre>
And it renders fine. I even tweaked <em>layout.njk</em> a little to be sure the right one was being used. So for me, relative paths do seem to work.
To confirm, is "layouts/intro.njk" to be found <em>inside</em> "/node_modules/_11tylayouts"? If I force an error by changing the "includes" path, the error returned looks different from yours:
<pre>
TemplateLayoutPathResolver directory does not exist for layout.njk: node_modules/testx
</pre>
I would think if you're having a problem with the path, you should see something similar.

**Comment by rphunt** [comment]
In version 0.10.0, I'm testing your approach with:
<pre>
layouts: '../node_modules/aaaa'
</pre>
then created a "/aaaa" folder in "/node_modules", then copied over:
<pre>
layout.njk
</pre>
And it renders fine. I even tweaked <em>layout.njk</em> a little to be sure the right one was being used. So for me, relative paths do seem to work.
To confirm, is "layouts/intro.njk" to be found <em>inside</em> "/node_modules/_11tylayouts"? If I force an error by changing the "includes" path, the error returned looks different from yours:
<pre>
TemplateLayoutPathResolver directory does not exist for layout.njk: node_modules/aaaax
</pre>
I would think if you're having a problem with the path, you should see something similar.

**Comment by nicjohnson** [comment]
I started a new project and verified that it works like you described @rphunt. Thanks for the time and feedback. Now I need to figure out why it's breaking in my existing project.
