### ISSUE TITLE
Configuration Hook/callback for custom `date` parsing

### ISSUE THREAD

**Issue by letrastudio** [11ty/eleventy#867]
I'd like to use [IANA time zone codes](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) for specifying localized time in post dates, like so:

```yaml
date: 2019-08-31 23:59:56 Europe/Lisbon
```

In my humble opinion this would be the best way to avoid the [dates off by one day pitfall](https://www.11ty.dev/docs/dates/#dates-off-by-one-day).

Unlike UTC-based time offsets (e.g. `+01:00`), IANA codes abstract away offset differences from Daylight Saving Time, so a single value magically works all year round. They're also easier to understand, and provide a bit more geographical context, which is a nice bonus.

IANA codes are supported in Luxon, represented by the [`z` token](https://moment.github.io/luxon/docs/manual/parsing.html#table-of-tokens).

Eleventy currently rejects this date format as invalid, but it works in Jekyll. I'm porting over my Jekyll blog, and with over 800 posts all using this date format, um, help

**Comment by harveyramer** [comment]
I second this. Other quick fixes seem like hacks.

**Comment by zachleat** [comment]
Hmm, after seeing some pain in https://github.com/11ty/eleventy/issues/822 too it does seem good to at least provide a configuration hook to add additional userland date parsing options.

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
Cross linking to  #879 (linting data)

**Comment by uncenter** [comment]
I'd love to see this change! For some time I've thought about removing the custom `date` parsing entirely and suggesting a way to implement it in the documentation, but seeing as this feature is pretty popular "removing" the default functionality could easily be done with this kind of hook (just return the date string with no processing) and obviously allows people to have their own date formats too!

**Comment by zachleat** [comment]
v3.0.0-alpha.15 will include a `eleventyConfig.addDateParsing` method for adding your own custom date parsing logic. This is a preprocessing step for existing Date logic.

You can return:

* a JavaScript `Date` to short-circuit `page.date` with this new value.
* any valid value for `date` will be processed using existing logic: https://www.11ty.dev/docs/dates/ As an example, you can return a new string that will be processed by Luxon.
* anything falsy (or no `return`) will fallback to the existing date logic.

Here’s an example using IANA time zone codes from the Eleventy test suite.

```yaml
---
date: 2019-08-31 23:59:56 America/New_York
---
# Markdown
```

```js
import { DateTime } from "luxon";

export default function(eleventyConfig) {
	eleventyConfig.addDateParsing(function(dateValue) {
		return DateTime.fromFormat(dateValue, "yyyy-MM-dd hh:mm:ss z");
	});
};
```

You _can_ add multiple callbacks and chain them together and they’ll all run before the fallback logic takes hold of the new value:

```js
eleventyConfig.addDateParsing((rawDateValueFromTemplate) => rawDateValueFromTemplate);
eleventyConfig.addDateParsing((rawDateValueFromFirstCallback) => rawDateValueFromFirstCallback);
```

**Comment by uncenter** [comment]
Wow that's amazing, thanks Zach! Exactly what I was looking for.

**Comment by zachleat** [comment]
Preview docs deploying here: https://11ty-website-git-v3-11ty.vercel.app/docs/dates/#configuration-api-for-custom-date-parsing
