### ISSUE TITLE
--serve interprets <script> tags asynchronously (?)

### ISSUE THREAD

**Issue by wsw70** [11ty/eleventy#875]
**Describe the bug**

I am building a web site using Pug as the templating language and Vue.js as the reactive framework.

When running `npx @11ty/eleventy --input=src` I get a `_site` which works correctly when served by a web server (such as `devd` or `caddy`).

When running `npx @11ty/eleventy --input=src --serve`, Eleventy crashes with 

```
PS D:\Seafile\dev\dev-perso\websites\eleventy2> npx @11ty/eleventy --watch  --input=src
Writing _site/about/index.html from ./src/about.pug.
Writing _site/index.html from ./src/index.pug.
Writing _site/posts/premier/index.html from ./src/posts/premier.md.
Writing _site/posts/second/index.html from ./src/posts/second.md.
Copied 3 items / Wrote 4 files in 1.00 seconds (v0.10.0)
Unhandled rejection in promise ([object Promise]): (more in DEBUG output)
> Vue is not defined

`ReferenceError` was thrown:
    ReferenceError: Vue is not defined
        at Object.<anonymous> (D:\Seafile\dev\dev-perso\websites\eleventy2\src\index.js:1:63)
        at Module._compile (module.js:653:30)
        at Object.Module._extensions..js (module.js:664:10)
        at Module.load (module.js:566:32)
        at tryModuleLoad (module.js:506:12)
        at Function.Module._load (module.js:498:3)
        at Module.require (module.js:597:17)
        at require (internal/module.js:11:18)
        at getDependenciesFor (D:\Seafile\dev\dev-perso\websites\eleventy2\node_modules\@11ty\dependency-tree\main.js:21:5)
        at getCleanDependencyListFor (D:\Seafile\dev\dev-perso\websites\eleventy2\node_modules\@11ty\dependency-tree\main.js:73:22)
```

**To Reproduce**

The main source is below, comments follow.

```
// base.pug

doctype html
html(lang="en")
    head
        meta(charset="UTF-8")
        meta(name="viewport", content="width=device-width, initial-scale=1.0")
        meta(http-equiv="X-UA-Compatible", content="ie=edge")
        title #{page.title}
        link(rel="stylesheet", href="/base.css")
    body
        // navigation
        div#navbar
            span#title
                a(href="/") The Blog
            span#about
                a(href="about") About

        div(class="main")
            block main
                p this is content in main from base (should never be displayed)

// ---------------------------------------
// index.pug

extends _includes/base.pug
block main
    div#app
        div#tags
            span(@click="allTags[tag]=!allTags[tag]" v-for="tag in filteredTags") {{tag}}
            button(@click="resetTags()") Enable all tags
        div.post(v-for="post in filteredPosts")
            h1
                a(:href="post.url") {{post.title}}
            span.tag(v-for="tag in post.tags") {{tag}}

    script(src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js")
    script(src="https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js")
    script(src="index.js")

// ---------------------------------------
// index.js

new Vue({
    el: "#app",
    data: {
        posts: [],
        tags: {},
        allTags: {},
        // filteredTags: [],
    },
    computed: {
        // provides an Array of tags which are selected
        filteredTags() {
            let t = Object.keys(this.allTags).filter(x => this.allTags[x])
            return t
        },
        filteredPosts() {
            return this.posts.filter(p => {
                console.log("p.tags: "+JSON.stringify(p.tags))
                console.log("filteredTags: "+JSON.stringify(this.filteredTags))
                console.log("intersection: "+JSON.stringify(_.intersection(p.tags, this.filteredTags)))
                return _.intersection(p.tags, this.filteredTags).length > 0
            })
        }
    },
    methods: {
        resetTags() {
            Object.keys(this.tags).forEach(t => {
                this.$set(this.allTags, t, true)
            });
        }
    },
    watch: {
    },
    mounted() {
        fetch("posts.json")
        .then(r => r.json())
        .then(r => this.posts = r)
        // get source tags
        fetch("tags.json")
        .then(r => r.json())
        .then(r => {
            this.tags = r
            this.resetTags()
        })
    }
})
```

The error, I believe, is that in `script.js` the `Vue` symbol is unknown. It is brought by the included script just above.

**Since the generated `_site` is correct and runs correctly through an external web server** it must be (wildly speculating) the way `--serve` (or `--watch`) interprets the files that poses a problem.

Wildly speculating even further, it may be that the `<script>` parts are served asynchronously (?) and therefore `script.js` expects `Vue` when `Vue` is not available yet.

The error mentions a Promise in the context of Vue not being available, this is particularly what makes me think that the scripts may be served asynchronously. But again, this is a wild guess.

That would be weird, though, as the generated HTML is correct (see how `<script>` is stacked correctly):

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
    <link rel="stylesheet" href="/base.css">
</head>

<body>
    <!-- navigation-->
    <div id="navbar"><span id="title"><a href="/">The Blog</a></span><span id="about"><a href="about">About</a></span>
    </div>
    <div class="main">
        <div id="app">
            <div id="tags"><span @click="allTags[tag]=!allTags[tag]" v-for="tag in filteredTags">{{tag}}</span><button
                    @click="resetTags()">Enable all tags</button></div>
            <div class="post" v-for="post in filteredPosts">
                <h1><a :href="post.url">{{post.title}}</a></h1><span class="tag" v-for="tag in post.tags">{{tag}}</span>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js"></script>
        <script src="index.js"></script>
    </div>
</body>

</html>
```

**Environment:**

- OS and Version: Windows 10
- Eleventy Version: 0.10.0

**Additional context**

The only workaround I found is to regenerate the site manually at each change and have it served by an external webserver.

**Comment by rphunt** [comment]
I'm kind of unclear why Eleventy even cares about Vue. It's like it's trying to process that index.js as if it was a data file.

Are you familiar with PassThrough File Copy? [https://www.11ty.dev/docs/copy/](https://www.11ty.dev/docs/copy/) (scroll down to Manual Passthrough File Copy ). Maybe you need to tell Eleventy to just copy that script over instead of using it.

But I'm not a Vue person, and I don't know why Eleventy would be doing this. Just my first thought.

**Comment by wsw70** [comment]
@rphunt THANK YOU. That was that.

`index.js` was at the root of my `src` directory, and was being processed (not sure how, probably executed).

I moved it to `src/_includes` and it now works fine.

I think I will make a PR on the documentation to explicitly describe the structure of the project. I now understand that  `src/_includes` is a special directory with special handling. I know that this is addressed here and there in the docs but I believe it should be at the very beginning so that users are more aware of what should go where. (or maybe I missed the right part in the docs)

**Comment by rphunt** [comment]
Cool. Note that `src/_includes` is really intended for layouts and partials. You can drop index.js into a folder like `src/js` then add to your `.eleventy.js`:
<pre>
eleventyConfig.addPassthroughCopy("src/js");
</pre>
This will copy over the js folder to your output folder. This works for a `src/css` folder too. Let me know if you need some help with it.

**Comment by wsw70** [comment]
Yes, this is what I ended up doing: creating a `static` folder (for JS, CSS, ...) which is then copied via `addPassthroughCopy()` to `_site/static`.

I am new to Eleventy so I am still stumbling here and there - the product is great though. The only thing which I cannot really put my finger on yet is its caching mechanisms. I sometimes need to erase `_site` a few times and restart Eleventy (in `--serve` mode) a few times as well do that the changes in the source files (`.pug` file for instance) actually make their way to the `_site` HTML ones. I will try to pinpoint some reproductible setups before raising an issue.

**Comment by rphunt** [comment]
One thing to note about `eleventy --serve` is that if you add new files or folders, you need to stop and restart it. I think it makes an inventory and only watches what is in it. 
I'm glad you got the rest working.

**Comment by HagelBagel** [comment]
Having struggled with this problem as well, I just want to add what worked for me. From my .eleventy.js file:
`eleventyConfig.setTemplateFormats([
        "njk",
        "md",
        "png",
        "jpg",
        "gif",
        "css"        
    ]);`
    
    eleventyConfig.addPassthroughCopy([
        "css",
        "src/js/sitescripts.js"
    ]);

**Comment by jeremiahlee** [comment]
I'm also having this issue. I have some static JavaScript I just want to be passed through, but adding JS files via `eleventyConfig.addPassthroughCopy()` or to `templateFormats` results in `ReferenceError: document is not defined`.
