### ISSUE TITLE
Issues with creating page from data

### ISSUE THREAD

**Issue by amykapernick** [11ty/eleventy#876]
**Describe the bug**
Trying to auto-generate pages from Contentful data. Data is displaying fine on the page, but when creating individual posts, the resultant files aren't being created correctly

**To Reproduce**

1. Run `npx @11ty/eleventy --serve`

**Expected behavior**
I expect each post to get a folder and index.html file created in the site folder

**Screenshots**
Eleventy output
```
> npx @11ty/eleventy --serve --port=$PORT
 
Writing _site/CODE_OF_CONDUCT/index.html from ./CODE_OF_CONDUCT.md.
Writing _site/on-submitting-to-conferences/index.html from ./postTemplate.njk.
Writing _site/2019-a-retrospective/index.html from ./postTemplate.njk.
Writing _site/setting-up-a-windows-computer-for-dev/index.html from ./postTemplate.njk.
Writing _site/html-and-css-tricks/index.html from ./postTemplate.njk.
Writing _site/ndc-minnesota-2019/index.html from ./postTemplate.njk.
Writing _site/how-notion-runs-my-life/index.html from ./postTemplate.njk.
Writing _site/an-origin-story/index.html from ./postTemplate.njk.
Writing _site/the-importance-of-routine/index.html from ./postTemplate.njk.
Writing _site/being-a-more-sustainable-you/index.html from ./postTemplate.njk.
Writing _site/ddd-perth-2018/index.html from ./postTemplate.njk.
Writing _site/index.html from ./index.njk.
Writing _site/on-submitting-to-conferences from ./views/postTemplate.njk.
Writing _site/2019-a-retrospective from ./views/postTemplate.njk.
Writing _site/setting-up-a-windows-computer-for-dev from ./views/postTemplate.njk.
Writing _site/html-and-css-tricks from ./views/postTemplate.njk.
Writing _site/ndc-minnesota-2019 from ./views/postTemplate.njk.
Writing _site/how-notion-runs-my-life from ./views/postTemplate.njk.
Writing _site/an-origin-story from ./views/postTemplate.njk.
Writing _site/the-importance-of-routine from ./views/postTemplate.njk.
Writing _site/being-a-more-sustainable-you from ./views/postTemplate.njk.
Writing _site/ddd-perth-2018 from ./views/postTemplate.njk.
Error writing templates: (more in DEBUG output)
> Having trouble writing template: _site/on-submitting-to-conferences/index.html
 
`TemplateWriterWriteError` was thrown
> ENOTDIR: not a directory, open '_site/2019-a-retrospective/index.html'
 
`Error` was thrown:
    Error: ENOTDIR: not a directory, open '_site/2019-a-retrospective/index.html'
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble writing template: _site/on-submitting-to-conferences/index.html
 
`TemplateWriterWriteError` was thrown
> ENOTDIR: not a directory, open '_site/2019-a-retrospective/index.html'
 
`Error` was thrown:
    Error: ENOTDIR: not a directory, open '_site/2019-a-retrospective/index.html'
Benchmark (Data): `./_data/contentful.js` took 339ms (27.9%)
Wrote 0 files in 1.08 seconds (v0.10.0)
Watching…
```

Resultant `_site` folder (after deleting and starting from scratch
![image](https://user-images.githubusercontent.com/15953185/72861136-fb633300-3d03-11ea-960b-4000255299bf.png)

Network tab when clicking to go to one of the posts
![image](https://user-images.githubusercontent.com/15953185/72861178-15047a80-3d04-11ea-9bd6-8e6adf2fbe52.png)

**Environment:**

- OS and Version: [e.g. Windows/Mac/Linux] `Windows 10 Pro v1909` node `12.6.0`
- Eleventy Version [via `eleventy --version` or `npx @11ty/eleventy --version`] `0.10.0`

**Additional context**

**Comment by amykapernick** [comment]
Permalinks must have trailing slashes

https://twitter.com/eleven_ty/status/1219812961851793408

**Comment by BrettMN** [comment]
I received this error as well (`> ENOTDIR: not a directory, open '_site/page1/index.html'`) while using 11ty serve.  

My issue was that I had missed the trailing slash, it ran and built the pages not in directories (`page1.html`, `page2.html` and so on).  

To get rid of the error I had to delete the output directory and re-start 11ty serve.

**Comment by equivalentideas** [comment]
> I received this error as well (> ENOTDIR: not a directory, open '_site/page1/index.html') while using 11ty serve.
> 
> My issue was that I had missed the trailing slash, it ran and built the pages not in directories (page1.html, page2.html and so on).
> 
> To get rid of the error I had to delete the output directory and re-start 11ty serve.

I just had this same issue. Deleting the output directory and restarting did the trick also.
