### ISSUE TITLE
How do I create pages from objects inside an object?

### ISSUE THREAD

**Issue by mishaor** [11ty/eleventy#877]
So, I want to embed Netlify CMS into an 11ty website and for multiple entries it requires each item to have it's own file in a directory, so I have a data structure like this:
```
{
  apps: {
    taxr: {},
    abapRepl: {},
    clientApp2: {},
    etc: {}
  }
}
```

How do I generate a webpage from objects in the `apps` object? I've read "Creating pages from data" in documentation but didn't find an answer for my question.

**Comment by rphunt** [comment]
To clarify...

You want a result like:
<pre>
/apps/taxr/1/index.html ../2/index.html ../3/index.html ...
/apps/abapRepl/1/index.html ../2/index.html ../3/index.html ...
/apps/clientApp2/1/index.html ../2/index.html ../3/index.html ...
</pre>

And you're hoping it can be done with one template by having pagination cycle recursively thru "apps", yes? 

Creating a paginating template for each apps[] item easy. But off the top of my head, I'm not sure how the recursion can be done.

**Comment by abdusco** [comment]
You can monkey-patch this method to return any number of items with any object you want. 

https://github.com/11ty/eleventy/blob/e0dc2ac00d8085c7ad3aa30f52e774110fb150c6/src/Plugins/Pagination.js#L137-L144

I think exposing this method with a hook or something would be great addition to the plugin. What do you think @zachleat ? Similar to how `before` method works:

https://github.com/11ty/eleventy/blob/e0dc2ac00d8085c7ad3aa30f52e774110fb150c6/src/Plugins/Pagination.js#L118-L124

**Comment by rphunt** [comment]
> How do I generate a webpage from objects in the `apps` object? I've read "Creating pages from data" in documentation but didn't find an answer for my question.

[https://www.11ty.dev/docs/pages-from-data/](https://www.11ty.dev/docs/pages-from-data/)

In the documentation, it's a JSON file containing an array of objects which contain key/value pairs. Your example is a JavaScript object with basically just a structure of nested keys.

It can be seen in the template shown in the documentation that the data is then explicitly called out into the front matter and the body. The key/value pairs are used to tell the pagination what pages to create, Eleventy is not just cycling thru objects. So what is described there is a different situation from yours.

What it appears you're asking for is a way for Eleventy to cycle thru any number of object levels and create folders matching all the key names, ultimately creating index.html pages for the last object of any one branch. AFAIK, Eleventy doesn't offer that.

Something more consistent with the documentation might be like this...

Create a new Eleventy project.

Create a file <strong>_data/list.json</strong> :
<pre>
{
  "animals": {
      "fishes": [
        {
          "name": "gold fish",
          "size" : "small"
        },
        {
          "name": "swordfish",
          "size" : "large"
        }
      ],
      "dogs": [
        {
          "name": "poodle",
          "size" : "small"
        },
        {
          "name": "german shepherd",
          "size" : "large"
        }
      ],
      "birds": [
        {
          "name": "finch",
          "size" : "small"
        },
        {
          "name": "eagle",
          "size" : "large"
        }
      ]
  }
}
</pre>

Then create 3 HTML files...

<strong>index01.html</strong> :
<pre>
---
pagination:
    data: list.animals.birds
    size: 1
    alias: bird
permalink: "birds/{{ bird.name | slug }}/"
---

A {{ bird.name }} is a {{ bird.size }} animal.
</pre>


<strong>index02.html</strong> :
<pre>
---
pagination:
    data: list.animals.dogs
    size: 1
    alias: dog
permalink: "dogs/{{ dog.name | slug }}/"
---

A {{ dog.name }} is a {{ dog.size }} animal.
</pre>

<strong>index03.html</strong> :
<pre>
---
pagination:
    data: list.animals.fishes
    size: 1
    alias: fish
permalink: "fishes/{{ fish.name | slug }}/"
---

A {{ fish.name }} is a {{ fish.size }} animal.
</pre>

The HTML files are named <strong>index0x</strong> to show that the resulting folder structure is not connected to those file names. They can be named <strong>birds</strong>, <strong>dogs</strong>, and <strong>fishes</strong> if desired.

This should result in this structure :

<pre>
_site
├── birds
    ├── eagle
        ├── index.html
    ├── finch
        ├── index.html
├── dogs
    ├── german-shepherd
        ├── index.html
    ├── poodle
        ├── index.html
├── fishes
    ├── gold-fish
        ├── index.html
    ├── swordfish
        ├── index.html
</pre>

But I don't know if this is applicable to your use case. Hopefully it helps.

**Comment by mishaor** [comment]
Okay, so I've found the solution to my problem. I dug into the source code, and 11ty can turn the object into an array suitable for pagination. I just had to add the `resolve: values` key to the `pagination` section in my template.
