### ISSUE TITLE
doesent work on Termux/ Ubuntu on Android

### ISSUE THREAD

**Issue by waozi-dev** [11ty/eleventy#878]
I tried running eleventy on Termux and using chroot ubuntu on android using AnLinux on my arm64 device, in both cases i would be able to successfully install eleventy however when trying to us eleventy with a simple readme.md file it would generate no output at all.

The program would run, but nothing is displayed in the terminal, not even an error.

**Comment by zachleat** [comment]
Does --version work? What about the debug output?

**Comment by waotzi** [comment]
@zachleat 
--version doest work
i made some screenshots for the debug output

![photo_2020-01-23_02-13-27](https://user-images.githubusercontent.com/31371807/72948643-15455a00-3d86-11ea-9137-510c18a8141f.jpg)
![photo_2020-01-23_02-13-26](https://user-images.githubusercontent.com/31371807/72948646-16768700-3d86-11ea-9b81-7f791d85819e.jpg)
![photo_2020-01-23_02-13-33](https://user-images.githubusercontent.com/31371807/72948648-18404a80-3d86-11ea-9e03-cfe3cddbfe70.jpg)
![photo_2020-01-23_02-13-36](https://user-images.githubusercontent.com/31371807/72948652-1b3b3b00-3d86-11ea-91e1-6430ec29a8bd.jpg)

**Comment by zachleat** [comment]
What version of node are you on here?

Looks like it dies right before it creates the globs it’s looking for. This is what you’d expect to see:
![image](https://user-images.githubusercontent.com/39355/72955595-22e8e880-3d62-11ea-8674-55bb20697fdc.png)

Another interesting data point might be `DEBUG=Eleventy* eleventy --version`

**Comment by waotzi** [comment]
@zachleat 

node --version
v13.0.0

![photo_2020-01-23_18-20-56](https://user-images.githubusercontent.com/31371807/73007637-26857980-3e0d-11ea-88c4-8afbdac7ba41.jpg)
![Uploading photo_2020-01-23_18-20-54.jpg…]()

**Comment by zachleat** [comment]
Unfortunately this issue slipped under the radar—I’m finally circling back through some of the old issues on the tracker but I’d love a confirmation that this old one is still relevant before I start debugging! If I don’t hear anything in the next two weeks, I’ll likely close it as stale—sorry (and thank you!)

**Comment by waozi-dev** [comment]
hi, no problem we can close it, i no longer need it
