### ISSUE TITLE
Update node minimum version to 10 per LTS retiring 8

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#880]
Node 8 is no longer being maintained.

https://nodejs.org/en/about/releases/

Marginally relevant to #678 if this happens before

**Comment by Ryuno-Ki** [comment]
@zachleat Do you consider this in 0.11.0 as well? Or only for stable release?

**Comment by zachleat** [comment]
Fixed by https://github.com/11ty/eleventy/commit/cdb1191360a53ba7defc2b93b1ec2895d031c368

@Ryuno-Ki this will ship with 1.0 (was not part of 0.11.0)
