### ISSUE TITLE
The difference between data.content and templateContent

### ISSUE THREAD

**Issue by pepelsbey** [11ty/eleventy#882]
I have a collection of pages grouped by `tags: episode`. When I cycle through such collection using `{%- for episode in collections.episode -%}` I can easily get front matter data by `episode.date` for example. When I need the actual content of a page, I use `episode.data.content`. I’m not sure where it came from, I can’t find it on docs, but it used to work.

Today I realized that it doesn’t work anymore and `{{ episode.data.content }}` returns nothing. I found `templateContent` and it worked just like `data.content` used to work before.

The weird thing is that `data.content` [still works](https://github.com/lp-cast/3lp.11ty/blob/master/src/layouts/feed.njk#L41) it one project, but [stopped working](https://github.com/web-standards-ru/podcast.11ty/blob/master/src/layouts/feed.njk#L59) on the other, so I had to replace it with `templateContent`. Both of the projects use the latest `0.10.0` and I have no idea what’s going on :)

I’m glad I (kind of) figured out how to make it work. But here are my questions:

1. What is `data.content`, where it’s documented, why it’s not always available?
2. What’s the difference  between `data.content` and `templateContent`?

Thank you 🌲

**Comment by jameshfisher** [comment]
I have the same question. From experimentation, it seems collection items have an `item.templateContent`, but not a `item.content`. But from a layout, the page has a `data.content`.

**Comment by jtlapp** [comment]
If this is intentional, it really ought to be in the docs. I just spent an hour and a half trying to figure out why `data.content` wasn't working on items of a paginated collection. This thread told me the solution.

**Comment by uncenter** [comment]
Seeing as [`content` is supposedly an alias of `templateContent` for collection data](https://www.11ty.dev/docs/collections/#collection-item-data-structure) I'm surprised that that apparently isn't the case for other places where `templateContent` exists. I'd say this is less of a https://github.com/11ty/eleventy/labels/education and more of a change that would involve deprecating `templateContent` in v3 and ensuring that `content` works in all places `templateContent` does.

**Comment by zachleat** [comment]
Related to #338, `content` is the thing starting in 2.0+ (via #2695) per the docs link in https://github.com/11ty/eleventy/issues/882#issuecomment-2171748014

It’s unlikely that we’ll remove `templateContent` because it’s super cheap to maintain that compatibility moving forward.
