### ISSUE TITLE
Allow for dynamic ignore configuration

### ISSUE THREAD

**Issue by cfjedimaster** [11ty/eleventy#894]
Right now you can only ignore files via .eleventyignore or .gitignore. I need the ability to pass ignore configuration via the CLI, or in my .elevent.js file so that in development I can ignore some things that are not ignored in production.

My real world use case: I've got 6k+ blog posts and while Eleventy is fast, while working locally I'd like to ignore a good chunk of those via a glob pattern.

**Comment by binyamin** [comment]
> Since we use [lodash-style issue management](https://twitter.com/samselikoff/status/991395669016436736) here, enhancements are marked as closed. You can vote on this issue with a :+1:, or view [the enhancement backlog](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+)

**Comment by edwardhorsford** [comment]
[Possibly related issue.](https://github.com/11ty/eleventy/issues/188)

In lieu of this I've thought of using my build pipeline to dynamically write out the `.elventyIgnore` at build time - but this feels awkward.

**Comment by zachleat** [comment]
Shipping with 1.0—going with @binyamin’s idea to add an ignores Set to the config with a node_modules/** default!

Docs will show up at https://www.11ty.dev/docs/ignores/ in a bit

**Comment by zachleat** [comment]
You can programmatically add and delete ignores in your configuration file. eleventyConfig.ignores is a JavaScript Set. It starts with a default node_modules/** entry.

```js
module.exports = function(eleventyConfig) {
    eleventyConfig.ignores.add("README.md");
    eleventyConfig.ignores.delete("README.md");
};
```
