### ISSUE TITLE
Add easier way to set autoescape config for 11ty without needing custom Nunjucks.Environment

### ISSUE THREAD

**Issue by pdehaan** [11ty/eleventy#895]
**Is your feature request related to a problem? Please describe.**

I was hoping it'd be easier to modify the Nunjucks config. Currently it looks like if I want to modify `autoescape`, I have to add Nunjucks as a dependency, create a new environment, and then overwrite the default Nunjucks environment.

```js
const Nunjucks = require("nunjucks");

module.exports = eleventyConfig => {
  const nunjucksEnvironment = new Nunjucks.Environment(
    new Nunjucks.FileSystemLoader(["src/_includes"]), // we need to pass in our includes dir here
    {
      lstripBlocks: true,
      trimBlocks: true,
      autoescape: false
    }
  );

  eleventyConfig.setLibrary("njk", nunjucksEnvironment);
  return {};
};
```

**Describe the solution you'd like**

Not sure if this is the correct API, but I was looking at https://mozilla.github.io/nunjucks/api.html#configure and was hoping there would possibly be a `eleventyConfig.setNunjucksOptions()`, similar to https://www.11ty.dev/docs/languages/liquid/#optional-use-your-own-options, so instead of having to worry about requiring Nunjucks and defining a new environment, I could just say:

```js
eleventyConfig.setNunjucksOptions({ autoescape: false });
```

And maybe that would deep merge the existing Nunjucks options with my overrides.

**Describe alternatives you've considered**

Looks like I can do this with a Nunjucks dependency (I couldn't figure out how to access the existing Nunjucks inner object via `eleventyConfig` so I could try calling try calling `inner.eleventyNunjucksRef.configure({ autoescape: true });`

**Additional context**

**Comment by octoxalis** [comment]
You don't have to use Nunjucks Environment.
Have look [there](https://github.com/octoxalis/11tyTips/blob/master/source/make/11ty/libraries.js) where `make_o` is `eleventyConfig`.

**Comment by AramZS** [comment]
Just noting that @octoxalis proposed solution might have worked at some point in the past, but I was unable to implement it as given today.

**Comment by pdehaan** [comment]
@zachleat Is this something we'd want to consider for v1 [adding `eleventyConfig.setNunjucksOptions({..})` similar to how we have [`eleventyConfig.setLiquidOptions({..})`](https://www.11ty.dev/docs/languages/liquid/#optional-use-your-own-options)]?

I often find myself debugging templates using the [Nunjucks `throwOnUndefined` option](https://mozilla.github.io/nunjucks/api.html#configure) but needing to create a whole new Nunjucks.Environment with my include paths, etc. can get a bit tricky.

**Comment by zachleat** [comment]
Yeah, I think this is foundational (small to implement) and would be a high value addition. Adding to the milestone.

**Comment by zachleat** [comment]
See also https://github.com/11ty/eleventy/issues/1342

**Comment by zachleat** [comment]
Docs added to 11ty-website a4cf33cd514d8f63a66acb3051dee8bab10d6615

Shipping with Canary 42.
