### ISSUE TITLE
is there a way to prevent a (non excluded) sub-directory from generating output?

### ISSUE THREAD

**Issue by ckot** [11ty/eleventy#896]
Hi,

I'm attempting to create an SPA, which is primarily html, using eleventy.

```
src/
   _includes/
   index.njk
   scenes/
       scene1.njk
       scene2.njk
        ...
```
All of the templates in the `scenes` sub-directory are tagged 'scenes'

index.njk
```
{% for scene in collections.scenes %}
   <section id="{{scene.data.id}}" class="scene">
      {{scene.templateContent}}
   </section>
{% endfor %}
```

This works great, as far as the generated 'index.html', but as expected, eleventy outputs:

dist
```
dist/
    index.html   <-- this is all I need
    scenes/    <-- don't want this
        scene1/index.html
        scene2/index.html
        ...
```

I *suppose* I could simply append a `&& rm -rf dist/scenes` to my build step, but is there a more 11ty-way of doing this (something I could do in my .eleventy.js) ?

**Comment by pdehaan** [comment]
Try https://www.11ty.dev/docs/permalinks/#permalink-false

Probably fastest way would be to create a _src/scenes/scenes.json_ file and add the following, which should add the `permalink:false` front matter to each of the templates in the src/scenes/* folder (versus adding that in each file individually):

```json
{
  "permalink": false
}
```

https://www.11ty.dev/docs/data-template-dir/ (for more info on directory data files)

**Comment by ckot** [comment]
@pdehaan Thanks!  That worked.  I guess I skimmed right past permalinks when I read the docs.

Oddly enough, this sets 'outputPath' to `false`, which *can* break transform functions which don't test that outputPath is truthy prior to doing something with it, as I found out, when I got the (below) error, although it was simple to fix.

```
Error writing templates: (more in DEBUG output)
> Having trouble writing template: false

`TemplateWriterWriteError` was thrown
> outputPath.endsWith is not a function

`TypeError` was thrown:
    TypeError: outputPath.endsWith is not a function
        at Template.<anonymous> (/home/ckot/projects/work/11ty_test/.eleventy.js:7:24)
        at Template.runTransforms (/usr/lib/node_modules/@11ty/eleventy/src/Template.js:387:29)
        at Template.renderPageEntry (/usr/lib/node_modules/@11ty/eleventy/src/Template.js:548:28)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by pdehaan** [comment]
@ckot good catch, I don’t think I’ve tried transforms and permalink:false together before. Might be worth filing a separate issue for that (with your solution/workaround, since now I’m curious).
