### ISSUE TITLE
Cannot read property 'trim' of undefined in EleventyErrorHandler.js

### ISSUE THREAD

**Issue by dbauszus-glx** [11ty/eleventy#899]
I try to run the following command:

`npx eleventy --input ./_docs --output ./docs --formats=html,md --pathprefix=/xyz/docs --serve`

This builds the output directory and then throws hundreds of 'trim' error messages.

I tested with node v9.7, 10.16.3, 12.7 and 12.10 against eleventy v0.9 and 0.10.

**Comment by dbauszus-glx** [comment]
So the trim is just a borked way of handling the error in EleventyErrorHandler.js which doesn't check ref.message before printing the message. The actual error is caused by System limit for number of file watchers reached. Will open a separate issues for this.

**Comment by zachleat** [comment]
Ah hmm, I suspect it’s coming from this? https://github.com/11ty/eleventy/blob/cde29307ef06722e5708e373f9ba6b38c11db018/src/EleventyErrorHandler.js#L50

What is the value of `ref` and `ref.message` in your error?

**Comment by mohitk05** [comment]
Hey @zachleat, new to the codebase but what I can see is the `EleventyErrorHandler.message(...)` function does not return anything and hence when `.trim()` is called on `message()` this error is thrown. I think you wanted to trim the message before being passed to the `.message` function? If that's so then `trim()` could be called for the whole argument of `message()`. Let me know if that's the case, will create a PR for this!

**Comment by zachleat** [comment]
We’ll need to circle back to make sure this fix worked after the next beta is released.

**Comment by zachleat** [comment]
The next beta is out! Please re-test and we can open it back up if you’re still seeing this issue.

**Comment by DanCanetti** [comment]
I'm on the latest version 0.10.0 and I've just started getting this error over the past day or so: 

```
Unhandled rejection in promise: (more in DEBUG output)
Uncaught exception: (more in DEBUG output)
> Cannot read property 'trim' of undefined

'TypeError' was thrown:
    TypeError: Cannot read property 'trim' of undefined
        at Function.log (/usr/local/lib/node_modules/@11ty/eleventy/src/EleventyErrorHandler.js:41:26)
        at Function.error (/usr/local/lib/node_modules/@11ty/eleventy/src/EleventyErrorHandler.js:32:26)
        at process.on (/usr/local/lib/node_modules/@11ty/eleventy/cmd.js:24:26)
        at process.emit (events.js:198:13)
        at emitPromiseRejectionWarnings (internal/process/promises.js:119:20)
        at process._tickCallback (internal/process/next_tick.js:69:34)
```
