### ISSUE TITLE
`addPassthroughCopy` target

### ISSUE THREAD

**Issue by Wilto** [11ty/eleventy#90]
So, all my templates and such live in `/_src` and everything gets written to `/_site`, just to keep the [repo root](https://github.com/Wilto/wilto-makes-food) tidy.

```javascript
dir: {
    input: "_src",
    includes: "_includes",
    data: "_data",
    output: "_site"
  }
```

The “and such” includes images, so: `eleventyConfig.addPassthroughCopy("_src/img");`—but they end up getting written to `/_site/_src/img`.

Assuming I’m not doing something wrong here, should `addPassthroughCopy` be set up to accept an (optional) target argument? Something like:

```javascript
eleventyConfig.addPassthroughCopy( "_src/img", "_site/_assets/img" );
```

If it sound feasible, I might be able to take a crack at it.

**Comment by kleinfreund** [comment]
I would say this is a bug, no? Paths inside input dir should be maintained when adding them as path through copy files.

**Comment by Wilto** [comment]
If I’m reading you right, yeah—paths inside the directory should be maintained for sure. If I specify `eleventyConfig.addPassthroughCopy( "_src/css" );`, I would want it to grab the contents of `css`, `css/fonts`, `css/icons`, etc. That seems to be working.

Trouble is that the whole path ends up translated to my output directory, including an empty `_src` directory—so `eleventyConfig.addPassthroughCopy( "_src/css" );` is always going to give me `_site/_src/css/`.

**Comment by zachleat** [comment]
Yes, I agree. This is a bug.

If you look at `TemplatePassthrough.js` it’s very simple. I’m guessing that the `getOutputPath()` method in there needs to be modified to use `TemplatePath.stripPathFromDir`.

**Comment by zachleat** [comment]
@Wilto Lemme know if you want to work on it so I don’t 😀

**Comment by Wilto** [comment]
Oh, yeah—I’ll grab it, if you haven’t already.
