### ISSUE TITLE
So what actually processes the markdown?

### ISSUE THREAD

**Issue by dixonge** [11ty/eleventy#901]
Is it liquid or is it the markdown-it plugin? I honestly can't tell. Which is it, and what is the difference?

**Comment by ogdenstudios** [comment]
It's markdown-it, not liquid. [Liquid](https://shopify.github.io/liquid/) and the other templating languages give you access to templating functionality. 

[Markdown-it](https://www.npmjs.com/package/markdown-it) processes markdown and renders the HTML from the markdown. 

You can render markdown without liquid, and liquid without markdown. They're accomplishing separate tasks independent of one another. 

Is that a useful answer?

**Comment by dixonge** [comment]
UPDATE: the reason I mention liquid is because of this line in eleventy.js:

```markdownTemplateEngine: "liquid",```

**Comment by scottishstoater** [comment]
Reading the source, I *pretty sure* markdown is processed using [markdown-it](https://github.com/11ty/eleventy/blob/master/src/Engines/Markdown.js). The template engine option allows you to use Liquid, Nunjucks etcs within the markdown file, handy for using filters, shortcodes etc within your markdown body.

**Comment by dixonge** [comment]
> Reading the [source](https://github.com/11ty/eleventy/blob/master/src/Engines/Markdown.js), I'm pretty sure markdown is processed using [markdown-it](https://github.com/11ty/eleventy/blob/master/src/Engines/Markdown.js). The template engine option allows you to use Liquid, Nunjucks etcs within the markdown file, handy for using filters, shortcodes etc within your markdown body.

OK, so I'm using nunjucks exclusively, and not using Liquid at all, but that is specified in the eleventy-base-blog for some reason. Guess I'll leave it for now. Thanks!
