### ISSUE TITLE
request for documentation update for developing with client-side js  when using --serve | --watch

### ISSUE THREAD

**Issue by ckot** [11ty/eleventy#902]
I was having similar, or perhaps the same issue as #875 .  

my original project structure.
```
src/
    _includes/
        layout.njk
    index.njk
    css/
       index.css
    js/
      index.js
package.json
.eleventy.js
```

my minimal index.js
```
const fooBtn = document.getElementById("foo");

function foo() {
    console.log("Foo was clicked!");
}

fooBtn.addEventListener("click", foo);
```

Everything worked fine when simply using `eleventy` to build my output dir, however, both `eleventy --serve` and `eleventy --watch` produce the identical exception:

```
Unhandled rejection in promise ([object Promise]): (more in DEBUG output)
> document is not defined

`ReferenceError` was thrown:
    ReferenceError: document is not defined
        at initApp (/home/ckot/projects/work/11ty_test/src/js/index.js:106:5)
        at Object.<anonymous> (/home/ckot/projects/work/11ty_test/src/js/index.js:122:1)
        at Module._compile (internal/modules/cjs/loader.js:778:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:692:17)
        at require (internal/modules/cjs/helpers.js:25:18)
        at getDependenciesFor (/usr/lib/node_modules/@11ty/eleventy/node_modules/@11ty/dependency-tree/main.js:21:5)
```

Yikes! I wasn't expecting my index.js to get executed.  I guess I simply didn't notice that eleventy supports .js templates rather than merely just as data files.  

This is *starting* to make sense to me, although, since `js` wasn't listed as one of my `templateFormats`, and that `index.js` isn't one of the naming conventions for data files, and that I'm  doing a passThroughCopy for these files,  I'm still a bit puzzled why they are actually be executed.

Anyway, I'm not sure exactly what I'm doing wrong. Perhaps the docs should make it clear what happens to client side js files, perhaps even suggest a project layout/config so that the behavior is what you would expect.

I *was* able to solve my issue entirely by what is in the docs, but only because of lots of searching through issues.   I think that maybe the docs table-of-contents could be updated so that some items are only found deep within sections you wouldn't think to look in.  Also some of the examples in the docs showed use cases which didn't originally make me to think they were relevant to my issue. I can provide specifics if this issue gets any traction.

Anyway, I solved my problem (for the most part) by moving my client-code out of my eleventy `input` dir. I was delighted to find that `eleventyConfig.addPassthroughCopy()` and `eleventyConfig.addWatchTarget()` allow files/directories outside of the `input` dir.

**solution1**
new project structure
```
src/
   templates/
       _includes/
           layout.njk
      index.njk
   css/
        index.css
   js/
      index.js
package.json
.eleventy.js
```
'src/templates' is now the 'input' dir,   'css' and 'js' are now outside of the 'input' dir.

eleventy.js changes
```
    eleventyConfig.addWatchTarget("src/css/*.css")
    eleventyConfig.addWatchTarget("src/js/*.js");
    // need to use mappings so that your js and css code don't get copied to your output dir
    // as 'src/js' and 'src/css'
    eleventyConfig.addPassthroughCopy({'src/js': '.'});
    eleventyConfig.addPassthroughCopy('src/css', '.'});
```

Anyway, that totally solved my problem. I *totally* realize that this is hackish rapid application development, and that I should be using a bundler, such as webpack, to bundle my js code. 

I've seen that a bunch of people were wanting to work with webpack, and I found I could get this working with only minor changes.

**solution 2**

`npm install webpack webpack-cli  concurrently style-loader css-loader --save-dev`

webpack.config.js
```
const path = require("path");

module.exports = {
    mode: 'development',
    entry: "./src/js/index.js",
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: "app.bundle.js"
    },
    devtool: 'inline-source-map',
    module: {
        rules: [
            {test: /\.css$/, use: ['style-loader', 'css-loader']}
        ]
    }
}
```

which lets me, in index.js
```
import '../css/index.css'
```

meaning, in my  layout.njk I can remove the
``` 
<link rel="stylesheet" src="./css/index.css">
```

and make the following .eleventy.js changes
```
   // not needed anymore since the css is part of webpack bundle
   // eleventyConfig.addWatchTarget("src/css/*.css");
   // eleventyConfig.addPassthroughCopy({"src/css": "."})

    // simply look for changes in the webpack app bundle and copy to output dir
    eleventyConfig.addWatchTarget("dist/*.js");
    eleventyConfig.addPassthroughCopy({'dist': '.'});
```

and finally, change the scripts in package.json
```
  "scripts": {
    "build": "webpack && eleventy",
    "start": "concurrently \"webpack --watch\" \"eleventy --serve\""
  },
```

I know this is a rather primitive webpack setup, as it's hardcoded for 'development', but it displays having eleventy watching for changes to my app bundle and doing a pass-through copy of it, and thanks to `concurrently` , `eleventy -serve` is picking up changes from `webpack --watch`.

Anyway, I think it would be great if the docs got updated regarding client-side js, as I *imagine* I'm not the only one confused, and I would be curious to see what *better* solution(s) might be.

**Comment by Ryuno-Ki** [comment]
Thanks!
I was having a similar issue yesterday (with `window` being undefined) and have a pointer now, where to look for the root cause (since it's a static JS file meant to be only copied).

**Comment by Ryuno-Ki** [comment]
Hm, just took the time to take a look at [addPassthroughCopy](https://www.11ty.dev/docs/copy/) (which I hadn't used before), but I can still see the same error. Will need to take some more time to dig deeper :-(

**Comment by tannerdolby** [comment]
I might be a bit late on this. But I tried including client-side JavaScript `document.querySelector()` inside `.eleventy.js` and received the same error: `ReferenceError: document is not defined`. This issue (#902) references using --serve and --watch but my comment mainly addresses quickly developing with client-side JavaScript.

I've spent many hours reading through [11ty documentation](https://www.11ty.dev/docs/) for various things while building sites, and the one concept that's not super clear for new users in the current documentation is how to use client-side JavaScript files.

Here is the way I included my JavaScript file `site.js` that uses `document.querySelector()` which requires access to [Document](https://developer.mozilla.org/en-US/docs/Web/API/Document) interface.

Project structure:
```
src/
    _data/
        ...
    _includes/layouts/
        base.njk
        ...
    css/
        style.css
    images/
        ...
    js/
        site.js
.eleventy.js
package.json
```

1. Add the folder containing client-side js to your site's output by using [Manual Passthrough File Copy](https://www.11ty.dev/docs/copy/#manual-passthrough-file-copy-(faster)) inside `.eleventy.js`.
```
eleventyConfig.addPassthroughCopy("src/js"); // Copies the src/js/ directory to sites output (_site)
```
2. Add the `<script>` element into whichever template you need, I want to use client-side js (toggling a class) on elements from the `base.njk` layout so I add mine there.
```
        ...
    </body>
    <script src="/js/site.js" type="text/javascript"></script>
</html>
```
And voila! The added `<script>` element gives `base.njk` access to the code inside `site.js`. This might not be the *right* way but it is a method I'm currently using so if anyone has better solutions please share.

**Comment by ckot** [comment]
@tannerdolby thanks!  sorry I didn't notice this until now.

**Comment by tannerdolby** [comment]
@zachleat || @binyamin I think this can be closed now. One less issue in the tracker!
