### ISSUE TITLE
Default cli command doesn't exit on finish, so next commands not executed

### ISSUE THREAD

**Issue by mchepurnoy** [11ty/eleventy#904]
**Describe the bug**
First of all, I would like to thank you for building such a great tool for ssg. 
When I run default cli command `npx @11ty/eleventy` it doesn't finish on exit. For example if I want to run some command after building my site, I had to exit with cmd+c and run another command. 
Maybe there is some cli parameter that can do this? I couldn't find it in the documentation.

**To Reproduce**

1. Execute `npx @11ty/eleventy && echo 'Site is build'`
2. Site is build correctly
3. Echo command would be never executed

**Expected behavior**
Command should print out 'Site is build'

**Screenshots**
<img width="419" alt="image" src="https://user-images.githubusercontent.com/5318490/73918337-83cfff00-48d2-11ea-91e6-ae18745c99e4.png">

**Environment:**

- OS and Version: macOS Catalina version 10.15.2
- Eleventy Version 0.10.0

**Comment by scottishstoater** [comment]
Hey @mchepurnoy,

I have a similar set up and I ran the command you shared on my project and it worked as you intended, for me. The default eleventy command with no flags builds the site and exits, you'd need to add the `--watch` or `---serve` flags for it to continue running waiting on a manual exit (`cmd+c`).

Do you have the source on a public repo?  I suspect this problem could have something to do with your local set up. It would be good to isloate to problem to either a project level (something in your project config) or machine level (something in computer environment setup) so we can get you back on track.

Output for me:
![2020-02-06 09 37 43](https://user-images.githubusercontent.com/6320793/73924464-76ac1380-48c4-11ea-8c68-a9995917e51a.gif)

**Comment by mchepurnoy** [comment]
Hello @scottishstoater,

Thanks for your response. 
It seems indeed problem in my setup. Specifically in node.js version. (12.3.1)

I tried new setup on different version of node.js 10.13.0 and it worked as you mentioned.

**Comment by peterwgnd** [comment]
@mchepurnoy wondering if you could give a bit more detail on your fix. Running into the same issue. Get this log in the terminal "Copied 22 files / Wrote 10 files in 0.37 seconds (37.0ms each, v0.11.0)" everything in my dist folder is built correctly, but build command never exits without a Ctrl+C. Down graded my node version to 10.13.0 using NVM, but still having the same problem.

**Comment by FinlayDaG33k** [comment]
This issue is sadly still a thing using Docker (`node:10`, `node:12` and `node:14`).
![image](https://user-images.githubusercontent.com/13424273/92703132-3e851b80-f352-11ea-90f0-50faf1612559.png)

**Comment by brianfryer** [comment]
I'm also experiencing this exact issue. When I run the `eleventy` command, the build process never finishes (which blocks deployment to Netlify).

I've tried different versions of `node` (`10.13.0`, `11.15.0`, `15.6.0`) but the issue remains regardless of environment.

**Comment by pdehaan** [comment]
@brianfryer Is your 11ty site on GitHub? Curious if it will work on my machine or if there is maybe any interesting debug messages which might point to the issue.
