### ISSUE TITLE
pagination before function

### ISSUE THREAD

**Issue by mvolkmann** [11ty/eleventy#917]
**Describe the bug**
I can't get an example of using the `before` function to work.

**To Reproduce**

1. Add the following in the front matter of any page that currently uses pagination: `before: function (data) { return data; }`
2. See error in terminal that says " SyntaxError: Unexpected token ':'"
3. Remove the `before` front matter and see that the error goes away.

**Expected behavior**
This particular `before` function should have no effect.

- OS and Version: macOS 10.15.1
- Eleventy Version 0.10.0

**Comment by mvolkmann** [comment]
I suspect part of the issue is whether the front matter needs to being with `---js` when using `before`. Is that required?

**Comment by mvolkmann** [comment]
I got it working! IIUC, in order to use `before` all the front matter must be converted from YAML to JavaScript and it must start with `---js`. Is this correct?

**Comment by pdehaan** [comment]
I believe that is correct, per https://www.11ty.dev/docs/pagination/#the-before-callback example (and https://www.11ty.dev/docs/data-frontmatter/#javascript-front-matter and to a lesser degree, the gray-matter example at https://github.com/jonschlinkert/gray-matter/blob/master/examples/javascript.js).

I don't think JSON, YAML, or TOML support functions, so it makes sense that it is only supported for JavaScript front matter.

**Comment by zachleat** [comment]
Theoretically it should also work with JS data files too and any format that allows JS functions
