### ISSUE TITLE
moving toward a 1.0 release

### ISSUE THREAD

**Issue by mvolkmann** [11ty/eleventy#921]
I'm wondering what remains to be done before a version 1.0 of 11ty can be released.
I have a few suggestions.

1. It seems to me that Nunjucks is a better version of Liquid. The syntax is mostly the same. I'd like to see Nunjucks become the default templating language in 1.0.
1. In the spirit of more consistent naming, I'd like for "eleventy" to be replaced by "11ty" wherever possible. Could the configuration file be renamed from ".eleventy.js" to ".11ty.js" or even "11ty.js" so it isn't a hidden file?
1. Perhaps the duplicate data in the pagination object should be removed and the newer, shorter property names should be retained.
1. These issues and perhaps others may need to be addressed: https://github.com/11ty/eleventy/issues/919, https://github.com/11ty/eleventy/issues/915

I'm sure others can think of additional changes they would like to see before 1.0.

**Comment by octoxalis** [comment]
To go a bit further, I would say that the documentation should be **standardized** giving the precedence to Nunjucks **and** JavaScript.

We are evolving in the Node context, the real strength of 11ty, and JavaScript should have the precedence over YAML ot TOML which, IMHO, are much less powerful than JS for front matter declarations.

**Comment by Ryuno-Ki** [comment]
Keep in mind, that many people migrated over from Jekyll and GH Pages. So supporting Liquid and YAML have their merits.

**Comment by Ryuno-Ki** [comment]
Personally I'd like to see proper code documentation before a 1.0 release (willing to fill PRs for that).

**Comment by mvolkmann** [comment]
I would never advocate for removing support for Liquid, YAML, or any other syntax that is currently supported. I think 11ty’s support for a wide variety of syntaxes is an important differentiator from other SSGs. For example, choosing an SSG that requires authors to know frameworks like React or Vue, or know programming languages that are not widely used (like Go) seems like a bad idea to me because it limits the number of people that will be able to help maintain the site.

**Comment by octoxalis** [comment]
Of course removing support for Liquid or YAML would be silly.

However, I'd like to rely on a **reference documentation** and JavaScript is therefore the best candidate: every 11ty developer is supposed to know it.

**Comment by reubenlillie** [comment]
I agree about adding more JavaScript examples to the documentation. I've built my site (https://gitlab.com/reubenlillie/reubenlillie.com) with *.11ty.js templates only. I think the exercise of adding JS to the docs would also help the up some loose ends, for example, #642 (still my _only_ line liquid/nunjucks in any of my 11ty projects). And, before 0.1.0, it'd probably be a good idea to have more thorough tutorials and/or a suite of templates/themes.

**Comment by pdehaan** [comment]
> . I've built my site ([gitlab.com/reubenlillie/reubenlillie.com](https://gitlab.com/reubenlillie/reubenlillie.com)) with *.11ty.js templates only.

@reubenlillie That is some of the most beautifully documented code I've ever seen. Thanks!
Very interesting use of 11ty.js templates for layouts, etc. :+1:

**Comment by reubenlillie** [comment]
> @reubenlillie That is some of the most beautifully documented code I've ever seen. 

Aw, shucks! Thanks, @pdehaan.

**Comment by octoxalis** [comment]
For those who want JavaScript examples of 11ty use, have a look at my [11tyTips](https://11tytips.netlify.com) site and its "frame" companion [11tyFrame](https://11tyframe.netlify.com): all code is in Github repositories.Some tips still in progress, but hoping it can help...

**Comment by octoxalis** [comment]
@reubenlillie : I like the main site, however font size looks strangely large on my  (27", 4K) desktop screen and Github page too tiny.

**Comment by reubenlillie** [comment]
> I like the main site, however font size looks strangely large on my (27", 4K) desktop screen and Github page too tiny.

Thanks, @octoxalis. That's helpful feedback. So this thread can stay on topic, I'm happy to discuss possible tweaks in the site repo: https://gitlab.com/reubenlillie/reubenlillie.com/.

**Comment by PierBover** [comment]
> In the spirit of more consistent naming, I'd like for "eleventy" to be replaced by "11ty" wherever possible.

Personally I prefer "eleventy" as it's just the natural and obvious way to write it. "11ty" seems witty at first but it's not practical IMO (other than in the logo).

Anyway, I think consistency is more important than personal preferences and everything (config file, template files, etc) should be one or the other.

> Could the configuration file be renamed from ".eleventy.js" to ".11ty.js" or even "11ty.js" so it isn't a hidden file?

Event better `eleventy.config.js`.

**Comment by zachleat** [comment]
Note that I’d like to move away from a big issue here into individual ones, if possible.

We do have a project going here for Eleventy 1.0 https://github.com/orgs/11ty/projects/5

**Comment by zachleat** [comment]
Hey y’all—we’re getting much closer to a 1.0 so I’m trying to organize the feedback here:

> It seems to me that Nunjucks is a better version of Liquid. The syntax is mostly the same. I'd like to see Nunjucks become the default templating language in 1.0.

Sorry the default change here is probably not going to happen. This would cause me a lot of support burden 😅

> In the spirit of more consistent naming, I'd like for "eleventy" to be replaced by "11ty" wherever possible. Could the configuration file be renamed from ".eleventy.js" to ".11ty.js" or even "11ty.js" so it isn't a hidden file?

11ty is the org and eleventy is the software. I know that’s confusing. In retrospect it may have been nicer to use `11ty/11ty` but I didn’t 😅. The addition of more default config locations is filed here https://github.com/11ty/eleventy/issues/1029

> Perhaps the duplicate data in the pagination object should be removed and the newer, shorter property names should be retained.

I’d say this is low priority right now too. I did clean up the docs a bit to focus on the new stuff.

> These issues and perhaps others may need to be addressed: excessive calls to .11tydata.js functions with pagination #919, data cascade precedence not matching docs #915

Those are both still in scope for 1.0, yep.

Going to close this as I think we’ve either addressed all the points or have other issues for the remaining points. Thanks y’all!
