### ISSUE TITLE
Document getFilteredByGlob only working with supported extensions

### ISSUE THREAD

**Issue by cfjedimaster** [11ty/eleventy#925]
I'm working on workarounds to #117 and wanted to use the Collections API as a way to handle it. My thought was - use `collection.getFilteredByGlob` to find `mjml` files. I was going to process them in the addCollection function to change their data to plain HTML. However, getFilteredByGlob seems to ignore extensions Eleventy doesn't support. It's probably obvious, but I'd document this.

**Comment by zachleat** [comment]
The blue warning box does document this behavior but it could be made more explicit to this specific issue: https://www.11ty.dev/docs/collections/#getfilteredbyglob(-glob-) Happy to entertain a PR here

**Comment by cfjedimaster** [comment]
I filed a PR. :)

**Comment by cfjedimaster** [comment]
When I filed the PR, I wrote, "Addresses #925" - which I thought would auto link it.

**Comment by zachleat** [comment]
They’re different repos, NBD

**Comment by zachleat** [comment]
Closed by https://github.com/11ty/11ty-website/pull/296
