### ISSUE TITLE
Lifecycle explained

### ISSUE THREAD

**Issue by dgrammatiko** [11ty/eleventy#926]
Eleventy is great, though some functionality (from a developer point of view) is left to be discovered by debugging the app itself. This is quite a tedious task and it would be far easier if there was a section in the docs explaining the lifecycle of eleventy (hooks, events, etc).

**Comment by felipeqq2** [comment]
I second this, 11ty's documentation is really poor about it;

**Comment by zachleat** [comment]
We do have a order of operations page in the docs: https://www.11ty.dev/docs/advanced-order/

**Comment by dgrammatiko** [comment]
That will do it for me, thanks @zachleat
