### ISSUE TITLE
shortcodes and SVG

### ISSUE THREAD

**Issue by mvolkmann** [11ty/eleventy#928]
Can anyone see a reason why this shortcode would render the HTML text instead of the actual SVG?
If I use the commented out return instead of the one that returns the SVG string, it just renders "TEST".

```js
  eleventyConfig.addShortcode(
    'circle',
    (radius, bgColor = 'black', strokeWidth = 0, stroke = 'black') => {
      const halfStrokeWidth = strokeWidth / 2;
      const diameter = radius * 2;
      const size = diameter + strokeWidth;

      //return `<div>TEST</div>`;
      return `
        <svg
          style="height: ${size}px; width: ${size}px"
          viewBox="0 0 ${size} ${size}"
          xmlns="http://www.w3.org/2000/svg">
          <circle
            cx="${radius + halfStrokeWidth}"
            cy="${radius + halfStrokeWidth}"
            fill="${bgColor}"
            stroke="${stroke}"
            stroke-width="${strokeWidth}"
            r="${radius}" />
        </svg>
      `;
    }
  );
```

Here is how I use it:

```njk
{% circle 50, 'yellow', 10, 'blue' %}
```

**Comment by pdehaan** [comment]
Works for me<sup>(tm)</sup>.

HTML in my generated index.html is:

```html
        <svg
          style="height: 110px; width: 110px"
          viewBox="0 0 110 110"
          xmlns="http://www.w3.org/2000/svg">
          <circle
            cx="55"
            cy="55"
            fill="yellow"
            stroke="blue"
            stroke-width="10"
            r="50" />
        </svg>
```

localhost:8080 totally lookin' like:

![localhost_8080](https://user-images.githubusercontent.com/557895/74302912-f7c43a00-4d0c-11ea-95bf-d501cd2c3e6a.png)

Wondering if somewhere in your templates you're missing a `| safe ` and it's escaping the tags.

**Comment by mvolkmann** [comment]
That can't be the issue because if I replace what I'm returning from the shortcode with the following, it outputs "TEST" in red. Something is causing it to not process SVG.

```js
      return `<div style="color: red">TEST</div>`;
```

**Comment by mvolkmann** [comment]
I created a minimal GitHub repo that demonstrates the issue.
See https://github.com/mvolkmann/11ty-svg-issue.

**Comment by octoxalis** [comment]
Could be a server issue not an 11ty issue. I had similar problems with VS Code Live server truncating inlined SVG. Your code looks correct.

**Comment by zachleat** [comment]
I'm pretty sure this is the markdown code blocks thing that keeps cropping up

https://www.11ty.dev/docs/languages/markdown/#there-are-extra-and-in-my-output

**Comment by mvolkmann** [comment]
@zachleat Right you are! All I had to do to fix it was remove the whitespace before `<svg` in the string I return from `.eleventy.js`!
