### ISSUE TITLE
Permalink attribute adds erroneous <p> tags to path

### ISSUE THREAD

**Issue by philhawksworth** [11ty/eleventy#93]
When specifying the permalink for a file via either the front matter or via the folder json config, the path generated is wrapped in an undesired `<p>` tag.

```
---
title: "My test file"
permalink: "/news/{{ title | slug }}/index.html"
---
```

Yielding the following log output when the build runs (where `src/sites` and `dist` are my input and output directories):
```
writing dist/<p>/news/my-test-file/index.html</p> from ./src/site/news/my-test-file.md.
```

This also happens if the nunjucks templating expression is omitted and a string is used on its own like so:

```
---
title: "My test file"
permalink: "/news/my-test-file/index.html"
---
```

- Eleventy version: 0.3.0
- my other config related to templating: 
```
    templateFormats : ["njk", "md"],
    htmlTemplateEngine : "njk",
    markdownTemplateEngine : "njk"
```

**Comment by zachleat** [comment]
@philhawksworth Any templateEngineOverride’s in play here?

**Comment by zachleat** [comment]
I can reproduce this with `templateEngineOverride` and given our previous discussions gonna assume the answer is yes

**Comment by philhawksworth** [comment]
Yes there are templateEngineOverrides in play:

`"templateEngineOverride": "njk,md" `
