### ISSUE TITLE
JavaScript functions not applied to top level function 11ty.js templates using an arrow function

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#934]
Works:
```
module.exports = function({ name }) {
  return `<p>${this.upper(name)}</p>`;
};
```

Broken:
```
module.exports = ({ name }) => {
  return `<p>${this.upper(name)}</p>`;
};
```

Can’t find `this.upper`.

**Comment by zachleat** [comment]
Agree with myself from 30 minutes ago that this is pretty confusing but also it is correct JavaScript behavior, specifically with `this` and arrow functions. I’ll leave this open as we may have a nicer solution later. Definitely need to add docs around this.

**Comment by zachleat** [comment]
Relevant MDN sections:

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#No_separate_this
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Invoked_through_call_or_apply

**Comment by pdehaan** [comment]
Re: original comment... both snippets look the same to me.
Was one of them supposed to use the `function` syntax, or am I missing something?

**Comment by zachleat** [comment]
@pdehaan Ah, yep sorry—fixed now!

**Comment by zachleat** [comment]
Warning added here https://www.11ty.dev/docs/languages/javascript/#warning-about-arrow-functions

**Comment by zachleat** [comment]
Closing this as a documentation/education issue. I don’t think there is a good way forward here to smooth this over. Sorry, past me.
