### ISSUE TITLE
`renderData` only works on paginated templates

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#941]
After some investigation into implementing #481 it should be noted that for some time the undocumented `renderData` feature has only been available on pagination templates.

Not really sure how to handle this. `renderData` has always been a bit discouraged but I know a fair number of people have used it. We did have tests around it but they weren’t quite high level enough to catch it.

Ideally this would be fixed and its use still discouraged as #481 will be the preferred method going forward.

**Comment by crtr0** [comment]
Does that mean #481 will be re-opened? What's the best way to get notified once this issue is addressed?

**Comment by zachleat** [comment]
#481 is not off the table! Make sure you read this comment carefully https://github.com/11ty/eleventy/issues/481#issuecomment-481516829

The overarching project is managed here https://github.com/11ty/eleventy/projects/1

**Comment by zachleat** [comment]
(I am actively working on this feature for a project)

**Comment by zachleat** [comment]
The fix for `renderData` is shipping with the next minor version
