### ISSUE TITLE
Is there a way to use shortcodes in markdown files?

### ISSUE THREAD

**Issue by PierBover** [11ty/eleventy#944]

**Comment by mvolkmann** [comment]
I'm fairly new to 11ty, but I think you can if you use a template language like Nunjucks or Liquid.
Add this to the front matter in the Markdown file:

```yaml
templateEngineOverride: njk,md
```
Then you should be able to use shortcodes you have defined like this where "dog" the name of a shortcode that takes breed and name arguments.

```njk
{% dog "Whippet", "Dasher" %}
```

**Comment by PierBover** [comment]
Thanks @mvolkmann !

It seems you are right: https://www.11ty.dev/docs/languages/

I will try and report back later.

**Comment by pdehaan** [comment]
Per https://www.11ty.dev/docs/languages/markdown/

> _<q>Markdown files are by default pre-processed as Liquid templates. [You can change this default in your configuration file](https://www.11ty.dev/docs/config/#default-template-engine-for-markdown-files) (or disable it altogether). To change this for a single template and not globally, read [Changing a Template’s Rendering Engine](https://www.11ty.dev/docs/languages/).</q>_

**Comment by PierBover** [comment]
Thanks @pdehaan I think that solves it.
