### ISSUE TITLE
JavaScriptTemplateInvalidDataFormatError: Invalid data format returned

### ISSUE THREAD

**Issue by gabbersepp** [11ty/eleventy#945]
**Describe the bug**
I have several small projects built with eleventy. Suddenly some of them doesn't work anmore. If I run `eleventy` (w/o `--serve`) I get following error:

![image](https://user-images.githubusercontent.com/3234900/74730755-03e95380-5247-11ea-926f-1421c6753a1d.png)

I tried to reproduce it:
+ new folder
+ npm init
+ npm install -D @11ty/eleventy
+ add "eleventy" script to package.json
+ run "npm run 11ty"
+ --> works

If I then copy the package.json, package-lock.json from one of the failing projects, I suddenly get this error. Both files are equal.
I have now following files:

![image](https://user-images.githubusercontent.com/3234900/74730908-4ad74900-5247-11ea-8053-cefca0013aac.png)

I really have no idea where this comes from. I can build another project with exactly the same version (0.10.0) on the same machine.
**Environment:**

- Win10 64Bit
- 0.10.0

**Comment by gabbersepp** [comment]
I found a solution: It turns out that eleventy did not recognize the `index.njk` in the root directory. Instead it tries to read all MD files from node_modules. After moving the file into `/views` and providing a custom eleventy config, the error went away. No idea why this worked initially

**Comment by salemhilal** [comment]
I had the same issue. I added 11ty to [this project](https://github.com/salemhilal/salemhilal.github.io/) as-is and it failed, but deleting `index.html` caused it to build `README.md` as expected. At the very least, this seems like an opportunity for some better error handling — can this issue be reopened?

**Comment by gabbersepp** [comment]
@salemhilal I reopened it. You are right. Maybe there can be build a better error handling

**Comment by zachleat** [comment]
Fixed by #383, which shipped with 1.0.0
