### ISSUE TITLE
Slugify filter function isn't working

### ISSUE THREAD

**Issue by ericwbailey** [11ty/eleventy#946]
**Describe the bug**
I'm attempting to create a custom filter function to create slugs that remove special characters. The filter is a direct copy from [this repo's `.eleventy.js`](https://github.com/danurbanowicz/eleventy-netlify-boilerplate/blob/master/.eleventy.js#L59) file, following [the conversations in this issue](https://github.com/11ty/eleventy/issues/278).

**To Reproduce**
I have the following filter in my `.eleventy.js` file:

```
  eleventyConfig.addFilter("slugify", function (str) {
    return slugify(str, {
      lower: true,
      replacement: "-",
      remove: /[*+~.·,()'"`´%!?¿:@]/g
    });
  });
```

When trying to slugify a string, I get a the following error:

```
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering njk template ./src/archive.njk

`TemplateContentRenderError` was thrown
> (./src/archive.njk)
  ReferenceError: slugify is not defined
```
A full copy of my `.eleventy.js` is available as [a gist](https://gist.github.com/ericwbailey/2507b3102ae3b6340b750aa591050a39).

**Expected behavior**
Slugify should remove special characters, so a string reading `"Dogs: They're really great!"` gets turned into `dogs-theyre-really-great`.

**Environment:**

- macOS Catalina 10.15.3
- Node v10.14.2
- Eleventy version 0.10.0

And thanks for taking a look!

**Comment by pdehaan** [comment]
You need to do `const slugify = require("slugify");` at the top of your config file.

**Comment by ericwbailey** [comment]
Oh my god 😅

Worked like a charm. Thank you!
