### ISSUE TITLE
TOML | YAML | JSON Configuration in addition to .eleventy.js to make it friendly to non technical users

### ISSUE THREAD

**Issue by sirinath** [11ty/eleventy#956]
Though 11ty holds out to be simpler static generator the configuration is more verbose and complicated. Since many templates are supported in 11ty maybe the same can be done for configuration so the configuration or a large part of the configuration is accessible to non-technical users also.

Other tools like Hugo TOML, YAML & JSON Configuration. So maybe 11ty can also do the same. This would simplify:

```
module.exports = function(eleventyConfig) {
  // Add a filter using the Config API
  eleventyConfig.addFilter( "myFilter", function() {});

  // You can return your Config object (optional).
  return {
    dir: {
      input: "views",
      output: "dist"
    }
  };
};
```

into

```
filer:
  - name: myFilter
  - function: none

dir:
  - input: "views",
  - output: "dist"
```

Which is more readable, user-friendly and concise.

If multiple configuration files are present then the options in them can be merged in priority order with `.eleventy.js` having the highest priority or by the date modified of the configuration files in case there are conflicting options. 

In case of internal or common filters, another option is to thing through the above a step further so that JavaScript functions may not be needed for configuration. This way accidentally mutating internal data structures also may not happen.

**Comment by zachleat** [comment]
Ah, no sorry unfortunately this is not on the table for this project. Normally I would place things into the queue but I need to say no to this one.

Using TOML/YAML/JSON for configuration would be an incredibly leaky abstraction and would lose a lot of power when using those methods. I’m trying to move away from the declarative return object for configuration and towards configuration API methods, which offer more power.
