### ISSUE TITLE
Fresh install errors - possibly due to core-js@2.6.11

### ISSUE THREAD

**Issue by StarfallProjects** [11ty/eleventy#958]
**Describe the bug**
Trying to do a fresh local install of 11ty for a new project, getting errors on install. Installation does not complete (11ty doesn't end up listed in the `package.json`, and doesn't run)

**To Reproduce**

1. Run `npm install --save-dev @11ty/eleventy`
2. See it throw an error:
```
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn =
npm ERR! file =
npm ERR! path =
npm ERR! errno ENOENT
npm ERR! core-js@2.6.11 postinstall: `node -e "try{require('./postinstall')}catch(e){}"`
npm ERR! spawn = ENOENT
npm ERR!
npm ERR! Failed at the core-js@2.6.11 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

3. Try to run with `npx @11ty/eleventy` (just in case it's an ignorable error)
4. See it throw another error:
```
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'C:\Users\debor\Desktop\Code\habermas-terminology\node_modules\@11ty\eleventy\cmd.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Environment:**

- Windows 10, PowerShell
- latest on npm (as of 22nd Feb 2020)

**Other**
Note that the installation also warns that core-js@2.6.11 is no longer maintained and should be upgraded to 3.x

**Comment by zachleat** [comment]
What’s your `node --version`?

**Comment by StarfallProjects** [comment]
12.15.0

**Comment by StarfallProjects** [comment]
Up upgraded to 12.16.1 (the current LTS: https://nodejs.org/en/) and still get the same error.

**Comment by DirtyF** [comment]
Not reproduced on latest macOS with current LTS node:

```
volta install @11ty/eleventy@latest
success: installed @11ty/eleventy@0.10.0 with executables: eleventy
```

**Comment by StarfallProjects** [comment]
Still having the errors today, so went and tried on Ubuntu via WSL. Node 12.6.1, latest 11ty, and it installed and ran, albeit with quite a few warnings. No errors though.

It looks like somehow Windows/Node on Windows is being more sensitive about the outdated corejs?

**Comment by StarfallProjects** [comment]
Tried it on Windows with Git Bash today (in case it was Powershell being a pain) and still had the errors.

**Comment by pdehaan** [comment]
I wonder if this is related to https://github.com/zloirock/core-js/issues/582

**Comment by StarfallProjects** [comment]
@pdehaan that looks like a Powershell issue? Would it explain seeing it in git bash as well?

**Comment by zachleat** [comment]
@StarfallProjects okay to close as issue in dependency?

**Comment by StarfallProjects** [comment]
@zachleat yes - thanks for the community help on this! I guess I am once again the PowerShell-shaped canary in the coalmine 🤦‍♀

**Comment by zachleat** [comment]
Thank you!
