### ISSUE TITLE
Access to currently running domain

### ISSUE THREAD

**Issue by cfjedimaster** [11ty/eleventy#965]
While we have access to env variables, it would be nice if we could get access to domain specific values like the current running host and port. While you can get by without this using env variables (if env === 'prod' then my url must be foo.com), I think it could still be useful to have access to.

**Comment by ogdenstudios** [comment]
Where do you need this? On the client side? Or in the server? 

You can grab some useful information from regular ol' DOM APIs on client side. Here's a [SO post about getting the host url from the DOM](https://stackoverflow.com/questions/6042007/how-to-get-the-host-url-using-javascript-from-the-current-page) that might be useful.

**Comment by cfjedimaster** [comment]
I was imagining server-side. It's definitely available client-side.

**Comment by ogdenstudios** [comment]
Have you considered something like [path-prefix](https://www.11ty.dev/docs/config/#deploy-to-a-subdirectory-with-a-path-prefix) or some kind of global data variable that you can set at build time? Since Eleventy is an SSG, it's not going to generate server responses like server-side rendering might. This seems like something you could do with a command or env variable at build time.

**Comment by cfjedimaster** [comment]
Right, it _can_ be done now. I definitely acknowledge that. And I know it would only be available at build time, ie it wouldn't be dynamic in the build results. I'm just saying it could be handy to be able to access these values.

**Comment by zachleat** [comment]
I’m a bit confused what this means? I understand that you’d want to find the `host` but I’m not sure there is a way to do this without proprietary hooks into web servers or application servers that is probably outside the realm of what we want to dip into.

**Comment by cfjedimaster** [comment]
I had imagined we could have access to something like a request object, but... yeah. The more I think about this the more I feel like it's not a good idea. My attempt here was to help out SO questioner (https://stackoverflow.com/questions/60309000/generating-full-urls-on-eleventy-and-netlify/60401857?noredirect=1#comment106866809_60401857), but I think we can do without. Thanks for hearing me out!

**Comment by Ryuno-Ki** [comment]
Thinking about it …
When I build on one server and deploy it to another one (think CI/CD and CDN system), then the host which builds the file would not be the same as the one serving them …
So I'd go with an environment variable for the build system, which contains information about the target one.
