### ISSUE TITLE
Occasional stdout maxBuffer length exceeded

### ISSUE THREAD

**Issue by aaronshekey** [11ty/eleventy#978]
When building [Stacks](https://stackoverflow.design), our devs are intermittently getting

``` bash
Warning: stdout maxBuffer length exceeded Use --force to continue
Aborted due to warnings.
```

It's not every build, so it's tough to isolate. Has anyone else seen this in their builds?

**Environment:**
- OS and Version: MacOS 10.15.3
- Eleventy Version: 0.10.0

**Comment by zachleat** [comment]
Haven’t seen any other reports of this one, years later. Sorry, I’m going to close this one as stale!
