### ISSUE TITLE
Access to .eleventy.js variables from .11ty.js templates

### ISSUE THREAD

**Issue by brycewray** [11ty/eleventy#979]
Have been studying the excellent all-JavaScript (all-`.11ty.js`) templating done by Reuben Lillie in [his site](https://reubenlillie.com) [GitLab repo](https://gitlab.com/reubenlillie/reubenlillie.com), as recently mentioned on the Eleventy Twitter feed. I set up a small (so far, local-only) repo with only `.11ty.js` templates and began tinkering. I soon saw that `const`s created within `.eleventy.js` weren't "visible" through the .11ty.js template — ***e.g.*** (and this goes back to [Pascal Widdershoven's solution to the "previous/next" thing](https://github.com/11ty/eleventy/issues/529#issuecomment-568257426), even though I know that another method for this is coming soon in 0.11.0):
```
// from .eleventy.js

  eleventyConfig.addCollection("posts", function(collection) {
    const coll = collection.getFilteredByTag("post")

    for(let i = 0; i < coll.length; i++) {
      const prevPost = coll[i-1]
      const nextPost = coll[i+1]

      coll[i].data["prevPost"] = prevPost
      coll[i].data["nextPost"] = nextPost
    }

    return coll;
  })
```
... works in my usual site's Nunjucks-based single-post template just fine, but when I try to access either of the resulting `const`s in a similar .11ty.js template like so ...

```
// from an .11ty.js template file

  ${data.title != "The obligatory About Me page"
    ? `<div class="bg-dark">
    <h3 class="ctr wht"><a href="/posts" style="border-bottom: 0;">Other posts</a></h3>
    ${nextPost.url !== null
      ? `<p class="ctr">
        <strong>Next</strong>: 
        <a class="next" href=${nextPost.url}>${nextPost.data.title}</a>
      </p>`
      : ``
    }
    ${prevPost.url !== null
      ? `<p class="ctr">
        <strong>Previous</strong>: 
        <a class="previous" href=${prevPost.url}>${prevPost.data.title}</a>
      </p>`
      : ``
    }
    </div>`
    : ``
  }
`
```
... Eleventy gives me an error message to the effect that `nextPost` is undefined. (If, just for bleeps and giggles, I delete the reference to `nextPost`, the same occurs with `prevPost` as well. So, clearly, the `.11ty.js` template doesn't recognize these `.eleventy.js`-created `const`s.)

If this is a stupid question that is amply answered in the 11ty.dev docs, I apologize in advance, **but**: is there some extra heavy lifting, JS-wise, that an .11ty.js-based site must do to "see" `const`s and/or `var`s that are defined in `.eleventy.js`? Thanks in advance, even if the responder(s) will only be pointing out my inability to grasp something that's obvious to those who are more JS-savvy than I. :-) I just want to know.

**Comment by pdehaan** [comment]
I haven’t tried 11ty.js as a template yet, but I did notice you had `data.title`. Does it need to be `data.nextPost` as well?
Or do you have this in a GitHub repo or somewhere I can clone and take a look?

**Comment by brycewray** [comment]
@pdehaan I tried a variety of things so I don’t think it’s because of that (`data.nextPost` vs. `data.title`). As for the repo, I have just put it up at https://github.com/brycewray/eleventy_jst. Any/all help very welcome. Thanks!

**Comment by pdehaan** [comment]
```diff
diff --git a/src/_includes/layouts/posts/singlepost.11ty.js b/src/_includes/layouts/posts/singlepost.11ty.js
index 5838b25..0fb656d 100644
--- a/src/_includes/layouts/posts/singlepost.11ty.js
+++ b/src/_includes/layouts/posts/singlepost.11ty.js
@@ -45,17 +45,17 @@ exports.render = function (data) {
   ${data.title != "The obligatory About Me page"
     ? `<div class="bg-dark">
     <h3 class="ctr wht"><a href="/posts" style="border-bottom: 0;">Other posts</a></h3>
-    ${nextPost.url !== null
+    ${data.nextPost && data.nextPost.url !== null
       ? `<p class="ctr">
         <strong>Next</strong>:
-        <a class="next" href=${nextPost.url}>${nextPost.data.title}</a>
+        <a class="next" href=${data.nextPost.url}>${data.nextPost.data.title}</a>
       </p>`
       : ``
     }
-    ${prevPost.url !== null
+    ${data.prevPost && data.prevPost.url !== null
       ? `<p class="ctr">
         <strong>Previous</strong>:
-        <a class="previous" href=${prevPost.url}>${prevPost.data.title}</a>
+        <a class="previous" href=${data.prevPost.url}>${data.prevPost.data.title}</a>
       </p>`
       : ``
     }
```

Now, http://localhost:8081/posts/2018/09/why-finally-settled-ulysses/ shows a "Previous: HardyPress: WP + SSG with a twist" link at the bottom.

**Comment by brycewray** [comment]
@pdehaan thanks so much!
