### ISSUE TITLE
Custom ordering

### ISSUE THREAD

**Issue by bradfrost** [11ty/eleventy#981]
Hey all! Thanks for such a great tool.

I'm wondering how best to tackle custom ordering in Eleventy for a website that contains documentation that needs to be presented in a specific order. I've read [this page in the docs](https://www.11ty.dev/docs/collections/#sorting) but am still struggling with how to approach this.

My thought was to add an `order` bit to each doc page's frontmatter, like so:

```
---
title: Installing
category: getting-started
order: 10
---
```

I'd increment by to (`order: 20`, `order: 30`, and so on) to allow slots for any future documentation that would need to be wedged between two existing docs pages.

So my question is: how would I go about displaying that collection ordered by my custom `order` variable?

**Comment by pdehaan** [comment]
@bradfrost How about something like a custom collection with custom sorting, per  https://www.11ty.dev/docs/collections/#collection-api-methods (and scroll down to the "myCustomSort" example bit) and your metadata custom `order` value?

```js
module.exports = function(eleventyConfig) {
  // Sort with `Array.sort`
  eleventyConfig.addCollection("myCustomSort", function(collection) {
    return collection.getAll().sort(function(a, b) {
      return b.date - a.date;
    });
  });
};
```

Instead of the ambitious `.getAll()`, I'd probably use [`.getFilteredByTag()`](https://www.11ty.dev/docs/collections/#getfilteredbytag(-tagname-)) or [`.getFilteredByGlob()`](https://www.11ty.dev/docs/collections/#getfilteredbyglob(-glob-)), but like, whatever.

If you have a repo somewhere, I can take a look and try and do a PR and kick around some ideas.

**Comment by bradfrost** [comment]
@pdehaan Thanks for the speedy response! 

Yeah that function is exactly what I was looking at, but I'm a bit lost on how specifically I would call the `order` and then sort by that value.

**Comment by drubb** [comment]
Here's a similar example, extracting and sorting menu items from all posts:

```
eleventyConfig.addCollection("menuItems", collection =>
    collection
      .getAll()
      .filter(function(item) {
        return "menu" in item.data;
      })
      .sort((a, b) => {
        return (a.data.menu.order || 0) - (b.data.menu.order || 0);
      })
  );
```
The corresponding front matter:
```
menu:
  text: Location
  order: 3
```
In case the order isn't specified it defaults to zero.

**Comment by pdehaan** [comment]
@bradfrost A bit rough, but this might get you started: https://github.com/pdehaan/11ty-custom-collection-sort

But yeah, I didn't account for missing order fields like @drubb's example.

**Comment by pdehaan** [comment]
Added a ["beta" branch](https://github.com/pdehaan/11ty-custom-collection-sort/tree/beta) to my repo above which uses the beta 0.11 `getPreviousCollectionItem` and `getNextCollectionItem` filters: https://github.com/pdehaan/11ty-custom-collection-sort/tree/beta

Oddly, I only think the collection navigation items are available in liquidjs templates, So I had to switch from Nunjucks to Liquidjs. I filed a bug at https://github.com/11ty/eleventy/issues/983.

**Comment by zachleat** [comment]
Ah yep I think @pdehaan did it how I would have here:

```
eleventyConfig.addCollection("docs", collection => {
    const docs = collection.getFilteredByGlob("src/docs/*.njk")
      .sort((a, b) => {
        return Number(a.data.order) - Number(b.data.order);
      });
    return docs;
  });
```

via https://github.com/pdehaan/11ty-custom-collection-sort/blob/master/.eleventy.js

It’s also worth noting that I did write a Navigation plugin that solves this exact thing for you, docs for `order` are here: https://www.11ty.dev/docs/plugins/navigation/#re-ordering-items

**Comment by bradfrost** [comment]
Hey all, thanks for the input and help! I only now had time to go back and plug in these solutions and they work! Next up is getting the navigation plugin up and running since that seems like a more fleshed out solution. Appreciate it!

**Comment by oneezy** [comment]
> via https://github.com/pdehaan/11ty-custom-collection-sort/blob/master/.eleventy.js
> 
> It’s also worth noting that I did write a Navigation plugin that solves this exact thing for you, docs for `order` are here: https://www.11ty.dev/docs/plugins/navigation/#re-ordering-items

does the **navigationPlugin** also order pages?
