### ISSUE TITLE
getNextCollectionItem only available in Liquid templates?

### ISSUE THREAD

**Issue by pdehaan** [11ty/eleventy#983]
**Describe the bug**
I'm trying to use 0.11-beta.1 and having problems when using `getPreviousCollectionItem` and `getNextCollectionItem` filters in Nunjucks templates.

```js
---
layout: layouts/default.njk
---

{% set previousPost = collections.docs | getPreviousCollectionItem(page) %}
{% set nextPost = collections.docs | getNextCollectionItem(page) %}

<main data-order="{{ order }}">
  <header>
    <h1>{{ title }}</h1>
  </header>
  <section>{{ content | trim | safe }}</section>
  <nav>
  {% if previousPost %}Previous Blog Post: <a href="{{ previousPost.url }}">{{ previousPost.data.title }}</a>{% endif %}
  {% if nextPost %}Next Blog Post: <a href="{{ nextPost.url }}">{{ nextPost.data.title }}</a>{% endif %}
  </nav>
</main>
```

**To Reproduce**

1. Install beta 0.11 (<kbd>npm install @11ty/eleventy@beta -D</kbd>)
2. Try and use collection nav, per docs: https://www.11ty.dev/docs/filters/collection-items/
3. Build project via <kbd>npx eleventy</kbd>

**Expected behavior**
Should work in Nunjucks.

**Environment:**

- OS and Version: macOS Catalina
- Eleventy Version [via `eleventy --version` or `npx @11ty/eleventy --version`]: 0.11.0-beta.1

**Additional context**

Console log debugging the `eleventyConfig` param in my .eleventy.js config file:

```
  liquidFilters: {
    slug: [Function],
    url: [Function],
    log: [Function],
    getCollectionItem: [Function],
    getPreviousCollectionItem: [Function],
    getNextCollectionItem: [Function]
  },
  nunjucksFilters: { slug: [Function], url: [Function], log: [Function] },
  handlebarsHelpers: { slug: [Function], url: [Function], log: [Function] },
  javascriptFunctions: { slug: [Function], url: [Function], log: [Function] },
```

Per https://github.com/11ty/eleventy/blob/d8f941e0e4cf04d47f965d324f29c0683b549b85/config.js#L10-L18, it looks like we're explicitly only adding filters to Liquid engine.

**Comment by zachleat** [comment]
OH, uh… that was a silly oversight. Thanks for catching that!

**Comment by nhoizey** [comment]
Had the same issue, happy it has already been fixed… ;-)

@zachleat do you plan to release a second beta?

**Comment by gerwitz** [comment]
+1 for a beta release with this!
