### ISSUE TITLE
I wish 11ty had support for Textile (Markdown's friendly uncle)

### ISSUE THREAD

**Issue by whaleen** [11ty/eleventy#990]
**Describe the solution you'd like**
Same ability to compose content in .textile files as is possible in .md files.

**Describe alternatives you've considered**
I prefer Markdown myself but to pay respects to the late Dean Allen I believe all systems should support Textile. 

**Textile**
- [https://en.wikipedia.org/wiki/Textile_(markup_language)](https://en.wikipedia.org/wiki/Textile_(markup_language))
- [https://textile-lang.com/](https://textile-lang.com/)

**Comment by pdehaan** [comment]
Ref: #117

**Comment by zachleat** [comment]
@pdehaan is right this will likely be pushed into plugin land after #117 is released. But I’ll put it in the enhancement queue anyway.

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
We do want these to live in plugin land moving forward so I am removing this one from the enhancement queue.

https://www.11ty.dev/docs/languages/custom/

Note the specific sections on aliasing https://www.11ty.dev/docs/languages/custom/#aliasing-an-existing-template-language and overriding https://www.11ty.dev/docs/languages/custom/#overriding-a-built-in-template-language
