### ISSUE TITLE
How can I access data from a json file in my own javascript?

### ISSUE THREAD

**Issue by richcorbs** [11ty/eleventy#996]
I'm trying to use data from a json file in javascript on the page.

When I try to put my data into the javascript in the template (`{{ myData }}`) I get `[object Object]` which isn't what I'm trying to do.

**Comment by pdehaan** [comment]
@richcorbs I think that should be correct (you're trying to `.toString()` an object).

If you want to debug the object, in Nunjucks you can use the built-in `dump` filter (ie: `{{ myData | dump }}` or if you want it pretty printed, you can try `{{ myData | dump(2) }}`. I think Liquidjs _just_ added a similar `json` filter, but Eleventy is using a slightly older version of liquidjs at the moment. Or, the Eleventy 0.11 beta should have a fancy, new `log` filter which dumps the value to the terminal via `console.log()`, ie `{{ myData | log }}`.

But generally you'd use the properties directly, `{{ myData.name }}`, or you could loop over an array in your object, `{% for item in myData.items %}`, or whatever.

**Comment by richcorbs** [comment]
Thanks @pdehaan! That's perfect for my use case `{{ myData | dump | safe }}` worked perfectly!
