### ISSUE TITLE
Sort Custom Collections Randomly

### ISSUE THREAD

**Issue by scottwater** [11ty/eleventy#997]
Any suggestions for sorting a collection randomly?

I thought this would work:

```javascript
  eleventyConfig.addCollection("caps", collection => {
    return collection.getFilteredByTag("gmk").sort((a, b) => Math.random());
  });
```

But it is still sorting them alphabetically (no dates are available).

Thanks,
Scott

**Comment by pdehaan** [comment]
`Math.random()` returns a float between 0.0 and 1.0, so it probably won’t affect the default sort order. You could try something like subtracting 0.5 so you get a number between -0.5 and +0.5, per https://javascript.info/task/shuffle

Or, if you’re using nunjucks and want a single random element from an array/collection there is a `random` filter.

**Comment by scottwater** [comment]
That did the trick. Thanks for the tip and explanation.
